---
title: "Greek Art and Architecture (AMNE 376)"
toc: true
listing:
- id: amne376
  type: grid
  image-placeholder: placeholder_images/placeholder.png
  contents:
    - "../../docs/AMNE-376/notebook/amne376_image_embedding.qmd"
  categories: true
  fields: [image, title, date, description]
  sort-ui: [title, date]
---

This section contains material to support UBC's [Greek Art and Architecture (AMNE 376)](https://vancouver.calendar.ubc.ca/course-descriptions/subject/amnev).  The visual culture of the ancient Greek world in the second and first millennia BCE, especially from c. 1000 to 30 BCE. Credit will be granted for only one of CLST_V 331, AMNE_V 376 or ARTH_V 331. Equivalency: ARTH_V 331 or CLST_V 331. 

## AMNE 376: Suggested Lesson Plan

**80-minute lecture or 50-minute discussion on computer vision, image embedding, and their applications in Archaeology and Art History.**  
Agendas are provided for both lecture and discussion formats.

---

### Learning Objectives

By the end of this lesson, students will:

1. **Become familiar with concepts** such as computer vision, convolution, convolutional neural network (CNN), and image embeddings.
2. **Understand how computers "see"** and distinguish between different images by identifying unique visual elements and quantifying their similarity.
3. **Explore photographs of Kouroi** from Richter's "Kouroi: Archaic Greek Youths: a Study of the Development of the Kouros Type in Greek Sculpture (1942)" and create image embeddings for these photographs using pre-trained models.
4. **Learn how to cluster and classify Kouroi** based solely on photographs and critically analyze the advantages and limitations of these techniques and their potential applications in archaeology and art history.

---

### Materials and Technical Requirements

- **Jupyter notebook** (hosted on the prAxIs UBC website)
- Device with internet access (**laptop preferred**)
- No previous coding experience required (**familiarity with Python is an asset**)
- Students may pair up (groups of 2 or 3) if device access is limited
- **Group work is encouraged**; students will compare findings

---

### Pre-lesson Requirements

**Instructor should:**
- Test run the notebook using Jupyter Open and be familiar with the content.
- (Optionally) Instruct students how to run code on Jupyter Open if they are interested in exploring on their own.

**Students should:**
- Complete all required readings for "The Archaic World: Temples, Statues, and Colour".
- Browse the text explanations in the static notebook on the prAxIs UBC website.
- (If time permits) Browse through the notebooks on convolution and CNN.

---

## Agenda for the Lecture

If this format is chosen, students don’t have to run code themselves, but they may explore after class. Students should have access to image folders and interactive visualization objects.

1. **Pre-discussion and brief lecture** on Jupyter Notebook, introducing students to the programmatic environment (5–10 min)
2. **Introduction section and basics of convolution** (10 min)
3. **Dataset exploration, creation of embeddings, PCA visualization** and discussion about commonalities among clustered images (20 min)
4. **Introduce classification using image embeddings, evaluation of results, group activities** (try to classify yourself, strengths and limitations of classifier, etc.) (20 min)
5. **Lead discussion on machine learning applications in archaeology/art history** (formalism, relic restoration, the future of archaeology) (15 min)
6. **Conclusions and takeaways** (5–10 min)

---

## Agenda for the Discussion

If the discussion format is chosen, group activities are emphasized and all students should run the notebook code themselves.

1. **Before discussion:** Instructions on how to load/run code on Jupyter Open so students can explore immediately.
2. **Open the notebook; execute first two sections** and discuss computer vision and convolution (10 min)
3. **Execute Section 3, 4, 5; discuss observations** based on visualized image embeddings, commonalities among Kouros clusters (15 min)
4. **Try to classify materials/groups** of Kouroi based on images, check accuracy (5 min)
5. **Execute Section 6, discuss classifier quality, metrics, applications, and improvements** (15 min)
6. **Closing discussion** (5 min)

---

## Activity Materials

### In-Class Discussion Questions

- **Describe the differences and similarities** between how computers and humans identify similarity between two images.
- **Find photographs of Kouroi** that correspond to scatter plot points; discuss patterns among Kouroi that cluster together. What features do you think the embeddings captured?
- **Describe features that characterize a Kouros:** what would you focus on to classify their era or material based only on photos?
- **Discuss what different insights the CNN model may provide,** and what might be biased by the model itself.

---

### Discussion Post Questions

- **List some AI applications in archaeology/art history research.** Do you think any can be replaced by human labor?
- **Based on your knowledge of computer vision,** do you think CNN models can analyze objects more objectively? Why?
- **Discuss whether you would trust the use of AI** in the following for studying cultural relics/artifacts: style analysis, sentiment analysis, cultural relic restoration, age identification. Why?

---


# Modules

::: {#amne376}
:::
