---
format:
  html:
    embed-resources: true
    toc: false
---

AI is revolutionizing research in economics by enabling new ways of using data and by creating new models for studying economic phenomena.  Unfortunately, to many economics students, AI tools are magical "black boxes," disconnected from their economic training and broader educational experience. Economics students without computational or technical backgrounds are often not able to participate in computer science courses where AI tools are typically taught.  Additionally, when AI literacies are taught only in a computer science context, economics students may not understand how to apply these tools to economic applications.

This paper will discuss how educators can foster critical AI literacies and practical AI skills in economics, and show how disciplinary expertise can enhance the usefulness of AI and vice-versa.  Rather than the conventional use of AI as a writing assistant or personal tutor, it will show educators how to help students understand how AI can be used to address empirical problems within economics.  We will present a selection of classroom-tested examples of how AI models can be used in the students' disciplines to answer questions otherwise impossible, or very difficult, to address.  For example:

* In political economy, showing how word embeddings can be used to identify differences between the language used by autocratic and democratic leaders.
* In financial economics, showing how machine learning models can use textual analysis to predict stock price movements based on news articles.

These examples are illustrated using interactive Jupyter notebooks, which provide a user-friendly way to explore the tools for students.  All our resources are available as open educational resources (OERs) for attendees to adapt and use in their own classrooms.  We will also outline other available modules during the session, and discuss how existing (or future) modules can be used to meet specific learning objectives in economics classes.



