{
  "hash": "da3cb949c879302d150f4be287de74df",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Propensity Scores and Doubly-Robust Estimation\"\nauthor: Alex Ronczewski\ndate: 2026-06-19\ndescription: \"The sixth notebook in the Causal ML stream. We return to the 401(k) question and adjust for confounders a second way: by modelling who gets treated. We estimate the propensity score, reweight the data with inverse probability weighting, and combine the treatment model with the outcome model into the doubly-robust estimator\"\ncategories:\n  - Python\n  - machine learning\n  - causal inference\n  - propensity score\n  - inverse probability weighting\n  - treatment effects\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html:\n    embed-resources: true\n    self-contained-math: true\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: Python\n        language: python3\n        name: python3\n---\n\n\n\n\n\n\n## Outline\n\n### Prerequisites\n\n- Notebook 5 of this stream: estimating a treatment effect by adjusting for confounders\n- Comfort with `pandas` and basic Python at the COMET-intermediate level\n\n### Learning Outcomes\n\nBy the end of this notebook you will be able to:\n\n1. Define the **propensity score** and estimate it from data.\n2. Explain and compute **inverse probability weighting (IPW)**.\n3. Read a covariate-balance plot and say what weighting does to the data.\n4. Explain why the outcome route and the treatment route each fail when their model is wrong.\n5. Compute the **doubly-robust (AIPW)** estimator and explain what \"doubly robust\" means.\n\n::: {#57652b81 .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\nfrom sklearn.linear_model import LogisticRegression, LinearRegression\nfrom sklearn.preprocessing import StandardScaler\n\nRANDOM_STATE = 42\nTRUE_EFFECT = 2.0   # used later, in a simulated world where we set the real effect ourselves\n```\n:::\n\n\n## 1. Two routes to the same effect\n\nNotebook 4 left us with a recipe for the effect of 401(k) eligibility on savings. Using the unconfoundedness assumption, comparing eligible and ineligible households that match on their characteristics $X$ recovers the effect. We did this by modeling the **outcome**: predict savings from eligibility and $X$, then read off the difference. That was one of our two routes.\n\nIn this notebook, instead of modelling savings, we model **who gets treated**. If we can work out each household's chance of being eligible given its characteristics, we can use that chance to undo the imbalance between the two groups. You can look at this like the opposite of notebook 4, instead of modelling savings we model eligibility. The chance of treatment given $X$ is called the **propensity score**, and it leads to two estimators, inverse probability weighting and the doubly-robust estimator, that we build here.\n\nBoth routes aim at the same number, the average effect of eligibility.\n\n## 2. The Propensity Score\n\nThe **propensity score** is the probability of being treated given the covariates, $e(X) = P(D = 1 \\mid X)$. For our data it is the chance that a household with a given age, income, education, etc, is eligible for a 401(k). We don't know this for certain as we can't directly see it in our real data, so we will estimate it, this is a yes/no question so we will use a logistic regression. \n\n::: {#d2b97fcb .cell execution_count=2}\n``` {.python .cell-code}\nsavings = pd.read_csv(\"datasets/Pension401k.csv\")\nconfounders = [\"age\", \"inc\", \"educ\", \"fsize\", \"marr\", \"twoearn\", \"db\", \"pira\", \"hown\"]\nD = savings[\"e401\"].to_numpy()        # treatment: eligible for a 401(k)\nY = savings[\"net_tfa\"].to_numpy()     # outcome: net financial assets\nX = savings[confounders].to_numpy()\nX_std = StandardScaler().fit_transform(X)\n\npropensity = LogisticRegression(max_iter=2000).fit(X_std, D).predict_proba(X_std)[:, 1]\nprint(f\"Propensity score ranges from {propensity.min():.2f} to {propensity.max():.2f}\")\nprint(f\"Share of households eligible: {D.mean():.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPropensity score ranges from 0.10 to 0.98\nShare of households eligible: 0.37\n```\n:::\n:::\n\n\nFor a comparison to be possible everywhere, both eligible and ineligible households have to appear at every propensity value. This is the **overlap** or **positivity** condition from Notebook 4.\n\nThe visualization below shows the overlap condition, both ineligible and eligible households appear across the whole range, so a comparison is possible. \n\n::: {#e80f8ef5 .cell execution_count=3}\n``` {.python .cell-code}\nplt.figure(figsize=(9, 5))\nplt.hist(propensity[D == 0], bins=30, alpha=0.6, density=True, label=\"ineligible\")\nplt.hist(propensity[D == 1], bins=30, alpha=0.6, density=True, label=\"eligible\")\nplt.xlabel(\"estimated propensity score (chance of being eligible)\")\nplt.ylabel(\"density\")\nplt.title(\"Both groups appear across the whole range, so a comparison is possible\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_06_propensity_ipw_files/figure-ipynb/cell-4-output-1.png){}\n:::\n:::\n\n\nBoth curves cover the range from near zero to near one. Every household has comparable households on the other side, so overlap holds and we can proceed.\n\n### 2.1 Inverse probability weighting\n\nFor inverse probability weighting we take an eligible household that, given its characteristics, was unlikely to be eligible, meaning it has a low propensity score. It is rare among the eligible, and it stands in for many similar households that ended up ineligible. So we let it count for more, giving it a weight of one over its propensity, $1/e(X)$. We do the mirror image on the other side, weighting each ineligible household by one over its chance of being ineligible, $1/(1 - e(X))$. After this reweighting the two groups carry the same spread of characteristics, as though eligibility had been handed out at random.\n\nWe can watch the reweighting work. For each covariate, measure how far apart the eligible and ineligible groups are, before weighting and after.\n\n::: {#870c0d7d .cell execution_count=4}\n``` {.python .cell-code}\ne = np.clip(propensity, 0.01, 0.99)   # clip extremes so we never divide by a near-zero number\nw = np.where(D == 1, 1 / e, 1 / (1 - e))\n\nbefore, after = [], []\nfor j in range(len(confounders)):\n    v = X[:, j]\n    before.append((v[D == 1].mean() - v[D == 0].mean()) / v.std())\n    tw = np.sum(w[D == 1] * v[D == 1]) / np.sum(w[D == 1])\n    cw = np.sum(w[D == 0] * v[D == 0]) / np.sum(w[D == 0])\n    after.append((tw - cw) / v.std())\n\nrows = np.arange(len(confounders))\nplt.figure(figsize=(8, 6))\nplt.scatter(np.abs(before), rows, color=\"tab:red\", zorder=3, label=\"before weighting\")\nplt.scatter(np.abs(after), rows, color=\"tab:green\", zorder=3, label=\"after weighting\")\nplt.axvline(0, color=\"black\", linewidth=0.8)\nplt.yticks(rows, confounders)\nplt.xlabel(\"gap between groups, in standard deviations (closer to 0 is better balanced)\")\nplt.title(\"Weighting by the propensity score balances the covariates\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_06_propensity_ipw_files/figure-ipynb/cell-5-output-1.png){}\n:::\n:::\n\n\nBefore weighting, the red dots sit well away from zero: the eligible and ineligible groups differ on most characteristics, with income having the largest gap. After weighting, the green dots collapse toward zero. The groups now look alike. With them balanced, the **inverse probability weighting (IPW)** estimate of the effect is the difference between the weighted average savings of the two groups.\n\n::: {#08c842d1 .cell execution_count=5}\n``` {.python .cell-code}\ndef ipw_ate(D, Y, e):\n    treated = np.sum((D / e) * Y) / np.sum(D / e)\n    control = np.sum(((1 - D) / (1 - e)) * Y) / np.sum((1 - D) / (1 - e))\n    return treated - control\n\nprint(f\"IPW estimate of the effect of eligibility: {ipw_ate(D, Y, e):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nIPW estimate of the effect of eligibility: 1.70\n```\n:::\n:::\n\n\nOn the 401(k) data this gives 1.7 thousand dollars. Notice it sits well below the outcome-route estimate from Notebook 4, which was 5.9 thousand. The two routes disagree, and so far we don't have the tools to say which to believe. That is what will be discussed in the next section. \n\n## 3. Our two routes and their different models\n\nThe outcome route is only as good as the savings model. If our prediction of savings given $X$ is wrong, the estimate is biased. The treatment route, IPW, is only as good as the propensity model, so if our prediction of eligibility given $X$ is wrong, the weights are wrong and so is the estimate. On real data we cannot see which model is off, because we never know the true effect, so as we did in the past, we will build a world where we do.\n\nIn this world the true effect is 2, we set it ourselves. Both the chance of treatment and the level of savings depend on a covariate through a squared term, so a model that includes that term is correct and a model that leaves it out is wrong. We can then hand each estimator a correct or a wrong model on purpose and see what happens.\n\n::: {#a0405ccf .cell execution_count=6}\n``` {.python .cell-code}\ndef simulate(n, seed):\n    rng = np.random.default_rng(seed)\n    Xs = rng.normal(0, 1, (n, 4))\n    index = 0.6 * Xs[:, 0] - 0.6 * Xs[:, 1] + 0.7 * Xs[:, 0] ** 2   # propensity depends on a square\n    elig = (rng.uniform(size=n) < 1 / (1 + np.exp(-index))).astype(float)\n    out = TRUE_EFFECT * elig + Xs[:, 0] + Xs[:, 1] + Xs[:, 0] ** 2 + rng.normal(0, 1, n)\n    return Xs, elig, out\n\nX_sim, D_sim, Y_sim = simulate(5000, RANDOM_STATE)\nwith_square = np.column_stack([X_sim, X_sim[:, 0] ** 2])   # the correct model includes the square\nplain = X_sim                                              # the wrong model leaves it out\n\ndef fit_routes(X_out, X_ps):\n    e = np.clip(LogisticRegression(max_iter=2000).fit(X_ps, D_sim).predict_proba(X_ps)[:, 1], 0.01, 0.99)\n    mu1 = LinearRegression().fit(X_out[D_sim == 1], Y_sim[D_sim == 1]).predict(X_out)\n    mu0 = LinearRegression().fit(X_out[D_sim == 0], Y_sim[D_sim == 0]).predict(X_out)\n    return e, mu1, mu0\n\nscenarios = [(\"both models right\", with_square, with_square),\n             (\"outcome model wrong\", plain, with_square),\n             (\"propensity model wrong\", with_square, plain)]\n\nprint(f\"true effect = {TRUE_EFFECT}\")\nfor name, X_out, X_ps in scenarios:\n    e_s, mu1_s, mu0_s = fit_routes(X_out, X_ps)\n    print(f\"  {name:24s}: regression {np.mean(mu1_s - mu0_s):.2f}   IPW {ipw_ate(D_sim, Y_sim, e_s):.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\ntrue effect = 2.0\n  both models right       : regression 2.00   IPW 2.10\n  outcome model wrong     : regression 2.78   IPW 2.10\n  propensity model wrong  : regression 2.00   IPW 2.83\n```\n:::\n:::\n\n\nWhen both models are right, both routes recover the true 2. When the outcome model is wrong, the regression route is biased (2.78) while IPW, still using the right propensity, is correct. When the propensity model is wrong, IPW is biased (2.83) while the regression route is correct. Each route fails when its own model fails, and on real data we would not know that it had happened.\n\n## 4. The doubly-robust estimator\n\nWe want an estimator that survives a wrong model as long as the other one is right. The **augmented inverse probability weighting (AIPW)** estimator does this by using both at once. \n\nStart with the outcome route's answer, which is the regression estimate of the effect. Then check whether the outcome model actually fit: look at its mistakes, the gap between each household's real savings and what the model predicted. Reweight those mistakes the IPW way and add them on as a correction. Written out, the estimate is the average over households of:\n\n$$\n\\hat{\\tau} = \\frac{1}{n} \\sum_{i} \\Big[ \\underbrace{\\hat{\\mu}_1(X_i) - \\hat{\\mu}_0(X_i)}_{\\text{regression guess}} + \\underbrace{\\frac{D_i \\, (Y_i - \\hat{\\mu}_1(X_i))}{e(X_i)} - \\frac{(1 - D_i) \\, (Y_i - \\hat{\\mu}_0(X_i))}{1 - e(X_i)}}_{\\text{correction from the model's mistakes}} \\Big]\n$$\n\n::: {.callout-note}\n## Read this for the meaning, not the symbols\n\nDo not try to follow the formula term by term. The only thing to hold onto is its shape: the first part is the regression guess of the effect, and the second part is a correction built from the outcome model's mistakes, weighted like in the IPW.\n:::\n\nWhat matters is what the correction does in each case:\n\n- If the **outcome** model is right, it makes no systematic mistakes, so its residuals average to nothing and the correction vanishes. We keep the correct regression estimate.\n- If the outcome model is wrong but the **propensity** is right, those mistakes are where the leftover bias is hiding, and weighting them like IPW is what removes it.\n\nEither way the answer comes out right, as long as one of the two models is correct. This is very powerful when we can't for certain tell if our model is right.\n\n::: {.callout-important}\n## What \"doubly robust\" means\n\nAn estimator is **doubly robust** if it stays correct as long as at least one of its two models, the outcome model or the propensity model, is right, which gives you two chances instead of one. It does not save you if both models are wrong, and it does nothing about an unmeasured confounder, which breaks unconfoundedness itself and is beyond the reach of every estimator in this notebook.\n:::\n\nWe run all three estimators in our made-up example and plot them.\n\n::: {#0447e349 .cell execution_count=7}\n``` {.python .cell-code}\ndef aipw_score(D, Y, e, mu1, mu0):\n    return mu1 - mu0 + D * (Y - mu1) / e - (1 - D) * (Y - mu0) / (1 - e)\n\nlabels, reg_vals, ipw_vals, aipw_vals = [], [], [], []\nfor name, X_out, X_ps in scenarios:\n    e_s, mu1_s, mu0_s = fit_routes(X_out, X_ps)\n    labels.append(name.replace(\" \", \"\\n\"))\n    reg_vals.append(np.mean(mu1_s - mu0_s))\n    ipw_vals.append(ipw_ate(D_sim, Y_sim, e_s))\n    aipw_vals.append(np.mean(aipw_score(D_sim, Y_sim, e_s, mu1_s, mu0_s)))\n\npos = np.arange(len(labels))\nplt.figure(figsize=(9, 5))\nplt.bar(pos - 0.25, reg_vals, 0.25, label=\"regression\", color=\"tab:blue\")\nplt.bar(pos, ipw_vals, 0.25, label=\"IPW\", color=\"tab:orange\")\nplt.bar(pos + 0.25, aipw_vals, 0.25, label=\"AIPW (doubly robust)\", color=\"tab:green\")\nplt.axhline(TRUE_EFFECT, color=\"black\", linestyle=\"--\", label=f\"true effect = {TRUE_EFFECT:.0f}\")\nplt.xticks(pos, labels)\nplt.ylabel(\"estimated effect\")\nplt.title(\"Only AIPW lands on the truth when one of the two models is wrong\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_06_propensity_ipw_files/figure-ipynb/cell-8-output-1.png){}\n:::\n:::\n\n\nRegression (blue) is off when the outcome model is wrong; IPW (orange) is off when the propensity model is wrong; AIPW (green) sits on the true effect in all three worlds. It needed only one of its two models to be right.\n\n### 4.1 The doubly-robust estimate on the 401(k) data\n\nWe will apply the model to our real savings data, combining the logistic propensity from section 2 with simple linear models of savings.\n\n::: {#e555da83 .cell execution_count=8}\n``` {.python .cell-code}\nmu1 = LinearRegression().fit(X_std[D == 1], Y[D == 1]).predict(X_std)\nmu0 = LinearRegression().fit(X_std[D == 0], Y[D == 0]).predict(X_std)\n\nscore = aipw_score(D, Y, e, mu1, mu0)\naipw = score.mean()\naipw_se = score.std() / np.sqrt(len(score))\nprint(f\"AIPW estimate: {aipw:.2f}  (se {aipw_se:.2f})\")\nprint(f\"95% interval : {aipw - 1.96 * aipw_se:.2f} to {aipw + 1.96 * aipw_se:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAIPW estimate: 1.91  (se 3.55)\n95% interval : -5.04 to 8.87\n```\n:::\n:::\n\n\nThe point estimate is 1.91 thousand dollars. The raw gap between eligible and ineligible households was about 19.6 thousand (Notebook 4), and AIPW puts the de-confounded effect near 1.9. Almost all of that raw gap was selection: eligible households were already richer savers, and once we account for that, what looked like a $19,600 effect is at most a couple of thousand (look at the upper bound of the 95% confidence interval). We have shown that shrinkage (selection bias), which is an important lesson in this notebook on real data. \n\nWhat we cannot yet do is measure the piece that is left precisely. The standard error is large (3.55), and the 95% interval contains large negative values, zero and large positive values, so we cannot even be sure the effect is positive. Savings are very spread out, a few households hold enormous amounts, and reweighting a quantity like that is noisy. Simple linear models remove the bias but leave too much variance behind. We will close this gap in the next notebook which is double machine learning.  \n\n::: {.callout-tip}\n## Self-test\n\nSuppose you are confident your propensity model is right but unsure about your outcome model. Does AIPW help you, and how?\n\n<details><summary>Show / hide answer</summary>\nYes. AIPW is correct as long as either model is right, so a correct propensity model alone is enough to make the estimate consistent, whatever the outcome model does. In that case AIPW behaves like a refined version of IPW: the outcome model is along for the ride and mostly reduces the variance. The same holds with the roles reversed, and that is the appeal of having two chances.\n</details>\n:::\n\n## 5. Connections\n\nThis notebook added the treatment-modelling route to the outcome-modelling route of Notebook 4, and combined them. The combination, AIPW, is the bridge to the rest of the stream: its score is the object that double machine learning (notebook 7) is built around.\n\n- **Back to Notebook 5:** there we adjusted for confounders by selecting controls for a single regression; here we adjust by modelling the treatment instead, and then combine the two routes.\n- **Forward to Notebook 7:** double machine learning, which estimates the two models with any learner and computes the doubly-robust score with cross-fitting, turning this notebook's noisy estimate into a sharp one.\n\n### References\n\n- Chernozhukov, V., Chetverikov, D., Demirer, M., Duflo, E., Hansen, C., Newey, W., & Robins, J. (2018). *Double/debiased machine learning for treatment and structural parameters.* Econometrics Journal, 21(1), C1-C68. The cross-fitting that Notebook 7 builds on.\n- Facure, M. (2023). *Doubly robust estimation* (Chapter 12). In *Causal Inference for the Brave and True.* https://matheusfacure.github.io/python-causality-handbook/12-Doubly-Robust-Estimation.html\n- Glynn, A., & Quinn, K. (2009). *An Introduction to the Augmented Inverse Propensity Weighted Estimator.* https://www.law.berkeley.edu/archive/files/AIPW(1).pdf\n- Poterba, J. M., Venti, S. F., & Wise, D. A. (1995). *Do 401(k) contributions crowd out other personal saving?* Journal of Public Economics, 58(1), 1-32. The eligibility question.\n- Robins, J. M., Rotnitzky, A., & Zhao, L. P. (1994). *Estimation of regression coefficients when some regressors are not always observed.* Journal of the American Statistical Association, 89(427), 846-866. The augmented, doubly-robust estimator.\n- Rosenbaum, P. R., & Rubin, D. B. (1983). *The central role of the propensity score in observational studies for causal effects.* Biometrika, 70(1), 41-55.\n\n---\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: 'D:\\Users\\alexr\\anaconda3\\share\\jupyter\\kernels\\python3'\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.13.5\n---\n",
    "supporting": [
      "notebook_06_propensity_ipw_files\\figure-ipynb"
    ],
    "filters": []
  }
}