---
title: "Image Analysis Overview"
author: "prAxIs UBC Team <br> _Kaiyan Zhang_"
image: 
categories:
  - Python
  - image analysis
  - computer vision
format:
  html: default
  revealjs:
    scrollable: true
    smaller: true
    slide-number: true
    output-ext: slides.html
  ipynb:
    jupyter:
      kernelspec:
        display_name: Python
        language: python3
        name: python3
---

## Section 1: Image Analysis Overview

### 1.1 Motivation

### 1.2 Applications

### 1.3 Types of Images

## Section 2: Computational Image Analysis

### 2.1 Image as a Type of Data

### 2.1.1 Image Representation

### 2.1.2 Image Formats

### 2.2 Image Processing vs. Image Analysis

### 2.2.1 Data Acquisition and Preprocessing

### 2.2.2 Image Enhancement

### 2.2.3 "Manual" Image Analysis Techniques

### 2.3 Classical Computer Vision

### 2.3.1 Bag of Visual Words (BoVW)

### 2.4 Machine Learning for Image Analysis

### 2.4.1 Supervised Learning

### 2.4.2 Unsupervised Learning

### 2.4.3 Deep Learning and CNN

### 2.4.4 Critical Considerations in Using ML/DL Models

### 2.7 Common Libraries for Image Analysis in Python

## Section 3: Demo: Practical Workflow for Image Analysis

### 3.1 Problem Definition

### 3.2 Data Collection

### 3.3 Using Pre-trained Models

### 3.4 Evaluation Metrics

### 3.5 Model Fine-tuning

### 3.6 Visualizing Results

### 3.7 Ethical Considerations

## Conclusion

### References