{
  "hash": "86cedba56958e2d29b7e39baec2a80ab",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Optical Character Recognition (OCR)\"\nauthor: \"Alex Ronczewski\"\ndate: 2026-04-06\ndescription: OCR\ncategories:\n  - Python\n  - OCR\n  - text extraction\n  - image processing\nexecute:\n  eval: true\n  echo: true\n  output: true\n  fig-format: png\n  fig-dpi: 100\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the code\"\n    embed-resources: true\n    self-contained-math: true\njupyter: python3\n---\n\n\n## Setup and Library Loading\n\nBefore we begin, we need to install and import the necessary libraries. This notebook uses several Python packages for OCR, image processing, and text analysis.\n\n::: {.callout-tip}\n**Installation Note:** If you're running this notebook for the first time, uncomment and run the installation commands below. Some libraries require additional system dependencies:\n\n- **Poppler**: Required for PDF conversion - install via `conda install poppler` or system package manager\n:::\n\nInstall the necessary packages: \n\n::: {#f8ed83ed .cell execution_count=1}\n``` {.python .cell-code}\n# Uncomment the line below to install packages:\n#!pip install pytesseract easyocr opencv-python Pillow matplotlib pandas numpy nltk jiwer pdf2image \"surya-ocr>=0.9\" poppler anthropic\n```\n:::\n\n\nLoad the required packages:\n\n::: {#df219dfd .cell execution_count=2}\n``` {.python .cell-code}\nimport os\nimport re\nos.environ[\"KMP_DUPLICATE_LIB_OK\"] = \"TRUE\" # avoid OpenMP conflicts between libraries\nimport json\nimport warnings\nwarnings.filterwarnings('ignore')\nimport copy\nfrom PIL import Image, ImageDraw, ImageFont\nimport cv2\nimport numpy as np\nimport easyocr\nimport pandas as pd\nimport matplotlib.pyplot as plt\nimport nltk\nfrom nltk.tokenize import word_tokenize, sent_tokenize\nfrom nltk.stem import PorterStemmer, WordNetLemmatizer\nfrom jiwer import wer, cer\nfrom pdf2image import convert_from_path\nimport gc\nimport torch\nfrom surya.foundation import FoundationPredictor\nfrom surya.recognition import RecognitionPredictor\nfrom surya.detection import DetectionPredictor\nfrom surya.layout import LayoutPredictor\nfrom surya.settings import settings\nnltk.download('punkt')\nnltk.download('wordnet')\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n[nltk_data] Downloading package punkt to\n[nltk_data]     C:\\Users\\alexr\\AppData\\Roaming\\nltk_data...\n[nltk_data]   Package punkt is already up-to-date!\n[nltk_data] Downloading package wordnet to\n[nltk_data]     C:\\Users\\alexr\\AppData\\Roaming\\nltk_data...\n[nltk_data]   Package wordnet is already up-to-date!\n```\n:::\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\nTrue\n```\n:::\n:::\n\n\nHere we define helper functions for loading and displaying images, and prepare the output directory. These functions will help us a lot throughout the notebook. \n\n::: {#caed95ed .cell execution_count=3}\n``` {.python .cell-code}\ndef load_image(path):\n    #Load an image from pdf, jp2, tif, jpg, or png and return as RGB numpy array.\n    if path.endswith('.pdf'):\n        from pdf2image import convert_from_path\n        pages = convert_from_path(path, dpi=300)\n        return np.array(pages[0])\n    else:\n        img = Image.open(path)\n        if img.mode != 'RGB':\n            img = img.convert('RGB')\n        return np.array(img)\n\ndef display_image(img, title=\"Image\", figsize=(10, 8)):\n    plt.figure(figsize=figsize)\n    if len(img.shape) == 2:\n        plt.imshow(img, cmap='gray')\n    else:\n        plt.imshow(img)\n    plt.title(title)\n    plt.axis('off')\n    plt.tight_layout()\n    plt.show()\n    plt.close()\n\ndef display_images_side_by_side(img1, img2, title1=\"Before\", title2=\"After\", figsize=(14, 6)):\n    fig, axes = plt.subplots(1, 2, figsize=figsize)\n\n    if len(img1.shape) == 2:\n        axes[0].imshow(img1, cmap='gray')\n    else:\n        axes[0].imshow(img1)\n    axes[0].set_title(title1)\n    axes[0].axis('off')\n\n    if len(img2.shape) == 2:\n        axes[1].imshow(img2, cmap='gray')\n    else:\n        axes[1].imshow(img2)\n    axes[1].set_title(title2)\n    axes[1].axis('off')\n\n    plt.tight_layout()\n    plt.show()\n    plt.close()\n\nos.makedirs('output', exist_ok=True)\nprint(\"Output directory ready: ./output/\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOutput directory ready: ./output/\n```\n:::\n:::\n\n\n## Introduction\n\nBefore we begin it is important to define how a computer can read text in the first place.\n\n### Digitized Text vs. Machine-Readable Text\n\nHumans and computers see text, and images differently. When you open a scanned document or a photograph of a page on your computer, you can read the words on screen but your computer cannot. You can see the context and what the image or text represents, but from a computer's perspective there is no difference from a photograph of a landscape. In this case images are treated as visual, pixel-based graphics which are rendered onto your computer monitor, but the computer does not know exactly what it is rendering the same way a human viewing the images does. It could be a picture of your family, the ocean, a letter or a painting. \n\n**Machine-readable text**, by contrast, is stored as character data (e.g., Unicode, or ASCII ) that software can search, sort, count, and analyze. A PDF or a Word document already contains machine-readable text. A normal picture does not. This distinction matters because nearly every computational text-analysis method (keyword search, topic modeling, named-entity recognition, embeddings) requires machine-readable text as input. If your source material exists only as images (scans, photographs, microfilm captures), you need a way to bridge the gap. That is exactly what OCR does.\n\n### What is OCR?\n\n**Optical Character Recognition (OCR)** is the technology that converts different types of documents: scanned paper documents, photographs of text, or images containing text into editable and searchable digital text.\n\nFor humanities researchers, OCR makes it possible to work with historical documents at scale, enabling:\n\n- **Digitization**: Converting physical archives into searchable digital collections\n- **Corpus Building**: Creating large text datasets for computational analysis\n- **Accessibility**: Making historical documents searchable and accessible to researchers worldwide\n- **Text Mining**: Enabling large-scale analysis of historical texts\n\n### What You'll Learn\n\nBy the end of this notebook, you will be able to:\n\n1. **Understand OCR vs VLM** and be able to choose which model/tool to use\n2. **Extract text** from historical documents using EasyOCR and Surya OCR\n3. **Pre-process images** to improve OCR accuracy\n4. **Handle complex document layouts** like multi-column newspapers\n5. **Evaluate OCR quality** using standard metrics (CER, WER, Confidence Scores)\n6. **Post-process OCR output** for downstream analysis\n7. **Scale your workflow** for batch processing\n\n## Part 1: Traditional OCR\n\n### 1.1 What is Text Extraction?\n\nText extraction from documents falls into three main categories:\n\n1. **Printed Text**: Machine-generated text (newspapers, books, typed documents)\n   - Best suited for traditional OCR engines\n   - High accuracy achievable with good quality scans\n\n2. **Handwritten Text**: Human-written manuscripts, letters, notes\n   - Requires specialized HTR models\n   - Accuracy varies significantly based on handwriting style\n\n3. **Mixed Content**: Documents with text, illustrations, tables\n   - Requires layout analysis before text extraction\n   - May need different approaches for different regions\n\n#### Available OCR Tools\n\n| Tool | Type | Strengths | Best For |\n|------|------|-----------|----------|\n| **Tesseract** | Open-source | Fast, accurate on clean text | Printed documents |\n| **EasyOCR** | Open-source | Multi-language, deep learning | Diverse scripts |\n| **Surya OCR** | Open-source | Multi-language, layout detection, CPU-friendly | Complex layouts |\n| **Transkribus** | Freemium | Excellent HTR, crowdsourcing | Handwritten documents |\n| **Azure Document Intelligence** | Paid | Enterprise-grade, form extraction | Business documents |\n| **AWS Textract** | Paid | Table extraction, scalable | Structured documents |\n\n### 1.2 How Does Traditional OCR Work?\n\nTraditional OCR systems convert images of text into machine-readable characters through a multi-stage pipeline. While early OCR relied on template matching (comparing characters against a library of known fonts), modern tools like EasyOCR and Tesseract use deep learning to achieve far greater accuracy.\n\n#### The OCR Pipeline\n\nMost OCR systems follow a two-stage process:\n\n1. **Text Detection**: First, the system locates *where* text appears in the image. This involves identifying bounding boxes around words, lines, or paragraphs. Deep learning models scan the image and predict regions likely to contain text, even when text is rotated, curved, or partially obscured.\n\n2. **Text Recognition**: Once text regions are detected, a separate model reads *what* the text says. This typically uses a neural network architecture called a **CRNN (Convolutional Recurrent Neural Network)** that processes the image sequence and outputs a string of characters. You can read more about CNNs at [A Related Notebook](https://ubcecon.github.io/praxis-ubc/docs/intro_to_cnns/intro_to_cnn.html). \n\n#### Why Deep Learning Changed OCR\n\nTraditional template-matching OCR required near-perfect conditions: clean scans, standard fonts, and horizontal text. Deep learning models learn patterns from millions of examples, enabling them to:\n\n- Recognize text in varied fonts, sizes, and styles\n- Handle noise, blur, and degradation common in historical documents\n- Detect text at any angle or orientation\n- Generalize to scripts and languages they weren't explicitly programmed for\n\n**EasyOCR** specifically uses a CRAFT (Character Region Awareness for Text) detector for finding text, paired with a CRNN-based recognizer. This combination makes it particularly effective for documents with complex layouts or mixed content.\n\n### 1.3 EasyOCR Demo\n\n**EasyOCR** is a newer, deep-learning-based OCR library that supports 80+ languages. It provides built-in support for detecting text regions.\n\n::: {.callout-warning}\n**GPU Acceleration**: EasyOCR can use GPU for faster processing. If you have a CUDA-capable GPU, it will be automatically detected. On CPU, processing may take a few seconds.\n:::\n\nWe will first load our sample image, a clean newspaper column:\n\n::: {#b9676736 .cell execution_count=4}\n``` {.python .cell-code}\nimg_path = \"data/simple/newspaper_clean_col1.jp2\"\nimg = load_image(img_path)\ndisplay_image(img, title=\"Sample Newspaper Column\", figsize=(8, 12))\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-5-output-1.png){}\n:::\n:::\n\n\nThis is just one vertical column of clear text, for this notebook this will act as our most basic example. \n\nWe load the EasyOCR package and set it to read English with `easyocr.Reader(['en'])`.\n\n::: {#23cc343f .cell execution_count=5}\n``` {.python .cell-code}\nreader = easyocr.Reader(['en'], gpu=torch.cuda.is_available())\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nUsing CPU. Note: This module is much faster with a GPU.\n```\n:::\n:::\n\n\n::: {#339b0252 .cell execution_count=6}\n``` {.python .cell-code}\nresults = reader.readtext(img)\n\nprint(f\"EasyOCR detected {len(results)} text regions\")\nprint(\"\\nFirst 10 detections:\")\nfor i, (bbox, text, conf) in enumerate(results[:10]):\n    print(f\"  {i+1}. '{text}' (confidence: {conf:.2%})\")\n\nextracted_text = '\\n'.join([text for (bbox, text, conf) in results])\n\nocr_df = pd.DataFrame({\n    'text': [text for (bbox, text, conf) in results],\n    'conf': [conf * 100 for (bbox, text, conf) in results]\n})\n\nprint(f\"\\nTotal text length: {len(extracted_text)} characters\")\nprint(f\"Average confidence: {ocr_df['conf'].mean():.1f}%\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEasyOCR detected 246 text regions\n\nFirst 10 detections:\n  1. 'Twenty-Fifth Infantcy' (confidence: 62.46%)\n  2. 'Wins Athletic Honors' (confidence: 83.43%)\n  3. 'Champions' (confidence: 100.00%)\n  4. 'of' (confidence: 97.88%)\n  5. 'Six' (confidence: 99.99%)\n  6. 'Regiments' (confidence: 88.16%)\n  7. 'Com -' (confidence: 97.59%)\n  8. 'pete' (confidence: 99.44%)\n  9. 'in' (confidence: 99.98%)\n  10. 'Exciting Finals of' (confidence: 93.86%)\n\nTotal text length: 2348 characters\nAverage confidence: 91.4%\n```\n:::\n:::\n\n\nEasyOCR scanned the newspaper image and identified 246 separate regions containing text, returning each one with its bounding box coordinates, the recognized text, and a confidence score. \n\n##### Confidence Metrics\n\nConfidence scores are numerical metrics; typically ranging from 0 to 1 (0% to 100%) which indicates an AI or machine learning model's level of certainty in its prediction or classification. They represent the probability that the model's output is correct. A more technical definition is that: When an OCR model predicts a character, it computes a softmax probability distribution over all possible output classes. The confidence score is the maximum probability (the model's estimated likelihood that its top prediction is correct). For example if an OCR model sees a deformed or smudged **e** it does not say immediately that it is an e, but calculates a probability for all characters (e,c,a,7,.,0 etc). The confidence score we see is the highest value of this prediction. This is a simplified description, the exact computation varies by model architecture (e.g. CTC-based models like EasyOCR compute sequence-level probabilities, while transformer models like Surya use token-level log-probabilities); but the intuition is the same: higher scores mean the model is more certain.\n\nCrucially **confidence scores are not accuracy**, softmax normalizes over the model's known vocabulary, not over ground truth. It is a valuable metric, but do not overly rely on it or tunnel vision on pushing the highest confidence. Low confidence is often more informative than high, it gives insights on the model's true uncertainty. \n\n#### Visualizing EasyOCR Bounding Boxes\n\nOne advantage of EasyOCR is that it provides polygonal bounding boxes that can better fit rotated or curved text:\n\n::: {#3cdc675f .cell execution_count=7}\n``` {.python .cell-code}\nimg_with_boxes = img.copy()\n\nfor (bbox, text, conf) in results:\n    pts = np.array(bbox, dtype=np.int32)\n    color = (0, int(255 * conf), int(255 * (1 - conf))) # green=high, red=low\n    cv2.polylines(img_with_boxes, [pts], isClosed=True, color=color, thickness=2)\n\ndisplay_image(img_with_boxes, title=\"EasyOCR Text Detections (Green=High Conf, Red=Low Conf)\", figsize=(10, 14))\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-8-output-1.png){}\n:::\n:::\n\n\nWe can very clearly visually see the way in which EasyOCR is reading the text. Green boxes represent high confidence while red are lower confidence (we do not see any fully red boxes as there are no very low confidence regions).\n\nThe overall confidence from EasyOCR is at 91.4% which is not bad, but it is worth keeping in mind that this is a very basic example and the model is still making some mistakes. If we were to use a more difficult sample EasyOCR will struggle. \n\n\n### 1.4 Paid Tools Overview\n\nWhile open-source tools work well for many use cases, commercial solutions offer additional features:\n\n| Tool | Pricing | Key Features | Best For |\n|------|---------|--------------|----------|\n| **Transkribus** | Freemium (~50 pages/month free via credit system) | HTR, crowdsourcing, model training | Historical manuscripts |\n| **Arkindex** | Free for researchers | Document processing pipelines | Archives |\n| **eScriptorium** | Free (self-hosted) | Medieval manuscripts, collaborative | Academic projects |\n| **Azure Document Intelligence** | Basic OCR ~$1.50/1000 pages; forms/tables $10–$65/1000 | Form extraction, tables, structure | Business documents |\n| **AWS Textract** | Basic OCR ~$1.50/1000 pages; structured extraction higher | Tables, forms, scalable API | Enterprise integration |\n| **Google Cloud Vision** | Basic OCR ~$1.50/1000 images; Document AI higher | Multi-language, handwriting | Diverse content |\n\n## Part 2: Beyond Traditional OCR\n\n### 2.1 What Are VLMs?\n\nAt the other end of the spectrum from traditional OCR are **Vision Language Models (VLMs)**. These take a fundamentally different approach to document understanding. Rather than recognizing characters individually like traditional OCR, VLMs understand documents as a whole, interpreting text, layout, and visual context together.\n\n#### Bottom-Up vs Top-Down Approaches\n\n| Approach | Traditional OCR | Vision Language Models |\n|----------|-----------------|------------------------|\n| **Method** | Character-by-character recognition | Whole-document understanding |\n| **Layout** | Separate step | Integrated |\n| **Context** | Limited | Full document context |\n| **Errors** | Isolated character mistakes | More coherent (or coherently wrong!) |\n\n#### When to Use OCR vs VLMs\n\n**Use Traditional OCR when:**\n\n- Documents are clean and well-formatted\n- You need character-level confidence scores\n- Processing speed is critical\n- Resources are limited\n\n**Use VLMs when:**\n\n- Documents have complex layouts\n- Text quality is poor or degraded\n- You need to extract structured information\n- Handwritten and printed text are mixed\n\n::: {.callout-warning}\n**GPU Requirements**: Most VLMs require significant GPU memory (8GB+). For CPU-only systems, consider Surya OCR which works well on CPU.\n:::\n\n### 2.2 How Do VLMs Work?\n\nVision Language Models combine two powerful components: a **vision encoder** that \"sees\" the image and a **language model** that \"reasons\" about what it sees. This architecture allows them to understand documents the way humans do; taking in the whole page at once rather than reading character by character.\n\n#### The VLM Architecture\n\nVLMs typically follow a three-stage process:\n\n1. **Visual Encoding**: The image is divided into small patches (like tiles in a mosaic) and processed by a vision encoder. Often a Vision Transformer (ViT). This converts the raw pixels into a sequence of visual embeddings that capture shapes, patterns, and spatial relationships.\n\n2. **Cross-Modal Fusion**: The visual embeddings are combined with text understanding capabilities. This can happen through:\n   - **Early fusion**: Visual and text tokens are merged and processed together\n   - **Late fusion**: Separate processing streams that combine at the output stage\n   - **Cross-attention**: The language model attends to relevant parts of the image when generating text\n\n3. **Text Generation**: A language model (often a transformer decoder) generates the output text, guided by what it \"saw\" in the image. Because this is a language model, it can produce grammatically coherent text and use context to fill in gaps.\n\n#### Why VLMs \"Understand\" Documents Differently\n\nTraditional OCR processes text in isolation; each character or word is recognized independently. VLMs take a fundamentally different approach, they have the whole context of the document and can generate correct grammatical sentences based on that context. They also have built-in layout understanding as they can \"see\" the document. \n\nFor example, if a historical document has a smudged word, traditional OCR might output nonsense characters. A VLM can use surrounding context like the topic of the paragraph, common phrases of the era, grammatical structure in order to infer the most likely word.\n\n**The Trade-off**: VLMs are more powerful but also much more resource-intensive. They excel at understanding *what a document means* but may sometimes \"hallucinate\" plausible-sounding text that wasn't actually in the image. This will be familiar to anyone who has used ChatGPT or other LLMs in the past. Traditional OCR is more literal. It only outputs what it detects, errors and all.\n\n### 2.3 Surya OCR Demo\n\nFull VLMs like GPT-4V or Gemini are powerful but require significant computational resources, often cloud-hosted GPUs and API costs. For this notebook we use **Surya OCR** instead, a practical middle ground. Surya is not a VLM in the strict sense, but it borrows ideas from that world: it uses transformer-based models and includes built-in layout analysis alongside text detection and recognition. It works well on CPU, supports 90+ languages, and does not require cloud access or API keys.\n\nLet's try running Surya OCR on the same newspaper column and look at the results. This will take longer to run than EasyOCR. We can then compare the confidence and findings. \n\n::: {#3d3da915 .cell execution_count=8}\n``` {.python .cell-code}\nfoundation_predictor = FoundationPredictor()\nrec_predictor = RecognitionPredictor(foundation_predictor)\ndet_predictor = DetectionPredictor()\n\nsurya_img = Image.fromarray(img)\nsurya_results = rec_predictor([surya_img], det_predictor=det_predictor)\nsurya_result = surya_results[0]\n\nsurya_texts = [line.text for line in surya_result.text_lines]\nsurya_scores = [line.confidence for line in surya_result.text_lines]\n\nprint(f\"Surya OCR detected {len(surya_texts)} text regions\")\nprint(\"\\nFirst 10 detections:\")\nfor i, (text, conf) in enumerate(zip(surya_texts[:10], surya_scores[:10])):\n    print(f\"  {i+1}. '{text}' (confidence: {conf:.2%})\")\n\nsurya_full_text = ' '.join(surya_texts)\nprint(f\"\\n[Total characters extracted: {len(surya_full_text)}]\")\nprint(f\"Average confidence: {np.mean(surya_scores):.1%}\")\nprint(\"\\nFull text preview:\")\nprint(surya_full_text[:2000])\n\ndel rec_predictor, det_predictor, foundation_predictor\ngc.collect()\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:23<00:00, 23.78s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:23<00:00, 23.84s/it]\n\rRecognizing Text:   0%|          | 0/73 [00:00<?, ?it/s]\rRecognizing Text:   1%|▏         | 1/73 [00:47<56:50, 47.37s/it]\rRecognizing Text:   3%|▎         | 2/73 [00:47<23:16, 19.67s/it]\rRecognizing Text:   4%|▍         | 3/73 [00:49<13:14, 11.35s/it]\rRecognizing Text:   5%|▌         | 4/73 [00:49<08:07,  7.06s/it]\rRecognizing Text:   8%|▊         | 6/73 [00:50<03:59,  3.57s/it]\rRecognizing Text:  10%|▉         | 7/73 [00:51<03:04,  2.79s/it]\rRecognizing Text:  19%|█▉        | 14/73 [00:55<01:10,  1.19s/it]\rRecognizing Text:  25%|██▍       | 18/73 [00:55<00:42,  1.30it/s]\rRecognizing Text:  32%|███▏      | 23/73 [00:58<00:34,  1.44it/s]\rRecognizing Text:  41%|████      | 30/73 [01:02<00:25,  1.67it/s]\rRecognizing Text:  44%|████▍     | 32/73 [01:02<00:22,  1.84it/s]\rRecognizing Text:  45%|████▌     | 33/73 [01:10<00:49,  1.25s/it]\rRecognizing Text:  47%|████▋     | 34/73 [01:10<00:43,  1.12s/it]\rRecognizing Text:  51%|█████     | 37/73 [01:12<00:36,  1.00s/it]\rRecognizing Text:  52%|█████▏    | 38/73 [01:13<00:32,  1.07it/s]\rRecognizing Text:  55%|█████▍    | 40/73 [01:13<00:23,  1.43it/s]\rRecognizing Text:  60%|██████    | 44/73 [01:15<00:16,  1.80it/s]\rRecognizing Text:  68%|██████▊   | 50/73 [01:15<00:06,  3.31it/s]\rRecognizing Text:  75%|███████▌  | 55/73 [01:15<00:03,  4.80it/s]\rRecognizing Text:  81%|████████  | 59/73 [01:15<00:02,  6.09it/s]\rRecognizing Text:  84%|████████▎ | 61/73 [01:16<00:01,  6.36it/s]\rRecognizing Text:  86%|████████▋ | 63/73 [01:17<00:02,  4.01it/s]\rRecognizing Text:  88%|████████▊ | 64/73 [01:17<00:02,  3.58it/s]\rRecognizing Text:  89%|████████▉ | 65/73 [01:18<00:03,  2.61it/s]\rRecognizing Text:  90%|█████████ | 66/73 [01:18<00:02,  2.78it/s]\rRecognizing Text:  92%|█████████▏| 67/73 [01:19<00:02,  2.58it/s]\rRecognizing Text:  95%|█████████▍| 69/73 [01:19<00:01,  3.00it/s]\rRecognizing Text:  96%|█████████▌| 70/73 [01:20<00:00,  3.18it/s]\rRecognizing Text:  99%|█████████▊| 72/73 [01:20<00:00,  4.08it/s]\rRecognizing Text: 100%|██████████| 73/73 [01:20<00:00,  4.08it/s]\rRecognizing Text: 100%|██████████| 73/73 [01:20<00:00,  1.11s/it]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nSurya OCR detected 73 text regions\n\nFirst 10 detections:\n  1. '<b>Twenty-Fifth Infantry</b>' (confidence: 98.09%)\n  2. '<b>Wins Athletic Honors</b>' (confidence: 97.80%)\n  3. 'Champions of Six Regiments Com-' (confidence: 99.36%)\n  4. 'pete in Exciting Finals of Tour-' (confidence: 99.68%)\n  5. 'nament in Honolulu.' (confidence: 99.78%)\n  6. 'THE COLORED REGIMENT WINS.' (confidence: 99.84%)\n  7. 'Scores Nearly Half of All the Points' (confidence: 99.43%)\n  8. 'Made by Combined Competitors' (confidence: 98.73%)\n  9. 'Two Omaha Boys in Contest.' (confidence: 99.55%)\n  10. 'HOW THEY ENDED' (confidence: 98.47%)\n\n[Total characters extracted: 2384]\nAverage confidence: 99.4%\n\nFull text preview:\n<b>Twenty-Fifth Infantry</b> <b>Wins Athletic Honors</b> Champions of Six Regiments Com- pete in Exciting Finals of Tour- nament in Honolulu. THE COLORED REGIMENT WINS. Scores Nearly Half of All the Points Made by Combined Competitors Two Omaha Boys in Contest. HOW THEY ENDED Twenty-fifth Inf. .....70 points First Infantry.....40 points Second Infantry ......29 points Coast Defense .....14 points Honolulu, H. T., March 24-The Twenty-fifth Infantry February 26, made good its promises to carry off the major honors of the big military athletic meet, finishing in the finals against three other regiments with seventy points to its credit out of a total of one hundred and fifty-four. In addition, Gilbert, of the Twenty- fifth, smashed the Island record for the 100-yard dash to smithereens and set a local mark equal to the best ever made in the world. The finals attracted a great throng of spectators to Alexander Field. In- terest in the meet had steadily in- creased with each day's preliminaries and all who had been out to see any of the preliminary events were out early for the finals, besides several hundred who were out for the first time. Time and time again the spectators swarmed on to the field, but promptly left at the request of the officer in charge. There was really nothing for the guard company to do in keeping back the crowd and only good natured taunts were hurled back and forth by the men of one regiment to those of another, as some favorite measured up to their expectation. Crowd Out Eearly. At nine o'clock sharp the first event took place. There were tardy ones who lamented their misfortune, and well they might, for Gilbert of the Twenty-fifth Infantry held the bleach- ers spellbound as he raced down the cinder track in record time. He ran in magnificent form and smashed his newly established record of nine and four-fifths seconds by setting a new one of nine and three-fifth seconds. No Mistake Possible. Five stop watches caught the world record time of ni\n```\n:::\n:::\n\n\nOutput text sample: \"Twenty-Fifth Infantry Wins Athletic Honors Champions of Six Regiments Com- pete in Exciting Finals of Tour- nament in Honolulu. THE COLORED REGIMENT WINS. Scores Nearly Half of All the Points Made by Combined Competitors Two Omaha Boys in Contest.\"\n\nEasyOCR had an Average confidence: 91.4% while Surya had an average confidence of 99.4%. It is worth noting that confidence is not everything and it is important to actually review the results or compare them to a \"ground-truth\" (the actual text inside of the document often in a .txt format). The text preview looks correct, but this was a very simple example. Let's try on something far more difficult. \n\n#### Testing on Handwritten Documents\n\nOur example here will be a handwritten letter from the American Civil war from Alexander Parker Crittenden to his wife, Clara Crittenden dated to December 11, 1864. We can see how EasyOCR and Surya handle this more difficult handwritten example. \n\n::: {#bd1310b3 .cell execution_count=9}\n``` {.python .cell-code}\nletter_pages = convert_from_path(\"data/simple/handwritten_letter_page1.pdf\", dpi=300)\nletter_img = np.array(letter_pages[0])\ndisplay_image(letter_img, title=\"Handwritten Letter (Civil War Era)\", figsize=(10, 12))\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-10-output-1.png){}\n:::\n:::\n\n\nThe text is handwritten in cursive along with there being lots of background noise from the next page bleeding into the frame. Let's first try EasyOCR. \n\n::: {#7339ab7d .cell execution_count=10}\n``` {.python .cell-code}\neasyocr_hw_results = reader.readtext(letter_img)\neasyocr_hw_text = '\\n'.join([text for (bbox, text, conf) in easyocr_hw_results])\neasyocr_hw_confs = [conf for (bbox, text, conf) in easyocr_hw_results]\n\nprint(\"EasyOCR:\")\nprint(f\"Regions detected: {len(easyocr_hw_results)}\")\nprint(f\"Avg confidence: {np.mean(easyocr_hw_confs):.2%}\")\nprint(f\"\\nExtracted text (first 500 chars):\\n{easyocr_hw_text[:500]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEasyOCR:\nRegions detected: 61\nAvg confidence: 29.82%\n\nExtracted text (first 500 chars):\nAlexander Parker Crittenden letter to his wife, Clara Crittenden; Decem.\nhttps://digitalcollections lib.washington edu/digital/collection/civilwarli.\n{ { \n88>\n5>\ndecv lelavc\n3\nTlei aninezc\nLCexucc Yuv\n9\nCfc\nIc '\nL\n~ecue{EC\nlcZ  Alz_\n1&\nlu l\nUinCc\nU\n[&xuaUz \nKv\nSoscuzu\nPLles ~[czadl\n7 &i_\nU\nRabs\n4\nClusukU\nluus\nl\nAcc\nliual\nhlaZez\nGheha\nY& ,\nUi\nha< <\nIa<\nUck _\nEzZ\nJ\nLafc\n2Z _\nUkl\nZ\nLaid\nUlR~\n2 of 4\n2026-02-03, 5.12 p.m\n'fnyuut\n@ee\n[S6 G\n[\nuf\nkavc\n(\nkg\nC1\nbtC Z\nSA\n~fz\n```\n:::\n:::\n\n\nEasyOCR has performed very poorly and the output for the actual body of the letter is mostly random symbols and nonsensical. This is an excellent example to not follow average confidence blindly as the average confidence is 29.82% which should imply that it is slightly legible. The average confidence here is skewed by the lines above the letter from the University of Washington which are not handwritten. \n\nLet's try now with Surya: \n\n::: {#bf5ded37 .cell execution_count=11}\n``` {.python .cell-code}\nfoundation_predictor = FoundationPredictor()\nrec_predictor_hw = RecognitionPredictor(foundation_predictor)\ndet_predictor_hw = DetectionPredictor()\n\nsurya_hw_img = Image.fromarray(letter_img)\nsurya_hw_results = rec_predictor_hw([surya_hw_img], det_predictor=det_predictor_hw)\nsurya_hw_result = surya_hw_results[0]\n\nsurya_hw_texts = [line.text for line in surya_hw_result.text_lines]\nsurya_hw_scores = [line.confidence for line in surya_hw_result.text_lines]\nsurya_hw_text = '\\n'.join(surya_hw_texts)\n\nprint(\"--- Surya OCR ---\")\nprint(f\"Regions detected: {len(surya_hw_texts)}\")\nprint(f\"Avg confidence: {np.mean(surya_hw_scores):.2%}\")\nprint(f\"\\nExtracted text (first 500 chars):\\n{surya_hw_text[:500]}\")\n\ndel rec_predictor_hw, det_predictor_hw, foundation_predictor\ngc.collect()\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:07<00:00,  7.25s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:07<00:00,  7.25s/it]\n\rRecognizing Text:   0%|          | 0/22 [00:00<?, ?it/s]\rRecognizing Text:   5%|▍         | 1/22 [00:56<19:51, 56.75s/it]\rRecognizing Text:   9%|▉         | 2/22 [00:57<07:51, 23.60s/it]\rRecognizing Text:  14%|█▎        | 3/22 [00:58<04:13, 13.34s/it]\rRecognizing Text:  18%|█▊        | 4/22 [00:59<02:33,  8.52s/it]\rRecognizing Text:  27%|██▋       | 6/22 [01:00<01:10,  4.41s/it]\rRecognizing Text:  36%|███▋      | 8/22 [01:01<00:37,  2.68s/it]\rRecognizing Text:  55%|█████▍    | 12/22 [01:02<00:13,  1.30s/it]\rRecognizing Text:  68%|██████▊   | 15/22 [01:03<00:06,  1.02it/s]\rRecognizing Text:  77%|███████▋  | 17/22 [01:04<00:03,  1.29it/s]\rRecognizing Text:  82%|████████▏ | 18/22 [01:04<00:02,  1.41it/s]\rRecognizing Text:  86%|████████▋ | 19/22 [01:05<00:02,  1.34it/s]\rRecognizing Text:  95%|█████████▌| 21/22 [01:25<00:03,  3.87s/it]\rRecognizing Text: 100%|██████████| 22/22 [01:26<00:00,  3.43s/it]\rRecognizing Text: 100%|██████████| 22/22 [01:26<00:00,  3.94s/it]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n--- Surya OCR ---\nRegions detected: 22\nAvg confidence: 87.35%\n\nExtracted text (first 500 chars):\nAlexander Parker Crittenden letter to his wife, Clara Crittenden, Decem...\nhttps://digitalcollections.lib.washington.edu/digital/collection/civilwar/i...\nIngmia Dec 11, 1864\nMy dear Clara\nThis imment received yours\nrequested the\nElefi tant me by tester -\nI wish you would go\nor send to Itamellow to\nForenings Pholograph galle\nthe of the place of\nChurchite i Midograph\nwer not preserved unally\nthe places are kept\nIf this has been have\nmore of the photographs\nTur I ince\nWhen if\nsend you down the\nonly\n```\n:::\n:::\n\n\nThis output is far far better, Surya has read the text quite accurately. It is night and day from EasyOCR, it is not perfect but you can determine the general content of the letter. \n\n::: {#7958e58e .cell execution_count=12}\n``` {.python .cell-code}\ncomparison = pd.DataFrame({\n    'Metric': ['Regions detected', 'Avg confidence', 'Total characters'],\n    'EasyOCR': [len(easyocr_hw_results), f\"{np.mean(easyocr_hw_confs):.2%}\", len(easyocr_hw_text)],\n    'Surya OCR': [len(surya_hw_texts), f\"{np.mean(surya_hw_scores):.2%}\", len(surya_hw_text)]\n})\ndisplay(comparison)\n\ndel reader\ngc.collect()\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Metric</th>\n      <th>EasyOCR</th>\n      <th>Surya OCR</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Regions detected</td>\n      <td>61</td>\n      <td>22</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Avg confidence</td>\n      <td>29.82%</td>\n      <td>87.35%</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Total characters</td>\n      <td>468</td>\n      <td>542</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nBoth engines struggle a bit more with handwritten text. Traditional OCR is built for printed characters, so the low confidence scores and garbled output here are expected. Surya, with its transformer-based approach, performs much better. We have seen both great OCR and poor OCR, so what can we do to get the best results, how can we help the models. You can just throw different models at text and hope it works, but there are many tools and techniques which can be used to improve the OCR quality. In the next section we will look at developing a full pipeline to give the models a leg-up by giving them the best possible source and then post-processing techniques to analyze the output. \n\n## Part 3: Pre-processing \n\nA complete OCR workflow involves three stages: **pre-processing**, **text extraction**, and **post-processing**. Each stage can significantly impact final accuracy.\n\nPre-processing transforms raw document images into formats optimized for OCR. Each technique below uses a different image to highlight what that step does best.\n\n### 3.1 Grayscale Conversion\n\nConverting to grayscale simplifies the image from three colour channels (RGB) down to one. By removing colour, it reduces noise and improves contrast between text and background. This also lowers file size which is critical for computation time and can be very impactful for batch-processing lots of documents. Here we use a colour photograph of the UBC campus:\n\n::: {#20fd6e76 .cell execution_count=13}\n``` {.python .cell-code}\nubc_img = load_image(\"data/pre_processing_example/ubc_preprocess.jpg\")\nubc_gray = cv2.cvtColor(ubc_img, cv2.COLOR_RGB2GRAY)\ndisplay_images_side_by_side(ubc_img, ubc_gray, \"Original (UBC)\", \"Grayscale (UBC)\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-14-output-1.png){}\n:::\n:::\n\n\nNow let's try the same thing on a very different image — a handwritten restaurant menu on a blackboard:\n\n::: {#ff3447a9 .cell execution_count=14}\n``` {.python .cell-code}\nmenu_img = load_image(\"data/pre_processing_example/colourful-restaurant-menu-written-on-blackboard-style-sign-DH7FAJ.jpg\")\nmenu_gray = cv2.cvtColor(menu_img, cv2.COLOR_RGB2GRAY)\ndisplay_images_side_by_side(menu_img, menu_gray, \"Original (Menu)\", \"Grayscale (Menu)\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-15-output-1.png){}\n:::\n:::\n\n\nThis will help OCR models \"see\" the text and extract it. Grayscale helps OCR clearly see and analyze text as it reduces color noise and channel complexity. The image is simplified and allows the model to extract the text. \n\n#### 3.1.1 Binarization\n\nBinarization converts the image to pure black and white. **Otsu's method** is a global automatic image thresholding algorithm that converts grayscale images into binary (black and white) by determining an optimal threshold that separates pixels into foreground and background classes. It automatically finds the optimal threshold:\n\nFirst we will apply Otsu's method to our image of UBC to show what it does: \n\n::: {#9a99c62d .cell execution_count=15}\n``` {.python .cell-code}\notsu_thresh, ubc_binary = cv2.threshold(ubc_gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)\n\nprint(f\"Otsu selected threshold: {otsu_thresh:.0f} (out of 255)\")\ndisplay_images_side_by_side(ubc_img, ubc_binary, \"Original\", \"Otsu's Binarization\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOtsu selected threshold: 145 (out of 255)\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-16-output-2.png){}\n:::\n:::\n\n\nNow let's apply binarization to a noisy newspaper page:\n\n::: {#a51f1040 .cell execution_count=16}\n``` {.python .cell-code}\nnoisy_img = load_image(\"data/simple/newspaper_noisy.jp2\")\nnoisy_gray = cv2.cvtColor(noisy_img, cv2.COLOR_RGB2GRAY)\n\notsu_thresh, otsu_binary = cv2.threshold(noisy_gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)\n\ndisplay_images_side_by_side(noisy_img, otsu_binary, \"Original\", \"Otsu's Binarization\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-17-output-1.png){}\n:::\n:::\n\n\nWe can see that the end result is much clearer. It is black text on a pure white background as opposed to the gray, the smudges have also decreased on the margins of the newspaper. \n\n#### 3.1.2 Denoising\n\nNoise in images is \"the random, unwanted variation in brightness or colour information in digital images, appearing as a grainy, speckled, or mottled texture.\" An example is ![Noise Example](data/pre_processing_example/noise_example.png)\n\nRemoving noise can dramatically improve OCR accuracy. Let's first see what denoising does on a noisy image without text:\n\n::: {#d931e8be .cell execution_count=17}\n``` {.python .cell-code}\nnoisy_notext = load_image(\"data/pre_processing_example/noise_cleanup_example_notext.png\")\nnoisy_notext_gray = cv2.cvtColor(noisy_notext, cv2.COLOR_RGB2GRAY)\n\ndenoised_notext = cv2.fastNlMeansDenoising(noisy_notext_gray, h=10)\ndisplay_images_side_by_side(noisy_notext, denoised_notext, \"Original (Noisy)\", \"Denoised\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-18-output-1.png){}\n:::\n:::\n\n\nThe image of the woman on the left has small visible specks on it which could hinder OCR quality, on the right it is far clearer. \n\nNow let's apply the same technique to a noisy image that contains text:\n\n::: {#efd4931b .cell execution_count=18}\n``` {.python .cell-code}\nnoisy_text = load_image(\"data/pre_processing_example/noise_text.png\")\nnoisy_text_gray = cv2.cvtColor(noisy_text, cv2.COLOR_RGB2GRAY)\n\ndenoised_text = cv2.fastNlMeansDenoising(noisy_text_gray, h=10)\ndisplay_images_side_by_side(noisy_text, denoised_text, \"Original (Noisy Text)\", \"Denoised\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-19-output-1.png){}\n:::\n:::\n\n\nThe text is much clearer and easier to read. \n\n#### 3.1.3 Deskewing\n\nRotated documents hurt OCR accuracy. Let's detect and correct rotation:\n\nFirst we will make a function called deskew which we will apply later in the notebook. It determines the skew of the image and then rotates it to be facing upwards. \n\n::: {#e9b62181 .cell execution_count=19}\n``` {.python .cell-code}\n# Detect skew angle via Hough lines and rotate to correct it\ndef deskew(image):\n    if len(image.shape) == 3:\n        gray = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)\n    else:\n        gray = image.copy()\n\n    edges = cv2.Canny(gray, 50, 150, apertureSize=3)\n    lines = cv2.HoughLines(edges, 1, np.pi/180, 200)\n\n    if lines is None:\n        return image, 0\n\n    angles = []\n    for rho, theta in lines[:, 0]:\n        angle = np.degrees(theta) - 90\n        if -45 < angle < 45:\n            angles.append(angle)\n\n    if not angles:\n        return image, 0\n\n    median_angle = np.median(angles)\n\n    (h, w) = image.shape[:2]\n    center = (w // 2, h // 2)\n    M = cv2.getRotationMatrix2D(center, median_angle, 1.0)\n    rotated = cv2.warpAffine(image, M, (w, h), flags=cv2.INTER_CUBIC,\n                              borderMode=cv2.BORDER_REPLICATE)\n\n    return rotated, median_angle\n```\n:::\n\n\nWe now apply our deskew function on some example text:\n\n::: {#a182ad06 .cell execution_count=20}\n``` {.python .cell-code}\nskewed_img = load_image(\"data/pre_processing_example/deskew_example.jpg\")\ndeskewed, angle = deskew(skewed_img)\nprint(f\"Detected skew angle: {angle:.2f} degrees\")\n\ndisplay_images_side_by_side(skewed_img, deskewed, \"Original\", f\"Deskewed ({angle:.2f}°)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDetected skew angle: -20.00 degrees\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-21-output-2.png){}\n:::\n:::\n\n\nThe text was dynamically rotated. This greatly improves OCR as skewed text hurts OCR accuracy because models expect horizontal baselines, even a few degrees of tilt causes character errors. \n\n#### 3.1.4 Contrast Enhancement using CLAHE\n\n**CLAHE (Contrast Limited Adaptive Histogram Equalization)** improves readability of an image by fixing the lighting.\n\nWe will use our grayscale image of UBC and improve the contrast. CLAHE divides the image into small tiles and runs histogram equalization independently on each one, stretching brightness levels so the darks get darker and the lights get lighter. A contrast limit prevents over-amplification of noise in uniform regions.\n\n::: {#d95f85b2 .cell execution_count=21}\n``` {.python .cell-code}\nclahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))\nubc_enhanced = clahe.apply(ubc_gray)\n\ndisplay_images_side_by_side(ubc_gray, ubc_enhanced, \"Original Grayscale\", \"CLAHE Enhanced\")\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-22-output-1.png){}\n:::\n:::\n\n\n::: {.callout-warning}\n**Over pre-processing**: Doing too much pre-processing can degrade the image quality and make it nearly illegible. A clean PDF run through aggressive binarization + denoising will lose information. Be careful when running pre-processing, not every document needs every step. They can hurt more than help. Look at the output and test various techniques. \n:::\n\n### 3.2 Layout Analysis\n\nHistorical newspapers and various other documents often have complex multi-column layouts. Without proper layout analysis, OCR might read across columns incorrectly.\n\n#### Why Layout Analysis Matters\n\nConsider this scenario:\n\n```\nColumn 1           Column 2\n-----------        -----------\nThe mayor          Meanwhile,\nannounced today    across town\nthat the city      residents\n```\n\nWithout layout analysis, OCR might read: \"The mayor Meanwhile, announced today across town...\"\n\nSurya OCR includes a `LayoutPredictor` that detects and classifies document regions into types like Text, Table, Figure, SectionHeader, and more. It also assigns a reading order so you know which region to process first. \n\nLet's load our more difficult newspaper example and run Layout Analysis on it. \n\n::: {#db53d657 .cell execution_count=22}\n``` {.python .cell-code}\nmulticolumn_path = \"data/simple/newspaper_multicolumn.jp2\"\nmulticolumn_img = load_image(multicolumn_path)\nmulticolumn_pil = Image.fromarray(multicolumn_img)\n\ndisplay_image(multicolumn_img, title=\"Multi-Column Newspaper Front Page\", figsize=(12, 14))\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-23-output-1.png){}\n:::\n:::\n\n\nCompared to our single column, this is far more difficult with various columns, titles, images and sub-headings. We will run the Surya OCR LayoutPredictor which will detect regions of text and just like the EasyOCR example from earlier put boxes around them. It also comes with confidence scores. \n\n::: {#12248b02 .cell execution_count=23}\n``` {.python .cell-code}\nfoundation_predictor = FoundationPredictor(checkpoint=settings.LAYOUT_MODEL_CHECKPOINT)\nlayout_predictor = LayoutPredictor(foundation_predictor)\n\nlayout_results = layout_predictor([multicolumn_pil])\nlayout = layout_results[0]\n\nprint(f\"Detected {len(layout.bboxes)} layout regions:\\n\")\nfor box in layout.bboxes:\n    print(f\"  [{box.label}] position {box.position}, confidence {box.confidence:.2%}\")\n\ndel layout_predictor, foundation_predictor\ngc.collect()\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\rRecognizing Layout:   0%|          | 0/1 [00:00<?, ?it/s]\rRecognizing Layout: 100%|██████████| 1/1 [00:26<00:00, 26.34s/it]\rRecognizing Layout: 100%|██████████| 1/1 [00:26<00:00, 26.34s/it]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nDetected 113 layout regions:\n\n  [PageHeader] position 0, confidence 76.75%\n  [PageHeader] position 1, confidence 57.76%\n  [PageHeader] position 2, confidence 86.22%\n  [Text] position 3, confidence 75.94%\n  [Text] position 4, confidence 80.20%\n  [Text] position 5, confidence 88.44%\n  [Text] position 6, confidence 97.85%\n  [Text] position 7, confidence 96.38%\n  [Text] position 8, confidence 96.42%\n  [SectionHeader] position 9, confidence 71.03%\n  [SectionHeader] position 10, confidence 71.15%\n  [Text] position 11, confidence 82.41%\n  [Text] position 12, confidence 97.44%\n  [Text] position 13, confidence 99.03%\n  [Text] position 14, confidence 60.36%\n  [Text] position 15, confidence 98.26%\n  [Text] position 16, confidence 97.85%\n  [Text] position 17, confidence 99.26%\n  [Text] position 18, confidence 99.52%\n  [Text] position 19, confidence 98.80%\n  [Text] position 20, confidence 99.93%\n  [Text] position 21, confidence 99.86%\n  [Text] position 22, confidence 99.86%\n  [SectionHeader] position 23, confidence 92.54%\n  [Text] position 24, confidence 99.94%\n  [Text] position 25, confidence 99.94%\n  [Text] position 26, confidence 99.96%\n  [Text] position 27, confidence 99.83%\n  [Text] position 28, confidence 99.85%\n  [Text] position 29, confidence 99.84%\n  [SectionHeader] position 30, confidence 70.92%\n  [Text] position 31, confidence 98.95%\n  [Text] position 32, confidence 99.69%\n  [Text] position 33, confidence 99.81%\n  [Text] position 34, confidence 91.56%\n  [Text] position 35, confidence 78.99%\n  [Text] position 36, confidence 95.13%\n  [Text] position 37, confidence 97.17%\n  [Text] position 38, confidence 97.77%\n  [Text] position 39, confidence 99.67%\n  [Text] position 40, confidence 99.75%\n  [Text] position 41, confidence 58.86%\n  [Text] position 42, confidence 96.98%\n  [Text] position 43, confidence 99.89%\n  [Text] position 44, confidence 99.97%\n  [Text] position 45, confidence 99.99%\n  [Text] position 46, confidence 99.91%\n  [SectionHeader] position 47, confidence 89.62%\n  [Text] position 48, confidence 99.97%\n  [Text] position 49, confidence 99.60%\n  [Text] position 50, confidence 99.80%\n  [Text] position 51, confidence 99.95%\n  [Text] position 52, confidence 99.94%\n  [Text] position 53, confidence 97.24%\n  [Text] position 54, confidence 52.97%\n  [Picture] position 55, confidence 96.68%\n  [Picture] position 56, confidence 74.31%\n  [Text] position 57, confidence 52.48%\n  [Text] position 58, confidence 88.91%\n  [SectionHeader] position 59, confidence 92.95%\n  [Text] position 60, confidence 95.98%\n  [Text] position 61, confidence 97.67%\n  [Text] position 62, confidence 99.42%\n  [Text] position 63, confidence 99.89%\n  [Text] position 64, confidence 99.99%\n  [Text] position 65, confidence 99.98%\n  [Text] position 66, confidence 99.96%\n  [Text] position 67, confidence 99.96%\n  [Text] position 68, confidence 99.74%\n  [Text] position 69, confidence 98.66%\n  [SectionHeader] position 70, confidence 98.18%\n  [Text] position 71, confidence 99.96%\n  [Text] position 72, confidence 99.97%\n  [Text] position 73, confidence 99.87%\n  [Text] position 74, confidence 91.55%\n  [SectionHeader] position 75, confidence 60.16%\n  [Table] position 76, confidence 90.22%\n  [Text] position 77, confidence 88.40%\n  [Text] position 78, confidence 98.59%\n  [Text] position 79, confidence 98.30%\n  [Text] position 80, confidence 98.73%\n  [SectionHeader] position 81, confidence 92.70%\n  [Text] position 82, confidence 99.64%\n  [Text] position 83, confidence 99.55%\n  [Text] position 84, confidence 99.83%\n  [SectionHeader] position 85, confidence 78.00%\n  [Text] position 86, confidence 99.89%\n  [Text] position 87, confidence 99.84%\n  [Text] position 88, confidence 99.34%\n  [Text] position 89, confidence 99.90%\n  [Text] position 90, confidence 98.18%\n  [Text] position 91, confidence 99.69%\n  [Text] position 92, confidence 97.21%\n  [Text] position 93, confidence 94.09%\n  [Text] position 94, confidence 99.86%\n  [Text] position 95, confidence 99.80%\n  [Text] position 96, confidence 99.99%\n  [Text] position 97, confidence 100.00%\n  [Text] position 98, confidence 100.00%\n  [Text] position 99, confidence 99.98%\n  [Text] position 100, confidence 99.99%\n  [Text] position 101, confidence 99.98%\n  [SectionHeader] position 102, confidence 97.50%\n  [Text] position 103, confidence 99.99%\n  [Text] position 104, confidence 99.89%\n  [Text] position 105, confidence 99.99%\n  [Text] position 106, confidence 100.00%\n  [Text] position 107, confidence 99.99%\n  [Text] position 108, confidence 96.45%\n  [SectionHeader] position 109, confidence 98.09%\n  [Text] position 110, confidence 100.00%\n  [Text] position 111, confidence 99.98%\n  [Text] position 112, confidence 99.85%\n```\n:::\n:::\n\n\n::: {#301ce6af .cell execution_count=24}\n``` {.python .cell-code}\nannotated_img = copy.deepcopy(multicolumn_pil)\ndraw = ImageDraw.Draw(annotated_img)\n\nfor box in layout.bboxes:\n    poly = [(int(p[0]), int(p[1])) for p in box.polygon]\n    draw.line(poly + [poly[0]], fill=\"red\", width=4)\n    draw.text((poly[0][0], poly[0][1] - 14), f\"{box.label} ({box.position})\", fill=\"red\")\n\ndisplay_image(np.array(annotated_img), title=\"Detected Layout Regions\", figsize=(12, 14))\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-25-output-1.png){}\n:::\n:::\n\n\nThe algorithm has successfully ran and we can see red boxes around all of the major text sections, images and titles including tiny subheadings. This is an excellent tool and gives even more context to OCR. \n\n### 3.3 Post-processing\n\nOCR output often contains errors and requires cleaning. Post-processing can include:\n\n1. **Spell checking and correction**\n2. **Text normalization** (tokenization, lemmatization)\n3. **Structured output** (JSON(.json), Markdown(.md), TEXT(.txt))\n\nTokenization is the process of breaking down the raw text output generated from a scanned image or document into smaller, distinct, and manageable units called tokens. This simplifies data analysis, and Natural Language Processing (NLP) tasks. \n\n#### Text Normalization with NLTK\n\nWe will use our simple newspaper column example from earlier. We have the sample text and we will first turn it into smaller tokens, and then stem and lemmatize the tokens. Here we use NLTK's `word_tokenize()` which splits text into individual words and punctuation marks. This is different from the subword tokenization used by LLMs (like BPE), which breaks words into smaller pieces. For our purposes, word-level tokens are what we need for counting, stemming, and lemmatization.\n\n::: {#de609a31 .cell execution_count=25}\n``` {.python .cell-code}\nsample_text = \"\"\"\nTwenty-Fifth Infantry Wins Athletic Honors\n\nChampions of Six Regiments Compete in Exciting Finals of Tournament in Honolulu.\n\nTHE COLORED REGIMENT WINS.\n\nScores Nearly Half of All the Points Made by Combined Competitors Two Omaha Boys in Contest.\n\"\"\"\n\ntokens = word_tokenize(sample_text)\nsentences = sent_tokenize(sample_text)\n\nprint(\"Tokenization Results:\")\nprint(f\"  Words: {len(tokens)}\")\nprint(f\"  Sentences: {len(sentences)}\")\nprint(f\"\\nFirst 20 tokens: {tokens[:20]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTokenization Results:\n  Words: 40\n  Sentences: 3\n\nFirst 20 tokens: ['Twenty-Fifth', 'Infantry', 'Wins', 'Athletic', 'Honors', 'Champions', 'of', 'Six', 'Regiments', 'Compete', 'in', 'Exciting', 'Finals', 'of', 'Tournament', 'in', 'Honolulu', '.', 'THE', 'COLORED']\n```\n:::\n:::\n\n\nThe tokens here are just words as we are giving the raw correct text to the function, there is no OCR required, if it was complex OCR like with the handwritten letter the tokens that the model uses might be a little different from words. \n\nNext we will run stemming and lemmatization on our tokens. “Stemming and lemmatization are text preprocessing techniques that reduce the inflected forms of words across a text data set to one common root word or dictionary form, also known as a “lemma” in computational linguistics.\"\"\n\n::: {#3b34e196 .cell execution_count=26}\n``` {.python .cell-code}\nstemmer = PorterStemmer()\nlemmatizer = WordNetLemmatizer()\n\ntest_words = ['running', 'competed', 'competitors', 'athletics', 'winning']\n\nprint(\"\\nStemming vs Lemmatization:\")\nfor word in test_words:\n    stem = stemmer.stem(word)\n    lemma = lemmatizer.lemmatize(word)\n    print(f\"  {word:15} -> Stem: {stem:12} | Lemma: {lemma}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nStemming vs Lemmatization:\n  running         -> Stem: run          | Lemma: running\n  competed        -> Stem: compet       | Lemma: competed\n  competitors     -> Stem: competitor   | Lemma: competitor\n  athletics       -> Stem: athlet       | Lemma: athletics\n  winning         -> Stem: win          | Lemma: winning\n```\n:::\n:::\n\n\nStemming can be very useful for text analysis as all conjugations and versions of similar words are reduced to the root stem. It is vital for many Natural Language Processing techniques. \n\n#### Structured Output\n\nConverting OCR output to structured formats enables downstream analysis:\n\nWe make a function to save the .json output of our OCR. \n\n::: {#ca82011d .cell execution_count=27}\n``` {.python .cell-code}\n#Create a structured JSON output from OCR results.\ndef create_structured_output(text, ocr_data_df, source_file, ocr_engine=\"easyocr\"):\n    words = word_tokenize(text)\n    sentences = sent_tokenize(text)\n\n    output = {\n        \"metadata\": {\n            \"source_file\": source_file,\n            \"ocr_engine\": ocr_engine,\n            \"total_characters\": len(text),\n            \"total_words\": len(words),\n            \"total_sentences\": len(sentences),\n            \"average_confidence\": float(ocr_data_df['conf'].mean()) if 'conf' in ocr_data_df else None\n        },\n        \"text\": text.strip(),\n        \"sentences\": sentences,\n        \"word_count_by_confidence\": {\n            \"high (90-100)\": len(ocr_data_df[ocr_data_df['conf'] >= 90]),\n            \"medium (70-89)\": len(ocr_data_df[(ocr_data_df['conf'] >= 70) & (ocr_data_df['conf'] < 90)]),\n            \"low (< 70)\": len(ocr_data_df[ocr_data_df['conf'] < 70])\n        }\n    }\n\n    return output\n```\n:::\n\n\nThis will be for our simple newspaper column example:\n\n::: {#b26d69bb .cell execution_count=28}\n``` {.python .cell-code}\nstructured = create_structured_output(extracted_text, ocr_df, \"newspaper_clean_col1.jp2\")\n\nwith open('output/document.json', 'w') as f:\n    json.dump(structured, f, indent=2)\n\nprint(\"Structured Output:\")\nprint(json.dumps(structured['metadata'], indent=2))\nprint(f\"\\nWord count by confidence: {structured['word_count_by_confidence']}\")\nprint(f\"\\nSaved to: output/document.json\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nStructured Output:\n{\n  \"source_file\": \"newspaper_clean_col1.jp2\",\n  \"ocr_engine\": \"easyocr\",\n  \"total_characters\": 2348,\n  \"total_words\": 441,\n  \"total_sentences\": 8,\n  \"average_confidence\": 91.42954141447443\n}\n\nWord count by confidence: {'high (90-100)': 178, 'medium (70-89)': 47, 'low (< 70)': 21}\n\nSaved to: output/document.json\n```\n:::\n:::\n\n\nA .json is less human-readable than a .txt, but it is excellent for machine processing and programming tasks. Here what our .json looks like:\n\n![.json example](media/json_example.png)\n\n.json files are great tools for Natural Language Processing (NLP) techniques examples of which are: \n\n- **Named-Entity Recognition (NER)** — automatically identify people, places, dates, and organizations mentioned in the document.\n- **Topic Modeling** — discover recurring themes across a large corpus of digitized documents.\n- **Sentiment / Stance Analysis** — measure tone or opinion in editorials, letters, or testimony.\n- **Text Embeddings & Semantic Search** — convert passages into vector representations so you can search by meaning rather than exact keywords.\n\nFor hands-on examples of several of these techniques, see the prAxIs [Text Embeddings Workshop](https://ubcecon.github.io/praxis-ubc/docs/hist_workshop/text_embeddings_workshop.html) module.\n\n#### LLM-Based Correction\n\nFor high-value documents, Large Language Models can correct OCR errors using contextual understanding that rule-based methods lack.\n\n::: {.callout-note}\nThe cell below requires an `ANTHROPIC_API_KEY` environment variable set in your shell before launching the notebook. It calls Claude Haiku 4.5 and costs roughly **$0.001 per run** on a page of text. The code is commented out by default to avoid accidental API charges.\n:::\n\n::: {#c3550545 .cell execution_count=29}\n``` {.python .cell-code}\n# LLM-based OCR correction with Claude Haiku 4.5 \n# Requires: ANTHROPIC_API_KEY env var.\n#\n# import anthropic\n#\n# client = anthropic.Anthropic()          # reads ANTHROPIC_API_KEY from env\n#\n# correction_prompt = (\n#     \"The following text was extracted from a historical newspaper using OCR. \"\n#     \"Please correct any obvious OCR errors while preserving the original meaning \"\n#     \"and historical language. Do not modernize spelling or grammar.\\n\\n\"\n#     \"OCR TEXT:\\n\"\n#     f\"{extracted_text}\\n\\n\"\n#     \"CORRECTED TEXT:\"\n# )\n#\n# message = client.messages.create(\n#     model=\"claude-haiku-4-5\",\n#     max_tokens=2048,\n#     messages=[{\"role\": \"user\", \"content\": correction_prompt}],\n# )\n#\n# corrected_text = message.content[0].text\n#\n# # ── Display results ──────────────────────────────────────────────────\n# print(\"=== Corrected Text ===\\n\")\n# print(corrected_text)\n#\n# # ── Before / after snippet comparison ────────────────────────────────\n# snippet_len = 500\n# print(\"\\n\\n=== Before / After Comparison (first 500 chars) ===\")\n# print(f\"\\nBEFORE (raw OCR):\\n{extracted_text[:snippet_len]}\")\n# print(f\"\\nAFTER  (LLM corrected):\\n{corrected_text[:snippet_len]}\")\n```\n:::\n\n\nHere is the output from running the cell above on our EasyOCR newspaper extraction (first 5 sentences shown):\n\n```\n=== Corrected Text ===\n\nTwenty-Fifth Infantry Wins Athletic Honors\n\nChampions of Six Regiments Compete in Exciting Finals of Tournament in Honolulu.\n\nTHE COLORED REGIMENT WINS.\n\nScores Nearly Half of All the Points Made by Combined Competitors Two Omaha Boys in Contest.\n\nHOW THEY ENDED\nTwenty-fifth Inf. ..................... 70 points\nFirst Infantry ........................ 40 points\nSecond Infantry ....................... 29 points\nCoast Defense ......................... 14 points\n\nHonolulu, H. T., March 24—The Twenty-fifth Infantry February 26, made good its\npromises to carry off the major honors of the big military athletic meet, finishing\nin the finals against three other regiments with seventy points to its credit out\nof a total of one hundred and fifty-four.\n\n```\n\nThe LLM corrected several common OCR errors: `Infantcy` → `Infantry`, `AlI` → `All`, `T,,` → `T.,`, `24-_The` → `24—The`, and rejoined hyphenated line breaks (`Com-pete` → `Compete`, `Tour-nament` → `Tournament`). It also replaced colons with periods where appropriate and reconstructed the tabular score layout.\n\nLLM corrections can catch errors that rule-based methods miss, though they carry a small risk of hallucinating plausible text that was not in the original document.\n\n### 3.4 Evaluation: Measuring OCR Quality\n\nEvaluating OCR accuracy requires comparing extracted text against a known \"ground truth.\" We use two standard metrics:\n\n- **Character Error Rate (CER)**: Percentage of characters that are wrong\n- **Word Error Rate (WER)**: Percentage of words that are wrong\n\nWe first load our correct .txt version of the newspaper column.\n\n::: {#284fab49 .cell execution_count=30}\n``` {.python .cell-code}\nwith open(\"data/simple/ground_truth_clean.txt\", \"r\") as f:\n    ground_truth = f.read()\n\nprint(\"Ground Truth (first 500 characters):\")\nprint(ground_truth[:500])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGround Truth (first 500 characters):\nTwenty-Fifth Infantry Wins Athletic Honors\n\nChampions of Six Regiments Compete in Exciting Finals of Tournament in Honolulu.\n\nTHE COLORED REGIMENT WINS.\n\nScores Nearly Half of All the Points Made by Combined Competitors Two Omaha Boys in Contest.\n\nHOW THEY ENDED\nTwenty-fifth Inf. .....................70 points\nFirst Infantry..........................40 points\nSecond Infantry ......................29 points\nCoast Defense .........................14 points\n\nHonolulu, H. T., March 24â€”The Twenty-f\n```\n:::\n:::\n\n\nAnd then we compare it with our EasyOCR output to see how the model performed.\n\n::: {#ea7df882 .cell execution_count=31}\n``` {.python .cell-code}\ngt_normalized = ground_truth.lower().strip()\nocr_normalized = extracted_text.lower().strip()\n\nword_error_rate = wer(gt_normalized, ocr_normalized)\nchar_error_rate = cer(gt_normalized, ocr_normalized)\n\nprint(\"OCR Evaluation Metrics:\")\nprint(f\"\\nWord Error Rate (WER):      {word_error_rate:.2%}\")\nprint(f\"Character Error Rate (CER): {char_error_rate:.2%}\")\nprint(f\"\\nWord Accuracy:      {1 - word_error_rate:.2%}\")\nprint(f\"Character Accuracy: {1 - char_error_rate:.2%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOCR Evaluation Metrics:\n\nWord Error Rate (WER):      80.51%\nCharacter Error Rate (CER): 17.34%\n\nWord Accuracy:      19.49%\nCharacter Accuracy: 82.66%\n```\n:::\n:::\n\n\n::: {.callout-note}\n**Interpreting Error Rates:**\n\n- **CER < 5%**: Excellent - minimal manual correction needed\n- **CER 5-10%**: Good - some manual review recommended\n- **CER 10-20%**: Fair - significant post-processing needed\n- **CER > 20%**: Poor - consider improving source images or using different OCR approach\n:::\n\nWe can see that there are lots of errors from the EasyOCR output with only ~20% of words being correct and ~17% of characters being incorrect. Much of this error comes from how WER and CER are computed — differences in reading order, line breaks, and whitespace between the OCR output and ground truth all count as errors, even when the characters themselves were read correctly. This is why confidence was 91.4% but word accuracy is much lower.\n\n#### Confidence-Based Quality Flagging\n\nWe can use confidence scores to automatically flag words that likely need manual review. We set a threshold (in this case 70%), and we flag all other. These could also be fed into a LLM for editing.  \n\n::: {#c993e64a .cell execution_count=32}\n``` {.python .cell-code}\nlow_conf_threshold = 70\nlow_conf_words = ocr_df[ocr_df['conf'] < low_conf_threshold][['text', 'conf']]\n\nprint(f\"Words with confidence below {low_conf_threshold}%:\")\nprint(f\"  Total flagged: {len(low_conf_words)} out of {len(ocr_df)} ({len(low_conf_words)/len(ocr_df):.1%})\")\n\nif len(low_conf_words) > 0:\n    print(\"\\n  Sample low-confidence words:\")\n    display(low_conf_words.head(20))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWords with confidence below 70%:\n  Total flagged: 21 out of 246 (8.5%)\n\n  Sample low-confidence words:\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>text</th>\n      <th>conf</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Twenty-Fifth Infantcy</td>\n      <td>62.461939</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Scores Nearly Half of</td>\n      <td>68.373654</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>AlI the Points</td>\n      <td>53.332837</td>\n    </tr>\n    <tr>\n      <th>30</th>\n      <td>Second   Infantry</td>\n      <td>64.370979</td>\n    </tr>\n    <tr>\n      <th>36</th>\n      <td>H.</td>\n      <td>22.868835</td>\n    </tr>\n    <tr>\n      <th>37</th>\n      <td>T,,</td>\n      <td>65.192774</td>\n    </tr>\n    <tr>\n      <th>39</th>\n      <td>24-_The</td>\n      <td>21.203665</td>\n    </tr>\n    <tr>\n      <th>60</th>\n      <td>its   credit</td>\n      <td>61.451588</td>\n    </tr>\n    <tr>\n      <th>82</th>\n      <td>equal</td>\n      <td>52.342412</td>\n    </tr>\n    <tr>\n      <th>87</th>\n      <td>world.</td>\n      <td>58.739307</td>\n    </tr>\n    <tr>\n      <th>99</th>\n      <td>had</td>\n      <td>57.016563</td>\n    </tr>\n    <tr>\n      <th>138</th>\n      <td>charge.</td>\n      <td>59.880112</td>\n    </tr>\n    <tr>\n      <th>157</th>\n      <td>another,</td>\n      <td>63.084649</td>\n    </tr>\n    <tr>\n      <th>158</th>\n      <td>a5</td>\n      <td>38.334483</td>\n    </tr>\n    <tr>\n      <th>164</th>\n      <td>their expectation:</td>\n      <td>48.727530</td>\n    </tr>\n    <tr>\n      <th>169</th>\n      <td>took   place:</td>\n      <td>48.095689</td>\n    </tr>\n    <tr>\n      <th>184</th>\n      <td>the</td>\n      <td>53.323942</td>\n    </tr>\n    <tr>\n      <th>186</th>\n      <td>ers   spellbound</td>\n      <td>65.892382</td>\n    </tr>\n    <tr>\n      <th>187</th>\n      <td>a5</td>\n      <td>67.793630</td>\n    </tr>\n    <tr>\n      <th>188</th>\n      <td>he  raced</td>\n      <td>56.961843</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nWe have a list of our worst text regions. With many of them being incorrect or just partial segments.\n\nIn this cell we will clear the demo images and cache for notebook performace.\n\n::: {#fcf0dc89 .cell execution_count=33}\n``` {.python .cell-code}\n# cleanup demo images from Parts 1-3 and clear Jupyter output cache\ndel img, img_with_boxes, surya_img, surya_result, surya_results\ndel letter_pages, letter_img, surya_hw_img, surya_hw_result, surya_hw_results\ndel easyocr_hw_results\ndel ubc_img, ubc_gray, ubc_binary, ubc_enhanced\ndel menu_img, menu_gray\ndel noisy_img, noisy_gray, otsu_binary\ndel noisy_notext, noisy_notext_gray, denoised_notext\ndel noisy_text, noisy_text_gray, denoised_text\ndel skewed_img, deskewed\ndel multicolumn_img, multicolumn_pil\nget_ipython().history_manager.output_hist.clear()\ngc.collect()\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\n```\n:::\n\n\n## Part 4: Real-World Case Studies\n\nParts 1–3 used curated, relatively clean sample images. Real archival documents are messier: faded ink, unusual fonts, handwritten annotations, and centuries of wear. We have seen different OCR models along with many techniques, in this section we put it all together into a full OCR workflow which we run on two different historical documents spanning different eras and formats.\n\n### 4.1 Al Capone (Legal Documents)\n\nOur first real-world documents come from the Al Capone tax evasion case (1931). Legal documents of this era were typically typewritten, which should be favorable for OCR; but the scan quality and age of the documents introduce challenges. We have two items from this collection: the verdict (a GIF scan) and the first two pages of witness testimony (a PDF).\n\n#### Loading the Raw Documents\n\n::: {#6aeb2c02 .cell execution_count=34}\n``` {.python .cell-code}\nalcapone_verdict_raw = load_image(\"data/alcapone/alcapone_verdict.gif\")\n\ntestimony_pages = convert_from_path(\n    \"data/alcapone/alcapone_testimony.pdf\",\n    dpi=300,\n    first_page=1,\n    last_page=2,\n)\nalcapone_testimony_p1_raw = np.array(testimony_pages[0])\nalcapone_testimony_p2_raw = np.array(testimony_pages[1])\n\nalcapone_documents = {\n    \"verdict\": alcapone_verdict_raw,\n    \"testimony_p1\": alcapone_testimony_p1_raw,\n    \"testimony_p2\": alcapone_testimony_p2_raw,\n}\n\nfor label, img in alcapone_documents.items():\n    display_image(img, title=f\"Al Capone — {label} (raw)\", figsize=(10, 12))\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-35-output-1.png){}\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-35-output-2.png){}\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-35-output-3.png){}\n:::\n:::\n\n\nWe can see that most of the text is written on a typewriter, and we have testimonial signatures on the first page. \n\n#### Preprocessing\n\nBefore running OCR we chain the same techniques introduced in Part 3 into a single pipeline function. The ordering matters: we convert to grayscale first (required by all subsequent steps), deskew to correct any rotation, denoise to remove speckle, apply CLAHE to boost local contrast, and finally binarize with Otsu's method to produce a clean black-and-white image.\n\n::: {#fe60faef .cell execution_count=35}\n``` {.python .cell-code}\n# our pre-processing pipeline (reuses a single array to save memory)\ndef preprocess_for_ocr(image):\n    img = cv2.cvtColor(image, cv2.COLOR_RGB2GRAY)\n    img, angle = deskew(img)\n    img = cv2.fastNlMeansDenoising(img, h=10)\n    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))\n    img = clahe.apply(img)\n    _, img = cv2.threshold(img, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)\n    return img, angle\n```\n:::\n\n\n::: {#a383bf58 .cell execution_count=36}\n``` {.python .cell-code}\nalcapone_preprocessed = {}\nfor label, img in alcapone_documents.items():\n    processed, angle = preprocess_for_ocr(img)\n    alcapone_preprocessed[label] = processed\n    print(f\"{label}: detected skew angle = {angle:.2f}°\")\n\ndisplay_images_side_by_side(\n    alcapone_documents[\"verdict\"], alcapone_preprocessed[\"verdict\"],\n    \"Verdict — Raw\", \"Verdict — Preprocessed\", figsize=(14, 10))\ndisplay_images_side_by_side(\n    alcapone_documents[\"testimony_p1\"], alcapone_preprocessed[\"testimony_p1\"],\n    \"Testimony Page 1 — Raw\", \"Testimony Page 1 — Preprocessed\", figsize=(14, 10))\ndisplay_images_side_by_side(\n    alcapone_documents[\"testimony_p2\"], alcapone_preprocessed[\"testimony_p2\"],\n    \"Testimony Page 2 — Raw\", \"Testimony Page 2 — Preprocessed\", figsize=(14, 10))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nverdict: detected skew angle = 0.00°\ntestimony_p1: detected skew angle = 0.00°\ntestimony_p2: detected skew angle = 0.00°\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-37-output-2.png){}\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-37-output-3.png){}\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-37-output-4.png){}\n:::\n:::\n\n\nThe output is much clearer with minimal noise and just black text on a white background. This will vastly improve OCR quality. \n\n#### Layout Analysis\n\nBefore running OCR, we use Surya's `LayoutPredictor` (Section 3.2) to identify document regions (Text, Table, SectionHeader, etc). Rather than feeding the entire page to the OCR engine and hoping it avoids non-text areas, we extract only the text-bearing regions and process them in reading order. This produces cleaner results because the recognizer never sees figures, decorations, or blank margins. For large batches this will also reduce computation time. \n\n::: {#e98e0819 .cell execution_count=37}\n``` {.python .cell-code}\nTEXT_LABELS = {\"Text\", \"SectionHeader\", \"Title\", \"Caption\", \"Table\",\n               \"ListItem\", \"Footnote\", \"PageHeader\", \"PageFooter\"}\n\nfoundation_predictor = FoundationPredictor(checkpoint=settings.LAYOUT_MODEL_CHECKPOINT)\nlayout_predictor = LayoutPredictor(foundation_predictor)\n\nalcapone_layouts = {}\n\nfor label, processed_img in alcapone_preprocessed.items():\n    pil_img = Image.fromarray(cv2.cvtColor(processed_img, cv2.COLOR_GRAY2RGB))\n    layout_results = layout_predictor([pil_img])\n    layout = layout_results[0]\n    alcapone_layouts[label] = layout\n\n    print(f\"{label}: {len(layout.bboxes)} regions detected\")\n    for box in layout.bboxes:\n        marker = \"*\" if box.label in TEXT_LABELS else \" \"\n        print(f\"  {marker} [{box.label}] position {box.position}, confidence {box.confidence:.2%}\")\n\n    annotated = copy.deepcopy(pil_img)\n    draw = ImageDraw.Draw(annotated)\n    for box in layout.bboxes:\n        poly = [(int(p[0]), int(p[1])) for p in box.polygon]\n        color = \"green\" if box.label in TEXT_LABELS else \"red\"\n        draw.line(poly + [poly[0]], fill=color, width=4)\n        draw.text((poly[0][0], poly[0][1] - 14), f\"{box.label} ({box.position})\", fill=color)\n\n    display_image(np.array(annotated), title=f\"{label} — Layout Regions (green = OCR, red = skip)\", figsize=(10, 12))\n    print()\n\ndel layout_predictor, foundation_predictor\ngc.collect()\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\rRecognizing Layout:   0%|          | 0/1 [00:00<?, ?it/s]\rRecognizing Layout: 100%|██████████| 1/1 [00:10<00:00, 10.97s/it]\rRecognizing Layout: 100%|██████████| 1/1 [00:10<00:00, 10.98s/it]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nverdict: 4 regions detected\n  * [SectionHeader] position 0, confidence 88.45%\n    [Form] position 1, confidence 67.06%\n  * [Text] position 2, confidence 69.19%\n  * [Text] position 3, confidence 79.06%\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-38-output-4.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\rRecognizing Layout:   0%|          | 0/1 [00:00<?, ?it/s]\rRecognizing Layout: 100%|██████████| 1/1 [00:11<00:00, 11.92s/it]\rRecognizing Layout: 100%|██████████| 1/1 [00:11<00:00, 11.94s/it]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\ntestimony_p1: 11 regions detected\n  * [PageHeader] position 0, confidence 92.59%\n  * [Text] position 1, confidence 96.97%\n  * [Text] position 2, confidence 99.97%\n  * [Text] position 3, confidence 99.95%\n  * [Text] position 4, confidence 99.89%\n  * [Text] position 5, confidence 99.96%\n  * [Text] position 6, confidence 99.99%\n  * [Text] position 7, confidence 99.96%\n  * [Text] position 8, confidence 99.99%\n  * [Text] position 9, confidence 99.95%\n  * [PageFooter] position 10, confidence 68.48%\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-38-output-8.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\rRecognizing Layout:   0%|          | 0/1 [00:00<?, ?it/s]\rRecognizing Layout: 100%|██████████| 1/1 [00:11<00:00, 11.58s/it]\rRecognizing Layout: 100%|██████████| 1/1 [00:11<00:00, 11.58s/it]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\ntestimony_p2: 3 regions detected\n  * [Text] position 0, confidence 97.47%\n  * [Text] position 1, confidence 99.98%\n  * [Text] position 2, confidence 99.95%\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-38-output-12.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n```\n:::\n:::\n\n\nWe can see green and red boxes around regions of interest in our documents. This improves our OCR quality by giving the OCR model information on what to expect in each section (text, section header, Table, Footnote), and how to interpret and analyze this text. \n\n#### Layout-Guided OCR\n\nNow we run Surya's recognition on only the text-bearing regions identified above, in reading order. For each region we crop the preprocessed image using the layout bounding box, run OCR on that crop, and collect the results. This avoids feeding blank margins, decorative elements, or non-text areas to the model.\n\n::: {#a304fba3 .cell execution_count=38}\n``` {.python .cell-code}\nfoundation_predictor = FoundationPredictor()\nrec_predictor = RecognitionPredictor(foundation_predictor)\ndet_predictor = DetectionPredictor()\n\nalcapone_ocr_results = {}\n\nfor label, processed_img in alcapone_preprocessed.items():\n    layout = alcapone_layouts[label]\n    text_boxes = sorted(\n        [b for b in layout.bboxes if b.label in TEXT_LABELS],\n        key=lambda b: b.position,\n    )\n\n    all_texts = []\n    all_scores = []\n    h, w = processed_img.shape[:2]\n\n    for box in text_boxes:\n        xs = [p[0] for p in box.polygon]\n        ys = [p[1] for p in box.polygon]\n        x1 = max(0, int(min(xs)))\n        y1 = max(0, int(min(ys)))\n        x2 = min(w, int(max(xs)))\n        y2 = min(h, int(max(ys)))\n\n        crop = processed_img[y1:y2, x1:x2]\n        if crop.size == 0:\n            continue\n\n        pil_crop = Image.fromarray(cv2.cvtColor(crop, cv2.COLOR_GRAY2RGB))\n        results = rec_predictor([pil_crop], det_predictor=det_predictor)\n        result = results[0]\n\n        all_texts.extend([line.text for line in result.text_lines])\n        all_scores.extend([line.confidence for line in result.text_lines])\n\n    full_text = \" \".join(all_texts)\n\n    alcapone_ocr_results[label] = {\n        \"texts\": all_texts,\n        \"scores\": all_scores,\n        \"full_text\": full_text,\n    }\n\n    print(f\"{label}:\")\n    print(f\"  Text regions used: {len(text_boxes)} of {len(layout.bboxes)}\")\n    print(f\"  Lines detected   : {len(all_texts)}\")\n    print(f\"  Avg confidence   : {np.mean(all_scores):.2%}\" if all_scores else \"  Avg confidence   : N/A\")\n    print(f\"  Text preview     : {full_text[:300]}...\\n\")\n\ndel rec_predictor, det_predictor, foundation_predictor\ngc.collect()\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:02<00:00,  2.14s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:02<00:00,  2.14s/it]\n\rRecognizing Text:   0%|          | 0/3 [00:00<?, ?it/s]\rRecognizing Text:  33%|███▎      | 1/3 [00:03<00:07,  3.64s/it]\rRecognizing Text:  67%|██████▋   | 2/3 [00:05<00:02,  2.65s/it]\rRecognizing Text: 100%|██████████| 3/3 [00:06<00:00,  1.65s/it]\rRecognizing Text: 100%|██████████| 3/3 [00:06<00:00,  2.02s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.63s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.63s/it]\n\rRecognizing Text:   0%|          | 0/11 [00:00<?, ?it/s]\rRecognizing Text:   9%|▉         | 1/11 [00:03<00:39,  3.95s/it]\rRecognizing Text:  18%|█▊        | 2/11 [00:04<00:18,  2.08s/it]\rRecognizing Text:  27%|██▋       | 3/11 [00:04<00:09,  1.19s/it]\rRecognizing Text:  64%|██████▎   | 7/11 [00:04<00:01,  2.83it/s]\rRecognizing Text:  82%|████████▏ | 9/11 [00:05<00:00,  3.60it/s]\rRecognizing Text: 100%|██████████| 11/11 [00:08<00:00,  1.25it/s]\rRecognizing Text: 100%|██████████| 11/11 [00:08<00:00,  1.22it/s]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.88s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.88s/it]\n\rRecognizing Text:   0%|          | 0/4 [00:00<?, ?it/s]\rRecognizing Text:  25%|██▌       | 1/4 [00:01<00:05,  1.95s/it]\rRecognizing Text:  50%|█████     | 2/4 [00:02<00:01,  1.03it/s]\rRecognizing Text:  75%|███████▌  | 3/4 [00:02<00:00,  1.27it/s]\rRecognizing Text: 100%|██████████| 4/4 [00:02<00:00,  1.38it/s]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nverdict:\n  Text regions used: 3 of 4\n  Lines detected   : 18\n  Avg confidence   : 80.02%\n  Text preview     : IN THE DISTRICT COURT OF THE UNITED STATES FOR THE NORTHERN DISTRICT OF ILLINOIS PASTERN DIVISION _____ L'Oldeelling Sufrey & Martha 4. 6. Smart. (Burr Dugan Ambrou Mewhant. W.J. Henrich W/ Ma Vormely Leogs W. Larsen nate 6 Brown (a. ' & a. . . . . . . . . . . . . . . . . .  nater 6.1 Inverse Louis ...\n\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.48s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.48s/it]\n\rRecognizing Text:   0%|          | 0/2 [00:00<?, ?it/s]\rRecognizing Text:  50%|█████     | 1/2 [00:00<00:00,  1.94it/s]\rRecognizing Text: 100%|██████████| 2/2 [00:00<00:00,  3.87it/s]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.55s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.55s/it]\n\rRecognizing Text:   0%|          | 0/1 [00:00<?, ?it/s]\rRecognizing Text: 100%|██████████| 1/1 [00:01<00:00,  1.35s/it]\rRecognizing Text: 100%|██████████| 1/1 [00:01<00:00,  1.35s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.42s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.42s/it]\n\rRecognizing Text:   0%|          | 0/1 [00:00<?, ?it/s]\rRecognizing Text: 100%|██████████| 1/1 [00:00<00:00,  3.00it/s]\rRecognizing Text: 100%|██████████| 1/1 [00:00<00:00,  3.00it/s]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.79s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.79s/it]\n\rRecognizing Text:   0%|          | 0/1 [00:00<?, ?it/s]\rRecognizing Text: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it]\rRecognizing Text: 100%|██████████| 1/1 [00:02<00:00,  2.04s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.57s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.57s/it]\n\rRecognizing Text:   0%|          | 0/1 [00:00<?, ?it/s]\rRecognizing Text: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it]\rRecognizing Text: 100%|██████████| 1/1 [00:01<00:00,  1.96s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.44s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.44s/it]\n\rRecognizing Text:   0%|          | 0/2 [00:00<?, ?it/s]\rRecognizing Text:  50%|█████     | 1/2 [00:02<00:02,  2.42s/it]\rRecognizing Text: 100%|██████████| 2/2 [00:03<00:00,  1.71s/it]\rRecognizing Text: 100%|██████████| 2/2 [00:03<00:00,  1.81s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.45s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.45s/it]\n\rRecognizing Text:   0%|          | 0/1 [00:00<?, ?it/s]\rRecognizing Text: 100%|██████████| 1/1 [00:03<00:00,  3.02s/it]\rRecognizing Text: 100%|██████████| 1/1 [00:03<00:00,  3.02s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.48s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.48s/it]\n\rRecognizing Text:   0%|          | 0/6 [00:00<?, ?it/s]\rRecognizing Text:  17%|█▋        | 1/6 [00:08<00:44,  8.90s/it]\rRecognizing Text:  33%|███▎      | 2/6 [00:10<00:18,  4.63s/it]\rRecognizing Text:  50%|█████     | 3/6 [00:10<00:07,  2.57s/it]\rRecognizing Text:  67%|██████▋   | 4/6 [00:11<00:03,  1.69s/it]\rRecognizing Text:  83%|████████▎ | 5/6 [00:11<00:01,  1.16s/it]\rRecognizing Text: 100%|██████████| 6/6 [00:11<00:00,  1.87s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.45s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.45s/it]\n\rRecognizing Text:   0%|          | 0/3 [00:00<?, ?it/s]\rRecognizing Text:  33%|███▎      | 1/3 [00:02<00:05,  2.84s/it]\rRecognizing Text:  67%|██████▋   | 2/3 [00:05<00:02,  2.71s/it]\rRecognizing Text: 100%|██████████| 3/3 [00:06<00:00,  1.91s/it]\rRecognizing Text: 100%|██████████| 3/3 [00:06<00:00,  2.14s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.45s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.45s/it]\n\rRecognizing Text:   0%|          | 0/4 [00:00<?, ?it/s]\rRecognizing Text:  25%|██▌       | 1/4 [00:07<00:23,  7.83s/it]\rRecognizing Text:  50%|█████     | 2/4 [00:08<00:07,  3.77s/it]\rRecognizing Text:  75%|███████▌  | 3/4 [00:08<00:02,  2.10s/it]\rRecognizing Text: 100%|██████████| 4/4 [00:08<00:00,  1.31s/it]\rRecognizing Text: 100%|██████████| 4/4 [00:08<00:00,  2.24s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.39s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.39s/it]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\ntestimony_p1:\n  Text regions used: 11 of 11\n  Lines detected   : 22\n  Avg confidence   : 99.59%\n  Text preview     :   UNITED STATES  Before Judge Wilkerson ALPHONSE CAPONE Chicago, Friday, July 31, 1931. Ten o'clock A. M. Court met pursuant to adjournment. THE COURT: In the income tax cases, the motion to withdraw the plea of guilty is granted. As the cases are to be tried, the interests of justice require that t...\n\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.45s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.45s/it]\n\rRecognizing Text:   0%|          | 0/12 [00:00<?, ?it/s]\rRecognizing Text:   8%|▊         | 1/12 [00:12<02:20, 12.79s/it]\rRecognizing Text:  17%|█▋        | 2/12 [00:16<01:14,  7.42s/it]\rRecognizing Text:  25%|██▌       | 3/12 [00:16<00:37,  4.17s/it]\rRecognizing Text:  58%|█████▊    | 7/12 [00:17<00:06,  1.21s/it]\rRecognizing Text:  83%|████████▎ | 10/12 [00:17<00:01,  1.42it/s]\rRecognizing Text: 100%|██████████| 12/12 [00:17<00:00,  1.76it/s]\rRecognizing Text: 100%|██████████| 12/12 [00:17<00:00,  1.47s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.49s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.49s/it]\n\rRecognizing Text:   0%|          | 0/8 [00:00<?, ?it/s]\rRecognizing Text:  12%|█▎        | 1/8 [00:09<01:06,  9.46s/it]\rRecognizing Text:  25%|██▌       | 2/8 [00:11<00:29,  4.86s/it]\rRecognizing Text:  50%|█████     | 4/8 [00:11<00:07,  1.85s/it]\rRecognizing Text:  62%|██████▎   | 5/8 [00:11<00:04,  1.40s/it]\rRecognizing Text:  75%|███████▌  | 6/8 [00:11<00:02,  1.01s/it]\rRecognizing Text:  88%|████████▊ | 7/8 [00:11<00:00,  1.36it/s]\rRecognizing Text: 100%|██████████| 8/8 [00:12<00:00,  1.69it/s]\rRecognizing Text: 100%|██████████| 8/8 [00:12<00:00,  1.51s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.47s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.47s/it]\n\rRecognizing Text:   0%|          | 0/4 [00:00<?, ?it/s]\rRecognizing Text:  25%|██▌       | 1/4 [00:08<00:25,  8.59s/it]\rRecognizing Text:  50%|█████     | 2/4 [00:08<00:07,  3.60s/it]\rRecognizing Text:  75%|███████▌  | 3/4 [00:08<00:02,  2.05s/it]\rRecognizing Text: 100%|██████████| 4/4 [00:09<00:00,  1.32s/it]\rRecognizing Text: 100%|██████████| 4/4 [00:09<00:00,  2.28s/it]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\ntestimony_p2:\n  Text regions used: 3 of 3\n  Lines detected   : 24\n  Avg confidence   : 99.15%\n  Text preview     : sented to another grand jury. ( The in enumeration of overt acts the defendant and others are charged with substantial offenses within the period of the statute of limitations for which a heavier penalty is provided than that possible under the conspiracy indictment. The court will not believe unles...\n\n```\n:::\n:::\n\n\nWe show the verdict (Page 1) and testimony page 2 (Page 3) here as representative examples; testimony page 1 is omitted for brevity but follows the same pattern.\n\nOutput Text Preview Page 1 (Verdict): \"IN THE DISTRICT COURT OF THE UNITED STATES FOR THE NORTHERN DISTRICT OF ILLINOIS PASTERN DIVISION _____ L'Oldeelling Sufrey & Martha 4. 6. Smart. (Burr Dugan Ambrou Mewhant. W.J. Henrich W/ Ma Vormely Leogs W. Larsen nate 6 Brown\"\n\nOutput Text Preview Page 3 (Testimony p2): \"sented to another grand jury. ( The in enumeration of overt acts the defendant and others are charged with substantial offenses within the period of the statute of limitations for which a heavier penalty is provided than that possible under the conspiracy indictment.\"\n\nThe model gives us a confidence value along with a preview of the text. The first page with the handwritten signatures has a much lower confidence than the rest of the document (we have seen previously how OCR struggles on handwritten text). The text preview also looks quite high quality. The third page specifically has a 99.09% confidence.\n\n#### Post-Processing: Confidence Analysis\n\nWe divide every OCR line into three confidence tiers: high (>= 90%), medium (70–89%), and low (< 70%) - and flag the low-confidence lines for manual review. We could then send these low-confidence regions to an LLM for autocorrection. \n\n::: {#d8db8d46 .cell execution_count=39}\n``` {.python .cell-code}\nsummary_rows = []\nfor label, res in alcapone_ocr_results.items():\n    scores = np.array(res[\"scores\"])\n    n = len(scores)\n    high = int(np.sum(scores >= 0.90))\n    medium = int(np.sum((scores >= 0.70) & (scores < 0.90)))\n    low = int(np.sum(scores < 0.70))\n    summary_rows.append({\n        \"Document\": label,\n        \"Lines\": n,\n        \"Avg Confidence\": f\"{np.mean(scores):.2%}\" if n else \"N/A\",\n        \"High (>=90%)\": f\"{high} ({high/n:.0%})\" if n else \"0\",\n        \"Medium (70-89%)\": f\"{medium} ({medium/n:.0%})\" if n else \"0\",\n        \"Low (<70%)\": f\"{low} ({low/n:.0%})\" if n else \"0\",\n    })\n\nsummary_df = pd.DataFrame(summary_rows)\ndisplay(summary_df)\n\nprint(\"\\n Low-confidence lines (< 70%) for manual review\")\nfor label, res in alcapone_ocr_results.items():\n    low_lines = [(t, s) for t, s in zip(res[\"texts\"], res[\"scores\"]) if s < 0.70]\n    if low_lines:\n        print(f\"\\n{label} ({len(low_lines)} lines):\")\n        for text, score in low_lines:\n            print(f\"  [{score:.2%}] {text}\")\n    else:\n        print(f\"\\n{label}: no low-confidence lines\")\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Document</th>\n      <th>Lines</th>\n      <th>Avg Confidence</th>\n      <th>High (&gt;=90%)</th>\n      <th>Medium (70-89%)</th>\n      <th>Low (&lt;70%)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>verdict</td>\n      <td>18</td>\n      <td>80.02%</td>\n      <td>7 (39%)</td>\n      <td>6 (33%)</td>\n      <td>5 (28%)</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>testimony_p1</td>\n      <td>22</td>\n      <td>99.59%</td>\n      <td>22 (100%)</td>\n      <td>0 (0%)</td>\n      <td>0 (0%)</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>testimony_p2</td>\n      <td>24</td>\n      <td>99.15%</td>\n      <td>23 (96%)</td>\n      <td>1 (4%)</td>\n      <td>0 (0%)</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n Low-confidence lines (< 70%) for manual review\n\nverdict (5 lines):\n  [39.98%] _____\n  [53.30%] W/ Ma Vormely\n  [63.75%] (a. ' & a. . . . . . . . . . . . . . . . . . \n  [69.16%] nater 6.1\n  [69.80%] Inverse\n\ntestimony_p1: no low-confidence lines\n\ntestimony_p2: no low-confidence lines\n```\n:::\n:::\n\n\nThe handwritten signatures on the verdict are where we are having lower model performance.  \n\n#### Structured Output & Export\n\nFinally, we save each document's OCR results in both JSON (machine-readable) and plain text formats. The `create_surya_structured_output` function mirrors the `create_structured_output` helper from Part 3, adapted for Surya's line-level output with confidence scores.\n\n::: {#538262f7 .cell execution_count=40}\n``` {.python .cell-code}\ndef create_surya_structured_output(full_text, texts, scores, source_file):\n    words = word_tokenize(full_text)\n    sentences = sent_tokenize(full_text)\n    scores_arr = np.array(scores)\n\n    output = {\n        \"metadata\": {\n            \"source_file\": source_file,\n            \"ocr_engine\": \"surya\",\n            \"total_lines\": len(texts),\n            \"total_characters\": len(full_text),\n            \"total_words\": len(words),\n            \"total_sentences\": len(sentences),\n            \"average_confidence\": float(np.mean(scores_arr)) if len(scores_arr) else None,\n        },\n        \"text\": full_text.strip(),\n        \"sentences\": sentences,\n        \"lines\": [\n            {\"text\": t, \"confidence\": float(s)} for t, s in zip(texts, scores)\n        ],\n        \"confidence_distribution\": {\n            \"high (>=90%)\": int(np.sum(scores_arr >= 0.90)),\n            \"medium (70-89%)\": int(np.sum((scores_arr >= 0.70) & (scores_arr < 0.90))),\n            \"low (<70%)\": int(np.sum(scores_arr < 0.70)),\n        },\n    }\n    return output\n\nfile_labels = {\n    \"verdict\": \"alcapone_verdict\",\n    \"testimony_p1\": \"alcapone_testimony_p1\",\n    \"testimony_p2\": \"alcapone_testimony_p2\",\n}\n\nfor label, res in alcapone_ocr_results.items():\n    structured = create_surya_structured_output(\n        res[\"full_text\"], res[\"texts\"], res[\"scores\"],\n        source_file=file_labels[label],\n    )\n\n    json_path = f\"output/{file_labels[label]}.json\"\n    txt_path = f\"output/{file_labels[label]}.txt\"\n\n    with open(json_path, \"w\", encoding=\"utf-8\") as f:\n        json.dump(structured, f, indent=2, ensure_ascii=False)\n\n    with open(txt_path, \"w\", encoding=\"utf-8\") as f:\n        f.write(structured[\"text\"])\n\n    print(f\"Saved: {json_path}  ({structured['metadata']['total_words']} words)\")\n    print(f\"Saved: {txt_path}\")\n    print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSaved: output/alcapone_verdict.json  (77 words)\nSaved: output/alcapone_verdict.txt\n\nSaved: output/alcapone_testimony_p1.json  (138 words)\nSaved: output/alcapone_testimony_p1.txt\n\nSaved: output/alcapone_testimony_p2.json  (235 words)\nSaved: output/alcapone_testimony_p2.txt\n\n```\n:::\n:::\n\n\n#### Ground Truth Evaluation (Testimony)\n\nFor the testimony pages we have a human transcription, which lets us compute the same WER and CER metrics introduced in section 3.4. This is the real test: confidence scores tell us what the *model* thinks, but error rates tell us what actually happened.\n\n::: {#7be895b0 .cell execution_count=41}\n``` {.python .cell-code}\nwith open(\"data/alcapone/correct_text/correct_testimony.txt\", \"r\") as f:\n    testimony_ground_truth = f.read()\n\nprint(\"Ground truth (first 500 characters):\")\nprint(testimony_ground_truth[:500])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGround truth (first 500 characters):\n\nUNITED STATES          )\n                        )\n    vs                  )  Before Judge Wilkerson\n                        )\nALPHONSE CAPONE         )\n\n\n                Chicago, Friday, July 31, 1931.\n\n                    Ten o'clock A. M.\n\n            Court met pursuant to adjournment.\n\n            PRESENT:  As before.\n\n                    - - - - -\n\n        THE COURT:  In the income tax cases, the motion\nto withdraw the plea of guilty is granted.  As\nthe cases are to be tried, the interests\n```\n:::\n:::\n\n\nWe can preview the ground truth testimony and then concatenate the OCR output from both testimony pages and compare against the full ground truth.\n\n::: {#daba5263 .cell execution_count=42}\n``` {.python .cell-code}\ntestimony_ocr_text = (\n    alcapone_ocr_results[\"testimony_p1\"][\"full_text\"]\n    + \" \"\n    + alcapone_ocr_results[\"testimony_p2\"][\"full_text\"]\n)\n\ndef normalize_for_comparison(text):\n    text = text.lower().strip()\n    text = re.sub(r'\\s+', ' ', text)\n    return text\n\ngt_normalized = normalize_for_comparison(testimony_ground_truth)\nocr_normalized = normalize_for_comparison(testimony_ocr_text)\n\nword_error_rate = wer(gt_normalized, ocr_normalized)\nchar_error_rate = cer(gt_normalized, ocr_normalized)\n\nprint(\"TESTIMONY OCR EVALUATION\")\nprint(f\"\\nWord Error Rate (WER):      {word_error_rate:.2%}\")\nprint(f\"Word Accuracy:              {1 - word_error_rate:.2%}\")\nprint(f\"\\nCharacter Error Rate (CER): {char_error_rate:.2%}\")\nprint(f\"Character Accuracy:         {1 - char_error_rate:.2%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTESTIMONY OCR EVALUATION\n\nWord Error Rate (WER):      6.84%\nWord Accuracy:              93.16%\n\nCharacter Error Rate (CER): 2.84%\nCharacter Accuracy:         97.16%\n```\n:::\n:::\n\n\nThe preprocessing into OCR into post-processing pipeline is now complete for the Al Capone documents. For the verdict we relied on confidence scores alone, but the testimony evaluation with ground truth gives us a concrete measure of how well the pipeline actually performed.\n\nWe can see that we have a low WER and CER. This is a good score, and could be improved further with post-processing techniques like LLM correction. This worked well for the typewritten case, but let's try something even more ambitious.\n\n::: {#2ee3b0b7 .cell execution_count=43}\n``` {.python .cell-code}\n# cleanup Al Capone data and clear Jupyter output cache\ndel alcapone_documents, alcapone_preprocessed, alcapone_layouts\ndel alcapone_ocr_results, testimony_ground_truth, testimony_ocr_text\nget_ipython().history_manager.output_hist.clear()\ngc.collect()\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\n```\n:::\n\n\n### 4.2 Medieval Medical Manuscripts\n\nOur most challenging case: pages from medieval medical and astrological texts. Unlike the typewritten Al Capone documents, these are handwritten in medieval scripts with abbreviations, Latin text, and marginal annotations. We apply the same preprocessing, Surya OCR, confidence analysis, export pipeline used above. Here we do not have a ground truth and will have to rely on confidence scores and an eye test. \n\nWe will be using *Cirogia vulgare. Ricettario. Antidotarium vulgare* which was published between 1300 and 1350 in Latin and Medical/Astrological texts in English published between 1551 and 1553. \n\nTo be clear this is difficult for OCR and we are not expecting an excellent result using a relatively simple and non-computationally intensive model (Surya) that is not specifically trained for medieval text like this. \n\n#### Loading the Raw Documents\n\nWe load and display our documents:\n\n::: {#4a834499 .cell execution_count=44}\n``` {.python .cell-code}\nmedieval_chirurgia_raw = load_image(\"data/medieval_medical_manuscripts/cirogia_vulgare_1.jpg\")\nmedieval_calendar_raw = load_image(\"data/medieval_medical_manuscripts/calendars_3.jpg\")\n\nmedieval_documents = {\n    \"chirurgia_vulgare\": medieval_chirurgia_raw,\n    \"calendar_3\": medieval_calendar_raw,\n}\n\nfor label, img in medieval_documents.items():\n    display_image(img, title=f\"Medieval — {label} (raw)\", figsize=(10, 12))\n```\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-45-output-1.png){}\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-45-output-2.png){}\n:::\n:::\n\n\n#### Preprocessing\n\nWe reuse the `preprocess_for_ocr` pipeline defined in section 4.1. Medieval manuscripts may have significant skew from uneven binding and faded ink, so the deskew and CLAHE steps are especially important here.\n\n::: {#a5ade857 .cell execution_count=45}\n``` {.python .cell-code}\nmedieval_preprocessed = {}\nfor label, img in medieval_documents.items():\n    processed, angle = preprocess_for_ocr(img)\n    medieval_preprocessed[label] = processed\n    print(f\"{label}: detected skew angle = {angle:.2f}°\")\n\ndisplay_images_side_by_side(\n    medieval_documents[\"chirurgia_vulgare\"], medieval_preprocessed[\"chirurgia_vulgare\"],\n    \"Chirurgia Vulgare — Raw\", \"Chirurgia Vulgare — Preprocessed\", figsize=(14, 10)\n)\ndisplay_images_side_by_side(\n    medieval_documents[\"calendar_3\"], medieval_preprocessed[\"calendar_3\"],\n    \"Calendar 3 — Raw\", \"Calendar 3 — Preprocessed\", figsize=(14, 10)\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nchirurgia_vulgare: detected skew angle = -1.00°\ncalendar_3: detected skew angle = -2.00°\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-46-output-2.png){}\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-46-output-3.png){}\n:::\n:::\n\n\nOnce again the output is far clearer with minimal noise and black text on a pure white background. \n\n#### Layout Analysis\n\nLayout analysis on medieval manuscripts is especially valuable. These documents mix body text, marginal annotations, decorated initials, and tabular elements (the calendar page). By identifying regions first, we can feed only text-bearing areas to the OCR engine and skip illuminations and decorations that would produce garbage output.\n\n::: {#61a69bc7 .cell execution_count=46}\n``` {.python .cell-code}\nfoundation_predictor = FoundationPredictor(checkpoint=settings.LAYOUT_MODEL_CHECKPOINT)\nlayout_predictor = LayoutPredictor(foundation_predictor)\n\nmedieval_layouts = {}\n\nfor label, processed_img in medieval_preprocessed.items():\n    pil_img = Image.fromarray(cv2.cvtColor(processed_img, cv2.COLOR_GRAY2RGB))\n    layout_results = layout_predictor([pil_img])\n    layout = layout_results[0]\n    medieval_layouts[label] = layout\n\n    print(f\"--- {label}: {len(layout.bboxes)} regions detected ---\")\n    for box in layout.bboxes:\n        marker = \"*\" if box.label in TEXT_LABELS else \" \"\n        print(f\"  {marker} [{box.label}] position {box.position}, confidence {box.confidence:.2%}\")\n\n    annotated = copy.deepcopy(pil_img)\n    draw = ImageDraw.Draw(annotated)\n    for box in layout.bboxes:\n        poly = [(int(p[0]), int(p[1])) for p in box.polygon]\n        color = \"green\" if box.label in TEXT_LABELS else \"red\"\n        draw.line(poly + [poly[0]], fill=color, width=4)\n        draw.text((poly[0][0], poly[0][1] - 14), f\"{box.label} ({box.position})\", fill=color)\n\n    display_image(np.array(annotated), title=f\"{label} — Layout Regions (green = OCR, red = skip)\", figsize=(10, 12))\n    print()\n\ndel layout_predictor, foundation_predictor\ngc.collect()\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\rRecognizing Layout:   0%|          | 0/1 [00:00<?, ?it/s]\rRecognizing Layout: 100%|██████████| 1/1 [00:11<00:00, 11.77s/it]\rRecognizing Layout: 100%|██████████| 1/1 [00:11<00:00, 11.77s/it]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n--- chirurgia_vulgare: 2 regions detected ---\n  * [Text] position 0, confidence 99.73%\n  * [Text] position 1, confidence 99.62%\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-47-output-3.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\rRecognizing Layout:   0%|          | 0/1 [00:00<?, ?it/s]\rRecognizing Layout: 100%|██████████| 1/1 [00:12<00:00, 12.38s/it]\rRecognizing Layout: 100%|██████████| 1/1 [00:12<00:00, 12.38s/it]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n--- calendar_3: 13 regions detected ---\n  * [Text] position 0, confidence 53.27%\n  * [Text] position 1, confidence 54.22%\n  * [Text] position 2, confidence 98.65%\n  * [Text] position 3, confidence 55.33%\n  * [Text] position 4, confidence 97.67%\n    [Picture] position 5, confidence 57.38%\n  * [Text] position 6, confidence 98.95%\n    [Picture] position 7, confidence 81.46%\n  * [Text] position 8, confidence 99.75%\n    [Picture] position 9, confidence 89.71%\n  * [Text] position 10, confidence 99.89%\n    [Picture] position 11, confidence 84.52%\n  * [Text] position 12, confidence 99.37%\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](ocr_notebook_files/figure-html/cell-47-output-7.png){}\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n```\n:::\n:::\n\n\nWith our layout set we can run the proper OCR. \n\n#### Layout-Guided OCR\n\n::: {#7c4f4299 .cell execution_count=47}\n``` {.python .cell-code}\nfoundation_predictor = FoundationPredictor()\nrec_predictor = RecognitionPredictor(foundation_predictor)\ndet_predictor = DetectionPredictor()\n\nmedieval_ocr_results = {}\n\nfor label, processed_img in medieval_preprocessed.items():\n    layout = medieval_layouts[label]\n    text_boxes = sorted(\n        [b for b in layout.bboxes if b.label in TEXT_LABELS],\n        key=lambda b: b.position,\n    )\n\n    all_texts = []\n    all_scores = []\n    h, w = processed_img.shape[:2]\n\n    for box in text_boxes:\n        xs = [p[0] for p in box.polygon]\n        ys = [p[1] for p in box.polygon]\n        x1 = max(0, int(min(xs)))\n        y1 = max(0, int(min(ys)))\n        x2 = min(w, int(max(xs)))\n        y2 = min(h, int(max(ys)))\n\n        crop = processed_img[y1:y2, x1:x2]\n        if crop.size == 0:\n            continue\n\n        pil_crop = Image.fromarray(cv2.cvtColor(crop, cv2.COLOR_GRAY2RGB))\n        results = rec_predictor([pil_crop], det_predictor=det_predictor)\n        result = results[0]\n\n        all_texts.extend([line.text for line in result.text_lines])\n        all_scores.extend([line.confidence for line in result.text_lines])\n\n    full_text = \" \".join(all_texts)\n\n    medieval_ocr_results[label] = {\n        \"texts\": all_texts,\n        \"scores\": all_scores,\n        \"full_text\": full_text,\n    }\n\n    print(f\"--- {label} ---\")\n    print(f\"  Text regions used: {len(text_boxes)} of {len(layout.bboxes)}\")\n    print(f\"  Lines detected   : {len(all_texts)}\")\n    print(f\"  Avg confidence   : {np.mean(all_scores):.2%}\" if all_scores else \"  Avg confidence   : N/A\")\n    print(f\"  Text preview     : {full_text[:300]}...\\n\")\n\ndel rec_predictor, det_predictor, foundation_predictor\ngc.collect()\nif torch.cuda.is_available():\n    torch.cuda.empty_cache()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:04<00:00,  4.96s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:04<00:00,  4.96s/it]\n\rRecognizing Text:   0%|          | 0/22 [00:00<?, ?it/s]\rRecognizing Text:   5%|▍         | 1/22 [00:16<05:52, 16.80s/it]\rRecognizing Text:  23%|██▎       | 5/22 [00:17<00:43,  2.55s/it]\rRecognizing Text:  55%|█████▍    | 12/22 [00:17<00:08,  1.20it/s]\rRecognizing Text:  68%|██████▊   | 15/22 [00:17<00:04,  1.64it/s]\rRecognizing Text:  86%|████████▋ | 19/22 [00:17<00:01,  2.44it/s]\rRecognizing Text: 100%|██████████| 22/22 [00:17<00:00,  3.16it/s]\rRecognizing Text: 100%|██████████| 22/22 [00:17<00:00,  1.23it/s]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:02<00:00,  2.56s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:02<00:00,  2.56s/it]\n\rRecognizing Text:   0%|          | 0/22 [00:00<?, ?it/s]\rRecognizing Text:   5%|▍         | 1/22 [00:15<05:32, 15.85s/it]\rRecognizing Text:   9%|▉         | 2/22 [00:16<02:12,  6.65s/it]\rRecognizing Text:  18%|█▊        | 4/22 [00:16<00:45,  2.55s/it]\rRecognizing Text:  32%|███▏      | 7/22 [00:16<00:16,  1.13s/it]\rRecognizing Text:  64%|██████▎   | 14/22 [00:16<00:03,  2.44it/s]\rRecognizing Text:  82%|████████▏ | 18/22 [00:16<00:01,  3.51it/s]\rRecognizing Text:  91%|█████████ | 20/22 [00:17<00:00,  4.02it/s]\rRecognizing Text: 100%|██████████| 22/22 [00:19<00:00,  2.33it/s]\rRecognizing Text: 100%|██████████| 22/22 [00:19<00:00,  1.14it/s]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n--- chirurgia_vulgare ---\n  Text regions used: 2 of 2\n  Lines detected   : 44\n  Avg confidence   : 85.47%\n  Text preview     : fichelosso ouesto aten similiance cola sinci bid trure whamest nesia tructo Avouani Suarvan chellangue no aborron troppooue roaltro chempevins tisse losso. sicometra mountmento, esuces listimo pāno vilins. onero vitera chemol to mellio-uniavum mattre elosso colape na ouero cotenta fi come dirintozeo...\n\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.52s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.52s/it]\n\rRecognizing Text:   0%|          | 0/2 [00:00<?, ?it/s]\rRecognizing Text:  50%|█████     | 1/2 [00:10<00:10, 10.20s/it]\rRecognizing Text: 100%|██████████| 2/2 [00:15<00:00,  7.31s/it]\rRecognizing Text: 100%|██████████| 2/2 [00:15<00:00,  7.75s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.47s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.47s/it]\n\rRecognizing Text:   0%|          | 0/2 [00:00<?, ?it/s]\rRecognizing Text:  50%|█████     | 1/2 [00:00<00:00,  1.56it/s]\rRecognizing Text: 100%|██████████| 2/2 [00:00<00:00,  3.12it/s]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.54s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.54s/it]\n\rRecognizing Text:   0%|          | 0/2 [00:00<?, ?it/s]\rRecognizing Text:  50%|█████     | 1/2 [00:14<00:14, 14.45s/it]\rRecognizing Text: 100%|██████████| 2/2 [00:19<00:00,  9.08s/it]\rRecognizing Text: 100%|██████████| 2/2 [00:19<00:00,  9.88s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.40s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.40s/it]\n\rRecognizing Text:   0%|          | 0/2 [00:00<?, ?it/s]\rRecognizing Text:  50%|█████     | 1/2 [00:00<00:00,  1.54it/s]\rRecognizing Text: 100%|██████████| 2/2 [00:00<00:00,  2.69it/s]\rRecognizing Text: 100%|██████████| 2/2 [00:00<00:00,  2.42it/s]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.52s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.52s/it]\n\rRecognizing Text:   0%|          | 0/5 [00:00<?, ?it/s]\rRecognizing Text:  20%|██        | 1/5 [00:05<00:23,  5.98s/it]\rRecognizing Text:  40%|████      | 2/5 [00:11<00:17,  5.82s/it]\rRecognizing Text:  80%|████████  | 4/5 [00:12<00:02,  2.28s/it]\rRecognizing Text: 100%|██████████| 5/5 [00:18<00:00,  3.66s/it]\rRecognizing Text: 100%|██████████| 5/5 [00:18<00:00,  3.75s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.53s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.54s/it]\n\rRecognizing Text:   0%|          | 0/3 [00:00<?, ?it/s]\rRecognizing Text:  33%|███▎      | 1/3 [00:06<00:12,  6.15s/it]\rRecognizing Text:  67%|██████▋   | 2/3 [00:12<00:06,  6.45s/it]\rRecognizing Text: 100%|██████████| 3/3 [00:29<00:00, 11.05s/it]\rRecognizing Text: 100%|██████████| 3/3 [00:29<00:00,  9.78s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.58s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.58s/it]\n\rRecognizing Text:   0%|          | 0/6 [00:00<?, ?it/s]\rRecognizing Text:  17%|█▋        | 1/6 [00:06<00:32,  6.47s/it]\rRecognizing Text:  33%|███▎      | 2/6 [00:07<00:14,  3.52s/it]\rRecognizing Text:  50%|█████     | 3/6 [00:12<00:11,  3.92s/it]\rRecognizing Text:  67%|██████▋   | 4/6 [00:12<00:05,  2.51s/it]\rRecognizing Text:  83%|████████▎ | 5/6 [00:13<00:01,  1.78s/it]\rRecognizing Text: 100%|██████████| 6/6 [00:20<00:00,  3.63s/it]\rRecognizing Text: 100%|██████████| 6/6 [00:20<00:00,  3.40s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.52s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.52s/it]\n\rRecognizing Text:   0%|          | 0/4 [00:00<?, ?it/s]\rRecognizing Text:  25%|██▌       | 1/4 [00:06<00:18,  6.11s/it]\rRecognizing Text:  50%|█████     | 2/4 [00:11<00:11,  5.80s/it]\rRecognizing Text:  75%|███████▌  | 3/4 [00:11<00:03,  3.20s/it]\rRecognizing Text: 100%|██████████| 4/4 [00:26<00:00,  7.60s/it]\rRecognizing Text: 100%|██████████| 4/4 [00:26<00:00,  6.54s/it]\n\rDetecting bboxes:   0%|          | 0/1 [00:00<?, ?it/s]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.50s/it]\rDetecting bboxes: 100%|██████████| 1/1 [00:01<00:00,  1.50s/it]\n\rRecognizing Text:   0%|          | 0/7 [00:00<?, ?it/s]\rRecognizing Text:  14%|█▍        | 1/7 [00:06<00:41,  6.97s/it]\rRecognizing Text:  29%|██▊       | 2/7 [00:12<00:30,  6.15s/it]\rRecognizing Text:  57%|█████▋    | 4/7 [00:13<00:07,  2.49s/it]\rRecognizing Text:  71%|███████▏  | 5/7 [00:13<00:03,  1.76s/it]\rRecognizing Text:  86%|████████▌ | 6/7 [00:13<00:01,  1.37s/it]\rRecognizing Text: 100%|██████████| 7/7 [00:13<00:00,  1.01it/s]\rRecognizing Text: 100%|██████████| 7/7 [00:13<00:00,  1.99s/it]\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n--- calendar_3 ---\n  Text regions used: 9 of 13\n  Lines detected   : 33\n  Avg confidence   : 71.58%\n  Text preview     : The Pathures and properties Of the Fixed Starres. Ander the 16 degre of V. Snieb rifeth & forme topes offi<br>the nature of 4. Invites a hora constant to в п Under the 16. degre of V. driet rifeth, & flarre topes off<br>the nature of 4. Inpiter 6: h. Galmene they of be borne<br>sonder his confectati...\n\n```\n:::\n:::\n\n\nText Output Sample Manuscript: \"fichelosso ouesto aten similiance cola sinci bid trure whamest nesia tructo Avouani Suarvan chellangue no aborron troppooue roaltro chempevins tisse losso. sicometra mountmento, esuces listimo pāno vilins. onero vitera chemol to mellio-uniavum mattre elosso colape na ouero cotenta fi come dirintozeo..\"\n\nText Output Sample Horoscope: \"The Pathures and properties Of the Fixed Starres. Ander the 16 degre of V. Snieb rifeth & forme topes offi<br>the nature of 4. Invites a hora constant to в п Under the 16. degre of V. driet rifeth, & flarre topes off<br>the nature of 4. Inpiter 6: h. Galmene they of be borne<br>sonder his confectati...\"\n\nThe output here does not seem bad, it is in Latin for the first document which is a good sign. If we run the output for the first document into DeepTL we end up with: \n\n\"This little thing looks like a tiny, two-sided, double-edged blade. Avouani Suarvan's tongue doesn't really hate anything, but it can cut through other things. As for the mounting, the result is a very thin sheet. I'm adding a new layer to the best-of-the-best matrix, and I've also included some content, as if to make it more detailed.\"\n\nAs for the second image (the horoscope) it is in English so it will be easier to understand. The output is messy with obvious issues, but it is in very old English and can be roughly understood. \n\nWe sadly do not have the actual text so we can not compare like with the Al Capone case, but for a very difficult test we have done relatively well. \n\n#### Post-Processing: Confidence Analysis\n\nMedieval handwriting is far harder for OCR engines than typewritten text, so we expect lower confidence scores and more low-confidence lines than the Al Capone documents.\n\n::: {#63553125 .cell execution_count=48}\n``` {.python .cell-code}\nsummary_rows = []\nfor label, res in medieval_ocr_results.items():\n    scores = np.array(res[\"scores\"])\n    n = len(scores)\n    high = int(np.sum(scores >= 0.90))\n    medium = int(np.sum((scores >= 0.70) & (scores < 0.90)))\n    low = int(np.sum(scores < 0.70))\n    summary_rows.append({\n        \"Document\": label,\n        \"Lines\": n,\n        \"Avg Confidence\": f\"{np.mean(scores):.2%}\" if n else \"N/A\",\n        \"High (>=90%)\": f\"{high} ({high/n:.0%})\" if n else \"0\",\n        \"Medium (70-89%)\": f\"{medium} ({medium/n:.0%})\" if n else \"0\",\n        \"Low (<70%)\": f\"{low} ({low/n:.0%})\" if n else \"0\",\n    })\n\nsummary_df = pd.DataFrame(summary_rows)\ndisplay(summary_df)\n\nprint(\"\\nLow-confidence lines (< 70%) for manual review\")\nfor label, res in medieval_ocr_results.items():\n    low_lines = [(t, s) for t, s in zip(res[\"texts\"], res[\"scores\"]) if s < 0.70]\n    if low_lines:\n        print(f\"\\n{label} ({len(low_lines)} lines):\")\n        for text, score in low_lines:\n            print(f\"  [{score:.2%}] {text}\")\n    else:\n        print(f\"\\n{label}: no low-confidence lines\")\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Document</th>\n      <th>Lines</th>\n      <th>Avg Confidence</th>\n      <th>High (&gt;=90%)</th>\n      <th>Medium (70-89%)</th>\n      <th>Low (&lt;70%)</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>chirurgia_vulgare</td>\n      <td>44</td>\n      <td>85.47%</td>\n      <td>13 (30%)</td>\n      <td>27 (61%)</td>\n      <td>4 (9%)</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>calendar_3</td>\n      <td>33</td>\n      <td>71.58%</td>\n      <td>5 (15%)</td>\n      <td>17 (52%)</td>\n      <td>11 (33%)</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nLow-confidence lines (< 70%) for manual review\n\nchirurgia_vulgare (4 lines):\n  [66.39%] bid trure whamest\n  [65.40%] mattre elosso colape\n  [58.08%] and religions day\n  [67.92%] pano themeso intra\n\ncalendar_3 (11 lines):\n  [24.86%] в\n  [22.31%] п\n  [34.96%] ě\n  [19.60%] ħ.\n  [43.79%] <b>Vanius</b>\n  [65.96%] 1.0? mare no coniogned in this flare: Bey Bat be borne und\n  [41.49%] <b>Manua</b>\n  [69.14%] fell duoth Parte of & nature of S' martie & Gionificts\n  [32.36%] ut II\n  [60.47%] CHIRU\n  [69.25%] Und Herre offent wingo wifell of fare fixed off &\n```\n:::\n:::\n\n\nHere again we can see the lowest confidence regions. \n\n#### Structured Output & Export\n\nWe reuse the `create_surya_structured_output` function from section 4.1 to save the medieval results.\n\n::: {#7bcdde66 .cell execution_count=49}\n``` {.python .cell-code}\nmedieval_file_labels = {\n    \"chirurgia_vulgare\": \"medieval_chirurgia_vulgare\",\n    \"calendar_3\": \"medieval_calendar_3\",\n}\n\nfor label, res in medieval_ocr_results.items():\n    structured = create_surya_structured_output(\n        res[\"full_text\"], res[\"texts\"], res[\"scores\"],\n        source_file=medieval_file_labels[label],\n    )\n\n    json_path = f\"output/{medieval_file_labels[label]}.json\"\n    txt_path = f\"output/{medieval_file_labels[label]}.txt\"\n\n    with open(json_path, \"w\", encoding=\"utf-8\") as f:\n        json.dump(structured, f, indent=2, ensure_ascii=False)\n\n    with open(txt_path, \"w\", encoding=\"utf-8\") as f:\n        f.write(structured[\"text\"])\n\n    print(f\"Saved: {json_path}  ({structured['metadata']['total_words']} words)\")\n    print(f\"Saved: {txt_path}\")\n    print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nSaved: output/medieval_chirurgia_vulgare.json  (132 words)\nSaved: output/medieval_chirurgia_vulgare.txt\n\nSaved: output/medieval_calendar_3.json  (481 words)\nSaved: output/medieval_calendar_3.txt\n\n```\n:::\n:::\n\n\nThe medieval manuscripts are the most challenging documents we tested. The confidence scores here are much lower than the Al Capone results, reflecting the fundamental challenge of applying modern OCR to handwritten medieval text. For documents like these, OCR output is best treated as a rough draft that requires significant human review and correction.\n\n::: {.callout-note}\n**Medieval scripts and OCR limitations.** Standard OCR models, including Surya, are trained primarily on modern printed and typewritten text. Medieval handwriting uses ligatures, abbreviations, and letter forms that differ substantially from modern scripts. Specialized models trained on historical handwriting (such as Kraken or Transkribus) may perform better on these documents.\n:::\n\n## Part 5: Batch Processing & Scalability\n\nThis next section is more technical and might not be useful for all readers.\n\nWhen working with historical archives, you rarely process just one document. Real-world digitization projects often involve thousands or even millions of pages. This section covers strategies for scaling your OCR workflow to handle large document collections efficiently and reliably.\n\n### 5.1 Parallelization Strategies\n\nProcessing documents one at a time is slow. Modern computers have multiple CPU cores and often GPUs that can work simultaneously. **Parallelization** divides work across these resources to dramatically reduce processing time.\n\n#### CPU vs GPU Parallelization\n\nImage pre-processing tasks (grayscale conversion, binarization, denoising) are **CPU-bound** meaning, they primarily use the processor rather than memory or disk. Python's `concurrent.futures` module provides a straightforward way to parallelize these tasks across multiple CPU cores. The `ThreadPoolExecutor` is suitable for I/O-bound tasks (reading/writing files), while `ProcessPoolExecutor` is better for CPU-bound computation like image processing. \n\nOCR models like EasyOCR and Surya OCR can use GPUs for faster inference. Unlike CPU parallelization where you run multiple processes, GPU parallelization typically involves **batching**—feeding multiple images through the model simultaneously.\n\n| Approach | Best For | Python Tools |\n|----------|----------|--------------|\n| **CPU Multi-processing** | Image pre-processing, heavy computation | `concurrent.futures.ProcessPoolExecutor`, `multiprocessing` |\n| **CPU Threading** | Network requests, file I/O | `concurrent.futures.ThreadPoolExecutor`, `threading` |\n| **GPU Batching** | Model inference (OCR) | Native batch support in Surya OCR; loop-based in EasyOCR |\n\n::: {.callout-note}\n**Linux vs Windows**: Parallelization often performs better on Linux systems. Windows has higher overhead for creating new processes, and some libraries (like `multiprocessing`) behave differently. If you're processing very large archives, consider using a Linux server or cloud VM. This is more accessible than ever with tools like [Windows Subsystem for Linux 2](https://learn.microsoft.com/en-us/windows/wsl/install)\n:::\n\n#### Batch Size Tuning\n\nWhen using GPU-accelerated models, the **batch size**; how many images you process at once can significantly affect performance. Larger batches use GPU memory more efficiently but require more VRAM.\n\n**Batch size guidelines:**\n\n- 4GB GPU: batch_size = 2-4\n- 8GB GPU: batch_size = 4-8\n- 16GB+ GPU: batch_size = 8-16\n\nStart small and increase until you encounter memory limits.\n\n### 5.2 Progress Tracking and Logging\n\nWhen processing thousands of documents, visibility into your pipeline's progress is essential. You need to know how far along you are, which files have been processed, and whether any errors occurred.\n\n#### Progress Bars with tqdm\n\nThe `tqdm` library provides elegant progress bars that work in terminals, Jupyter notebooks, and scripts. It shows elapsed time, estimated time remaining, and processing speed. Simply wrap any iterable with `tqdm()` to add a progress bar.\n\n#### Structured Logging\n\nFor production pipelines, Python's built-in `logging` module provides structured, configurable logging that can write to files, include timestamps, and categorize messages by severity (DEBUG, INFO, WARNING, ERROR). Configure separate handlers for console output (important messages only) and file output (detailed logs).\n\n#### Manifest Files for Tracking\n\nA **manifest file** (CSV or JSON) tracks the status of each document, including metadata like confidence scores, processing time, and any errors. This allows you to resume interrupted jobs and audit your results. Key fields to track:\n\n| Field | Purpose |\n|-------|---------|\n| `filename` | Original file identifier |\n| `status` | success / failed / pending |\n| `timestamp` | When processing occurred |\n| `processing_time_sec` | Duration for performance analysis |\n| `avg_confidence` | OCR quality metric |\n| `error_message` | Details if processing failed |\n\n### 5.3 File Organization\n\nA well-organized file structure makes batch processing manageable and reproducible. Poor organization leads to confusion, lost outputs, and difficulty resuming failed jobs.\n\n#### Mirror the Input Directory\nWhen processing a large archive, maintain a parallel output directory structure that mirrors the input. This makes it easy to find the output for any given input file.\n\n```\nproject/\n├── input/\n│   ├── archive_1/\n│   │   ├── page_001.jp2\n│   │   ├── page_002.jp2\n│   │   └── ...\n│   └── archive_2/\n│       ├── doc_001.pdf\n│       └── ...\n├── output/\n│   ├── archive_1/\n│   │   ├── page_001_preprocessed.png\n│   │   ├── page_001_ocr.json\n│   │   ├── page_001_text.txt\n│   │   └── ...\n│   └── archive_2/\n│       └── ...\n├── logs/\n│   └── ocr_pipeline_20260203.log\n└── manifest.csv\n```\n\n#### Consistent Naming Conventions\n\nUse consistent, descriptive naming that includes the processing stage:\n\n| Stage | Naming Pattern | Example |\n|-------|----------------|---------|\n| Original | `{name}.{ext}` | `page_001.jp2` |\n| Preprocessed | `{name}_preprocessed.png` | `page_001_preprocessed.png` |\n| OCR Output | `{name}_ocr.json` | `page_001_ocr.json` |\n| Extracted Text | `{name}_text.txt` | `page_001_text.txt` |\n| Corrected Text | `{name}_corrected.txt` | `page_001_corrected.txt` |\n\n### 5.4 Workflow Orchestration\n\nA complete OCR pipeline combines preprocessing, text extraction, and post-processing into an automated workflow. Good orchestration includes checkpoints for resumability and proper error handling.\n\n#### Pipeline Architecture (Pseudocode)\n\nAn example pipeline would look something like this: \n\n```\nFUNCTION run_ocr_pipeline(input_directory, output_directory):\n\n    # Initialize tracking\n    manifest = load_or_create_manifest(output_directory)\n    checkpoint = load_checkpoint(output_directory)\n\n    # Initialize models once (EXPENSIVE: do not recreate per file)\n    foundation   = FoundationPredictor()\n    rec_pred     = RecognitionPredictor(foundation)\n    det_pred     = DetectionPredictor()\n    layout_found = FoundationPredictor(checkpoint=LAYOUT_CHECKPOINT)\n    layout_pred  = LayoutPredictor(layout_found)\n\n    # Define which layout regions contain text\n    TEXT_LABELS = {\"Text\", \"SectionHeader\", \"Title\", \"Caption\",\n                   \"Table\", \"ListItem\", \"Footnote\", \"PageHeader\", \"PageFooter\"}\n\n    # Find all files to process\n    all_files = find_files(input_directory, pattern=\"*.jp2\")\n    files_to_process = filter_already_processed(all_files, checkpoint)\n\n    # Process each file\n    FOR each file IN tqdm(files_to_process):\n\n        TRY:\n            # Step 1: Load image\n            image = load_image(file)\n\n            # Step 2: Preprocess (grayscale → deskew → denoise → CLAHE → Otsu)\n            preprocessed, skew_angle = preprocess_for_ocr(image)\n            save(preprocessed, get_output_path(file, \"_preprocessed.png\"))\n\n            # Step 3: Layout analysis on preprocessed image\n            layout = layout_pred([to_pil(preprocessed)])[0]\n            text_regions = sort_by_position(\n                filter(layout.bboxes, label IN TEXT_LABELS)\n            )\n\n            # Step 4: Layout-guided OCR (crop each text region, run OCR)\n            all_texts  = []\n            all_scores = []\n            FOR each region IN text_regions:\n                crop = preprocessed[region.y1:region.y2, region.x1:region.x2]\n                result = rec_pred([to_pil(crop)], det_predictor=det_pred)[0]\n                all_texts  += [line.text for line in result.text_lines]\n                all_scores += [line.confidence for line in result.text_lines]\n\n            full_text = join(all_texts)\n\n            # Step 5: Post-process — confidence analysis\n            avg_confidence = mean(all_scores)\n            low_conf_lines = filter(all_texts, score < 0.70)\n\n            # Step 6: Save structured output (JSON + TXT)\n            structured = create_surya_structured_output(\n                full_text, all_texts, all_scores, source_file=file\n            )\n            save_json(structured, get_output_path(file, \"_ocr.json\"))\n            save_text(full_text,  get_output_path(file, \"_text.txt\"))\n\n            # Step 7: Ground truth comparison (if available)\n            IF ground_truth_exists(file):\n                gt = load_ground_truth(file)\n                wer_score = wer(normalize(gt), normalize(full_text))\n                cer_score = cer(normalize(gt), normalize(full_text))\n\n            # Update tracking\n            update_manifest(manifest, file,\n                status=\"success\", confidence=avg_confidence,\n                lines=len(all_texts), low_conf=len(low_conf_lines))\n            add_to_checkpoint(checkpoint, file)\n\n        CATCH error:\n            # Log error but continue processing\n            log_error(file, error)\n            update_manifest(manifest, file, status=\"failed\", error=error)\n            CONTINUE\n\n    # Cleanup GPU memory\n    DELETE rec_pred, det_pred, foundation, layout_pred, layout_found\n    gc.collect()\n\n    # Final summary\n    print_summary(manifest)\n```\n\n#### Error Handling and Recovery\n\nWhen processing thousands of files, some will inevitably fail due to corrupted images, unsupported formats, or unexpected content. A good pipeline catches these errors, logs them, and continues processing. Use `try` functions and make sure that one file does not crash the full pipeline to not waste time and money. \n\nThe checkpoint system allows you to:\n\n1. **Resume interrupted jobs**: If your process crashes or you need to stop, simply run it again and it will skip already-processed files\n2. **Retry failures**: Clear specific files from the checkpoint to reprocess them\n3. **Audit results**: The manifest provides a complete record of what was processed, when, and with what results\n\n### 5.5 Cloud Computing Options\n\nLocal processing works for small projects, but large archives may require cloud resources; either for raw computing power or for access to commercial OCR services. Some options are: Google Colab (for smaller batches), AWS EC2 from Amazon and Google Cloud. \n\n::: {.callout-tip}\n**For UBC Researchers**: The Advanced Research Computing (ARC) Sockeye cluster provides free access to high-performance computing resources, including GPUs. This is an excellent option for processing large document archives without cloud costs. See [UBC ARC Documentation](https://arc.ubc.ca/compute-storage/ubc-arc-sockeye) for access details. It might be worth reaching out. \n:::\n\n#### Managed OCR Services\n\nFor very large projects or when you need the highest accuracy, managed services handle infrastructure and provide optimized models:\n\n| Service | Pricing (approx.) | Strengths |\n|---------|-------------------|-----------|\n| **AWS Textract** | ~$1.50/1,000 pages (basic OCR); $10–$15/1,000 (forms/tables) | Table extraction, forms |\n| **Google Document AI** | ~$1.50/1,000 pages (basic OCR); higher for structured extraction | Layout analysis, multiple languages |\n| **Azure Document Intelligence** | ~$1.50/1,000 pages (basic OCR); $10–$65/1,000 (forms/tables) | Handwriting, forms |\n| **Transkribus** | ~50 pages/month free (credit-based system) | Historical documents, HTR models |\n\nThese services are particularly valuable when:\n\n- You need to process millions of pages quickly\n- Documents contain complex tables or forms\n- You require handwritten text recognition (HTR)\n- Accuracy is more important than cost\n\n### 5.6 Cost and Time Estimation\n\nBefore starting a large OCR project, estimate the time and cost to avoid surprises. A realistic estimate accounts for every stage of the pipeline, not just OCR inference.\n\n#### Breaking Down Time per Page\n\nThe single biggest mistake is estimating only OCR time. In practice, preprocessing and layout analysis add significant overhead. A more accurate formula breaks the pipeline into stages:\n\n$$\nT_{\\text{page}} = T_{\\text{load}} + T_{\\text{preprocess}} + T_{\\text{layout}} + T_{\\text{ocr}} + T_{\\text{postprocess}} + T_{\\text{save}}\n$$\n\n| Stage | Typical Time (CPU) | Typical Time (GPU) |\n|-------|-------------------|-------------------|\n| Load + decode image | 0.1–0.5s | 0.1–0.5s |\n| Preprocessing (grayscale, deskew, denoise, CLAHE, Otsu) | 0.5–2s | 0.5–2s |\n| Layout analysis | 1–3s | 0.3–1s |\n| OCR inference | 2–8s | 0.5–2s |\n| Post-processing + save | 0.1–0.5s | 0.1–0.5s |\n| **Total per page** | **~4–14s** | **~1.5–6s** |\n\nThese ranges vary with page size (DPI), document complexity, and number of text regions detected by layout analysis. A page with 15 text regions takes longer than a page with 3.\n\n#### Total Time Estimation\n\n$$\nT_{\\text{total}} = \\frac{T_{\\text{page}} \\times N_{\\text{pages}}}{P}\n$$\n\nWhere $N_{\\text{pages}}$ is the number of documents and $P$ is the parallelism factor.\n\nThe parallelism factor depends on your setup. CPU preprocessing can be parallelized across cores, but GPU model inference is typically sequential (one image at a time) unless you batch. A realistic factor for a machine with 4 CPU cores and 1 GPU is around 2–3x, not 4x, because the GPU becomes the bottleneck.\n\n#### Example Scenarios\n\n| Scenario | Pages | Hardware | Time/Page | Parallelism | Total Time | Cost |\n|----------|-------|----------|-----------|-------------|------------|------|\n| Small project | 500 | Laptop (CPU only) | ~10s | 1x | ~1.4 hours | $0 |\n| Medium project | 10,000 | Desktop with GPU | ~3s | 2x | ~4.2 hours | $0 |\n| Large project | 100,000 | Cloud GPU ($1/hr) | ~2s | 3x | ~18.5 hours | ~$19 |\n| Large project | 100,000 | AWS Textract | managed | managed | ~2–4 hours | ~$150 |\n\n::: {.callout-tip}\n**Run a pilot first.** Before committing to a full run, process 50–100 representative pages and time each stage. Multiply up from real measurements rather than estimates. This also lets you catch pipeline bugs early, before you've burned hours of compute.\n:::\n\n### 5.7 Reproducibility\n\nReproducibility ensures that you (or others) can recreate your results exactly. This is essential for academic research and for debugging issues that arise later.\n\n#### Key Elements of Reproducibility\n\n1. **Package Versions**: Record exact versions of all libraries used\n2. **Configuration Files**: Store all parameters in version-controlled config files\n3. **Model Checkpoints**: Document which OCR models and versions were used\n4. **Determinism**: Standard OCR inference is deterministic, but if your pipeline includes stochastic steps (e.g. data augmentation during fine-tuning), set seeds and consider enabling `torch.use_deterministic_algorithms(True)`\n5. **Data Provenance**: Track the source and version of input data\n\n::: {.callout-tip}\n**Best Practice**: Create a `requirements.txt` or `environment.yml` file for your project. This allows others to recreate your exact environment. Use Version control (like Git) when necessary. \n:::\n\n## 6.0 Conclusion\n\nThis notebook walked through and explained a complete OCR workflow. \n\n**Parts 1 and 2** introduced two families of text-extraction technology. Traditional OCR engines like EasyOCR use convolutional and recurrent networks trained on character-level features, while modern transformer-based tools like Surya combine detection, recognition, and layout understanding into a single framework. Both have trade-offs: traditional engines are lightweight and fast; transformer-based approaches are more accurate on complex layouts but require more computational power.\n\n**Part 3** discussed preprocessing techniques like grayscale conversion, deskewing, denoising, contrast enhancement (CLAHE), and binarization (Otsu thresholding) which can dramatically improve OCR output. We also covered layout analysis for detecting document structure, and post-processing techniques like tokenization, and evaluation metrics (CER, WER, and confidence scores) for measuring quality.\n\n**Part 4** put everything together on real historical documents. For the Al Capone legal records (1931), we ran the full pipeline: preprocessing, layout-guided OCR, confidence analysis, structured export, and ground-truth evaluation against a human-verified transcript. The medieval medical manuscripts demonstrated the same workflow on much older, more degraded sources where no ground truth exists, relying instead on confidence-based quality assessment.\n\n**Part 5** addressed what happens when your project grows beyond a handful of pages. How to orchestrate and utilize a full OCR pipeline on a large scale.  \n\n#### Where to Go Next\n\nThe techniques in this notebook are a starting point. For researchers looking to go further:\n\n- **Downstream analysis**: Once text is extracted, you can apply text analysis methods such as [topic modeling, named-entity recognition, and text embeddings](https://ubcecon.github.io/praxis-ubc/docs/text_analysis/text_analysis.html) to study patterns across large document collections.\n- **Fine-tuning**: Both EasyOCR and Surya support fine-tuning on custom datasets. If you are working with a specific script, language, or document style, a small amount of labeled training data can significantly improve accuracy.\n- **Handwriting recognition (HTR)**: Handwritten documents remain one of the hardest challenges in OCR. Tools like [Transkribus](https://readcoop.eu/transkribus/) specialize in this area and can be integrated into pipelines similar to the one built here.\n\n::: {.callout-tip}\n**Remember**: OCR is not an end in itself. It is the first step in turning physical documents into machine-readable data that can be searched, analyzed, and shared. The quality of every downstream analysis depends on the quality of the text extraction that feeds it, so investing time in preprocessing and evaluation pays off throughout your entire research pipeline.\n:::\n\n## 7.0 References\n\nAlamy. (n.d.). *Colourful restaurant menu written on blackboard* [Stock photograph]. Alamy. <https://www.alamy.com/colourful-restaurant-menu-written-on-blackboard-style-sign-image62245978.html>\n\nAmazon Web Services. (n.d.). *Amazon Textract*. <https://aws.amazon.com/textract/>\n\nBerkeley Institute for Cognitive Science. (n.d.). *Otsu's threshold explained*. <https://bic-berkeley.github.io/psych-214-fall-2016/otsu_threshold.html>\n\nBrunner, S. (n.d.). *Deskew* [Computer software]. GitHub. <https://github.com/sbrunner/deskew>\n\nda Costa-Luis, C., Larroque, S. K., Altendorf, K., Mary, H., Korobov, M., Yorav-Raphael, N., Ivanov, I., Bargull, M., Rodrigues, N., Chen, G., & tqdm developers. (n.d.). *tqdm: A fast, extensible progress bar for Python* [Computer software]. GitHub. <https://github.com/tqdm/tqdm>\n\nGoogle Cloud. (n.d.). *Document AI*. <https://cloud.google.com/document-ai>\n\nIBM. (n.d.). *Stemming and lemmatization*. IBM Think. <https://www.ibm.com/think/topics/stemming-lemmatization>\n\nJaidedAI. (n.d.). *EasyOCR* [Computer software]. GitHub. <https://github.com/JaidedAI/EasyOCR>\n\nLibrary of Congress. (n.d.-a). *Chronicling America: Historic American newspapers*. <https://www.loc.gov/collections/chronicling-america/titles/>\n\nLibrary of Congress. (n.d.-b). *Travels in America, 1750–1920*. <https://www.loc.gov/collections/travels-in-america-1750-to-1920/about-this-collection/>\n\nMicrosoft Azure. (n.d.). *AI Document Intelligence*. <https://azure.microsoft.com/en-us/products/ai-services/ai-document-intelligence>\n\nMrázek, P. (n.d.). *Input images for filtering examples* [Image]. ResearchGate. <https://www.researchgate.net/profile/Pavel-Mrazek/publication/225873793/figure/fig3/AS:302795820421145@1449203557624/nput-images-for-the-filtering-examples-Noise-free-on-the-left-used-in-Figures-5-and-6.png>\n\nNational Archives and Records Administration. (n.d.). *Al Capone tax evasion case records*. National Archives Catalog. <https://catalog.archives.gov/id/1105475>\n\nNVIDIA. (n.d.). *Vision language models*. NVIDIA Glossary. <https://www.nvidia.com/en-us/glossary/vision-language-models/>\n\nOpenCV. (n.d.-a). *Histogram equalization (CLAHE)*. OpenCV Documentation. <https://docs.opencv.org/4.x/d5/daf/tutorial_py_histogram_equalization.html>\n\nOpenCV. (n.d.-b). *Image thresholding*. OpenCV Documentation. <https://docs.opencv.org/4.x/d7/d4d/tutorial_py_thresholding.html>\n\nOtsu, N. (1979). A threshold selection method from gray-level histograms. *IEEE Transactions on Systems, Man, and Cybernetics*, *9*(1), 62–66. <https://doi.org/10.1109/TSMC.1979.4310076>\n\nParuchuri, V. (n.d.). *Surya OCR* [Computer software]. GitHub. <https://github.com/VikParuchuri/surya>\n\nprAxIs. (n.d.-a). *Text analysis*. UBC Economics. <https://ubcecon.github.io/praxis-ubc/docs/text_analysis/text_analysis.html>\n\nprAxIs. (n.d.-b). *Text embeddings workshop*. UBC Economics. <https://ubcecon.github.io/praxis-ubc/docs/hist_workshop/text_embeddings_workshop.html>\n\nPython Software Foundation. (n.d.-a). *concurrent.futures — Launching parallel tasks*. Python Documentation. <https://docs.python.org/3/library/concurrent.futures.html>\n\nPython Software Foundation. (n.d.-b). *logging — Logging facility for Python*. Python Documentation. <https://docs.python.org/3/library/logging.html>\n\nREAD-COOP. (n.d.). *Transkribus*. <https://readcoop.eu/transkribus/>\n\nKaur, G., & Kaur, R. (2013). *Image de-noising using wavelet transform and various filters*. International Journal of Research in Computer Science, 3(4), 15–21. <https://www.researchgate.net/publication/252066070_Image_De-Noising_using_Wavelet_Transform_and_Various_Filters>\n\nTesseract OCR. (n.d.). *Tesseract open source OCR engine* [Computer software]. GitHub. <https://github.com/tesseract-ocr/tesseract>\n\nUBC Advanced Research Computing. (n.d.). *Sockeye*. <https://arc.ubc.ca/compute-storage/ubc-arc-sockeye>\n\nUBC iSchool. (n.d.). *About*. <https://ischool.ubc.ca/about/>\n\nUBC Learning Media. (n.d.-a). *Channels* [Video]. <https://learning.media.ubc.ca/media/Channels/0_u0aqwm1q>\n\nUBC Learning Media. (n.d.-b). *Raster density and colour adjustments* [Video]. <https://learning.media.ubc.ca/media/6.2+Raster+Density+and+Colour+Adjustments+/0_cuwawgrc>\n\nUniversity of Washington Libraries. (n.d.). *Civil War letters collection*. <https://content.lib.washington.edu/civilwarweb/index.html>\n\nYale University Library. (n.d.-a). *Collection of calendars, horoscopes, and medical and astrological texts* [Manuscript]. Yale University Library Digital Collections. <https://collections.library.yale.edu/catalog/16960305>\n\nYale University Library. (n.d.-b). *Cirogia vulgare. Ricettario. Antidotarium vulgare* [Manuscript]. Yale University Library Digital Collections. <https://collections.library.yale.edu/catalog/16960329>\n\nZhang, L. (n.d.). *High-quality video denoising for motion-based exposure control*. University of Wisconsin–Madison. <https://pages.cs.wisc.edu/~lizhang/projects/autoexpo/content/text.html>\n\n",
    "supporting": [
      "ocr_notebook_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}