{
  "hash": "01a0114c80a1cf1327291218e4fed649",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 3.2.2 - Advanced - Instrumental Variables 2\nauthor: COMET Team <br> _Names_\ndate: 2024-06-03\nversion: 1.0\ndescription: An introduction to estimating causal effects with instrumental variables on Jupyter and R.\ncategories: [advanced, R, instrumental variables, causality, 2SLS, regression]\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html: default\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: R\n        language: r\n        name: ir\nimage: /media/comet_placeholder.png\n---\n\n## Prerequisites\n\n- A basic understanding of instrumental variables\n- A basic understanding of Jupyter and R\n- A theoretical understanding of linear regressions\n\n## Learning Outcomes\n\nAfter completing this notebook, you will be able to:\n\n- Understand how instrumental variables solve issues with omitted variable bias and endogeneity\n- Choose appropriate instrumental variables\n- Apply two-stage least-squares regressions (2SLS) in the context of undergraduate research using R  \n\n## References\n\n- CORE (Curriculum Open-access Resources in Economics) Econ. (n.d.). THE ECONOMY (1.14.1) [E-book]. Electric Book Works.\n- Hanck, C., Arnold, M., Gerber, A., & Schmelzer, M. (n.d.). Introduction to econometrics with R [E-book]. University of Duisburg-Essen.\n- Kleiber, Christian, and Achim Zeileis. 2008. Applied Econometrics with R. New York: Springer-Verlag.\n- Kiviet, J. F., & Kripfganz, S. (2021). Instrument approval by the Sargan test and its consequences for coefficient estimation. Economics Letters, 205, 109935.\n- Stock, James, H., and Francesco Trebbi. 2003. \"Retrospectives: Who Invented Instrumental Variable Regression?\" Journal of Economic Perspectives, 17 (3): 177-194.\n- Wright, P. (1928). The Tariff on Animal and Vegetable Oils. The Macmillan Company.\n\n## Recap\n\nIn _Instrumental Variables 1_, we introduced instrumental variables and explained how instrumental variables can be used to solve issues with partial random assignment and OVB. We also showed how to adjust our specification for when the instrument is not randomly assigned. In this notebook, we assume knowledge of the material presented in _Instrumental Variables 1_ and turn to the issue of endogeneity.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages needed for the analysis\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(AER)\nlibrary(haven)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'haven' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\n# load self-writing tests\nsource('advanced_instrumental_variables2_test.r')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'digest' was built under R version 4.4.2\n```\n\n\n:::\n:::\n\n\n## Example 3 - Tariffs on Animal and Vegetable Oils \n\nEconomists attribute the first formal application of instrumental variable analysis to Philip G. Wright, in his 1928 review *Tariffs on Animal and Vegetable Oils* (Stock et al. 2003). In Appendix B, Wright discusses the economic effects of imposing tariffs in the imports of butter and flaxseed, which are both major inputs of animal and vegetable oils. Wright explains that to determine the effects of tariffs on the quantity of output and market price of the goods, we must find the elasticities of demand and supply of butter and flaxseed. The problem with estimating elasticities, argues Wright, is that we cannot estimate demand and supply curves from price-output data alone: the combinations of points are determined endogenously by both demand and supply conditions.\n\nWe explain it below.\n\n### The problem\n\nWright had to estimate demand and supply curves with data on prices and quantity of output. He explains that \"if cost [supply] conditions remain fixed while demand conditions vary, prices will lie on the supply curves; if demand conditions remain fixed while cost [supply] conditions vary, prices will lie on the demand curve.\" \n\nIn panel A of figure 3, the supply curve is kept fixed, so the combination of points $(P_{i}, Q_{i})$ must necessarily be caused by demand shifts. We can estimate the supply curve by connecting the points $(P_{i}, Q_{i})$. Panel B is analogous, albeit when demand is fixed and shifts in supply explain the combinations $(P_{i}, Q_{i})$. We can estimate the demand curve by connecting the points $(P_{i}, Q_{i})$. \n\n![Appendix B, The Tariff on Animal and Vegetable Oils. Wright, P. (1928). The Macmillan Company.](media/figure3.png)\n\nWe face a problem when neither the supply nor the demand curve remains fixed. When that happens \"price-output data yield no direct information as to either curve.\" That is, there is an infinite combination of simultaneous demand and supply shifts that could lead to the combination of points $(P_{i}, Q_{i})$. \n\nIn figure 4, Wright shows that if you connect the $(P_{i}, Q_{i})$ when both demand and supply shift, the curve recovered is neither the underlying demand nor the underlying supply curve.\n\n![Appendix B, The Tariff on Animal and Vegetable Oils. Wright, P. (1928). The Macmillan Company.](media/figure4.png)\n\nBased on this information, Wright concludes that \"the elasticities of supply and demand cannot be computed from price, output, and consumption data alone (...) elasticities of supply and demand can be computed only when assurance is obtained that [either] the cost [supply] or demand curve remains fixed.\" Since in most situations we cannot know if either demand or supply is fixed, we have a problem of endogeneity.\n\n### The solution\n\nWright also provides a solution to the problem above: \"in the absence of intimate knowledge of demand and supply conditions, statistical methods (...) must be based on the introduction of additional factors. Such additional factors may be factors which (A) affect demand conditions without affecting cost [supply] conditions or which (B) affect cost [supply] conditions without affecting demand conditions.\" Based on these definitions and for the case of agricultural crops, answer the questions below.\n\nWhich of the following could be an example of \"additional factor type A\" as described by Wright?\n\n(A) Amount of rainfall per harvest\n(B) Price of a substitute for the crop\n(C) GDP per capita\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\n# Enter your answer below as \"A\", \"B\", or \"C\"\n\nanswer_1 <- \"...\"\ntest_1()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\n# Enter your answer below as \"A\", \"B\", or \"C\"\n\nanswer_1 <- \"B\"\ntest_1()\n```\n:::\n\n\n\nWhich of the following could be an example of \"additional factor type B\" as described by Wright?\n\n(A) Yield per acre of the harvest\n(B) Income taxes\n(C) Marginal product of labor\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\n# Enter your answer below as \"A\", \"B\", or \"C\"\n\nanswer_2 <- \"...\"\ntest_2()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\n# Enter your answer below as \"A\", \"B\", or \"C\"\n\nanswer_2 <- \"A\"\ntest_2()\n```\n:::\n\n\nIt should be clear that Wright's \"additional factors\" were nothing more than instrumental variables. Let's model Wright's problem using the example of the demand of flaxseed.\n\n### Modeling the demand elasticity of flaxseed\n\n We can estimate the relationship between the quantity and price of flaxseed with a model of the form:\n\n$$\n\\log(P_i) = \\beta_0 + \\beta_1 \\log(Q_i) + u_i \n$$\n\nwhere \n\n- $P_i$ is the market price per kilogram of flaxseed for harvest $i$\n- $Q_i$ is the number of kilograms of flaxseed sold for harvest $i$\n\nOur goal is to find an unbiased estimate of $\\beta_1$, which can be interpreted as the reciprocal of the elasticity of demand: the \\% change in price associated with 1\\% change in quantity. We cannot estimate $\\beta_1$ with OLS because the model is endogenous; $(P_{i}, Q_{i})$ are determined by both demand and supply jointly.\n\nTo solve this problem we need an instrument for quantity of flaxseed. The instrument must satisfy:\n\n1. Relevance: must have a causal effect on quantity of flaxseed\n2. Exogenous: must only affects the price of flaxseed through the quantity of flaxseed\n3. Random assignment: must not be correlated to the error term\n\nA potential candidate for an instrument could be the amount of rainfall per harvest. It has a causal effect on quantity (more rain makes for a better harvest), does not affect price directly, and is a random event. \n\nNow it's your turn to model a solution to endogeneity in the context of cigarette consumption taxes.\n\n## Example 4: Pigouvian Taxes on Cigarettes\n\nPigouvian taxes are taxes on goods and services that generate negative externalities. Microeconomic theory says that to maximize social surplus in competitive markets, we should tax goods with negative externalities until their prices equal the marginal social cost of production. \n\nConsumption of cigarettes have well known negative externalities; smoking cigarettes increases the risk of health problems, adding costs to public healthcare systems. Policy makers across the globe have attempted to eliminate these negative externalities by imposing Pigouvian taxes on cigarette purchases. To determine the optimal tax rate, economists need to estimate demand and supply curves, as well as the associated price elasticities for cigarettes.  \n\nIn this example, you will try to estimate the price elasticity of demand for cigarettes with the dataset `CigarettesSW` from the package `AER`. `CigarettesSW` is a panel dataset that contains information about cigarette consumption as well as other economic indicators for all 48 continental federal states in the US from 1985 to 1995. For our analysis, we'll only use data from the 1995 cross-section. \n\nRun the cells below to load, filter, and see an overview of the dataset.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the dataset\ndata(\"CigarettesSW\")\n\n# run the command below to see a detailed description of the variables\n#?CigarettesSW \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# filter dataset for the year 1995\nc1995 <- subset(CigarettesSW, year == \"1995\")\nhead(c1995)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   state year   cpi population     packs    income      tax    price     taxs\n49    AL 1995 1.524    4262731 101.08543  83903280 40.50000 158.3713 41.90467\n50    AR 1995 1.524    2480121 111.04297  45995496 55.50000 175.5425 63.85917\n51    AZ 1995 1.524    4306908  71.95417  88870496 65.33333 198.6075 74.79082\n52    CA 1995 1.524   31493524  56.85931 771470144 61.00000 210.5047 74.77133\n53    CO 1995 1.524    3738061  82.58292  92946544 44.00000 167.3500 44.00000\n54    CT 1995 1.524    3265293  79.47219 104315120 74.00000 218.2805 86.35550\n```\n\n\n:::\n:::\n\n\n\n### Choosing our estimator\n\nWe're interested in estimating the price elasticity of demand for cigarettes. For a single variable demand function, the price elasticity of demand is the coefficient $\\beta_1$ in the equation below. \n\n$$\n\\log(Q_i) = \\beta_0 + \\beta_1 \\log(P_i) + u_i \n$$\n\nwhere \n\n- $Q_i$ is the number of cigarette packs per capita sold for state $i$\n- $P_i$ is the after-tax average real price per pack of cigarettes for state $i$\n\nWhy can't we estimate $\\beta_1$ with a simple regression of $\\log(Q_i)$ on $\\log(P_i)$?\n\n(A) We are faced with endogeneity\n(B) There is reverse causality\n(C) $\\log(P_{i})$ is correlated to the error term\n(D) All of the above\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\n# Enter your answer below as \"A\", \"B\", \"C\", or \"D\"\n\nanswer_3 <- \"...\"\ntest_3()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\n# Enter your answer below as \"A\", \"B\", \"C\", or \"D\"\n\nanswer_3 <- \"D\"\ntest_3()\n```\n:::\n\n\n\nHaving ruled out the possibility of an OLS estimator, we turn to IV estimators. List the conditions that our variable needs to meet to be an appropriate instrument:\n\n(A) Must not be correlated to the error term\n(B) Must have a causal effect on the price of cigarettes\n(C) Must have a causal effect on the demand of cigarettes\n(D) Must only affect the price of cigarettes through the demand of cigarettes\n(E) Must only affect the demand of cigarettes through the price of cigarettes\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\n# Enter your answer as a string of letters in alphabetical order ex: \"ABD\", \"BCE\", or \"CDE\"\n\nanswer_4 <- \"...\"\ntest_4()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\n# Enter your answer as a string of letters in alphabetical order ex: \"B\", \"ACD\", or \"BD\"\n\nanswer_4 <- \"ABE\"\ntest_4()\n```\n:::\n\n\nA variable that appears to meet the criteria above is the general state-level sales taxes. Sales taxes increase the prices of cigarettes in the market and should not have a direct effect on quantity demanded. Although sales taxes are _definitely not randomly assigned_, we'll assume for now that they are uncorrelated with the error term in our model. \n\nWe can calculate general state-level sales taxes by subtracting `tax` from `taxs` on our dataset. We're going to call the new variable `sales_tax`, coded in dollars per pack. \n\nBelow we compute the real sales tax and real per capita prices.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute the real sales tax\nc1995$sales_tax <- ((c1995$taxs - c1995$tax) / c1995$cpi)\n\n# compute real per capita prices\nc1995$rprice <- (c1995$price / c1995$cpi)\n\nhead(c1995)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   state year   cpi population     packs    income      tax    price     taxs\n49    AL 1995 1.524    4262731 101.08543  83903280 40.50000 158.3713 41.90467\n50    AR 1995 1.524    2480121 111.04297  45995496 55.50000 175.5425 63.85917\n51    AZ 1995 1.524    4306908  71.95417  88870496 65.33333 198.6075 74.79082\n52    CA 1995 1.524   31493524  56.85931 771470144 61.00000 210.5047 74.77133\n53    CO 1995 1.524    3738061  82.58292  92946544 44.00000 167.3500 44.00000\n54    CT 1995 1.524    3265293  79.47219 104315120 74.00000 218.2805 86.35550\n   sales_tax   rprice\n49 0.9216975 103.9182\n50 5.4850193 115.1854\n51 6.2057067 130.3199\n52 9.0363074 138.1264\n53 0.0000000 109.8097\n54 8.1072834 143.2287\n```\n\n\n:::\n:::\n\n\n### Validating instrument relevance\n\nBefore we run our IV regression with `ivreg()`, let's validate our choice of the instrument. We think sales taxes increase the price of cigarettes. Let's calculate the correlation between both variables to check that our data matches our economic logic. \n\n> **Think deeper**: what if we found a negative correlation between the instrument and the treatment? How would that affect our choice of the instrumental variable?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# check the correlation between sales tax and price\ncor(c1995$sales_tax, c1995$rprice)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6856138\n```\n\n\n:::\n:::\n\n\nA correlation of approximately 0.686 indicates that `sales_tax` and `rprice` are indeed positively related: higher sales taxes lead to higher prices.\n\nWe can further test the relevance assumption by looking at the relationship between the instrument and the treatment on the first stage regression. If we let `sales_tax` equal $Z$, what would be the specification of our first stage regression?\n\n(A) $\\log(Q_i)= π_0 + π_1Z_i + ν_i$ \n(B) $\\log(P_i)= π_0 + π_1Z_i + ν_i$ \n(C) $\\log(Q_i)= π_0 + π_1\\widehat{\\log(P_i)} + π_2Z_i + ν_i$ \n(D) $\\log(P_i)= π_0 + π_1\\widehat{\\log(Q_i)} + π_2Z_i + ν_i$ \n\n\n::: {.cell .question}\n\n```{.r .cell-code}\n# Enter your answer below as \"A\", \"B\", \"C\", or \"D\"\n\nanswer_5 <- \"...\"\ntest_5()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\n# Enter your answer below as \"A\", \"B\", \"C\", or \"D\"\n\nanswer_5 <- \"B\"\ntest_5()\n```\n:::\n\n\nLet's run the first stage regression using the function `lm()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run the first stage\ncig_s1 <- lm(log(rprice) ~ sales_tax, data = c1995)\n\n# test the significance of the coefficients with robus standard errors\ncoeftest(cig_s1, vcov = vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n            Estimate Std. Error  t value  Pr(>|t|)    \n(Intercept) 4.616546   0.030847 149.6586 < 2.2e-16 ***\nsales_tax   0.030729   0.005142   5.9761 3.145e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWe find that an increase of 1 dollar per pack in sales taxes leads to an increase of approximately 3 percent in the real sales price. The effect is significant at the 0.1\\% significance level.\n\nIt is very important that the coefficient on our first stage is statistically significant. If it's not, we do not have enough evidence to reject the null hypothesis that the instrument is not related to the variable of interest, and the instrument fails to satisfy the necessary assumption of instrument relevance. \n\n> **Rule of thumb**: it is recommended that the t-statistic of the first stage should have absolute value larger than 3.2 to satisfy instrument relevance (Stock and Yogo, 2005). \n\nHow much of the variation in the variable of interest does our instrument actually predict? \n\nWe can find this by calculating the $R^2$ of our regression, the goodness-of-fit measure for linear regression models. It indicates the percentage of the variance in the dependent variable `rprice` explained by the independent variable `sales_tax`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# R^2 of the first stage regression\nsummary(cig_s1)$r.squared\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4709961\n```\n\n\n:::\n:::\n\n\nThe $R^2$ of our regression reveals that 47.1\\% of the variation in after-tax prices is explained by the variation of sales taxes across states. This suggests that our instrument has significant predictive power, which can make us more confident of our results.\n\nUnfortunately, there is no quantitative way to validate the IV assumption of exogeneity. Instead, we must rely on our economic logic: we think it is reasonable to assume that general state-level taxes are not correlated to the error term in our model.\n\n### Estimating the elasticity of demand with 2SLS\n\nNow, we're ready to run our IV regression with `ivreg()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run the IV regression with 'ivreg()'\ncig_ivreg <- ivreg(log(packs) ~ log(rprice) | sales_tax, data = c1995)\n\n# test the significance of the coefficients with robus standard errors\ncoeftest(cig_ivreg, vcov = vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n            Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)  9.71988    1.60583  6.0529 2.413e-07 ***\nlog(rprice) -1.08359    0.33508 -3.2338  0.002263 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe regression output shows that an increase of 1\\% in price is associated with a decrease of 1.08\\% in quantity demanded, indicating that the demand for cigarettes is quite sensitive to changes in price.\n\nBut we’re not done yet. As always, we need to take a closer look at our model, understand the shortcomings of our modeling choices, and try to fix them.\n\n### Demand for cigarettes with multiple regressors\n\nIn the previous example, we chose sales price as the only regressor of our demand function. However, we know that there are several other socioeconomic variables that affect the demand for goods and services. We have data on average income for each state. As income likely affects both the demand for cigarettes and our instrument[^1], we should consider adding it as a control. Let's fit the model again but this time with real per capita income $I$ as an additional regressor.\n\n[^1]: States with high incomes per capita tend to have higher income taxes, raising proportionally more money through income taxes than sales taxes.\n\n$$\n\\log(Q_i) = \\beta_0 + \\beta_1 \\log(P_i) + \\beta_2 \\log(I_i) + u_i \n$$\n\nLet's calculate the real per capita income and store it as `rincome` on our dataset `c1995`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add rincome to the dataset\nc1995$rincome <- with(c1995, income / population / cpi)\n```\n:::\n\n\nLet's run `ivreg()` again but this time controlling for `rincome`. \n\n> Remember that we have to specify the control on both sides of the vertical bar.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run the IV regression with 'ivreg()' controlling for income\ncig_ivreg2 <- ivreg(log(packs) ~ log(rprice) + log(rincome) | log(rincome) + sales_tax, data = c1995)\n\n# test the significance of the coefficients with robus standard errors\ncoeftest(cig_ivreg2, vcov = vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n             Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)   9.43066    1.34793  6.9964 1.032e-08 ***\nlog(rprice)  -1.14338    0.40109 -2.8507  0.006562 ** \nlog(rincome)  0.21452    0.33067  0.6487  0.519807    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe estimated effect is approximately -1.14, a stronger effect than our single regressor estimate. Since we expect income to have a positive effect on quantity demanded, this result makes intuitive sense. If those were the only sources of variation affecting our model, we could be confident about our results.\n\n> **Think deeper**: Are there any potential sources of bias that we fail to control for in our model?\n\n### Demand for cigarettes with multiple instruments\n\nWhat if we have two potential candidates for instrumental variables?\n\nFor example, we could have potentially used pigouvian taxes that have already been implemented as an instrument for cigarette prices. The cigarette-specific taxes increase the market price of cigarettes, and, if they are not correlated to the error term, meet the exogeneity condition to be an instrumental variable.\n\nIV regressions are flexible enough to allow for multiple instruments. Let's calculate the real pigouvian taxes, store them as `cig_tax` in our dataset, and run `ivreg()` with both `sales_tax` and `cig_tax` as our instruments.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# add cigtax to the data set\nc1995$cig_tax <- c1995$tax/c1995$cpi\n\n# run `ivreg()` with multiple instruments\ncig_ivreg3 <- ivreg(log(packs) ~ log(rprice) + log(rincome) | \n                    log(rincome) + sales_tax + cig_tax, data = c1995)\n\n# test the significance of the coefficients with robust standard errors\ncoeftest(cig_ivreg3, vcov = vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n             Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)   9.89496    1.02539  9.6500 1.569e-12 ***\nlog(rprice)  -1.27742    0.26704 -4.7837 1.883e-05 ***\nlog(rincome)  0.28040    0.26408  1.0618     0.294    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe elasticity of demand caculated with both instruments is even greater than that estimated with the previous models. We find that the demand for cigarettes decreases by 1.28\\% for every 1\\% increase in price.\n\nOur standard errors decreased significantly when we added a second instrument to our specification. That happens because we're using more variation to explain the treatment. Nevertheless, it is important to remember that lower standard errors only add value to the model if the instruments are valid: if they meet the conditions for instrumental variables. \n\nLet's revisit our discussion of instrument validity with our extended model.\n\n### Validating instrument relevance with multiple instruments\n\nSpecifications with multiple instruments still need to meet the relevance criteria. The relevance condition is only met if the instruments are jointly significant, which can be determined through an F-test of the first stage coefficients. If we reject the null hypothesis of the F-test, it means that at least one of the coefficients is significant.\n\n> **Rule of thumb**: it is recommended that the F-statistic should be at least 10 to satisfy instrument relevance (Stock and Yogo, 2005).\n\nOur first stage with a control and 2 instruments is:\n\n$$\n\\log(P_i)= \\pi_{0} + \\pi_{1}Z_{1i} + \\pi_{2}Z_{2i} + \\pi_{3}\\log(I_{i}) + ν_i\n$$ \n\nwhere \n\n- $\\log(P_{i})$ is our treatment `log(rprice)`\n- $Z_{1i}$, $Z_{2i}$ are our instruments `sales_tax` and `cig_tax`\n- $\\log(I_{1})$ is our control `log(rincome)`\n\nLet's run the joint hypothesis F-test with the function `anova()`. The inputs to `anova()` are (1) the model of interest and (2) a restricted version of the model of interest omitting the variables being tested.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run first stage\nmultiple_s1 <- lm(log(rprice) ~ sales_tax + cig_tax + log(rincome), data = c1995)\n\n# run restricted version of first stage\nmultiple_s1_restricted <- lm(log(rprice) ~ log(rincome), data = c1995)\n\n# test the significance of the coefficients with `anova`\nanova(multiple_s1_restricted, multiple_s1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nModel 1: log(rprice) ~ log(rincome)\nModel 2: log(rprice) ~ sales_tax + cig_tax + log(rincome)\n  Res.Df     RSS Df Sum of Sq      F    Pr(>F)    \n1     46 0.55522                                  \n2     44 0.04579  2   0.50943 244.73 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nThe F-test output shows that our F-stat is 244, sufficient to reject the null hypothesis that our instruments are significant at the 0.1\\% significance level. This suggests that our instruments do indeed meet the relevance criteria.\n\nNow we turn to exogeneity: the instruments need to be uncorrelated to the error term of the original model.\n\nIn our case, that means that `sales_tax` and `cig_tax` need to be uncorrelated to $u_{i}$ in the specification below.\n\n$$\n\\log(Q_i) = \\beta_0 + \\beta_1 \\log(P_i) + \\beta_2 \\log(I_i) + u_i\n$$\n\nAs we've seen, there is no easy way to test for this condition when we have a single instrument - we must instead rely on our economic logic about the variables and their relationships. However, there is a clever way of testing for exogeneity when we have more than one instrument.\n\n### Validating instrument exogeneity with multiple instruments\n\nIf both instruments are relevant and exogenous with respect to the model, then their estimated causal effects must be unbiased. Think about it: if both instruments isolate good variation of the variable of interest, these two slices of variation must represent the same relationship between the variable of interest and the outcome. Therefore, to test for exogeneity when we have more than one instrument, we can calculate the 2SLS estimate using each instrument separately and compare both estimates. If they are not the same, chances are at least one of the instruments is not exogenous.\n\n> Note that this test only works if we have more instruments than variables of interest, a condition denominated **overidentification**.\n\nLet's run two IV regressions: one just with `sales_tax` as an instrument and the other just with `cig_tax` as an instrument. If the estimated coefficients from these two regressions are not similar, we probably have at least one invalid instrument.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run the IV regression with `sales_tax` as an instrument\nsales_tax_iv <- ivreg(log(packs) ~ log(rprice) + log(rincome) | log(rincome) + sales_tax, data = c1995)\n\n# test the significance of the coefficients with robust standard errors\ncoeftest(sales_tax_iv, vcov=vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n             Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)   9.43066    1.34793  6.9964 1.032e-08 ***\nlog(rprice)  -1.14338    0.40109 -2.8507  0.006562 ** \nlog(rincome)  0.21452    0.33067  0.6487  0.519807    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# run the IV regression with `cig_tax` as an instrument\ncig_tax_iv <- ivreg(log(packs) ~ log(rprice) + log(rincome) | log(rincome) + cig_tax, data = c1995)\n\n# test the significance of the coefficients with robust standard errors\ncoeftest(cig_tax_iv, vcov=vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n             Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)  10.02363    1.08022  9.2792 5.133e-12 ***\nlog(rprice)  -1.31458    0.27285 -4.8180 1.682e-05 ***\nlog(rincome)  0.29867    0.25697  1.1622    0.2513    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nOur estimates appear to be quite dissimilar, which could indicate that at least one of our instruments is not exogenous. Let's use our economic knowledge to interpret this result.\n\nPerhaps pigouvian taxes differ greatly based on the strength of the cigarette industry in each state. For example, states with cigarette manufacturing facilities might have both a cultural inclination to smoke more and have strong lobbying groups that keep excise taxes low. That is something that we don't control for in our regression, which could possibly undermine the exogeneity of `cig_tax`, deeming it an inappropriate instrument.\n\nIt could also be possible that the difference between both 2SLS estimates is actually just sampling variance. If we look at the confidence interval of the coefficients above, we see that each confidence interval contains both of the estimated effects. \n\nTo certify ourselves that the difference between both estimates is actually material (and not just sampling variance) we need to do a statistical test, called the **overidentifying restriction test** with the J-statistic. The statistical theory of this test is beyond the scope of this notebook but in the next section we learn to analyze the test outputs given by the software. \n\n### Analyzing diagnostic tests of `ivreg()`\n\nThe function `ivreg()` has diagnostic tests that estimate the exogeneity test as well as other tests related to the IV assumptions. Let's examine the `summary()` output of `ivreg()` for our `cig_ivreg3` specification. \n\n> Remember that `cig_ivreg3` is the IV regression with both of the instruments `sales_tax` and `cig_tax`, and with the control `rincome`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run summary of our IV regression output\nsummary(cig_ivreg3, diagnostics=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nivreg(formula = log(packs) ~ log(rprice) + log(rincome) | log(rincome) + \n    sales_tax + cig_tax, data = c1995)\n\nResiduals:\n       Min         1Q     Median         3Q        Max \n-0.6006931 -0.0862222 -0.0009999  0.1164699  0.3734227 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    9.8950     1.0586   9.348 4.12e-12 ***\nlog(rprice)   -1.2774     0.2632  -4.853 1.50e-05 ***\nlog(rincome)   0.2804     0.2386   1.175    0.246    \n\nDiagnostic tests:\n                 df1 df2 statistic p-value    \nWeak instruments   2  44   244.734  <2e-16 ***\nWu-Hausman         1  44     3.068  0.0868 .  \nSargan             1  NA     0.333  0.5641    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1879 on 45 degrees of freedom\nMultiple R-Squared: 0.4294,\tAdjusted R-squared: 0.4041 \nWald test: 13.28 on 2 and 45 DF,  p-value: 2.931e-05 \n```\n\n\n:::\n:::\n\n\nThe diagnostic tests conducted by `ivreg()` are (1) Weak instruments (2) Wu-Hausman (3) Sargan test.\n\n- **Weak instruments test**: tests for instrument relevance with the F-statistic. This test is equivalent to what we did with `anova()`: if we reject the null, it means that at least one instrument is not weak.\n- **Wu-Hausman test**: tests for the endogeneity of the variable of interest. If we reject the null, it means that the treatment is indeed endogenous, so we cannot use OLS to estimate the causal effect.\n- **Sargan test**: tests for instrument exogeneity with the J-statistic. This is the overidentifying restrictions test we needed for the previous section. If we reject the null, it means that at least one of the instruments is not exogenous, and consequently, invalid.\n\nOur output shows that we reject the null for the Weak instruments test with a very high statistic, we reject the Wu-Hausman test at the 10\\% significance level, and we do not reject the Sargan test.\n\nThe results of tests (A) and (B) were expected based on our previous analysis. The Weak instruments test corroborates our finding of instrument relevance with `anova()` and the Wu-Hausman test confirms what we already know about the endogenous relationship of price and quantity. What is interesting from the output of the diagnostics is that we don't reject the null hypothesis for exogeneity. That suggests that the difference in the 2SLS estimates that we found in the previous section was due to sampling variance, and not caused by invalid instruments. \n\nNevertheless, it is important to keep in mind that the results of these tests are just one piece of supporting evidence for modeling choices. The tests by themselves are not sufficient to support choices of instrumental variables, and more broadly, choices of empirical methods. \n\nIn this example, we should be skeptic of the resuls of the Sargan test. The Sargan test commits a large proportion of type II error, which can lead to substantial estimation errors if the invalid instruments are stronger than valid instruments (Kripfganz and Kiviet, 2021). If our test failed to identify `cig_tax` as an invalid instrument, this could substantially undermine our model. Adding `cig_tax` to our main specification is a matter of judgment.\n\n## Summary\n\nIn the notebooks _Instrumental Variables 1 and 2_ we learned how to:\n\n- Use instrumental variables to solve partial random assignment, OVB, and endogeneity\n- Choose appropriate instrumental variables\n- Interpret the causal estimates calculated with IV regressions\n- Run IV regression in R using the `AER` package\n\nAs a supplement to these notebooks, we recommend reading the paper [Acemoglu et. al (2001)](https://pubs.aeaweb.org/doi/pdfplus/10.1257/aer.91.5.1369). In this paper, the authors use IVs to trace the determinants of cross-country differences in GDP per capita in the late 20th century.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}