
## Section 1: Traditional qualitative coding

The Coding Manual for Qualitative Researchers
Qualitative Data: An Introduction to Coding and Analysis
https://resources.nu.edu/c.php?g=1007180&p=7392331


### 1.1 Examples of traditional qualitative coding, papers

A interactive NYT article would work nicely here. A lot of their research is qualitative coding voter preferences etc

### 1.2 Recent updates

https://www.mturk.com/
https://www.prolific.com/academic-researchers

## Section 2: Computational text analysis

### 2.1 Supervised machine learning

Tokenization, Text Normalization, Stop Word Removal, TF-IDF (google it + show off the relevant python/R libraries)
For R:
- SnowballC
- tidytext
Python:
- scikitlearn

#### 2.1.1 Statistical frameworks

https://smltar.com/ 
Naive Bayes, Logistic Regression, SVMs
- Show off R/python libraries for this

#### 2.1.2 Deep learning frameworks

https://www.packtpub.com/en-us/product/getting-started-with-google-bert-9781838821593


### 2.2 Unsupervised learning 

#### 2.2.1 Topic modelling

- LDA
Introduction to Topic Modeling and Text Classification, W.J.B. Mattingly

#### 2.2.2 Clustering

- K-means, Hierarchical
Text Mining: Classification, Clustering, and Applications, Ashok N. Srivastava

#### 2.2.3 Embeddings (briefly)
- Word2Vec
- Skip-Gram, CBOW
Embeddings in Natural Language Processing: Theory and Advances in Vector Representations of Meaning

### 2.3 Natural Language Processing (brief)

#### Examples: dependency relationships, object detection, grammatical parsing
- NER

### 2.4 Recent Updates

#### 2.4.1 NLI, zero-shot learning, BERT

#### 2.4.2 Classification and discovery using decoder only models

##### 2.4.2.1 Zero shot, few shot, RAG, fine tuning of LLMs (all very briefly! just mention them)

##### 2.4.2.2 LLMs using APIs vs. chat-based format (brief)

##### 2.4.2.3 Local models vs. sending data to a company (brief)

### 2.5 AI ethics