{
  "hash": "1f47f083f52caf03a862625cd9c0b270",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"1.2 - Beginner - Dispersion and Dependence\"\nauthor: COMET Team <br> _Oliver (Junye) Xu, Anneke Dresselhuis, Jonathan Graves_\ndate: 12 January 2023\ndescription: In this notebook we explore how data is spread out, and what that means for its interpretation.  This includes both how individual values may vary, and how values may _co-vary_ with one another.\ncategories: [econ 325, central tendency, descriptive statistics, variance, covariance, standard deviation, correlation, beginner, R, interquartile range, beginner]\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html: default\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: R\n        language: r\n        name: ir\nimage: /media/comet_placeholder.png\n---\n\n\n## Outline\n\n### Prerequisites\n\n-   Introduction to Jupyter\n-   Introduction to R\n-   Introduction to Visualization\n-   Central Tendency\n-   Distribution\n\n### Outcomes\n\nThis notebook explains the concepts of dispersion and dependence. After completing this notebook, you will be able to:\n\n-   Understand and interpret measures of dispersion, including variance and standard deviation\n-   Understand and interpret measures of dependence, including covariance and correlation\n-   Investigate, compute, and interpret common descriptive statistics\n-   Create summary tables for variables, including qualitative variables\n-   Parse summary statistics for meaning\n\n### References\n\n-   [Introductory Statistics](https://openstax.org/books/introductory-statistics/pages/2-7-measures-of-the-spread-of-the-data)\n\n## Introduction\n\nIn this notebook, we will continue learning about how to use descriptive statistics to represent sets of data. We've already seen how to compute measures of central tendency and determine which measures are appropriate for given situations. We'll now focus on computing measures of dispersion and dependence in order to better understand both the variation of variables, as well as relationships between variables in a data set. We'll dedicate time to both measures, but we'll look at dispersion first. Let's first import our familiar 2016 Census data set from Statistics Canada.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(haven)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'haven' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# reading in the data\ncensus_data <- read_dta(\"../datasets_beginner/01_census2016.dta\")\n\n# load self-tests\nsource(\"beginner_dispersion_and_dependence_tests.r\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'digest' was built under R version 4.4.2\n```\n\n\n:::\n:::\n\n\n\n## Part 1: Measures of Dispersion for a Single Variable\n\nMeasures of dispersion describe the spread of data, that is, the possible values that a variable in a data set can take on. Common measures of dispersion which we'll look at include the range, interquartile range, standard deviation and variance.\n\n### Range and interquartile range\n\nThe **range** of a variable is the difference between the maximum and minimum value that a variable takes on. \n\nThe **interquartile range** of a variable is the difference between the 75th and 25th percentile values of the variable. We can use functions like `quantile()` and `fivenum()` to calculate these statistics quite quickly.\n\n> **Note**: both `quantile()` and `fivenum()` return the same output: a list with different percentiles of the data. By default, these are the minimum,  25th percentile, 50th percentile (median), 75th percentile, and maximum values.\n\n### Variance\n\nThe **variance** is the average of the squared differences from the mean.\n\n-   Small variance: observations tend to fall close to the mean\n-   High variance: observations are very spread out from the mean.\n\nThe formula for the sample variance is:\n\n$$\ns_{x}^2 = \\frac{\\sum_{i=1}^{n} (x_i - \\overline{x})^2}{n - 1}\n$$\n\nThe formula for the variance in a population is:\n\n$$\n\\sigma_{x}^2 = \\int(x - \\mu)^2 f(x) dx\n$$\n\n### Standard deviation\n\nThe **standard deviation** is the square root of the variance. It also measures dispersion around the mean, similar to the variance.  For a sample this is:\n\n$$\ns_{x} = \\sqrt{s_{x}^2} = \\sqrt{\\frac{\\sum_{i = 1}^{n} (x_i - \\overline{x})^2}{n - 1}}\n$$\n\nFor the population:\n\n$$\n\\sigma_{x} = \\sqrt{\\sigma_{x}^2}\n$$\n\n> **Example**: a normal distribution with `mean = 30` and `sd = 5` is exactly the same thing as a normal distribution with `mean = 30` and `variance = 25`.\n\nWe usually use standard deviations rather than variances because the variance does not have the *same units* as the original variable, while the standard deviation does.\n\n> **Advanced Note**: In econometrics, some samples have more information than others about the population.For example, an estimate of the population variance based on a sample size of 100 certainly has more information than a sample size of 10. We measure the degree of uncertainty of an estimate using the **degrees of freedom** of an **estimate**. The degrees of freedom for our estimate of variance (sample variance) is equal to $n - 1$.\n\nIn R, we use the `var()` function to calculate the variance of a variable, and the `sd()` function for the standard deviation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate the variance of wage\nvariance <- var(census_data$wages, na.rm = TRUE) # remember that we need to remove all NA values\n```\n:::\n\n\n\n### Test your knowledge\n\nCalculate the standard deviation of wages by filling in the code on the cell below.\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\n# fill in the ... with your code below to find the sd of wages - round your answer to the nearest whole number\n\nanswer_1 <- ...()\ntest_1()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\n# fill in the ... with your code below to find the sd of wages\nanswer_1 <- round(sqrt(var(census_data$wages, na.rm = TRUE)))\n\ntest_1()\n```\n:::\n\n\n\n### Interpreting Variation\n\nLet's say we're interested in understanding how the `wages` variable is dispersed around the mean.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# recall the mean of wages\nmean(census_data$wages, na.rm = TRUE) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 54482.52\n```\n\n\n:::\n\n```{.r .cell-code}\n# calculate the standard deviation of wages\nsd(census_data$wages, na.rm = TRUE) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 64275.27\n```\n\n\n:::\n:::\n\n\n\nWe have a pretty large standard deviation - even larger than our mean! This tells us that most of the Canadians in the data set have a wage which lies approximately $64275.27$ away from the mean of $54482.52$.\n\nThis large standard deviation tells us that there is high variation in wages and that some of them are very far from the mean. This can be for many reasons, but one possibility is that we have **outliers** in the data set: extreme values of the variable `wages`. This is common for wage distributions in the presence of income inequality.\n\n> **To Remember**: the standard deviation is small when the data are all concentrated close to the mean, while the standard deviation is large when the data are spread out away from the mean.\n\n### Empirical Rule\n\nRecall, from the *Central Tendency* notebook, that a very important distribution in econometrics is the **normal distribution**. For a variable with values distributed in this way, there is a quick way to estimate the density of the distribution with the standard deviation. This is called **68-95-99.7 rule** or **Empirical Rule**:\n\n-   68% of the values are within 1 standard deviation of the mean\n-   95% are within 2 standard deviations of the mean\n-   99.7% are within 3 standard deviations from the mean\n-   Remaining values are outliers and incredibly rare\n\n![\"Empirical rule\"](media/standard_deviation_examples.png)\n\nThis gives us a helpful frame of reference when discussing the standard deviation of a variable.\n\nFor example: let's take test scores. Assuming test scores are normally distributed, if the mean score on a test is 70 and the standard deviation is 10, this tells us that approximately 68% of students who wrote that test earned a score between 60 and 80 (1 standard deviation), approximately 95% earned a score between 50 and 90 (2 standard deviations) and virtually everyone earned a score between 40 and 100 (3 standard deviations).\n\n### Test your knowledge\n\nLet's suppose the mean test score of my ECON 325 exam was 70 and the standard deviation was 5. If test scores are normally distributed and my grade was 85, what percentage of students got a grade higher than mine?\n\n> **Hint**: The area under the normal distribution has to sum to 1.\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\n# write your answer in decimal form and don't round\n\nanswer_2 <- ...\ntest_2()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_2 <- 0.0015 # 1 - (0.997/2 + 0.5)\ntest_2()\n```\n:::\n\n\n\n## Part 2: Measures of Dispersion for Multiple Variables \n\nMeasures of **dependence** calculate relationships between variables. The two most common are *covariance* and *correlation*.\n\n### Covariance\n\n**Covariance** is a measure of the direction of a relationship between two variables.\n\n-   Positive covariance: two variables are positively related\n    -   When one variable goes up, the other goes up, and vice versa.\n-   Negative covariance: two variables are negatively related.\n    -   When one variable goes up, the other goes down, and vice versa.\n\nThis is similar to the idea of variance, but where variance measures how a *single* variable varies, covariance measures how *two* vary together.  They also have similar formulas.\n\nSample Covariance:\n\n$$\ns_{x,y}=\\frac{\\sum_{i=1}^{n}(x_{i}-\\bar{x})(y_{i}-\\bar{y})}{n-1}\n$$\n\nPopulation Covariance:\n\n$$\n\\sigma_{x,y}=\\int\\int(x_{i}-\\mu_x)(y_{i}-\\mu_y)f(x,y)dxdy\n$$\n\nThis is tedious to calculate, especially for large samples. In R, we can use the `cov()` function to calculate the covariance between two variables. Let's say we're interested in exploring the covariance between the `wages` variable and `mrkinc` variable in the dataset.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# cov() function requires use=\"complete.obs\" to remove NA entries\ncov(census_data$wages, census_data$mrkinc, use=\"complete.obs\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4798121947\n```\n\n\n:::\n:::\n\n\n\nThe calculated covariance between the `wages` variable and `mrkinc` variable in the dataset is positive, indicating the two variables are positively related. As one variable changes, the other variable will change in the same direction. \n\nLet's try computing the covariance \"by hand\" to understand how the formula really works. To simplify the process, we will construct a hypothetical data set with variables $x$ and $y$.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(6, 8, 10)\ny <- c(25, 100, 125)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# find the average values of x and y\navg_x <- mean(x)\navg_y <- mean(y)\n\n# sum the products of the differences between the observations and the average\nnumerator <- {(x[1] - avg_x)*(y[1] - avg_y) + (x[2] - avg_x)*(y[2] - avg_y) + (x[3] - avg_x)*(y[3] - avg_y)}\n\n# denominator is the sample size minus 1\ndenominator <- 3-1\n\nprint(numerator/denominator)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# confirming the previous calculation\ncov(x,y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 100\n```\n\n\n:::\n:::\n\n\n\nInterpreting covariances directly is difficult because the size of the covariance depends on the scale of $x$ and $y$.  Repeat the preceding calculation, but with variables that are 10x as large.  What do you see?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- c(60, 80, 100)\ny <- c(250, 1000, 1250)\n\ncov(x,y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10000\n```\n\n\n:::\n:::\n\n\n\nThe solution to this problem is the next topic: correlation.\n\n### Correlation\n\nA **correlation coefficient** measures the relationship between two variables. It allows us to know both if two variables move in the same direction (positive correlation), or in the opposite directions (negative correlation), or if they have no relationship (no correlation).\n\n> **Note**:  even though a covariance or correlation may be zero, this does not mean that there is no relationship between the variables - this only means that there is no *linear* relationship.\n\nCorrelation fixes the scale problem with covariance by standardizing covariance to a scale of -1 to 1.  It does this by dividing the covariance by the standard deviations of the variables. The most popular version is **Pearson's correlation coefficient** which is calculated as follows.\n\n$$\nr_{x,y} = \\frac{\\sum_{i=1}^{n} (x_i - \\overline{x})(y_i - \\overline{y})}{\\sqrt{\\sum_{i=1}^{n} (x_i - \\overline{x})^2 \\sum_{i=1}^{n}(y_i - \\overline{y})^2}}=\\frac{s_{x,y}}{s_{x} s_{y}}\n$$\n\nOnce again, let's try to compute the correlation \"by hand\" using the formula above.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnumerator <- sum((x - mean(x))*(y - mean(y)))\ndenominator <- sqrt(sum((x - mean(x))^2) * sum((y - mean(y))^2))\nnumerator/denominator\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9607689\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nnumerator <- cov(x,y)\ndenominator <- sd(x) * sd(y)\nnumerator/denominator\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9607689\n```\n\n\n:::\n:::\n\n\n\nIn R, we can use the `cor()` function to calculate the correlation between two variables.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Confirming the previous calculation\ncor(x,y)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9607689\n```\n\n\n:::\n:::\n\n\n\nTo calculate the correlation between the `wages` variable and `mrkinc` variable in the dataset:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# cor() function requires use=\"complete.obs\" to remove NA entries\ncor(census_data$wages, census_data$mrkinc, use=\"complete.obs\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8898688\n```\n\n\n:::\n:::\n\n\n\nNow we have the number 0.8898687 $\\approx$ 0.89 as our correlation coefficient. What does it really mean? \n\nA correlation coefficient ranges from -1 to 1, which tells us two things:\n\n1.  The direction of the relationship between the 2 variables.\n   \n    -   A negative correlation coefficient means that two variables move in opposite directions. If a variable increases the other decreases and vice versa.\n    -   A positive correlation implies that the two variables move in the same direction, that is, if one variable increases the other also increases and vice versa.\n\n2.  The strength of the relationship between the 2 variables.\n\n    -   The more extreme the correlation coefficient (the closer to -1 or 1), the stronger the relationship. The less extreme the correlation coefficient (the closer to 0), the weaker the relationship. \n    -   Two variables are uncorrelated if the correlation coefficient is close to 0. As one variable increases, there is no tendency in the other variable to either decrease or increase.\n\n![Three scatter plots are shown demonstrating positive, negative and no correlation\"](media/correlation_examples.png)\n\nWe can also easily visualize the correlation between two variables by plotting a scatter plot with a trend line via the `ggplot()` function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# scatterplot of market income against wages\nggplot(census_data, aes(x = mrkinc, y = wages)) +\n       geom_point(shape = 1)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 48875 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](beginner_dispersion_and_dependence_files/figure-ipynb/unnamed-chunk-17-1.png)\n:::\n:::\n\n\n\nAdding a trend line to the scatter plot helps us interpret the directionality of two variables. We can do it via the `geom_smooth()` function by including the `method = lm` argument, which displays scatterplot patterns in the presence of overplotting. You will learn more about how trend lines are mathematically formulated in advanced econometrics classes.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(census_data, aes(x = mrkinc, y = wages)) +\n  geom_point(shape = 1) +\n  geom_smooth(method = lm) # add this argument to draw the trendline\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 48875 rows containing non-finite outside the scale range\n(`stat_smooth()`).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Removed 48875 rows containing missing values or values outside the scale range\n(`geom_point()`).\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](beginner_dispersion_and_dependence_files/figure-ipynb/unnamed-chunk-18-1.png)\n:::\n:::\n\n\n\nNow we can see the apparent positive correlation!\n\n### Test your knowledge\n\nIs the following statement True or False?\n\nThe correlation coefficient adjusts the measure of covariance so that it can measure linear relationships.\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nanswer_3 <-  \"...\" # enter \"True\" or \"False\"\n\ntest_3()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_3 <- \"False\" # enter \"True\" or \"False\"\n\ntest_3()\n```\n:::\n\n\n\nSuppose the weights of packages(in lbs) at a particular post office are recorded as below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npackage_data <- c(95, 130, 148, 183, 100, 98, 137, 110, 188, 166)\n```\n:::\n\n::: {.cell .question}\n\n```{.r .cell-code}\n# calculate the mean, standard deviation and variance of the weights of packages\n# round all answers to 2 decimal places\n\nanswer_4 <- # enter your answer here for mean\nanswer_5 <- # enter your answer here for standard deviation \nanswer_6 <- # enter your answer here for variance\n\ntest_4()\ntest_5()\ntest_6()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_4 <- round(mean(package_data),2)\nanswer_5 <- round(sd(package_data),2)\nanswer_6 <- round(var(package_data),2)\n\ntest_4()\ntest_5()\ntest_6()\n```\n:::\n\n\n\nUse the example above to answer: Assuming the weights follow a normal distribution, 68% of packages at the post office weigh how much?\n\n(A) 68% of packages weigh between 65.30 and 150.70 lbs\n(B) 68% of packages weigh between 100.40 and 170.60 lbs\n(C) 68% of packages weigh between 120.40 and 150.60 lbs \n(D) 68% of packages weigh between 80.56 and 120.60 lbs\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nanswer_7 <- \"...\"    # enter your choice here (ex, \"F\")\n\ntest_7()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_7 <- \"B\"    # enter your choice here (ex, \"F\")\n\ntest_7()\n```\n:::\n\n\n\nNow, brainstorm some real-world examples that best demonstrate the correlation relationships below. The first one is already done for you!\n\n -   zero or near zero: the number of forks in your house vs the average rainfall where you live\n -   weak negative: \n -   strong positive: \n -   weak positive: \n -   strong negative: \n",
    "supporting": [
      "beginner_dispersion_and_dependence_files\\figure-ipynb"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}