{
  "hash": "c4dd0cd098ffb9cec32064d3d4e92aa8",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 3.2.1 - Advanced - Instrumental Variables\nauthor: COMET Team <br>\ndate: 2024-06-10\nversion: 1.0\ndescription: An introduction to estimating causal effects with instrumental variables on Jupyter and R.\ncategories: [advanced, R, instrumental variables, causality, 2SLS, regression]\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html: default\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: R\n        language: r\n        name: ir\nimage: /media/comet_placeholder.png\n---\n\n\n## Prerequisites\n\n-   An intermediate understanding of Jupyter and R\n-   A theoretical understanding of linear regressions\n\n## Learning Outcomes\n\nAfter completing this notebook, you will be able to:\n\n-   Understand how instrumental variables solve omitted variable bias\n-   Choose appropriate instrumental variables\n-   Estimate causal effects with 2SLS estimators\n\n## References\n\n-   Baicker, K., Taubman, S. L., Allen, H. L., Bernstein, M., Gruber, J. H., Newhouse, J. P., Schneider, E. C., Wright, B. J., Zaslavsky, A. M., & Finkelstein, A. N. (2013). The Oregon Experiment: Effects of Medicaid on clinical outcomes. New England Journal of Medicine, 368(18), 1713–1722.\n-   Card, D. (1993). Using geographic variation in college proximity to estimate the return to schooling. National Bureau of Economic Research.\n-   Hanck, C., Arnold, M., Gerber, A., & Schmelzer, M. (n.d.). Introduction to econometrics with R \\[E-book\\]. University of Duisburg-Essen.\n-   Kleiber, Christian, and Achim Zeileis. 2008. Applied Econometrics with R. New York: Springer-Verlag.\n\n## Outline\n\nThe notebooks *Instrumental Variables 1 and 2* are structured as follows:\n\n* Context: Oregon Health Insurance Experiment\n    - Introducing instrumental variables in the context of partial random assignment\n    - Laying out the theory of instrumental variables and their estimators\n* Example 2: College Proximity and Returns to Education\n    - Solving OVB with data from Card (1993)\n    - Applying IV estimators on R using the `AER` package\n    - Discussing the differences between OLS and IV estimates\n* Example 3: Tariffs on Animal and Vegetable Oils \n    - Understanding the first application of instrumental variables in the context of endogeneity\n    - Modeling solutions to endogeneity in demand and supply relationships\n* Example 4: Pigouvian Taxes on Cigarettes \n    - Extending IV regressions to multiple instruments\n    - Introducing statistical tests to quantify the validity of instruments\n\n## Context: Oregon Health Insurance Experiment\n\nUniversal healthcare is one of the most widely debated topics in economic policy. Since 1965, the federal government of the United States provides free healthcare to American citizens through two different health insurance programs: Medicare and Medicaid. These programs cover medical costs of at-risk and some low-income Americans. In 2010, the federal government approved the Affordable Care Act, which let US states extend Medicaid to all low-income adults within their jurisdictions.\n\nThe key question the states faced was: **should we extend health insurance to all low-income adults?**\n\nThis decision required the states to assess the costs and benefits of extending health insurance to the uninsured. Crucially, they need to know how much (or whether at all) health insurance improves health outcomes of individuals.\n\nA first approach might be to estimate the effect of health insurance using a regression. For instance, we could regress health outcomes on insurance status. Unfortunately, this model would have *omitted variables bias (OVB)*. It is likely that the older and lower-income population currently covered by Medicare and Medicaid is less healthy than the average American. This would result in a misleading estimate. We need another approach.\n\nIdeally, we would want to randomly select people from the uninsured population, randomly assign health insurance to them, then compare the health outcomes of the two groups. This was what the State of Oregon did in 2008.\n\n### The experiment: solving the problem of partial random assignment\n\nFrom 2008 to 2011, the state of Oregon randomly assigned Medicaid coverage to 30,000 uninsured citizens through a lottery system. The lottery winners were offered full coverage of the Oregon Health Plan (OHP) Standard Medicaid, once they submitted some documentation. The state recorded the health outcomes of both the individuals that won and lost the lottery over the course of several years.\n\nAlthough this is close to our ideal, it's not a perfect randomly controlled trial (RCT). Lottery winners were only given free insurance if they submitted their documents and met some eligibility criteria[^1]. Many lottery winners either did not submit the required documents or turned out to be ineligible to the program. In the end, only about 25\\% of the lottery winners eventually enrolled in OHP Standard.\n\n[^1]: To be eligible for OHP Standard, individuals must be 19-64 years old, an Oregon resident who is a US citizen or legal immigrant, ineligible for other public health insurance, and uninsured for the past six months. Individuals must also earn less than the federal poverty level, and have assets worth no more than US\\$2,000.\n\nWhile the *possibility to apply for insurance* was randomly assigned by the lottery system, *insurance status* was not randomly assigned. This means that if health outcomes were related to the reason why they didn't fill out their forms, or were ineligible, we could still have OVB.\n\nFortunately, there are ways around this \"partial random assignment\". We can (1) isolate the variation in insurance status created by the lottery and (2) calculate the effect of insurance status on health outcomes just for this isolated variation. This approach is called **instrumental variables**.\n\n### The theory\n\nWe are interested in the effect of *insurance status* on *health outcomes.* We know:\n\n-   Lottery results are randomly assigned\n-   Winning the lottery increases the probability of insurance coverage\n-   Insurance coverage affects health outcomes\n\nWe can use these facts to isolate the effect of health insurance. The key insight is that winning the lottery can only affect your health through its impact on your health insurance. This means that the following relationship must be true:\n\n$$\n\\text{Effect of lottery on insurance} \\cdot \\text{Effect of insurance on health} = \\text{Effect of lottery on health}\n$$\n\n> **Example**: Imagine that all of the lottery winners were automatically enrolled in the insurance program. That would mean that the probability of insurance status for lottery winners is 100\\%. In this scenario, insurance status is determined *solely* by the lottery, so we have a traditional RCT. A comparison of health outcomes between those who won and those who lost the lottery (or those who have and those who don't have insurance) would be unbiased. This can be seen on the equation above: if the effect of lottery on insurance $=$ 1, then effect of lottery on health outcomes $=$ effect of insurance on health outcomes.\n\nSince lottery winners are not automatically enrolled in the insurance program, winning the lottery increases the probability of insurance coverage by less than 100\\%. This means that insurance status is determined by both the lottery and other external variables (for example, maybe those who don't submit the application on time care less about their health). In this case, a simple comparison of health outcomes between individuals would yield a biased estimate.\n\nTo get the true effect of insurance on health, we can rearrange the relationship.\n\n$$\n\\text{Effect of insurance on health} = \\frac{\\text{Effect of lottery on health}}{\\text{Effect of lottery on insurance}}\n$$\n\nLet's be a little more rigorous about what we mean by \"effect\". Since lottery is a binary variable (you either win or lose the lottery), we can rewrite the \"effects\" as the difference in averages for the lottery dummy turned on and off. We get a ratio of differences of conditional averages: the difference in health outcomes conditional on lottery result divided by the difference in insurance status conditional on lottery result.\n\n$$\n    \\text{Effect of insurance on health} = \\frac{\\text{Average health of winners} - \\text{Average health of losers}}{\\text{Average insurance of winners} - \\text{Average insurance of losers}}\n$$\n\nThat seems like something we can calculate. This difference in averages should adjust our estimates to reflect the \"partial random assignment\" situation. The effect of insurance on health equals the effect of the lottery results on health *adjusted for the probability that lottery winners enroll in the insurance program*.\n\n> **Think deeper**: Why can we interpret the effect of lottery on insurance as the probability that lottery winners enroll in the insurance program?\n\n### Health insurance example with simulated data\n\nLet's calculate the effect of insurance on health with a very simple simulated dataset.\n\n`simulated_health_data` has data on 1,000 uninsured individuals who participated in a lottery system for public health insurance coverage in a fictitious state. The variables coded are:\n\n-   `lot_win` dummy == 1 for lottery winners\n-   `insurance_status` dummy == 1 for enrolled in the insurance program\n-   `health_outcome` for an aggregate measure of health outcomes after 12 months of insurance enrollment (the higher, the better!)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages needed for the analysis\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(AER)\n\n# load datasets\nsource('advanced_instrumental_variables1_data1.r')\nsource('advanced_instrumental_variables1_data2.r')\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# set seed to ensure reproducibility\nset.seed(123)\n\n# inspect the data\nhead(simulated_health_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  lot_win insurance_status health_outcome\n1       1                1       4.203441\n2       1                0       3.611472\n3       1                1       5.913553\n4       0                0       5.356231\n5       1                0       3.096004\n6       0                0       4.510023\n```\n\n\n:::\n:::\n\n\n\nSimilar to the Oregon experiment, lottery winners are only enrolled in the insurance program if they submit a set of required documents. We can see that winning the lottery does not guarantee enrollment since there are individuals for whom `lot_win == 1` and `insurance_status == 0`.\n\nLet's find the share of individuals who won the lottery but did not enroll in the insurance program.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshare_enrolled <- simulated_health_data %>%\n                  filter(lot_win == 1) %>%    # filter for lottery winners\n                  summarize(share_enrolled = sum(insurance_status)/sum(lot_win))    # find % of winners who enrolled\nprint(as.double(share_enrolled))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6501976\n```\n\n\n:::\n:::\n\n\n\nOnly 65\\% of those who win the lottery actually enroll in the insurance program. This adds bias to the randomization process and deems a simple difference in means (and consequently, an OLS estimate) an inappropriate estimate of the causal effect.\n\nLet's (1) calculate the OLS estimate as if this was a traditional RCT (2) calculate our adjusted estimate of the causal effect. Since we're working with simulated data, we can compare our estimates to the true underlying relationships.\n\n#### Calculating the OLS estimate\n\nLet's use the `lm()` function to calculate the OLS estimate as if this was a traditional RCT. We log-transform health outcomes to interpret the coefficient in percentage terms.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#  run linear regression\nOLS_estimate <- lm(log(health_outcome) ~ insurance_status, data = simulated_health_data)\n\n# test significance of coefficients with robust standard errors\ncoeftest(OLS_estimate, vcov=vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n                  Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)      1.4497924  0.0094603 153.250 < 2.2e-16 ***\ninsurance_status 0.2153683  0.0122449  17.588 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nThe OLS estimate of the effect of insurance on health outcomes is very large: insured individuals have 21.5\\% better health outcomes on average. This estimate supports the idea that there are large benefits in extending health insurance coverage to the population that is currently uninsured.\n\n#### Calculating our adjusted estimate\n\nLet's calculate the adjusted estimate that we derived in the previous section.\n\nFirst, we calculate the average values of insurance status and health outcomes conditional on lottery result. We store those values in a data frame called `conditional_means`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nconditional_means <- simulated_health_data %>%\n                     group_by(lot_win) %>%    # group data based on lottery results\n                     summarize(avg_insurance_status = mean(insurance_status),    # calculate sample averages of status and outcomes\n                     avg_health_outcome = mean(log(health_outcome)))            \nconditional_means\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  lot_win avg_insurance_status avg_health_outcome\n    <dbl>                <dbl>              <dbl>\n1       0                0                   1.50\n2       1                0.650               1.54\n```\n\n\n:::\n:::\n\n\n\nNow, we divide the difference in conditional means of health outcomes by the difference in conditional means of insurance status.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate difference in conditional means of health outcomes\neffect_lot_health <- conditional_means[2,3] - conditional_means[1,3]\n\n# calculate difference in conditional means of insurance status\neffect_lot_insurance <- conditional_means[2,2] - conditional_means[1,2]\n\n# calculate adjusted estimate\nadjusted_estimate <- as.double(effect_lot_health/effect_lot_insurance)\nprint(adjusted_estimate)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05724885\n```\n\n\n:::\n:::\n\n\n\nThe estimated causal effect calculated with our adjusted estimate is approximately 5.7\\% - just a fraction of the OLS estimate. \n\nThis stark difference suggests that there is OVB in our OLS estimate. Before we look at what's happening under the hood, let's formalize what we did in this example.\n\n### Formalizing instrumental variables\n\nWe use **instrumental variables** (IVs) to isolate causal effects from models that might be plagued with omitted variable bias or endogeneity. IVs allow us to make causal inferences with observational data when OLS estimators are biased. \n\nWe were interested in estimating $\\beta_1$ in the model below:\n\n$$\nHealth_i = \\beta_0 + \\beta_1 Insurance_{i} + \\epsilon_i\n$$\n\nWe say that a variable $Z$ can be used as an instrumental variable for $Insurance$ only if it satisfies all of the following conditions:\n\n-   $Z$ is randomly assigned (or as good as randomly assigned)\n-   $Z$ has a causal effect on $Insurance$\n-   $Z$ affects the outcome variable $Health$ exclusively through $Insurance$ (that is, $Z$ does not have a direct effect on $Health$)\n\nIt should be clear that lottery results can be used as an instrument since it is a variable that satisfies the three conditions: (1) is randomly assigned (2) has a causal effect on insurance status (3) only affects health outcomes through insurance status.\n\n### Formalizing the Wald estimator\n\nThe **Wald estimator** uses instrumental variables to compute the causal effect of the variable of interest on the outcome. It does so through the relationship which we have derived in the context of the Oregon Health Insurance Experiment.\n\nAs long as the three IV assumptions are met, the effect of the instrument on the variable of interest times the effect of the variable of interest on the outcome equals the effect of the instrument on the outcome. For an instrument $Z$, a treatment $D$, and an outcome $Y$:\n\n$$\n\\text{Effect of } Z \\text{ on } D \\cdot \\text{Effect of } D \\text{ on } Y = \\text{Effect of } Z \\text{ on } Y\n$$\n\nRearranging the equation gets us to the effect we're interested in calculating:\n\n$$\n\\text{Effect of } D \\text{ on } Y = \\frac{\\text{Effect of } Z \\text{ on } Y}{\\text{Effect of } Z \\text{ on } D}\n$$\n\nWhen $Z$ is a binary variable, our relationship of interest can be written as a differences in conditional means:\n\n$$\n    \\text{Effect of } D \\text{ on } Y = \\frac{\\mathbb{E}[Y_{i} \\mid Z_{i} = 1] - \\mathbb{E}[Y_{i} \\mid Z_{i} = 0]}{\\mathbb{E}[D_{i} \\mid Z_{i} = 1] - \\mathbb{E}[D_{i} \\mid Z_{i} = 0]}\n$$\n\nThis is exactly what we did in our example with simulated data. Let's turn back to our analysis and compare our estimates to the true underlying relationships.\n\n### Back to the insurance example with simulated data\n\nLet's compare our OLS estimate (21.5\\%) and Wald estimate (5.7\\%) to the underlying relationships of the data.\n\nThe following dataset `simulated_health_data_extended` includes the variable `income`, coded in thousands of dollars per year.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# inspect the dataset\nhead(simulated_health_data_extended)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  lot_win    income insurance_status health_outcome\n1       1  54.77738                1       4.203441\n2       1  37.02049                0       3.611472\n3       1 279.20750                1       5.913553\n4       0 211.92480                0       5.356231\n5       1  22.10942                0       3.096004\n6       0  90.92389                0       4.510023\n```\n\n\n:::\n:::\n\n\n\nIn this (very simplified) simulated world, `income` was the only source of bias in our original model.\n\nIf we had income data from the start, we could have solved the OVB by simply controlling for income on a regression of health outcomes on insurance status. Let's do that now.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run linear regression controlling for income\nextended_model <- lm(log(health_outcome) ~ insurance_status + log(income), data = simulated_health_data_extended)\n\n# test significance of coefficients with robust standard errors\ncoeftest(extended_model, vcov=vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n                  Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)      0.4619388  0.0118137  39.102 < 2.2e-16 ***\ninsurance_status 0.0580070  0.0019328  30.013 < 2.2e-16 ***\nlog(income)      0.2251684  0.0025261  89.137 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nThe extended model shows that, controlling for income, the causal effect of insurance on outcomes is 5.8\\% - very similar to our Wald estimate. Income is positively related to both health outcomes and insurance status, and is the main determinant of health outcomes in our fictitious state.\n\nThe true causal effect of insurance on outcomes is actually 5\\%[^2]. The difference between the Wald estimate, the extended model, and the true causal effect can be attributed to sampling variance.\n\n[^2]: We know because the data is simulated.\n\nThis example shows that the Wald estimator can be used to solve OVB when we do not have data to control for the omitted variable in our model. That was only possible because we had an instrument that was (1) randomly assigned (2) causally related to the variable of interest (3) only affected the outcome through the variable of interest.\n\n#### From the Wald estimator to the 2SLS estimator\n\nThe Wald estimator is useful to build the intuition around instrumental variables. However, researchers rarely use it in their research. Researchers typically use a much more flexible estimator, the **2SLS estimator**.\n\nThe 2SLS estimator, which we will denote $\\beta^{TSLS}_{1}$, is equivalent to the Wald estimator. For an instrument $Z$, a treatment $D$, and an outcome $Y$:\n\n$$\n    \\text{Effect of } D \\text{ on } Y = \\frac{\\mathbb{E}[Y_{i} \\mid Z_{i} = 1] - \\mathbb{E}[Y_{i} \\mid Z_{i} = 0]}{\\mathbb{E}[D_{i} \\mid Z_{i} = 1] - \\mathbb{E}[D_{i} \\mid Z_{i} = 0]} = \\beta^{TSLS}_{1}\n$$\n\n To calculate $\\beta^{TSLS}_{1}$, we have to run 2 regressions. The first regression is a regression of the treatment on the instrument, called the **first stage regression**. The second regression is a regression of the outcome on the fitted values of the first stage regression, called the **second stage regression**. Follow the step-by-step below.\n\n\n(1) Run the first stage regression:\n\n$$\n    D_{i} = \\beta_{0} + \\beta_{1}Z_{i} + v_{i}\n$$\n\n(2) Store the fitted values from the first stage regression $\\widehat{D_{i}}$:\n\n$$\n    \\widehat{D_{i}} = b_{0} + b_{1}Z_{i}\n$$\n\nwhere $b_{0}$, $b_{1}$ are the estimated coefficients of the first stage.\n\n(3) Run the second stage regression:\n\n$$\n    Y_{i} = \\beta^{TSLS}_{0} + \\beta^{TSLS}_{1}\\widehat{D_{i}} + u_{i}\n$$\n\nThe coefficient on our second stage regression $\\beta^{TSLS}_{1}$ is the effect of interest: the causal effect of $D$ on $Y$.\n\n#### Calculating the 2SLS estimate\n\nLet's calculate the 2SLS estimate of the effect of insurance on health with our simulated health insurance data.\n\n(1) Run the first stage:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run the first stage regression\nhealth_st1 <- lm(insurance_status ~ lot_win, data = simulated_health_data)\n\n# test significance of coefficients with robust standard errors\ncoeftest(health_st1, vcov=vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n              Estimate Std. Error t value  Pr(>|t|)    \n(Intercept) 8.6507e-15 8.8818e-17  97.398 < 2.2e-16 ***\nlot_win     6.5020e-01 2.1243e-02  30.608 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nSimilar to our Wald estimate, the first stage indicates that winning the lottery increases the probability of insurance coverage by 65\\%. The effect is significant at the 0.1\\% significance level.\n\n> **Think deeper**: what would happen if the coefficient on `lot_win` was not significant?\n\n(2) Store the fitted values of the first stage:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# store fitted values as a new column named `insurance_status_hat`\nsimulated_health_data$insurance_status_hat <- health_st1$fitted.values\n\n# look at a subset of the updated dataset\nhead(simulated_health_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  lot_win insurance_status health_outcome insurance_status_hat\n1       1                1       4.203441         6.501976e-01\n2       1                0       3.611472         6.501976e-01\n3       1                1       5.913553         6.501976e-01\n4       0                0       5.356231         6.921547e-16\n5       1                0       3.096004         6.501976e-01\n6       0                0       4.510023         6.921547e-16\n```\n\n\n:::\n:::\n\n\n\n(3) Run the second stage:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run the second stage regression\nhealth_st2 <- lm(log(health_outcome) ~ insurance_status_hat, data = simulated_health_data)\n\n# test significance of coefficients with robust standard errors\ncoeftest(health_st2, vcov=vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n                     Estimate Std. Error  t value Pr(>|t|)    \n(Intercept)          1.501814   0.010289 145.9694  < 2e-16 ***\ninsurance_status_hat 0.057249   0.023162   2.4717  0.01361 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nOur 2SLS estimate is 5.7\\% - exactly equal to our Wald estimate. Let's take a moment to understand why this works.\n\n#### Making sense of the 2SLS estimate\n\nRemember that the problem with just running a simple OLS when there is OVB is that the *variable of interest is correlated to the error term* of the model: $Cov(Insurance_{i}, \\epsilon_{i})\\neq 0$.\n\nWhen we run the first stage, we effectively decompose the treatment into two parts: the error term and the variation explained by the instrument (the fitted values). Since the instrument is randomly assigned (or as good as randomly assigned) and the fitted values are driven solely by the instrument, *the fitted values are necessarily not correlated to the error term*: $Cov(\\widehat{Insurance_{i}}, \\epsilon_{i}) = 0$.\n\nProblem solved. We throw away the bad variation of the treatment (the error term of the first stage) and run a regression of the outcome on the good variation of the treatment (the fitted values of the first stage). The estimated coefficient of this regression is our 2SLS estimate, an unbiased estimate of the causal effect.\n\nIt is important to remember that this only works when the instrument satisfies the three criteria:\n\n(1) Random assignment: the instrument is as good as randomly assigned\n(2) Relevance: the instrument has a causal effect on the variable of interest\n(3) Exogeneity: the instrument only affects the outcome through the variable of interest\n\n> At this point, you should have the background knowledge to understand most of what the researchers did to measure the effect of insurance on health in the Oregon Health Insurance Experiment. The Baicker (2013) study can be read for free on the [New England Journal of Medicine](https://www.nejm.org/doi/10.1056/NEJMsa1212321?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200www.ncbi.nlm.nih.gov). We recommend reading the \"Special Article\" as well as the \"Analytic Specifications\" section (pages 5-7) of the Supplementary Appendix.\n\nIn the following example, we'll show how we can take advantage of the flexibility of the 2SLS estimator to use instruments that are not randomly assigned.\n\n## Example 2: College Proximity and Returns to Education\n\nAn interesting topic in labor economics is understanding how education affects future earnings. Card (1993) investigates this relationship by calculating the economic returns to schooling with college proximity as an instrumental variable.\n\nIn this example, we'll try to answer the same questions as Card (1993) with a simplified version of his dataset. Our dataset `cdist_data` contains the following variables for high school graduates:\n\n-   `distance` dummy == 1 for living close to 4-year college in 1966\n-   `momdad14` dummy == 1 for living with both parents at age 14\n-   `black` dummy == 1 for being black\n-   `south` dummy == 1 for living in the south in 1976\n-   `urban` dummy == 1 for living in urban area in 1976\n-   `wage` for wage in 1976\n-   `educ` for years of education in 1976\n-   `exper` for years of experience in 1976\n-   `fatheduc` for years of father's education\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# view data\nhead(as.data.frame(cdist_data))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  educ age fatheduc momdad14 south black wage exper urban distance\n1    7  29       10        1     0     1  548    16     1        0\n2   12  27        8        1     0     0  481     9     1        0\n3   12  34       14        1     0     0  721    16     1        0\n4   11  27       11        1     0     0  250    10     1        1\n5   12  34        8        1     0     0  729    16     1        1\n6   12  26        9        1     0     0  500     8     1        1\n```\n\n\n:::\n:::\n\n\n\n\n### The selection problem\n\nThe question we want to answer is: **what is the effect of an extra year of education on wages?**\n\nA simple regression of `wage` on `education` would generate a biased estimate of the causal effect because education is not randomly assigned across the surveyed. As Card (1993) put it, \"individuals make their own schooling choices; depending on how these choices are made, measured earnings differences between workers with difference levels of schooling may over-state or under-state the true return to education.\" That is just another way of saying that the model contains selection bias.\n\nWe have two potential solutions for this problem (1) solving the OVB with additional control variables (2) solving the OVB with an instrumental variable that is randomly assigned (or as good as randomly assigned). Let's try both approaches and compare them with the (biased) OLS estimate.\n\n#### Calculating the OLS estimate\n\nFirst, let's estimate the returns to education with simple regression of the form:\n\n$$\n\\log(wage_i) = \\beta_0 + \\beta_1 education_i + u_i, \n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run linear regression\nsimple_OLS <- lm(log(wage) ~ educ, data=cdist_data)\n\n# test significance of coefficients with robust standard errors\ncoeftest(simple_OLS, vcov=vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n             Estimate Std. Error t value  Pr(>|t|)    \n(Intercept) 5.5708823  0.0391347 142.351 < 2.2e-16 ***\neduc        0.0520942  0.0029099  17.902 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nThe OLS estimate for the returns to education is a 5.2\\% boost in earnings for every additional year of schooling.\n\n#### Controlling for observable differences\n\nLet's try adding controls. Remember from the linear regression section that we should try controlling for confounding variables: variables that affect earnings and/or education but are not affected by education. Let's follow Card (1993) and add the controls `momdad14`, `south`, `black`, `fatheduc`, `exper`, and `urban`.\n\n> Card (1993) runs additional specifications with `exper` as endogenous, but we'll limit our analysis to this single model.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run linear regression\nmultiple_OLS <- lm(log(wage) ~ educ + momdad14 + south + black + fatheduc + exper + urban, data=cdist_data)\n\n# test significance of coefficients with robust standard errors\ncoeftest(multiple_OLS, vcov=vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n               Estimate  Std. Error t value Pr(>|t|)    \n(Intercept)  4.89585136  0.06838126 71.5964   <2e-16 ***\neduc         0.07305334  0.00378057 19.3234   <2e-16 ***\nmomdad14     0.02846695  0.01788123  1.5920   0.1115    \nsouth       -0.12944651  0.01550886 -8.3466   <2e-16 ***\nblack       -0.18058719  0.01848351 -9.7702   <2e-16 ***\nfatheduc     0.00037098  0.00248502  0.1493   0.8813    \nexper        0.03925794  0.00225366 17.4197   <2e-16 ***\nurban        0.16496612  0.01525507 10.8139   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nWhen adding controls, the estimated returns to education increase to 7.3\\% higher wages for every additional year of schooling.\n\n#### Using an instrumental variable to estimate the causal effect\n\nLet's estimate the returns to education using college proximity as an instrumental variable. The logic behind choosing this instrument is that students who live closer to colleges are more likely to pursue more education than those who live further away.\n\nThe variable `distance` on our dataset maps whether the survey respondents live close to a 4-year college. Let's estimate the returns to education with the 2SLS estimator.\n\n(1) Run the first stage regression:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run the first stage\ndist_s1 <- lm(educ ~ distance , data=cdist_data)\n\n# test significance of coefficients with robust standard errors\ncoeftest(dist_s1, vcov=vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n             Estimate Std. Error  t value  Pr(>|t|)    \n(Intercept) 12.698015   0.090284 140.6448 < 2.2e-16 ***\ndistance     0.829019   0.106753   7.7657 1.105e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nThe fitted values of our first stage are given by: \n$$\n\\widehat{education_{i}}= 12.698 + 0.829 distance_{i}\n$$\n\nWe find that students living close to a 4-year college pursue 0.83 years more of education than those who don't live close to a college. The effect is significant at the 0.1% significance level.\n\n(2) Store the fitted values from the first stage:\n\nWe store the fitted values of our first stage regression, $\\widehat{education_{i}}$ as the variable `educ_hat` in our dataset `cdist_data`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# store fitted values as a new column named `educ_hat`\ncdist_data$educ_hat <- dist_s1$fitted.values\n\n# view the appended dataset\nhead(cdist_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 11\n# Rowwise: \n   educ   age fatheduc momdad14 south black  wage exper urban distance educ_hat\n  <dbl> <dbl>    <dbl>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>    <dbl>    <dbl>\n1     7    29       10        1     0     1   548    16     1        0     12.7\n2    12    27        8        1     0     0   481     9     1        0     12.7\n3    12    34       14        1     0     0   721    16     1        0     12.7\n4    11    27       11        1     0     0   250    10     1        1     13.5\n5    12    34        8        1     0     0   729    16     1        1     13.5\n6    12    26        9        1     0     0   500     8     1        1     13.5\n```\n\n\n:::\n:::\n\n\n\n(3) Run the second stage regression:\n\n$$\n\\log(wage_{i}) = \\beta_0 + \\beta_1 \\widehat{education_{i}} + u_i.\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run the second stage\ndist_s2 <- lm(log(wage) ~ educ_hat, data=cdist_data)\n\n# test significance of coefficients with robust standard errors\ncoeftest(dist_s2, vcov = vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n            Estimate Std. Error t value  Pr(>|t|)    \n(Intercept) 3.767472   0.272642 13.8184 < 2.2e-16 ***\neduc_hat    0.188063   0.020556  9.1486 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nThe 2SLS estimate for the returns to education is a staggering 18.8\\% increase in wages for every additional year of schooling. This result suggests substantial returns to education; even higher than the range of 10-14\\% found by Card (1993). More importantly, this estimate differs significantly from the 5-7\\% range that we found with our OLS estimates.\n\nBut we're not done yet. We need to take a closer look at our model, understand the shortcomings of our modeling choices, and try to fix them. Before doing that though, let's take a quick look at `ivreg()`.\n\n#### Estimating 2SLS directly with `ivreg()`\n\nThe function `ivreg()` from the `AER` package carries out 2SLS automatically. It follows the same structure as `lm()`, with the added feature of specifying instruments with a vertical bar after the regression formula. Let's run `ivreg()` on our college distance data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run 'ivreg()' regression\ndist_ivreg <- ivreg(log(wage) ~ educ | distance, data = cdist_data)\n\n# test significance of coefficients with robust standard errors\ncoeftest(dist_ivreg, vcov = vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n            Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)  3.76747    0.34698  10.858 < 2.2e-16 ***\neduc         0.18806    0.02616   7.189 8.197e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nNotice that `ivreg()` gives us the same result as running the first and second stages independently: an additional year of education is associated with a 18.8\\% increase in wages. However, `ivreg()` gives us larger standard errors. This might be a problem for hypothesis testing... More on this later.\n\n> Although we report our main results with `ivreg()`, running first stage regressions is useful for testing assumptions about instrument relevance. We discuss this on *Instrumental Variables 2*.\n\n### Analyzing the results\n\nNow that we have estimated the returns to education with OLS, multiple regression, and 2SLS, let's think critically about the estimated coefficients and reflect about any possible shortcomings of our modeling choices. Use the following questions to guide your reflection:\n\n-   Are we confident that our multiple regression specification solves the selection problem? Are there any important effects that we have failed to control? If yes, what is the probable direction of the bias?\n\n-   Is college proximity a good instrument? If not, what assumptions does it fail to meet? Is there any way that we could improve our IV approach?\n\nThe answers to some of these questions can be found on [Card (1993)](https://davidcard.berkeley.edu/papers/geo_var_schooling.pdf). Read through the paper to find out how he solves the selection problem.\n\n### Adding controls to the IV regression\n\nWe have a problem with our instrument: college proximity is not randomly assigned. It is possible that distance from a 4-year college is correlated to the error term of the model (for example, marginalized groups living far from colleges could be less likely to both attend college and work high-paying jobs). \n\nTo fix this we need to control for variables which undermine our instrument (for example, ethnicity) in the IV regression. If we are able to control for all sources of variation that affect our outcome directly (or indirectly, through a variable that is not our instrument), the instrument will be \"as good as randomly assigned\"\n\nIn our example, we need to control for all potential determinants of college proximity that also affect wages directly. Controlling for these potential sources of variation (`momdad14`, `south`, `black`, `fatheduc`, `exper`, `urban`), we can be more confident (although not 100\\% confident) that our instrument satisfies the three IV conditions.\n\nLet's run our extended IV regression with `ivreg()`:\n\n> Note that `ivreg()` requires users to specify the control variables on both sides of the vertical bar.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run 'ivreg()' regression with controls\ndist_ivreg <- ivreg(log(wage) ~ educ + momdad14 + south + black + fatheduc + exper + urban | distance + momdad14 + south + black + fatheduc + exper + urban, data = cdist_data)\n\n# test significance of coefficients with robust standard errors\ncoeftest(dist_ivreg, vcov = vcovHC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nt test of coefficients:\n\n              Estimate Std. Error t value  Pr(>|t|)    \n(Intercept)  3.9094711  0.8118751  4.8154 1.542e-06 ***\neduc         0.1418015  0.0565698  2.5067 0.0122401 *  \nmomdad14    -0.0148690  0.0403914 -0.3681 0.7128077    \nsouth       -0.1113123  0.0219196 -5.0782 4.043e-07 ***\nblack       -0.1380354  0.0394155 -3.5021 0.0004684 ***\nfatheduc    -0.0103807  0.0091567 -1.1337 0.2570217    \nexper        0.0640102  0.0203599  3.1439 0.0016832 ** \nurban        0.1366726  0.0284443  4.8049 1.624e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\nOur estimate is a 14.2\\% increase in earnings for every additional year of education. This is well within the range of 10-14\\% found by Card (1993). \n\n### Local average treatment effect (LATE)\n\nOur 2SLS estimate with controls is twice as large as our multiple regression estimate. If we're controlling for so many variables in the multiple regression, what is driving such a big difference in estimates?\n\nIt is possible that the **treatment on the treated (TOT)** and **local average treatment effect (LATE)** are different for our subjects. \n\nWhen we use traditional regression methods to estimate causal effects, we use the entire (within group) variation of the treatment to calculate the causal effect. This is what we call treatment on the treated.\n\nWhen we use instrumental variables, we isolate the variation of the treatment driven by the instrument. If the instrument does not affect the entire population equally, we could systematically exclude observations with economic meaning from our calculation. We have three types of individuals in the college distance dataset:\n\n1. Those who would go to college regardless of where they live: the *always-takers*.\n2. Those who wouldn't go to college regardless of where they live: the *never-takers*.\n3. Those who would go to college only if they live close to a 4-year college: the *compliers*.\n\nAlthough both always-takers and compliers are treated, an IV approach only uses the variation of compliers to estimate the causal effect. That makes sense: since the instrument doesn't affect the choice of individuals type 1 and 2 of going to college, their instrument-driven variation must necessarily be zero. We call the causal effect on compliers the local average treatment effect.\n\nIt is likely that the compliers in our dataset are lower-income students, who would only go to college if they could live with their parents and not pay housing costs. If that is true, then the difference in results between the multiple regression and the IV regression could be driven by differences in the TOT and LATE (and not just OVB). \n\nOur larger LATE could suggest that the returns to education for the poor are higher than the returns to education for the rich, a finding that could influence the decisions that both agents and policymakers make about education spending. \n\n### A note on standard errors\n\nPreviously, we noted that standard errors from manually estimated 2SLS and `ivreg()` are different. It is important to note that ***the correct standard errors are those calculated by*** `ivreg()`.\n\nStandard errors from manually calculated 2SLS do not adjust for the added uncertainty inherent to IVs: the fact that we use predictions from the first stage regression as regressors in the second stage regression. The IV standard erros fix for this additional uncertainty by adding a term for the correlation between the instrument and the treatment. This makes IV standard errors from `ivreg()` larger and more accurate than `lm()` standard errors.",
    "supporting": [
      "advanced_instrumental_variables1_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}