{
  "hash": "1a8ad6ec467bb20113da9f59021777e2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"1.3.2 - Beginner - Confidence Intervals\"\nauthor: COMET Team <br> _Anneke Dresselhuis, Colby Chambers, Jonathan Graves_\ndate: 12 January 2023\ndescription: What does it mean to be confident in a statistical estimate?  This notebook is an introduction to confidence, and confidence intervals - especially in the context of the mean value of a variable.\ncategories: [econ 325, confidence intervals, beginner, R, confidence level, point estimate, sample mean, t-distribution, normal distribution, sample proportion, chi-square distribution]\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html: default\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: R\n        language: r\n        name: ir\nimage: /media/comet_placeholder.png\n---\n\n\n## Outline\n\n### Prerequisites\n\n-   Introduction to Jupyter \n-   Introduction to R\n-   Introduction to Visualization\n-   Central Tendency\n-   Distribution \n-   Dispersion and Dependence \n\n### Outcomes\n\nAfter completing this notebook, you will be able to: \n\n-   Interpret and report confidence intervals \n-   Calculate confidence intervals under a variety of conditions \n-   Understand how the scope of sampling impacts confidence intervals\n\n### References\n\n-   [Simulating the Construction of Confidence Intervals for Sample\n    Means](https://rpubs.com/pgrosse/545955)\n\n## Introduction\n\nSo far, we have developed a strong grasp of core concepts in statistics. We've learned about measures of central tendency and variation, as well as how these measures relate to distributions. We have also learned about random sampling and how sampling distributions can shed light on the parameters of a population distribution.\n\nSo, how can we apply this knowledge to real empirical work? In this notebook, we will learn about a key concept which relates to how we report our results empirically when sampling from a population. This is the idea of a **confidence interval**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# importing packages\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(haven)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'haven' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# load self-tests\nsource(\"beginner_confidence_intervals_tests.r\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'digest' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\n# loading the dataset\ncensus_data <- read_dta(\"../datasets_beginner/01_census2016.dta\")\n\n# cleaning the dataset\ncensus_data <- filter(census_data, !is.na(census_data$wages))\ncensus_data <- filter(census_data, !is.na(census_data$mrkinc))\ncensus_data <- filter(census_data, census_data$pkids != 9)\n```\n:::\n\n\n\n## Part 1: Introducing Confidence Intervals\n\nA **confidence interval** is an estimate that gives us a range of values within which we expect a population parameter to fall. Put another way, it provides a range within which we can have a certain degree of *confidence* that a desired parameter, such as a population mean, lies.\n\nThis is in contrast to a **point estimate**, which is a specific estimated value of another object, like a population parameter. The point estimate of the population mean is the sample mean and the point estimate of the population standard deviation is the sample standard deviation.\n\nLet's make this concrete with an example.\n\nLet's say we're interested in finding the mean GPA of undergraduate students at universities across Canada.Instead of collecting the GPA of every single undergraduate student in the country without error, we collect a sample of students and find the mean of their GPAs (the sample mean). However, due to sampling variability, *our sample mean will probably not be exactly equal to the population mean*. It would be better to provide a range of values in which we think the population mean lies. This is where **confidence intervals** become useful - instead of just providing the sample mean, confidence intervals allow us to combine information about central tendency and dispersion into a single object.\n\n### Confidence levels\n\nThe confidence interval describes a range in which we think the population parameter lies. To calculate this confidence interval, we must choose a **confidence level**. The confidence level indicates the probability that the parameter lies within our confidence interval.\n\nA higher confidence level means greater certainty that our confidence interval serves as a good range of values for the population parameter of interest.\n\n**The most commonly chosen confidence level is 95%**, but other percentages (90%, 99%) are also used.\n\nIf we choose the 95% confidence level for our mean GPA example, we could say that we are **95% confident** that the true mean GPA of all Canadian undergraduates lies in the range of the confidence interval (which we'll learn to calculate below). Being 95% confident means that if we drew random samples of undergraduate students (e.g., 1000 samples), got different sample means for each sample (1000 sample means), and calculated confidence intervals from those sample means (1000 confidence intervals), we would expect 95% of the confidence intervals (950 confidence intervals) to contain the actual average GPA of all Canadian undergraduates.\n\n### Calculating confidence intervals\n\nThe official representation of a confidence interval is the following:\n\n$$\n(\\text{point estimate} - \\text{margin of error}, \\text{point estimate} + \\text{margin of error})\n$$\n\nor\n\n$$ \n\\text{point estimate} \\pm \\text{margin of error}\n$$\n\nWe add and subtract a **margin of error** from our point estimate to find the **lower bound** and **upper bound** of our confidence interval estimate. The calculation for the margin of error varies depending on the sample statistic. Let's look at a few important special cases: the confidence intervals for the sample mean, sample proportion, and sample variance.\n\n## Part 2: Confidence Intervals for the Sample Mean\n\nTo construct a confidence interval for a sample mean (e.g., the mean GPA of a sample of undergraduates), we must meet the following three conditions:\n\n1. Random sampling\n\n2. The sampling distribution of the sample means must be **approximately normal**, either because\n\n    -   The original population is normally distributed\n    -   The sample size is larger than 30 (invokes the Central Limit Theorem)\n\n3. Our sample observations must be **independent** either because\n\n    -   We sample with replacement (when we record an observation, we put it back in the population with the possibility of drawing it again)\n    -   Our sample size is less than 10% of the population size\n\nIf each of conditions 1-3 are met, we are able to construct a valid confidence interval around our sample mean. There are two different cases for this construction.\n\n### Case 1: when we know the population standard deviation\n\nIn rare instances when we may know the standard deviation of the population of interest, we use the following formula to calculate the confidence interval:\n\n$$\n\\bar x \\pm z_{\\alpha / 2} \\cdot \\frac{\\sigma}{\\sqrt n}\n$$\n\nwhere \n\n- $\\bar x$ is the sample mean\n- $z$ is the critical value (from the standard normal distribution) \n- $1-\\alpha$ is the confidence level\n- $\\sigma$ is the population standard deviation\n- $n$ is the sample size\n\n> **Note**: this case is extremely rare as it requires us to know the standard deviation but not the mean of a population! Typically we either know both the mean and standard deviation of the population or we know neither.\n\n### Case 2: when we don't know the population standard deviation\n\nIn this case, we estimate the population standard deviation with the sample standard deviation and we use the $t$-distribution to calculate the margin of error. Otherwise, the calculation procedure follows exactly as in Case 1.\n\n$$\n\\bar x \\pm t_{\\alpha / 2} \\cdot \\frac{s}{\\sqrt n}\n$$\n\nwhere \n\n- $\\bar x$ is the sample mean\n- $t$ is the critical value (from the $t$-distribution) \n- $1-\\alpha$ is the confidence level \n- $s$ is the sample standard deviation\n- $n$ is the sample size\n\nTo illustrate, let's construct a 95% confidence interval for the sample mean of the variable `wages`. We can use the function `mean()` to calculate its mean, which will serve as our point estimate.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculating the sample mean of wages\nsample_mean <- mean(census_data$wages)\nsample_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 55500.56\n```\n\n\n:::\n:::\n\n\n\nNow that we have this point estimate, we can calculate our margin of error around it. To do so, we must first find\n\n1.  The $t$ value corresponding to a 95% confidence level\n2.  The sample standard deviation of `wages`\n3.  The sample size (the number of observations recorded for `wages`)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# finding the sample size and associated degrees of freedom\nn <- nrow(census_data)\ndf <- n - 1\n\n# finding the t value for a confidence level of 95%\nt <- qt(p = 0.05, df = df)\n\n# finding the sample standard deviation of wages\ns <- sd(census_data$wages)\n\n# calculating the lower and upper bounds of the desired confidence interval\n\nlower_bound <- sample_mean - (t*s/sqrt(n))\nupper_bound <- sample_mean + (t*s/sqrt(n))\n\nlower_bound\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 55708.3\n```\n\n\n:::\n\n```{.r .cell-code}\nupper_bound\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 55292.82\n```\n\n\n:::\n:::\n\n\n\nWe are 95% confident that the mean wage of all Canadians ranges between $55708$ and $55293$. We also know this is a valid confidence interval estimate because our `wages` variable and the procedure for sampling meets all of the three criteria outlined:\n\n1.  Random sampling: Statistics Canada (the source for this data) utilizes random sampling\n2.  Our sample size is $n > 30$ and thus we don't even need to check the distribution of `wages`\n3.  Our observations are independent because our sample size $n$ is less than 10% of the total population (the total population of Canada is about 38 million)\n\n Relative to the large value of the sample mean, this confidence interval is very narrow. This means our confidence interval estimate is very precise.\n\n### Test your knowledge\n\nMatilda takes a random sample of 20 books from a library in order to estimate the average number of pages among all books in the library.\n\nDoes it make more sense for Matilda to use a standard normal distribution or a t-distribution to calculate the margin of error for her confidence interval?\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\n# replace \"...\" by your answer for \"z\" or \"t\" here\nanswer_1 <- \"...\"\n\ntest_1()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_1 <- \"t\"\n\ntest_1()\n```\n:::\n\n\n\nMatilda finds a sample mean of 280 pages and sample variance of 400 pages. She wants to construct a 90% confidence interval for her sample mean. What will be the upper and lower bounds of this interval (assuming it's a valid confidence interval)?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# here are the values you need to calculate\nsample_mean <- \ns <- \nn <- \ndf <- n-1 # this is given to help you out\nt <- \n```\n:::\n\n::: {.cell .question}\n\n```{.r .cell-code}\nlower_bound <- # your answer for the lower bound here, rounded to the nearest integer\nupper_bound <- # your answer for the upper bound here, rounded to the nearest integer\n\nanswer_2 <- lower_bound\nanswer_3 <- upper_bound\n\ntest_2()\ntest_3()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nsample_mean <- 280\ns <- 400\nn <- 20\ndf <- n - 1\nt <- qt(p = 0.1, df = df)\n\nlower_bound <- sample_mean - (t*s/sqrt(n))\nupper_bound <- sample_mean + (t*s/sqrt(n))\n\nanswer_2 <- lower_bound\nanswer_3 <- upper_bound\n\ntest_2()\ntest_3()\n```\n:::\n\n\n\n## Part 3: Confidence Intervals for the Sample Proportion\n\nSimilar to the sample mean, we can also calculate confidence intervals for sample proportions.\n\nSuppose a population must vote for one of the two political parties (A or B), and we want to find out the proportion of the population that voted for party A.\n\nTo do that we must\n\n1.  Collect a random sample and calculate the corresponding sample proportion\n2.  Estimate a confidence interval for the sample proportion\n\nJust like in the case of the sample mean, confidence intervals for sample proportions must satisfy three conditions:\n\n1. Random sampling\n\n2. The sampling distribution of the sample means must be **approximately normal**, because\n\n    -   There are at least 10 \"successes\" and 10 \"failures\" in our sample (e.g., at least 10 people in our sample voted for party A and at least 10 people voted for party)\n\n3. Our sample observations must be **independent** either because\n\n    -   We sample with replacement (when we record an observation, we put it back in the population with the possibility of drawing it again)\n    -   Our sample size is less than 10% of the population size\n\nIf conditions 1-3 are all met, we are able to construct a valid confidence interval around our sample proportion. There is a single case for calculating the margin of error and confidence interval for sample proportions.\n\n### Case: when we don't know the population standard deviation\n\nWhen we don't know the standard deviation of the population, we use the following formula to construct confidence intervals for sample proportions:\n\n$$\n\\hat P \\pm z_{\\alpha / 2} \\cdot \\sqrt \\frac {\\hat P \\cdot(1 - \\hat P)}{n}\n$$\n\nwhere \n- $\\hat P$ is the sample proportion\n- $z$ is the critical value (from the standard normal distribution) \n- $1-\\alpha$ is the confidence level\n- $n$ is the sample size\n\n> **Think deeper**: why is there only one case for confidence intervals of sample proportions?\n\nLet's calculate a 95% confidence interval for the sample proportion of the variable `pkids` from our `census_data`. `pkids == 1` for when the respondent lives in a household with kids, and `pkids == 0` otherwise. We can calculate our sample proportion, which serves as our point estimate for the confidence interval.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculating our sample proportion of observations with pkids == 1\np <- sum(census_data$pkids == 1) / nrow(census_data)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7089509\n```\n\n\n:::\n:::\n\n\n\nNow that we have our sample proportion, we can find our $z$ critical value for a 95% confidence level and calculate our confidence interval.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# finding the z value for a confidence level of 95%\nz <- qnorm(p = 0.05, lower.tail = FALSE) # lower.tail = FALSE gives us the right tail of the distribution\n\n# calculating the lower and upper bounds of the desired confidence interval\nn <- nrow(census_data)\nlower_bound <- p - z*sqrt(p*(1-p)/n)\nupper_bound <- p + z*sqrt(p*(1-p)/n)\n\nlower_bound\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7075431\n```\n\n\n:::\n\n```{.r .cell-code}\nupper_bound\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7103586\n```\n\n\n:::\n:::\n\n\n\nFrom our above calculations, we can say that we are 95% confident that the true proportion of Canadians with a child in their household ranges between $70.75\\%$ - $71.04\\%$.\n\n> **Note**: In rare cases when our sample proportion estimate is either too high or too low, we may find that the confidence interval may surpass the domain [0,1]. When that happens we can cap the confidence interval at 0 or 1 and make a note about it when reporting the results.\n\n### Test your knowledge\n\nMatilda now wants to know the proportion of students in her school who are left-handed. Let's assume her sampling procedure meets all of the criteria for constructing a valid confidence interval. She takes a sample of 200 students and finds that 22 of them are left-handed. What is the upper and lower bound of a 98% confidence interval for the proportion of the school's overall student body that are left-handed?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# your code here\n```\n:::\n\n::: {.cell .question}\n\n```{.r .cell-code}\nlower_bound <- # your answer for the lower bound here, rounded to 3 decimal places (in proportion form, i.e. 10% = 0.1)\nupper_bound <- # your answer for the upper bound here, rounded to 3 decimal places (in proportion form, i.e. 10% = 0.1)\n\nanswer_4 <- lower_bound\nanswer_5 <- upper_bound\n\ntest_4()\ntest_5()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nn <- 200\nestimate <- 22/n\nz <- qnorm(p = 0.02, lower.tail = FALSE)\n\nlower_bound <- round(estimate - (z * sqrt(estimate * (1 - estimate) / n)), 3)\nupper_bound <- round(estimate + (z * sqrt(estimate * (1 - estimate) / n)), 3)\n\nanswer_4 <- lower_bound\nanswer_5 <- upper_bound\n\ntest_4()\ntest_5()\n```\n:::\n\n\n\nLet's imagine that our sample size and confidence level are fixed and cannot be changed. What sample proportion of students who are left-handed would result in the smallest **valid** confidence interval possible?\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\n# enter your answers in the vector below in ascending order (smaller number first)\n\nanswer_6 <- c(...,...) # your answer for the sample proportions here (i.e. 10% = 0.1)\ntest_6()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_6 <- c(10/200,190/200)\n\ntest_6()\n```\n:::\n\n\n\n## Part 4: Confidence Intervals for the Sample Variance\n\nIf for some reason we want to estimate the standard deviation of a population, we could also create confidence intervals for the sample variance. The logic is the same as confidence intervals explained above, but instead of the sample mean or proportion, our point estimate is the sample variance. The conditions needed to construct a confidence interval for the sample variance are the same as the sample mean. We restate them below.\n\n1. Random sampling\n\n2. The sampling distribution of the sample means must be **approximately normal**, either because\n\n    -   The original population is normally distributed\n    -   The sample size is larger than 30 (invokes the Central Limit Theorem)\n\n3. Our sample observations must be **independent** either because\n\n    -   We sample with replacement (when we record an observation, we put it back in the population with the possibility of drawing it again)\n    -   Our sample size is less than 10% of the population size\n\nIf conditions 1-3 are all met, we are able to construct a valid confidence interval for our sample variance.\n\n### Case: when we don't know the population standard deviation\n\nWe only need worry about this case when calculating confidence intervals for the sample variance. If we knew the population standard deviation, we would also know the population variance and therefore not need to construct a confidence interval to estimate this number.\n\nThe formula for confidence intervals works a bit differently for the sample variance: instead of adding and subtracting a margin of error to our point estimate, we will use our point estimate to calculate the lower and upper bounds of our confidence interval directly.\n\n$$\n(\\frac{(n - 1) \\cdot s^2}{\\chi^2_{\\alpha/{2}}}, \\frac{(n - 1) \\cdot s^2}{\\chi^2_{1 - \\alpha/{2}}})\n$$\n\nwhere \n\n- $n$ is the sample size\n- $s^2$ is the sample variance\n- $\\chi^2$ is the critical value from the chi-squared distribution with $n - 1$ degrees of freedom\n- $1 - \\alpha$ is the confidence level\n\n> **Note**: Constructing this type of confidence interval is different from previous instances with the sample mean and sample proportion. This is because, unlike the sample mean and sample proportion, the sample variance follows a **non-normal distribution**: the $\\chi^2$ distribution.\n\nLet's construct a 95% confidence interval for the sample variance of `mrkinc`. Our procedure will follow exactly the steps above. First, let's calculate the sample variance:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculating the variance of mrkinc\nvar <- var(census_data$mrkinc)\nvar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7711295816\n```\n\n\n:::\n:::\n\n\n\nNow that we have our sample variance let's find the other statistics necessary to calculate our confidence interval estimate.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# finding sample size\nn <-nrow(census_data)\n\n# finding the chi-squared values for a 95% confidence level and n - 1 degrees of freedom\nupper_chi <- qchisq(p = 0.05, df = (n - 1), lower.tail = TRUE)\nlower_chi <- qchisq(p = 0.05, df = (n - 1), lower.tail = FALSE)\n\n# calculating the upper and lower bounds of the desired confidence interval\nlower_bound <- ((n - 1)*var)/lower_chi\nupper_bound <- ((n - 1)*var)/upper_chi\n\nlower_bound\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7677615858\n```\n\n\n:::\n\n```{.r .cell-code}\nupper_bound\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7745209769\n```\n\n\n:::\n:::\n\n\n\nTherefore, we are 95% confident that the variance of market income among all Canadians is within ($7677615858$, $7745209769$). This is quite a large interval, but given the size of the variance for this variable, it seems reasonable.\n\n### Test your knowledge\n\nMatilda wants to know the variance of weights of all cars sold at her father's car dealership. She takes the steps below.\n\n-   She takes a random sample of 40 cars and records their weights\n-   She finds that they have a sample mean weight of 5,000 pounds and a sample variance of 250,000\n\nMatilda wants to construct a 95% confidence interval estimate for the population variance. What are the upper and lower bounds of this confidence interval?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# write your code here\n# here are the variables you need to calculate\n\nn <- \nvar <-\n\nlower_chi <- \nupper_chi <-\n```\n:::\n\n::: {.cell .question}\n\n```{.r .cell-code}\nlower_bound <- # your answer for the lower bound here, rounded to the nearest whole number\nupper_bound <- # your answer for the upper bound here, rounded to the nearest whole number\n\nanswer_7 <- lower_bound\nanswer_8 <- upper_bound\n\ntest_7()\ntest_8()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nn <- 40\nvar <- 250000\n\nlower_chi <- qchisq(p = 0.05, df = (n - 1), lower.tail = FALSE)\nlower_bound <- ((n-1)*var)/lower_chi\n\nupper_chi <- qchisq(p = 0.05, df = (n - 1), lower.tail = TRUE)\nupper_bound <- ((n-1)*var)/upper_chi\n\nanswer_7 <- round(lower_bound)\nanswer_8 <- round(upper_bound)\n\ntest_7()\ntest_8()\n```\n:::\n\n\n\nLet's now say that Matilda draws a new random sample of 40 cars and reports with 95% confidence that the population variance of car weights falls within the confidence interval (490000, 640000). Under this sampling procedure, what is the 95% confidence interval estimate for the standard deviation of weights of all cars ever sold at the dealership?\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nanswer_9 <- # your answer for the lower bound here\nanswer_10 <- # your answer for the upper bound here\n\ntest_9()\ntest_10()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_9 <- sqrt(490000)\nanswer_10 <- sqrt(640000)\n\ntest_9()\ntest_10()\n```\n:::\n\n\n\n\n## Part 5: What Affects the Width of Confidence Intervals?\n\nWe can see that no matter the parameter we are estimating, we always need to specify:\n\n-   The confidence level\n-   The sample size\n\nLet's explore what happens to our confidence intervals when we change each of these numbers.\n\n### Changing the sample size\n\nLet's say we want to change our sample size $n$.\n\n-   If we **increase** our sample size $n$, both our margin of error and confidence interval will **decrease**. That happens because a larger sample makes our estimates more precise.\n\n-   If we **decrease** our sample size $n$, both our margin of error and confidence interval will **increase**. That happens because a smaller sample makes our estimates less precise.\n\nTo see this point interactively, run the code below in which we change the input $n$ for our function to create 95% confidence intervals. We can see that the size of the confidence intervals increase or decrease depending on whether we decrease or increase the simulated sample size.\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# simulating data\npopulation <- rnorm(10000, 0, 1)\n\n# defining a function which outputs a confidence interval for the sample mean given an input `n` for the sample size\ncreate_confidence_intervals <- function(n) {\n    x = mean(sample(population, n))\n    z = qnorm(p = 0.05, lower.tail=FALSE)\n    lower = x - (z*1/sqrt(n))\n    upper = x + (z*1/sqrt(n))\n    df = data.frame(lower, upper)\n    return(c(lower, upper))\n    }\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# confidence intervals with sample size 10\ncf_10 <- create_confidence_intervals(10)\ndifference_between_bounds <- cf_10[2] - cf_10[1]\n\ncf_10\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.2062310  0.8340658\n```\n\n\n:::\n\n```{.r .cell-code}\ndifference_between_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.040297\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# confidence intervals with sample size 20\ncf_20 <- create_confidence_intervals(20)\ndifference_between_bounds <- cf_20[2] - cf_20[1]\n\ncf_20\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.4194348  0.3161661\n```\n\n\n:::\n\n```{.r .cell-code}\ndifference_between_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7356009\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# confidence intervals with sample size 100\ncf_100 <- create_confidence_intervals(100)\ndifference_between_bounds <- cf_100[2] - cf_100[1]\n\ncf_100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.34319468 -0.01422395\n```\n\n\n:::\n\n```{.r .cell-code}\ndifference_between_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3289707\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# confidence intervals with sample size 10000\ncf_10000 <- create_confidence_intervals(10000)\ndifference_between_bounds <- cf_10000[2] - cf_10000[1]\n\ncf_10000\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.00541623  0.02748084\n```\n\n\n:::\n\n```{.r .cell-code}\ndifference_between_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03289707\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Try it yourself!\n# create_confidence_intervals(...)\n```\n:::\n\n\n\n\n### Changing the confidence level\n\n-   If we **increase** the confidence level to a higher percentage, then the new confidence interval will be **wider**.\n\n-   If we **decrease** the confidence level to a lower percentage, then the new confidence interval will be **narrower**.\n\nThe logic is simple: to be more confident that our confidence interval actually does contain the true value of the population parameter, we have to increase its range of values.\n\nThis all occurs mathematically through an increase/decrease in our margin of error (or bounds) due to the increase/decrease in our $z$ or $t$ critical values.\n\nTo see this point interactively, modify the code below by changing the input for $\\alpha$. We can see that the vertical length (width) of the confidence intervals increase or decrease depending on whether we increase or decrease the simulated confidence level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npopulation <- rnorm(10000, 0, 1)\n\n# defining a function which outputs a confidence interval for a given confidence level\ncreate_confidence_intervals <- function(alpha) {\n    x = mean(sample(population, 100))\n    z = qnorm(p = alpha, lower.tail=FALSE)\n    lower = x - (z*1/sqrt(100))\n    upper = x + (z*1/sqrt(100))\n    df = data.frame(lower, upper)\n    return(c(lower, upper))\n    }\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# confidence intervals with significance level 0.01\ncf_1_pct <- create_confidence_intervals(0.01)\ndifference_between_bounds <- cf_1_pct[2] - cf_1_pct[1]\n\ncf_1_pct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.3122216  0.1530480\n```\n\n\n:::\n\n```{.r .cell-code}\ndifference_between_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.4652696\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# confidence intervals with significance level 0.05\ncf_5_pct <- create_confidence_intervals(0.05)\ndifference_between_bounds <- cf_5_pct[2] - cf_5_pct[1]\n\ncf_5_pct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.42576371 -0.09679298\n```\n\n\n:::\n\n```{.r .cell-code}\ndifference_between_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.3289707\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# confidence intervals with significance level 0.1\ncf_10_pct <- create_confidence_intervals(0.1)\ndifference_between_bounds <- cf_10_pct[2] - cf_10_pct[1]\n\ncf_10_pct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.1917654  0.0645449\n```\n\n\n:::\n\n```{.r .cell-code}\ndifference_between_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2563103\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# confidence intervals with significance level 0.2\ncf_20_pct <- create_confidence_intervals(0.2)\ndifference_between_bounds <- cf_20_pct[2] - cf_20_pct[1]\n\ncf_20_pct\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.2555447 -0.0872204\n```\n\n\n:::\n\n```{.r .cell-code}\ndifference_between_bounds\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1683242\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Try it yourself!\n# create_confidence_intervals(...)\n```\n:::\n\n\n\n### Test your knowledge\n\nMatilda thinks that one of her confidence intervals above is too wide and wishes to narrow it. What could she do in order to achieve this goal?\n\n(A) increase the sample size and increase the confidence level\n(B) decrease the sample size and decrease the confidence level\n(C) increase the sample size and decrease the confidence level\n(D) decrease the sample size and increase the confidence level\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nanswer_11 <- \"...\" # your answer here\n\ntest_11()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_11 <- \"C\"\n\ntest_11()\n```\n:::\n\n\n\n## Part 6: Common Misconceptions\n\nUp to this point, we've covered what confidence intervals are, how we calculate them, and how they're sensitive to two key parameters. To wrap up, let's clarify a couple of misconceptions about the interpretation of confidence intervals.\n\n### Misconception 1:\n\n*If we have a 95% confidence interval, this is a **concrete range** under which our estimated population parameter **must** fall*.\n\nIf we repeated our sampling procedure many times and constructed a confidence interval each time, we would expect about 95% of these confidence intervals to contain our true parameter. **Note that this does not imply that the confidence interval we calculated contains the true parameter**. Since about 5% of our confidence intervals will not contain the true parameter, nothing prevents the confidence interval we calculate from being one of those 5% that don't contain the parameter.\n\nMain takeaway is that the confidence interval is an *estimator* and not an official range of possible values for the population parameter.\n\n### Misconception 2:\n\n*If we have a confidence level of 95%, 95% of our population data must lie within the calculated confidence interval*.\n\nThis is not true since our confidence level indicates the long run percentage of constructed confidence intervals which contain our true parameter but says nothing about the spread of our actual data. To find the range within which 95% of our data lie, we must consult a histogram for the population and calculate percentiles.\n\nFor instance, if our data is quite bimodal distributed (around half of our data is clustered far to the left of our mean, and the other half is clustered far to the right of our mean), our calculated 95% confidence interval will likely contain very little (much less than 95%) of the data.\n\nThe confidence level does **not** determine the spread of the actual data\n\n### Misconception 3:\n\n*If we have a confidence level of 95%, a confidence interval calculated from a sample of 500 observations will more likely contain the true parameter than a confidence interval calculated from a sample of 100 observations.*\n\nWe know from the previous section that a confidence interval generated from the sample $n = 500$ will be narrower than one generated from $n = 100$. However, a confidence level by definition is the percentage of calculated intervals we expect to contain the true parameter of interest if we calculated these intervals over and over. This means any one interval from a sample of $n = 100$ has a 95% chance of containing the true parameter, just as any one interval from a sample of $n = 500$ has a 95% chance of containing the true parameter. Each interval (the wider one from $n = 100$ and narrower one from $n= 500$) has a chance of containing the true parameter relative to all other calculated intervals for that same sample size.\n\nHence, whether we have an interval from a sample of $n = 100$ or $n = 500$, we are still 95% confident in both cases that the true parameter lies within that interval. The probability of a given interval containing the true parameter is not affected by the sample size. This probability only changes when we change our confidence level.\n\n::: callout-note\n## 🔎 **Let's think critically**\n\n- 🟠 Every research context will drastically shape how confidence intervals are approached. As we have seen, the volume and quality of data affect how accurate data analyses can be, and many rules of thumb in data science are simply that - rules of thumb, as opposed to hard facts about how to report statistics.\n- 🟠 What are some situations where you want to know that something is true with nearly 100% confidence?\n- 🟠 What are some situations where the uncertainty of statistic is maybe not so bad?\n- 🟠 What does it *really* mean to have something within or outside of a confidence interval?\n:::\n",
    "supporting": [
      "beginner_confidence_intervals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}