{
  "hash": "d02ecedff761e9ff18da0eed1421b956",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: '2.5 - Intermediate - Interactions and Non-linear Terms'\nauthor: 'COMET Team <br> _Emrul Hasan, Jonah Heyl, Shiming Wu, William Co, Jonathan Graves_'\ndate: 8 December 2022\ndescription: 'How do we specific non-linear models?  Why would we want to do so?  This notebook covers non-linear and interaction models, including marginal effects and related issues.'\ncategories: [econ 326, multiple regression, regression, controls, intermediate, R, interaction terms, non-linear terms, polynomial terms, continuous variable]\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html: default\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: R\n        language: r\n        name: ir\nimage: /media/comet_placeholder.png\n---\n\n## Outline\n\n### Prerequisites\n- Multiple regression\n- Simple regression\n- Data analysis and introduction\n\n### Outcomes\nIn this worksheet, you will learn:\n\n- How to incorporate interaction terms into a regression analysis\n- How to interpret models with interaction terms\n- How to create models which include non-linear terms\n- How to compute simple marginal effects for models with non-linear terms\n- How to explain polynomial regressions as approximations to a non-linear regression function\n\n### References\n\n- Statistics Canada, Survey of Financial Security, 2019, 2021. Reproduced and distributed on an \"as is\" basis with the permission of Statistics Canada. Adapted from Statistics Canada, Survey of Financial Security, 2019, 2021. This does not constitute an endorsement by Statistics Canada of this product.\n\n- Stargazer package is due to: Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables. R package version 5.2.3. https://cran.r-project.org/web/packages/stargazer/index.html\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(haven)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'haven' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(scales)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'scales' was built under R version 4.4.3\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(stargazer)\nlibrary(car)\n\nsource(\"intermediate_interactions_and_nonlinear_terms_functions.r\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'digest' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nsource(\"intermediate_interactions_and_nonlinear_terms_tests.r\")\n\nSFS_data <- read_dta(\"../datasets_intermediate/SFS_2019_Eng.dta\")\nSFS_data <- clean_up_data()\n```\n:::\n\n\n## Part 1: Interactions in Regression Models\n\nOne of the most common extensions to multiple regression models is to include **interaction** terms.  What is an interaction term?  It's basically a term which represents the product of two (or more) variables in a model.\n\nFor example, if we have a dummy variable for being a female ($F_i$) and a dummy variable for having a university degree ($D_i$), the _interaction_ of these two variables is the product $D_i \\times F_i$.  This can seem complicated, but it also has a simple interpretation: it is now a dummy for being _both_ a female and having a university degree.  You can see why this is true:\n\n$$ \nD_i \\times F_i = 1 \\iff D_i = 1 \\text{ and } F_i = 1\n$$\n\nThis is why these terms are so important for understanding regressions: they provide us with a simple way to describe and study how *combinations* of our explanatory variables impact our model.  These variables enter into our regression models in exactly the same way as usual:\n\n$$\nY_i = \\beta_0 + \\beta_1 F_i + \\beta_2 D_i + \\beta_3 D_i \\times F_i + \\epsilon_i\n$$\n\nAt this point, you can see that this is just a multiple regression model - the only difference is that one of the variables is a combination of the other variables.  From an estimation perspective, there's no issue - you can use OLS to estimate a model with interaction terms, just like simple regressions.  However, as we have seen, there are important differences when it comes to the *interpretation* of these models.  Let's learn more about this in this worksheet.\n\nThere are (in general) two ways to create interactions in R: (i) manually (i.e. creating a new variable which is $D_i \\times F_i$ then adding it to the regression), or (ii) using the built-in tools in R.  However, method (i) is a trap!  You should never use this method.  Why?  There are two reasons:\n\n1.  The main reason is that R (and you, the analyst) lose track of the relationship between the created interaction variable and the underlying variables.  This means that you can't use other tools to analyze this relationship (there are many packages such as `margins` which allow you to investigate complex interactions) which is a big loss.  You also can't perform post-regression analysis on the underlying variables in a simple way anymore.\n2.  The second reason is that it's easy to make mistakes.  You might define the interaction incorrectly (possible!).  However, it's more of an issue if later on you change the underlying variables and then forget to re-compute the interactions.  It also makes your code harder to read.\n\nBottom line: don't do it.  Interactions in R are easy to create: you simply use the `:` or `*` operator when defining an interaction term.  \n\n- The `:` operator creates the interaction(s) of the two variables in question\n- The `*` operation creates the interactions(s) _and_ the main effects of the variables as well\n\nEven better: if you are interacting two qualitative (factor) variables, it will automatically \"expand\" the interaction into every possible combination of the variables.  A lot less work!\n\nFor example, let's look at a regression model which interacts gender and education. Before we run regression, let's first summarize education into 'university' and 'non-university'.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSFS_data <- SFS_data %>% # creates a Education dummy variable\n               mutate( \n               Education = case_when(\n                     education == \"University\" ~ \"University\", # the ~ separates the original from the new name\n                     education == \"Non-university post-secondary\" ~ \"Non-university\",\n                     education == \"High school\" ~ \"Non-university\",\n                     education == \"Less than high school\" ~ \"Non-university\")) %>%\n             mutate(Education = as_factor(Education)) # remember, it's a factor!\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nregression1 <- lm(wealth ~ gender + Education + gender:Education, data = SFS_data)\n\n# regression1 <- lm(wealth ~ gender*Education, data = SFS_data) # an alternative way to run the same regression\n\nsummary(regression1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wealth ~ gender + Education + gender:Education, \n    data = SFS_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2286681  -745004  -438908   240471 29236721 \n\nCoefficients:\n                                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                        818279      27274  30.003  < 2e-16 ***\ngenderFemale                      -143396      44247  -3.241   0.0012 ** \nEducationUniversity                862232      45504  18.949  < 2e-16 ***\ngenderFemale:EducationUniversity  -324112      71196  -4.552 5.37e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1707000 on 10137 degrees of freedom\nMultiple R-squared:  0.04717,\tAdjusted R-squared:  0.04688 \nF-statistic: 167.3 on 3 and 10137 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThere are a few important things to notice about this regression result.  First, take a close look at the terms:\n\n- `genderFemale` this is the main effect for being a female.  You *might* immediately say that this is the impact of being a female - but this is *not true*.  Why?  Because female shows up in two places!  We have to be a little more careful - this is the effect of being a female in the base group (non-university) \n- `genderFemale:EducationUniversity` this is the interaction effect of being a female and having a university degree.  Basically, family with female (university degree) as main earner accumulates $143,396 + 324,112 = 467,508$ less wealth, compared with male counterpart.\n\nYou can see this interpretation in the regression model itself:\n\n$$\nW_i = \\beta_0 + \\beta_1 F_i + \\beta_2 D_i + \\beta_3 F_i \\times D_i + \\epsilon_i\n$$\n\nConsider:\n\n$$\n\\frac{\\Delta W_i}{\\Delta F_i} = \\beta_1 + \\beta_3 D_i\n$$\n\nThe marginal effect of being a female-lead household _changes_ depending on what the value of $D_i$ is!  For non-university degree (the level where $D_i = 0$) it's $\\beta_1$.  For university degree (the level where $D_i =1$), it's $\\beta_1 + \\beta_3$.  This is why, in an interaction model, it doesn't really make sense to talk about the \"effect of female\" - because there isn't a single, immutable effect.  It is different for different education degrees!\n\nYou can talk about the *average* effect, which is just $\\beta_1 + \\beta_3 \\bar{D_i}$ - but that's not really what people are asking about when they are discussing the gender effect, in general.\n\nThis is why it's very important to carefully think about a regression model with interaction terms - the model may seem simple to estimate, but the interpretation is more complex.\n\n### Interactions with Continuous Variables\n\nSo far, we have just looked at interacting qualitative variables - but you can interact any types of variables!\n\n- Qualitative-Qualitative\n- Qualitative-Quantitative\n- Quantitative-Quantitative\n\nThe format and syntax in R is similar, with some small exceptions to deal with certain combinations of variables.  However (again), you do need to be careful with interpretation.\n\nFor example, let's look at the interaction of income and sex on wealth.  In a regression equation, this would be expressed like:\n\n$$\nW_i = \\beta_0  + \\beta_1 Income_i + \\beta_2 F_i + \\beta_3 Income_i \\times F_i + \\epsilon_i\n$$\n\nNotice that, just like before:\n\n$$\n\\frac{\\partial W_i}{\\partial Income_i} = \\beta_1 + \\beta_3 F_i\n$$\n\nThere are two *different* \"slope\" coefficients; basically, male and female lead family can have a different return to wealth.  Let's see this in R:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregression2 <- lm(wealth ~ income_before_tax + gender + income_before_tax:gender, data = SFS_data)\n\nsummary(regression2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wealth ~ income_before_tax + gender + income_before_tax:gender, \n    data = SFS_data)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-16443704   -665085   -305096    219190  27934239 \n\nCoefficients:\n                                 Estimate Std. Error t value Pr(>|t|)    \n(Intercept)                     5.248e+05  2.489e+04  21.081   <2e-16 ***\nincome_before_tax               5.503e+00  1.382e-01  39.826   <2e-16 ***\ngenderFemale                   -3.433e+05  4.035e+04  -8.508   <2e-16 ***\nincome_before_tax:genderFemale  3.946e+00  3.045e-01  12.961   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1544000 on 10137 degrees of freedom\nMultiple R-squared:  0.2198,\tAdjusted R-squared:  0.2196 \nF-statistic: 951.9 on 3 and 10137 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAs we can see here, the female-lead households in our model accumulate about 3.946 dollars more in wealth per dollar of income earned than male-lead respondents. But female-lead households accumulate 343,300 dollars less than male counterparts. So the overall effects depend on average income before tax. \n\nThis addresses the common problem of estimating a regression model where you think the impact of a continuous variable might be different across the two groups.  One approach would be to run the model only for men, and only for women, and then compare - but this isn't a good idea.  Those regressions have a much smaller sample size, and if you have other controls in the model, you will \"throw away\" information.  The interaction method is much better.\n\n## Part 2: Non-linear Terms in Regression Models\n\nYou might have been puzzled by why these models were called \"linear\" regressions.  The reason is because they are linear in the *coefficients*: the dependent variable is expressed as a linear combination of the explanatory variables.\n\nThis implies that we can use the same methods (OLS) to estimate models that including linear combinations of _non-linear functions_ of the explanatory variables.  We have actually already seen an example of this: remember using `log` of a variable?  That's a non-linear function!\n\nAs we learned when considering `log`, the most important difference here is again regarding interpretations, not the actual estimation.\n\nIn R, there is one small complication: when you want to include mathematical expressions in a model formula, you need to \"isolate\" then using the `I()` function.  This is because many operations in R, like `+` or `*` have a special meaning in a regression model.\n\nFor example, let's consider a quadratic regression - that is, including both $Income_i$ and $Income_i^2$ (income squared) in our model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nregression3 <- lm(wealth ~ income_before_tax + I(income_before_tax^2), data = SFS_data)\n\nsummary(regression3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = wealth ~ income_before_tax + I(income_before_tax^2), \n    data = SFS_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-5477325  -633443  -223676   235217 27338412 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)             1.931e+05  2.167e+04   8.913   <2e-16 ***\nincome_before_tax       9.353e+00  1.806e-01  51.793   <2e-16 ***\nI(income_before_tax^2) -2.246e-06  1.001e-07 -22.445   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1520000 on 10138 degrees of freedom\nMultiple R-squared:  0.2444,\tAdjusted R-squared:  0.2442 \nF-statistic:  1639 on 2 and 10138 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAs you can see, we get regression results much like we would expect.  However, how do we interpret them?  The issue is that *income* enters into two places.  We need to carefully interpret this model, using our knowledge of the equation:\n\n$$\nW_i = \\beta_0 + \\beta_1 Income_i + \\beta_2 Income_i^2 + \\epsilon_i\n$$\n\n$$\n\\implies \\frac{\\partial W_i}{\\partial Income_i} = \\beta_1 + 2 \\beta_2 Income_i\n$$\n\nYou will notice something special about this; the marginal effect is *non-linear*. As $Income_i$ changes, the effect of income on $W_i$ changes. This is because we have estimated a quadratic relationship; the slope of a quadratic changes as the explanatory variable changes. That's what we're seeing here!\n\nThis makes these models relatively difficult to interpret, since the marginal effects change (often dramatically) as the explanatory variables change. You frequently need to carefully interpret the model and often (to get estimates) perform tests on *combinations* of coefficients, which can be done using things like the `car` package or the `lincom` function.  You can also compute this manually, using the formula for the sum of variances.\n\nFor example, let's test if the marginal effect of income is significant at $Income_i = \\overline{Income}_i$.  This is the most frequently reported version of this effects, often called the \"marginal effect at the means\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- mean(SFS_data$income_before_tax)\n\nlinearHypothesis(regression3, hypothesis.matrix = c(0, 1, 2*m), rhs=0) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLinear hypothesis test:\nincome_before_tax  + 191923.863524307 I(income_before_tax^2) = 0\n\nModel 1: restricted model\nModel 2: wealth ~ income_before_tax + I(income_before_tax^2)\n\n  Res.Df        RSS Df  Sum of Sq      F    Pr(>F)    \n1  10139 3.0023e+16                                   \n2  10138 2.3411e+16  1 6.6124e+15 2863.5 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nAs we can see, it is highly significant\n\n> **Think Deeper**: what is the vector ``c(0, 1, 2*m)`` doing in the above expression?\n\nLet's see exactly what those values are.  Recall the formula:\n\n$$\nV(aX + bY) = a^2 V(X) + b^2 V(Y) + 2abCov(X,Y)\n$$\n\nIn our situation, $X = Y = W_i$, so this is:\n\n$$\nV(\\beta_1 + 2\\bar{W_i}\\beta_2) = V(\\beta_1) + 4\\bar{W_i}^2V(\\beta_2) + 2(2\\bar{W_i})Cov(\\beta_1,\\beta_2)\n$$\n\nFortunately, these are all things we have from the regression and its variance-covariance matrix:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nv <- vcov(regression3)\ncoefs <- regression3$coefficients\nv\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                         (Intercept) income_before_tax I(income_before_tax^2)\n(Intercept)             4.695045e+08     -2.791901e+03           1.044877e-03\nincome_before_tax      -2.791901e+03      3.261026e-02          -1.349776e-08\nI(income_before_tax^2)  1.044877e-03     -1.349776e-08           1.001580e-14\n```\n\n\n:::\n\n```{.r .cell-code}\nvar <- v[2,2] + 4*(m^2)*v[3,3] + 4*m*v[3,2]\n\nvar\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.02779811\n```\n\n\n:::\n\n```{.r .cell-code}\ncoef <-  coefs[[2]] + 2*m*coefs[[3]]\n\nprint(\"Coefficent Combination and SD\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Coefficent Combination and SD\"\n```\n\n\n:::\n\n```{.r .cell-code}\nround(coef,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8.922\n```\n\n\n:::\n\n```{.r .cell-code}\nround(sqrt(var),3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.167\n```\n\n\n:::\n:::\n\n\nAs you can see, this gets fairly technical and is not something you will want to do without a very good reason.  In general, it's a better idea to rely on some of the packages written for R that handle this task for the (specific) model you are interested in evaluating.\n\n### Aside: Why Polynomial Terms?\n\nYou might be wondering why econometricians spend so much time talking about models that included polynomial terms, when those are (realistically) a very small set of the universe of possible functions of an explanatory variable (you already know why we talk about `log` so much!).  \n\nThe reason is actually approximation.  Consider the following _non-linear_ model:\n\n$$\nY_i = f(X_i) + e_i\n$$\n\nThis model is truly non-linear (and not just in terms of the parameters).  How can we estimate this model?  It's hard!  There are techniques to estimate complex models like this, but how far can we get with good-old OLS?  The answer is - provided that $f$ is \"smooth\" - pretty far.\n\nThink back to introductory calculus; you might remember a theorem called [Taylor's Theorem](https://en.wikipedia.org/wiki/Taylor%27s_theorem).  It says that a smoothly differentiable function can be arbitrarily well-approximated (about a point) by a polynomial expansion:\n\n$$\nf(x) = f(a) + f'(a)(x-a) + \\frac{f''(a)}{2!}(x-a)^2 + \\cdots + \\frac{f^{(k)}(a)}{k!}(x-a)^k + R_k(x)\n$$\n\nand the error term $R_k(x) \\to 0$ as $x \\to a$ and $k \\to \\infty$.\n\nLook closely at this expression.  Most of the terms (like $f'(a)$) are constants.  In fact, you can show that this can be written like:\n\n$$\nf(x) = \\beta_0 + \\beta_1 x + \\beta_2 x^2 + \\cdots + \\beta_k x^k + r\n$$\n\nPutting this into our expression above gives us the relationship:\n\n$$\nY_i = \\beta_0 + \\beta_1 X_i + \\beta_2 X_i^2 + \\cdots + \\beta_k X_i^k+ \\epsilon_i\n$$\n\nWhich is a linear regression model!  What this say is actually very important: linear regression models can be viewed as _approximations_ to nonlinear regressions, provided we have enough polynomial terms.  This is one complication: the error term is definitely not uncorrelated.  You can learn more about how to address this issue in other courses, but at the most the omitted variable bias is relatively small as $k \\to \\infty$.\n\n## Part 3: Exercises\n\nThis section has both written and coding exercises for you to test your knowledge about interactions and non-linear terms in regression models. The answers to the written exercises are on the last section of the notebook.\n\n### Questions\n\nConsider the following regression model:\n\n$$\n\\begin{equation}\nW_i = \\beta_1 + \\beta_2 F_i + \\beta_3 E_i + \\beta_4 P_i + \\beta_5 F_i\\times E_i + \\beta_6 F_i \\times P_i + \\epsilon_i\n\\end{equation}\n$$\n\nwhere\n\n- $W_i$ denotes wealth\n- $F_i$ is a dummy variable for the gender of main earner in the household ($F_i=1$ if female is the main earner)\n- $E_i$ is a factor variable for education \n- $P_i$ is a factor variable for province\n\n1. How should we interpret the coefficients $\\beta_5$ and $\\beta_6$? Why might these effects be important to estimate?\n\n<details>\n  <summary>Show/Hide Solution</summary>\n$\\beta_5$ is the difference of 'value-added' of education between female-lead household and male-lead household. $\\beta_6$ is the difference of province effects between female-lead household and male-lead household.\n\nThese interaction terms provide us with a simple way to describe and study how _combinations_ of our explanatory variables impact our model. With these interaction terms, we can understand how education and geography affect wealth of male-lead and female-lead households differently.\n</details>\n\nNow, let's estimate the model and interpret it concretely. (Please follow the order of variables in regression model): \n\n```\nreg1 <- gender, Education, province\n\nreg0 <- gender, education, province\n```\n\nWhat are your interaction variables? (remember to follow the same order)\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nreg0 <- lm(???, data = SFS_data)\n\nreg1 <- lm(???, data = SFS_data)\n\nsummary(reg0)\nsummary(reg1)\n\ntest_1()\ntest_2()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nreg0 <- lm(wealth ~ gender+education+province+gender:education+gender:province, data = SFS_data)\n\nreg1 <- lm(wealth ~ gender+Education+province+gender:Education+gender:province, data = SFS_data)\n\nsummary(reg0)\nsummary(reg1)\n\ntest_1()\ntest_2()\n```\n:::\n\n\n\n4. How do we interpret the coefficient estimate on `gender:Education`? What education level do female-lead households appear to be most discriminated in? How might we explain this intuitively?\n\n<details>\n  <summary>Show/Hide Solution</summary>\nIt means if the main earner is a female with a university degree, the household accumulates 302,008 dollars less wealth, than the male counterpart. University degree holders are most discriminated, because $|\\hat{\\beta_5}|$ is higher than $|\\hat{\\beta_2}|$.\n\nOne possible explanation is that males with university degree are more likely to become managers or other higher level employees than females. The inequality in incomes lead to the inequality in wealth.\n</details>\n\n5. How do you interpret the coefficient estimate on `genderFemale:provinceAlberta`? (Hint: Write out the average wealth equations for female, male in Alberta, and female in Alberta separately.)\n\n<details>\n  <summary>Show/Hide Solution</summary>\nAverage wealth for female-lead family: $E[wealth|female]=\\beta_{1}+\\beta_{2}=455918-87277$\n\nAverage wealth for male-lead family in Alberta: $E[wealth|male,Alberta]=\\beta_{1}+\\beta_{4,Alberta}=455918+502683$\n\nAverage wealth for female-lead family in Alberta: $E[wealth|female,Alberta]=\\beta_{1}+\\beta_{2}+\\beta_{4,Alberta}+\\beta_{6,Alberta}=455918-87277+502683-105798$\n\nThus $\\beta_{6,Alberta}$ is the difference of wealth when living in Alberta between female-lead household and male-lead household.\n</details>\n\nNow let's test whether the returns to education increase if people are entrepreneurs. `business` is a factor variable which suggests whether the household owns a business. Please add terms to the regression equation that allow us to run this test. Then, estimate this new model. We don't need `province` and `gender` variables in this exercise. For education, please use `education` variable. And we will continue to study wealth accumulated in households.\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nSFS_data$business <- relevel(SFS_data$business, ref = \"No\") # co not change; makes \"not a business owner\" the reference level for business\n\nreg2 <- lm(???, data = SFS_data)\n\nsummary(reg2)\ntest_3()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nSFS_data$business <- relevel(SFS_data$business, ref = \"No\")\n\nreg2 <- lm(wealth ~ education+business+education:business, data = SFS_data)\n\nsummary(reg2)\n\ntest_3()\n```\n:::\n\n\n7. Do returns to education increase when people are entrepreneurs? Explain why or why not with reference to the regression estimates.\n\n<details>\n  <summary>Show/Hide Solution</summary>\nFrom the above results of regression, owning a business increases 1.29 million dollars wealth on average. But the estimates of returns to education for being an entrepreneur or not is not significant. Thus we cannot conclude how education will affect the returns of entrepreneurs.\n</summary>\n\nA topic that many labour economists are concerned with, and one that we have discussed before, is the gender-wage gap. In this activity, we will construct a \"difference-in-difference\" regression to explore this gap using the `SFS_data2`.\n\nSuppose that we want to estimate the relationship between age, sex and wages. Within this relationship, we suspect that women earn less than men from the beginning of their working lives, ***but this gap does not change as workers age***.\n\nEstimate a regression model (with no additional control variables) that estimates this relationship using ``SFS_data2``. We will use `income_before_tax` variable. Order: list `gender` before `agegr`.\n\nTested Objects: `reg3A`\n\nLet's first simplify levels of age group using following codes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# some data cleaning - just run this!\nSFS_data <- \n        SFS_data %>%\n        mutate(agegr = case_when(\n              age == \"01\" ~ \"Under 30\", #under 20\n              age == \"02\" ~ \"Under 30\", #20-24\n              age == \"03\" ~ \"20s\", #25-29\n              age == \"04\" ~ \"30s\",\n            age == \"05\" ~ \"30s\",\n              age == \"06\" ~ \"40s\",\n              age == \"07\" ~ \"40s\",\n              age == \"08\" ~ \"50s\",\n              age == \"09\" ~ \"50s\",\n              age == \"10\" ~ \"60s\", #60-64\n              age == \"11\" ~ \"Above 65\", #65-69\n              age == \"12\" ~ \"Above 65\", #70-74\n              age == \"13\" ~ \"Above 75\", #75-79\n              age == \"14\" ~ \"Above 75\", #80 and above\n              )) %>%\n        mutate(agegr = as_factor(agegr))\n\nSFS_data$agegr <- relevel(SFS_data$agegr, ref = \"Under 30\") #Set \"Under 30\" as default factor level\n```\n:::\n\n\nLet's restrict the sample to main working groups. Just run the following line.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSFS_data2 <- subset(SFS_data, agegr == \"20s\" | agegr == \"30s\" | agegr == \"40s\" | agegr == \"50s\" | agegr == \"60s\" )\n```\n:::\n\n::: {.cell .question}\n\n```{.r .cell-code}\nSFS_data2$agegr <- relevel(SFS_data2$agegr, ref = \"20s\") # do not change; makes \"20s\" the reference level for age\n\nreg3A <- lm(???, data = SFS_data2)\n\nsummary(reg3A)\n\ntest_4() \n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nSFS_data2$agegr <- relevel(SFS_data2$agegr, ref = \"20s\")\n\nreg3A <- lm(income_before_tax ~ gender+agegr, data = SFS_data2)\n\nsummary(reg3A)\n\ntest_4()\n```\n:::\n\n\n\n9. What is the relationship between age and wages? Between sex and earnings? Is there a significant wage gap? Why might the regression above not give us the \"full picture\" of the sex wage gap?\n\n<details>\n  <summary>Show/Hide Solution</summary>\n Income before tax of households increase as main earners become older, and the peak arrives at their 50s. Female-lead households generally earn 34,852 dollars less than male-lead households. This regression does not provide us the \"full picture\" of sex wage gap, because the gender gap may change when people age.\n</details>\n\nNow, estimate the relationship between wages and age for male-lead households and female-lead households separately, then compare their returns to age. Let's continue to use `income_before_tax`\n\nTested objects: ``reg3M`` (for males), ``reg3F`` (for females).\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nreg3M <- lm(..., data = filter(SFS_data2, gender == \"Male\"))\nreg3F <- lm(..., data = filter(SFS_data2, gender == \"Female\"))\n\nsummary(reg3M)\nsummary(reg3F)\n\ntest_5()\ntest_6() \n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nreg3M <- lm(income_before_tax ~ agegr, data = filter(SFS_data2, gender == \"Male\"))\nreg3F <- lm(income_before_tax ~ agegr, data = filter(SFS_data2, gender == \"Female\"))\n\nsummary(reg3M)\nsummary(reg3F)\n\ntest_5()\ntest_6() \n```\n:::\n\n\n12. Do these regression estimates support your argument? Explain.\n\n<details>\n  <summary>Show/Hide Solution</summary>\nYes, these regression estimates support our hypothesis. First of all, for both male-lead and female-lead households, incomes increase as main earners become older, and the peak appears at their 50s. Second, there is a gender-wage gap in which female-lead households earn less. But the gap changes as age changes.\n</details>\n\nAdd one additional term to the multiple regression that accounts for the possibility that the sex wage gap can change as workers age. Please list gender before age.\n\nTested Objects: `reg4`.\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nreg4 <- lm(???, data = SFS_data2)\n\nsummary(reg4)\n\ntest_7() \n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nreg4 <- lm(income_before_tax ~ gender+agegr+gender:agegr, data = SFS_data2)\n\nsummary(reg4)\n\ntest_7() \n```\n:::\n\n\n14. According to the regression you estimated above, what is the nature of the sex wage gap?\n\n<details>\n  <summary>Show/Hide Solution</summary>\nGenerally speaking, the gender-income gap increases when workers become older. And the gender-income gap is widest at their 40s.\n</details>\n\nNow, suppose that a team of researchers is interested in the relationship between the price of a popular children's chocolate brand (let's call it \"Jumbo Chocolate Egg\") and its demand. The team conducts a series of surveys over a five-year period where they ask 200 households in a Vancouver neighborhood to report how many packs of Jumbo Chocolate Egg they bought in each quarter of the year. The company that produces Jumbo Chocolate Egg is interested in estimating the price elasticity of demand for their chocolate, so they changed the price of a pack of chocolate each quarter over this period. This survey is voluntary - the team went door-to-door to gather the data, and people could refuse to participate.\n\nAfter they compile a dataset from the survey responses, the team estimates this model:\n\n$$\nQ_i^2 = \\alpha_1 + \\alpha_2 ln(P_i) + \\alpha_3 H_i + \\epsilon_i\n$$\n\n$Q_i$ denotes the quantity of chocolate packs that household $i$ purchased in a given quarter of a given year. That is, each quarter for a given household is a separate observation. $P_i$ is the price of the pack of chocolate in the given quarter, and $H_i$ is the household size (in number of people). Note that $\\hat{\\alpha_2}$ is *supposed to be* the estimated elasticity of demand.\n\nYou join the team as a research advisor - in other words, you get to criticize their project and get paid doing so. Sounds great, but you have a lot of work ahead.\n\n15. Are there any omitted variables that the team should be worried about when estimating the model? Give 2 examples of such variables if so, and explain how each variable's omission could affect the estimated elasticity of demand.\n\n<details>\n  <summary>Show/Hide Solution</summary>\nThere are omitted variables, for example, age of kids and a dummy variable which represents Christmas and New Year. Omitting Christmas and New Year dummy will decrease $|\\hat{\\alpha}_{2}|$, because people buy more chocolates during Christmas, even if price of chocolate is high. Controlling Christmas dummy will recover the real elasticity of demand, which is a larger real $|\\alpha_{2}|$.\n\nWhen kids are young, they tend to consume more chocolates. Thus parts of the variations of consumption come from ages of kids. Without controlling for ages, the estimated elasticity is not reliable.\n</details>\n\n16. Is there anything wrong with the specification of the regression model? If so, explain how to correct it; if not, explain why the specification is correct.\n\n<details>\n  <summary>Show/Hide Solution</summary>\nThe dependent variable should be $ln(Q_{i})$ instead of $Q_{i}^{2}$.\n</details>\n\n17. Is there any potential for sample selection bias in this study? Explain by referencing specific aspects of the experiment. What effect might this bias have on the estimated elasticity of demand?\n\n<details>\n  <summary>Show/Hide Solution</summary>\nThere is sample selection bias, because people could refuse to participate. This means people who responded might be households who like Jumbo Chocolate Egg brand, and the estimated elasticity $|\\hat{\\alpha}_{2}|$ is smaller than the real elasticity among general population.\n</details>\n\n18. A member of your team writes in the research report that \"this estimated elasticity of demand tells us about the preferences of consumers around Canada.\" Do you have an issue with this statement? Why or why not?\n\n<details>\n  <summary>Show/Hide Solution</summary>\nThe result cannot represent the whole Canada, because participants were from a single neighborhood in Vancouver.\n</details>\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}