name: quarto-render
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.3
  - pip
  - jupyterlab
  - ipywidgets
  - nbformat
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - contextily
  - geopandas
  - spacy
  - nltk
  - networkx
  - python-louvain
  - tqdm
  - jupyter
  - notebook
  - ipykernel

  - pip:
    - tensorflow-cpu
    - torch --index-url https://download.pytorch.org/whl/cpu
    - torchvision --index-url https://download.pytorch.org/whl/cpu
    - transformers
    - datasets
    - kaggle
    - pyvis
    - datar
    - umap-learn
    - tf-keras