name: quarto-render
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # Core ML/Data Science packages with compatible versions
  - numpy>=1.26.0,<2.0.0  # Satisfies all requirements
  - pandas>=2.0.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  # Jupyter ecosystem
  - jupyterlab>=4.0.0
  - jupyter>=1.0.0
  - notebook>=7.0.0
  - ipykernel>=6.25.0
  - ipywidgets>=8.1.0
  - nbformat>=5.9.0
  
  # Geospatial packages (compatible versions)
  - geopandas>=0.14.0
  - contextily>=1.4.0
  
  # NLP and other packages
  - networkx>=3.1
  - tqdm>=4.65.0
  
  # Essential typing extensions (conda version to avoid conflicts)
  - typing_extensions>=4.12.0
  
  - pip:
    # ML frameworks
    - torch==2.1.0 --index-url https://download.pytorch.org/whl/cpu
    - torchvision==0.16.0 --index-url https://download.pytorch.org/whl/cpu
    - tensorflow==2.15.0
    - transformers==4.37.0  # Compatible with both TF and PyTorch
    - datasets>=2.16.0
    
    # NLP packages that need specific versions
    - spacy>=3.7.0
    - nltk>=3.8.0
    - python-louvain>=0.16
    
    # Other pip-only packages
    - kaggle>=1.5.0
    - pyvis>=0.3.2
    - datar>=0.15.0
    - umap-learn>=0.5.4
