name: quarto-render
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - tensorflow==2.13.0
  - keras=2.13.1           
  - pip
  - jupyterlab
  - ipywidgets
  - nbformat
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - contextily
  - geopandas
  - spacy
  - nltk
  - networkx
  - python-louvain
  - tqdm
  - jupyter
  - notebook
  - ipykernel
  - pip:
      - torch==2.0.0 --index-url https://download.pytorch.org/whl/cpu
      - torchvision==0.15.1 --index-url https://download.pytorch.org/whl/cpu
      - transformers==4.33.2
      - datasets
      - tf-keras==2.13.0
      - kaggle
      - pyvis
      - datar
      - umap-learn
