project:
  type: website
  preview:
    port: 4200
    browser: true
  resources:
  - pages/index/placeholder_images
  - media/praxis-animation-1000x233-revised.gif
  - media/praxis-animation-1000x233-white.gif
  render: 
  - "media/*"
  - "files/*"
  - "docs/image_analysis/image_analysis_stub.qmd"
  - "*.qmd"
  - "*.ipynb"
  - "*.r"
  - "!in_progress/*"
  - "!docs/SOCI-415/soci_415_network_analysis.qmd"  #ignore the file with .html
  - "!docs/SOCI-415/kinmatrix.qmd"
  - "!docs/SOCI-415/cbdb_dataset.qmd" 
  - "!docs/ECON-227/llm_distributions.qmd" 
  - "!docs/hist_workshop/text_embeddings_workshop.qmd" 
  - "!docs/intro_to_cnns/intro_to_cnn.qmd"
  - "!docs/intro_to_convolutions/intro_to_convolution.qmd"
  - "!docs/intro_to_deep_learning/intro_to_fundamental_ML.qmd"
  - "!docs/AMNE-376/amne_376_image_embedding.qmd"
  - "!docs/SOCI-280/soci_280_bert.qmd"
  - "!docs/OCR/ocr_notebook.qmd"
  - "!docs/image_analysis/image_analysis.qmd"
  - "!docs/CTree_CEA/political_economy.qmd"
  - "!docs/CTree_CEA/llm_distributions.qmd"
  - "!docs/CTree_CEA/ctree_cea_2026/praxis_presentation.qmd"
  - "!docs/1_Getting_Started/getting_started_intro_to_data/getting_started_intro_to_data2.qmd"
  - "!docs/1_Getting_Started/getting_started_intro_to_jupyter/getting_started_intro_to_jupyter.qmd"
  - "!docs/1_Getting_Started/getting_started_intro_to_python/getting_started_intro_to_python.qmd"
  - "!docs/1_Getting_Started/getting_started_intro_to_r/getting_started_intro_to_r.qmd"
  - "!docs/2_Beginner/beginner_central_tendency/beginner_central_tendency.qmd"
  - "!docs/2_Beginner/beginner_confidence_intervals/beginner_confidence_intervals.qmd"
  - "!docs/2_Beginner/beginner_dispersion_and_dependence/beginner_dispersion_and_dependence.qmd"
  - "!docs/2_Beginner/beginner_distributions/beginner_distributions.qmd"
  - "!docs/2_Beginner/beginner_hypothesis_testing/beginner_hypothesis_testing.qmd"
  - "!docs/2_Beginner/beginner_intro_to_central_tendency/beginner_intro_to_central_tendency.qmd"
  - "!docs/2_Beginner/beginner_intro_to_data_visualization1/beginner_intro_to_data_visualization1.qmd"
  - "!docs/2_Beginner/beginner_intro_to_data_visualization2/beginner_intro_to_data_visualization2.qmd"
  - "!docs/2_Beginner/beginner_intro_to_statistics2/beginner_intro_to_statistics2.qmd"
  - "!docs/2_Beginner/beginner_sampling_distributions/beginner_sampling_distributions.qmd"
  - "!docs/3_Intermediate/intermediate_interactions_and_nonlinear_terms/intermediate_interactions_and_nonlinear_terms.qmd"
  - "!docs/3_Intermediate/intermediate_intro_to_regression/intermediate_intro_to_regression.qmd"
  - "!docs/3_Intermediate/intermediate_multiple_regression/intermediate_multiple_regression.qmd"
  - "!docs/3_Intermediate/intermediate_summary_statistics/GTsummary.qmd"
  - "!docs/4_Advanced/advanced_geospatial/advanced_geospatial.qmd"
  - "!docs/4_Advanced/advanced_geospatial/advanced_geospatial_2.qmd"
  - "!docs/4_Advanced/advanced_instrumental_variables/advanced_instrumental_variables1.qmd"
  - "!docs/4_Advanced/advanced_instrumental_variables/advanced_instrumental_variables2.qmd"
  - "!docs/4_Advanced/advanced_linear_differencing/advanced_linear_differencing.qmd"
  - "!docs/4_Advanced/advanced_network_analysis/intro_to_python_network_analysis.qmd"
  - "!docs/4_Advanced/advanced_network_analysis/network_analysis_notebook.qmd"
  - "!docs/4_Advanced/advanced_network_analysis/network_analysis_notebook_II.qmd"
  - "!docs/4_Advanced/advanced_synthetic_control/advanced_synthetic_control.qmd"
  - "!docs/4_Advanced/advanced_vocalization/advanced_vocalization_draft.qmd"
  - "!docs/4_Advanced/advanced_word_embeddings/advanced_word_embeddings_python_version.qmd"
  - "!docs/5_Research/econ490-pystata/01_Setting_Up_PyStata.qmd"
  - "!docs/5_Research/econ490-pystata/02_Working_Dofiles.qmd"
  - "!docs/5_Research/econ490-pystata/09_Stata_Graphs.qmd"
  - "!docs/5_Research/econ490-pystata/11_Linear_Reg.qmd"
  - "!docs/5_Research/econ490-pystata/14_PostReg.qmd"
  - "!docs/5_Research/econ490-pystata/03_Stata_Essentials.qmd"
  - "!docs/5_Research/econ490-pystata/04_Locals_and_Globals.qmd"
  - "!docs/5_Research/econ490-pystata/05_Opening_Data_Sets.qmd"
  - "!docs/5_Research/econ490-pystata/06_Creating_Variables.qmd"
  - "!docs/5_Research/econ490-pystata/07_Within_Group.qmd"
  - "!docs/5_Research/econ490-pystata/08_Merge_Append.qmd"
  - "!docs/5_Research/econ490-pystata/10_Combining_Graphs.qmd"
  - "!docs/5_Research/econ490-pystata/12_Exporting_Output.qmd"
  - "!docs/5_Research/econ490-pystata/13_Dummy.qmd"
  - "!docs/5_Research/econ490-pystata/15_Panel_Data.qmd"
  - "!docs/5_Research/econ490-pystata/16_Diff_in_Diff.qmd"
  - "!docs/5_Research/econ490-pystata/17_IV.qmd"
  - "!docs/5_Research/econ490-pystata/18_Wf_Guide2.qmd"
  - "!docs/5_Research/econ490-r/01_Setting_Up.qmd"
  - "!docs/5_Research/econ490-r/02_Working_Rscripts.qmd"
  - "!docs/5_Research/econ490-r/03_R_Essentials.qmd"
  - "!docs/5_Research/econ490-r/04_Opening_Data_Sets.qmd"
  - "!docs/5_Research/econ490-r/05_Creating_Variables.qmd"
  - "!docs/5_Research/econ490-r/07_Combining_Datasets.qmd"
  - "!docs/5_Research/econ490-r/08_ggplot_graphs.qmd"
  - "!docs/5_Research/econ490-r/09_Combining_Graphs.qmd"
  - "!docs/5_Research/econ490-r/10_Linear_Reg.qmd"
  - "!docs/5_Research/econ490-r/11_Exporting_Output.qmd"
  - "!docs/5_Research/econ490-r/12_Dummy.qmd"
  - "!docs/5_Research/econ490-r/13_PostReg.qmd"
  - "!docs/5_Research/econ490-r/14_Panel_Data.qmd"
  - "!docs/5_Research/econ490-r/15_Diff_in_Diff.qmd"
  - "!docs/5_Research/econ490-r/16_IV.qmd"
  - "!docs/5_Research/econ490-stata/01_Setting_Up.qmd"
  - "!docs/5_Research/econ490-stata/02_Working_Dofiles.qmd"
  - "!docs/5_Research/econ490-stata/03_Stata_Essentials.qmd"
  - "!docs/5_Research/econ490-stata/04_Locals_and_Globals.qmd"
  - "!docs/5_Research/econ490-stata/05_Opening_Data_Sets.qmd"
  - "!docs/5_Research/econ490-stata/06_Creating_Variables.qmd"
  - "!docs/5_Research/econ490-stata/07_Within_Group.qmd"
  - "!docs/5_Research/econ490-stata/08_Merge_Append.qmd"
  - "!docs/5_Research/econ490-stata/09_Stata_Graphs.qmd"
  - "!docs/5_Research/econ490-stata/10_Combining_Graphs.qmd"
  - "!docs/5_Research/econ490-stata/11_Linear_Reg.qmd"
  - "!docs/5_Research/econ490-stata/12_Exporting_Output.qmd"
  - "!docs/5_Research/econ490-stata/13_Dummy.qmd"
  - "!docs/5_Research/econ490-stata/14_PostReg.qmd"
  - "!docs/5_Research/econ490-stata/15_Panel_Data.qmd"
  - "!docs/5_Research/econ490-stata/16_Diff_in_Diff.qmd"
  - "!docs/5_Research/econ490-stata/17_IV.qmd"
  - "!docs/5_Research/econ490-stata/18_Wf_Guide2.qmd"
  - "!docs/6_Projects/projects_example_project_econ325/Projects_Example_Project_ECON325.qmd"
  - "!docs/6_Projects/projects_example_project_econ326/Projects_Example_Project_ECON326.qmd"
  

execute:
    eval: false
    keep-ipynb: false
    cache: false

website:
  title: "Praxis"
  search: true
  page-navigation: true
  reader-mode: false
  repo-url: https://github.com/ubcecon/praxis-ubc
  repo-actions: [issue]
  favicon: media/praxis-badge.png 
  page-footer: 
    left: 
    - text: <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'><img alt='Creative Commons License' style='border-width:0' src='https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png' /></a>.  <a rel='license' href='https://comet.arts.ubc.ca/pages/copyright.html'>See details.</a>
    right: 
      - text: 'The Praxis Project and UBC are located on the traditional, ancestral and unceded territory of the xʷməθkʷəy̓əm (Musqueam) and Sḵwx̱wú7mesh (Squamish) peoples.' 
  navbar:
    background: primary
    search: false
    logo: media/praxis-badge-white.png
    left:
      - text: "Get Started"
        menu:
          - text: Quickstart Guide
            file: pages/quickstart.qmd
      - text: "Courses"
        menu:
          #- text: "HIST-414"
          #  file: pages/index/index_HIST-414.qmd 
          - text: "AMNE-376"
            file: pages/index/index_AMNE-376.qmd 
          - text: "SOCI-415"
            file: pages/index/index_SOCI415.qmd 
          - text: "SOCI-280"
            file: pages/index/index_SOCI280.qmd 
          - text: "ECON-227"
            file: pages/index/index_ECON227.qmd
          - text: "Making Sense of Economic Data (ECON 226/227)"
            file: pages/index/index_226.qmd
          - text: "Econometrics I (ECON 325)"
            file: pages/index/index_325.qmd
          - text: "Econometrics II (ECON 326)"
            file: pages/index/index_326.qmd
          - text: "Statistics in Geography (GEOG 374)"
            file: pages/index/index_geog.qmd
          - text: "---"
          - text: "Browse All"
            file: pages/index/all.qmd
      - text: "Learn By Skill Level"
        menu:
        - text: "Getting Started"
          file: pages/index/index_getting_started.qmd
        - text: "Beginner"
          file: pages/index/index_beginner.qmd
        - text: "Intermediate - Econometrics"
          file: pages/index/index_intermediate.qmd
        - text: "Intermediate - Geospatial"
          file: pages/index/index_geog.qmd
        - text: "Advanced"
          file: pages/index/index_advanced.qmd
        - text: "---"
        - text: "Browse All"
          file: pages/index/all_learnbyskill.qmd
      - text: "Learn to Research"
        menu: 
          - text: "Learn How to Do a Project"
            file: pages/index/index_research.qmd
      - text: "All Topics"
        file: pages/index/all.qmd
      - text: "Teach with Praxis"
        menu:
          - text: "Learn how to teach with Praxis" 
            href: pages/teaching_with_praxis.qmd 
          #- text: "Using Praxis in the Classroom"
          #  href: pages/using_comet.qmd 

    right:
    - icon: play
      text: Launch Praxis
      menu:
        - text: Launch on JupyterOpen (with Data)
          href: "https://open.jupyter.ubc.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fpraxis-ubc&urlpath=lab%2Ftree%2Fpraxis-ubc%2F&branch=praxis-notebooks"
          icon: cloud-check
        - text: Launch on JupyterOpen (lite)
          href: "https://open.jupyter.ubc.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fpraxis-ubc&urlpath=lab%2Ftree%2Fpraxis-ubc%2F&branch=praxis-notebooks"
          icon: cloud-check
        - text: Launch on Syzygy
          href: "https://ubc.syzygy.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fpraxis-ubc&urlpath=lab%2Ftree%2Fpraxis-ubc%2F&branch=praxis-notebooks"
          icon: gear
        - text: Launch on Colab
          href: "https://colab.research.google.com/github/ubcecon/praxis-ubc/blob/praxis-notebooks/"
          icon: google
        - text: Launch Locally
          href: "https://github.com/ubcecon/praxis-ubc/archive/refs/heads/praxis-notebooks.zip"
          icon: cloud-download
        - text: "---"
        - text: Github Repository
          href: "https://github.com/ubcecon/praxis-ubc"      
      
    - text: " | "
      href: "#"
    - icon: github
      href: https://github.com/ubcecon/praxis-ubc
      aria-label: GitHub
      target: _blank
    - text: "About"
      menu:
      - pages/team.qmd
      - pages/copyright.qmd


filters:
  - answers

format:
  html:
    theme:
      light:
        - default
        - comet_theme.scss
      dark:
        - default
        - comet_theme_dark.scss
    html-math-method: mathjax
    css: styles.css
    toc: true
    anchor-sections: true
    email-obfuscation: javascript
    page-layout: full
    link-external-newwindow: true
    lang: en-GB
    include-in-header: metadata.html
