project:
  type: website
  preview:
    port: 4200
    browser: true
  render: 
  - "media/*"
  - "files/*"
  - "*.qmd"
  - "*.ipynb"
  - "*.r"
  - "!in_progress/*"

execute:
    eval: false
    keep-ipynb: false
    cache: false

website:
  title: "Praxis"
  search: true
  page-navigation: true
  reader-mode: false
  repo-url: https://github.com/ubcecon/praxis-ubc
  #repo-actions: [edit, issue]
  repo-actions: [issue]
  favicon: media/praxis-badge.png 
  page-footer: 
    left: 
    - text: <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'><img alt='Creative Commons License' style='border-width:0' src='https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png' /></a>.  <a rel='license' href='https://comet.arts.ubc.ca/pages/copyright.html'>See details.</a>
    right: 
      - text: 'The prAxIs Project and UBC are located on the traditional, ancestral and unceded territory of the xʷməθkʷəy̓əm (Musqueam) and Sḵwx̱wú7mesh (Squamish) peoples.' 
  navbar:
    background: primary
    search: false
    logo: media/praxis-badge-white.png
    #tools: 
    #  - icon: github
    #    href: https://github.com/ubcecon/comet-project
    left:
      - text: "Get Started/Placeholder_1"
        menu:
        - text: Quickstart Guide
          file: pages/quickstart.qmd #Placeholder .qmd here to render
      - text: "Courses"
        menu:
        - text: "HIST-414"
          file: pages/index/index_HIST-414.qmd 
        - text: "AMNE-376"
          file: pages/index/index_AMNE-376.qmd 
        - text: "AMNE-170"
          file: pages/index/index_AMNE-170.qmd 
        - text: "SOCI-415"
          file: pages/index/index_SOCI415.qmd 
        - text: "SOCI-217"
          file: pages/index/index_SOCI217.qmd 
        - text: "SOCI-280"
          file: pages/index/index_SOCI280.qmd 
        - text: "ECON-227"
          file: pages/index/index_ECON227.qmd 
        - text: "---"
        - text: "Browse All"
          file: pages/index/all.qmd
      - text: "Topics"
        menu:
        - text: "CNN"
          file: pages/index/index_CNN.qmd 
        - text: "Convolution"
          file: pages/index/index_convolution.qmd   
      - text: "Teach With prAxIs"
        menu: #Maybe update links here (Feedback)
        - text: "Learn how to teach with prAxIs" 
          href: pages/teaching_with_comet.qmd 
        - text: "Using prAxIs in the Classroom"
          href: pages/using_comet.qmd 

    right: #updates
      - icon: play
        text: Launch prAxIs
        menu:
          - text: Launch on JupyterOpen (with Data)
            href: "https://open.jupyter.ubc.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fcomet-notebooks&urlpath=lab%2Ftree%2Fcomet-notebooks%2F&branch=main"
            icon: cloud-check
          - text: Launch on JupyterOpen (lite)
            href: "https://open.jupyter.ubc.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fcomet-project&urlpath=lab%2Ftree%2Fcomet-project%2F&branch=main"
            icon: cloud-check
          - text: Launch on Syzygy
            href: "https://ubc.syzygy.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fcomet-project&urlpath=lab%2Ftree%2Fcomet-project%2F&branch=main"
            icon: gear
          - text: Launch on Colab
            href: "https://colab.research.google.com/github/ubcecon/comet-notebooks/blob/main/"
            icon: google
          - text: Launch Locally
            href: "https://github.com/ubcecon/comet-notebooks/archive/refs/heads/main.zip"
            icon: cloud-download
          - text: "---"
          - text: Project Datasets
            href: https://github.com/ubcecon/comet-open/archive/refs/heads/datasets.zip
            icon: clipboard-data
          - #text: Github Repository
            #href: https://github.com/ubcecon/praxis-ubc
      - text: " | "
        href: "#"
      - text: "About"
        menu:
         - pages/team.qmd 
         - pages/copyright.qmd 

sidebar:
  - title: "Learn by Class"
    style: docked
    collapse-level: 1
    contents:
      - text: "<h4>Learn by Class</h4>"
      - text: ---
      - section: 
          file: pages/index/index_HIST-414.qmd
          contents:
            - text: "HIST-414 Notebook 1"
              file: docs/HIST-414/Hist414-notebook-1.qmd
            - text: "HIST-414 Notebook 2"
              file: docs/HIST-414/Hist414-notebook-2.qmd
            - text: "HIST-414 Notebook 3"
              file: docs/HIST-414/Hist414-notebook-3.qmd

      - text: ---

      - section:
          file: pages/index/index_AMNE-170.qmd
          contents:
            - text: "AMNE-170 Notebook 1"
              file: docs/AMNE-170/AMNE170-notebook-1.qmd
            - text: "AMNE-170 Notebook 1"
              file: docs/AMNE-170/AMNE170-notebook-2.qmd
            - text: "AMNE-170 Notebook 1"
              file: docs/AMNE-170/AMNE170-notebook-3.qmd

      - text: ---

      - section: 
          file: pages/index/index_AMNE-376.qmd
          contents:
            - text: "AMNE-376 Notebook 1"
              file: docs/AMNE-376/AMNE376-notebook-1.qmd
            - text: "AMNE-376 Notebook 2"
              file: docs/AMNE-376/AMNE376-notebook-2.qmd
            - text: "AMNE-376 Notebook 3"
              file: docs/AMNE-376/AMNE376-notebook-3.qmd

      - text: ---

      - section:
          file: pages/index/index_SOCI-400.qmd
          contents:
            - text: "SOCI-400 Notebook 1"
              file: docs/SOCI-400/SOCI400-notebook-1.qmd
            - text: "SOCI-400 Notebook 1"
              file: docs/SOCI-400/SOCI400-notebook-2.qmd
            - text: "SOCI-400 Notebook 1"
              file: docs/SOCI-400/SOCI400-notebook-3.qmd

      - text: ---


filters:
  - answers

format:
  html:
    theme:
      light: 
        - sandstone
        - comet_theme.scss
    css: styles.css
    toc: true
    anchor-sections: true
    email-obfuscation: javascript
    page-layout: full
    link-external-newwindow: true
    lang: en-GB
    include-in-header: metadata.html
