project:
  type: website
  preview:
    port: 4200
    browser: true
  resources:
  - pages/index/placeholder_images
  - media/praxis-animation-1000x233-revised.gif
  - media/praxis-animation-1000x233-white.gif
  render: 
  - "media/*"
  - "files/*"
  - "*.qmd"
  - "*.ipynb"
  - "*.r"
  - "!in_progress/*"
  - "!docs/CTree_CEA/ctree_cea_2026/praxis_presentation.qmd"
  - "!docs/setup_rise.ipynb"  # one-time RISE setup notebook, distributed as-is (not a web page)
  

execute:
    eval: false
    keep-ipynb: false
    cache: false
    freeze: true

website:
  title: "Praxis"
  search: true
  page-navigation: true
  reader-mode: false
  repo-url: https://github.com/ubcecon/praxis-ubc
  repo-actions: [issue]
  favicon: media/praxis-badge.png 
  page-footer: 
    left: 
    - text: <a rel='license' href='http://creativecommons.org/licenses/by-nc-sa/4.0/'><img alt='Creative Commons License' style='border-width:0' src='https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png' /></a>.  <a rel='license' href='https://ubcecon.github.io/comet-open/pages/copyright.html'>See details.</a>
    right: 
      - text: 'The Praxis Project and UBC are located on the traditional, ancestral and unceded territory of the xʷməθkʷəy̓əm (Musqueam) and Sḵwx̱wú7mesh (Squamish) peoples.' 
  navbar:
    background: primary
    search: false
    logo: media/praxis-badge-white.png
    left:
      - text: "Get Started"
        menu:
          - text: Quickstart Guide
            file: pages/quickstart.qmd
      - text: "Courses"
        menu:
          #- text: "HIST-414"
          #  file: pages/index/index_HIST-414.qmd 
          - text: "AMNE-376"
            file: pages/index/index_AMNE-376.qmd 
          - text: "SOCI-415"
            file: pages/index/index_SOCI415.qmd 
          - text: "SOCI-280"
            file: pages/index/index_SOCI280.qmd 
          - text: "ECON-227"
            file: pages/index/index_ECON227.qmd
          - text: "Causal Machine Learning"
            file: pages/index/index_Causal_ML.qmd
          - text: "Game Theory"
            file: pages/index/index_Game_Theory.qmd
          - text: "---"
          - text: "Browse All"
            file: pages/index/all.qmd
      - text: "All Topics"
        file: pages/index/all.qmd
      - text: "Teach with Praxis"
        menu:
          - text: "Learn how to teach with Praxis" 
            href: pages/teaching_with_praxis.qmd 
          #- text: "Using Praxis in the Classroom"
          #  href: pages/using_comet.qmd 

    right:
    - icon: play
      text: Launch Praxis
      menu:
        - text: Launch on JupyterOpen (with Data)
          href: "https://open.jupyter.ubc.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fpraxis-ubc&urlpath=lab%2Ftree%2Fpraxis-ubc%2F&branch=praxis-notebooks"
          icon: cloud-check
        - text: Launch on JupyterOpen (lite)
          href: "https://open.jupyter.ubc.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fpraxis-ubc&urlpath=lab%2Ftree%2Fpraxis-ubc%2F&branch=praxis-notebooks"
          icon: cloud-check
        - text: Launch on Syzygy
          href: "https://ubc.syzygy.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fpraxis-ubc&urlpath=lab%2Ftree%2Fpraxis-ubc%2F&branch=praxis-notebooks"
          icon: gear
        - text: Launch on Colab
          href: "https://colab.research.google.com/github/ubcecon/praxis-ubc/blob/praxis-notebooks/"
          icon: google
        - text: Launch Locally
          href: "https://github.com/ubcecon/praxis-ubc/archive/refs/heads/praxis-notebooks.zip"
          icon: cloud-download
        - text: "---"
        - text: Github Repository
          href: "https://github.com/ubcecon/praxis-ubc"      
      
    - text: " | "
      href: "#"
    - icon: github
      href: https://github.com/ubcecon/praxis-ubc
      aria-label: GitHub
      target: _blank
    - text: "About"
      menu:
      - pages/team.qmd
      - pages/copyright.qmd


filters:
  - answers

format:
  html:
    theme:
      light:
        - default
        - comet_theme.scss
      dark:
        - default
        - comet_theme_dark.scss
    highlight-style:
      light: comet_theme.json
      dark: comet_theme_dark.json
    html-math-method: mathjax
    css: styles.css
    toc: true
    anchor-sections: true
    email-obfuscation: javascript
    page-layout: full
    link-external-newwindow: true
    lang: en-GB
    include-in-header: metadata.html
    include-after-body: scroll_to_top.html
