---
title: SOCI 415 Network Analysis - Lesson Plan
date: '2025-08-19'
description: Lesson Plan for SOCI-415
categories:
  - Python
  - network analysis
format:
  html: default
  ipynb:
    jupyter:
      kernelspec:
        display_name: Python
        language: python3
        name: python3
---

# SOCI 415: Suggested Lesson Plan

## Pre Readings

**Before First Lecture:**

* [Power in Networks: The Medici](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3673940) Only Section’s 1,2, and 7
* [KINMATRIX Data](https://www.demographic-research.org/volumes/vol51/25/51-25.pdf) Only Page 789 - 793: Intro and Methods

**Before Second Lecture:**

* [The China Biographical Database User Guide](https://projects.iq.harvard.edu/sites/projects.iq.harvard.edu/files/cbdb/files/cbdb_users_guide.pdf) Only Page 1-2

## Learning Objectives

By the end of this lesson, students will:

1. Be familiar with Network Analysis Terminology such as: nodes, edges, degree, density, centrality and clustering and will have seen them used in a real research context. 
2. Have some insight into how to create networks and utilize them to answer research questions
3. Explore real life examples with the KINMATRIX and CBDB Dataset for family analysis
4. Have multiple discussions about the data, network analysis and limitations of the techniques used. 

## Materials and Technical Requirements

1. Access to a Google drive with a .zip file (can be a link on Canvas)
2. Device with internet access (laptop preferred)
3. No previous coding experience required (familiarity with Python is an asset)
4. No previous network analysis or high-level math experience required

## Pre-lesson Requirements:

* **Instructors should**: Test if the .html files from the .zip file render correctly. Once it is tested they render correctly the instructor should read over and be familiar with the context to answer the student's questions. 
* **Students should:** Complete the pre-readings for each lecture and come with a laptop to class. 

## Brief Lesson Structure

**Introductory Notebook:**

* Intro for what is network analysis and key terminology
* How to create simple and random graphs in Python with NetworkX
* Degree, Density and Weights
* Adjacency Matrices
* Measures of Centrality (Network Distance and Eccentricity, Degree Centrality, Closeness Centrality, Betweenness Centrality) 

**KINMATRIX Notebook:**

* Intro to the KINMATRIX Dataset and broad patterns across countries
* Density by Age and Gender Across Countries 
* Colored Family Networks and Visualization of Gender
* Health and Education Across Countries
* Family size vs Political Allegiance in USA and Poland 
* Employment and Education in Poland
* Parental Separation
* Gender and Sexuality Across Countries and Regions

**The China Biographical Database Notebook:**

* Intro
* Louvain Algorithm and Community Clustering
* Degree Centrality and Important Family members (Who they were)
* Did women act more as bridges and who these key women were
* Networks over time between dynasties 

## Discussions

**KINMATRIX Discussions:**

* Discussion on Density by Age and Gender Across the Countries
* Discussion on Family Structure
* Discussion on Family size and Political Allegiance 
* Discussion on Parental Separation Across the Countries
* Hands on Section where students draw their own ego-networks of their families (Maybe website we will see) 

**The China Biographical Database Discussions:**

* Discussion on Louvain and Visualizations
* Discussion on Centrality 