{
  "hash": "2822eb141b67729e5b9e28197bb84c3b",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Trees, Forests, and Boosting\"\nauthor: Alex Ronczewski\ndate: 2026-06-21\nimage: /media/stream_icons/causal-ml-3.png\ndescription: \"The third notebook in the Causal ML stream. We show a different way to be flexible: decision trees, which split the data into boxes and predict the local average. A single deep tree overfits, so we average many of them into a random forest, and we close with boosting. Trees and forests are flexible nonparametric predictors, and like everything in this stream so far, they do not identify causal effects.\"\ncategories:\n  - Python\n  - machine learning\n  - decision trees\n  - random forests\n  - boosting\n  - nonparametric\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html: default\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: Python\n        language: python3\n        name: python3\n---\n\n## Outline\n\n### Prerequisites\n\n- Notebook 2 of this stream: ridge and lasso, variable selection, and the train/test/cross-validate recipe\n- Comfort with `pandas` and basic Python at the COMET-intermediate level\n- No prior knowledge of trees is assumed; regression trees, forests, and boosting are all introduced here\n\n### Learning Outcomes\n\nBy the end of this notebook you will be able to:\n\n1. Describe what a **regression tree** does: split the feature space into boxes and predict the average outcome in each box.\n2. Fit a single decision tree and **read its splits** off a diagram.\n3. Explain why a deep tree **overfits**, and identify `max_depth` as its flexibility hyperparameter.\n4. Choose the depth of a tree by cross-validation, reusing the recipe from Notebook 1.\n5. Explain **bagging** and fit a **random forest**, and say why averaging many trees lowers variance.\n6. Read a table of **feature importances** as a predictive diagnostic.\n7. Describe in one sentence how **boosting** differs from bagging.\n8. Explain why a random forest's predictions and importances are **not** causal effects.\n\n::: {#7860909f .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\nfrom sklearn.tree import DecisionTreeRegressor, plot_tree\nfrom sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor\nfrom sklearn.neighbors import KNeighborsRegressor\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.pipeline import make_pipeline\nfrom sklearn.model_selection import train_test_split, cross_val_score, KFold\nfrom sklearn.metrics import mean_squared_error\n\nRANDOM_STATE = 42  # fix randomness so splits, folds, and forests are reproducible\n```\n:::\n\n\n## 1. A Third way to be Flexible\n\nSo far this stream has shown flexibility in two different ways. In Notebook 1, k-nearest-neighbours was flexible because it averaged whatever points sat nearby, and the parameter $k$ set how many. In Notebook 2, linear models were flexible because we could pour in covariates, and the penalty $\\lambda$ kept their coefficients in check.\n\nThis notebook introduces a third kind of flexibility. A **decision tree** does not measure distance and does not fit a line. It carves the feature space into rectangular boxes by asking a sequence of yes-or-no questions about one feature at a time, and to predict a new case it returns the average outcome of the training points that landed in the same box.\n\nThis will be very new to most of you, so we'll build up to this, starting with a single tree that we can draw and read. Then we'll watch it overfit, just as $k=1$ KNN overfit in Notebook 1 and OLS overfit with too many controls in Notebook 2. Then we fix the overfitting by averaging many trees into a **random forest**, and we close with a brief look at **boosting**, a second way to combine trees. Throughout, we're still predicting, and the causal turn comes in Notebook 4.\n\n### 1.1 The data: back to the 401(k) households\n\nWe return to the **401(k)** data from Notebook 1: one row per U.S. household, the net financial assets `net_tfa` (in thousands of dollars) as the target, and ten features of the household, including `e401`, whether the household is eligible for a 401(k). We re-use this data as we have a test MSE of about 2654 which we will try and beat, and we can ask the question that matters when choosing between methods: which one predicts new households best.\n\n::: {#2519febd .cell execution_count=2}\n``` {.python .cell-code}\nsavings = pd.read_csv(\"datasets/Pension401k.csv\")\n\nfeatures = [\"age\", \"inc\", \"educ\", \"fsize\", \"marr\",\n            \"twoearn\", \"db\", \"pira\", \"hown\", \"e401\"]\ntarget = \"net_tfa\"\n\ny = savings[target].to_numpy()\nX = savings[features]\n\nX_train, X_test, y_train, y_test = train_test_split(\n    X, y, test_size=0.3, random_state=RANDOM_STATE)\n\nprint(\"Training households:\", len(X_train))\nprint(\"Test households    :\", len(X_test))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTraining households: 6940\nTest households    : 2975\n```\n:::\n:::\n\n\nOne thing we do **not** have to do this time is scale the features. A tree split is a question like \"is income above 65?\", and the answer does not change if we measure income in dollars or in thousands of dollars: the ordering of the households is all that matters, not the units. This is different from Notebook 1, where KNN measured distance and so needed every feature on a common scale, and from Notebook 2, where the penalty acted on coefficient sizes. Trees are blind to scale, so there is no `StandardScaler` here except inside the KNN model we carry over for comparison.\n\n::: {#8d021d85 .cell execution_count=3}\n``` {.python .cell-code}\nbaseline_mse = mean_squared_error(y_test, np.full_like(y_test, y_train.mean()))\n\nknn = make_pipeline(StandardScaler(), KNeighborsRegressor(n_neighbors=15))\nknn.fit(X_train, y_train)\nknn_mse = mean_squared_error(y_test, knn.predict(X_test))\n\nprint(f\"Predict-the-mean test MSE        : {baseline_mse:.1f}\")\nprint(f\"KNN (k=15, from Notebook 1) test MSE: {knn_mse:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPredict-the-mean test MSE        : 3708.3\nKNN (k=15, from Notebook 1) test MSE: 2654.4\n```\n:::\n:::\n\n\nPredicting the average savings of every household, ignoring all ten features, gives a test MSE of about 3708. That is the floor any real model must clear. The KNN model from Notebook 1 clears it at about 2654. Those two numbers, 3708 and 2654, are what we will try and beat. \n\n## 2. A single decision tree\n\nA regression tree is built greedily, one split at a time. It looks across every feature and every possible cut point, and chooses the single split that most reduces the mean squared error of the two groups it creates. Then it repeats the search inside each group, and again inside those, and so on. The result is a set of boxes, called **leaves**, and the prediction for any household is just the average training value in whatever leaf the household falls into.\n\nThe clearest way to see this is to grow a shallow tree, shallow enough to draw, and read it.\n\n::: {#69f34522 .cell execution_count=4}\n``` {.python .cell-code}\ntree3 = DecisionTreeRegressor(max_depth=3, random_state=RANDOM_STATE)\ntree3.fit(X_train, y_train)\n\nplt.figure(figsize=(16, 8))\nplot_tree(tree3, feature_names=features, filled=True, rounded=True,\n          impurity=False, fontsize=9)\nplt.title(\"A regression tree of depth 3 (leaf value = predicted net financial assets)\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_03_trees_forests_boosting_files/figure-ipynb/cell-5-output-1.png){}\n:::\n:::\n\n\nRead the tree from the top. The very first question it asks is whether the household owns an IRA (`pira`): owning one separates committed savers from everyone else with a single yes/no, which is why the tree chose it first. From there the splits are mostly about income, with age deciding some of the deeper ones. Follow any path down to a leaf and you reach a predicted value, and those values climb steeply: from a few thousand dollars in the leaves of low-income non-savers up into the hundreds of thousands for older, high-income IRA owners. The tree has rediscovered, with no equation, what a regression would also find: savings track income, age, and whether a household already holds retirement accounts.\n\n::: {#a6c834b6 .cell execution_count=5}\n``` {.python .cell-code}\nprint(f\"Depth-3 tree test MSE: {mean_squared_error(y_test, tree3.predict(X_test)):.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDepth-3 tree test MSE: 3034.7\n```\n:::\n:::\n\n\nThis little tree already beats predicting the mean, though it is still short of KNN. It is also easy to read, which is part of why trees are popular. But the depth-3 limit was ours to impose. What happens if we let the tree grow as deep as it likes?\n\n### 2.1 When Trees overfit\n\nIf we remove the depth limit, the tree keeps splitting until it can't anymore, in the limit isolating nearly one training household per leaf.\n\n::: {#eed0c1c1 .cell execution_count=6}\n``` {.python .cell-code}\ndeep_tree = DecisionTreeRegressor(random_state=RANDOM_STATE)  # no depth limit\ndeep_tree.fit(X_train, y_train)\n\nprint(f\"Deep tree depth        : {deep_tree.get_depth()}\")\nprint(f\"Deep tree training MSE : {mean_squared_error(y_train, deep_tree.predict(X_train)):.1f}\")\nprint(f\"Deep tree test MSE     : {mean_squared_error(y_test, deep_tree.predict(X_test)):.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDeep tree depth        : 37\nDeep tree training MSE : 0.0\nDeep tree test MSE     : 4739.5\n```\n:::\n:::\n\n\nThe tree grew 37 levels deep, and its training MSE is essentially zero. It has put almost every training household in a leaf of its own and reads the value straight back, so on the training data it is never wrong. We have seen this failure twice already: it is the $k=1$ nearest-neighbour problem from Notebook 1 and the too-many-coefficients problem from Notebook 2, just with trees. The test MSE, 4739.5, is *worse* than the depth-3 tree, worse than KNN, and worse even than predicting the mean. A tree deep enough to memorise the training households carries none of that memorisation over to new ones.\n\nSo `max_depth` is the tree's flexibility parameter, playing the role that $k$ played for KNN and $\\lambda$ played for ridge and lasso. A shallow tree is rigid and high-bias, a deep tree is flexible and high-variance, and somewhere in between is a depth that predicts best.\n\n### 2.2 Choosing the depth\n\nWe find that depth the same way we found $k$ in Notebook 1: plot it and watch both errors.\n\n::: {#21e4ef72 .cell execution_count=7}\n``` {.python .cell-code}\ndepths = range(1, 21)\ntrain_errors, test_errors = [], []\nfor d in depths:\n    t = DecisionTreeRegressor(max_depth=d, random_state=RANDOM_STATE).fit(X_train, y_train)\n    train_errors.append(mean_squared_error(y_train, t.predict(X_train)))\n    test_errors.append(mean_squared_error(y_test, t.predict(X_test)))\n\nbest_depth_by_test = list(depths)[int(np.argmin(test_errors))]\n\nplt.figure(figsize=(9, 6))\nplt.plot(list(depths), train_errors, label=\"training MSE\")\nplt.plot(list(depths), test_errors, label=\"test MSE\")\nplt.axvline(best_depth_by_test, color=\"black\", linestyle=\"--\",\n            label=f\"lowest test MSE at depth = {best_depth_by_test}\")\nplt.xlabel(\"max_depth\")\nplt.ylabel(\"mean squared error\")\nplt.title(\"The bias-variance tradeoff for a tree: depth is the flexibility knob\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_03_trees_forests_boosting_files/figure-ipynb/cell-8-output-1.png){}\n:::\n:::\n\n\nIt is the same picture as Notebook 1, drawn against depth instead of $k$, as that is the corresponding hyperparameter for trees. Training MSE falls steadily toward zero as the tree grows, because a deeper tree can always cut the training data more finely. Test MSE traces the bias-variance U-shape: shallow trees (depth 1 to 3) are too rigid and sit a little high, it bottoms out across a flat, noisy stretch from roughly depth 4 to 7, and beyond depth 8 it climbs steadily as the tree fits noise. The dashed line marks the lowest test MSE here, at depth 4, but several neighbouring depths are similar. That flat, wiggly bottom is why we don't pick the depth by eye, and turn to cross-validation instead.\n\nWe choose it with cross-validation, never touching the test set, like in notebook 1.\n\n::: {#301c38c1 .cell execution_count=8}\n``` {.python .cell-code}\nkfold = KFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)\n\ncv_errors = []\nfor d in depths:\n    scores = cross_val_score(\n        DecisionTreeRegressor(max_depth=d, random_state=RANDOM_STATE),\n        X_train, y_train, cv=kfold, scoring=\"neg_mean_squared_error\")\n    cv_errors.append(-scores.mean())\n\nbest_depth = list(depths)[int(np.argmin(cv_errors))]\ntree_best = DecisionTreeRegressor(max_depth=best_depth, random_state=RANDOM_STATE).fit(X_train, y_train)\ntree_mse = mean_squared_error(y_test, tree_best.predict(X_test))\n\nprint(f\"Cross-validation chose max_depth = {best_depth}\")\nprint(f\"Tuned single-tree test MSE: {tree_mse:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCross-validation chose max_depth = 4\nTuned single-tree test MSE: 2784.9\n```\n:::\n:::\n\n\nCross-validation decides on a shallow depth of 4, and the tuned tree scores just behind KNN, close enough that a single well-chosen tree is already a competitive predictor. We have now run the same four steps as in Notebook 1: split off a test set, cross-validate on the training data to choose the parameter, pick the best value, and evaluate once on the sealed test set.\n\nThe issue is that even the best single tree is a high-variance object. Shift a few training households and the greedy search can pick a different first split, and the whole tree below it rearranges. We can see that instability directly. Below we pick five test households spanning low to high savings, and ask forty trees, each fit to a different bootstrap resample of the training data, to predict each one. **Bootstrapping**: drawing, with replacement, many resamples of the training data the same size as the original (you may have seen this concept in ECON 226 and 326). Every grey dot is one tree's guess; the red mark is the forest's single answer.\n\n::: {#03e2286c .cell execution_count=9}\n``` {.python .cell-code}\nforest_demo = RandomForestRegressor(n_estimators=300, random_state=RANDOM_STATE, n_jobs=-1)\nforest_demo.fit(X_train, y_train)\n\n# Five test households spanning low to high predicted savings.\norder = np.argsort(forest_demo.predict(X_test))\npicks = [order[int(q * (len(order) - 1))] for q in [0.2, 0.4, 0.6, 0.8, 0.9]]\nX_pick = X_test.iloc[picks]\n\n# Ask forty single trees, each fit to its own bootstrap resample, about each household.\nrng = np.random.default_rng(0)\ntree_guesses = np.array([\n    DecisionTreeRegressor(random_state=RANDOM_STATE).fit(X_train.iloc[idx], y_train[idx]).predict(X_pick)\n    for idx in (rng.integers(0, len(X_train), len(X_train)) for _ in range(40))\n])\n\nplt.figure(figsize=(9, 6))\nfor j in range(len(picks)):\n    xj = (j + 1) + rng.uniform(-0.18, 0.18, len(tree_guesses))\n    plt.scatter(xj, tree_guesses[:, j], s=14, alpha=0.4, color=\"grey\",\n                label=\"single trees (one dot per tree)\" if j == 0 else None)\nplt.scatter(range(1, len(picks) + 1), forest_demo.predict(X_pick), color=\"tab:red\",\n            s=160, marker=\"_\", linewidth=3, zorder=5, label=\"random forest\")\nplt.xticks(range(1, len(picks) + 1), [f\"household {i+1}\" for i in range(len(picks))])\nplt.ylim(-40, 180)\nplt.ylabel(\"predicted net financial assets ($1,000s)\")\nplt.title(\"Ask 40 single trees about one household and they scatter; the forest gives one steady answer\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_03_trees_forests_boosting_files/figure-ipynb/cell-10-output-1.png){}\n:::\n:::\n\n\nFor any one household the grey dots are spread all over: ask a different resample and a single tree shifts its answer by tens of thousands of dollars. The red mark is the forest, the average of trees just like these, and it sits as one steady prediction in the middle of the scatter. The spread grows for the higher-saving households on the right, where a few extreme outcomes make any singular tree have extremely high variance. \n\n## 3. Many Trees: Random Forest\n\nA single deep tree has low bias and high variance: it captures fine structure, but its predictions can swing a lot when the training data changes, just as the grey dots above showed. We fix this by taking the average. If we had many trees, each fit to a slightly different sample, their individual errors would partly cancel when we averaged their predictions, while the structure they agree on would survive.\n\nWe do not have many samples, but we can manufacture them by **bootstrapping**. We fit a deep tree to each resample and average their predictions. This is called **bagging**, short for bootstrap aggregating, and it keeps the low bias of deep trees while cutting their variance.\n\nA **random forest** adds one more idea. At each split, each tree is allowed to consider only a random handful of the features, not all ten. This stops every tree from opening with the same IRA split and makes the trees less alike, so their errors cancel more thoroughly when averaged. It leads to a bit more bias per tree, but we get a significant drop in variance instead.\n\n::: {#2ee372e1 .cell execution_count=10}\n``` {.python .cell-code}\nforest = RandomForestRegressor(n_estimators=300, random_state=RANDOM_STATE, n_jobs=-1)\nforest.fit(X_train, y_train)\n\nforest_mse = mean_squared_error(y_test, forest.predict(X_test))\nprint(f\"Random forest training MSE: {mean_squared_error(y_train, forest.predict(X_train)):.1f}\")\nprint(f\"Random forest test MSE    : {forest_mse:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRandom forest training MSE: 473.8\nRandom forest test MSE    : 2837.7\n```\n:::\n:::\n\n\nThe forest scores 2837.7 on the test set. Notice the training MSE: it is far from zero, even though each individual tree in the forest still memorises its own bootstrap sample. Averaging across 300 trees pulls the aggregate away from memorisation, and that's why the forest generalizes well, when a single deep tree did not. On this data the forest is similar to a tuned-tree and KNN.\n\n### 3.1 Feature Importance\n\nA forest cannot be drawn as one readable diagram, but it can tell us how much each feature contributed to reducing MSE across all the splits in all the trees. This is called **feature importance**.\n\n::: {#c586c58b .cell execution_count=11}\n``` {.python .cell-code}\nimportances = pd.Series(forest.feature_importances_, index=features).sort_values()\n\nplt.figure(figsize=(9, 6))\nplt.barh(importances.index, importances.values)\nplt.xlabel(\"importance (share of total MSE reduction)\")\nplt.title(\"Random forest feature importances\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_03_trees_forests_boosting_files/figure-ipynb/cell-12-output-1.png){}\n:::\n:::\n\n\nIncome is by far the most useful feature, followed by age and owning an IRA. This matches what we read off the single tree. Look at `e401` in that graph, the eligibility for a 401(k) variable that this whole stream is building toward. It is near the very bottom, barely used by the forest at all. It's a useful diagnostic, but a *predictive* one. We will find out in notebook 8 that its predictive power says nothing about its true effect.\n\n## 4. Boosting\n\nBagging and forests build many trees in parallel and average them. **Boosting** builds trees in sequence. The first tree makes its predictions, and the next tree is fit not to the outcome but to the errors the first one left behind, so it spends its effort on the cases the aggregate is getting wrong. Add a third tree fit to what the first two still miss, repeated over many rounds. The trees are kept deliberately shallow, because each one only has to nudge the running prediction a little.\n\nWe can watch the running prediction build up. Below we boost on income alone so we can draw it, and plot the ensemble's fit after 1 round, after 5, and after 50.\n\n::: {#ecab889e .cell execution_count=12}\n``` {.python .cell-code}\ninc1 = X_train[[\"inc\"]]\ninc_grid = pd.DataFrame({\"inc\": np.linspace(inc1[\"inc\"].min(), inc1[\"inc\"].max(), 200)})\n\ngb = GradientBoostingRegressor(n_estimators=200, max_depth=2, random_state=RANDOM_STATE)\ngb.fit(inc1, y_train)\nstage_preds = list(gb.staged_predict(inc_grid))\n\nplt.figure(figsize=(9, 6))\nplt.scatter(inc1[\"inc\"], y_train, s=8, alpha=0.1, color=\"grey\")\nfor n in [1, 10, 100]:\n    plt.plot(inc_grid[\"inc\"], stage_preds[n - 1], linewidth=2, label=f\"{n} round(s)\")\nplt.ylim(-10, 120)\nplt.xlabel(\"income ($1,000s)\")\nplt.ylabel(\"predicted net financial assets ($1,000s)\")\nplt.title(\"Boosting builds up: each round fits the errors the last ones left\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_03_trees_forests_boosting_files/figure-ipynb/cell-13-output-1.png){}\n:::\n:::\n\n\nAfter one round the fit is a simple step function. After ten it has bent toward the data. After one hundred it traces the income-savings relationship even closer, having spent each new tree on whatever the running total still got wrong. Now we fit the full boosted model on all ten features.\n\n::: {#77c69742 .cell execution_count=13}\n``` {.python .cell-code}\nboosted = GradientBoostingRegressor(random_state=RANDOM_STATE)\nboosted.fit(X_train, y_train)\nboosted_mse = mean_squared_error(y_test, boosted.predict(X_test))\n\nprint(f\"Gradient boosting test MSE: {boosted_mse:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGradient boosting test MSE: 2593.4\n```\n:::\n:::\n\n\nOut of the box, boosting is the best predictor we have built on this data, ahead of KNN and the forest. The gap is small, and it can be improved further with some fine tuning; the point for us is not which tree ensemble wins by a few percent, but that both bagging and boosting take the overfitting tree from section 2 and turn it into a powerful predictor. In practice the boosting idea is taken further by libraries like `XGBoost` and `LightGBM`, which are among the most reliable predictors in everyday use, but the mechanism is the one we just learned about.\n\nWe stop at tree ensembles. Neural networks are another flexible predictor, you can read more about them [in this notebook](https://ubcecon.github.io/praxis-ubc/docs/intro_to_deep_learning/intro_to_fundamental_ML.html).\n\n## 5. So have we found the effect of 401(k) eligibility?\n\nLet us line up every model we have fit on this same split.\n\n::: {#92b99c83 .cell execution_count=14}\n``` {.python .cell-code}\nresults = pd.DataFrame({\n    \"model\": [\"Predict the mean\", \"KNN (k=15)\", \"Single tree (tuned)\",\n              \"Random forest\", \"Gradient boosting\"],\n    \"test MSE\": [baseline_mse, knn_mse, tree_mse, forest_mse, boosted_mse],\n})\nprint(results.round(1).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              model  test MSE\n   Predict the mean    3708.3\n         KNN (k=15)    2654.4\nSingle tree (tuned)    2784.9\n      Random forest    2837.7\n  Gradient boosting    2593.4\n```\n:::\n:::\n\n\nThe flexible methods all beat the baseline and land close together, with boosting a bit ahead of the others. So we now have a decent predictor of household savings. Time for the question this stream keeps returning to:\n\n> Do any of these models tell us the **effect** of 401(k) eligibility on a household's savings?\n\n**No!** Look back at the model comparison: the flexible methods cluster together, and they got there by chasing whatever predicts savings. The tree opened on owning an IRA because that variable splits savers from everyone else with the most predictive power, not because we ever showed that owning an IRA causes savings, and the forest utilizes income and age for the same reason. Meanwhile `e401`, the eligibility variable this whole stream is building toward, sat near the bottom of the importance plot, almost useless for prediction because eligible and ineligible households already look so different. But that low importance says nothing about its effect: in Notebook 1 we built a world where eligibility had a real, positive effect that a naive comparison still got wrong, and the public-economics literature finds a real effect too. And no forest (or other predictive technique), ever imagines *this* household made eligible with everything else held fixed, which is the counterfactual a causal answer requires. A model can be a fine predictor and still be useless for the effect we came here to measure. Notebook 4 makes the turn and explains what identifying a treatment effect actually requires.\n\n::: {.callout-note}\n## Its causal future\n\nThe random forest comes back later in a causal disguise. Notebook 8's **causal forest** reuses this notebook's ideas, re-aimed from predicting an outcome to estimating how a treatment effect varies from one household to the next.\n:::\n\n## Connections\n\n- **Back to [Notebook 2](notebook_02_regularization_ridge_lasso.qmd):**  ridge and lasso were flexible *linear* models, controlled by a penalty. \n- **Forward to [Notebook 4](notebook_04_prediction_to_treatment_effects.qmd):** we now have learned three prediction tools and still cannot answer a causal question with any of them. Notebook 4 explains why, and what identification requires that prediction does not, and why.\n\n### References\n\n- Breiman, L. (1996). *Bagging predictors.* Machine Learning, 24(2), 123-140.\n- Breiman, L. (2001). *Random forests.* Machine Learning, 45(1), 5-32.\n- Chernozhukov, V., Hansen, C., & Spindler, M. (2016). *hdm: High-dimensional metrics.* R Journal, 8(2), 185-199. The source of the 401(k) dataset.\n- Friedman, J. H. (2001). *Greedy function approximation: a gradient boosting machine.* Annals of Statistics, 29(5), 1189-1232.\n- GeeksforGeeks. (2025). *Feature importance with random forests.* GeeksforGeeks. https://www.geeksforgeeks.org/machine-learning/feature-importance-with-random-forests/\n- James, G., Witten, D., Hastie, T., & Tibshirani, R. (2021). *An Introduction to Statistical Learning.* Springer. (Chapter 8.)\n- scikit-learn developers. (n.d.). *1.10. Decision trees.* scikit-learn. https://scikit-learn.org/stable/modules/tree.html\n- Wikipedia contributors. (2025). *Bootstrap aggregating.* Wikipedia. https://en.wikipedia.org/wiki/Bootstrap_aggregating\n- Wikipedia contributors. (n.d.). *Random forest.* Wikipedia. https://en.wikipedia.org/wiki/Random_forest\n\n---\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.13.5\n---\n",
    "supporting": [
      "notebook_03_trees_forests_boosting_files\\figure-ipynb"
    ],
    "filters": []
  }
}