{
  "hash": "98819fdd847d48c898a7b5b6c1968c45",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Network Analysis: KINMATRIX Dataset\"\nauthor: prAxIs UBC Team <br> _Alex Ronczewski_\ndate: '2025-10-13'\ndescription: Using the KINMATRIX Dataset to explore network analysis for SOCI 415\nimage: media/2023_poland.jpg\ncategories:\n  - Python\n  - network analysis\n  - SOCI 415\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html:\n    embed-resources: true\n    self-contained-math: true\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: Python\n        language: python3\n        name: python3\n---\n\n\n\n\n\n\n# Prerequisites\nSOCI 415 Network Analysis Notebook\n\n## KINMATRIX DATA DESCRIPTION\nThe KINMATRIX dataset represents families as ego-centric networks of younger adults aged 25 to 35, collecting extensive data about both nuclear and extended kin across ten countries. The data include over 12,000 anchor respondents and more than 252,000 anchor-kin dyads, encompassing a wide range of relatives such as parents, siblings, grandparents, aunts, uncles, cousins, and complex kin (e.g., step- and half-relatives).\n\nAnchor respondents refer to the ones directly sampled from. These anchors filled out the survey about their families and kin meaning that they will always be at the center of these family networks. \n\nThe countries in the dataset are the United Kingdom, Germany, Poland, Italy, Sweden, Denmark, Finland, Norway, the Netherlands and the USA. \n\n## Downloading the Data\n\nStudents will have to download the data for legal reasons and then place them into the notebook's working directory. \n\nFirst navigate to [The KINMATRIX Data page](https://kinmatrix.eu/data/) from there click on the **large red Data download button**. You will need to make an account on GESIS. Once you have created the account on the right-hand side there is a panel with different download options. Press **Datasets** and select **ZA8825_v1-0-0.dta (Dataset) 112.56 MB**, make sure it is the .dta version. \n\nThis will start a download, once it is completed copy the file and paste it into the datasets folder in the same directory as the notebook. There will already be one file there called latest.db make sure it is in the same folder.\n\n### Part 1. Broader Patterns Across Countries \n\nWe will begin by looking at broader patterns across different countries. This will serve as an introduction into the dataset and will be a foundation for more focused analysis later on. First we import all the necessary Python libraries for data manipulation, network analysis, and visualization. This will allow us to get results for each country. The output of this cell will be a list of countries in the data. \n\nImport Libraries and the Data:\n\n::: {#8c12a47f .cell execution_count=1}\n``` {.python .cell-code}\n#Import libraries\nimport matplotlib.pyplot as plt \nimport matplotlib.patches as mpatches \nimport networkx as nx \nimport pandas as pd \nimport numpy as np\nimport geopandas as gpd\nimport contextily as ctx\nfrom mpl_toolkits.axes_grid1.inset_locator import inset_axes\nimport community as community_louvain\nimport random\nimport plotly.graph_objects as go\nfrom pyvis.network import Network\nimport re\nimport matplotlib.cm as cm\n\nfile_path = r'datasets/ZA8825_v1-0-0.dta' #path\ndf = pd.read_stata(file_path)\n\n#Print country codes\nprint(df['anc_cou'].unique())\n\n#Make a list of countries\ncountry_dfs = {}\nfor country in df['anc_cou'].unique():\n    country_dfs[country] = df[df['anc_cou'] == country]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n['1. UK', '10. USA', '3. Poland', '5. Sweden', '7. Finland', '9. Netherlands', '2. Germany', '4. Italy', '8. Norway', '6. Denmark']\nCategories (10, object): ['1. UK' < '2. Germany' < '3. Poland' < '4. Italy' ... '7. Finland' < '8. Norway' < '9. Netherlands' < '10. USA']\n```\n:::\n:::\n\n\n#### 1.1 Make it a Network \n\nHere, we systematically construct a kinship network for each country in the dataset using the NetworkX Python package. For each country, we filter the data, create a new graph, and add nodes representing anchor individuals and their kin. Then we draw edges between the nodes. Finally, we print out the number of nodes and edges for each country's network, providing a quick overview of network size and complexity across the dataset.\n\n::: {#489b300f .cell execution_count=2}\n``` {.python .cell-code}\n# Set up a dictionary of countries\ncountry_map = {\n    'UK': '1. UK',\n    'Germany': '2. Germany',\n    'Poland': '3. Poland',\n    'Italy': '4. Italy',\n    'Sweden': '5. Sweden',\n    'Denmark': '6. Denmark',\n    'Finland': '7. Finland',\n    'Norway': '8. Norway',\n    'Netherlands': '9. Netherlands',\n    'USA': '10. USA'\n}\ngraphs = {}\n\nfor country, anc_cou_value in country_map.items():\n    filtered_df = df[df['anc_cou'] == anc_cou_value]\n    G_filtered = nx.Graph()\n    \n    # Add anchor nodes\n    for idx, row in filtered_df.iterrows():\n        G_filtered.add_node(row['anc_id'], \n                            country=row['anc_cou'],\n                            age=row['anc_age'],\n                            gender=row['anc_gnd'])\n    \n    # Add kin nodes and edges\n    for idx, row in filtered_df.iterrows():\n        kin_node = f\"{row['anc_id']}_{row.get('kin_nam', 'unknown')}_{idx}\"\n        G_filtered.add_node(kin_node, relation=row.get('kin_rel1', None))\n        G_filtered.add_edge(row['anc_id'], kin_node, relation=row.get('kin_rel1', None))\n    \n    # Store the graph and anchor nodes\n    anchor_nodes = list(filtered_df['anc_id'].unique())\n    graphs[country] = {\n        'graph': G_filtered,\n        'anchor_nodes': anchor_nodes\n    }\n    \n    print(f\"{country}:\")\n    print(f\"  Number of nodes: {G_filtered.number_of_nodes()}\")\n    print(f\"  Number of edges: {G_filtered.number_of_edges()}\")\n    print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nUK:\n  Number of nodes: 26951\n  Number of edges: 25638\n\nGermany:\n  Number of nodes: 20934\n  Number of edges: 19726\n\nPoland:\n  Number of nodes: 34658\n  Number of edges: 32926\n\nItaly:\n  Number of nodes: 37278\n  Number of edges: 35369\n\nSweden:\n  Number of nodes: 7204\n  Number of edges: 6849\n\nDenmark:\n  Number of nodes: 3160\n  Number of edges: 3006\n\nFinland:\n  Number of nodes: 4936\n  Number of edges: 4695\n\nNorway:\n  Number of nodes: 2706\n  Number of edges: 2579\n\nNetherlands:\n  Number of nodes: 8187\n  Number of edges: 7793\n\nUSA:\n  Number of nodes: 118702\n  Number of edges: 113697\n\n```\n:::\n:::\n\n\nWe can see that the KINMATRIX dataset has a wide range of networks ranging from smaller countries like Norway and Denmark (~3000 Nodes) to expansive networks like the United States with 118,702 nodes. This is a good overview, but it does not really give any information on the nature of the networks, their size, family relations and other interesting statistics. \n\n#### 1.2 Finding summary statistics across the countries \n\nThis block computes and displays key network statistics for each country's kinship network. We calculate the mean degree (average number of connections per node), and the gender distribution among anchor nodes. \n\n::: {#47b2f1cd .cell execution_count=3}\n``` {.python .cell-code}\nfor country, data in graphs.items():\n    G = data['graph']\n    anchor_nodes = data['anchor_nodes']\n    \n    # Mean degree for anchor nodes only\n    anchor_degrees = [G.degree(n) for n in anchor_nodes]\n    mean_anchor_degree = np.mean(anchor_degrees) if anchor_degrees else 0\n    \n    # Gender distribution among anchor nodes\n    female_count = sum(1 for n in anchor_nodes if G.nodes[n].get('gender') == '2. Female')\n    male_count = sum(1 for n in anchor_nodes if G.nodes[n].get('gender') == '1. Male')\n    other_count = sum(1 for n in anchor_nodes if G.nodes[n].get('gender') == '3. Other gender or no gender')\n    \n    print(f\"{country}:\")\n    print(f\"  Mean degree (anchor nodes): {mean_anchor_degree:.2f}\")\n    print(f\"  Female anchor nodes: {female_count}\")\n    print(f\"  Male anchor nodes: {male_count}\")\n    print(f\"  Other/No gender anchor nodes: {other_count}\")\n    print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nUK:\n  Mean degree (anchor nodes): 19.53\n  Female anchor nodes: 752\n  Male anchor nodes: 553\n  Other/No gender anchor nodes: 7\n\nGermany:\n  Mean degree (anchor nodes): 16.33\n  Female anchor nodes: 670\n  Male anchor nodes: 534\n  Other/No gender anchor nodes: 4\n\nPoland:\n  Mean degree (anchor nodes): 19.01\n  Female anchor nodes: 1023\n  Male anchor nodes: 705\n  Other/No gender anchor nodes: 4\n\nItaly:\n  Mean degree (anchor nodes): 18.53\n  Female anchor nodes: 1040\n  Male anchor nodes: 858\n  Other/No gender anchor nodes: 9\n\nSweden:\n  Mean degree (anchor nodes): 19.29\n  Female anchor nodes: 170\n  Male anchor nodes: 184\n  Other/No gender anchor nodes: 1\n\nDenmark:\n  Mean degree (anchor nodes): 19.52\n  Female anchor nodes: 88\n  Male anchor nodes: 66\n  Other/No gender anchor nodes: 0\n\nFinland:\n  Mean degree (anchor nodes): 19.48\n  Female anchor nodes: 113\n  Male anchor nodes: 124\n  Other/No gender anchor nodes: 3\n\nNorway:\n  Mean degree (anchor nodes): 20.31\n  Female anchor nodes: 68\n  Male anchor nodes: 56\n  Other/No gender anchor nodes: 3\n\nNetherlands:\n  Mean degree (anchor nodes): 19.78\n  Female anchor nodes: 246\n  Male anchor nodes: 148\n  Other/No gender anchor nodes: 0\n\nUSA:\n  Mean degree (anchor nodes): 22.72\n  Female anchor nodes: 2992\n  Male anchor nodes: 1956\n  Other/No gender anchor nodes: 53\n\n```\n:::\n:::\n\n\nThe results are interesting we can see that the smallest family networks are in Germany (16.33 nodes per anchor) and the largest are in the United States (22.72 nodes per anchor). We can also see that there are more women than men in most countries especially in the US (2,992 women compared to 1,956 men). \n\n#### 1.3 Pyvis Visualization for Norway\n\nHere we have enough information to do a visualization of our findings. We will use the Pyvis package. This package will make an interactive visualization which you can zoom in and pan around. This will be the most simple visualization we will make, and it will just be on the shape and size of the network. The code loads the NetworkX graph into Pyvis, cleans any missing attribute values, and provides interactive controls for exploring the network.\n\n::: {#18e99413 .cell execution_count=4}\n``` {.python .cell-code}\n# Retrieve the Norway Network\nG_Norway = graphs['Norway']['graph']\nanchor_nodes_norway = graphs['Norway']['anchor_nodes']\n\n# Clean None attributes\nfor n, attrs in G_Norway.nodes(data=True):\n    for k, v in attrs.items():\n        if v is None:\n            G_Norway.nodes[n][k] = \"NA\"\n\nfor u, v, attrs in G_Norway.edges(data=True):\n    for k, val in attrs.items():\n        if val is None:\n            G_Norway.edges[u, v][k] = \"NA\"\n\n# Create a new Pyvis Network\nnet = Network(height='800px', width='100%', notebook=True)\n\n# Create simple anchor mapping\nanchor_to_label = {}\nfor i, anchor in enumerate(anchor_nodes_norway, 1):\n    anchor_to_label[anchor] = f\"Anchor-{i}\"\n\n# Add nodes manually \nfor node in G_Norway.nodes():\n    if node in anchor_nodes_norway:\n        # Anchor nodes with labels\n        net.add_node(node, label=anchor_to_label[node], color='#4ECDC4', size=15)\n    else:\n        # Kin nodes\n        net.add_node(node, color='#4ECDC4', size=8)\n\n# Add edges manually\nfor u, v in G_Norway.edges():\n    net.add_edge(u, v)\n\nfor node in net.nodes:\n    if node['id'] not in anchor_nodes_norway:\n        node['label'] = '' \n\n# Minimal settings\nnet.show('norway_updated_network.html')\n\nprint(\"All blue nodes version saved as 'norway_all_blue_nodes.html'\")\nprint(f\"Total nodes: {G_Norway.number_of_nodes()}\")\nprint(f\"Total edges: {G_Norway.number_of_edges()}\")\nprint(f\"Anchor nodes labeled: {len(anchor_nodes_norway)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.\nnorway_updated_network.html\nAll blue nodes version saved as 'norway_all_blue_nodes.html'\nTotal nodes: 2706\nTotal edges: 2579\nAnchor nodes labeled: 127\n```\n:::\n:::\n\n\n### 2. Density by Age and Gender Across Countries \n\nThis code block constructs kinship network graphs for each country in the KINMATRIX dataset and then analyzes how the number of nodes in the family networks vary by age and gender within each country. This analysis helps reveal patterns and differences in family network structure across demographic groups and between countries, providing insight into how kinship connectivity varies by age and gender in different countries.\n\n::: {#495b52cb .cell execution_count=5}\n``` {.python .cell-code}\ngraphs = {}\n\nfor country, anc_cou_value in country_map.items():\n    filtered_df = df[df['anc_cou'] == anc_cou_value]\n    G_filtered = nx.Graph()\n    \n    # Add anchor nodes\n    for idx, row in filtered_df.iterrows():\n        G_filtered.add_node(row['anc_id'], \n                            country=row['anc_cou'],\n                            age=row['anc_age'],\n                            gender=row['anc_gnd'])\n    \n    # Add kin nodes and edges\n    for idx, row in filtered_df.iterrows():\n        kin_node = f\"{row['anc_id']}_{row.get('kin_nam', 'unknown')}_{idx}\"\n        G_filtered.add_node(kin_node, relation=row.get('kin_rel1', None))\n        G_filtered.add_edge(row['anc_id'], kin_node, relation=row.get('kin_rel1', None))\n\n    graphs[country] = G_filtered\n\ndef analyze_family_degree_by_demographics(G_filtered):\n    degree_by_age = {}\n    degree_by_gender = {}\n\n    # Identify anchor nodes by prerequisite attribute\n    anchor_nodes = [n for n, d in G_filtered.nodes(data=True)\n                    if ('age' in d and 'gender' in d)]\n\n    for anchor_id in anchor_nodes:\n        # Degree of the anchor node (number of kin ties)\n        deg = G_filtered.degree(anchor_id)\n        age = G_filtered.nodes[anchor_id].get('age')\n        gender = G_filtered.nodes[anchor_id].get('gender')\n\n        if age is not None:\n            age_group = age // 10 * 10  \n            degree_by_age.setdefault(age_group, []).append(deg)\n        if gender is not None:\n            degree_by_gender.setdefault(gender, []).append(deg)\n\n    print(\"Mean Degree by Age Group:\")\n    for age_group, degrees in sorted(degree_by_age.items()):\n        print(f\"  Age {age_group}s: Mean Degree = {np.mean(degrees):.2f}, Count = {len(degrees)}\")\n\n    print(\"\\nMean Degree by Gender:\")\n    for gender, degrees in degree_by_gender.items():\n        print(f\"  Gender {gender}: Mean Degree = {np.mean(degrees):.2f}, Count = {len(degrees)}\")\n\n#Show results\nfor country in country_map:\n    if country in graphs:\n        print(f\"\\n--- {country} ---\")\n        analyze_family_degree_by_demographics(graphs[country])\n    else:\n        print(f\"No graph available for {country}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n--- UK ---\nMean Degree by Age Group:\n  Age 20s: Mean Degree = 20.23, Count = 539\n  Age 30s: Mean Degree = 19.04, Count = 774\n\nMean Degree by Gender:\n  Gender 1. Male: Mean Degree = 18.78, Count = 553\n  Gender 2. Female: Mean Degree = 20.08, Count = 752\n  Gender 3. Other gender or no gender: Mean Degree = 20.29, Count = 7\n  Gender -2. Prefer not to answer: Mean Degree = 12.00, Count = 1\n\n--- Germany ---\nMean Degree by Age Group:\n  Age 20s: Mean Degree = 16.97, Count = 509\n  Age 30s: Mean Degree = 15.86, Count = 699\n\nMean Degree by Gender:\n  Gender 1. Male: Mean Degree = 15.68, Count = 534\n  Gender 2. Female: Mean Degree = 16.80, Count = 670\n  Gender 3. Other gender or no gender: Mean Degree = 24.25, Count = 4\n\n--- Poland ---\nMean Degree by Age Group:\n  Age 20s: Mean Degree = 19.29, Count = 738\n  Age 30s: Mean Degree = 18.80, Count = 994\n\nMean Degree by Gender:\n  Gender 2. Female: Mean Degree = 20.25, Count = 1023\n  Gender 1. Male: Mean Degree = 17.22, Count = 705\n  Gender 3. Other gender or no gender: Mean Degree = 17.75, Count = 4\n\n--- Italy ---\nMean Degree by Age Group:\n  Age 20s: Mean Degree = 18.69, Count = 778\n  Age 30s: Mean Degree = 18.42, Count = 1131\n\nMean Degree by Gender:\n  Gender 2. Female: Mean Degree = 19.00, Count = 1040\n  Gender 1. Male: Mean Degree = 17.97, Count = 858\n  Gender 3. Other gender or no gender: Mean Degree = 17.11, Count = 9\n  Gender -2. Prefer not to answer: Mean Degree = 18.00, Count = 2\n\n--- Sweden ---\nMean Degree by Age Group:\n  Age 20s: Mean Degree = 19.20, Count = 147\n  Age 30s: Mean Degree = 19.36, Count = 208\n\nMean Degree by Gender:\n  Gender 1. Male: Mean Degree = 18.20, Count = 184\n  Gender 2. Female: Mean Degree = 20.48, Count = 170\n  Gender 3. Other gender or no gender: Mean Degree = 18.00, Count = 1\n\n--- Denmark ---\nMean Degree by Age Group:\n  Age 20s: Mean Degree = 20.04, Count = 77\n  Age 30s: Mean Degree = 19.00, Count = 77\n\nMean Degree by Gender:\n  Gender 2. Female: Mean Degree = 20.68, Count = 88\n  Gender 1. Male: Mean Degree = 17.97, Count = 66\n\n--- Finland ---\nMean Degree by Age Group:\n  Age 20s: Mean Degree = 18.70, Count = 123\n  Age 30s: Mean Degree = 20.30, Count = 118\n\nMean Degree by Gender:\n  Gender 1. Male: Mean Degree = 17.61, Count = 124\n  Gender 2. Female: Mean Degree = 21.50, Count = 113\n  Gender -2. Prefer not to answer: Mean Degree = 24.00, Count = 1\n  Gender 3. Other gender or no gender: Mean Degree = 19.00, Count = 3\n\n--- Norway ---\nMean Degree by Age Group:\n  Age 20s: Mean Degree = 18.69, Count = 58\n  Age 30s: Mean Degree = 21.67, Count = 69\n\nMean Degree by Gender:\n  Gender 2. Female: Mean Degree = 22.82, Count = 68\n  Gender 1. Male: Mean Degree = 17.30, Count = 56\n  Gender 3. Other gender or no gender: Mean Degree = 19.33, Count = 3\n\n--- Netherlands ---\nMean Degree by Age Group:\n  Age 20s: Mean Degree = 19.87, Count = 183\n  Age 30s: Mean Degree = 19.70, Count = 211\n\nMean Degree by Gender:\n  Gender 2. Female: Mean Degree = 20.88, Count = 246\n  Gender 1. Male: Mean Degree = 17.95, Count = 148\n\n--- USA ---\nMean Degree by Age Group:\n  Age 20s: Mean Degree = 22.62, Count = 2032\n  Age 30s: Mean Degree = 22.78, Count = 2973\n\nMean Degree by Gender:\n  Gender 2. Female: Mean Degree = 23.83, Count = 2992\n  Gender 1. Male: Mean Degree = 21.01, Count = 1956\n  Gender 3. Other gender or no gender: Mean Degree = 23.21, Count = 53\n  Gender -2. Prefer not to answer: Mean Degree = 16.50, Count = 4\n```\n:::\n:::\n\n\n#### 2.1 Finding a Pattern\n\nInteractive part: Have a look at our findings from sections 1 and 2, based on frameworks taught in class explain a reason for them. \n\nSome example findings are listed below, you can try to answer these 3, or look for your own and try to link it to a concept from class. \n\n1. Age does not seem to be a factor in mean degree. In six out of ten countries, anchors in their 20's have a higher degree than anchors in their 30's. Why is this, we would expect older anchors to have larger families? \n2. Women tend to have a higher mean degree than men in all countries (Poland: Male = 17.97, Female = 20.25). Why is this?\n3. The USA has the largest mean degree out of all countries in the dataset by both age and gender. Is it purely because of the large sample size in the US or are there other factors? We might expect the US to have a lower mean degree especially among anchors aged 20-30 as their parents or grandparents are likely to be immigrants disconnected from their families in their original countries. \n\n# 3.0 Colored Family Networks \n\nFor the next part of the notebook we have decided to focus on the Pomeranian (Pomorskie in Polish) Voivodeship in north-western Poland with the largest city being Gdańsk. \n\n![Location of Pomerania](media/pomorskie.png) \n\nIt has a population of 2.24 million as of 2019. \n\nThe code below will filter our data for Poland and the Pomorskie region to have a smaller subset.\n\n::: {#a014fd74 .cell execution_count=6}\n``` {.python .cell-code}\nfiltered_df = df[(df['anc_cou'] == '3. Poland') & (df['anc_regpl'] == '11. Pomorskie')] #Filter anc_cou to be Poland and anc_regpl to be Pomorskie\n#print(filtered_df.head())\nprint(f\"Number of rows after filtering: {len(filtered_df)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of rows after filtering: 2291\n```\n:::\n:::\n\n\n### 3.1 Make it a NetworkX Network\nThe code below makes a new NetworkX relationship with anchors (highest level of a family ancestor) and their kin. The output will be the total number of nodes and edges in the Network. \n\n::: {#286952f6 .cell execution_count=7}\n``` {.python .cell-code}\nG_filtered = nx.Graph()\n\n# Add anchor nodes for filtered data\nfor idx, row in filtered_df.iterrows():\n    G_filtered.add_node(row['anc_id'], \n                        country=row['anc_cou'],\n                        age=row['anc_age'],\n                        gender=row['anc_gnd'])\n\n# Add kin nodes and edges \nfor idx, row in filtered_df.iterrows():\n    kin_node = f\"{row['anc_id']}_{row.get('kin_nam', 'unknown')}_{idx}\"\n    G_filtered.add_node(kin_node, relation=row.get('kin_rel1', None))\n    G_filtered.add_edge(row['anc_id'], kin_node, relation=row.get('kin_rel1', None))\n\n# Define anchor_nodes\nanchor_nodes = list(filtered_df['anc_id'].unique())\n\nprint(f\"Number of nodes: {G_filtered.number_of_nodes()}\")\nprint(f\"Number of edges: {G_filtered.number_of_edges()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of nodes: 2414\nNumber of edges: 2291\n```\n:::\n:::\n\n\nThe Network in the Pomorskie region of Poland is quite small with 2414 nodes meaning that we can easily visualize it without running into computational problems.  \n\n### 3.2 Colored Visualization\n\nWe will make a Pyvis visualization with coloring for family structures. This will again be an interactive visualization where you will be able to pan and zoom. Another feature is that you can hover over nodes to see their gender, \n\nBelow we will have a legend of the relationships. \n\n::: {#4ee21523 .cell execution_count=8}\n``` {.python .cell-code}\n# Define color map for main relationship types\nrelationship_colors = {\n    'father': 'blue',\n    'mother': 'pink',\n    'brother': 'green',\n    'sister': 'purple',\n    'aunt': 'orange',\n    'uncle': 'brown',\n    'cousin': 'teal',\n    'grandfather': 'navy',\n    'grandmother': 'magenta',\n    'son': 'red',\n    'daughter': 'yellow',\n    'nephew': 'lightgreen',\n    'niece': 'lightpink',\n    'stepfather': 'slateblue',\n    'stepmother': 'plum',\n    'other': 'gray',\n}\n\ndef extract_relation(rel_str):\n    if not isinstance(rel_str, str):\n        return 'other'\n    rel_str = rel_str.lower()\n    # Remove the number prefix\n    rel_str = re.sub(r'^\\d+\\.\\s*', '', rel_str)\n    \n    # Find all matching relationship keywords with word boundaries and return the last one\n    found_relations = []\n    \n    # Sort relationship keys by length\n    sorted_keys = sorted(relationship_colors.keys(), key=len, reverse=True)\n    \n    for key in sorted_keys:\n        if key == 'other':\n            continue\n        # Use word boundaries to match complete words only\n        pattern = r'\\b' + re.escape(key) + r'\\b'\n        matches = list(re.finditer(pattern, rel_str))\n        for match in matches:\n            found_relations.append((match.start(), key))\n    \n    if found_relations:\n        # Sort by position and return the last one\n        found_relations.sort(key=lambda x: x[0])\n        return found_relations[-1][1]\n    \n    return 'other'\n\n# Create a new Pyvis Network\nnet = Network(height='800px', width='100%', notebook=True, bgcolor='#ffffff', font_color='black')\n\n# Create anchor mapping for cleaner labels\nanchor_to_label = {}\nanchor_nodes = list(filtered_df['anc_id'].unique())\nfor i, anchor in enumerate(anchor_nodes, 1):\n    anchor_to_label[anchor] = f\"Anchor-{i}\"\n\n# Add anchor nodes with clean labels\nfor idx, row in filtered_df.iterrows():\n    net.add_node(row['anc_id'],\n                 label=anchor_to_label[row['anc_id']],  \n                 color='lightblue',  \n                 size=15,  \n                 title=f\"Age: {row['anc_age']}<br>Gender: {row['anc_gnd']}\")\n\n# Add kin nodes and edges with relationship-based coloring\nfor idx, row in filtered_df.iterrows():\n    relation_raw = row.get('kin_typ', None)  \n    relation = extract_relation(relation_raw)\n    color = relationship_colors.get(relation, 'gray')\n    kin_node = f\"{row['anc_id']}_{row.get('kin_nam', 'unknown')}_{idx}\"\n    \n    # Add kin node with temporary label (will be removed later)\n    net.add_node(kin_node,\n                 label=str(row.get('kin_nam', 'unknown')),  # Temporary label\n                 color=color,\n                 size=8,  # Smaller size for kin nodes\n                 title=f\"Relation: {relation_raw}\")  # Hover info stays\n    \n    net.add_edge(row['anc_id'], kin_node, title=relation_raw)\n\nfor node in net.nodes:\n    if node['id'] not in anchor_nodes:\n        node['label'] = ''  # Empty label for kin nodes - no labels when zoomed in\n\nnet.show_buttons()\nnet.show('family_structure_network.html')\n\npatches = [mpatches.Patch(color=color, label=relation) for relation, color in relationship_colors.items()]\n\n# Plot the legend of family relations in the cell output\nfig, ax = plt.subplots(figsize=(6, 4))\nax.legend(handles=patches, loc='center', frameon=False, fontsize=10)\nax.axis('off')\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.\nfamily_structure_network.html\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](kinmatrix_files/figure-ipynb/cell-9-output-2.png){}\n:::\n:::\n\n\nWhen looking at the visualization you can hover over the nodes for more family information, or you can look at the color legend printed just below the visualization. When hovering over a node you will see strings similar to \"Relation: 100. Father - Aunt 2 - Cousin 1.\" At first this might seem confusing, that a single node can have three relations associated with it. To explain the bizarre relationship structures lets print out the relationships to understand what's going on. \n\n::: {#1f94953b .cell execution_count=9}\n``` {.python .cell-code}\n# Build a table of anchor-label, kin-name, relationship string, and extracted main type\nrelationship_table = []\n\nfor idx, row in filtered_df.iterrows():\n    anchor_label = anchor_to_label.get(row['anc_id'], str(row['anc_id']))\n    kin_name = row.get('kin_nam', 'unknown')\n    rel_str = row.get('kin_typ', '')\n    main_relation = extract_relation(rel_str)\n    relationship_table.append({\n        'Anchor': anchor_label,\n        'Kin Name': kin_name,\n        'Relationship(s)': rel_str,\n        'Main Relation': main_relation\n    })\n\nrel_df = pd.DataFrame(relationship_table)\n# Display first 20 rows for quick inspection\nprint(rel_df.head(20).to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Anchor      Kin Name                  Relationship(s) Main Relation\nAnchor-1 1. Valid name        245. Mother - Grandfather   grandfather\nAnchor-1 1. Valid name                     4. Brother 2       brother\nAnchor-1 1. Valid name                     13. Sister 1        sister\nAnchor-1 1. Valid name                     3. Brother 1       brother\nAnchor-1 1. Valid name              35. Father - Aunt 1          aunt\nAnchor-1 1. Valid name         24. Father - Grandmother   grandmother\nAnchor-1 1. Valid name  145. Father - Aunt 1 - Cousin 1        cousin\nAnchor-1 1. Valid name        246. Mother - Grandmother   grandmother\nAnchor-1 1. Valid name                        2. Mother        mother\nAnchor-1 1. Valid name                        1. Father        father\nAnchor-1 1. Valid name            247. Mother - Uncle 1         uncle\nAnchor-1 1. Valid name 267. Mother - Uncle 1 - Cousin 1        cousin\nAnchor-1 1. Valid name         23. Father - Grandfather   grandfather\nAnchor-2 1. Valid name                     3. Brother 1       brother\nAnchor-2 1. Valid name                     4. Brother 2       brother\nAnchor-2 1. Valid name                        1. Father        father\nAnchor-2 1. Valid name                     14. Sister 2        sister\nAnchor-2 1. Valid name                     7. Brother 5       brother\nAnchor-2 1. Valid name                     8. Brother 6       brother\nAnchor-2 1. Valid name                        2. Mother        mother\n```\n:::\n:::\n\n\nThis makes things more clear. For example: the label \"245. Mother - Grandfather\" means: this kin is reached via the anchor's \"mother\" and then her \"grandfather.\"\n\nAnother example is: \"145. Father - Aunt 1 - Cousin 1\" which means: this relative is a cousin through the anchor's father's aunt.\n\nThese strings are traversals through the family tree of the anchor individual. The most important is the last term for these two examples \"Grandfather\" and \"Cousin,\" these are family role that the node has from the anchors perspective. The first one is the anchors Grandfather on his mothers side and the second one is his cousin from his father's side. \n\n# 3.3 In class discussion from the family structures visualization\n\nStudents will look at the visualization on their browser and in small groups of 3-4 will discuss how the findings from this dataset can be linked to theories in studied frameworks from the course. After about 10 minutes of discussion groups will state their most interesting or best interpretation that they found, some possible examples are listed below for the Social Exchange Framework, and the Feminist Framework.\n \n**Social Exchange Framework**\nFamily ties exist as a exchange of resources so each edge between the nodes means there is some form of exchange, this could range from such as support, care, or obligation. The color-coding of relationships (e.g., blue for father, pink for mother) visually distinguishes different types of exchanges, allowing analysis of who is connected to whom and what kinds of resources or support might flow along those ties. For example, a node with many blue (father) and pink (mother) connections might receive more parental support, while green (brother) or purple (sister) ties could represent sibling exchanges.\n\n**Feminist Framework**\nThe feminist framework examines gender roles, power imbalances, and the ways traditional family structures reinforce gender inequality. For example we can link the centrality or marginalization of female roles (e.g., mothers, daughters, sisters) compared to male roles (fathers, sons, brothers) to patriarchal structures of modern western society. \n\n# 4.0 Visualization of Gender \n\nBelow the code will make an interactive Pyvis visualization with dots colored for gender. This can be used to discuss gender compositions of families and feminist theory. We can see if our network supports the theory of power imbalances and reflect the ways traditional family structures reinforce gender inequality. \n\n::: {#0d93bd27 .cell execution_count=10}\n``` {.python .cell-code}\n#Relationship mapping\nGENDER_FROM_RELATIONSHIP = {\n    # Male relationships\n    'father': 'male', 'dad': 'male', 'daddy': 'male', 'papa': 'male',\n    'son': 'male', 'brother': 'male', 'grandfather': 'male', 'grandpa': 'male',\n    'uncle': 'male', 'nephew': 'male', 'husband': 'male', 'boyfriend': 'male',\n    'stepfather': 'male', 'stepson': 'male', 'stepbrother': 'male',\n    'father-in-law': 'male', 'son-in-law': 'male', 'brother-in-law': 'male',\n    'godfather': 'male', 'godson': 'male',\n    \n    # Female relationships\n    'mother': 'female', 'mom': 'female', 'mommy': 'female', 'mama': 'female',\n    'daughter': 'female', 'sister': 'female', 'grandmother': 'female', 'grandma': 'female',\n    'aunt': 'female', 'niece': 'female', 'wife': 'female', 'girlfriend': 'female',\n    'stepmother': 'female', 'stepdaughter': 'female', 'stepsister': 'female',\n    'mother-in-law': 'female', 'daughter-in-law': 'female', 'sister-in-law': 'female',\n    'godmother': 'female', 'goddaughter': 'female'\n}\n\n#Function to get gender color from node\ndef get_node_gender_and_color(row, is_anchor=True):\n    # Gender color mapping\n    colors = {'male': 'purple', 'female': 'yellow', 'unknown': 'green'} \n    \n    if is_anchor:\n        # For anchor nodes\n        gender_field = str(row.get('anc_gnd', '')).lower().strip()\n        \n        # Handle various gender field formats\n        if gender_field in ['m', 'male', 'man', '1. male', '1.male', 'male.', '1']:\n            return 'male', colors['male']\n        elif gender_field in ['f', 'female', 'woman', '2. female', '2.female', 'female.', '2']:\n            return 'female', colors['female']\n        elif 'male' in gender_field and 'female' not in gender_field:\n            return 'male', colors['male']\n        elif 'female' in gender_field:\n            return 'female', colors['female']\n    else:\n        # For kin nodes\n        gender_field = str(row.get('kin_gnd', '')).lower().strip()\n        \n        # Handle various gender field formats for kin nodes too\n        if gender_field in ['m', 'male', 'man', '1. male', '1.male', 'male.', '1']:\n            return 'male', colors['male']\n        elif gender_field in ['f', 'female', 'woman', '2. female', '2.female', 'female.', '2']:\n            return 'female', colors['female']\n        elif 'male' in gender_field and 'female' not in gender_field:\n            return 'male', colors['male']\n        elif 'female' in gender_field:\n            return 'female', colors['female']\n        \n        # Get gender from relationship if direct gender field doesn't work\n        relationship = str(row.get('kin_typ', '')).lower().strip()\n        # Clean the relationship string\n        relationship = re.sub(r'^(my|the|a|an)\\s+', '', relationship)\n        \n        # Check for relationship matches\n        for rel_key, gender in GENDER_FROM_RELATIONSHIP.items():\n            if rel_key in relationship or relationship in rel_key:\n                return gender, colors[gender]\n    \n    return 'unknown', colors['unknown']\n\n# Initialize your network\nnet = Network(height=\"600px\", width=\"100%\", bgcolor=\"#ffffff\", font_color=\"black\", notebook=True)\n\n# Create anchor mapping for cleaner labels\nanchor_to_label = {}\nanchor_nodes = list(filtered_df['anc_id'].unique())\nfor i, anchor in enumerate(anchor_nodes, 1):\n    anchor_to_label[anchor] = f\"Anchor-{i}\"\n\n# Add anchor nodes with gender-based coloring and only gender in hover\nprint(\"Adding anchor nodes with gender colors...\")\nfor idx, row in filtered_df.iterrows():\n    gender, color = get_node_gender_and_color(row, is_anchor=True)\n    net.add_node(row['anc_id'],\n                 label=anchor_to_label[row['anc_id']],  # Clean \"Anchor-X\" label\n                 color=color,\n                 size=15,  # Larger size for anchor nodes\n                 title=f\"Gender: {gender}\")  # Only gender in hover\n\n# Add kin nodes and edges with gender-based coloring\nprint(\"Adding kin nodes with gender colors...\")\nfor idx, row in filtered_df.iterrows():\n    gender, color = get_node_gender_and_color(row, is_anchor=False)\n    kin_node = f\"{row['anc_id']}_{row.get('kin_nam', 'unknown')}_{idx}\"\n    \n    net.add_node(kin_node,\n                 label='',  # No label for kin nodes\n                 color=color,\n                 size=8,  # Smaller size for kin nodes\n                 title=f\"Gender: {gender}\")  # Only gender in hover\n    \n    # Add edge between anchor and kin (no title/hover info on edges)\n    net.add_edge(row['anc_id'], kin_node)\n\n# Remove labels from kin nodes (keep only anchor node labels)\nfor node in net.nodes:\n    if node['id'] not in anchor_nodes:\n        node['label'] = ''  # Empty label for kin nodes\n\n# Configure and display network\nnet.show_buttons(filter_=['physics'])\nnet.show('cdn_gender_only_kinship_network_fixed.html')\nprint(\"Network created successfully with gender-only hover info!\")\n\n# Print summary of node colors\nnode_colors = {}\nfor node in net.nodes:\n    color = node['color']\n    node_colors[color] = node_colors.get(color, 0) + 1\n\nprint(\"\\nNode color summary:\")\ncolor_to_gender = {'purple': 'Male', 'yellow': 'Female', 'green': 'Unknown'}\nfor color, count in node_colors.items():\n    gender_name = color_to_gender.get(color, color)\n    print(f\"  {gender_name}: {count} nodes\")\n\nprint(f\"\\nNetwork summary:\")\nprint(f\"- Total nodes: {len(net.nodes)}\")\nprint(f\"- Total edges: {len(net.edges)}\")\nprint(f\"- Anchor nodes labeled: {len(anchor_nodes)}\")\nprint(f\"- Kin nodes: {len(net.nodes) - len(anchor_nodes)} (no labels)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nWarning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.\nAdding anchor nodes with gender colors...\nAdding kin nodes with gender colors...\ncdn_gender_only_kinship_network_fixed.html\nNetwork created successfully with gender-only hover info!\n\nNode color summary:\n  Male: 1222 nodes\n  Female: 1191 nodes\n  Unknown: 1 nodes\n\nNetwork summary:\n- Total nodes: 2414\n- Total edges: 2291\n- Anchor nodes labeled: 123\n- Kin nodes: 2291 (no labels)\n```\n:::\n:::\n\n\nThe color scheme we are using is male are purple, women are yellow and other/unknown gender individuals are colored as green. \n\n# 5.0 Health and Education Across Countries\n\nThe KINMATRIX Dataset is not just limited to information about family relations, during the data gathering process researchers also asked about socio-economic variables like education, employment, health, sexuality and religion. Our goal for this section is to look at Health and Education across the ten countries in the dataset. These metrics are based on surveys of anchor individuals. These are subjective measures which can change from country to country, the goal is to look if there are differences between countries which we can infer from the data that causes these differences in health and education. We should not expect these findings to reflect findings in censuses, or large cross country surveys of health and education as that was not the purpose of the KINMATRIX Dataset. \n\n### 5.1 Health and Education Variables\n\nWhen doing any analysis it's important to be familiar with the variables. In this case we are looking at Health and Education which are `anc_hea` and `anc_eduall`. Below we will print out all possible values these variables can take and the count of response for each.\n\n::: {#a9df029b .cell execution_count=11}\n``` {.python .cell-code}\nprint(\"All possible values in 'anc_hea':\")\nprint(df['anc_hea'].value_counts(dropna=False), end='\\n\\n')\n\nprint(\"All possible values in 'anc_eduall':\")\nprint(df['anc_eduall'].value_counts(dropna=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAll possible values in 'anc_hea':\nanc_hea\n2. Good           131432\n3. Fair            63840\n1. Very good       45289\n4. Bad              9298\n5. Very bad         1307\n-1. Don't know       981\n-2. No answer        131\nName: count, dtype: int64\n\nAll possible values in 'anc_eduall':\nanc_eduall\n3. High                     173231\n2. Mid                       70184\n1. Low                        7849\n-2. Prefer not to answer      1014\nName: count, dtype: int64\n```\n:::\n:::\n\n\n`anc_hea`: This variable which stands for the anchor person's self-rated health. The possible values represent subjective categories ranging from Very Good to Very Bad health. We can see most people in the dataset are in Good health with few in Bad or Very Bad health. \n\n`anc_eduall`: This variable represents the anchor person’s overall level of education, classified into three levels and an option for non-response. We can see most people in the dataset have high education. We will find out about why later on.  \n\nThe way in which we will define healthy is if the respondent says his health is either \"Very Good\" or \"Good.\" As for education we will define someone who is educated if they answered the \"High Response.\"\n\nThe Code block below will look through all countries and find most and least educated and most and least healthy. \n\n::: {#a1066482 .cell execution_count=12}\n``` {.python .cell-code}\n# Country mapping dictionary\ncountry_map = {\n    'UK': '1. UK',\n    'Germany': '2. Germany',\n    'Poland': '3. Poland',\n    'Italy': '4. Italy',\n    'Sweden': '5. Sweden',\n    'Denmark': '6. Denmark',\n    'Finland': '7. Finland',\n    'Norway': '8. Norway',\n    'Netherlands': '9. Netherlands',\n    'USA': '10. USA'\n}\n\n# Initialize results storage\nhealth_results = {}\neducation_results = {}\n\n# Calculate percentages for each country\nfor country, code in country_map.items():\n    country_df = df[df['anc_cou'] == code]\n    \n    # Health calculation\n    health_counts = country_df['anc_hea'].value_counts(dropna=True)\n    very_good = health_counts.get('1. Very good', 0)\n    good = health_counts.get('2. Good', 0)\n    total_health = health_counts.sum()\n    health_pct = (very_good + good) / total_health if total_health > 0 else 0\n    health_results[country] = health_pct\n    \n    # Education calculation\n    edu_counts = country_df['anc_eduall'].value_counts(dropna=True)\n    high_edu = edu_counts.get('3. High', 0)\n    # Exclude 'Prefer not to answer' from total\n    valid_responses = edu_counts.drop('-2. Prefer not to answer', errors='ignore').sum()\n    edu_pct = high_edu / valid_responses if valid_responses > 0 else 0\n    education_results[country] = edu_pct\n\n# Sort results from most to least\nsorted_health_desc = sorted(health_results.items(), key=lambda x: x[1], reverse=True)\nsorted_education_desc = sorted(education_results.items(), key=lambda x: x[1], reverse=True)\n\n# Prepare output strings\nhealth_output = \"Countries sorted by health (most to least healthy):\\n\"\nedu_output = \"Countries sorted by education (most to least educated):\\n\"\n\nfor country, pct in sorted_health_desc:\n    health_output += f\"{country}: {pct:.2%}\\n\"\n\nfor country, pct in sorted_education_desc:\n    edu_output += f\"{country}: {pct:.2%}\\n\"\n\nprint(health_output)\nprint(edu_output)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCountries sorted by health (most to least healthy):\nItaly: 76.60%\nNetherlands: 75.95%\nUK: 72.10%\nUSA: 69.29%\nNorway: 67.82%\nGermany: 67.78%\nFinland: 67.67%\nPoland: 66.55%\nSweden: 65.69%\nDenmark: 57.68%\n\nCountries sorted by education (most to least educated):\nUSA: 80.40%\nFinland: 76.63%\nUK: 72.62%\nNorway: 70.49%\nNetherlands: 66.53%\nPoland: 62.91%\nDenmark: 56.59%\nItaly: 52.55%\nSweden: 47.23%\nGermany: 45.97%\n\n```\n:::\n:::\n\n\nWe can see that the finding may be surprising for most people. The United States being the most educated and Germany being the least does seem strange at first glance, but these findings are correct according to the data.\n\nThe reason for these findings are the sampling methodology used by the Researchers. In the [Methods Report](https://www.demographic-research.org/volumes/vol51/25/51-25.pdf), we can find that the KINMATRIX researchers explicitly acknowledge that their data shows \"Substantial under-representation of lower-educated people in all countries\" and \"No accurate representation of country differences across intermediate and higher education levels\" (8). This is inflating the higher education percentages across the countries in our dataset. Because of the nature of education this bias towards higher education also \"extends also to their parental background\" (14) and further. \n\nAnother reason for this is bias is the manner in which the data was collected. The key reason is that the researchers did not do random sampling, but rather quota sampling from Dynata access panels which hosted an online survey. This method may lead to the exclusion of people without the internet and a computer as there was no mobile access. This is a known limitation of web-based, non-probability sampling that affects social surveys and the researchers are aware of it.  \n\nAs for the health section the bias is less clear here, but the health results show similar patterns because higher-educated people are both more likely to report Good health and more likely to participate in online surveys, creating a \"double selection\" effect. \n\n# 6.0 Family size vs Politics in USA and Poland \n\nYou might have heard in politics and online that right-wing politics is family oriented and conservatives have larger families with more children. This is a common claim but is there empirical evidence to back it up?\n\nIn the United States researchers have found that right-leaning individuals tend to have larger families and more children than their left-leaning counterparts, with evidence spanning multiple decades and geographic regions. Republican leaning high-school seniors from 1989-2019 desired more children than their Democrat leaning peers. \n\nAs for actual statistics of childbirth between Republican and Democrat states. Analysis of U.S. birth rates reveals that 100 conservative adults raise 208 children on average, compared to 147 for democrats this is a 41% gap which is very significant. Post-2016, Republican-majority counties saw 7,000 more births than expected, while Democratic counties had 38,000 fewer. \n\nThere is substantial evidence to conclude that Republican states should have larger families with more children than their Democrat counterparts, but does this track in the KINMATRIX data. \n\n### 6.1 Republican and Democrat States\n\nThe way in which KINMATRIX categorizes US states is in regions. The regions are New England, South Atlantic, Mid-Atlantic, East South Central, East North Central, Pacific, West South Central, Mountain, and West North Central. Based on these regions and the Cook Partisan Voting Index (PVI). \n\nThe Democrat regions are: \n\n* New England (CT, MA, ME, NH, RI, VT)',\n* Pacific (AK, CA, HI, OR, WA)',\n* Mid-Atlantic (NJ, NY, DE, PA)',\n* East North Central (IL, IN, MI, OH, WI)' \n\nThe Republican Regions are: \n\n* East South Central (AL, KY, MS, TN)',\n* West South Central (AR, LA, OK, TX)',\n* West North Central (IA, KS, MN, MO, NE, ND, SD)',\n* Mountain (AZ, CO, ID, MT, NV, NM, UT, WY)',\n* South Atlantic (FL, GA, MD, NC, SC, VA, WV, DC)'\n\nThe output of this code block will be the average size of families in these regions. \n\n::: {#6904215e .cell execution_count=13}\n``` {.python .cell-code}\n# Extract US data from country_dfs and make a proper copy\nus_data = country_dfs['10. USA'].copy()  \n\n# Map region names to political lean\ndemocrat_regions = [\n    '5. New England (CT, MA, ME, NH, RI, VT)',\n    '6. Pacific (AK, CA, HI, OR, WA)',\n    '3. Mid-Atlantic (NJ, NY, DE, PA)',\n    '1. East North Central (IL, IN, MI, OH, WI)'\n]\n\nrepublican_regions = [\n    '2. East South Central (AL, KY, MS, TN)',\n    '9. West South Central (AR, LA, OK, TX)',\n    '8. West North Central (IA, KS, MN, MO, NE, ND, SD)',\n    '4. Mountain (AZ, CO, ID, MT, NV, NM, UT, WY)',\n    '7. South Atlantic (FL, GA, MD, NC, SC, VA, WV, DC)'\n]\n\n# Define color map for main relationship types\nrelationship_colors = {\n    'father': 'blue',\n    'mother': 'pink',\n    'brother': 'green',\n    'sister': 'purple',\n    'aunt': 'orange',\n    'uncle': 'brown',\n    'cousin': 'teal',\n    'grandfather': 'navy',\n    'grandmother': 'magenta',\n    'son': 'red',\n    'daughter': 'yellow',\n    'nephew': 'lightgreen',\n    'niece': 'lightpink',\n    'stepfather': 'slateblue',\n    'stepmother': 'plum',\n    'other': 'gray',\n}\n\n# Assign group based on region\ndef assign_state_group(region):\n    if region in democrat_regions:\n        return 'Democrat'\n    elif region in republican_regions:\n        return 'Republican'\n    else:\n        return 'Other'\n\n# Define relationship extraction function\ndef extract_relation(rel_str):\n    if not isinstance(rel_str, str):\n        return 'other'\n    rel_str = rel_str.lower()\n    rel_str = re.sub(r'^\\d+\\.\\s*', '', rel_str)\n    for key in relationship_colors.keys():\n        if key in rel_str:\n            return key\n    return 'other'\n\n# Apply transformations\nus_data['state_group'] = us_data['anc_regus'].apply(assign_state_group)\nus_data['relation'] = us_data['kin_typ'].apply(extract_relation)\n\n\ndef calculate_metrics(group_data):\n    kin_counts = group_data.groupby('anc_id').size()\n    avg_kin = kin_counts.mean() if not kin_counts.empty else 0\n    \n    children = group_data[group_data['relation'].isin(['son', 'daughter'])]\n    children_count = children.groupby('anc_id').size()\n    avg_children = children_count.mean() if not children_count.empty else 0\n    \n    cluster_sizes = kin_counts + 1  # Anchor + kin count\n    avg_cluster_size = cluster_sizes.mean() if not cluster_sizes.empty else 0\n    return avg_kin, avg_children, avg_cluster_size\n\n# Calculate results\nresults = {}\nfor group in ['Republican', 'Democrat']:\n    group_data = us_data[us_data['state_group'] == group]\n    avg_kin, avg_children, avg_cluster_size = calculate_metrics(group_data)\n    results[group] = {\n        'avg_kin_per_anchor': avg_kin,\n        'avg_children_per_anchor': avg_children,\n        'avg_cluster_size': avg_cluster_size\n    }\n\n# Overall in the US\navg_kin, avg_children, avg_cluster_size = calculate_metrics(us_data)\nresults['Overall US'] = {\n    'avg_kin_per_anchor': avg_kin,\n    'avg_children_per_anchor': avg_children,\n    'avg_cluster_size': avg_cluster_size\n}\n\n# print results\nfor group, metrics in results.items():\n    print(f\"{group} Regions:\")\n    print(f\"  Avg kin per anchor: {metrics['avg_kin_per_anchor']:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRepublican Regions:\n  Avg kin per anchor: 23.91\nDemocrat Regions:\n  Avg kin per anchor: 22.33\nOverall US Regions:\n  Avg kin per anchor: 22.72\n```\n:::\n:::\n\n\nThe main findings are consistent with the theory discussed above. From the KINMATRIX data of the 118,702 Nodes in the United States. Republican regions on average have larger families of 23.91 versus 22.33 in Democrat regions. This is a difference of 1.58. \n\n### 6.2 Politics for Poland \n\nThe administrative Regions for Poland in KINMATRIX is voivodeships. There are 16 voivodeships in Poland and they are the largest administrative regions similar to provinces in Canada. \n\n![Map of Polish voivodeships](media/wojewodstwa.png)\n\nLet's see if this tracks across countries and is not just a phenomenon present in the United States. Poland politically is a similarly divided nation with the more Eastern and Southern regions preferring conservative candidates and the Western and Northern regions preferring more liberal candidates. Below is displayed a Map of the 2023 Polish Parliamentary elections. \n\n![Map of the 2023 Polish Parliamentary elections (For Sejm and Senate)](media/2023_poland.jpg) \n\nThe Polish presidential Election had its second round on June 1, 2025 and this is the map of the election. \n\n![Map of this Presidential Election](media/2025_poland.webp) \n\nThis general trend of political allegiance has been around since Poland became independent from the USSR in 1989. Following the analysis in the United States using the Polish election results over the last 20 years the four most left-leaning voivodeships are: Mazowieckie (Warsaw), Pomorskie (Gdansk/Tri-city), Wielkopolskie (Poznan) and Zachodniopomorskie (Szczeczin). The four most right-leaning voivodeships are: Podkarpackie (Rzeszow/Przemysl) Lubelskie (Lublin), Podlaskie (Bialystok), and Świętokrzyskie (Kielce). We will repeat the analysis for the United States with these eight voivodeships.\n\n::: {#a69b649e .cell execution_count=14}\n``` {.python .cell-code}\npoland_df = country_dfs['3. Poland'].copy()\n\n# Define left-leaning and right-leaning voivodeships\nleft_leaning_voivodeships = [\n    '7. Mazowieckie',  # Warsaw\n    '11. Pomorskie',   # Gdansk/Tri-city\n    '15. Wielkopolskie',  # Poznan\n    '16. Zachodnio-Pomorskie'  # Szczeczin\n]\nright_leaning_voivodeships = [\n    '9. Podkarpackie',  # Rzeszow/Przemysl\n    '4. Lubelskie',     # Lublin\n    '10. Podlaskie',    # Bialystok\n    '13. Swietokrzyskie'  # Kielce\n]\n\n# Assign political group\ndef assign_voivodeship_group(voiv):\n    if voiv in left_leaning_voivodeships:\n        return 'Left-leaning'\n    elif voiv in right_leaning_voivodeships:\n        return 'Right-leaning'\n    else:\n        return 'Other'\npoland_df['voivodeship_group'] = poland_df['anc_regpl'].apply(assign_voivodeship_group)\n\n# Relationship normalization\nrelationship_colors = {\n    'father': 'blue',\n    'mother': 'pink',\n    'brother': 'green',\n    'sister': 'purple',\n    'aunt': 'orange',\n    'uncle': 'brown',\n    'cousin': 'teal',\n    'grandfather': 'navy',\n    'grandmother': 'magenta',\n    'son': 'red',\n    'daughter': 'yellow',\n    'nephew': 'lightgreen',\n    'niece': 'lightpink',\n    'stepfather': 'slateblue',\n    'stepmother': 'plum',\n    'other': 'gray',\n}\ndef extract_relation_pl(rel_str):\n    if not isinstance(rel_str, str):\n        return 'other'\n    rel_str = rel_str.lower()\n    rel_str = re.sub(r'^\\d+\\.\\s*', '', rel_str)\n    for key in relationship_colors.keys():\n        if key in rel_str:\n            return key\n    return 'other'\npoland_df['relation'] = poland_df['kin_typ'].apply(extract_relation_pl)\n\n# Metrics calculation\ndef calculate_metrics_pl(group_data):\n    kin_counts = group_data.groupby('anc_id').size()\n    avg_kin = kin_counts.mean() if not kin_counts.empty else 0\n    children = group_data[group_data['relation'].isin(['son', 'daughter'])]\n    children_count = children.groupby('anc_id').size()\n    avg_children = children_count.mean() if not children_count.empty else 0\n    cluster_sizes = kin_counts + 1  # Anchor + kin count\n    avg_cluster_size = cluster_sizes.mean() if not cluster_sizes.empty else 0\n    return avg_kin, avg_children, avg_cluster_size\n\n# Calculate and print results\nresults_pl = {}\nfor group in ['Right-leaning', 'Left-leaning']:\n    group_data = poland_df[poland_df['voivodeship_group'] == group]\n    avg_kin, avg_children, avg_cluster_size = calculate_metrics_pl(group_data)\n    results_pl[group] = {\n        'avg_kin_per_anchor': avg_kin,\n        'avg_children_per_anchor': avg_children,\n        'avg_cluster_size': avg_cluster_size\n    }\n\n# Overall Poland\navg_kin, avg_children, avg_cluster_size = calculate_metrics_pl(poland_df)\nresults_pl['Overall Poland'] = {\n    'avg_kin_per_anchor': avg_kin,\n    'avg_children_per_anchor': avg_children,\n    'avg_cluster_size': avg_cluster_size\n}\n\n# Print results\nfor group, metrics in results_pl.items():\n    print(f\"{group} Voivodeships:\")\n    print(f\"  Avg kin per anchor: {metrics['avg_kin_per_anchor']:.2f}\")\n    #print(f\"  Avg cluster size: {metrics['avg_cluster_size']:.2f}\")\n    print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRight-leaning Voivodeships:\n  Avg kin per anchor: 20.85\n\nLeft-leaning Voivodeships:\n  Avg kin per anchor: 18.54\n\nOverall Poland Voivodeships:\n  Avg kin per anchor: 19.01\n\n```\n:::\n:::\n\n\nJust like with the United States the trend of right-leaning Voivodeships having larger families is true. The average kin per anchor in left-leaning regions is 18.54 and in right-leaning regions is 20.85 a difference of 2.31 which is larger than the 1.58 in the United States. \n\nWe should also test if these results are significant. To do this we will use a t-test which you may be familiar with from any introductory statistics class like STATS 200. A t-test measures the difference between the means of two groups, taking into account the variability within those groups. It helps determine if the observed difference is statistically significant, meaning it's unlikely to have occurred by random chance. \n\n### 6.3 Significance of these findings \n\nWe will first do our $t$-test for the United States. \n\n::: {#1487bd2a .cell execution_count=15}\n``` {.python .cell-code}\nfrom scipy import stats #library with statistical functions like t-test\n\n# Extract US data from country_dfs and make a proper copy\nus_data = country_dfs['10. USA'].copy()\n\n# Map region names to political lean\ndemocrat_regions = [\n    '5. New England (CT, MA, ME, NH, RI, VT)',\n    '6. Pacific (AK, CA, HI, OR, WA)',\n    '3. Mid-Atlantic (NJ, NY, DE, PA)',\n    '1. East North Central (IL, IN, MI, OH, WI)'\n]\n\nrepublican_regions = [\n    '2. East South Central (AL, KY, MS, TN)',\n    '9. West South Central (AR, LA, OK, TX)',\n    '8. West North Central (IA, KS, MN, MO, NE, ND, SD)',\n    '4. Mountain (AZ, CO, ID, MT, NV, NM, UT, WY)',\n    '7. South Atlantic (FL, GA, MD, NC, SC, VA, WV, DC)'\n]\n\n# Assign group based on region\ndef assign_state_group(region):\n    if region in democrat_regions:\n        return 'Democrat'\n    elif region in republican_regions:\n        return 'Republican'\n    else:\n        return 'Other'\n\n# Apply transformation\nus_data['state_group'] = us_data['anc_regus'].apply(assign_state_group)\n\n# Calculate kin counts per anchor for each political group\nrepublican_kin_counts = us_data[us_data['state_group'] == 'Republican'].groupby('anc_id').size()\ndemocrat_kin_counts = us_data[us_data['state_group'] == 'Democrat'].groupby('anc_id').size()\n\n# Perform t-test for US data\nus_t_stat, us_p_value = stats.ttest_ind(republican_kin_counts, democrat_kin_counts)\n\nprint(f\"Republican regions - Sample size: {len(republican_kin_counts)}\")\nprint(f\"Republican regions - Mean kin per anchor: {republican_kin_counts.mean():.2f}\")\nprint(f\"Republican regions - Std deviation: {republican_kin_counts.std():.2f}\")\nprint()\nprint(f\"Democrat regions - Sample size: {len(democrat_kin_counts)}\")\nprint(f\"Democrat regions - Mean kin per anchor: {democrat_kin_counts.mean():.2f}\")\nprint(f\"Democrat regions - Std deviation: {democrat_kin_counts.std():.2f}\")\nprint()\nprint(f\"T-statistic: {us_t_stat:.4f}\")\nprint(f\"P-value: {us_p_value:.6f}\")\nprint(f\"Significant at α=0.05: {'Yes' if us_p_value < 0.05 else 'No'}\") # main findings to be easy for students\nprint(f\"Significant at α=0.01: {'Yes' if us_p_value < 0.01 else 'No'}\") # main findings to be easy for students\nprint()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRepublican regions - Sample size: 1685\nRepublican regions - Mean kin per anchor: 23.91\nRepublican regions - Std deviation: 12.85\n\nDemocrat regions - Sample size: 2314\nDemocrat regions - Mean kin per anchor: 22.33\nDemocrat regions - Std deviation: 11.67\n\nT-statistic: 4.0600\nP-value: 0.000050\nSignificant at α=0.05: Yes\nSignificant at α=0.01: Yes\n\n```\n:::\n:::\n\n\nWe find that for the United States both the Democrat and Republican leaning regions have a large sample size and our findings are significant at both 95% and 99% Confidence Intervals meaning that they are likely not caused by random coincidence.  \n\nLet's see if this trend continues in Poland. \n\n::: {#b7d337f0 .cell execution_count=16}\n``` {.python .cell-code}\npoland_df = country_dfs['3. Poland'].copy()\n\n# Define left-leaning and right-leaning voivodeships\nleft_leaning_voivodeships = [\n    '7. Mazowieckie',  # Warsaw\n    '11. Pomorskie',   # Gdansk/Tri-city\n    '15. Wielkopolskie',  # Poznan\n    '16. Zachodnio-Pomorskie'  # Szczeczin\n]\n\nright_leaning_voivodeships = [\n    '9. Podkarpackie',  # Rzeszow/Przemysl\n    '4. Lubelskie',     # Lublin\n    '10. Podlaskie',    # Bialystok\n    '13. Swietokrzyskie'  # Kielce\n]\n\n# Assign political group\ndef assign_voivodeship_group(voiv):\n    if voiv in left_leaning_voivodeships:\n        return 'Left-leaning'\n    elif voiv in right_leaning_voivodeships:\n        return 'Right-leaning'\n    else:\n        return 'Other'\n\npoland_df['voivodeship_group'] = poland_df['anc_regpl'].apply(assign_voivodeship_group)\n\n# Calculate kin counts per anchor for each political group\nright_kin_counts = poland_df[poland_df['voivodeship_group'] == 'Right-leaning'].groupby('anc_id').size()\nleft_kin_counts = poland_df[poland_df['voivodeship_group'] == 'Left-leaning'].groupby('anc_id').size()\n\n# Perform t-test for Poland data\npoland_t_stat, poland_p_value = stats.ttest_ind(right_kin_counts, left_kin_counts)\n\nprint(f\"Right-leaning voivodeships - Sample size: {len(right_kin_counts)}\")\nprint(f\"Right-leaning voivodeships - Mean kin per anchor: {right_kin_counts.mean():.2f}\")\nprint(f\"Right-leaning voivodeships - Std deviation: {right_kin_counts.std():.2f}\")\nprint()\nprint(f\"Left-leaning voivodeships - Sample size: {len(left_kin_counts)}\")\nprint(f\"Left-leaning voivodeships - Mean kin per anchor: {left_kin_counts.mean():.2f}\")\nprint(f\"Left-leaning voivodeships - Std deviation: {left_kin_counts.std():.2f}\")\nprint()\nprint(f\"T-statistic: {poland_t_stat:.4f}\")\nprint(f\"P-value: {poland_p_value:.6f}\")\nprint(f\"Significant at α=0.05: {'Yes' if poland_p_value < 0.05 else 'No'}\")\nprint(f\"Significant at α=0.01: {'Yes' if poland_p_value < 0.01 else 'No'}\")\nprint()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRight-leaning voivodeships - Sample size: 258\nRight-leaning voivodeships - Mean kin per anchor: 20.85\nRight-leaning voivodeships - Std deviation: 9.72\n\nLeft-leaning voivodeships - Sample size: 638\nLeft-leaning voivodeships - Mean kin per anchor: 18.54\nLeft-leaning voivodeships - Std deviation: 9.19\n\nT-statistic: 3.3489\nP-value: 0.000845\nSignificant at α=0.05: Yes\nSignificant at α=0.01: Yes\n\n```\n:::\n:::\n\n\nWe again find that for Poland both the left and right leaning regions have a large enough sample size and our findings are significant at both 95% and 99% Confidence Intervals. Because the research is biased towards educated people it makes sense that the right-leaning regions of Poland have a smaller sample size as most of the educated people will be in larger cities like Warsaw, Krakow or Gdansk (which are left-leaning). \n\nMore conservative regions in Poland have larger families by on average 2.31 people. This is even more significant than in the United States. \n\n### 6.4 Discussion\n\nFor the next part of the notebook turn to a person next to you and discuss these findings. Why do these more conservative regions have larger families is it just more \"traditional values,\" or is there something more? Use the frameworks discussed in class. This will be easier for the United States as people are more familiar with politics and life in the United States. But also try for Poland; this will be more difficult. \n\n# 7.0 Employment and Education in Poland\n\nIn this section, we analyze the regional patterns of education, employment, and health across the Polish voivodeships, using our data from the KINMATRIX dataset. By summarizing key demographic statistics for each region, we can assess how the socioeconomic landscape of Poland corresponds to established trends we take for granted in theory (for example: larger cities are more educated and have higher employment rates). \n\n![Map of Polish voivodeships](media/wojewodstwa.png)\n\nThe cell below will filter the dataset for Poland and loop through all the voivodeships. \n\n::: {#532a923e .cell execution_count=17}\n``` {.python .cell-code}\n# Filter for Poland\npoland_df = df[df['anc_cou'] == '3. Poland']\n\n# Get unique voivodeships\nvoivodeships = poland_df['anc_regpl'].dropna().unique()\n\n# Loop through all voivodeships\nfor voiv in voivodeships:\n    voiv_df = poland_df[poland_df['anc_regpl'] == voiv]\n    print(f\"Voivodeship: {voiv}, Number of Anchor Nodes: {len(voiv_df)}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nVoivodeship: 12. Slaskie, Number of Anchor Nodes: 3398\nVoivodeship: 1. Dolnoslaskie, Number of Anchor Nodes: 2659\nVoivodeship: 11. Pomorskie, Number of Anchor Nodes: 2291\nVoivodeship: 7. Mazowieckie, Number of Anchor Nodes: 5033\nVoivodeship: 9. Podkarpackie, Number of Anchor Nodes: 1829\nVoivodeship: 3. Lódzkie, Number of Anchor Nodes: 1747\nVoivodeship: 6. Malopolskie, Number of Anchor Nodes: 3486\nVoivodeship: 5. Lubuskie, Number of Anchor Nodes: 857\nVoivodeship: 13. Swietokrzyskie, Number of Anchor Nodes: 864\nVoivodeship: 2. Kujawsko-Pomorskie, Number of Anchor Nodes: 1902\nVoivodeship: 16. Zachodnio-Pomorskie, Number of Anchor Nodes: 1001\nVoivodeship: 15. Wielkopolskie, Number of Anchor Nodes: 3503\nVoivodeship: 10. Podlaskie, Number of Anchor Nodes: 1013\nVoivodeship: 4. Lubelskie, Number of Anchor Nodes: 1673\nVoivodeship: 14. Warminsko-Mazurskie, Number of Anchor Nodes: 1044\nVoivodeship: 8. Opolskie, Number of Anchor Nodes: 626\n```\n:::\n:::\n\n\nFrom the cell below we will get all of our summary statistics for each voivodeship. \n\n::: {#413e843e .cell execution_count=18}\n``` {.python .cell-code}\n# List of variables\nsummary_vars = {\n    'education': 'anc_eduall',                # Education (all countries)\n    'education_poland': 'anc_edupl',          # Education (Poland-specific)\n    'sexual_orientation': 'anc_sor',          # Sexual orientation\n    'gender': 'anc_gnd',                      # Gender\n    'income': 'anc_sss',                      # Subjective social status (income proxy)\n    'age': 'anc_age',                         # Age\n    'region': 'anc_regpl',                    # Voivodeship (region)\n    'ethnicity': 'anc_eth',                   # Ethnicity\n    'religion1': 'anc_rel1',                  # Religion (dummy for religious)\n    'religion2': 'anc_rel2',                  # Religion (which religion)\n    'religion3': 'anc_rel3',                  # Religion (frequency/attendance)\n    'employment': 'anc_emp',                  # Employment status\n    'health': 'anc_hea',                      # Health\n    'parental_separation': 'par_sep'          # Parental separation\n}\n\ndef summarize_voivodeship(voiv_df):\n    stats = {}\n    # Network construction\n    G = nx.Graph()\n    for idx, row in voiv_df.iterrows():\n        G.add_node(row['anc_id'], age=row['anc_age'], gender=row['anc_gnd'])\n        kin_node = f\"{row['anc_id']}_{row.get('kin_nam', 'unknown')}_{idx}\"\n        G.add_node(kin_node, relation=row.get('kin_typ', None))\n        G.add_edge(row['anc_id'], kin_node)\n    stats['nodes'] = G.number_of_nodes()\n    stats['edges'] = G.number_of_edges()\n    stats['density'] = nx.density(G)\n    degrees = [deg for node, deg in G.degree()]\n    stats['mean_degree'] = np.mean(degrees) if degrees else 0\n\n    # Demographic summaries\n    for label, var in summary_vars.items():\n        value_counts = voiv_df[var].value_counts(dropna=False)\n        stats[label] = value_counts.to_dict()\n    return stats\n\n# Filter for Poland and get unique voivodeships\npoland_df = df[df['anc_cou'] == '3. Poland']\nvoivodeships = poland_df['anc_regpl'].dropna().unique()\n\n# Loop through voivodeships and print summary\nfor voiv in voivodeships:\n    voiv_df = poland_df[poland_df['anc_regpl'] == voiv]\n    stats = summarize_voivodeship(voiv_df)\n    print(f\"\\nVoivodeship: {voiv}\")\n    print(f\"  Nodes: {stats['nodes']}\")\n    #print(f\"  Edges: {stats['edges']}\")\n    #print(f\"  Mean degree: {stats['mean_degree']:.2f}\")\n    print(f\"  Education (all): {stats['education']}\")\n    print(f\"  Education (Poland): {stats['education_poland']}\")\n    #print(f\"  Sexual orientation: {stats['sexual_orientation']}\")\n    #print(f\"  Gender: {stats['gender']}\")\n    #print(f\"  Income (subjective social status): {stats['income']}\")\n    #print(f\"  Age: {stats['age']}\")\n    #print(f\"  Region: {stats['region']}\")\n    #print(f\"  Ethnicity: {stats['ethnicity']}\")\n    #print(f\"  Religion 1: {stats['religion1']}\")\n    #print(f\"  Religion 2: {stats['religion2']}\")\n    #print(f\"  Religion 3: {stats['religion3']}\")\n    print(f\"  Employment: {stats['employment']}\")\n    print(f\"  Health: {stats['health']}\")\n    #print(f\"  Parental separation: {stats['parental_separation']}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nVoivodeship: 12. Slaskie\n  Nodes: 3592\n  Education (all): {'3. High': 1864, '2. Mid': 1120, '1. Low': 374, '-2. Prefer not to answer': 40}\n  Education (Poland): {'6. Postgraduate education': 1171, '2. Secondary education': 1049, '5. University education': 525, '1. Incomplete secondary education': 374, '4. Vocational or professional certification': 168, '3. Some university or vocational certification': 71, '-2. Prefer not to answer': 40, '-3. Does not apply': 0, '7. Doctorate, post-doctorate or equivalent': 0}\n  Employment: {'1. Full-time employed': 2453, '2. Part-time employed': 245, '4. Unemployed': 234, '6. Homemaker and/or Caretaker': 207, '3. Self-employed': 145, '8. Permanently sick or disabled': 61, '9. Other': 42, '5. In education': 11, '7. Retired': 0}\n  Health: {'2. Good': 1666, '3. Fair': 1061, '1. Very good': 392, '4. Bad': 205, '5. Very bad': 48, \"-1. Don't know\": 26, '-2. No answer': 0}\n\nVoivodeship: 1. Dolnoslaskie\n  Nodes: 2808\n  Education (all): {'3. High': 1718, '2. Mid': 643, '1. Low': 286, '-2. Prefer not to answer': 12}\n  Education (Poland): {'6. Postgraduate education': 1016, '5. University education': 529, '2. Secondary education': 481, '1. Incomplete secondary education': 286, '3. Some university or vocational certification': 162, '4. Vocational or professional certification': 138, '7. Doctorate, post-doctorate or equivalent': 35, '-2. Prefer not to answer': 12, '-3. Does not apply': 0}\n  Employment: {'1. Full-time employed': 2110, '4. Unemployed': 267, '3. Self-employed': 164, '2. Part-time employed': 57, '6. Homemaker and/or Caretaker': 35, '5. In education': 17, '9. Other': 9, '7. Retired': 0, '8. Permanently sick or disabled': 0}\n  Health: {'2. Good': 1492, '3. Fair': 531, '1. Very good': 441, '4. Bad': 142, \"-1. Don't know\": 53, '-2. No answer': 0, '5. Very bad': 0}\n\nVoivodeship: 11. Pomorskie\n  Nodes: 2414\n  Education (all): {'3. High': 1473, '2. Mid': 661, '1. Low': 157, '-2. Prefer not to answer': 0}\n  Education (Poland): {'6. Postgraduate education': 791, '2. Secondary education': 573, '5. University education': 502, '1. Incomplete secondary education': 157, '4. Vocational or professional certification': 141, '3. Some university or vocational certification': 88, '7. Doctorate, post-doctorate or equivalent': 39, '-3. Does not apply': 0, '-2. Prefer not to answer': 0}\n  Employment: {'1. Full-time employed': 1709, '6. Homemaker and/or Caretaker': 211, '4. Unemployed': 131, '2. Part-time employed': 104, '9. Other': 47, '5. In education': 46, '3. Self-employed': 43, '7. Retired': 0, '8. Permanently sick or disabled': 0}\n  Health: {'2. Good': 1378, '3. Fair': 584, '1. Very good': 265, '4. Bad': 43, \"-1. Don't know\": 21, '-2. No answer': 0, '5. Very bad': 0}\n\nVoivodeship: 7. Mazowieckie\n  Nodes: 5317\n  Education (all): {'3. High': 3532, '2. Mid': 1186, '1. Low': 315, '-2. Prefer not to answer': 0}\n  Education (Poland): {'6. Postgraduate education': 2309, '5. University education': 1030, '2. Secondary education': 913, '1. Incomplete secondary education': 315, '3. Some university or vocational certification': 273, '4. Vocational or professional certification': 135, '7. Doctorate, post-doctorate or equivalent': 58, '-3. Does not apply': 0, '-2. Prefer not to answer': 0}\n  Employment: {'1. Full-time employed': 3757, '3. Self-employed': 383, '2. Part-time employed': 334, '6. Homemaker and/or Caretaker': 185, '4. Unemployed': 135, '5. In education': 110, '9. Other': 93, '7. Retired': 23, '8. Permanently sick or disabled': 13}\n  Health: {'2. Good': 2643, '3. Fair': 1526, '1. Very good': 651, '4. Bad': 134, \"-1. Don't know\": 66, '-2. No answer': 13, '5. Very bad': 0}\n\nVoivodeship: 9. Podkarpackie\n  Nodes: 1912\n  Education (all): {'3. High': 1224, '2. Mid': 501, '1. Low': 104, '-2. Prefer not to answer': 0}\n  Education (Poland): {'6. Postgraduate education': 638, '5. University education': 535, '2. Secondary education': 364, '3. Some university or vocational certification': 137, '1. Incomplete secondary education': 104, '4. Vocational or professional certification': 51, '-3. Does not apply': 0, '-2. Prefer not to answer': 0, '7. Doctorate, post-doctorate or equivalent': 0}\n  Employment: {'1. Full-time employed': 1380, '4. Unemployed': 161, '5. In education': 78, '3. Self-employed': 71, '6. Homemaker and/or Caretaker': 69, '2. Part-time employed': 57, '9. Other': 13, '7. Retired': 0, '8. Permanently sick or disabled': 0}\n  Health: {'2. Good': 1108, '3. Fair': 565, '1. Very good': 130, '5. Very bad': 15, '4. Bad': 11, \"-1. Don't know\": 0, '-2. No answer': 0}\n\nVoivodeship: 3. Lódzkie\n  Nodes: 1851\n  Education (all): {'3. High': 1067, '2. Mid': 530, '1. Low': 126, '-2. Prefer not to answer': 24}\n  Education (Poland): {'6. Postgraduate education': 593, '2. Secondary education': 497, '5. University education': 339, '4. Vocational or professional certification': 128, '1. Incomplete secondary education': 126, '3. Some university or vocational certification': 33, '-2. Prefer not to answer': 24, '7. Doctorate, post-doctorate or equivalent': 7, '-3. Does not apply': 0}\n  Employment: {'1. Full-time employed': 1251, '4. Unemployed': 182, '3. Self-employed': 170, '6. Homemaker and/or Caretaker': 51, '8. Permanently sick or disabled': 50, '2. Part-time employed': 24, '5. In education': 19, '7. Retired': 0, '9. Other': 0}\n  Health: {'2. Good': 844, '3. Fair': 473, '1. Very good': 226, '4. Bad': 204, '-2. No answer': 0, \"-1. Don't know\": 0, '5. Very bad': 0}\n\nVoivodeship: 6. Malopolskie\n  Nodes: 3663\n  Education (all): {'3. High': 2566, '2. Mid': 754, '1. Low': 136, '-2. Prefer not to answer': 30}\n  Education (Poland): {'6. Postgraduate education': 1650, '5. University education': 691, '2. Secondary education': 569, '3. Some university or vocational certification': 185, '4. Vocational or professional certification': 173, '1. Incomplete secondary education': 136, '7. Doctorate, post-doctorate or equivalent': 52, '-2. Prefer not to answer': 30, '-3. Does not apply': 0}\n  Employment: {'1. Full-time employed': 2536, '6. Homemaker and/or Caretaker': 305, '3. Self-employed': 236, '2. Part-time employed': 210, '4. Unemployed': 153, '5. In education': 33, '7. Retired': 13, '8. Permanently sick or disabled': 0, '9. Other': 0}\n  Health: {'2. Good': 1791, '3. Fair': 1148, '1. Very good': 378, '4. Bad': 96, \"-1. Don't know\": 37, '5. Very bad': 36, '-2. No answer': 0}\n\nVoivodeship: 5. Lubuskie\n  Nodes: 901\n  Education (all): {'3. High': 448, '1. Low': 177, '2. Mid': 170, '-2. Prefer not to answer': 62}\n  Education (Poland): {'5. University education': 253, '1. Incomplete secondary education': 177, '6. Postgraduate education': 172, '2. Secondary education': 120, '-2. Prefer not to answer': 62, '3. Some university or vocational certification': 50, '4. Vocational or professional certification': 23, '-3. Does not apply': 0, '7. Doctorate, post-doctorate or equivalent': 0}\n  Employment: {'1. Full-time employed': 564, '4. Unemployed': 108, '6. Homemaker and/or Caretaker': 101, '2. Part-time employed': 32, '8. Permanently sick or disabled': 24, '3. Self-employed': 16, '5. In education': 12, '7. Retired': 0, '9. Other': 0}\n  Health: {'2. Good': 469, '3. Fair': 301, '4. Bad': 51, '1. Very good': 24, '5. Very bad': 12, \"-1. Don't know\": 0, '-2. No answer': 0}\n\nVoivodeship: 13. Swietokrzyskie\n  Nodes: 906\n  Education (all): {'3. High': 462, '2. Mid': 360, '1. Low': 42, '-2. Prefer not to answer': 0}\n  Education (Poland): {'2. Secondary education': 301, '6. Postgraduate education': 257, '5. University education': 176, '3. Some university or vocational certification': 59, '1. Incomplete secondary education': 42, '4. Vocational or professional certification': 20, '7. Doctorate, post-doctorate or equivalent': 9, '-3. Does not apply': 0, '-2. Prefer not to answer': 0}\n  Employment: {'1. Full-time employed': 566, '2. Part-time employed': 93, '6. Homemaker and/or Caretaker': 82, '3. Self-employed': 56, '9. Other': 47, '4. Unemployed': 11, '5. In education': 9, '7. Retired': 0, '8. Permanently sick or disabled': 0}\n  Health: {'2. Good': 459, '3. Fair': 236, '1. Very good': 169, \"-1. Don't know\": 0, '-2. No answer': 0, '4. Bad': 0, '5. Very bad': 0}\n\nVoivodeship: 2. Kujawsko-Pomorskie\n  Nodes: 1992\n  Education (all): {'3. High': 1171, '2. Mid': 489, '1. Low': 225, '-2. Prefer not to answer': 17}\n  Education (Poland): {'5. University education': 544, '6. Postgraduate education': 532, '2. Secondary education': 437, '1. Incomplete secondary education': 225, '4. Vocational or professional certification': 95, '3. Some university or vocational certification': 52, '-2. Prefer not to answer': 17, '-3. Does not apply': 0, '7. Doctorate, post-doctorate or equivalent': 0}\n  Employment: {'1. Full-time employed': 1100, '4. Unemployed': 337, '6. Homemaker and/or Caretaker': 175, '2. Part-time employed': 161, '5. In education': 59, '3. Self-employed': 44, '9. Other': 26, '7. Retired': 0, '8. Permanently sick or disabled': 0}\n  Health: {'2. Good': 919, '3. Fair': 551, '1. Very good': 319, '4. Bad': 96, '5. Very bad': 17, \"-1. Don't know\": 0, '-2. No answer': 0}\n\nVoivodeship: 16. Zachodnio-Pomorskie\n  Nodes: 1056\n  Education (all): {'3. High': 544, '2. Mid': 334, '1. Low': 111, '-2. Prefer not to answer': 12}\n  Education (Poland): {'2. Secondary education': 277, '6. Postgraduate education': 238, '5. University education': 202, '1. Incomplete secondary education': 111, '7. Doctorate, post-doctorate or equivalent': 73, '3. Some university or vocational certification': 57, '4. Vocational or professional certification': 31, '-2. Prefer not to answer': 12, '-3. Does not apply': 0}\n  Employment: {'1. Full-time employed': 738, '2. Part-time employed': 128, '4. Unemployed': 86, '8. Permanently sick or disabled': 22, '5. In education': 15, '9. Other': 12, '3. Self-employed': 0, '7. Retired': 0, '6. Homemaker and/or Caretaker': 0}\n  Health: {'2. Good': 599, '3. Fair': 269, '1. Very good': 111, \"-1. Don't know\": 22, '-2. No answer': 0, '4. Bad': 0, '5. Very bad': 0}\n\nVoivodeship: 15. Wielkopolskie\n  Nodes: 3679\n  Education (all): {'3. High': 2160, '2. Mid': 1088, '1. Low': 218, '-2. Prefer not to answer': 37}\n  Education (Poland): {'6. Postgraduate education': 1321, '2. Secondary education': 897, '5. University education': 750, '1. Incomplete secondary education': 218, '3. Some university or vocational certification': 191, '4. Vocational or professional certification': 65, '-2. Prefer not to answer': 37, '7. Doctorate, post-doctorate or equivalent': 24, '-3. Does not apply': 0}\n  Employment: {'1. Full-time employed': 2626, '4. Unemployed': 272, '2. Part-time employed': 242, '9. Other': 118, '3. Self-employed': 96, '6. Homemaker and/or Caretaker': 60, '5. In education': 57, '7. Retired': 32, '8. Permanently sick or disabled': 0}\n  Health: {'2. Good': 1987, '3. Fair': 921, '1. Very good': 400, '4. Bad': 100, '5. Very bad': 41, '-2. No answer': 36, \"-1. Don't know\": 18}\n\nVoivodeship: 10. Podlaskie\n  Nodes: 1063\n  Education (all): {'3. High': 612, '2. Mid': 302, '1. Low': 99, '-2. Prefer not to answer': 0}\n  Education (Poland): {'6. Postgraduate education': 421, '2. Secondary education': 266, '5. University education': 142, '1. Incomplete secondary education': 99, '4. Vocational or professional certification': 49, '3. Some university or vocational certification': 36, '-3. Does not apply': 0, '-2. Prefer not to answer': 0, '7. Doctorate, post-doctorate or equivalent': 0}\n  Employment: {'1. Full-time employed': 728, '4. Unemployed': 133, '3. Self-employed': 57, '6. Homemaker and/or Caretaker': 49, '2. Part-time employed': 46, '5. In education': 0, '7. Retired': 0, '8. Permanently sick or disabled': 0, '9. Other': 0}\n  Health: {'2. Good': 518, '3. Fair': 311, '1. Very good': 177, '4. Bad': 7, '-2. No answer': 0, \"-1. Don't know\": 0, '5. Very bad': 0}\n\nVoivodeship: 4. Lubelskie\n  Nodes: 1756\n  Education (all): {'3. High': 987, '2. Mid': 536, '1. Low': 137, '-2. Prefer not to answer': 13}\n  Education (Poland): {'6. Postgraduate education': 794, '2. Secondary education': 419, '1. Incomplete secondary education': 137, '3. Some university or vocational certification': 117, '5. University education': 111, '4. Vocational or professional certification': 82, '-2. Prefer not to answer': 13, '-3. Does not apply': 0, '7. Doctorate, post-doctorate or equivalent': 0}\n  Employment: {'1. Full-time employed': 1014, '2. Part-time employed': 191, '3. Self-employed': 177, '6. Homemaker and/or Caretaker': 162, '5. In education': 56, '8. Permanently sick or disabled': 50, '4. Unemployed': 23, '7. Retired': 0, '9. Other': 0}\n  Health: {'2. Good': 976, '3. Fair': 334, '1. Very good': 183, '4. Bad': 180, '-2. No answer': 0, \"-1. Don't know\": 0, '5. Very bad': 0}\n\nVoivodeship: 14. Warminsko-Mazurskie\n  Nodes: 1092\n  Education (all): {'2. Mid': 497, '3. High': 454, '1. Low': 93, '-2. Prefer not to answer': 0}\n  Education (Poland): {'2. Secondary education': 411, '6. Postgraduate education': 324, '1. Incomplete secondary education': 93, '3. Some university or vocational certification': 86, '5. University education': 67, '4. Vocational or professional certification': 47, '7. Doctorate, post-doctorate or equivalent': 16, '-3. Does not apply': 0, '-2. Prefer not to answer': 0}\n  Employment: {'1. Full-time employed': 779, '6. Homemaker and/or Caretaker': 131, '3. Self-employed': 107, '5. In education': 14, '4. Unemployed': 13, '2. Part-time employed': 0, '7. Retired': 0, '8. Permanently sick or disabled': 0, '9. Other': 0}\n  Health: {'2. Good': 584, '3. Fair': 298, '1. Very good': 94, '4. Bad': 55, '5. Very bad': 13, \"-1. Don't know\": 0, '-2. No answer': 0}\n\nVoivodeship: 8. Opolskie\n  Nodes: 656\n  Education (all): {'2. Mid': 296, '3. High': 264, '1. Low': 46, '-2. Prefer not to answer': 20}\n  Education (Poland): {'2. Secondary education': 270, '6. Postgraduate education': 219, '1. Incomplete secondary education': 46, '5. University education': 45, '3. Some university or vocational certification': 26, '-2. Prefer not to answer': 20, '-3. Does not apply': 0, '4. Vocational or professional certification': 0, '7. Doctorate, post-doctorate or equivalent': 0}\n  Employment: {'1. Full-time employed': 433, '3. Self-employed': 121, '6. Homemaker and/or Caretaker': 47, '2. Part-time employed': 14, '4. Unemployed': 11, '5. In education': 0, '7. Retired': 0, '8. Permanently sick or disabled': 0, '9. Other': 0}\n  Health: {'2. Good': 441, '1. Very good': 78, '3. Fair': 76, '4. Bad': 31, '-2. No answer': 0, \"-1. Don't know\": 0, '5. Very bad': 0}\n```\n:::\n:::\n\n\nWe will focus specifically on Education, Employment and Health. We will then contrast this information to the Polish Census and discuss why these differences exist very consistently across the voivodeships. If there are other variables which you are interested in like Age or Sexual orientation you can remove the **#** before the print command for it to show up in the cell output. \n\nWe have already looked at the variables education (all countries) and health, but it is a good habit to look at all variables. \n\nIn the code block below we will look at Employment (anc_emp) and Education Poland (anc_edupl) to examine the different levels these variables can take.  \n\n::: {#5237e92a .cell execution_count=19}\n``` {.python .cell-code}\n# Filter for Poland\npoland_df = df[df['anc_cou'] == '3. Poland']\n\n# Get unique values for Polish education levels\nedupl_levels = poland_df['anc_edupl'].dropna().unique()\n\n# Get unique values for employment levels\nemp_levels = poland_df['anc_emp'].dropna().unique()\n\nprint(\"Unique values for education_poland (anc_edupl):\")\nprint(edupl_levels)\n\nprint(\"\\nUnique values for employment (anc_emp):\")\nprint(emp_levels)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nUnique values for education_poland (anc_edupl):\n['2. Secondary education', '6. Postgraduate education', '1. Incomplete secondary education', '7. Doctorate, post-doctorate or equivalent', '5. University education', '3. Some university or vocational certification', '4. Vocational or professional certification', '-2. Prefer not to answer']\nCategories (9, object): ['-3. Does not apply' < '-2. Prefer not to answer' < '1. Incomplete secondary education' < '2. Secondary education' ... '4. Vocational or professional certification' < '5. University education' < '6. Postgraduate education' < '7. Doctorate, post-doctorate or equivalent']\n\nUnique values for employment (anc_emp):\n['1. Full-time employed', '2. Part-time employed', '4. Unemployed', '5. In education', '9. Other', '3. Self-employed', '6. Homemaker and/or Caretaker', '8. Permanently sick or disabled', '7. Retired']\nCategories (9, object): ['1. Full-time employed' < '2. Part-time employed' < '3. Self-employed' < '4. Unemployed' ... '6. Homemaker and/or Caretaker' < '7. Retired' < '8. Permanently sick or disabled' < '9. Other']\n```\n:::\n:::\n\n\nWe can already see a big difference between the variables education (all) and education (Poland). The education all variable just has qualitative levels (High, Medium, Low) while the Polish one has tangible levels like Postgraduate, Secondary School or Doctorate. This variable has an order which reflect the Polish Education system from incomplete secondary to the highest, doctorate/post-doctorate.\n\nThe employment variable also has clear levels like Full-time employed, Student or Unemployed. These categories are mutually exclusive and cover the main labor force statuses, reflecting employment, unemployment, studying, domestic and care work, retirement, and inability to work due to health.\n\nLet's go back to our original statistics from above the output of the cell above it is quite overwhelming, to make it easier we can sort from highest to smallest percentage.\n\n::: {#ed873868 .cell execution_count=20}\n``` {.python .cell-code}\nsummary_vars = {\n    'education': 'anc_eduall',\n    'education_poland': 'anc_edupl',\n    'sexual_orientation': 'anc_sor',\n    'gender': 'anc_gnd',\n    'income': 'anc_sss',\n    'age': 'anc_age',\n    'region': 'anc_regpl',\n    'ethnicity': 'anc_eth',\n    'religion1': 'anc_rel1',\n    'religion2': 'anc_rel2',\n    'religion3': 'anc_rel3',\n    'employment': 'anc_emp',\n    'health': 'anc_hea',\n    'parental_separation': 'par_sep'\n}\n\n# Filter for Poland and get unique voivodeships\npoland_df = df[df['anc_cou'] == '3. Poland']\nvoivodeships = poland_df['anc_regpl'].dropna().unique()\n\nsummary_results = {}\n\nfor voiv in voivodeships:\n    voiv_df = poland_df[poland_df['anc_regpl'] == voiv]\n    stats = {}\n    # Network construction\n    G = nx.Graph()\n    for idx, row in voiv_df.iterrows():\n        G.add_node(row['anc_id'], age=row['anc_age'], gender=row['anc_gnd'])\n        kin_node = f\"{row['anc_id']}_{row.get('kin_nam', 'unknown')}_{idx}\"\n        G.add_node(kin_node, relation=row.get('kin_typ', None))\n        G.add_edge(row['anc_id'], kin_node)\n    stats['nodes'] = G.number_of_nodes()\n    stats['edges'] = G.number_of_edges()\n    stats['density'] = nx.density(G)\n    degrees = [deg for node, deg in G.degree()]\n    stats['mean_degree'] = np.mean(degrees) if degrees else 0\n\n    # Demographic summaries\n    for label, var in summary_vars.items():\n        value_counts = voiv_df[var].value_counts(dropna=False)\n        stats[label] = value_counts.to_dict()\n    summary_results[voiv] = stats\n\nrows = []\nfor voiv, stats in summary_results.items():\n    # Education: % High\n    edu_counts = stats['education']\n    high = edu_counts.get('3. High', 0)\n    total_edu = sum([v for k, v in edu_counts.items() if isinstance(v, (int, float)) and k not in ['-2. Prefer not to answer']])\n    pct_high_edu = high / total_edu if total_edu else 0\n\n    # Employment: % Full-time or Part-time employed\n    emp_counts = stats['employment']\n    full_time = emp_counts.get('1. Full-time employed', 0)\n    part_time = emp_counts.get('2. Part-time employed', 0)\n    employed = full_time + part_time\n    total_emp = sum([v for k, v in emp_counts.items() if isinstance(v, (int, float))])\n    pct_employed = employed / total_emp if total_emp else 0\n\n    # Health: % Very good or Good\n    health_counts = stats['health']\n    very_good = health_counts.get('1. Very good', 0)\n    good = health_counts.get('2. Good', 0)\n    healthy = very_good + good\n    total_health = sum([v for k, v in health_counts.items() if isinstance(v, (int, float))])\n    pct_healthy = healthy / total_health if total_health else 0\n\n    # Number of nodes\n    nodes = stats['nodes']\n\n    # % not Heterosexual\n    sex_counts = stats['sexual_orientation']\n    hetero = sex_counts.get('1. Heterosexual', 0)\n    total_sex = sum([v for k, v in sex_counts.items() if isinstance(v, (int, float))])\n    pct_not_hetero = 1 - (hetero / total_sex) if total_sex else 0\n\n    rows.append({\n        'Voivodeship': voiv,\n        'Education_High_pct': pct_high_edu,\n        'Employment_Employed_pct': pct_employed,\n        'Health_Healthy_pct': pct_healthy,\n        'Nodes': nodes,\n        'Pct_Not_Hetero': pct_not_hetero\n    })\n\ndf_summary = pd.DataFrame(rows)\n\n# Sort and display for each metric\nmetrics = [\n    ('Education_High_pct', 'Education (High %)'),\n    ('Employment_Employed_pct', 'Employment (Employed %)'),\n    ('Health_Healthy_pct', 'Health (Very good or Good %)'),\n    ('Nodes', 'Number of nodes'),\n    ('Pct_Not_Hetero', '% not Heterosexual')\n]\nfor col, label in metrics:\n    print(f\"\\nSorted by {label} (descending):\")\n    display_cols = ['Voivodeship', col]\n    print(df_summary.sort_values(col, ascending=False)[display_cols].to_string(index=False))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nSorted by Education (High %) (descending):\n            Voivodeship  Education_High_pct\n         6. Malopolskie            0.742477\n         7. Mazowieckie            0.701768\n        9. Podkarpackie            0.669218\n        1. Dolnoslaskie            0.649037\n          11. Pomorskie            0.642951\n      15. Wielkopolskie            0.623197\n  2. Kujawsko-Pomorskie            0.621220\n             3. Lódzkie            0.619269\n          10. Podlaskie            0.604146\n           4. Lubelskie            0.594578\n            5. Lubuskie            0.563522\n            12. Slaskie            0.555092\n16. Zachodnio-Pomorskie            0.550051\n     13. Swietokrzyskie            0.534722\n            8. Opolskie            0.435644\n14. Warminsko-Mazurskie            0.434866\n\nSorted by Employment (Employed %) (descending):\n            Voivodeship  Employment_Employed_pct\n16. Zachodnio-Pomorskie                 0.865135\n      15. Wielkopolskie                 0.818727\n        1. Dolnoslaskie                 0.814968\n         7. Mazowieckie                 0.812835\n            12. Slaskie                 0.793996\n          11. Pomorskie                 0.791357\n         6. Malopolskie                 0.787722\n        9. Podkarpackie                 0.785675\n          10. Podlaskie                 0.764067\n     13. Swietokrzyskie                 0.762731\n14. Warminsko-Mazurskie                 0.746169\n             3. Lódzkie                 0.729823\n           4. Lubelskie                 0.720263\n            8. Opolskie                 0.714058\n            5. Lubuskie                 0.695449\n  2. Kujawsko-Pomorskie                 0.662986\n\nSorted by Health (Very good or Good %) (descending):\n            Voivodeship  Health_Healthy_pct\n            8. Opolskie            0.829073\n        1. Dolnoslaskie            0.726965\n     13. Swietokrzyskie            0.726852\n          11. Pomorskie            0.717154\n16. Zachodnio-Pomorskie            0.709291\n           4. Lubelskie            0.692767\n          10. Podlaskie            0.686081\n      15. Wielkopolskie            0.681416\n        9. Podkarpackie            0.676873\n         7. Mazowieckie            0.654480\n  2. Kujawsko-Pomorskie            0.650894\n14. Warminsko-Mazurskie            0.649425\n         6. Malopolskie            0.622203\n             3. Lódzkie            0.612479\n            12. Slaskie            0.605650\n            5. Lubuskie            0.575263\n\nSorted by Number of nodes (descending):\n            Voivodeship  Nodes\n         7. Mazowieckie   5317\n      15. Wielkopolskie   3679\n         6. Malopolskie   3663\n            12. Slaskie   3592\n        1. Dolnoslaskie   2808\n          11. Pomorskie   2414\n  2. Kujawsko-Pomorskie   1992\n        9. Podkarpackie   1912\n             3. Lódzkie   1851\n           4. Lubelskie   1756\n14. Warminsko-Mazurskie   1092\n          10. Podlaskie   1063\n16. Zachodnio-Pomorskie   1056\n     13. Swietokrzyskie    906\n            5. Lubuskie    901\n            8. Opolskie    656\n\nSorted by % not Heterosexual (descending):\n            Voivodeship  Pct_Not_Hetero\n          11. Pomorskie        0.137495\n             3. Lódzkie        0.133944\n        1. Dolnoslaskie        0.103798\n         7. Mazowieckie        0.102921\n      15. Wielkopolskie        0.102484\n            5. Lubuskie        0.093349\n     13. Swietokrzyskie        0.090278\n        9. Podkarpackie        0.085839\n            12. Slaskie        0.065921\n         6. Malopolskie        0.043603\n           4. Lubelskie        0.038255\n  2. Kujawsko-Pomorskie        0.026288\n          10. Podlaskie        0.025666\n16. Zachodnio-Pomorskie        0.024975\n14. Warminsko-Mazurskie        0.007663\n            8. Opolskie        0.000000\n```\n:::\n:::\n\n\nIf we look at the variables of Education, Employment, and Health we can gather which are the richest and healthiest voivodeships. The simplest is employment which we can compare to the below.\n\n\n![Map of Employment in Poland and Polish cities](media/registered_unemployed_persons_and_unemployment_rate-02.png) \n\nThis map is from 2017 and from the Polish census we can see that the lowest unemployment rates are in areas with large cities like the Mazowieckie (Warsaw), Malopolskie (Krakow) and Pomorskie (Gdansk) voivodeships. This makes sense as major cities bring opportunities. \n\nNow let's compare it to our KINMATRIX data, do these findings carry over? Our three most employed voivodeship's are: Zachodnio-Pomorskie with 86.5%, Wielkopolskie with 81.8% and Dolnoslaskie with 81.5%. Our three least employed are Opolskie with 71.4% Lubelskie with 69.5% and Kujawsko-Pomorskie with 66.29%. Even with the far smaller sample size these findings seem to be in-line with the census data and with development/economic theory. The voivodeship's with the lowest employment all lack big cities Opole, Lublin and Bydgoszcz are all far smaller than Szczecin, Poznan, and Wroclaw. \n\n# 8.0 Parental Separations \n\nLet's continue our analysis by looking at the Parental Separation Variable and seeing if we can infer any trends or interesting findings like before. \n\n::: {#49426ea9 .cell execution_count=21}\n``` {.python .cell-code}\nprint(\"Unique values for parental separation (par_sep):\")\nprint(df['par_sep'].dropna().unique())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nUnique values for parental separation (par_sep):\n['1. Yes', '-3. Does not apply', '2. No']\nCategories (3, object): ['-3. Does not apply' < '1. Yes' < '2. No']\n```\n:::\n:::\n\n\nIt is a simple indicator variable of if the anchor's parents are separated.\n\nWe will look through all countries in our dataset looking at countries and parental separation for the parents of the anchor individual. \n\n::: {#f198ead6 .cell execution_count=22}\n``` {.python .cell-code}\n# Country mapping dictionary\ncountry_map = {\n    'UK': '1. UK',\n    'Germany': '2. Germany',\n    'Poland': '3. Poland',\n    'Italy': '4. Italy',\n    'Sweden': '5. Sweden',\n    'Denmark': '6. Denmark',\n    'Finland': '7. Finland',\n    'Norway': '8. Norway',\n    'Netherlands': '9. Netherlands',\n    'USA': '10. USA'\n}\n\n# Initialize results storage\nseparation_results = {}\n\n# Calculate percentages for each country\nfor country, code in country_map.items():\n    country_df = df[df['anc_cou'] == code]\n    \n    # Parental separation calculation\n    sep_counts = country_df['par_sep'].value_counts(dropna=True)\n    separated = sep_counts.get('1. Yes', 0)  \n    # Exclude 'Prefer not to answer' from total \n    valid_responses = sep_counts.drop('-2. Prefer not to answer', errors='ignore').sum()\n    sep_pct = separated / valid_responses if valid_responses > 0 else 0\n    separation_results[country] = sep_pct\n\n# Sort results from most to least\nsorted_separation_desc = sorted(separation_results.items(), key=lambda x: x[1], reverse=True)\n\n# Prepare output string\nseparation_output = \"Countries sorted by parental separation (highest to lowest rate):\\n\"\n\nfor country, pct in sorted_separation_desc:\n    separation_output += f\"{country}: {pct:.2%}\\n\"\n\nprint(separation_output)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCountries sorted by parental separation (highest to lowest rate):\nItaly: 73.83%\nPoland: 64.66%\nNetherlands: 62.07%\nGermany: 57.64%\nUK: 57.34%\nFinland: 56.68%\nDenmark: 54.76%\nSweden: 48.04%\nUSA: 48.00%\nNorway: 46.61%\n\n```\n:::\n:::\n\n\nSurprising results with Poland and Italy at the top, we would not expect more traditional and Christian countries to have such a high divorce rate. Let's re-use the right and left leaning regions in Poland and see if parental separation differs by political allegiance. \n\n::: {#fec16fa2 .cell execution_count=23}\n``` {.python .cell-code}\n# Left-/right-leaning voivodeship lists are defined as before.\nleft_leaning_voivodeships = [\n    '7. Mazowieckie', '11. Pomorskie', '15. Wielkopolskie', '16. Zachodnio-Pomorskie'\n]\nright_leaning_voivodeships = [\n    '9. Podkarpackie', '4. Lubelskie', '10. Podlaskie', '13. Swietokrzyskie'\n]\n\npoland_df = country_dfs['3. Poland'].copy()\n\n# Assign the group using anc_regpl\ndef assign_voivodeship_group(voiv):\n    if voiv in left_leaning_voivodeships:\n        return 'Left-leaning'\n    elif voiv in right_leaning_voivodeships:\n        return 'Right-leaning'\n    else:\n        return 'Other'\n\npoland_df['voivodeship_group'] = poland_df['anc_regpl'].apply(assign_voivodeship_group)\n\n# Calculate parental separation per political group\nsep_results = {}\nfor group in ['Left-leaning', 'Right-leaning', 'Other']:\n    grp = poland_df[poland_df['voivodeship_group'] == group]\n    counts = grp['par_sep'].value_counts(dropna=True)\n    separated = counts.get('1. Yes', 0)\n    valid = counts.drop('-2. Prefer not to answer', errors='ignore').sum()\n    pct = separated / valid if valid > 0 else 0\n    sep_results[group] = pct\n\n# Print results\nfor group, pct in sep_results.items():\n    print(f\"{group}: {pct:.2%}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLeft-leaning: 66.69%\nRight-leaning: 69.57%\nOther: 61.45%\n```\n:::\n:::\n\n\nWe can see that there is no difference between left and right leaning regions with the Left-leaning regions having a separation percentage of 66.69% and the right leaning regions having one of 69.57%. So the cause is not political leaning. Let us also repeat this analysis for the United States.   \n\nUSA Analysis of Political Allegiance \n\n::: {#2d2949b0 .cell execution_count=24}\n``` {.python .cell-code}\n#American Regions from before\ndemocrat_regions = [\n    '5. New England (CT, MA, ME, NH, RI, VT)',\n    '6. Pacific (AK, CA, HI, OR, WA)',\n    '3. Mid-Atlantic (NJ, NY, DE, PA)',\n    '1. East North Central (IL, IN, MI, OH, WI)'\n]\n\nrepublican_regions = [\n    '2. East South Central (AL, KY, MS, TN)',\n    '9. West South Central (AR, LA, OK, TX)',\n    '8. West North Central (IA, KS, MN, MO, NE, ND...',  \n    '4. Mountain (AZ, CO, ID, MT, NV, NM, UT, WY)',\n    '7. South Atlantic (FL, GA, MD, NC, SC, VA, WV...'   \n]\n\n\nus_df = country_dfs['10. USA'].copy()\n\ndef assign_state_group(region):\n    if region in democrat_regions:\n        return 'Democrat'\n    elif region in republican_regions:\n        return 'Republican'\n\nus_df['state_group'] = us_df['anc_regus'].apply(assign_state_group)\n\nsep_results = {}\nfor group in ['Democrat', 'Republican']:\n    grp = us_df[us_df['state_group'] == group]\n    counts = grp['par_sep'].value_counts(dropna=True)\n    separated = counts.get('1. Yes', 0)\n    valid = counts.drop('-2. Prefer not to answer', errors='ignore').sum()\n    pct = separated / valid if valid > 0 else 0\n    sep_results[group] = pct\n\nfor group, pct in sep_results.items():\n    print(f\"{group} regions: {pct:.2%} had parental separation\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDemocrat regions: 52.59% had parental separation\nRepublican regions: 44.41% had parental separation\n```\n:::\n:::\n\n\nThe pattern is different in the United States we can see that Democrat regions have a far larger divorce rate than republican regions 52.59% compared to 44.41%. This is a large difference, but can we dig deeper into the reason for this difference. A possible reason for this could be religion where Republicans are more likely to be Christian than Democrats. \n\n**Note**: Religion questions were deliberately excluded from European KINMATRIX surveys, so we can not use it for our analysis of the European countries. They were only included for the United States which makes it perfect for this analysis. \n\nWe have three religious variables in the KINMATRIX Dataset: `anc_rel1`, `anc_rel2`, and `anc_rel3`. \nLike with all variables, let's look at all the levels this variable can take. \n\n::: {#bfe75243 .cell execution_count=25}\n``` {.python .cell-code}\nprint(\"Unique values for anc_rel1 (Religious dummy):\")\nprint(df['anc_rel1'].dropna().unique())\n\nprint(\"\\nUnique values for anc_rel2 (Religion ident.):\")\nprint(df['anc_rel2'].dropna().unique())\n\nprint(\"\\nUnique values for anc_rel3 (Attendance/frequency):\")\nprint(df['anc_rel3'].dropna().unique())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nUnique values for anc_rel1 (Religious dummy):\n['-3. Does not apply', '1. Yes', '2. No', '-1. Don't know']\nCategories (4, object): ['-3. Does not apply' < '-1. Don't know' < '1. Yes' < '2. No']\n\nUnique values for anc_rel2 (Religion ident.):\n['-3. Does not apply', '5. Jewish', '8. Other non-Christian religions', '2. Protestant', '4. Other Christian denomination', '1. Roman Catholic', '-2. Prefer not to answer', '6. Islamic', '3. Eastern Orthodox', '7. Eastern religions']\nCategories (10, object): ['-3. Does not apply' < '-2. Prefer not to answer' < '1. Roman Catholic' < '2. Protestant' ... '5. Jewish' < '6. Islamic' < '7. Eastern religions' < '8. Other non-Christian religions']\n\nUnique values for anc_rel3 (Attendance/frequency):\n['-3. Does not apply', '4. At least once a month', '2. More than once a week', '3. Once a week', '6. Less often', '5. Only on special holy days', '-1. Don't know', '7. Never', '1. Every day']\nCategories (9, object): ['-3. Does not apply' < '-1. Don't know' < '1. Every day' < '2. More than once a week' ... '4. At least once a month' < '5. Only on special holy days' < '6. Less often' < '7. Never']\n```\n:::\n:::\n\n\nFrom the output we can see that:\n\n* `anc_rel1` is a dummy variable for if the person is religious.\n* `anc_rel2` is a qualitative variable for which religion the person believes in.\n* `anc_rel3` is a variable for the frequency or attendance (how devout the person is).\n\n::: {#f786bb87 .cell execution_count=26}\n``` {.python .cell-code}\ndef sep_rate(df):\n    counts = df['par_sep'].value_counts(dropna=True)\n    separated = counts.get('1. Yes', 0)\n    # Exclude 'Prefer not to answer' from total\n    valid = counts.drop('-2. Prefer not to answer', errors='ignore').sum()\n    return (100 * separated / valid) if valid > 0 else 0\n\n# 1. Proportion \"Religious\" (anc_rel1 == \"1. Yes\")\nprint(\"Religious Differences by Region\")\nrel1 = us_df[us_df['anc_rel1'] != '-3. Does not apply']    # Exclude \"Does not apply\"\nfor group in ['Democrat', 'Republican']:\n    total = rel1[rel1['state_group'] == group].shape[0]\n    religious = rel1[(rel1['state_group']==group) & (rel1['anc_rel1'] == '1. Yes')].shape[0]\n    pct = 100 * religious / total if total else 0\n    print(f\"{group} regions: {pct:.1f}% report 'religious' (anc_rel1 == 'Yes')\")\nprint()\n\n# 2. Proportion attending at least monthly\nfreq_vals = {\"1. Every day\", \"2. More than once a week\", \"3. Once a week\", \"4. At least once a month\"}\nprint(\"Proportion attending religious services at least monthly:\")\nfor group in ['Democrat', 'Republican']:\n    sub = us_df[us_df['state_group'] == group]\n    att = sub['anc_rel3'].isin(freq_vals).sum()\n    total = sub['anc_rel3'].notna().sum()\n    pct = 100*att/total if total else 0\n    print(f\"{group}: {pct:.1f}% attend services at least monthly\")\nprint()\n\n# 3. Parental separation by religion (\"Yes\"/\"No\") within each region\nprint(\"Parental separation by religious status within region:\")\nfor group in ['Democrat','Republican']:\n    for rel_flag in ['1. Yes','2. No']:\n        sub = us_df[(us_df['state_group'] == group) & (us_df['anc_rel1'] == rel_flag)]\n        pct = sep_rate(sub)\n        print(f\"{group} - Religious '{rel_flag}': {pct:.2f}% parental separation\")\n    print()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nReligious Differences by Region\nDemocrat regions: 43.0% report 'religious' (anc_rel1 == 'Yes')\nRepublican regions: 53.0% report 'religious' (anc_rel1 == 'Yes')\n\nProportion attending religious services at least monthly:\nDemocrat: 11.7% attend services at least monthly\nRepublican: 14.7% attend services at least monthly\n\nParental separation by religious status within region:\nDemocrat - Religious '1. Yes': 61.74% parental separation\nDemocrat - Religious '2. No': 46.15% parental separation\n\nRepublican - Religious '1. Yes': 51.20% parental separation\nRepublican - Religious '2. No': 35.36% parental separation\n\n```\n:::\n:::\n\n\nAs we expected Republican regions are more religious with 53% of the respondents report that they are religious, compared to 43% in Democrat regions. Respondents from Republican regions also attend religious services more often (14.7% vs 11.7%). \n\nWhat is surprising is that it seems that religious families have a significant higher percentage of parental separation for both Democrat and Republican leaning regions. \n\n## 8.1 Discussion \n\nThe findings in this section are surprising. Please discuss these findings in your group. Here are some possible topics for discussion:\n\n* Cross-national variation: Poland and Italy, which are often seen as more traditional and Christian countries show the highest parental separation rates in this dataset. \n* Poland has no difference in parental separation based on political regions, but the United States does. Why is that?\n* How do we interpret the finding that within the US, 'religious' families (by self-report) have higher parental separation than non-religious ones? Does anyone have any ideas as to why?\n\n# 9.0 Non-Straight nodes across the countries and regions. \nFor the last part of this notebook let's look at which countries have the most straight and non-straight respondents. To do this we will use the **anc_sor** variable. As with all variables let's look at all the values this variable can take. \n\n::: {#8a0aaf7b .cell execution_count=27}\n``` {.python .cell-code}\nprint(df['anc_sor'].dropna().unique())\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n['1. Heterosexual', '3. Bisexual', '4. Other sexual orientation', '2. Gay or Lesbian']\nCategories (4, object): ['1. Heterosexual' < '2. Gay or Lesbian' < '3. Bisexual' < '4. Other sexual orientation']\n```\n:::\n:::\n\n\nThis variable records how respondents self-identify their sexual orientation. The variable is categorical, with four possible responses: Heterosexual, Gay or Lesbian, Bisexual and other. \n\nNow let's look through all the countries in the dataset looking for least and most straight countries. \n\n::: {#b69ea4d4 .cell execution_count=28}\n``` {.python .cell-code}\n# Your country mapping dictionary\ncountry_map = {\n    'UK': '1. UK',\n    'Germany': '2. Germany',\n    'Poland': '3. Poland',\n    'Italy': '4. Italy',\n    'Sweden': '5. Sweden',\n    'Denmark': '6. Denmark',\n    'Finland': '7. Finland',\n    'Norway': '8. Norway',\n    'Netherlands': '9. Netherlands',\n    'USA': '10. USA'\n}\n\n# Initialize results dictionary\norientation_results = {}\n\n# Calculate percentages for each country and sexual orientation\nfor country, code in country_map.items():\n    country_df = df[df['anc_cou'] == code]\n    \n    # Value counts including NaNs (if needed)\n    sor_counts = country_df['anc_sor'].value_counts(dropna=True)\n    # Optionally, exclude 'Prefer not to answer' category\n    valid_counts = sor_counts.drop('-2. Prefer not to answer', errors='ignore')\n    total = valid_counts.sum()\n    \n    # Calculate percentages for each orientation\n    percentages = {k: (v / total) for k, v in valid_counts.items()} if total > 0 else {}\n    orientation_results[country] = percentages\n\n# Print results\nfor country, percentages in orientation_results.items():\n    print(f\"{country_map[country]}:\")\n    if not percentages:\n        print(\"  No data\")\n        continue\n    # Sort by most common orientation first\n    sorted_orientations = sorted(percentages.items(), key=lambda x: x[1], reverse=True)\n    for orientation, pct in sorted_orientations:\n        print(f\"  {orientation}: {pct:.2%}\")\n    print()  # Blank line between countries\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1. UK:\n  1. Heterosexual: 86.47%\n  3. Bisexual: 7.15%\n  2. Gay or Lesbian: 4.06%\n  4. Other sexual orientation: 2.32%\n\n2. Germany:\n  1. Heterosexual: 87.93%\n  3. Bisexual: 5.72%\n  2. Gay or Lesbian: 3.58%\n  4. Other sexual orientation: 2.77%\n\n3. Poland:\n  1. Heterosexual: 92.21%\n  3. Bisexual: 4.22%\n  2. Gay or Lesbian: 3.02%\n  4. Other sexual orientation: 0.56%\n\n4. Italy:\n  1. Heterosexual: 90.71%\n  3. Bisexual: 4.91%\n  2. Gay or Lesbian: 3.44%\n  4. Other sexual orientation: 0.95%\n\n5. Sweden:\n  1. Heterosexual: 84.95%\n  3. Bisexual: 8.25%\n  2. Gay or Lesbian: 3.81%\n  4. Other sexual orientation: 2.99%\n\n6. Denmark:\n  1. Heterosexual: 81.57%\n  3. Bisexual: 9.45%\n  4. Other sexual orientation: 5.12%\n  2. Gay or Lesbian: 3.86%\n\n7. Finland:\n  1. Heterosexual: 83.75%\n  3. Bisexual: 11.14%\n  4. Other sexual orientation: 3.37%\n  2. Gay or Lesbian: 1.75%\n\n8. Norway:\n  1. Heterosexual: 88.25%\n  3. Bisexual: 7.02%\n  2. Gay or Lesbian: 3.88%\n  4. Other sexual orientation: 0.85%\n\n9. Netherlands:\n  1. Heterosexual: 87.24%\n  3. Bisexual: 6.60%\n  2. Gay or Lesbian: 3.31%\n  4. Other sexual orientation: 2.85%\n\n10. USA:\n  1. Heterosexual: 81.86%\n  3. Bisexual: 10.52%\n  2. Gay or Lesbian: 4.19%\n  4. Other sexual orientation: 3.43%\n\n```\n:::\n:::\n\n\nInteresting findings: \nPoland has the highest percentage of people identifying as heterosexual (92.21%), making it the most heterosexual country in this set.\nDenmark has the lowest percentage identifying as heterosexual (81.57%), and thus the highest percentage identifying as non-heterosexual (18.43%).\n\n### 9.1 Most Heterosexual and Non-Heterosexual regions in Poland and Denmark\n\nWe will look at the regions within each country that have the most heterosexual and non-heterosexual respondents. \n\nFirst Poland:\n\n::: {#3781a27d .cell execution_count=29}\n``` {.python .cell-code}\n# For Poland: calculate percentages per voivodeship\npoland_df = df[df['anc_cou'] == '3. Poland']\nvoivodeships = poland_df['anc_regpl'].dropna().unique()\n\nregion_hetero = {}\n\nfor region in voivodeships:\n    region_df = poland_df[poland_df['anc_regpl'] == region]\n    counts = region_df['anc_sor'].value_counts(dropna=True)\n    counts = counts.drop('-2. Prefer not to answer', errors='ignore')\n    total = counts.sum()\n    pct_hetero = counts.get('1. Heterosexual', 0) / total if total > 0 else 0\n    region_hetero[region] = pct_hetero\n\n# Sort and print most and least heterosexual regions\nmost_hetero_region = max(region_hetero.items(), key=lambda x: x[1])\nleast_hetero_region = min(region_hetero.items(), key=lambda x: x[1])\n\nprint(\"Poland:\")\nprint(f\"Most heterosexual region: {most_hetero_region[0]} ({most_hetero_region[1]*100:.2f}%)\")\nprint(f\"Most non-heterosexual region: {least_hetero_region[0]} ({100 - least_hetero_region[1]*100:.2f}%)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPoland:\nMost heterosexual region: 8. Opolskie (100.00%)\nMost non-heterosexual region: 11. Pomorskie (13.75%)\n```\n:::\n:::\n\n\nWe can again consult our map of the Polish Voivodeships. \n\n![Map of Polish voivodeships](media/wojewodstwa.png) \n\nOpole is the smallest and least populated voivodeship (province) of Poland. The province's name derives from that of the region's capital and largest city, Opole. Students should already be familiar with Pomerania (Pomorskie) as we have already used and discussed this voivodeship in this notebook. Pomorskie is in the north of Poland on the Baltic sea with the largest city being Gdansk which is a large port along with Gdynia in the region. \n\nLet's now look at the findings for Denmark:\n\n::: {#c63124ff .cell execution_count=30}\n``` {.python .cell-code}\n# For Denmark: similar approach\ndenmark_df = df[df['anc_cou'] == '6. Denmark']\nregions_dk = denmark_df['anc_regdk'].dropna().unique()\n\nregion_hetero_dk = {}\n\nfor region in regions_dk:\n    region_df = denmark_df[denmark_df['anc_regdk'] == region]\n    counts = region_df['anc_sor'].value_counts(dropna=True)\n    counts = counts.drop('-2. Prefer not to answer', errors='ignore')\n    total = counts.sum()\n    pct_hetero = counts.get('1. Heterosexual', 0) / total if total > 0 else 0\n    region_hetero_dk[region] = pct_hetero\n\n# Sort and print most and least heterosexual regions\nmost_hetero_region_dk = max(region_hetero_dk.items(), key=lambda x: x[1])\nleast_hetero_region_dk = min(region_hetero_dk.items(), key=lambda x: x[1])\n\nprint(\"Denmark:\")\nprint(f\"Most heterosexual region: {most_hetero_region_dk[0]} ({most_hetero_region_dk[1]*100:.2f}%)\")\nprint(f\"Most non-heterosexual region: {least_hetero_region_dk[0]} ({100 - least_hetero_region_dk[1]*100:.2f}%)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDenmark:\nMost heterosexual region: 5. Region Syddanmark (90.94%)\nMost non-heterosexual region: 3. Region Nordjylland (23.71%)\n```\n:::\n:::\n\n\nThe most heterosexual region is Syddanmark which is the south of Denmark. \n\n![Syddanmark](media/1280px-Syddanmark_in_Denmark.png) \n\nThe regional capital is Vejle but Odense is the region's largest city. \n\nAs for the most non-heterosexual region it is Nordjylland which is the north of Denmark. \n\n![Nordjylland](media/Nordjylland_in_Denmark.png) \n\nThe largest city in this region is Aalborg. \n\n# 10.0 Hands on Section \n\nFor the next section students will be tasked with working hands on with networks and performing the same data gathering as the researchers at KINMATRIX. Turn to the person next to you and on a piece of paper or a computer program like MSPaint draw their family network. Ask questions about family relation, age, gender and other demographic variables like education. Help each other and if you need an example look at the Pyvis visualizations. \n\nAlternatively students can plot their own family networks on our [Custom Ego-Network Build Website](https://alexr951.github.io/EgoNetworkApp/). \n\n# 11.0 Citations\n\nAl-Taie, M. Z., & Kadry, S. (2017). *Python for graph and network analysis*. Springer. https://doi.org/10.1007/978-3-319-53004-8\n\nBrown, Kristen  V. “The Coming Democratic Baby Bust.” The Atlantic Archive, 17 Feb. 2025, archive.is/pKsPn#selection-723.0-723.16. \n\n“Cook Partisan Voting Index.” Wikipedia, Wikimedia Foundation, 25 May 2025, en.wikipedia.org/wiki/Cook_Partisan_Voting_Index. \n\nCox, Kimberley. “Feminist Theory in Sociology: EBSCO.” EBSCO Information Services, Inc. | Www.Ebsco.Com, 2021, www.ebsco.com/research-starters/womens-studies-and-feminism/feminist-theory-sociology. \n\nDolan, Eric  W. “Research Reveals Widening Gap in Fertility Desires between Republicans and Democrats.” PsyPost, 7 Oct. 2024, www.psypost.org/research-reveals-widening-gap-in-fertility-desires-between-republicans-and-democrats/. \n\nGraves, Jonathan, et al. “Network Analysis for Anthropology.” COMET, UBC, 2024, comet.arts.ubc.ca. \n\n“Home.” Kinmatrix, 10 Apr. 2025, kinmatrix.eu/. \n\nKinmatrix: A New Data Resource for Studies of Families ..., www.demographic-research.org/volumes/vol51/25/51-25.pdf. Accessed 8 Aug. 2025. \n\nKrisch, Joshua  A. “This Shocking Map Shows Republicans’ Most Powerful Political Weapon.” Fatherly, 8 July 2022, www.fatherly.com/health/republicans-have-more-children. \n\nQuantEcon DataScience. (n.d.). *Social and economic networks*. https://datascience.quantecon.org/applications/networks.html\n\n“Registered Unemployed Persons and Unemployment Rate by Voivodships, Subregions and Powiats. as of the End of November 2017.” Stat.Gov.Pl, Government of Poland, 22 Dec. 2017, stat.gov.pl/en/topics/labour-market/registered-unemployment/registered-unemployed-persons-and-unemployment-rate-by-voivodships-subregions-and-powiats-as-of-the-end-of-november-2017,1,64.html. \n\nNomaguchi, K. M. & Milkie, M. A. (2003).  The costs and rewards of children:  The \neffect of becoming a parent on adults’ lives. Journal of Marriage and Family, 65 (2), 356-374. link:  http://www.jstor.org/stable/3600082?pq-origsite=summon\n\nSayama, H. (2024, April 30). *Generating random graphs*. In *Introduction to the modeling and analysis of complex systems*. Mathematics LibreTexts. \nhttps://math.libretexts.org/Bookshelves/Scientific_Computing_Simulations_and_Modeling/\nIntroduction_to_the_Modeling_and_Analysis_of_Complex_Systems_(Sayama)/15%3A_Basics_of_Networks/15.06%3A_Generating_Random_Graphs\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: 'D:\\Users\\alexr\\anaconda3\\share\\jupyter\\kernels\\python3'\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.13.5\n---\n",
    "supporting": [
      "kinmatrix_files\\figure-ipynb"
    ],
    "filters": []
  }
}