{
  "hash": "68289570eabb8238ed30cefa0583443c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"1.4.2 - Beginner - Hypothesis Testing\"\nauthor: COMET Team <br> _Oliver (Junye) Xu, Colby Chambers, Jonathan Graves, Jasmine Arora_\ndate: 12 January 2023\ndescription: What is a hypothesis?  How do we test it?  This notebook introduces hypothesis testing in two different ways, outlining the connection between them and how we can use this technique to answer economic questions.\ncategories: [econ 325, econ 226, econ 227. confidence intervals, hypothesis testing, t-test, type-I error, type-II error, p-value, R, beginner, significance level, critical value]\neditor: \n  markdown: \n    wrap: 72\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html: default\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: R\n        language: r\n        name: ir\nimage: /media/comet_placeholder.png\n---\n\n\n## Outline\n\n### Prerequisites\n\n-   Introduction to Jupyter\n-   Introduction to R\n-   Introduction to Visualization\n-   Central Tendency\n-   Distribution\n-   Dispersion and Dependence\n-   Confidence Intervals\n\n### Outcomes\n\nAfter completing this notebook, you will be able to:\n\n-   Set up hypotheses to address a research question\n-   Conduct 1-sample and 2-sample $t$-tests to address these questions in the context of population means\n-   Use the critical value and $p$-value approaches to determine whether or not to reject a null hypothesis\n-   Interpret type I and type II errors in order to explore how sample and population statistics relate\n\n## Introduction\n\nIn the previous notebook, we covered a fundamental tool in statistics: *confidence intervals*. In this notebook, we will build on this knowledge and learn about an important inference technique, perhaps one of the most important concepts in elementary statistics: **hypothesis testing**.\n\nHypothesis testing allows us to test precise statements about data, using a straight-forward process.\n\n1.  Create a hypothesis about some phenomenon (i.e. the relationship between two variables in our dataset).\n2.  Select a test to determine whether the sample data gives us credible reason to reject this initial hypothesis.\n3.  Conduct the test and draw conclusions about the validity of our hypothesis.\n\nThis is a very high-level summary of hypothesis testing: we will dive into the concept in much more detail throughout this notebook; along the way, we will rely on some helpful built-in functions in R to make this process more convenient.\n\nHowever, as you go through this notebook, pay careful attention to not just the mechanics but also the **logic** of hypothesis testing. This is perhaps the single most important concept in introductory econometrics, so a careful understanding of this material will serve you well in future courses and beyond. Let's get started!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# loading tests\nsource(\"beginner_hypothesis_testing_tests.r\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'digest' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\n# importing packages\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   4.0.3     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.4     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ readr::edition_get()   masks testthat::edition_get()\n✖ dplyr::filter()        masks stats::filter()\n✖ purrr::is_null()       masks testthat::is_null()\n✖ dplyr::lag()           masks stats::lag()\n✖ readr::local_edition() masks testthat::local_edition()\n✖ dplyr::matches()       masks tidyr::matches(), testthat::matches()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(haven)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'haven' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\n# reading in the data\ncensus_data <- read_dta(\"../datasets_beginner/01_census2016.dta\")\ncensus_data <- filter(census_data, !is.na(census_data$wages))\n```\n:::\n\n\n\n## The Hypothesis Testing Procedure\n\nA hypothesis test always involves two hypotheses: the **null hypothesis** and the **alternative hypothesis**.\n\n-   The null hypothesis (${H_0}$) expresses a \"default\" claim which is to be tested\n-   The hypothesis (${H_1}$) expresses the contrary to the null hypothesis. Typically, our alternative hypothesis expresses what we may hope to prove about our data.\n\n> **Example**: Perhaps we suspect that the mean wage of Canadian men is greater than \\$50,000 per year\n> -   Null hypothesis (${H_0}$): The mean wage of Canadian men is less than or equal to 50,000.\n> -   The hypothesis (${H_1}$): The mean wage of Canadian men is greater than 50,000.\n> -   If we find sufficient evidence in the data to reject the null hypothesis, we can argue with a certain degree of certainty that we should favour this alternative hypothesis. If we don't find this strong evidence, we fail to reject the null hypothesis (and our suspicion is probably false).\n\nTo determine whether we should reject the null hypothesis in favour of the alternative hypothesis, we need two key features:\n\n1.  A **significance level** (denoted by $\\alpha$):\n    -   The probability which determines the criterion for deciding if a sample statistic is \"unlikely\" if the null hypothesis is true.\n2.  A **test statistic**:\n    -   The number we calculate from our data: this is usually a function of various features of that data such as its mean, standard deviation, and sample size.\n\nTogether, these two features provide the criterion under which we can accept or reject our null hypothesis. We can implement these using the following approaches:\n\nThere are two common approaches we can use when testing a hypothesis:\n\n-   The **critical value approach (rejection region)**\n-   The $p$-value approach.\n\nBoth have their uses, and we will demonstrate both in this notebook. They also have a series of steps, some of which they share in common.\n\n## Steps in Hypothesis Testing\n\n-   Steps 1-3 apply identically to *both* the critical value and $p$-value approaches\n-   Step 4, the interpretation step, diverges between the two approaches.\n\nWe will start with one important type of test: the **one sample** $t$-test. This kind of test is used to evaluate statements about whether the population average is equal to a particular value - for instance, our example above with average wages being greater than $50,000. This test is appropriate in situations where:\n\n1.  The statistic is **normally distributed**: in the case of the sample mean, when $n > 120$, invoking the Central Limit Theorem for normality.\n2.  We **don't know the population standard deviation** of the variable we are testing.\n\nThis is very similar to when we constructed confidence intervals for a sample mean when we didn't know the population standard deviation in the previous notebook.\n\n> **Tip**: Wikipedia actually has quite a useful article containing a chart of [Common Hypothesis Tests](https://en.wikipedia.org/wiki/Test_statistic) for different kinds of statistics.\n\n### Our Example\n\nLet's work with our Census data, and suppose that our census data represents the **entire Canadian population** and we have no prior knowledge of it.\n\n-   Let's pretend we do not observe any population values from our census data, just like in real life where it is impossible to observe population parameters!\n-   We will randomly select a sample of observations from our census data (the population) to represent our sample.\n-   We can then test to see if the average wage in our sample data is equal to the hypothesized average wage of the population as a whole. Let's draw a random sample first!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123) # ensures the reproducibility of our code \n# (we get the same sample if we start with that same seed each time you run the same process)\n\nsample_data <- census_data %>% \n               slice_sample(n = 100,  # number of observations to sample from the population\n               replace = FALSE) # without replacement\n```\n:::\n\n\n\n### Step 1: State the Null Hypothesis and Alternative Hypothesis\n\nThe null hypothesis that a population mean wage $\\mu^{wage}$ is equal to a certain value $\\mu_{0}$ is:\n\n$$\n{H_0}: \\mu^{wage} = \\mu_{0}\n$$\n\nAt this point, we have 3 choices for how to formulate our alternative hypothesis:\n\n1.  **Two-Sided Test**: If we want the rejection of the null hypothesis to allow us to argue that $\\mu^{wage}$ is different from the specific value $\\mu_{0}$, then we can express our alternative hypothesis as:\n\n$$\n{H_1}: \\mu^{wage} \\neq \\mu_{0}\n$$\n\n2.  **One-Sided Test (Left-Tailed)**: If we want the rejection of the null hypothesis to allow us to argue that $\\mu^{wage}$ is less than the specific value $\\mu_{0}$, then we can express our alternative hypothesis as:\n\n$$\n{H_1}: \\mu^{wage} < \\mu_{0}\n$$\n\n3.  **One-Sided Test (Right-Tailed)**: If we want the rejection of the null hypothesis to allow us to argue that $\\mu^{wage}$ is greater than the specific value $\\mu_{0}$, then we can express our alternative hypothesis as:\n\n$$\n{H_1}: \\mu^{wage} > \\mu_{0}\n$$\n\nNote: We should always construct our hypotheses about *population parameters*, not sample statistics (ie: sample mean, variance or other features from the sample that can be immediately calculated).\n\nWe can make hypotheses about a population variance, proportion, or various other parameters of interest. The population mean is just the default we are considering since we are focusing our attention on the one-sample $t$-test for now.\n\nLet's take an example that literature on labour market earnings presents\n\n-   A null hypothesis that the mean wage of Canadians is $54,000 per year.\n\n-   We will set this up against a two-sided alternative---the more stringent alternative hypothesis that requires more certainty in findings to reject the null (as explained above).\n\n$$\nH_{0}: \\mu = 54000\n$$ \n$$\nH_{1}: \\mu \\neq 54000\n$$\n\n### Exercise\n\nAim: Investigate the mean years of education among all citizens in a country who are over the age of 18.\n\nHypothesis: The average years of education among adults in this country is 12 years (some degree of post-secondary education).\n\nThink about how you would set up your null hypothesis. Which of the following is *NOT* a correct alternative hypothesis?\n\n1.  \\$ {H_1}: \\mu\\^{education} \\< 12 \\$\n2.  \\$ {H_1}: \\mu\\^{education} \\neq 12 \\$\n3.  \\$ {H_1}: \\mu\\^{education} \\> 12 \\$\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nanswer_0 <- ...  # fill in the.. with your answer of either 1, 2 or 3 \ntest_0()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_0 <- 2  # fill in the.. with your answer of either 1, 2 or 3 \ntest_0()\n```\n:::\n\n\n\n## Step 2: Choose a Significance Level $\\alpha$\n\nBefore any calculation of test statistics, we must choose a **significance level**.\n\n-   This is the probability of seeing a sample statistic at least as extreme as the one we find from our data when we assume that our null hypothesis is actually true.\n\n-   We most commonly set our significance level at 0.05, or 5%, but other common values include 1%, 10% and even 20%.\n\n> **Tip**: Remember that confidence level is denoted as $1 - \\alpha$. Here, $\\alpha$ itself is the significance level, meaning that the **confidence level and significance level add up to 1**. It is important not to use these two terms interchangeably!\n\nWe will choose our confidence level to be 5% since this is a common standard in applied economic work:\n\n$$\n\\alpha = 0.05\n$$\n\n### Step 3: Compute the Test Statistic\n\nThis is the most mathematical step, requiring some calculation. Our **test statistic** gives us a numeric benchmark at which we can reject our null hypothesis in Step 4. Calculating the test statistic is quick but it is important to understand the intuition behind it and how it is derived.\n\nWhen we calculate our test statistic with the one-sample $t$-test we use the following approach:\n\n1.  Take our sample statistic\n2.  Subtract it from the mean of the sampling distribution\n3.  Divide this value by the standard deviation of our sampling distribution\n\nThe general process outlined above will always hold for calculating a test statistic. However, determining how exactly we calculate the mean and standard deviation of our desired sampling distribution will differ slightly depending on the situation, the type of parameter we are making inferences about, as well as our sample size and the shape of our population distribution.\n\nAs noted, we will look below for calculating the test statistic for one case: one sample $t$-tests.\n\nSince we don't know the standard deviation of our population but do know that the distribution of our sampling statistic is normal (since the sample size is \\> 30), we calculate our test statistic using the following **one sample** $t$-statistic:\n\n$$\n\\frac{\\bar x - \\mu_{0}}{(s / \\sqrt n)}\n$$\n\n\n-   $\\bar x$ is the sample mean we have found\n-   $\\mu_{0}$ is the population mean we are assuming to be true under the null hypothesis\n\n-   $H_{0} : \\mu = \\mu_{0}$, $s$ is the sample standard deviation and $n$ is the sample size.\n\nAgain, the formula for calculating the test statistic will differ depending on the test being performed, the size of our sample, and whether our hypothesis is about a population mean, proportion, or variance.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute the t-statistic/critical value for the one sample t-test\nt_stat <- (mean(sample_data$wages) - 54000)/(sd(sample_data$wages)/sqrt(100))\nt_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7221281\n```\n\n\n:::\n:::\n\n\n\n### Step 4: Interpret the Results\n\nThe last step in hypothesis testing requires us to conclusively **reject or fail to reject the null hypothesis**. We can either use the **critical value approach or the** $p$**-value approach** that would bring us to the same answer. Let's look at each of them individually.\n\n### The Critical Value (or Rejection Region) Approach:\n\n-   The critical value defines the upper and lower bounds of a confidence interval, or which defines the threshold of statistical significance in a statistical test.\n\n-   In this approach, we **compare our calculated test statistic to a critical value** (or values) corresponding to our chosen significance level.\n\n<div>\n\nThe critical value serves as the cutoff point beyond which we reject our\nnull hypothesis.\n\n-   We **reject our null hypothesis** if our calculated **test statistic is more extreme than the critical value** (situated more within the tail of the investigated distribution.\n\n-   We **fail to reject our null hypothesis** if the **test statistic is within these bounds.**\n\n</div>\n\n#### How are critical values computed?\n\n-   Depending on our test, we determine a critical value by determining what values of statistics have an $\\alpha$-percent chance of being more extreme than the critical value.\n\n-   These values are called the **rejection region** and are specific to the test. The diagrams below illustrate this process.\n\n#### **One-Sided Test (Left-Tail** **ed)**:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# alt text for accessibility\nalt_text <- \"A plot visualizing the left-tailed rejection region in a probability distribution curve.\"\n\ndraw_cr(\"left-tailed\", df = 30, cv = -2)\nmtext(alt_text, side=3, line=2.75, cex=1.1)\n```\n\n::: {.cell-output-display}\n![](beginner_hypothesis_testing_files/figure-ipynb/unnamed-chunk-6-1.png)\n:::\n:::\n\n\n\nThe first diagram shows where we can reject a null hypothesis such as $H_{0}:\\mu = \\mu_{0}$ in favour of the alternative hypothesis $H_{1}:\\mu < \\mu_{0}$.\n\n-   Null hypothesis: $\\mu \\leq\\mu_0$\n-   Alternative: $\\mu > \\mu_0$.\n-   The value which had an $\\alpha$-percent of lying above it is called the critical value, and the red region represents the rejection region.\n\n#### **One-Sided Test (Right-Tailed)**:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# alt text for accessibility\nalt_text <- \"A plot visualizing the right-tailed rejection region in a probability distribution curve.\"\n\ndraw_cr(\"right-tailed\", df = 30, cv = 2)\nmtext(alt_text, side=3, line=2.75, cex=1.1)\n```\n\n::: {.cell-output-display}\n![](beginner_hypothesis_testing_files/figure-ipynb/unnamed-chunk-7-1.png)\n:::\n:::\n\n\n\nThis second diagram shows us where we can reject a null hypothesis such as $H_{0}:\\mu = \\mu_{0}$ in favour of the alternative hypothesis $H_{1}:\\mu > \\mu_{0}$.\n\n-   If our calculated test statistic falls in this red rejection region, it is \"more extreme\" than the critical value corresponding to our chosen significance level. This means we can reject the null hypothesis in favour of the alternative hypothesis.\n-   If our calculated test statistic falls within the white region, we fail to reject our null.\n\n#### **Two-Sided Test**:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# alt text for accessibility\n\nalt_text <- \"A plot visualizing the two-tailed rejection region in a probability distribution curve\"\n\ndraw_cr(\"two-tailed\", df = 30, cv = 2)\nmtext(alt_text, side=3, line=2.75, cex=1.1)\n```\n\n::: {.cell-output-display}\n![](beginner_hypothesis_testing_files/figure-ipynb/unnamed-chunk-8-1.png)\n:::\n:::\n\n\n\nThe third diagram shows us how to use the critical value approach to choose whether or not to reject a null hypothesis for a two-sided test.\n\nLike previous cases:\n\n-   If our calculated test statistic falls within either of these rejection regions, we reject our null hypothesis. If it falls within the white region, we fail to reject our null.\n\n-   The area of the total red region equals $\\alpha$, our chosen significance level.\n\nHowever, for a two-sided test\n\n-   There are now two red regions since our alternative hypothesis is now $H_{1}: \\mu \\neq \\mu_{0}$.\n\n-   Our test statistic will fall near (or in) either the left-hand rejection region or right-hand region.\n\n-   The probability that it falls within that specific region itself is now half as likely as it was for the one-sided tests (the probability is now $\\alpha / 2$).\n\n-   Therefore, the two-sided test is more conservative as it is less likely for our calculated test statistic to fall inside the rejection region and allow us to reject our null hypothesis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# examples of how to compute critical values for different types of test\n# suppose the significance level is 0.05\n\n# finding the lower and upper critical values for a two-sided test\nqt(p=0.025, df=8, lower.tail=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -2.306004\n```\n\n\n:::\n\n```{.r .cell-code}\nqt(p=0.025, df=8, lower.tail=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.306004\n```\n\n\n:::\n\n```{.r .cell-code}\n# finding the critical value for a left-sided test\nqt(p=0.05, df=8, lower.tail=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.859548\n```\n\n\n:::\n\n```{.r .cell-code}\n# finding the critical value for a right-sided test\nqt(p=0.05, df=8, lower.tail=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.859548\n```\n\n\n:::\n:::\n\n\n\nLet's compute the rejection regions for our sample data:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# finding the lower and upper critical values for our sample data\nqt(p=0.025, df=99, lower.tail=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -1.984217\n```\n\n\n:::\n\n```{.r .cell-code}\nqt(p=0.025, df=99, lower.tail=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.984217\n```\n\n\n:::\n:::\n\n\n\n-   We can see from the above that our test statistic of about 0.72 fits within the upper and lower bound critical values of -1.98 and 1.98.\n-   Therefore the sample statistic is conditioned on the null hypothesis being true.\n-   We thus do not have strong evidence to reject the null hypothesis.\n-   We say that our sample mean is **not** **statistically significant**.\n\n <div>\n\n Statistically significant results are those which we find upon rejecting the null hypothesis.\n\n </div>\n\n### The $p$-value Approach:\n\n-   In this approach, we again use our test statistic to make inferences about our population. However, we no longer rely on the diagrams above.\n-   We instead calculate what is called a $p$-value: A number between 0 and 1 indicating the probability of observing a value at least as extreme as the test statistic if ${H_0}$ is true. - For example, a $p$-value of 0.05 would mean that if the ${H_0}$ is true, there is a 5% chance of getting a test-statistic as extreme or more extreme than the one we obtained.\n-   Small $p$-values provide evidence to reject the null hypothesis, since they indicate that the observed data is not likely if the hypothesis was true. Recall that in hypothesis testing we are trying to find evidence to reject the null hypothesis. A lower $p$-value provides evidence to reject the null hypothesis. Formally, if the  $p$-value is less than or equal to our significance level $\\alpha$,  the null hypothesis is rejected; otherwise, the null hypothesis is not rejected.\n\nFor example,\n\nTo find the $p$-value associated with a t-score in R, we can use the `pt()` function:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Examples of how to compute p values for different types of test\n\n# If the t-score/critical value is 1.8 for a right-tailed test\n# find p-value if the degrees of freedom is 30\npt(q=1.8, df=30, lower.tail=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.04096253\n```\n\n\n:::\n\n```{.r .cell-code}\n# If the t-score/critical value is 1.8 for a two-tailed test\n#find two-tailed p-value if the degrees of freedom is 30\n2*pt(q=1.8, df=30, lower.tail=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08192507\n```\n\n\n:::\n:::\n\n\n\nLet's compute the *p*-value for our sample data:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compute the p-value\n2*pt(q=t_stat, df=99, lower.tail=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.471918\n```\n\n\n:::\n:::\n\n\n\nOur $p$-value is about 0.47, which is much larger than our confidence level of 0.05. This means that, assuming the null is true, it is very likely that we see a value as extreme as our sample mean. It is thus not bizarre to imagine pulling such a sample statistic when the null of 54000 is in fact true. This causes us to fail to reject the null hypothesis.\n\n## Exercise\n\nLet's say that you choose a 5% significance level and conduct a one sample $t$-test (since you're testing a hypothesis about the mean of a single population for which you don't know the standard deviation). You receive a $p$-value of 0.02 and correctly reject your null hypothesis. Have you proved that your null hypothesis is false?\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nanswer_1 <- \"x\" # your answer of \"yes\" or \"no\" in place of \"x\" here\ntest_1()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_1 <- \"no\" # your answer of \"yes\" or \"no\" in place of \"x\" here\ntest_1()\n```\n:::\n\n\n\nLet's now run through the hypothesis testing procedure more quickly with a few examples, but this time through an automation process with `t.test()`. It performs one and two sample t-tests on vectors of data.\n\n## Applications of the Procedure with the R function `t.test()`\n\n## Example 1: One Sample $t$-test\n\nRecall from our previous example:\n\n$$\nH_{0}: \\mu = 54000\n$$ \n$$\nH_{1}: \\mu \\neq 54000\n$$\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# conduct one sample t-test\nt.test(x = sample_data$wages, mu = 54000, alternative = \"two.sided\", conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  sample_data$wages\nt = 0.72213, df = 99, p-value = 0.4719\nalternative hypothesis: true mean is not equal to 54000\n95 percent confidence interval:\n 47651.67 67612.97\nsample estimates:\nmean of x \n 57632.32 \n```\n\n\n:::\n:::\n\n\n\n> Now we may go back and check if the t statistic and $p$-value here match with our manual calculation above. It matches!\n\nThe `t.test()` function in R is super helpful in that it outputs a $p$-value and test statistic immediately, allowing us to either reject or fail to reject the null hypothesis immediately.\n\n-   In our sample data, our large $p$-value and non-extreme test statistic prevent us from rejecting the null.\n-   If we had different results (ie: a $p$-value \\< 0.05 or test statistic very large in magnitude), we would say that the probability of finding the particular sample mean under the null being true is incredibly unlikely. This sample mean would thus be a  statistically significant result which we could try with a high degree of uncertainty, allowing us to reject the null in favor of the alternative hypothesis.\n\n> Note: In this example, the $p$-value was about 0.47.\n> -   This does not mean that the probability the null hypothesis is true is 47%.\n> -   Rather, it means that if the null hypothesis is true, the probability of seeing a sample mean at least as far away from 54000 is 47%.\n> -   Therefore, since it is quite likely to pull a sample mean this large by chance, we cannot reject the null and we do not have statistically significant results.\n\n## Example 2: Two Sample $t$-test\n\n-   Unlike the one-sample $t$-test where we use a sample mean point estimate to test a hypothesis about a population mean, the two-sample $t$-test uses two sample means to test a hypothesis about whether the means of two independent populations differ from each other.\n\n-   We will use the two sample unpooled $t$-test with unequal variances when we know:\n    -   1. That both populations are normally distributed (or the sum of their sample sizes exceeds 40, invoking normality),\n\n    -   2. That the observations are independent between the two groups (i.e. observations are not paired between populations),\n\n    -   3. And we assume that both population standard deviations, while unknown, are different.\n\nFor this example, we will test the hypothesis that there is no difference between the mean wages of Canadians and Non-Canadians. We will set this up against a two-sided alternative.\n\n$$\nH_{0}: \\mu_{Canadian} = \\mu_{Non-Canadian}\n$$ \n$$\nH_{1}: \\mu_{Canadian} \\neq \\mu_{Non-Canadian}\n$$\n\nWe will again set our significance level at 5%.\n\n$$\n\\alpha = 0.05\n$$\n\nAgain, we will assume our census data represents our population and take two random samples from it, each of which will consist exclusively of Canadians or Non-Canadians.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123) # ensures the reproducibility of our code (we get the same sample if we start with that same seed each time you run the same process)\n\n\nsample_cad <- census_data %>% \n              filter(immstat == 1) %>% \n              slice_sample(n = 100,  # number of observations to sample from the population\n              replace = FALSE) # without replacement\n\nsample_noncad <- census_data %>% \n              filter(immstat == 2) %>% \n              slice_sample(n = 100,  # number of observations to sample from the population\n              replace = FALSE) # without replacement\n```\n:::\n\n\n\nFor fun, let's look at our sample statistics.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(sample_cad$wages)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 65362.89\n```\n\n\n:::\n\n```{.r .cell-code}\nmean(sample_noncad$wages)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 52611.15\n```\n\n\n:::\n:::\n\n\n\n-   We can already see a large difference in mean wages between Canadians and Non-Canadians here.\n\n-   However, we will have to conduct our $t$-test to determine if this difference is statistically significant and thus if we can reject our null hypothesis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# conducting our two sample t-test\nt.test(x=sample_cad$wages, y=sample_noncad$wages, conf.level=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  sample_cad$wages and sample_noncad$wages\nt = 1.4545, df = 159.7, p-value = 0.1478\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -4562.083 30065.563\nsample estimates:\nmean of x mean of y \n 65362.89  52611.15 \n```\n\n\n:::\n:::\n\n\n\nOur $t$-test yields a $p$-value of about 0.1478, greater than our significance level of 0.05. Thus, our result is not statistically significant and we cannot reject our null hypothesis.\n\n>**Note:** This reveals nothing about why this is the case and does not control for any relevant factors. You will learn more about this in upcoming courses.\n\n-   We ran this $t$-test on two independent populations (Canadians and Non-Canadians).\n-   Alternatively, if we want to compare the means of dependent populations and test whether or not they are the same, we can employ the `y ~ x` option to our `t.test()` function.\n    -   The dependent variable is on the left of the tilde (`~`)\n    -   The independent variable (or variables) is on the right of the tilde (`~`)\n-   We also need to specify within the `t.test()` function arguments to the options `paired` and `var.equal`.\n-   Both of these are set to FALSE by default, but we can change one or both of them to TRUE if we believe that our two samples come in pairs (a specific case of dependent samples) or the variances of the two populations are equal.\n\n> **Note**: The dependent sample t-test is also called the paired sample t-test ie: before-treatment and after-treatment patient groups in medical research.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Let's create some fake data to demonstrate paired sample t-test\n\nbefore <-c(200.1, 190.9, 192.7, 213, 241.4, 196.9, 172.2, 185.5, 205.2, 193.7)\nafter <-c(392.9, 393.2, 345.1, 393, 434, 427.9, 422, 383.9, 392.3, 352.2)\n\ndf <- data.frame( \n                group = rep(c(\"before\", \"after\"), each = 10),\n                weight = c(before,  after)\n                )\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(before, after,\n       data = df, \n       paired = TRUE,\n       conf.level=0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPaired t-test\n\ndata:  before and after\nt = -20.883, df = 9, p-value = 6.2e-09\nalternative hypothesis: true mean difference is not equal to 0\n95 percent confidence interval:\n -215.5581 -173.4219\nsample estimates:\nmean difference \n        -194.49 \n```\n\n\n:::\n:::\n\n\n\n## Exercise\n\nCompare the mean earnings of those who have and have not graduated from high school. Although you don't know the population standard deviations of earnings in each group, you determine that these are independent populations and their standard deviations must not be the same, arguing that there is a wider spread of earnings among those who graduated high school.\n\nMethod:\n\n-   You conduct an unpooled, unequal variance two sample $t$-test (the type of two sample $t$-test we explored earlier in our applications).\n\n-   You choose a significance level of 5%, the default level used.\n\n-   You set up the following hypotheses.\n\n$$\nH_{0}: \\mu_{graduated} = \\mu_{didn't \\ graduate}\n$$ \n$$\nH_{1}: \\mu_{graduated} \\neq \\mu_{didn't \\ graduate}\n$$\n\n-   Suppose a friend instead sets up a one-sided alternative, namely that $\\mu_{graduated} > \\mu_{didn't \\ graduate}$.\n\nAssuming the null hypothesis, significance level, sample data and type of test used are identical for both you and your friend, who is more likely to receive statistically significant results?\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nanswer_2 <- \"\" # your answer for \"you\" or \"your friend\" in place of \"x\" here\ntest_2()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_2 <- \"your friend\" # your answer for \"you\" or \"your friend\" in place of \"x\" here\ntest_2()\n```\n:::\n\n\n\n-   Moving forward with your two-sided hypothesis test, you find a sample mean statistic of 60000 for those who graduated high school and 25000 for those who didn't graduate high school.\n\n-   You find for your chosen significance level and distribution of sample means for each population that the resulting test statistic in your test is 1.5, while the critical values from the student's t-distribution are -2 and 2 respectively.\n\nShould you reject the null hypothesis that there is no statistically significant difference between the mean earnings of each population?\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nanswer_3 <- \"x\" # your answer for \"yes\" or \"no\" in place of \"x\" here\ntest_3()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_3 <- \"yes\" # your answer for \"yes\" or \"no\" in place of \"x\" here\ntest_3()\n```\n:::\n\n\n\n## Applications of Hypothesis Testing with Pearson's Correlation Coefficient\n\n### Pearson Correlation Test\n\nAnother parameter we can make hypotheses about is the correlation coefficient. We can use hypothesis testing to test inferences about the correlation between two variables by analyzing random samples.\n\nLet's do this with `wages` and `mrkinc`.\n\n> **Recall** two variables are highly positively correlated if their correlation coefficient is close to 1, while they are highly negatively correlated if it is close to -1.\n\nLet's suppose that we have reason to believe that `wages` and `mrkinc` are quite correlated (hence their correlation coefficient is not 0).\n\nTo find support for this, we will set this up as an alternative hypothesis to be supported after rejecting the null hypothesis that there is no correlation. To determine this we have to work to reject our null hypothesis. Let's set up the hypotheses below.\n\n$$\n{H_0}: r = 0\n$$ \n$$\n{H_1}: r \\neq 0\n$$\n\nWhere $r$ is the population correlation coefficient between the wages and market income of Canadians. Let's set the significance level at 5% (95% confidence level).\n\n$$\n\\alpha = 0.05\n$$\n\nLet's now look at our sample statistic (sample correlation coefficient) to shed some light on the number whose significance we will be testing in our hypothesis test.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# finding the cor() between wages and mrkinc, including use=\"complete.obs\" to remove NA entries\ncor(census_data$wages, census_data$mrkinc, use=\"complete.obs\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8898688\n```\n\n\n:::\n:::\n\n\n\nThis correlation coefficient appears quite far from 0, hence we will likely be able to reject the null hypothesis in favour of our alternative hypothesis of some relationship between `wages` and `mrkinc` (possibly very strongly positive relationship).\n\nHowever, there is always the small chance that we happen to have pulled a sample with a strong correlation which does not otherwise exist. To prevent this error of a false positive, let's conduct a Pearson Correlation test. Instead of having to calculate a test statistic and then calculate critical values or a $p$-value, we can just invoke the `cor.test()` function.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pearson correlation test\ncor.test(census_data$wages, census_data$mrkinc, use=\"complete.obs\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  census_data$wages and census_data$mrkinc\nt = 1142.5, df = 343061, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.8891702 0.8905632\nsample estimates:\n      cor \n0.8898688 \n```\n\n\n:::\n:::\n\n\n\nThe correlation test yields a small $p$-value of 2.2e-16 \\< $\\alpha$ = 0.05.\n\nThus, we see that this correlation is statistically significant and reject the null hypothesis in favour of the alternative hypothesis that the true correlation coefficient is not zero.\n\n## Type I and Type II Errors\n\nOne thing that is crucial to remember is that our hypothesis test may not always be correct. While a hypothesis test provides strong evidence for us to reject or fail to reject a null hypothesis, it is not concrete.\n\n<div>\n\nWe never say that we \"accept\" the null hypothesis, instead preferring to say that we \"fail to reject\" the null hypothesis when no strong evidence exists against it.</div>\n\nSimilarly, we never say that we \"accept\" the alternative hypothesis, only that we \"reject the null hypothesis in favour of the alternative hypothesis\".\n\nNeither hypothesis can conclusively be proven as true or false. Therefore, we may occasionally make incorrect decisions about rejecting or failing to reject a null hypothesis.\n\nThese errors are called **type I errors** and **type II errors**.\n\n| Null Hypothesis is... | True                                                      | False                                                    |\n|----------------------|-------------------------|-------------------------|\n| **Rejected**          | Type I Error: False Positive probability = $\\alpha$       | Correct Decision: False positive probability= $1 -\\beta$ |\n| **Not rejected**      | Correct Decision: True negative probability= $1 - \\alpha$ | Type II Error: False negative probability= $\\beta$.      |\n\n#### Type I error (false positive):\n\n-   This happens when we draw a sample statistic which appears incredibly unlikely under the null hypothesis and then **falsely assume that our null hypothesis is incorrect.** In reality, that sample statistic could have just been an unlikely pull under a true null hypothesis.\n-   It means concluding that results are **statistically significant** when, in reality, they came about purely by chance or because of unrelated factors.\n-   The probability of making a type I error is denoted by $\\alpha$ and is the significance level that we choose in the beginning.\n\n#### Type II error (false negative):\n\n-   This can occur when we pull a sample statistic which is seemingly reasonable under our null hypothesis and **falsely assume that we cannot reject the null**. In reality, that sample statistic could have just been an unlikely pull which would have otherwise encouraged us to reject the null.\n-   Probability of Type II error increases when we may **not have had enough statistical power**, such as when our sample size is too small, our level of significance is too high, or we are using a test that is not sensitive enough to detect a true difference.\n-   The probability of making a type II error is denoted as $1 - \\alpha$ or $\\beta$, while the probability of correctly rejecting a false null hypothesis is $1 - \\beta$ and is known as the power of the test.\n\n<div>\n\n> Note:\n> -   A higher confidence level and a lower significance level decreases $\\alpha$, Type I error risk, but increases $\\beta$,Type II error risk.\n> -   A higher statistical power decreases $\\beta$, Type II error risk, but increases $\\alpha$, Type I error risk.\n> -   For a fixed sample size, the smaller the $\\alpha$, the larger the $\\beta$.\n> -   Hence, there is a constant tradeoff between making type I and II errors.\n> -   Remember we select $\\alpha$ , our significance level and hence the probability of falsely rejecting a true null hypothesis before we even calculate our test statistic. However, we can never select for the probability of failing to reject a false null, $\\beta$. This probability instead emerges in the testing process.\n</div>\n\n### Exercise\n\nSuppose you choose a 5% significance level and conduct a one sample t-test with $p$-value of 0.13 and correctly reject the null hypothesis, but then conclude that the results are not statistically significant. What error have you made?\n\n\n\n::: {.cell .question}\n\n```{.r .cell-code}\nanswer_4 <- \"x\" # your answer of \"type 1\" or \"type 2\" in place of \"x\" here\ntest_4()\n```\n:::\n\n::: {.cell .answer}\n\n```{.r .cell-code}\nanswer_4 <- \"type 2\" # your answer of \"type 1\" or \"type 2\" in place of \"x\" here\ntest_4()\n```\n:::\n",
    "supporting": [
      "beginner_hypothesis_testing_files\\figure-ipynb"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}