<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-GB" xml:lang="en-GB"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.557">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alex Ronczewski">
<meta name="dcterms.date" content="2026-07-20">
<meta name="description" content="The second notebook in the Data Engineering stream, and your first job as a data analyst: the research team needs one deliverable, a regional wage briefing. On the way there you learn the core of SQL inside a single SELECT: joins and why they change row counts, GROUP BY and HAVING, the NULLs (which nearly get you fired), CASE logic, and edit many plausible-looking wrong queries. It ends with a question this notebook’s tools cannot answer.">

<title>Praxis - Basic Querying</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../media/praxis-badge.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="../../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<meta name="keywords" content="economics, econometrics, R, data, machine learning, UBC, COMET, geog 374, econ 325, econ 326, learning, teaching, learn r, r help, help, tutorial, r tutorial for beginners,learning statistics with r, learn r programming, learn statistics, linear regression, r machine learning, learn machine learning, university of british columbia, british columbia, r programming for beginners, r language tutorial, r tutorial for beginners, economic data, econometrics tutoring, economics help for students, economics homework help, oer resources for teachers, open educational resources for teachers, educational resource, oer project, oer materials, oer resources, learn economics online, learn econometrics, teach yourself economics, teach yourself econometrics, econometrics basics for beginners">

<!-- Google Search Console -->
<meta name="google-site-verification" content="wUHlRBWRzzUYwBbnKdvYg0lBpw5b0F7hnEq-QekkpQw">
<!-- End Google Search Console -->

<script>
(function() {
    function updateThemeImages() {
        var isDark = document.body.classList.contains('quarto-dark');
        var images = document.querySelectorAll('img[data-light-src][data-dark-src]');

        images.forEach(function(img) {
            var lightSrc = img.getAttribute('data-light-src');
            var darkSrc = img.getAttribute('data-dark-src');
            var newSrc = isDark ? darkSrc : lightSrc;

            // Only update if src is different to avoid reload flicker
            if (img.getAttribute('src') !== newSrc) {
                img.setAttribute('src', newSrc);
            }
        });
    }

    // Run when DOM is ready
    document.addEventListener('DOMContentLoaded', function() {
        updateThemeImages();

        // Watch for theme changes on body
        var observer = new MutationObserver(function(mutations) {
            mutations.forEach(function(mutation) {
                if (mutation.attributeName === 'class') {
                    updateThemeImages();
                }
            });
        });

        observer.observe(document.body, { attributes: true, attributeFilter: ['class'] });
    });

    // Also run after full page load
    window.addEventListener('load', updateThemeImages);
})();
</script>

<!-- Cloudflare Web Analytics -->
<script defer="" src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon="{&quot;token&quot;: &quot;911859291fee44e6ba0acc25f4f08be4&quot;}"></script>
<!-- End Cloudflare Web Analytics -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">
<!-- praxis-launch-notebook: per-notebook launch button (injected into output HTML at build time) -->
<script>
(function () {
  // Notebooks that get a launch button (path from "docs/", no extension)
  var NOTEBOOKS = [
    "docs/AMNE-376/amne_376_image_embedding",
    "docs/CTree_CEA/political_economy",
    "docs/Causal_ML/notebook_01_prediction_inference_causality",
    "docs/Causal_ML/notebook_02_regularization_ridge_lasso",
    "docs/Causal_ML/notebook_03_trees_forests_boosting",
    "docs/Causal_ML/notebook_04_prediction_to_treatment_effects",
    "docs/Causal_ML/notebook_05_post_double_selection",
    "docs/Causal_ML/notebook_06_propensity_ipw",
    "docs/Causal_ML/notebook_07_double_machine_learning",
    "docs/Causal_ML/notebook_08_heterogeneous_effects_causal_forests",
    "docs/Data_Engineer/notebook_01_why_databases_exist",
    "docs/Data_Engineer/notebook_02_basic_querying",
    "docs/Data_Engineer/notebook_03_advanced_sql",
    "docs/Data_Engineer/notebook_04_cleaning_real_data",
    "docs/Data_Engineer/notebook_05_designing_data",
    "docs/Data_Engineer/notebook_06_storage_speed_transactions",
    "docs/Data_Engineer/notebook_07_two_kinds_of_databases",
    "docs/Data_Engineer/notebook_08_pipelines_one",
    "docs/Data_Engineer/notebook_09_pipelines_two",
    "docs/Data_Engineer/notebook_10_embeddings_vector_search",
    "docs/Data_Engineer/notebook_11_capstone_rag",
    "docs/ECON-227/llm_distributions",
    "docs/Game_Theory/notebook_01_games_best_responses_nash",
    "docs/Game_Theory/notebook_02_mixed_strategies_fictitious_play",
    "docs/Game_Theory/notebook_03_repeated_games_axelrod_tournament",
    "docs/Game_Theory/notebook_04_learning_agents_collusion",
    "docs/OCR/ocr_notebook",
    "docs/SOCI-280/soci_280_bert",
    "docs/SOCI-415/cbdb_dataset",
    "docs/SOCI-415/kinmatrix",
    "docs/SOCI-415/soci_415_network_analysis",
    "docs/hist_workshop/text_embeddings_workshop",
    "docs/image_analysis/image_analysis",
    "docs/intro_to_cnns/intro_to_cnn",
    "docs/intro_to_convolutions/intro_to_convolution",
    "docs/intro_to_deep_learning/intro_to_fundamental_ML",
    "docs/intro_to_transformers/intro_to_transformers",
    "docs/text_analysis/text_analysis"
  ];

  function init() {
    var i = window.location.pathname.indexOf("/docs/");
    if (i === -1) return;
    var rel = window.location.pathname.slice(i + 1).replace(/\.html$/, "");
    if (NOTEBOOKS.indexOf(rel) === -1) return;

    var nb = rel + ".ipynb";
    var repo = "https%3A%2F%2Fgithub.com%2Fubcecon%2Fpraxis-ubc";
    var urlpath = encodeURIComponent("lab/tree/praxis-ubc/" + nb);
    var jupyter = "https://open.jupyter.ubc.ca/jupyter/hub/user-redirect/git-pull?repo=" +
      repo + "&urlpath=" + urlpath + "&branch=praxis-notebooks";
    var colab = "https://colab.research.google.com/github/ubcecon/praxis-ubc/blob/praxis-notebooks/" + nb;

    var wrap = document.createElement("div");
    wrap.className = "btn-group";
    wrap.style.margin = "0.5rem 0 1rem";
    wrap.innerHTML =
      '<button class="btn btn-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">' +
        '<i class="bi bi-play-fill"></i> Launch this notebook</button>' +
      '<ul class="dropdown-menu">' +
        '<li><a class="dropdown-item" target="_blank" rel="noopener" href="' + jupyter + '"><i class="bi bi-cloud-check"></i> JupyterOpen</a></li>' +
        '<li><a class="dropdown-item" target="_blank" rel="noopener" href="' + colab + '"><i class="bi bi-google"></i> Colab</a></li>' +
      '</ul>';

    var header = document.getElementById("title-block-header");
    if (header) {
      header.appendChild(wrap);
    } else {
      var main = document.querySelector("main.content") || document.querySelector("main");
      if (main) main.insertBefore(wrap, main.firstChild);
    }
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();
</script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../media/praxis-badge-white.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Praxis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-get-started" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Get Started</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-get-started">    
        <li>
    <a class="dropdown-item" href="../../pages/quickstart.html">
 <span class="dropdown-text">Quickstart Guide</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-courses" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Courses</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-courses">    
        <li>
    <a class="dropdown-item" href="../../pages/index/index_AMNE-376.html">
 <span class="dropdown-text">AMNE-376</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/index/index_SOCI415.html">
 <span class="dropdown-text">SOCI-415</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/index/index_SOCI280.html">
 <span class="dropdown-text">SOCI-280</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/index/index_ECON227.html">
 <span class="dropdown-text">ECON-227</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/index/index_Causal_ML.html">
 <span class="dropdown-text">Causal Machine Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/index/index_Game_Theory.html">
 <span class="dropdown-text">Game Theory</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/index/index_Data_Engineer.html">
 <span class="dropdown-text">Data Engineering</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../pages/index/all.html">
 <span class="dropdown-text">Browse All</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../pages/index/all.html"> 
<span class="menu-text">All Topics</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-teach-with-praxis" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Teach with Praxis</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-teach-with-praxis">    
        <li>
    <a class="dropdown-item" href="../../pages/teaching_with_praxis.html">
 <span class="dropdown-text">Learn how to teach with Praxis</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-launch-praxis" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      <i class="bi bi-play" role="img">
</i> 
 <span class="menu-text">Launch Praxis</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-launch-praxis">    
        <li>
    <a class="dropdown-item" href="https://open.jupyter.ubc.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fpraxis-ubc&amp;urlpath=lab%2Ftree%2Fpraxis-ubc%2F&amp;branch=praxis-notebooks"><i class="bi bi-cloud-check" role="img">
</i> 
 <span class="dropdown-text">Launch on JupyterOpen (with Data)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://open.jupyter.ubc.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fpraxis-ubc&amp;urlpath=lab%2Ftree%2Fpraxis-ubc%2F&amp;branch=praxis-notebooks"><i class="bi bi-cloud-check" role="img">
</i> 
 <span class="dropdown-text">Launch on JupyterOpen (lite)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://ubc.syzygy.ca/jupyter/hub/user-redirect/git-pull?repo=https%3A%2F%2Fgithub.com%2Fubcecon%2Fpraxis-ubc&amp;urlpath=lab%2Ftree%2Fpraxis-ubc%2F&amp;branch=praxis-notebooks"><i class="bi bi-gear" role="img">
</i> 
 <span class="dropdown-text">Launch on Syzygy</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://colab.research.google.com/github/ubcecon/praxis-ubc/blob/praxis-notebooks/"><i class="bi bi-google" role="img">
</i> 
 <span class="dropdown-text">Launch on Colab</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/ubcecon/praxis-ubc/archive/refs/heads/praxis-notebooks.zip"><i class="bi bi-cloud-download" role="img">
</i> 
 <span class="dropdown-text">Launch Locally</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/ubcecon/praxis-ubc">
 <span class="dropdown-text">Github Repository</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../#"> 
<span class="menu-text">|</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/ubcecon/praxis-ubc" target="_blank"> <i class="bi bi-github" role="img" aria-label="GitHub">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../pages/team.html">
 <span class="dropdown-text">Praxis Team</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../pages/copyright.html">
 <span class="dropdown-text">Copyright Information</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#outline" id="toc-outline" class="nav-link active" data-scroll-target="#outline">Outline</a>
  <ul class="collapse">
  <li><a href="#prerequisites" id="toc-prerequisites" class="nav-link" data-scroll-target="#prerequisites">Prerequisites</a></li>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link" data-scroll-target="#learning-outcomes">Learning Outcomes</a></li>
  </ul></li>
  <li><a href="#where-we-are-in-the-stream" id="toc-where-we-are-in-the-stream" class="nav-link" data-scroll-target="#where-we-are-in-the-stream">1. Where we are in the stream</a></li>
  <li><a href="#one-table-becomes-three" id="toc-one-table-becomes-three" class="nav-link" data-scroll-target="#one-table-becomes-three">2. One table becomes three</a></li>
  <li><a href="#sizing-up-the-data" id="toc-sizing-up-the-data" class="nav-link" data-scroll-target="#sizing-up-the-data">3. Sizing up the data</a></li>
  <li><a href="#crossing-tables-join" id="toc-crossing-tables-join" class="nav-link" data-scroll-target="#crossing-tables-join">4. Crossing tables: JOIN</a>
  <ul class="collapse">
  <li><a href="#the-inner-join" id="toc-the-inner-join" class="nav-link" data-scroll-target="#the-inner-join">4.1 The inner join</a></li>
  <li><a href="#the-left-join" id="toc-the-left-join" class="nav-link" data-scroll-target="#the-left-join">4.2 The left join</a></li>
  <li><a href="#joins-that-multiply" id="toc-joins-that-multiply" class="nav-link" data-scroll-target="#joins-that-multiply">4.3 Joins that multiply</a></li>
  </ul></li>
  <li><a href="#the-first-draft" id="toc-the-first-draft" class="nav-link" data-scroll-target="#the-first-draft">5. The first draft</a></li>
  <li><a href="#the-wrong-number-we-almost-published" id="toc-the-wrong-number-we-almost-published" class="nav-link" data-scroll-target="#the-wrong-number-we-almost-published">6. The wrong number we almost published</a></li>
  <li><a href="#comparing-fairly-case" id="toc-comparing-fairly-case" class="nav-link" data-scroll-target="#comparing-fairly-case">7. Comparing fairly: CASE</a></li>
  <li><a href="#the-final-deliverable" id="toc-the-final-deliverable" class="nav-link" data-scroll-target="#the-final-deliverable">8. The final deliverable</a></li>
  <li><a href="#the-question-we-cannot-answer-yet" id="toc-the-question-we-cannot-answer-yet" class="nav-link" data-scroll-target="#the-question-we-cannot-answer-yet">9. The question we cannot answer yet</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">10. Conclusion</a></li>
  <li><a href="#appendix-where-to-practice" id="toc-appendix-where-to-practice" class="nav-link" data-scroll-target="#appendix-where-to-practice">Appendix: where to practice</a></li>
  <li><a href="#connections" id="toc-connections" class="nav-link" data-scroll-target="#connections">Connections</a>
  <ul class="collapse">
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/ubcecon/praxis-ubc/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div><div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="notebook_02_basic_querying.ipynb" download="notebook_02_basic_querying.ipynb"><i class="bi bi-journal-code"></i>Jupyter</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Basic Querying</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Python</div>
    <div class="quarto-category">SQL</div>
    <div class="quarto-category">joins</div>
    <div class="quarto-category">data engineering</div>
  </div>
  </div>

<div>
  <div class="description">
    The second notebook in the Data Engineering stream, and your first job as a data analyst: the research team needs one deliverable, a regional wage briefing. On the way there you learn the core of SQL inside a single SELECT: joins and why they change row counts, GROUP BY and HAVING, the NULLs (which nearly get you fired), CASE logic, and edit many plausible-looking wrong queries. It ends with a question this notebook’s tools cannot answer.
  </div>
</div>


<div class="quarto-title-meta column-page-left">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Alex Ronczewski </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">20 July 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="outline" class="level2">
<h2 class="anchored" data-anchor-id="outline">Outline</h2>
<section id="prerequisites" class="level3">
<h3 class="anchored" data-anchor-id="prerequisites">Prerequisites</h3>
<ul>
<li>Notebook 1 of this stream: what a database and a DBMS are, <code>SELECT</code>, <code>WHERE</code>, <code>ORDER BY</code>, and running SQL through <code>%%sql</code> cells.</li>
</ul>
</section>
<section id="learning-outcomes" class="level3">
<h3 class="anchored" data-anchor-id="learning-outcomes">Learning Outcomes</h3>
<p>By the end of this notebook you will be able to:</p>
<ol type="1">
<li>Combine tables with <strong>inner</strong> and <strong>left joins</strong>, and predict how a join changes the number of rows.</li>
<li>Summarize data with <strong>aggregates</strong> and <code>GROUP BY</code>, and state the <strong>logical order</strong> in which SQL evaluates a query, including where <code>HAVING</code> fits.</li>
<li>Explain <strong>NULL</strong> and three-valued logic: why <code>= NULL</code> finds nothing, and how NULLs silently shape counts and averages.</li>
<li>Build categories inside a query with <code>CASE</code>.</li>
<li>Spot and fix plausible-looking wrong queries.</li>
</ol>
</section>
</section>
<section id="where-we-are-in-the-stream" class="level2">
<h2 class="anchored" data-anchor-id="where-we-are-in-the-stream">1. Where we are in the stream</h2>
<p><a href="media/NB2/stream_map.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="media/NB2/stream_map.png" class="img-fluid" style="width:85.0%" alt="Stream roadmap: four arcs, Querying data (NB1-4), Designing and storing data (NB5-7), Keeping data flowing (NB8-9), and Data for AI (NB10-11), with the current notebook highlighted."></a></p>
<p>Notebook 1 ended with us looking at one table at a time. This notebook is the core of SQL: everything an analyst does most days, and everything a screening interview asks about, built from a single <code>SELECT</code>. SQL is the language the world of data speaks, and it is far easier to learn than Python, R, C++ or any other programming language. It is truly intuitive, and with a little effort you will understand all of it. But we can make this effort fun (hopefully at least a little).</p>
<p>So instead of learning it like a manual, we will learn it on the job. You have just joined the survey’s research team as its data analyst (congratulations!!!), and the team is writing a short report on Canadian wages. One deliverable is yours: <strong>a single table, wages by region, full-time workers only, with worker counts and union shares.</strong></p>
<p>This is not a made-up type of table. Here is Statistics Canada’s version, wages and hours by union status, from the Labour Force Survey:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="media/NB2/statcan_wage_table.png" class="lightbox" data-glightbox="description: .lightbox-desc-2" data-gallery="quarto-lightbox-gallery-2" title="Statistics Canada Table 14-10-0134-01: average weekly earnings, hourly wage rate, and usual weekly hours by union status. Ours will be smaller and regional. And look at their 2025 hourly wages, 38.74 unionized and 35.37 not."><img src="media/NB2/statcan_wage_table.png" class="img-fluid figure-img" alt="Statistics Canada Table 14-10-0134-01: average weekly earnings, hourly wage rate, and usual weekly hours by union status. Ours will be smaller and regional. And look at their 2025 hourly wages, 38.74 unionized and 35.37 not."></a></p>
<figcaption>Statistics Canada Table 14-10-0134-01: average weekly earnings, hourly wage rate, and usual weekly hours by union status. Ours will be smaller and regional. And look at their 2025 hourly wages, 38.74 unionized and 35.37 not.</figcaption>
</figure>
</div>
<p>Along the way runs a <strong>wrong-query gallery</strong>: plausible-looking queries that do not do what their author wanted, sometimes with errors, but usually silently. Your colleagues will be submitting a few of these. Learning to catch them is a real skill.</p>
</section>
<section id="one-table-becomes-three" class="level2">
<h2 class="anchored" data-anchor-id="one-table-becomes-three">2. One table becomes three</h2>
<p>So far all of our data has lived in one table, and every question was answered by scanning that one table. This is the largest conceptual step from a standalone file (like a .csv) to a database.</p>
<p>A real database is almost never one big table. It is a collection of tables, where each table holds <strong>one kind of thing</strong>: one row per survey respondent, one row per province, one row per certification. The obvious question is why. Why not throw everything into a single wide table? Try it mentally with our data and it breaks in two different ways:</p>
<ul>
<li><strong>Facts about provinces would repeat once per respondent.</strong> British Columbia’s minimum wage would be stored 353 times, once in every BC row, and in the next few years when the rate changes, you would need to update all 353 copies perfectly or the data breaks. Notebook 1 named this disease: redundancy.</li>
<li><strong>Certifications do not fit the survey’s shape at all.</strong> One respondent holds three certifications, another holds none. Do you add columns <code>certification_1</code>, <code>certification_2</code>, <code>certification_3</code>, and break on the first person with four? Or repeat the person’s whole row once per certification, duplicating their wage and corrupting every average? Both options are bad, because “one row per person” is simply the wrong shape for facts that come in variable numbers per person.</li>
</ul>
<p>The relational answer is to give each kind of thing its own table, store every fact only once, and connect the tables through <strong>shared columns</strong>. Here is what our database looks like from this notebook on, drawn with real rows from each table:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="media/NB2/three_tables.png" class="lightbox" data-glightbox="description: .lightbox-desc-3" data-gallery="quarto-lightbox-gallery-3" title="The survey sits in the middle, and its two shaded columns each point into another table. The arrows trace two example matches; every other row matches the same way."><img src="media/NB2/three_tables.png" class="img-fluid figure-img" alt="The survey sits in the middle, and its two shaded columns each point into another table. The arrows trace two example matches; every other row matches the same way."></a></p>
<figcaption>The survey sits in the middle, and its two shaded columns each point into another table. The arrows trace two example matches; every other row matches the same way.</figcaption>
</figure>
</div>
<p>Read it row by row, following the arrows. Respondents 1 and 5 both live in British Columbia, so both of their rows match the same single <code>provinces</code> row: BC’s minimum wage of 17.40 is stored exactly once as well, whether 2 respondents point at it or all 353 who live there. On the other side, respondent 8 listed two certifications, so their one survey row matches two <code>certifications</code> rows. The shared columns doing the pointing, <code>province</code> on one side and <code>respondent_id</code> on the other, are called <strong>join keys</strong>, and section 4 is about the command that follows them.</p>
<p>First, the setup. We rebuild the database from the raw files so this notebook can be run alone without NB1:</p>
<div id="93b1e4d4" class="cell" data-execution_count="1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="c01280f4" class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>provinces <span class="op">=</span> pd.read_csv(<span class="st">"datasets/provinces.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>certifications <span class="op">=</span> pd.read_csv(<span class="st">"datasets/certifications.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>conn <span class="op">=</span> sqlite3.<span class="ex">connect</span>(<span class="st">"datasets/wage_survey.db"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>pd.read_csv(<span class="st">"datasets/wage_survey.csv"</span>).to_sql(<span class="st">"survey"</span>, conn, index<span class="op">=</span><span class="va">False</span>, if_exists<span class="op">=</span><span class="st">"replace"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>provinces.to_sql(<span class="st">"provinces"</span>, conn, index<span class="op">=</span><span class="va">False</span>, if_exists<span class="op">=</span><span class="st">"replace"</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>certifications.to_sql(<span class="st">"certifications"</span>, conn, index<span class="op">=</span><span class="va">False</span>, if_exists<span class="op">=</span><span class="st">"replace"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="2">
<pre><code>684</code></pre>
</div>
</div>
<p>The 684 that the cell reports is the row count of the last table written, <code>certifications</code>.</p>
<div id="9cc0d45d" class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>load_ext sql</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>config SqlMagic.autopandas <span class="op">=</span> <span class="va">True</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>config SqlMagic.displaycon <span class="op">=</span> <span class="va">False</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>config SqlMagic.feedback <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>sql sqlite:<span class="op">///</span>datasets<span class="op">/</span>wage_survey.db</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Before querying anything, look at the two new datasets side by side:</p>
<div id="4f6147ad" class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(provinces.to_string(index<span class="op">=</span><span class="va">False</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(certifications.head(<span class="dv">6</span>).to_string(index<span class="op">=</span><span class="va">False</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        province         region  minimum_wage  population
British Columbia     West Coast         17.40     5719961
         Alberta       Prairies         15.00     4980659
        Manitoba       Prairies         15.80     1507330
         Ontario Central Canada         17.20    16176977
          Quebec Central Canada         15.75     9110616

 respondent_id         certification
             2                 CPR-C
             4     First Aid Level 1
             8    Cloud Practitioner
             8 Security Fundamentals
            10     First Aid Level 1
            10                 WHMIS</code></pre>
</div>
</div>
<p>The first table, <code>provinces</code>, is a <strong>lookup table</strong> (also called a reference table): one row per province. It has only five rows, one per province, and holds values associated with each province, nothing about any individual respondent. Unlike the survey from NB1, this data is real. The minimum wages are the true legal rates in April 2025, from the Government of Canada’s minimum wage database, and the populations are Statistics Canada’s estimates for April 1, 2025; the region grouping is ours. It fits our survey through the <code>province</code> column: every respondent’s province should have a row here. It also matters for the job: the briefing wants <strong>regions</strong>, and the survey does not have a region column. This little table is where regions live.</p>
<p>The second table, <code>certifications</code>, is a new module of our simulated survey: respondents listed the job certifications they hold, one row per certification held. What one row stands for is different again, a person-certificate pair rather than a person, which is why respondents 8 and 10 each appear twice in the first six rows (respondent 8 with certifications for Cloud Practitioner and Security Fundamentals). It fits our survey through <code>respondent_id</code>, it is important to note, not all respondents had certifications: 548 of our 1,000 respondents listed none and so have no rows here at all, while others have two or three. This module is simulated because it has to be: Statistics Canada publishes real survey microdata, but public files are anonymized before release, and the respondent identifiers that link tables together, the exact thing this section teaches, are among the first things anonymization removes.</p>
<p>This three-table setup is a miniature of every production database you will ever work with: a big table of people or events, lookup tables describing the categories they belong to, and detail tables holding the facts that come in variable numbers. The rest of the notebook is about asking questions across all three.</p>
</section>
<section id="sizing-up-the-data" class="level2">
<h2 class="anchored" data-anchor-id="sizing-up-the-data">3. Sizing up the data</h2>
<p>Rule one of reporting on data: profile it before you summarize it. Nobody should publish numbers from a table they have never actually looked at, so before the briefing gets its first draft, we look into the survey. The profiling workhorse is <code>DISTINCT</code>, which removes duplicates from the result, every unique entry exactly once, and so answers the question “what does this column actually contain?”</p>
<div id="1c87decc" class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>SELECT DISTINCT province</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>FROM survey</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">province</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>British Columbia</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Ontario</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Quebec</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Manitoba</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>Alberta</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Saskatchewan</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Six provinces, each exactly once. Notebook 1’s table of typical file failures had <code>BC</code>, <code>B.C.</code>, <code>bc</code>, and <code>Britsh Columbia</code> all meaning one province; in a database with enforced categories, the same question is one keyword, and if the survey held even a single row with a new spelling, <code>DISTINCT</code> would expose it immediately.</p>
</section>
<section id="crossing-tables-join" class="level2">
<h2 class="anchored" data-anchor-id="crossing-tables-join">4. Crossing tables: JOIN</h2>
<p>The briefing wants wages by region. Wages live in <code>survey</code>, regions live in <code>provinces</code>, so we can’t use a single table to answer this question. Section 2 split our data apart and promised a command that connects it back together; this is <code>JOIN</code>, and it is the single most important idea in this notebook.</p>
<p>A <strong>join</strong> combines two tables by pairing up their rows wherever a matching rule holds. The rule almost always says that a shared column agrees on both sides, and that shared column is the <strong>join key</strong> from section 2’s diagram: <code>province</code> links the survey to <code>provinces</code>, and <code>respondent_id</code> links it to <code>certifications</code>. Use a <code>JOIN</code> whenever a question needs columns from more than one table, which in real work is most questions.</p>
<p>The classic picture of the join family looks like this, where each circle is a table and the shading marks which rows survive:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="media/NB2/join_diagram.png" class="lightbox" data-glightbox="description: .lightbox-desc-4" data-gallery="quarto-lightbox-gallery-4" title="The two on the left are this notebook’s tools: the inner join keeps only matched rows, the left join keeps everything from the left table. A right join is just a left join with the tables swapped, and a full outer join keeps everything from both sides; both are rarer, and SQLite only gained them recently."><img src="media/NB2/join_diagram.png" class="img-fluid figure-img" style="width:70.0%" alt="The two on the left are this notebook’s tools: the inner join keeps only matched rows, the left join keeps everything from the left table. A right join is just a left join with the tables swapped, and a full outer join keeps everything from both sides; both are rarer, and SQLite only gained them recently."></a></p>
<figcaption>The two on the left are this notebook’s tools: the inner join keeps only matched rows, the left join keeps everything from the left table. A right join is just a left join with the tables swapped, and a full outer join keeps everything from both sides; both are rarer, and SQLite only gained them recently.</figcaption>
</figure>
</div>
<section id="the-inner-join" class="level3">
<h3 class="anchored" data-anchor-id="the-inner-join">4.1 The inner join</h3>
<p>The syntax has three new pieces:</p>
<ol type="1">
<li><code>FROM survey AS s JOIN provinces AS p</code> names both tables and gives each a short <strong>alias</strong> (<code>s</code> and <code>p</code>), so the rest of the query can refer to them without spelling the full names out.</li>
<li><code>ON s.province = p.province</code> is the matching rule: pair up rows where the provinces agree.</li>
<li><code>s.province</code> and <code>p.province</code> are <strong>qualified</strong> column names. Both tables have a column called <code>province</code>, so every mention has to say whose it is, alias first, then a dot.</li>
</ol>
<blockquote class="blockquote">
<p><strong>Predict first.</strong> <code>survey</code> has 1,000 rows and <code>provinces</code> has 5. Before you run the next cell, commit to a number: how many rows will the join return?</p>
</blockquote>
<div id="9149d4c7" class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>SELECT s.respondent_id, s.province, p.region, p.minimum_wage</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>FROM survey AS s</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>JOIN provinces AS p ON s.province <span class="op">=</span> p.province</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">respondent_id</th>
<th data-quarto-table-cell-role="th">province</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">minimum_wage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1</td>
<td>British Columbia</td>
<td>West Coast</td>
<td>17.40</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>2</td>
<td>Ontario</td>
<td>Central Canada</td>
<td>17.20</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>3</td>
<td>Quebec</td>
<td>Central Canada</td>
<td>15.75</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>4</td>
<td>Ontario</td>
<td>Central Canada</td>
<td>17.20</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>5</td>
<td>British Columbia</td>
<td>West Coast</td>
<td>17.40</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">949</td>
<td>996</td>
<td>Ontario</td>
<td>Central Canada</td>
<td>17.20</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">950</td>
<td>997</td>
<td>Ontario</td>
<td>Central Canada</td>
<td>17.20</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">951</td>
<td>998</td>
<td>Ontario</td>
<td>Central Canada</td>
<td>17.20</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">952</td>
<td>999</td>
<td>Alberta</td>
<td>Prairies</td>
<td>15.00</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">953</td>
<td>1000</td>
<td>Quebec</td>
<td>Central Canada</td>
<td>15.75</td>
</tr>
</tbody>
</table>

<p>954 rows × 4 columns</p>
</div>
</div>
</div>
<p>Each result row is a survey row with its matching province facts attached. But read the output: <strong>954 rows</strong>. It’s not 1,000 or 5, and if you predicted either, you have just learned the most useful lesson in this section. A plain <code>JOIN</code> (an <strong>inner join</strong>) keeps only the rows that find a match, and Saskatchewan’s 46 respondents found none, because the profile in section 3 counted six provinces and our lookup table holds five. They were dropped, and nothing warned us or printed an error. If your next step were “average wage by region”, those 46 people would not exist. This is a problem and your boss would not be happy.</p>
</section>
<section id="the-left-join" class="level3">
<h3 class="anchored" data-anchor-id="the-left-join">4.2 The left join</h3>
<p>A <strong>left join</strong> keeps every row of the left table (the one named in <code>FROM</code>), matched or not, and fills the right table’s columns with NULL where no match exists. Use it in two situations: when losing unmatched rows is unacceptable (like in this case where every respondent must count), and when the unmatched rows are themselves the thing you are hunting for, because a left join is how you find out which of your rows have no partner.</p>
<div id="718c64fd" class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>SELECT s.respondent_id, s.province, p.region, p.minimum_wage</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>FROM survey AS s</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>LEFT JOIN provinces AS p ON s.province <span class="op">=</span> p.province</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>ORDER BY p.region</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">respondent_id</th>
<th data-quarto-table-cell-role="th">province</th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">minimum_wage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>40</td>
<td>Saskatchewan</td>
<td>None</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>41</td>
<td>Saskatchewan</td>
<td>None</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>45</td>
<td>Saskatchewan</td>
<td>None</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>52</td>
<td>Saskatchewan</td>
<td>None</td>
<td>NaN</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>64</td>
<td>Saskatchewan</td>
<td>None</td>
<td>NaN</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">995</td>
<td>968</td>
<td>British Columbia</td>
<td>West Coast</td>
<td>17.4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">996</td>
<td>969</td>
<td>British Columbia</td>
<td>West Coast</td>
<td>17.4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">997</td>
<td>989</td>
<td>British Columbia</td>
<td>West Coast</td>
<td>17.4</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">998</td>
<td>992</td>
<td>British Columbia</td>
<td>West Coast</td>
<td>17.4</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">999</td>
<td>995</td>
<td>British Columbia</td>
<td>West Coast</td>
<td>17.4</td>
</tr>
</tbody>
</table>

<p>1000 rows × 4 columns</p>
</div>
</div>
</div>
<p>1,000 rows, nobody dropped, and the Saskatchewan respondents sit at the top of the sort with <code>None</code> and <code>NaN</code> where a region and minimum wage should be. Those empty cells are <strong>NULLs</strong>, and in section 6 they will come very close to ruining our briefing.</p>
</section>
<section id="joins-that-multiply" class="level3">
<h3 class="anchored" data-anchor-id="joins-that-multiply">4.3 Joins that multiply</h3>
<p>So far joins have shrunk our table or preserved it. They can also make it grow.</p>
<blockquote class="blockquote">
<p><strong>Predict first.</strong> Some respondents have no rows in <code>certifications</code>, some have two or three. Will joining the survey to it return more or fewer than 1,000 rows?</p>
</blockquote>
<div id="7f25aa82" class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>SELECT s.respondent_id, s.industry, s.hourly_wage, c.certification</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>FROM survey AS s</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>JOIN certifications AS c ON s.respondent_id <span class="op">=</span> c.respondent_id</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">respondent_id</th>
<th data-quarto-table-cell-role="th">industry</th>
<th data-quarto-table-cell-role="th">hourly_wage</th>
<th data-quarto-table-cell-role="th">certification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>2</td>
<td>Health care</td>
<td>49.16</td>
<td>CPR-C</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>4</td>
<td>Education</td>
<td>26.09</td>
<td>First Aid Level 1</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>8</td>
<td>Technology</td>
<td>71.43</td>
<td>Cloud Practitioner</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>8</td>
<td>Technology</td>
<td>71.43</td>
<td>Security Fundamentals</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>10</td>
<td>Construction</td>
<td>43.31</td>
<td>First Aid Level 1</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">...</td>
<td>...</td>
<td>...</td>
<td>...</td>
<td>...</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">679</td>
<td>995</td>
<td>Construction</td>
<td>73.90</td>
<td>WHMIS</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">680</td>
<td>996</td>
<td>Manufacturing</td>
<td>27.44</td>
<td>Forklift Operator</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">681</td>
<td>997</td>
<td>Health care</td>
<td>26.41</td>
<td>CPR-C</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">682</td>
<td>998</td>
<td>Health care</td>
<td>26.25</td>
<td>CPR-C</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">683</td>
<td>998</td>
<td>Health care</td>
<td>26.25</td>
<td>First Aid Level 1</td>
</tr>
</tbody>
</table>

<p>684 rows × 4 columns</p>
</div>
</div>
</div>
<p>684 rows: the 548 respondents with no certifications vanished (inner join, no match), while respondent 8 now appears twice, once per certification, with their wage duplicated on both rows. Shrinking and multiplying at the same time. So a join can shrink a table, keep it the same size, or grow it.</p>
</section>
</section>
<section id="the-first-draft" class="level2">
<h2 class="anchored" data-anchor-id="the-first-draft">5. The first draft</h2>
<p>Time to draft the briefing. Its columns are summaries, worker counts, average wages, union shares, and summaries are what <strong>aggregates</strong> compute. An <strong>aggregate function</strong> collapses many rows into one number, and it’s the moment SQL stops returning dataframes (lists of rows) and starts returning answers. Five aggregates cover most of our daily needs: <code>COUNT</code> (how many), <code>SUM</code> (the total), <code>AVG</code> (the mean), and <code>MIN</code> and <code>MAX</code> (the extremes, which double as a quick sanity check on any numeric column). One more keyword joins them: <code>AS</code> renames an output column, and from here on nearly every query uses it, because aggregate columns otherwise come back with awkward machine-made names like <code>COUNT(*)</code>, and readable output is very valuable:</p>
<div id="d11cae6b" class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>SELECT COUNT(<span class="op">*</span>) AS respondents,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>       AVG(hourly_wage) AS avg_wage,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>       MIN(hourly_wage) AS lowest,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>       MAX(hourly_wage) AS highest</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>FROM survey</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">respondents</th>
<th data-quarto-table-cell-role="th">avg_wage</th>
<th data-quarto-table-cell-role="th">lowest</th>
<th data-quarto-table-cell-role="th">highest</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>1000</td>
<td>38.59119</td>
<td>17.4</td>
<td>113.04</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>One row summarizing our data: the survey’s average wage is 38.59 dollars, and wages run from 17.40 (British Columbia’s minimum wage) up to 113.04.</p>
<p>Whole-table summaries are not what the briefing wants; it compares groups. The tell is the word <em>by</em> or <em>per</em> in a question: average wage <strong>by</strong> province, respondents <strong>per</strong> industry. The moment you hear it, you are writing a <code>GROUP BY</code>. It splits the rows into groups, computes the aggregates once per group, and returns one row per group. Before regions, a practice draft at the province level, since it needs no join:</p>
<div id="37b9bc3e" class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>SELECT province, COUNT(<span class="op">*</span>) AS respondents, AVG(hourly_wage) AS avg_wage</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>FROM survey</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>GROUP BY province</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>ORDER BY avg_wage DESC</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">province</th>
<th data-quarto-table-cell-role="th">respondents</th>
<th data-quarto-table-cell-role="th">avg_wage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Saskatchewan</td>
<td>46</td>
<td>42.616304</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Alberta</td>
<td>125</td>
<td>40.191600</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Manitoba</td>
<td>62</td>
<td>39.101774</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Ontario</td>
<td>265</td>
<td>38.693623</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">4</td>
<td>British Columbia</td>
<td>353</td>
<td>38.209887</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">5</td>
<td>Quebec</td>
<td>149</td>
<td>36.514631</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This is a question Notebook 1 could not yet ask: average wage, by province. Before quoting the table, look at the respondent counts sitting next to the averages: Saskatchewan “leads the country” on a sample of 46 people. Printing the count beside the mean is the habit that keeps grouped averages trustworthy.</p>
<p>One clause completes the grouping toolkit. <code>WHERE</code> filters rows before they are grouped; to filter the <strong>groups themselves</strong>, by their counts or their averages, SQL has a separate keyword, <code>HAVING</code>. Why a separate keyword exists at all comes down to the order SQL evaluates a query in:</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
The order a query actually runs in
</div>
</div>
<div class="callout-body-container callout-body">
<p>You write <code>SELECT</code> first, but the engine evaluates in this order:</p>
<p><code>FROM</code> (and joins) → <code>WHERE</code> → <code>GROUP BY</code> → <code>HAVING</code> → <code>SELECT</code> → <code>ORDER BY</code> → <code>LIMIT</code></p>
<p><code>WHERE</code> runs before groups exist, so it cannot see aggregates. <code>HAVING</code> runs after, so it can. This one list resolves most beginner confusion about SQL, and asking about it is a screening-interview classic.</p>
</div>
</div>
<p>The same idea drawn out, with the order you type on the left and the order the engine runs on the right. Follow the crossing lines: <code>SELECT</code> is written first and evaluated almost last.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="media/NB2/sql_order_of_execution.png" class="lightbox" data-glightbox="description: .lightbox-desc-5" data-gallery="quarto-lightbox-gallery-5" title="The order you write a query versus the order SQL executes it. The crossing lines are exactly why WHERE cannot see aggregates and HAVING can."><img src="media/NB2/sql_order_of_execution.png" class="img-fluid figure-img" alt="The order you write a query versus the order SQL executes it. The crossing lines are exactly why WHERE cannot see aggregates and HAVING can."></a></p>
<figcaption>The order you write a query versus the order SQL executes it. The crossing lines are exactly why <code>WHERE</code> cannot see aggregates and <code>HAVING</code> can.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Wrong-query gallery #1
</div>
</div>
<div class="callout-body-container callout-body">
<p>A colleague wants the industries that pay 40 dollars an hour or more on average, and writes:</p>
<div id="fac93733" class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>SELECT industry, AVG(hourly_wage) AS avg_wage</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>FROM survey</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>WHERE AVG(hourly_wage) <span class="op">&gt;=</span> <span class="dv">40</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>GROUP BY industry</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>RuntimeError: (sqlite3.OperationalError) misuse of aggregate: AVG()
[SQL: SELECT industry, AVG(hourly_wage) AS avg_wage
FROM survey
WHERE AVG(hourly_wage) &gt;= 40
GROUP BY industry]
(Background on this error at: https://sqlalche.me/e/20/e3q8)</code></pre>
</div>
</div>
<p>This one does not fail silently: SQLite refuses to run it. Read the error message: <code>misuse of aggregate</code>. Why is an aggregate misused here?</p>
<details>
<summary>
Show / hide answer
</summary>
<p>Follow the evaluation order: <code>WHERE</code> runs before <code>GROUP BY</code>, at a point where the engine is looking at individual rows and no groups or averages exist yet, so an aggregate inside <code>WHERE</code> is meaningless and SQL rejects it. Filtering on an aggregate is exactly what <code>HAVING</code> is for. Enjoy this error, it is one of the few times SQL stops you instead of handing back a wrong number. The corrected syntax:</p>
<div id="5558071a" class="cell" data-execution_count="12">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>SELECT industry, AVG(hourly_wage) AS avg_wage</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>FROM survey</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>GROUP BY industry</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>HAVING AVG(hourly_wage) <span class="op">&gt;=</span> <span class="dv">40</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="12">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">industry</th>
<th data-quarto-table-cell-role="th">avg_wage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Construction</td>
<td>40.484393</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Finance</td>
<td>48.986667</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Public administration</td>
<td>40.421190</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>Technology</td>
<td>48.957917</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Four industries clear the bar.</p>
</details>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Your turn.</strong> The team also wants education numbers. Using only the <code>survey</code> table: for each education level, return the number of respondents and their average hourly wage, best paid group first. Start the cell with <code>%%sql</code>. If it is right, it returns 4 rows, with graduate degrees on top at just over 50 dollars an hour.</p>
</blockquote>
<div id="4176072b" class="cell" data-execution_count="13">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># your query here</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<details>
<summary>
Show / hide answer
</summary>
<div id="4d6ec9b9" class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>SELECT education, COUNT(<span class="op">*</span>) AS respondents, AVG(hourly_wage) AS avg_wage</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>FROM survey</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>GROUP BY education</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>ORDER BY avg_wage DESC</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="14">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">education</th>
<th data-quarto-table-cell-role="th">respondents</th>
<th data-quarto-table-cell-role="th">avg_wage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Graduate degree</td>
<td>121</td>
<td>50.133802</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Bachelor's degree</td>
<td>269</td>
<td>42.645465</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>College diploma</td>
<td>319</td>
<td>36.004796</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>High school</td>
<td>291</td>
<td>32.879175</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</details>
</section>
<section id="the-wrong-number-we-almost-published" class="level2">
<h2 class="anchored" data-anchor-id="the-wrong-number-we-almost-published">6. The wrong number we almost published</h2>
<p>The briefing asks for regions, not provinces, so the real draft needs section 4’s join and section 5’s grouping working together.</p>
<blockquote class="blockquote">
<p><strong>Predict first.</strong> The lookup table maps five provinces into three regions. How many rows will the regional table have?</p>
</blockquote>
<div id="f83a0e17" class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>SELECT p.region, COUNT(<span class="op">*</span>) AS workers, AVG(s.hourly_wage) AS avg_wage</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>FROM survey AS s</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>JOIN provinces AS p ON s.province <span class="op">=</span> p.province</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>GROUP BY p.region</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">workers</th>
<th data-quarto-table-cell-role="th">avg_wage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Central Canada</td>
<td>414</td>
<td>37.909396</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Prairies</td>
<td>187</td>
<td>39.830267</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>West Coast</td>
<td>353</td>
<td>38.209887</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Three regions, with sensible looking averages, a table you could paste straight into the report. Before we do, apply section 5’s habit and read the counts: 414 + 187 + 353 = 954. We surveyed 1,000 people. Where are the other 46?</p>
<p>Inner join dropped every respondent whose province has no row in <code>provinces</code>, and Saskatchewan has no row. Those people are findable, since the left join keeps them with NULL where a region should be. NULL is SQL’s marker for “no value here”, and it does not behave like a value. Watch what happens when we hunt for the missing rows with <code>WHERE</code>:</p>
<div id="279df12c" class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>SELECT s.respondent_id, s.province, p.region</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>FROM survey AS s</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>LEFT JOIN provinces AS p ON s.province <span class="op">=</span> p.province</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>WHERE p.region <span class="op">=</span> NULL</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="16">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">respondent_id</th>
<th data-quarto-table-cell-role="th">province</th>
<th data-quarto-table-cell-role="th">region</th>
</tr>
</thead>
<tbody>
</tbody>
</table>

</div>
</div>
</div>
<p>Zero rows, even though we watched 46 of them appear in section 4. The query looks correct, SQL raised no error, and the rows just aren’t there. The reason for this is that: <strong><code>= NULL</code> is never true, for anything, including NULL itself.</strong> NULL means “unknown”, and SQL’s logic is <strong>three-valued</strong>: a comparison can be true, false, or unknown, and any comparison against an unknown is itself unknown (think of this like undefined in math). <code>WHERE</code> keeps only the rows whose condition is true, so unknown is discarded just like false. Finding NULLs therefore has its own dedicated command, <code>IS NULL</code> (and its opposite, <code>IS NOT NULL</code>):</p>
<div id="cd0757e8" class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>SELECT COUNT(<span class="op">*</span>) AS missing_region</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>FROM survey AS s</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>LEFT JOIN provinces AS p ON s.province <span class="op">=</span> p.province</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>WHERE p.region IS NULL</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">missing_region</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>46</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>All 46, accounted for; excellent. Now the correct version of the regional draft. Rerun it with a left join, and <code>GROUP BY</code> does something helpful on its own: it collects all the NULLs into a group of their own:</p>
<div id="8107bdc6" class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>SELECT p.region, COUNT(<span class="op">*</span>) AS workers, AVG(s.hourly_wage) AS avg_wage</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>FROM survey AS s</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>LEFT JOIN provinces AS p ON s.province <span class="op">=</span> p.province</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>GROUP BY p.region</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">workers</th>
<th data-quarto-table-cell-role="th">avg_wage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>None</td>
<td>46</td>
<td>42.616304</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Central Canada</td>
<td>414</td>
<td>37.909396</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>Prairies</td>
<td>187</td>
<td>39.830267</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">3</td>
<td>West Coast</td>
<td>353</td>
<td>38.209887</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The <code>None</code> row is Saskatchewan, and it has the <strong>highest</strong> average wage in the table. Our three-region draft omitted 46 individuals who were the highest paid group in the survey and skewed every comparison in the process. Nothing crashed, no error warned us, and the wrong table even looked cleaner than the right one.</p>
<p>NULL causes chaos outside databases too. In 2016 a security researcher registered the custom license plate <code>NULL</code>, and whenever officers left the plate field blank on a citation, the system matched it to him:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="media/NB2/null_plate_cal.jpg" class="lightbox" data-glightbox="description: .lightbox-desc-6" data-gallery="quarto-lightbox-gallery-6" title="A real story: the researcher known as droogie told it at the DEF CON 27 security conference in 2019. Thousands of dollars of other people’s fines routed to one man, because a blank field and the string NULL are not the same thing, until some system decides they are."><img src="media/NB2/null_plate_cal.jpg" class="img-fluid figure-img" style="width:55.0%" alt="A real story: the researcher known as droogie told it at the DEF CON 27 security conference in 2019. Thousands of dollars of other people’s fines routed to one man, because a blank field and the string NULL are not the same thing, until some system decides they are."></a></p>
<figcaption>A real story: the researcher known as droogie told it at the DEF CON 27 security conference in 2019. Thousands of dollars of other people’s fines routed to one man, because a blank field and the string NULL are not the same thing, until some system decides they are.</figcaption>
</figure>
</div>
</section>
<section id="comparing-fairly-case" class="level2">
<h2 class="anchored" data-anchor-id="comparing-fairly-case">7. Comparing fairly: CASE</h2>
<p>The briefing spec says full-time workers only, and the survey has hours, not a full-time indicator column. <code>CASE</code> is SQL’s if-else, and it builds new columns out of conditions. Use it whenever the category you want to analyze does not exist as a column yet: banding a continuous variable, collapsing detailed codes into coarse groups, or building a dummy variable. Statistics Canada draws the full-time line at 30 hours a week, so let us build it (we will call it work_status) and summarize both groups:</p>
<div id="8386d516" class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>SELECT CASE WHEN weekly_hours <span class="op">&gt;=</span> <span class="dv">30</span> THEN <span class="st">'Full-time'</span> ELSE <span class="st">'Part-time'</span> END AS work_status,</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>       COUNT(<span class="op">*</span>) AS respondents,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>       AVG(hourly_wage) AS avg_wage</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>FROM survey</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>GROUP BY work_status</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">work_status</th>
<th data-quarto-table-cell-role="th">respondents</th>
<th data-quarto-table-cell-role="th">avg_wage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Full-time</td>
<td>819</td>
<td>38.718083</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Part-time</td>
<td>181</td>
<td>38.017017</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>819 full-timers, 181 part-timers, similar hourly wages. Notice the composition: <code>CASE</code> invents a column that exists nowhere in the table, and <code>GROUP BY</code> groups on it. A <code>CASE</code> can also hold many <code>WHEN</code> branches, checked top to bottom with the first match winning, which is how you band a numeric column into exclusive groups.</p>
</section>
<section id="the-final-deliverable" class="level2">
<h2 class="anchored" data-anchor-id="the-final-deliverable">8. The final deliverable</h2>
<p>We are ready! The end product we need is: wages by region, full-time workers only, with worker counts and union shares, and we will report only regions with at least 50 such workers. Two small things appear inside it. <code>ROUND(value, 2)</code> rounds a number to the given count of decimal places, two here, so the summary columns come back readable instead of trailing twelve decimals. And for the union share we will do a simple trick: <code>union_member</code> holds 0 or 1, and the average of a 0/1 column is a share, so <code>AVG(s.union_member)</code> is exactly the union share we need.</p>
<div id="e4cd4857" class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>SELECT p.region,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>       COUNT(<span class="op">*</span>) AS workers,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>       ROUND(AVG(s.hourly_wage), <span class="dv">2</span>) AS avg_wage,</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>       ROUND(AVG(s.union_member), <span class="dv">2</span>) AS union_share</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>FROM survey AS s</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>LEFT JOIN provinces AS p ON s.province <span class="op">=</span> p.province</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>WHERE s.weekly_hours <span class="op">&gt;=</span> <span class="dv">30</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>GROUP BY p.region</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>HAVING COUNT(<span class="op">*</span>) <span class="op">&gt;=</span> <span class="dv">50</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>ORDER BY avg_wage DESC</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">region</th>
<th data-quarto-table-cell-role="th">workers</th>
<th data-quarto-table-cell-role="th">avg_wage</th>
<th data-quarto-table-cell-role="th">union_share</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>Prairies</td>
<td>157</td>
<td>39.83</td>
<td>0.25</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">1</td>
<td>Central Canada</td>
<td>343</td>
<td>38.34</td>
<td>0.30</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">2</td>
<td>West Coast</td>
<td>283</td>
<td>38.16</td>
<td>0.26</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Read it in evaluation order, the same list from section 5: the join builds person-region rows, <code>WHERE</code> keeps the 819 full-timers, <code>GROUP BY</code> folds them into regions, <code>HAVING</code> keeps regions with 50 or more, <code>SELECT</code> computes and rounds the summaries, and <code>ORDER BY</code> sorts the surviving entries.</p>
<blockquote class="blockquote">
<p><strong>Think Deeper.</strong> <code>AVG(union_member)</code> works because the mean of a dummy variable is a proportion. You have used this fact all through your econometrics education: it is why a regression of a 0/1 outcome on a constant returns the sample share. The trick carries over to any yes/no column you encounter.</p>
</blockquote>
<p>One thing to consider: Saskatchewan’s full-timers, 36 of them, formed a NULL-region group, and the 50-worker floor in <code>HAVING</code> dropped it. That is the same group that we lost in section 6, but with one difference: this time we know, we chose the threshold, and we state this clearly in the meeting and final report. Dropping data can be okay, and sometimes it’s the correct choice outright. Dropping data without knowing is how wrong numbers get published and is always bad.</p>
</section>
<section id="the-question-we-cannot-answer-yet" class="level2">
<h2 class="anchored" data-anchor-id="the-question-we-cannot-answer-yet">9. The question we cannot answer yet</h2>
<p>The report is out, and a co-worker immediately asks the natural follow-up: <strong>do certified workers earn more?</strong> We have a certifications table; it feels like one join away.</p>
<p>It depends on a definition. The <strong>grain</strong> of a table is what one row stands for. In <code>survey</code>, a row is a person; in the certification join from section 4.3, a row is a person-certification pair. Aggregates count rows, so they answer questions at the grain of the table they are given, whether or not that is the question you asked.</p>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Wrong-query gallery #2
</div>
</div>
<div class="callout-body-container callout-body">
<p>How many respondents hold at least one certification? A colleague joins and counts:</p>
<div id="2d6db118" class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>SELECT COUNT(<span class="op">*</span>) AS certified_respondents</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>FROM survey AS s</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>JOIN certifications AS c ON s.respondent_id <span class="op">=</span> c.respondent_id</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">certified_respondents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>684</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>684 certified respondents. What is wrong, and what is the real number?</p>
<details>
<summary>
Show / hide answer
</summary>
<p>684 is the number of <strong>certifications</strong>, because the join has one row per person-certification pair and respondent 8 is being counted once per certificate. The question asks about people, and <code>COUNT(DISTINCT s.respondent_id)</code> counts each person once. Whenever a query involves a join, decide what one row means before you aggregate. The corrected syntax:</p>
<div id="4690c581" class="cell" data-execution_count="22">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>SELECT COUNT(DISTINCT s.respondent_id) AS certified_respondents</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>FROM survey AS s</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>JOIN certifications AS c ON s.respondent_id <span class="op">=</span> c.respondent_id</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">certified_respondents</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>452</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The real number is 452.</p>
</details>
</div>
</div>
<p>Counting people was rescued by <code>COUNT(DISTINCT ...)</code>. The average wage is where this breaks:</p>
<div id="f163db76" class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="op">%%</span>sql</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>SELECT AVG(s.hourly_wage) AS avg_wage_certified</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>FROM survey AS s</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>JOIN certifications AS c ON s.respondent_id <span class="op">=</span> c.respondent_id</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="23">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">avg_wage_certified</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">0</td>
<td>39.894459</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>39.89 dollars an hour, and we know before publication that it is computed at the wrong grain: every multi-certificate respondent’s wage is counted once per certificate, so the heavily certified pull the average toward themselves. What we want is the average over <strong>one row per certified person</strong>. With this notebook’s tools, a single <code>SELECT</code>, we are stuck. You would need to first collapse the join down to one row per person, and then average the result, which means running a query on the output of another query. A query inside a query.</p>
<p>That is exactly where Notebook 3 begins.</p>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">10. Conclusion</h2>
<p>The briefing shipped, and it was correct! Getting one table right took joins, aggregates, group filters, a manufactured column, and three close calls: a hunt for missing rows that came back empty because <code>= NULL</code> is never true, an inner join that deleted the best-paid group in the data, and a count taken at the wrong grain. They were queries that ran without throwing an error.</p>
<p>Thanks for sticking with me; SQL is the language of modern data and databases. It is a useful skill and the language itself is very human-readable with limited obfuscations and weird issues (most of which we discussed above). The coming notebooks will be more fun with more interesting real life examples. This notebook was much more computer science and code syntax, but it is worth it! With a little more practice you can write SQL as a skill on your resume and a whole bunch of jobs after graduation open up for you.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
You can now answer these interview questions
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>What is the difference between an inner join and a left join, and how can a join change the number of rows?</li>
<li>Why can <code>COUNT(column)</code> be smaller than <code>COUNT(*)</code>?</li>
<li>When do you filter with <code>WHERE</code> and when with <code>HAVING</code>?</li>
<li>Why does <code>WHERE x = NULL</code> return nothing, and what do you write instead?</li>
</ul>
<details>
<summary>
Show / hide model answers
</summary>
<ul>
<li>An inner join keeps only rows that find a match; a left join keeps every left-table row and fills unmatched columns with NULL. Row counts shrink when rows fail to match, and grow when a row matches several partners, one output row per matching pair.</li>
<li><code>COUNT(*)</code> counts rows; <code>COUNT(column)</code> counts only non-NULL values in that column, so every NULL widens the gap.</li>
<li><code>WHERE</code> filters individual rows before grouping and cannot see aggregates; <code>HAVING</code> filters whole groups after <code>GROUP BY</code> and can.</li>
<li>Comparisons with NULL evaluate to unknown rather than true, so the filter keeps nothing; write <code>x IS NULL</code> (or <code>x IS NOT NULL</code>).</li>
</ul>
</details>
</div>
</div>
</section>
<section id="appendix-where-to-practice" class="level2">
<h2 class="anchored" data-anchor-id="appendix-where-to-practice">Appendix: where to practice</h2>
<p>Everything in this notebook is interview material, and the way to make it permanent is repetitions on someone else’s data and questions. Three free sites are the standard tools:</p>
<ul>
<li><a href="https://datalemur.com">DataLemur</a>: SQL questions taken from real company interviews, with a generous free tier.</li>
<li><a href="https://www.stratascratch.com">StrataScratch</a>: interview questions you can solve in SQL or Python <code>pandas</code>.</li>
<li><a href="https://leetcode.com/studyplan/top-sql-50/">LeetCode SQL 50</a>: the classic curated list; its easy tier maps almost exactly onto this notebook.</li>
</ul>
<p>You are ready for the easy tier of all three right now: it is <code>SELECT</code>, <code>WHERE</code>, joins, and <code>GROUP BY</code>, which is what we just learned.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="media/NB2/data_lemur.png" class="lightbox" data-glightbox="description: .lightbox-desc-7" data-gallery="quarto-lightbox-gallery-7" title="DataLemur’s question board. Read the tag cloud on the right: Aggregate Functions, Joins, Distinct and Unique Handling, Null Handling, Conditional Logic. Every one of those tags is a section of this notebook."><img src="media/NB2/data_lemur.png" class="img-fluid figure-img" alt="DataLemur’s question board. Read the tag cloud on the right: Aggregate Functions, Joins, Distinct and Unique Handling, Null Handling, Conditional Logic. Every one of those tags is a section of this notebook."></a></p>
<figcaption>DataLemur’s question board. Read the tag cloud on the right: Aggregate Functions, Joins, Distinct and Unique Handling, Null Handling, Conditional Logic. Every one of those tags is a section of this notebook.</figcaption>
</figure>
</div>
</section>
<section id="connections" class="level2">
<h2 class="anchored" data-anchor-id="connections">Connections</h2>
<ul>
<li><strong>Back to <a href="../../docs/Data_Engineer/notebook_01_why_databases_exist.html">Notebook 1</a>:</strong> there we built the database and asked one-table questions; here the database grew to three tables.</li>
<li><strong>Forward to <a href="../../docs/Data_Engineer/notebook_03_advanced_sql.html">Notebook 3</a>:</strong> the certified-wage question needs a query that runs on the output of another query. Subqueries, CTEs, and views, window functions, changing data with INSERT and UPDATE, and how to run SQL from Python safely, including what a SQL injection is.</li>
</ul>
<section id="references" class="level3">
<h3 class="anchored" data-anchor-id="references">References</h3>
<ul>
<li>Government of Canada. <em>Current and forthcoming general minimum wage rates in Canada.</em> https://minwage-salairemin.service.canada.ca/en/general.html The source of the minimum wages in <code>provinces.csv</code> (rates in force April 2025).</li>
<li>Malan, D. (2024). <em>CS50’s Introduction to Databases with SQL.</em> Harvard University. https://cs50.harvard.edu/sql/ (Lecture 1, Relating, covers joins.)</li>
<li>ThoughtSpot (formerly Mode). <em>SQL tutorial.</em> https://www.thoughtspot.com/sql-tutorial A free reference that extends everything here.</li>
<li>SQLite. <em>The SELECT statement.</em> https://www.sqlite.org/lang_select.html</li>
<li>SQLite. <em>NULL handling in SQLite.</em> https://www.sqlite.org/nulls.html Three-valued logic, from the engine’s own documentation.</li>
<li>Statistics Canada. <em>Average weekly earnings, average hourly wage rate and average usual weekly hours by union status, annual.</em> Table 14-10-0134-01. https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1410013401 The real-world version of this notebook’s deliverable, shown in section 1.</li>
<li>Statistics Canada. (2025). <em>Canada’s population estimates, first quarter 2025.</em> The Daily, June 18, 2025. https://www150.statcan.gc.ca/n1/daily-quotidien/250618/dq250618a-eng.htm The source of the populations in <code>provinces.csv</code>.</li>
</ul>
<hr>


<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-2">Statistics Canada Table 14-10-0134-01: average weekly earnings, hourly wage rate, and usual weekly hours by union status. Ours will be smaller and regional. And look at their 2025 hourly wages, 38.74 unionized and 35.37 not.</span>
<span class="glightbox-desc lightbox-desc-3">The survey sits in the middle, and its two shaded columns each point into another table. The arrows trace two example matches; every other row matches the same way.</span>
<span class="glightbox-desc lightbox-desc-4">The two on the left are this notebook’s tools: the inner join keeps only matched rows, the left join keeps everything from the left table. A right join is just a left join with the tables swapped, and a full outer join keeps everything from both sides; both are rarer, and SQLite only gained them recently.</span>
<span class="glightbox-desc lightbox-desc-5">The order you write a query versus the order SQL executes it. The crossing lines are exactly why <code>WHERE</code> cannot see aggregates and <code>HAVING</code> can.</span>
<span class="glightbox-desc lightbox-desc-6">A real story: the researcher known as droogie told it at the DEF CON 27 security conference in 2019. Thousands of dollars of other people’s fines routed to one man, because a blank field and the string NULL are not the same thing, until some system decides they are.</span>
<span class="glightbox-desc lightbox-desc-7">DataLemur’s question board. Read the tag cloud on the right: Aggregate Functions, Joins, Distinct and Unique Handling, Null Handling, Conditional Logic. Every one of those tags is a section of this notebook.</span>
</div>
</section>
</section>

</main> <!-- /main -->
<button id="scroll-to-top" aria-label="Back to top">
  <svg width="18" height="18" viewbox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
    <path d="M12 19V5M12 5L5 12M12 5L19 12" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"></path>
  </svg>
</button>

<style>
#scroll-to-top {
  position: fixed;
  bottom: 28px;
  right: 28px;
  z-index: 999;

  display: flex;
  align-items: center;
  justify-content: center;
  width: 44px;
  height: 44px;
  padding: 0;
  border: none;
  border-radius: 50%;

  /* Follows the active Comet theme (light/dark) automatically,
     since these are the same Bootstrap vars compiled from
     comet_theme.scss / comet_theme_dark.scss */
  background-color: var(--bs-primary, #041746);
  color: #FFFFFF;

  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.25);
  cursor: pointer;

  opacity: 0;
  visibility: hidden;
  transform: translateY(10px);
  transition: opacity 0.2s ease, transform 0.2s ease, background-color 0.2s ease;
}

#scroll-to-top.is-visible {
  opacity: 1;
  visibility: visible;
  transform: translateY(0);
}

#scroll-to-top:hover,
#scroll-to-top:focus-visible {
  background-color: var(--bs-secondary, #CC7A00);
  outline: none;
}

#scroll-to-top svg {
  width: 18px;
  height: 18px;
}

/* Tooltip shown on hover/focus, to the left so it stays in the viewport */
#scroll-to-top::after {
  content: "Back to top";
  position: absolute;
  right: calc(100% + 10px);
  top: 50%;
  transform: translateY(-50%);
  white-space: nowrap;
  padding: 4px 10px;
  border-radius: 6px;
  background-color: rgba(0, 0, 0, 0.8);
  color: #FFFFFF;
  font-size: 0.8rem;
  opacity: 0;
  visibility: hidden;
  transition: opacity 0.2s ease;
  pointer-events: none;
}

#scroll-to-top:hover::after,
#scroll-to-top:focus-visible::after {
  opacity: 1;
  visibility: visible;
}

@media (max-width: 768px) {
  #scroll-to-top {
    bottom: 20px;
    right: 16px;
    width: 40px;
    height: 40px;
  }
}
</style>

<script>
(function () {
  var btn = document.getElementById("scroll-to-top");
  if (!btn) return;

  var toggleVisibility = function () {
    if (window.scrollY > 300) {
      btn.classList.add("is-visible");
    } else {
      btn.classList.remove("is-visible");
    }
  };

  window.addEventListener("scroll", toggleVisibility, { passive: true });
  toggleVisibility();

  btn.addEventListener("click", function () {
    window.scrollTo({ top: 0, behavior: "smooth" });
  });
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png"></a>.  <a rel="license" href="https://ubcecon.github.io/comet-open/pages/copyright.html">See details.</a>
  </li>  
</ul>
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/ubcecon/praxis-ubc/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
 The Praxis Project and UBC are located on the traditional, ancestral and unceded territory of the xʷməθkʷəy̓əm (Musqueam) and Sḵwx̱wú7mesh (Squamish) peoples.
  </li>  
</ul>
    </div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"loop":false,"openEffect":"zoom","descPosition":"bottom","closeEffect":"zoom","selector":".lightbox"});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




</body></html>