---
title: "prAxIs Team"
date: 2025-07-07
published-title: Last Updated
title-block-banner: false
filters:
  - collapse-callout
collapse-callout:
  note: true
---

<span style="color:#CC7A00;font-size:18.0pt"> The prAxIs project is a true team effort; the learning materials that you see here have taken input from many writers, coders, editors, and reviewers from a variety of disciplines. </span>  

> You can contact the prAxIs team at **ADD EMAIL**

## Principal Investigators

* [Jonathan Graves](https://jonathanlgraves.arts.ubc.ca/)
* [Laura Nelson](https://sociology.ubc.ca/profile/laura-nelson/)

## Research Assistants
::: {.column width="30%"}
<span style="color:#CC7A00"> **Summer 2025** </span>  
<li> Irene Berezin </li>
<li> Alex Ronczewski </li>
<li> Kaiyan Zhang </li>
<li> Jalen Faddick </li>
<li> Yash Mali </li>
<li> Anna Kovtunenko </li>
<li> Krishaant Pathmanathan </li>
<li> Katherine Karapetrovic </li>

:::

## prAxIs+ Partners

* **UBC's Department of Economics**:  [**Vancouver School of Economics**](https://economics.ubc.ca/)
* **UBC's Department of Sociology** and the [**Center for Computational Social Science**](https://ccss.arts.ubc.ca/): [Laura K. Nelson](https://sociology.ubc.ca/profile/laura-nelson/)

## Special Thanks

* The [UBC TLEF](https://tlef.ubc.ca/) team, especially [Jeff Miller](https://ctlt.ubc.ca/2022/11/15/jeff-miller/) and [Jason Myers](https://ctlt.ubc.ca/2022/11/15/jason-myers/).
* The team behind [QuantEcon](https://quantecon.org/), especially [Jesse Perla](https://economics.ubc.ca/profile/jesse-perla/) and [Peifan Wu](https://twitter.com/peifanwu) for their advice and support.
* The [UBC CTLT](https://ctlt.ubc.ca/), [Arts ISIT](https://isit.arts.ubc.ca/), and [LT Hub](https://lthub.ubc.ca/) Teams, for their support with Jupyter and GitLab, especially [Stephen Michaud](https://ctlt.ubc.ca/2022/11/09/stephen-michaud/), [Nausheen Shafiq](https://ctlt.ubc.ca/2022/11/03/nausheen-shafiq/), [Michael Ha](https://www.linkedin.com/in/michaelha/?originalSubdomain=ca) and [Lenny Mah](https://www.linkedin.com/in/lenny-mah-ab8658182/?originalSubdomain=ca).
* The UBC DataScience Slack and the Jupyter team, especially [Tiffany Timbers](https://www.stat.ubc.ca/users/tiffany-timbers), [Phil Austin](https://www.eoas.ubc.ca/people/philaustin), [Firas Moosvi](https://cmps.ok.ubc.ca/about/contact/firas-moosvi/), and the presenters and attendees at JupyterDays 2020
* The staff at the VSE for facilitating events, payments, and space use, especially [Maria Smith](https://economics.ubc.ca/profile/maria-smith/) and [Caroline Gatchalian](https://economics.ubc.ca/profile/caroline-gatchalian/)
* Plus many, many, more!