{
  "hash": "0d784cb6ba9809564b74f01fb9040204",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"13 - Good Regression Practice\"\nauthor: Marina Adshade, Paul Corcuera, Giulia Lo Forte, Jane Platt\ndate: 2024-05-29\ndescription: This notebook covers some good practices that should be implemented when we perform regression analysis. We look at how to handle outliers, multicollinearity, heteroskedasticity, and nonlinearity. \ncategories: [econ 490, r, outliers, winsorizing, trimming, multicollinearity, heteroskedasticity, nonlinearity]\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html: default\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: R\n        language: r\n        name: ir\nimage: /media/comet_placeholder.png\n---\n\n\n## Prerequisites\n\n1. Importing data into R.\n2. Creating new variables in R.\n3. Running OLS regressions.\n\n## Learning Outcomes\n\n1. Identify and correct for outliers by trimming or winsorizing the dependent variable. \n2. Identify and correct for the problem of multicollinearity.\n3. Identify and correct for the problem of heteroskedasticity. \n4. Identify and correct for the problem of non-linearity. \n\n## 13.1 Dealing with Outliers \n\nImagine that we have constructed a dependent variable which contains the earnings growth of individual workers and we see that some worker's earnings increased by more than 400%. We might wonder if this massive change is just a coding error made by the statisticians that produced the data set. Even without that type of error, though, we might worry that the earnings growth of a small number of observations are driving the results of our analysis. If this is the case, we are producing an inaccurate analysis based on results that are not associated with the majority of our observations. \n\nThe standard practice in these cases is to either winsorize or trim the subset of observations that are used in that regression. Both practices remove the outlier values in the dependent variable to allow us to produce a more accurate empirical analysis. \n\n<div class=\"alert alert-block alert-warning\">\n    \n**Warning:** We should only consider fixing outliers when there is a clear reason to address this issue. Do not apply the tools below if the summary statistics in your data make sense to you in terms of abnormal values. For example, outliers might be a sign that our dependent and explanatory variables have a non-linear relationship. If that is the case, we will want to consider including an interaction term that addresses that non-linearity. A good way to test for this is to create a scatter plot of our dependent and independent variables. This will help us to see if there are actually some outliers, or if there is just a non-linear relationship. </div>\n\n### 13.1.1 Winsorizing a Dependent Variable\n\nWinsorizing is the process of limiting extreme values in the dependent variable to reduce the effect of (possibly erroneous) outliers. It consists of replacing values below the $a$th percentile by that percentile's value, and values above the $b$th percentile by that percentile's value. Consider the following example using our fake data set:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Clear the memory from any pre-existing objects\nrm(list=ls())\n\n# loading in our packages\nlibrary(tidyverse) #This includes ggplot2! \n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   4.0.3     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.4     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(haven)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'haven' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(IRdisplay)\n\n#Open the dataset \nfake_data <- read_dta(\"../econ490-r/fake_data.dta\")  \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nquantile(fake_data$earnings, probs = c(0.01, 0.99))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1%        99% \n  2831.027 607140.324 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmin(fake_data$earnings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 36.19316\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmax(fake_data$earnings)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 63573580\n```\n\n\n:::\n:::\n\n\n\nFrom the summary statistics above, we can see that that the income earned by the individual at the 1st percentile is 2,831.03 and that the lowest earner in the data set earned 8.88.  \n\nWe can also see that income earned by the individual at the 99th percentile is only 607,140.32 and that the highest earner in the data earned over 60 millions!\n\nThese facts suggest to us that there are large outliers in our dependent variable.\n\nWe want to get rid of these outliers by winsorizing our data set. What that means is replacing the earnings of all observations below the 1st percentile by exactly the earnings of the individual at the 1st percentile, and replacing the earnings of all observations above the 99th percentile by exactly the earnings of the individual at the 99th percentile. \n\nTo winsorize this data, we do the following 3 step process:\n\n1. We create a new variable called *earnings_winsor* which is identical to our _earnings_ variable using `mutate`. We choose to store the winsorized version of the dependent variable in a different variable so that we don't overwrite the original data set. \n2. If earnings are smaller than the 1st percentile, we replace the values of *earnings_winsor* with the earnings of the individual at the 1st percentile: `(quantile(fake_data$earnings, probs = 0.01) = 2831)`.\n3. If earnings are larger than the 99th percentile, we replace the values of *earnings_winsor* with the earnings of the individual at the 99th percentile: `(quantile(fake_data$earnings, probs = 0.99) = 607140 )`.\n\nThe values of this new variable will be created using the command `ifelse()`. If earnings are less than 2831, the value of *earnings_winsor* is replaced by 2831 using this command.\n\nWe do this below:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfake_data <- fake_data %>%\n  mutate(earnings_winsor = ifelse(earnings<2831, 2831,  ifelse(earnings>607140, 607140, earnings))) \n```\n:::\n\n\n\nNow we will use this new dependent variable in our regression analysis. If the outliers were not creating problems, there will be no change in the results. If they were creating problems, those problems will now be fixed. \n\nLet's take a look at this by first running the regression from [Module 10](https://comet.arts.ubc.ca/docs/Research/econ490-r/10_Linear_Reg.html) with the original earning variable. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Generate the log of earnings_winsor\nfake_data <- fake_data %>%\n  mutate(log_earnings_winsor = log(earnings_winsor)) \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Run the regression from Module 10\nlm(data=fake_data, log(earnings) ~ as.factor(sex))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(earnings) ~ as.factor(sex), data = fake_data)\n\nCoefficients:\n    (Intercept)  as.factor(sex)M  \n        10.2428           0.5588  \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Run the previous regression with the log of earnings_winsor\nlm(data=fake_data, log_earnings_winsor ~ as.factor(sex))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_earnings_winsor ~ as.factor(sex), data = fake_data)\n\nCoefficients:\n    (Intercept)  as.factor(sex)M  \n        10.2556           0.5434  \n```\n\n\n:::\n:::\n\n\n\nDo you think that in this case the outliers were having a significant impact before being winsorized?\n\n### 13.1.2 Trimming a Dependent Variable \n\nTrimming consists of replacing both values below the $a$th percentile and values above the $b$ percentile by a missing value. This is done to exclude these outliers from regression, since R automatically excluedes missing (`NA`) observations in the `lm` command.\n\nBelow, we look at the commands for trimming a variable. Notice that the steps are quite similar to when we winsorized the same variable. Here, we are directly creating the log of trimmed earnings in one step. Don't forget to create a new variable to avoid overwriting our original variable!\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfake_data <- fake_data %>%\n        mutate(log_earnings_trimmed = ifelse(earnings<2831 ,  NA,  ifelse( earnings  > 607140 , NA, log(earnings)))) \n```\n:::\n\n\n\nAnd here is the result of the regression with the new dependent variable:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(data=fake_data, log_earnings_trimmed ~ as.factor(sex))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_earnings_trimmed ~ as.factor(sex), data = fake_data)\n\nCoefficients:\n    (Intercept)  as.factor(sex)M  \n        10.3056           0.4791  \n```\n\n\n:::\n:::\n\n\n\n## 13.2 Multicollinearity \n\nIf two variables are linear combinations of one another they are multicollinear. Ultimately, R does not allow us to include two variables in a regression that are perfect linear combinations of one another, such as a constant or a dummy variable for male and a dummy for female (since female = 1 - male). In all of the regressions above, we see that one of those variables was dropped from the regression \"because of collinearity\".\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfake_data <- fake_data %>%\n        mutate(male = case_when(sex == 'M' ~ 1, sex == 'F' ~ 0)) %>%\n        mutate(female = case_when(sex == 'F' ~ 1, sex == 'M' ~ 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlm(data=fake_data, log_earnings_trimmed ~ male + female)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_earnings_trimmed ~ male + female, data = fake_data)\n\nCoefficients:\n(Intercept)         male       female  \n    10.3056       0.4791           NA  \n```\n\n\n:::\n:::\n\n\n\nIs this a problem? Not really. Multicollinearity is a sign that a variable is not adding any new information. Notice that with the constant term and a male dummy we can know the mean earnings of females. In this case, the constant term is, by construction, the mean earnings of females, and the male dummy gives the earning premium paid to male workers.\n\nWhile there are some statistical tests for multicollinearity, nothing beats having the right intuition when running a regression. If there is an obvious case where two variables contain basically the same information, we'll want to avoid including both in the analysis. \n\nFor instance, we might have an age variable that includes both years and months (e.g. if a baby is 1 year and 1 month old, then this age variable would be coded as 1 + 1/12 = 1.083). If we include this variable in a regression that also includes an age variable for only years (e.g the baby's age would be coded as 1) then we would have the problem of multicollinearity. Because they are not perfectly collinear, R might still produce some results, but the coefficients on these two variables would be biased. \n\n## 13.3 Heteroskedasticity \n\nWhen we run a linear regression, we essentially split the outcome into a (linear) part explained by observables ($x_i$) and an error term ($e_i$):\n\n$$\ny_i = a + b x_i + e_i\n$$ \n\nThe standard errors in our coefficients depend on $e_i^2$ (as you might remember from your econometrics courses). Heteroskedasticity refers to the case where the variance of this projection error depends on the observables $x_i$. For instance, the variance of wages tends to be higher for people who are university educated (some of these people have very high wages) whereas it is small for people who are non-university educated (these people tend to be concentrated in lower paying jobs). R by default assumes that the variance does not depend on the observables, which is known as homoskedasticity. It is safe to say that this is an incredibly restrictive assumption.\n\nWhile there are tests for heteroskedasticity, the more empirical economists rely on including heteroskedastic consistent standard errors as a default in their regressions. The most standard way to do this is to use `feols`, another command similar to `lm()` that comes from the `fixest` package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#uncomment this line to install the package! install.packages('fixest')\nlibrary(fixest)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel = feols(log_earnings_trimmed ~ as.factor(sex) , fake_data)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNOTE: 2,764 observations removed because of NA values (LHS: 2,764).\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model, vcov=\"HC1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOLS estimation, Dep. Var.: log_earnings_trimmed\nObservations: 135,374\nStandard-errors: Heteroskedasticity-robust \n                 Estimate Std. Error   t value  Pr(>|t|)    \n(Intercept)     10.305585   0.006100 1689.4826 < 2.2e-16 ***\nas.factor(sex)M  0.479062   0.006878   69.6463 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 1.0373   Adj. R2: 0.035154\n```\n\n\n:::\n:::\n\n\n\nBest practices are simply to always use robust standard errors in your own research project, since most standard errors will be heteroskedastic.\n\n## 13.4 Non-linearity\n\nOur regression analysis so far assumes that the relationship between our explained and explanatory variables is linear. If this is not the case, meaning the relationship is non-linear, then we will get inaccurate results from our analysis. \n\nLet's consider an example. We know that earnings increases with age, but what if economic theory predicts that earnings increase by more for each year of age when workers are younger than when they are older? What we are asking here is whether earnings is increasing with age at a decreasing rate. In essence, we want to check whether there is a concave relation between age and earnings. We can think of several mechanisms for why this relationship might exist: for a young worker, as they age, they get higher wages through increased experience in the job; for an older worker, as they age, those wage increases will be smaller as there are smaller productity gains with each additional year working. In fact, if the productivity of workers decreaseas as they age, perhaps for reasons related to health, then it is possible to find a negative relationship between age and earning beyond a certain age -- the relationship would be an inverted U-shape.\n\nWe could check if this is the case in our model by including a new interaction term that is simply age interacted with itself, which is the equivalent of including age and age squared. We learned how to do this in [Module 12](https://comet.arts.ubc.ca/docs/Research/econ490-r/12_Dummy.html). Let's include this in the regression above.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfake_data <- fake_data %>% mutate(age2 = age^2) \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel = lm(log_earnings_trimmed ~ age + age2, fake_data)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model, vcov=\"HC1\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log_earnings_trimmed ~ age + age2, data = fake_data)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.79059 -0.72862  0.00703  0.73487  2.89202 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  9.009e+00  8.901e-02  101.22   <2e-16 ***\nage          6.691e-02  4.007e-03   16.70   <2e-16 ***\nage2        -6.450e-04  4.435e-05  -14.54   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.053 on 135371 degrees of freedom\n  (2764 observations deleted due to missingness)\nMultiple R-squared:  0.005464,\tAdjusted R-squared:  0.00545 \nF-statistic: 371.9 on 2 and 135371 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\nThere does seem to be some evidence in our regression results that this economic theory is correct, since the coefficient on the interaction term is both negative and statistically significant.\n\nHow do we interpret these results? Let's think about the equation we have just estimated:\n$$\nEarnings_i = \\beta_0 + \\beta_1 Age_i + \\beta_2 Age^2_i + \\varepsilon_i \n$$\n\nThis means that earnings of an individual change in the following way with their age:\n$$\n\\frac{\\partial Earnings_i}{\\partial Age_i} = \\beta_1 + 2 \\beta_2 Age_i\n$$\n\nDue to the quadratic term, as age changes, the relationship between age and earnings changes as well.\n\nWe have just estimated $\\beta_1$ to be positive and equal to 0.079, and $\\beta_2$ to be negative and equal to 0.001.\n\nThis means that, as age increases, it's correlation with earnings decrease:\n$$\n\\frac{\\partial Earnings_i}{\\partial Age_i} = 0.079 - 0.002 Age_i\n$$\n\nSince the marginal effect changes with the size of $Age_i$, providing one unique number for the marginal effect becomes difficult.\n\nThe most frequently reported version of this effect is the \"marginal effect at the means\": the marginal effect of age on earnings when age takes its average value. In our case, this will be equal to 0.079 minus 0.002 times the average value of age.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(fake_data$age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 45.16033\n```\n\n\n:::\n:::\n\n\n\nSince the average age of workers is 45, the marginal effect of age at the means is \n$$\n0.079 - 2 * 0.001 * 45 = -0.011\n$$\n\nWhat does that mean? It means that, for the average person, becoming one year older is associated with a 1% decrease in log earnings.\n\nNotice that this is the effect for the *average person*. Is the same true for young workers and older workers? To learn how to interpret this non-linearity in age, let's see how the predicted earnings correlate with age.\n\nWe can obtain the predicted earnings with the `predict` function and then use a scatterplot to eyeball its relationship with age. We covered how to create scatterplots in [Module 8](https://comet.arts.ubc.ca/docs/Research/econ490-r/08_ggplot_graphs.html)) and the `predict` function in [Module 10](https://comet.arts.ubc.ca/docs/Research/econ490-r/10_Linear_Reg.html).\n\nLet's see how to do this step by step.\n\nFirst, we store our regression in the object *fit*. Second, we use the function `model.frame` to keep only the observations and variables used in our regression. Then, we use `predict` to store in data frame *yhat* the predicted earnings obtained from our regression. Notice that `predict` creates a list, therefore we transform it into a data frame using the function `as.data.frame`. Finally, we merge the two data frames together using the function `cbind`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Run the regression with the quadratic term\nfit = lm(log_earnings_trimmed ~ age + age2, fake_data)\n\n# Predict earnigns and save them as yhat in the same data frame\ndatareg <- model.frame(fit)          # keep observations used in regression\nyhat <- as.data.frame(predict(fit))  # save predicted earnings as data frame\ndatareg = cbind(datareg, yhat)       # merge the two dataframes\ndatareg <- datareg %>% rename(yhat = \"predict(fit)\") # rename\n```\n:::\n\n\n\nOnce we have all the information in one unique data frame called *datareg*, we can display a scatterplot with age on the x-axis and predicted log-earnings on the y-axis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create scatterplot\nggplot(data = datareg, aes(x=age, y=yhat)) + geom_point()\n```\n\n::: {.cell-output-display}\n![](13_PostReg_files/figure-ipynb/unnamed-chunk-21-1.png)\n:::\n:::\n\n\n\nThe scatterplot shows an inverted-U relationship between age and the predicted log-earnings. This relationship implies that, when a worker is very young, aging is positively correlated with earnings. However, after a certain age, this correlation becomes negative and the worker gets lower earnings for each additional year of age. In fact, based on this graph, workers earnings start to decline just after the age of 50. Had we modelled this as a linear model, we would have missed this important piece of information! \n\n<div class=\"alert alert-info\">\n\n**Note:** If there is a theoretical reason for believing that non-linearity exists, R provides some tests for non-linearity. We can also create a scatter-plot to see if we observe a non-linear relationship in the data. We covered that approach in [Module 8](https://comet.arts.ubc.ca/docs/Research/econ490-r/8_ggplot_graphs.html).</div>\n\n## 13.5 Wrap Up \n\nIt is important to always follow best practices for regression analysis. Nonetheless, checking and correcting for outliers, as well as addressing heteroskedasticity, multicollinearity and non-linearity can be more of an art than a science. If you need any guidance on whether or not you need to address these issues, please be certain to speak with your instructor, TA, or supervisor.\n\n## 13.6 Wrap-up Table\n\n|Command|Function|\n|-------|--------|\n|`quantile(data$varname, probs = c(0.01, 0.99))`| It calculates the sample quantiles for the specified probabilities.|\n|`min(data$varname)`| It calculates the minimum value of a variable.|\n|`max(data$varname)`| It calculates the maximum value of a variable.|\n|`feols(depvar ~ indepvar, data)`| It performs a regression using robust standard errors.|\n|`model.frame(object)`| It saves the variables and observations specified by `object`.|\n\n## References\n[Syntax of quantile() function](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/quantile)\n[Syntax of model.frame() function](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/model.frame)",
    "supporting": [
      "13_PostReg_files\\figure-ipynb"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}