{
  "hash": "79ee2059e9fc7b0705b992fe931b4d4c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Projects - Example Project for ECON 325\"\nauthor: COMET Team <br> _Shiming Wu, Rathin Dharani, Jonathan Graves_\ndate: 12 January 2023\ndescription: Let's put it all together!  This notebook is an example of what a \"final project\" might look like in ECON 325.  It summarizes and uses all of the empirical skills and R commands present in the other notebooks.  \ncategories: [econ 325, regression, hypothesis testing, projects, t-test, visualization, summary statistics, R]\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html: default\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: R\n        language: r\n        name: ir\nimage: /media/comet_placeholder.png\n---\n\n# Outline\n\nIf you are reviewing the materials from ECON 325, or self-studying it, this is a good self-test to see if you understand all of the material. After completing this course, you should be able to:\n\n-   Read this notebook, and understand what the difference analyses are, and how they are being used\n-   Critique the choices made, understanding their pros and cons\n-   Understand what the R code is doing, and how it implements the analyses\n-   Be able to describe how to adjust or change this to do other analysis or change the focus or assumptions made in the analysis so far\n\nIf you're interested in getting started with econometric analysis, you may also use this as a model to guide your own project.\n\n# Education, Career and Inequality\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the packages\n\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   4.0.3     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.4     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(haven)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'haven' was built under R version 4.4.2\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(stargazer)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nPlease cite as: \n\n Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.\n R package version 5.2.3. https://CRAN.R-project.org/package=stargazer \n```\n\n\n:::\n\n```{.r .cell-code}\n#install.packages(\"vtable\") #run this line if you do not have \"vtable\" installed already. \nlibrary(vtable)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: kableExtra\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'kableExtra' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'kableExtra'\n\nThe following object is masked from 'package:dplyr':\n\n    group_rows\n```\n\n\n:::\n:::\n\n\n## Notes\n\n[[<sup>1</sup>](#fn2s)Stargazer package is due to: Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables. R package version 5.2.3. https://CRAN.R-project.org/package=stargazer ]{#fn2}\n\n# Introduction\n\nGetting a university degree can be tough. We may wonder whether higher education level can help us to achieve a more successful career. Besides, is education the only factor that impacts our career? In this project, we are going to answer these questions. Since one of the important proxies for a successful career is income, we are going to study the relationship between education, income, and wealth.\n\nNow, let's first import our data and clean our dataset. For this project, we will be using data from the 2019 Survey of Financial Security (SFS), provided by Statistics Canada (see the license notes). The survey was conducted by household unit, so income and wealth variables represent total income and wealth from a family, and household characteristics are usually the characteristics of main earners in the household. The main earner is the person who has highest income in a family. In order to study career outcomes, we restrict our samples to be households whose major sources of incomes are wages, salaries and self-employment incomes.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# READING IN DATA\nSFS_data <- read_dta(\"../datasets_projects/SFS_2019_Eng.dta\")\n\n# FILTERING OUT NA VALUES FOR TARGET VARIABLES\nSFS_data <- filter(SFS_data, !is.na(SFS_data$pefmtinc))\nSFS_data <- filter(SFS_data, !is.na(SFS_data$pefatinc))\nSFS_data <- filter(SFS_data, !is.na(SFS_data$pwnetwpg))\nSFS_data <- filter(SFS_data, !is.na(SFS_data$pagemieg))\n\n# SUBSETTING DATA \nSFS_data <- subset(SFS_data, pefmjsif == \"02\" | pefmjsif == \"03\") \n# restrict samples to be households whose major sources of incomes are wages, salaries and self-employment incomes.\n\n# RENAMING VARIABLES TO READABLE NAMES\nSFS_data <- rename(SFS_data, income_before_tax = pefmtinc)\nSFS_data <- rename(SFS_data, income_after_tax = pefatinc)\nSFS_data <- rename(SFS_data, wealth = pwnetwpg)\nSFS_data <- rename(SFS_data, gender = pgdrmie)\nSFS_data <- rename(SFS_data, education = peducmie)\nSFS_data <- rename(SFS_data, business = pbusind)\nSFS_data <- rename(SFS_data, province = ppvres)\nSFS_data <- rename(SFS_data, credit_limit = pattlmlc)\nSFS_data <- rename(SFS_data, age = pagemieg)\nSFS_data <- rename(SFS_data, employment = plffptme)\n\n# REFACTORING SOME VARIABLES\nSFS_data<-SFS_data[!(SFS_data$education==\"9\"),] # remove observations that education is \"not stated\"\nSFS_data$education <- as.numeric(SFS_data$education)\nSFS_data <- SFS_data[order(SFS_data$education),] # sort dataset by variable `education`\nSFS_data$education <- as.character(SFS_data$education)\nSFS_data$education[SFS_data$education == \"1\"] <- \"Less than high school\" \n# replace content to be 'less than high school' if orginal content is '1' for variable education\nSFS_data$education[SFS_data$education == \"2\"] <- \"High school\"\nSFS_data$education[SFS_data$education == \"3\"] <- \"Non-university post-secondary\"\nSFS_data$education[SFS_data$education == \"4\"] <- \"University\"\n\n# CHANGING ALL CATEGORICAL VARIABLES TO FACTOR VARIABLES (originally they were string variables)\nSFS_data$gender <- as_factor(SFS_data$gender)\nSFS_data$education <- as_factor(SFS_data$education)\nSFS_data$business <- as_factor(SFS_data$business)\nSFS_data$province <- as_factor(SFS_data$province)\nSFS_data$age <- as_factor(SFS_data$age)\nSFS_data$employment <- as_factor(SFS_data$employment)\n```\n:::\n\n\nSince we want to study income, let's restrict the sample to main working groups, mostly are people with age 25 to 65. The age variable we use is the age of main earner in a household.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSFS_data <- \n        SFS_data %>%\n        mutate(agegr = case_when(\n              age == \"01\" ~ \"Under 30\", #under 20\n              age == \"02\" ~ \"Under 30\", #20-24\n              age == \"03\" ~ \"20s\", #25-29\n              age == \"04\" ~ \"30s\",\n            age == \"05\" ~ \"30s\",\n              age == \"06\" ~ \"40s\",\n              age == \"07\" ~ \"40s\",\n              age == \"08\" ~ \"50s\",\n              age == \"09\" ~ \"50s\",\n              age == \"10\" ~ \"60s\", #60-64\n              age == \"11\" ~ \"Above 65\", #65-69\n              age == \"12\" ~ \"Above 65\", #70-74\n              age == \"13\" ~ \"Above 75\", #75-79\n              age == \"14\" ~ \"Above 75\", #80 and above\n              )) %>%\n        mutate(agegr = as_factor(agegr))\n\nSFS_data <- subset(SFS_data, agegr == \"20s\" | agegr == \"30s\" | agegr == \"40s\" | agegr == \"50s\" | agegr == \"60s\" )\nSFS_data$agegr <- factor(SFS_data$agegr,levels = c(\"20s\", \"30s\", \"40s\", \"50s\", \"60s\"))\n```\n:::\n\n\n# Summary Statistics\n\nBefore we begin our exploration, let's first describe variables of interest.\n\n-   Variables incomes and wealth are of the family unit. The wealth variable represents net worth of the family unit.\n\n-   Mean of income before tax of a family in 2019 is about \\$124,804.5.\n\n-   The standard deviation of income after tax is smaller than income before tax, which suggests tax and government transfers reduce income inequality in Canada.\n\n-   Net wealth of a family unit is approximately 9.5 times of the income after tax of a family. Unlike income after tax, standard deviation of wealth is large, thus dispersion of wealth is larger than income, which conforms with economic literature.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsumtable(SFS_data, \n      vars = c(\"income_before_tax\", \"income_after_tax\", \"wealth\"),\n       summ = c('mean(x)','median(x)', 'sd(x)' ),\n       digits = 7,\n       out = 'return')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in sumtable(SFS_data, vars = c(\"income_before_tax\", \"income_after_tax\",\n: Some labelled variables have unlabeled values. Treating these as numeric\nvariables and ignoring labels.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in sumtable(SFS_data, vars = c(\"income_before_tax\", \"income_after_tax\", : Factor variables ignore custom summ options. Cols 1 and 2 are count and percentage.\nBeware combining factors with a custom summ unless factor.numeric = TRUE.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           Variable     Mean Median       Sd\n1 income_before_tax 124804.5 100000 130976.4\n2  income_after_tax 104293.8  91325 82879.99\n3            wealth 951819.9 502000  1449620\n```\n\n\n:::\n:::\n\n\nSince `age` and `education` are factor variables, we can visualize them with histograms. As we can see from the graph below, many main earners are in their 50s, and most main earners have a post-secondary degree.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nage_plot<-ggplot(SFS_data, aes(x=agegr)) + \n          geom_bar(fill=\"lightblue\") + \n          ggtitle(\"Wage earners by Age Category\") +\n          ylab(\"Number of Earners\")+\n          xlab(\"Age Groups\") \noptions(repr.plot.width=7,repr.plot.height=7) #set size of the plot\nedu_plot<-ggplot(SFS_data, aes(x=education)) +\n          geom_bar(fill=\"lightgreen\") + \n          ggtitle(\"Wage earners by Highest Level of Education Recieved\") +\n          ylab(\"Number of Earners\") +\n          xlab(\"Education\") \nage_plot\n```\n\n::: {.cell-output-display}\n![](Projects_Example_Project_ECON325_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\nedu_plot\n```\n\n::: {.cell-output-display}\n![](Projects_Example_Project_ECON325_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n:::\n\n\nIn order to preclude effects of extreme values, let's remove observations that lie in highest 2% and lowest 2% of incomes and wealth. We see that both incomes and wealth are right-skewed: they have long right tails.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# FINDS THE LOWER AND UPPER BOUND SPECIFIED \npct2_income_before <- quantile(SFS_data$income_before_tax,c(0.02,0.98),type=1)\n\n# FILTERS OUT THE VALUES OUTSIDE OF THE BOUNDS SPECIFIED\nSFS_data <- filter(SFS_data, SFS_data$income_before_tax > pct2_income_before[1] & SFS_data$income_before_tax < pct2_income_before[2])\n\npct2_income_after <- quantile(SFS_data$income_after_tax,c(0.02,0.98),type=1)\nSFS_data <- filter(SFS_data, SFS_data$income_after_tax > pct2_income_after[1] & SFS_data$income_after_tax < pct2_income_after[2])\n\npct2_wealth <- quantile(SFS_data$wealth,c(0.02,0.98),type=1)\nSFS_data <- filter(SFS_data, SFS_data$wealth > pct2_wealth[1] & SFS_data$wealth < pct2_wealth[2])\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(repr.plot.width=7,repr.plot.height=7)\n\nincome_before_tax_plot<-ggplot(SFS_data, aes(x=income_before_tax)) + geom_histogram(colour = 4, fill = \"lightblue\", \n                 bins = 30)  + xlab(\"Income before Tax\") + ylab(\"Number of Observations\") + scale_x_continuous()\nincome_after_tax_plot<-ggplot(SFS_data, aes(x=income_after_tax)) + geom_histogram(colour = 4, fill = \"lightblue\", \n                 bins = 30)  + xlab(\"Income after Tax\") + ylab(\"Number of Observations\") + scale_x_continuous()\n\nincome_before_tax_plot\n```\n\n::: {.cell-output-display}\n![](Projects_Example_Project_ECON325_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\nincome_after_tax_plot\n```\n\n::: {.cell-output-display}\n![](Projects_Example_Project_ECON325_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n\n```{.r .cell-code}\nwealth_plot<-ggplot(SFS_data, aes(x=wealth)) + geom_histogram(colour = 4, fill = \"lightblue\", \n                 bins = 30)  + xlab(\"Wealth\") + ylab(\"Number of Observations\") + scale_x_continuous()\nwealth_plot\n```\n\n::: {.cell-output-display}\n![](Projects_Example_Project_ECON325_files/figure-html/unnamed-chunk-7-3.png){width=672}\n:::\n:::\n\n\n# Education and Career\n\nNow let's study the relationship between education, income and wealth.\n\n1.  Create a function `CI` to calculate confidence interval.\n2.  Store the mean of income and wealth by groups of education in table `results`.\n3.  Use the `CI` function to calculate confidence intervals and combine results in table `df_gr`. We also display results in graphs.\n\nFrom table `df_gr`, we notice that incomes and wealth increase as education increases. Thus education does help us to achieve a more successful career.\n\nMeanwhile, standard deviations also increase as education increases. This implies income and wealth inequality increase as education increases.\n\nFrom a personal point of view, in order to have a successful career, obtaining a degree is just a starting point as career development is also crucial for a successful career. From a policy perspective, policies that only target pre-labor market skill accumulation will be less effective than policies that foster career progression in reducing inequality.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCI <- function(data) {\n    x <- mean(data) # calculate mean of input\n    n <- length(data) # calculate number of observations\n    df <- n - 1 # degree of freedom is n-1\n    t <- qt(p = 0.05, df = df) # finding the t value for a confidence level of 95% \n    s <- sd(data) # finding the sample standard deviation of input\n    \n    # calculating the lower and upper bounds of the desired confidence interval\n    lower_bound <- x - (t*s/sqrt(n))\n    upper_bound <- x + (t*s/sqrt(n))\n    \n    bound<-c(lower_bound,upper_bound) # store lower bound and upper bound to a vector named `bound`\n    return(bound)\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n'Generate a Dataframe to Display Summary Statistics by Education Groups'\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Generate a Dataframe to Display Summary Statistics by Education Groups\"\n```\n\n\n:::\n\n```{.r .cell-code}\n#We can start by creating a new data frame named `results` to store mean and standard deviations of incomes and wealth by education groups. We can include our calculated confidence interval by running function `CI` with each of our variables of interest (`income_before_tax` and `wealth`).\n\nresults <- data.frame(SFS_data %>%\n  group_by(education) %>%\n  summarize(m_income = mean(income_before_tax),\n            sd_income = sd(income_before_tax),\n            CI_L_income = c(CI(income_before_tax)[2]),\n            CI_U_income = c(CI(income_before_tax)[1]), #Calculate confidence interval for `income_before_tax` using the `CI` function \n            m_wealth = mean(wealth),\n            sd_wealth = sd(wealth),\n            CI_L_wealth = c(CI(wealth)[2]), #Calculate confidence interval for `wealth` using the `CI` function \n            CI_U_wealth = c(CI(wealth)[1])))\n\nresults   \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                      education  m_income sd_income CI_L_income CI_U_income\n1         Less than high school  81239.44  49818.33    76360.99    86117.88\n2                   High school  94789.79  54371.99    92050.78    97528.81\n3 Non-university post-secondary 105596.85  57741.74   103280.45   107913.26\n4                    University 132165.26  67358.58   129765.25   134565.27\n  m_wealth sd_wealth CI_L_wealth CI_U_wealth\n1 420790.0  491730.0    372637.5    468942.5\n2 624052.8  709126.7    588330.2    659775.4\n3 666605.4  729836.6    637326.8    695883.9\n4 976124.9  910465.0    943684.7   1008565.1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(repr.plot.width=8,repr.plot.height=3)\ng <- ggplot(data = SFS_data, aes(x = education, y = income_before_tax)) + xlab(\"Education of Main Earner\") + ylab(\"Income before Tax\") + scale_y_continuous() \ng1 <- g + geom_bar(stat = \"summary\", fun = \"mean\", fill = \"lightblue\") #produce a summary statistic, the mean\ng1 <- g1 + coord_flip() #make a horizontal bar graph!\n\nf <- ggplot(data = SFS_data, aes(x = education, y = wealth)) + xlab(\"Education of Main Earner\") + ylab(\"Wealth\") + scale_y_continuous() \nf1 <- f + geom_bar(stat = \"summary\", fun = \"mean\", fill = \"lightblue\") #produce a summary statistic, the mean\nf1 <- f1 + coord_flip() #make a horizontal bar graph!\n\ng1\n```\n\n::: {.cell-output-display}\n![](Projects_Example_Project_ECON325_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\nf1\n```\n\n::: {.cell-output-display}\n![](Projects_Example_Project_ECON325_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n:::\n\n\nFrom table and graphs above, we know incomes and wealth of different education groups are different. But is the difference statistically significant? We use two sample t-test to verify the results.\n\nThe t-tests for income and wealth are significant. The results suggest people who obtain university degrees will have higher wages and wealth than people who own non-university post-secondary degrees.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt1 = t.test(\n       x = filter(SFS_data, education == \"Non-university post-secondary\")$income_before_tax,\n       y = filter(SFS_data, education == \"University\")$income_before_tax,\n       alternative = \"two.sided\",\n       mu = 0,\n       conf.level = 0.95)\n\nt1 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  filter(SFS_data, education == \"Non-university post-secondary\")$income_before_tax and filter(SFS_data, education == \"University\")$income_before_tax\nt = -13.108, df = 3787.9, p-value < 2.2e-16\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -30542.26 -22594.56\nsample estimates:\nmean of x mean of y \n 105596.9  132165.3 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(t1$estimate[1] - t1$estimate[2],2) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean of x \n-26568.41 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nt2 = t.test(\n       x = filter(SFS_data, education == \"Non-university post-secondary\")$wealth,\n       y = filter(SFS_data, education == \"University\")$wealth,\n       alternative = \"two.sided\",\n       mu = 0,\n       conf.level = 0.95)\n\nt2 \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  filter(SFS_data, education == \"Non-university post-secondary\")$wealth and filter(SFS_data, education == \"University\")$wealth\nt = -11.656, df = 3813, p-value < 2.2e-16\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -361581.3 -257457.8\nsample estimates:\nmean of x mean of y \n 666605.4  976124.9 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(t2$estimate[1] - t2$estimate[2],2) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean of x \n-309519.5 \n```\n\n\n:::\n:::\n\n\nNext, we study correlations between education, incomes and wealth.\n\nWe first draw graphs to depict correlations between education, incomes, and wealth. From graphs below, we find that they have positive correlations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\noptions(repr.plot.width=7,repr.plot.height=7)\nbefore_after_tax<-ggplot(SFS_data, aes(x = income_before_tax, y = income_after_tax)) + \n    xlab(\"Incomes before tax\") + ylab(\"Incomes after tax\") +\n    geom_point(shape = 1) + geom_smooth(method = lm, formula=y ~ x) + \n    scale_x_continuous() + scale_y_continuous() \nafter_tax_wealth<-ggplot(SFS_data, aes(x = income_after_tax, y = wealth)) + \n    xlab(\"Incomes after tax\") + ylab(\"Wealth\") +\n    geom_point(shape = 1) + geom_smooth(method = lm, formula=y ~ x) + \n    scale_x_continuous() + scale_y_continuous()\nedu_before_tax <- ggplot(SFS_data, aes(x = education, y = income_before_tax)) + \n    xlab(\"Education\") + ylab(\"Incomes\") + geom_boxplot(fill = \"lightyellow\") + scale_y_continuous()\nedu_wealth <- ggplot(SFS_data, aes(x = education, y = wealth)) + \n    xlab(\"Education\") + ylab(\"Wealth\") + geom_boxplot(fill = \"lightyellow\") + scale_y_continuous()\n\nbefore_after_tax\n```\n\n::: {.cell-output-display}\n![](Projects_Example_Project_ECON325_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n\n```{.r .cell-code}\nafter_tax_wealth\n```\n\n::: {.cell-output-display}\n![](Projects_Example_Project_ECON325_files/figure-html/unnamed-chunk-13-2.png){width=672}\n:::\n\n```{.r .cell-code}\nedu_before_tax\n```\n\n::: {.cell-output-display}\n![](Projects_Example_Project_ECON325_files/figure-html/unnamed-chunk-13-3.png){width=672}\n:::\n\n```{.r .cell-code}\nedu_wealth\n```\n\n::: {.cell-output-display}\n![](Projects_Example_Project_ECON325_files/figure-html/unnamed-chunk-13-4.png){width=672}\n:::\n:::\n\n\nLet's find out how large the correlations are between variables. We first transform `education` to be a numeric variable which increases as education increases.\n\nFrom table below, we know the correlations of education and incomes, and education and wealth are 0.26 and 0.21 respectively. This conforms with our previous results that incomes and wealth increase as education increases. But since correlations are not very close to 1, that means education is not the only factor to a successful career.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSFS_data$education<-as.numeric(SFS_data$education)\ncor_data<-select(SFS_data, c('education','income_before_tax','income_after_tax','wealth'))\nmydata.cor = cor(cor_data)\nmydata.cor\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  education income_before_tax income_after_tax    wealth\neducation         1.0000000         0.2633120        0.2405818 0.2065850\nincome_before_tax 0.2633120         1.0000000        0.9673971 0.5232641\nincome_after_tax  0.2405818         0.9673971        1.0000000 0.5159091\nwealth            0.2065850         0.5232641        0.5159091 1.0000000\n```\n\n\n:::\n:::\n\n\nFrom the table and graphs above, we know there is positive correlations between education and incomes, as well as wealth. Are the correlations significantly different from 0? To test our hypothesis we can perform Pearson correlation tests. The results suggest that correlations are significantly different from 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pearson correlation test\ncor.test(SFS_data$education, SFS_data$income_before_tax, use=\"complete.obs\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  SFS_data$education and SFS_data$income_before_tax\nt = 19.618, df = 5166, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.2377539 0.2885057\nsample estimates:\n     cor \n0.263312 \n```\n\n\n:::\n\n```{.r .cell-code}\ncor.test(SFS_data$education, SFS_data$wealth, use=\"complete.obs\") \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  SFS_data$education and SFS_data$wealth\nt = 15.176, df = 5166, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.1803358 0.2325402\nsample estimates:\n     cor \n0.206585 \n```\n\n\n:::\n:::\n\n\nSo far, we know that incomes and wealth increase as education increases. But there is one question which is not clear yet: is there another factor A that affects education and income at the same time, so that the real \"force\" that drives up income is factor A, rather than education? In order to answer this question, we can run regressions. Let's first change `education` back to a factor variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSFS_data$education <- as.character(SFS_data$education)\nSFS_data$education[SFS_data$education == \"1\"] <- \"Less than high school\"\nSFS_data$education[SFS_data$education == \"2\"] <- \"High school\"\nSFS_data$education[SFS_data$education == \"3\"] <- \"Non-university post-secondary\"\nSFS_data$education[SFS_data$education == \"4\"] <- \"University\"\nSFS_data$education <- as_factor(SFS_data$education)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nregression1 <- lm(income_before_tax ~ education, data = SFS_data)\nregression2 <- lm(income_before_tax ~ education + gender, data = SFS_data)\nregression3 <- lm(income_before_tax ~ education + gender + agegr, data = SFS_data)\n\nstargazer(regression1, regression2, regression3, title=\"Comparison of Controls\",\n          align = TRUE, type=\"text\", keep.stat = c(\"n\",\"rsq\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nComparison of Controls\n==================================================================================\n                                                   Dependent variable:            \n                                       -------------------------------------------\n                                                    income_before_tax             \n                                            (1)           (2)            (3)      \n----------------------------------------------------------------------------------\neducationHigh school                   13,550.360*** 15,455.860***  17,298.760*** \n                                        (4,064.420)   (3,982.514)    (3,872.655)  \n                                                                                  \neducationNon-university post-secondary 24,357.410*** 27,703.390***  30,476.770*** \n                                        (3,905.314)   (3,831.245)    (3,738.480)  \n                                                                                  \neducationUniversity                    50,925.820*** 56,798.720***  60,512.440*** \n                                        (3,845.376)   (3,786.581)    (3,701.046)  \n                                                                                  \ngenderFemale                                         -25,889.700*** -26,433.080***\n                                                      (1,740.864)    (1,691.062)  \n                                                                                  \nagegr30s                                                            21,658.990*** \n                                                                     (3,212.499)  \n                                                                                  \nagegr40s                                                            41,430.020*** \n                                                                     (3,205.554)  \n                                                                                  \nagegr50s                                                            47,544.640*** \n                                                                     (3,137.231)  \n                                                                                  \nagegr60s                                                            38,238.020*** \n                                                                     (3,635.176)  \n                                                                                  \nConstant                               81,239.440*** 86,800.250***  49,656.070*** \n                                        (3,612.400)   (3,557.476)    (4,401.249)  \n                                                                                  \n----------------------------------------------------------------------------------\nObservations                               5,168         5,168          5,168     \nR2                                         0.073         0.111          0.163     \n==================================================================================\nNote:                                                  *p<0.1; **p<0.05; ***p<0.01\n```\n\n\n:::\n:::\n\n\nThe table above displays results of 3 regressions.\n\nColumn (1) shows the regression with education and incomes.\n\n-   The average income of households whose education is less than high school is CAD 81239.44. Average income of family with high school degree is CAD 81239.44 + CAD 13550.36 = CAD 94789.8.\n-   Similarly, we can calculate the average incomes of households with non-university post-secondary degree and university degree (as seen in the two sample t-tests).\n-   So the first column suggests incomes increase as education increases.\n\nColumn (2) includes education and gender in the regression.\n\n-   Compared with male-lead family, a family with a female primary earner has a lower income.\n-   However, the coefficient of `education` is still positive, significant and monotonically increasing, which means after controlling effects of gender, income still increases as education increases.\n\nColumn (3) shows regression with gender and age group.\n\n-   We can see that people tend to earn more as they move on to later stages of their career.\n-   Once again, the positive and monotonically increasing coefficients of education show the positive correlation between education and incomes. Since after we include other factors that may affect incomes, the coefficients of education are still positive and stable, we have stronger evidence that income increase as education increases.\n\n# Going Further: Long-term Effect of Education\n\nFrom previous results, we find that incomes and wealth increase as education increases. The next interesting question is whether there is long-term effects of education on career outcomes. In order to study this question, we explore returns to education for different age groups. It will be great that if we can study this question via panel data, but since we do not observe the same person across time periods, we study returns to education from different age groups.\n\nWe perform Welch two sample t-test for each age group. We study the difference between university degree holders and non-university post-secondary degree holders. We compare outcomes of age group 30s and 50s, which represents early stage and mature stage of career respectively.\n\nWe first study education impacts on incomes. For both groups, differences of incomes between university and non-university are significantly different from 0. Surprisingly, the income gap of 50s is about 3 times as the gap when they are in 30s.\n\nAs for wealth, wealth gaps between the two education groups increase even more when people enter a mature stage of their career. The wealth gap of 50s is more than 4 times as the gap when they are in 30s.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Returns to education: University\n\n#30s\n\nretU = t.test(\n       x = filter(SFS_data, (agegr == \"30s\" & education=='Non-university post-secondary'))$income_before_tax,\n       y = filter(SFS_data, (agegr == \"30s\" & education=='University'))$income_before_tax,\n       alternative = \"two.sided\",\n       mu = 0,\n       conf.level = 0.95)\n\nretU\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  filter(SFS_data, (agegr == \"30s\" & education == \"Non-university post-secondary\"))$income_before_tax and filter(SFS_data, (agegr == \"30s\" & education == \"University\"))$income_before_tax\nt = -4.1221, df = 973.76, p-value = 4.074e-05\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -21275.679  -7551.823\nsample estimates:\nmean of x mean of y \n 98545.66 112959.41 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(retU$estimate[2] - retU$estimate[1],2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean of y \n 14413.75 \n```\n\n\n:::\n\n```{.r .cell-code}\n#50s\n\nretUF = t.test(\n       x = filter(SFS_data, (agegr == \"50s\" & education=='Non-university post-secondary'))$income_before_tax,\n       y = filter(SFS_data, (agegr == \"50s\" & education=='University'))$income_before_tax,\n       alternative = \"two.sided\",\n       mu = 0,\n       conf.level = 0.95)\n\nretUF\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  filter(SFS_data, (agegr == \"50s\" & education == \"Non-university post-secondary\"))$income_before_tax and filter(SFS_data, (agegr == \"50s\" & education == \"University\"))$income_before_tax\nt = -9.649, df = 1089.9, p-value < 2.2e-16\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -44858.35 -29697.33\nsample estimates:\nmean of x mean of y \n 116223.0  153500.8 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(retUF$estimate[2] - retUF$estimate[1],2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean of y \n 37277.84 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Returns to education: University\n\n#30s\n\nretU = t.test(\n       x = filter(SFS_data, (agegr == \"30s\" & education=='Non-university post-secondary'))$wealth,\n       y = filter(SFS_data, (agegr == \"30s\" & education=='University'))$wealth,\n       alternative = \"two.sided\",\n       mu = 0,\n       conf.level = 0.95)\n\nretU\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  filter(SFS_data, (agegr == \"30s\" & education == \"Non-university post-secondary\"))$wealth and filter(SFS_data, (agegr == \"30s\" & education == \"University\"))$wealth\nt = -3.7839, df = 961.73, p-value = 0.0001639\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -183272.41  -58093.02\nsample estimates:\nmean of x mean of y \n 366716.2  487399.0 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(retU$estimate[2] - retU$estimate[1],2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean of y \n 120682.7 \n```\n\n\n:::\n\n```{.r .cell-code}\n#50s\n\nretUF = t.test(\n       x = filter(SFS_data, (agegr == \"50s\" & education=='Non-university post-secondary'))$wealth,\n       y = filter(SFS_data, (agegr == \"50s\" & education=='University'))$wealth,\n       alternative = \"two.sided\",\n       mu = 0,\n       conf.level = 0.95)\n\nretUF\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  filter(SFS_data, (agegr == \"50s\" & education == \"Non-university post-secondary\"))$wealth and filter(SFS_data, (agegr == \"50s\" & education == \"University\"))$wealth\nt = -9.0266, df = 1089.8, p-value < 2.2e-16\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -602866.7 -387570.9\nsample estimates:\nmean of x mean of y \n 971711.5 1466930.3 \n```\n\n\n:::\n\n```{.r .cell-code}\nround(retUF$estimate[2] - retUF$estimate[1],2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nmean of y \n 495218.8 \n```\n\n\n:::\n:::\n\n\n# Summary\n\nIn this project, we study relationship between education and career. We use incomes and wealth as proxies for labor market outcomes.\n\nWe first describe income and wealth distribution in Canadian households, and we find that there are income inequality and wealth inequality in Canada.\n\nNext, we study relationship between education and career outcomes via exploration of correlations, two sample t-test and regressions. Our results suggest that there are significant and positive correlation of education, incomes and wealth. We find that incomes and wealth increase as education increases. Thus education does help us to achieve a more successful career. Meanwhile, standard deviations of incomes and wealth also increase as education increases. This implies income and wealth inequality increase as education increases.\n\nFinally, we explore the long-term effects of education via studying return to education of different age groups. We find that income and wealth gaps increase dramatically for university degree holders and non-university degree counterparts when they enter later stage of career. This result implies that there is long-term effect of education on incomes and wealth.\n\nTo sum up, from a personal point of view, not only is obtaining a degree important in order to have a successful career, but career development is also crucial. From a policy perspective, we need policies that target pre-labor market skill accumulation, as well as policies that foster career progression to effectively reduce inequality.\n\n## List of R Commands\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 'Commands about Dataframe'\n# \n# read_dta(file) #read dta files\n# \n# !is.na(data) #return not NA data\n# \n# filter(dataframe, conditions) #return dataframe that satisfies conditions, e.g.\n# SFS_data <- filter(SFS_data, !is.na(SFS_data$pefmtinc)) #return dataframe that variable pefmtinc is not NA\n# \n# subset(dataframe, conditions) #select subset of dataframe that satisfies conditions, e.g.\n# SFS_data <- subset(SFS_data, pefmjsif == \"02\" | pefmjsif == \"03\") #select subset of dataframe that major income sources are salary or self-employment incomes\n# \n# rename(dataframe, new name = old name) #rename variables in dataframe, e.g.\n# SFS_data <- rename(SFS_data, income_after_tax = pefatinc)\n# \n# dataframe[order(data),] #sort dataframe according to a variable, e.g.\n# SFS_data <- SFS_data[order(SFS_data$education),]\n# \n# mutate(new variable = [operation] existing variables) #adds new variables and preserves existing ones\n# \n# case_when(conditions) #vectorise multiple if_else() statements\n# \n# #e.g.\n# SFS_data <- \n#         SFS_data %>%\n#         mutate(agegr = case_when(\n#               age == \"01\" ~ \"Under 30\", #under 20\n#               age == \"02\" ~ \"Under 30\", #20-24\n#               age == \"03\" ~ \"20s\", #25-29\n#               age == \"04\" ~ \"30s\",\n#             age == \"05\" ~ \"30s\",\n#               age == \"06\" ~ \"40s\",\n#               age == \"07\" ~ \"40s\",\n#               age == \"08\" ~ \"50s\",\n#               age == \"09\" ~ \"50s\",\n#               age == \"10\" ~ \"60s\", #60-64\n#               age == \"11\" ~ \"Above 65\", #65-69\n#               age == \"12\" ~ \"Above 65\", #70-74\n#               age == \"13\" ~ \"Above 75\", #75-79\n#               age == \"14\" ~ \"Above 75\", #80 and above\n#               )) %>% \n# #create a new variable named `agegr` based on variable `age`. If age==\"01\", agegr will be \"Under 30\".\n# \n# data.frame(variable=c(...),...) #create dataframe which contains variable, and we can define what's in the column with c()\n# #e.g.\n# df <- data.frame(variables=c('income before tax','income after tax','wealth'),\n#                  mean=round(c(mean(SFS_data$income_before_tax),mean(SFS_data$income_after_tax),mean(SFS_data$wealth)),2),\n#                  median=round(c(median(SFS_data$income_before_tax),median(SFS_data$income_after_tax),median(SFS_data$wealth)),2),\n#                 sd=round(c(sd(SFS_data$income_before_tax),sd(SFS_data$income_after_tax),sd(SFS_data$wealth)),2))\n# #create a dataframe to contain variable names, means, medians and standard deviations.\n# \n# select(dataframe, variables) #select columns from a dataframe, e.g.\n# cor_data<-select(SFS_data, c('education','income_before_tax','income_after_tax','wealth'))\n# \n# length(data) #length of the vector\n# \n# group_by(variable) #takes an existing tbl and converts it into a grouped tbl where operations are performed \"by group\"\n# \n# summarize(variables) #creates a new data frame\n# \n# #e.g.\n# results <- \n#     SFS_data %>% \n#     group_by(education) %>%\n#     summarize(m_income = mean(income_before_tax), sd_income = sd(income_before_tax),\n#               m_wealth = mean(wealth), sd_wealth = sd(wealth))\n#convert SFS_data to a grouped table, grouped by `education`. make a new table with means, standard deviations of each group\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n'Commands about Types'\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Commands about Types\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# as.numeric(data) #transform strings to numbers, e.g.\n# SFS_data$education <- as.numeric(SFS_data$education)\n# \n# as.character(data) #transform numbers to strings, e.g.\n# SFS_data$education <- as.character(SFS_data$education)\n# \n# as_factor(data) #transform strings to factor variables, e.g.\n# SFS_data$gender <- as_factor(SFS_data$gender)\n# \n# factor(factor variable,levels = c(\"A\", \"B\", \"C\", \"D\", \"E\")) #order factor variable, e.g.\n# SFS_data$agegr <- factor(SFS_data$agegr,levels = c(\"20s\", \"30s\", \"40s\", \"50s\", \"60s\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n'Commands about Calculation'\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Commands about Calculation\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# round(data, number of digits) #round numbers to have certain number of digits\n# \n# sqrt(n) #square root of n\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n'Commands about Summary Statistics'\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Commands about Summary Statistics\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# mean(data) #mean of data\n# \n# median(data) #median of data\n# \n# sd(data) #standard deviation of data \n# \n# quantile(data, vector of probabilities) #produces sample quantiles corresponding to the given probabilities, e.g.\n# pct2_income_before <- quantile(SFS_data$income_before_tax,c(0.02,0.98),type=1)\n# #sample quantiles of 0.02 and 0.98 of income_before_tax\n# \n# cor(data) #correlations of variables\n# \n# qt(p = 0.05, df = df) #return t statistics with confidence level of 95% and degree of freedom of df\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#'Commands about Plots'\n\n# ggplot(data,options) #create plots, e.g.\n# \n# age_plot<-ggplot(SFS_data, aes(x=factor(agegr))) + geom_bar(fill=\"lightblue\") + xlab(\"Age Groups\") + theme(axis.text.x = element_text(angle = 90))\n# #create bar plot for factor varible `agegr`, with color lightblue, with texts display vertically\n# \n# income_before_tax_plot<-ggplot(SFS_data, aes(x=income_before_tax)) + geom_histogram()  + xlab(\"Income before Tax\") + ylab(\"Number of Observations\")\n# #create histogram for `income_before_tax`, with labels of x-axis and y-axis\n# \n# before_after_tax<-ggplot(SFS_data, aes(x = income_before_tax, y = income_after_tax)) + geom_point(shape = 1) + geom_smooth(method = lm)\n# #create scatter plot with a regression line\n# \n# ggarrange(plots, ncol=number of columns, nrow = number of rows) #arrange plots, e.g\n# ggarrange(income_before_tax_plot,income_after_tax_plot,  ncol = 2, nrow = 1) # arrange 2 plots in the same row\n# \n# corrplot(mydata.cor) #plot correlations\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#'define a function named `CI`, input `data`, output `bound`'\n\n# CI <- function(data) {\n#     ...\n#     return(bound)\n# }\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#'Commands about Tests'\n\n# t.test(x, y, alternative = c(\"two.sided\", \"less\", \"greater\"),\n#        mu = 0, paired = FALSE, var.equal = FALSE,\n#        conf.level = 0.95, …) #Performs one and two sample t-tests on vectors of data.\n# \n# cor.test(x, y, use=\"complete.obs\") #Test for association between paired samples, using one of Pearson's product moment correlation coefficient\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#'Commands about Regressions'\n\n# lm(dependent variable ~ independent variable, data) #run a regression\n# \n# stargazer(regression1, regression2, regression3, ...) #show several regression results in a table\n```\n:::\n\n\n## Quick Note on Commands\n\nIt's important to remember that you may need to use these commands in ways that aren't specified above. For example, you may want to use the `t_test` function with a different confidence level, so you may set `conf.level = 0.99`. You may also have to add new parameters depending on what you are trying to accomplish. For example, to run a linear regression with a subset of the data, you would need to add a `subset` parameter to the `lm` function. To discover what each of the functions can do, check out the R documentation for the functions to get a detailed list of the different parameters and default values you can use for function.\n\nhttps://www.rdocumentation.org/\n",
    "supporting": [
      "Projects_Example_Project_ECON325_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}