{
  "hash": "218ee6a3216a2dadce3674147cf90826",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Double Machine Learning\"\nauthor: Alex Ronczewski\ndate: 2026-06-21\ndescription: \"The seventh notebook in the Causal ML stream. We combine everything: the partially linear model, the residual-on-residual idea from Notebook 4, and any learner we like for the nuisance models. We add cross-fitting to stop the learners from contaminating the estimate, attach a standard error, and finally pin down the effect of 401(k) eligibility that Notebook 6 left as a wide interval.\"\ncategories:\n  - Python\n  - machine learning\n  - causal inference\n  - double machine learning\n  - cross-fitting\n  - treatment effects\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html:\n    embed-resources: true\n    self-contained-math: true\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: Python\n        language: python3\n        name: python3\n---\n\n\n\n\n\n\n## Outline\n\n### Prerequisites\n\n- Notebook 6 of this stream: estimating a treatment effect, and why a wide confidence interval leaves us stuck\n- Multiple regression and the idea of partialling out controls (COMET Intermediate)\n- Comfort with `pandas` and basic Python at the COMET-intermediate level\n\n### Learning Outcomes\n\nBy the end of this notebook you will be able to:\n\n1. Write down the **partially linear model** and identify the treatment effect in it.\n2. Estimate that effect by **residual-on-residual** regression with any learner.\n3. Explain why fitting the learners and the effect on the same data biases the estimate, and fix it with **cross-fitting**.\n4. Run a full **double machine learning** estimate with a standard error.\n5. Swap in any learner and see the estimate hold.\n\n::: {#e0d938dd .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\nfrom sklearn.linear_model import LassoCV, LogisticRegression\nfrom sklearn.ensemble import (RandomForestRegressor, RandomForestClassifier,\n                              GradientBoostingRegressor, GradientBoostingClassifier,\n                              ExtraTreesRegressor)\nfrom sklearn.model_selection import KFold\n\nRANDOM_STATE = 42\n```\n:::\n\n\n## 1. Where we Currently Stand After Notebook 6\n\nThe last three notebooks approached the same problem from different angles. Notebook 4 removed the controls from the outcome and the treatment separately, then regressed on the leftovers (orthogonalization). Notebook 5 did this for lasso, selecting controls twice. Notebook 6 modelled the treatment and combined the two routes into the doubly-robust estimator. Notebook 6 also left us stuck: its estimate of the 401(k) effect was 1.9 thousand dollars, but with a confidence interval running from negative five up to about positive nine, far too wide to tell whether eligibility helped at all. It was imprecise. \n\nThis notebook closes that gap. **Double machine learning (DML)** keeps the residual-on-residual concept from before and adds two things which greatly increase its power and usefulness:\n\n- **Any learner.** A **learner** is any prediction algorithm that fits a function to data, the kind of model we built in Notebooks 1 to 3. The two models we fit along the way, savings given the covariates and treatment given the covariates, are prediction problems, so we can use whichever learner predicts best: a lasso, a random forest, a boosted ensemble, a neural network or anything else that fits the data.\n- **Cross-fitting.** A method that stops our new flexible learners from biasing the effect, built from the train/test idea of Notebook 1.\n\nDML will lead to a sharp, significant estimate of the effect of 401(k) eligibility on savings.\n\n## 2. The partially linear model\n\nTo say what we are estimating, we write down a model. The **partially linear model** splits the outcome into the part we care about and the part we do not:\n\n$$\nY = \\theta D + g(X) + \\varepsilon .\n$$\n\nHere $Y$ is savings, $D$ is eligibility, and $X$ is the covariates. The number $\\theta$ is the effect of eligibility, the one thing we want. The function $g(X)$ is everything else that drives savings: income, age, and any other controls, and it can take any shape. The treatment depends on the covariates too:\n\n$$\nD = m(X) + v .\n$$\n\nThe function $m(X)$ is the propensity from Notebook 6, the part of eligibility explained by the covariates, and $v$ is what is left.\n\n::: {.callout-note}\n## Read these for the meaning\n\n$g$ and $m$ are called **nuisance** functions: we have to estimate them well, but we don't care what they are. We just want a clean value of $\\theta$ while the messy functions $g$ and $m$ are handled by a learner in the background. The word \"linear\" in the name refers only to how $D$ enters, through a single number $\\theta$. Everything else, $g(X)$, can be nonlinear.\n:::\n\n### 2.1 Orthogonalization: residual on residual\n\nThe trick for isolating $\\theta$ is the one we used in Notebook 4: remove the covariates' influence out of both sides, and then compare what is left. The covariates $X$ are the confounders, the common causes of eligibility and savings, so removing them from both the outcome and the treatment cleans the comparison.\n\nPredicting savings from the covariates and subtracting leaves $\\tilde{Y} = Y - g(X)$, the part of savings the covariates do not explain. Doing the same for eligibility leaves $\\tilde{D} = D - m(X)$, the part of eligibility the covariates do not explain. Subtracting $g(X)$ from the model leaves\n\n$$\n\\tilde{Y} = \\theta \\tilde{D} + \\varepsilon ,\n$$\n\nso the slope of $\\tilde{Y}$ on $\\tilde{D}$ is exactly $\\theta$. This is a famous result from Econometrics called the **Frisch-Waugh-Lovell theorem**. It states that multivariate regression coefficients can be calculated by \"partialling out\" (or residualizing) the influence of control variables from both the dependent variable and the primary independent variables. Residualizing first and controlling for everything at once are two roads to the same number. Notebook 4 demonstrated the first road with a lasso doing the predicting. The new freedom in DML is that any learner can play the role of $g$ and $m$, since we just need them to predict well.\n\nThere is one catch, the same one from Notebook 1: we can't use the same data twice.\n\n### 2.2 The issue with fitting and estimating on the same data\n\nSuppose we fit the two learners and compute the effect all on the same households. The danger is overfitting, a core theme of Notebooks 1, 2, and 3. A flexible learner can fit the training data too well, memorizing the noise and not being able to generalize to new data. If we feed these overfitting estimators into the residual-on-residual regression the effect comes out wrong.\n\nWe will make this happen on purpose to demonstrate it. We build a world where the true effect is 1, and we hand the residualizing to a learner that memorises its training data and dramatically overfits: an extremely-randomised forest grown until every household sits in its own leaf (check notebook 3). On the training data it predicts perfectly, so the leftovers collapse to nothing.\n\n::: {#9a0d6b9f .cell execution_count=2}\n``` {.python .cell-code}\ndef make_world(n, seed):\n    rng = np.random.default_rng(seed)\n    X = rng.normal(0, 1, (n, 8))\n    g = X[:, 0] + 0.7 * X[:, 1] + 0.5 * X[:, 2] + 0.4 * X[:, 0] * X[:, 1]\n    m = 0.6 * X[:, 0] + 0.4 * X[:, 2]\n    D = m + rng.normal(0, 1, n)\n    Y = 1.0 * D + g + rng.normal(0, 1, n)   # the true effect is 1\n    return X, D, Y\n\nX_sim, D_sim, Y_sim = make_world(1000, RANDOM_STATE)\n\ndef memoriser():\n    return ExtraTreesRegressor(n_estimators=100, min_samples_leaf=1,\n                               bootstrap=False, random_state=RANDOM_STATE, n_jobs=-1)\n\n# Same data for fitting and for the effect: no cross-fitting.\ny_leftover = Y_sim - memoriser().fit(X_sim, Y_sim).predict(X_sim)\nd_leftover = D_sim - memoriser().fit(X_sim, D_sim).predict(X_sim)\ntheta_same_data = np.sum(d_leftover * y_leftover) / np.sum(d_leftover * d_leftover)\n\nprint(f\"Leftover spread on the training data: Y {y_leftover.std():.3f}, D {d_leftover.std():.3f}\")\nprint(f\"Effect estimated on the same data: {theta_same_data:.2f}  (true effect is 1.0)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLeftover spread on the training data: Y 0.000, D 0.000\nEffect estimated on the same data: -0.10  (true effect is 1.0)\n```\n:::\n:::\n\n\nThe leftovers are approaching zero, because the learner reads the training outcomes back to us, memorizing the noise not true predictive signal. With nothing left to regress, the estimate collapses to -0.10, nowhere near the true 1.\n\nThe fix is **cross-fitting**, and it is the train/test split of Notebook 1 applied to the nuisance models. Split the data into folds. To get a household's leftover, use a learner that was fit on the *other* folds, never on that household. A learner can't memorise a household it was not shown, so the leftovers keep their real spread.\n\n::: {#90c4355c .cell execution_count=3}\n``` {.python .cell-code}\ndef crossfit_leftovers(X, target, make_model, n_splits=5):\n    leftover = np.zeros(len(target))\n    folds = KFold(n_splits, shuffle=True, random_state=RANDOM_STATE)\n    for train_idx, test_idx in folds.split(X):\n        model = make_model().fit(X[train_idx], target[train_idx])\n        leftover[test_idx] = target[test_idx] - model.predict(X[test_idx])\n    return leftover\n\ny_cf = crossfit_leftovers(X_sim, Y_sim, memoriser)\nd_cf = crossfit_leftovers(X_sim, D_sim, memoriser)\ntheta_crossfit = np.sum(d_cf * y_cf) / np.sum(d_cf * d_cf)\nprint(f\"Effect estimated with cross-fitting: {theta_crossfit:.2f}  (true effect is 1.0)\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEffect estimated with cross-fitting: 0.93  (true effect is 1.0)\n```\n:::\n:::\n\n\nWith cross-fitting the estimate is 0.93, close to the true value of 1. The plot lines the two up against the truth.\n\n::: {#52bd0292 .cell execution_count=4}\n``` {.python .cell-code}\nplt.figure(figsize=(7, 5))\nplt.bar([\"same data\\n(no cross-fitting)\", \"cross-fitting\"],\n        [theta_same_data, theta_crossfit],\n        color=[\"tab:red\", \"tab:green\"])\nplt.axhline(1.0, color=\"black\", linestyle=\"--\", label=\"true effect = 1\")\nplt.ylabel(\"estimated effect\")\nplt.title(\"Cross-fitting rescues the estimate from a memorising learner\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_07_double_machine_learning_files/figure-html/cell-5-output-1.png){width=589 height=446}\n:::\n:::\n\n\n::: {.callout-important}\n## The cross-fitting rule\n\nNever use the same household both to fit a nuisance model and to compute its leftover. Fit on one part of the data, take leftovers on another, and rotate. This lets us add a flexible, non-overfitting learner into the procedure keeping the true effect uncontaminated. Orthogonalization plus cross-fitting is what makes the name **double** machine learning.\n:::\n\n## 3. Double Machine Learning\n\nWe now have every piece. The recipe: cross-fit the leftovers of the outcome and the treatment with whatever learner we choose, then regress one on the other for the effect. A standard error comes from the spread of the per-household terms, the same influence-function concept from the doubly-robust score in Notebook 6.\n\n::: {#14ef5892 .cell execution_count=5}\n``` {.python .cell-code}\ndef dml_effect(X, D, Y, make_outcome, make_treatment, n_splits=5):\n    folds = KFold(n_splits, shuffle=True, random_state=RANDOM_STATE)\n    y_left = np.zeros(len(Y))\n    d_left = np.zeros(len(D))\n    for train_idx, test_idx in folds.split(X):\n        out = make_outcome().fit(X[train_idx], Y[train_idx])\n        y_left[test_idx] = Y[test_idx] - out.predict(X[test_idx])\n        treat = make_treatment().fit(X[train_idx], D[train_idx])\n        d_hat = treat.predict_proba(X[test_idx])[:, 1] if hasattr(treat, \"predict_proba\") \\\n            else treat.predict(X[test_idx])\n        d_left[test_idx] = D[test_idx] - d_hat\n    theta = np.sum(d_left * y_left) / np.sum(d_left * d_left)\n    resid = y_left - theta * d_left\n    se = np.sqrt(np.mean(d_left ** 2 * resid ** 2) / np.mean(d_left ** 2) ** 2 / len(Y))\n    return theta, se\n```\n:::\n\n\nNow we load our real 401(k) data and run it, using a random forest to model both savings and eligibility.\n\n::: {#2c714773 .cell execution_count=6}\n``` {.python .cell-code}\nsavings = pd.read_csv(\"datasets/Pension401k.csv\")\nconfounders = [\"age\", \"inc\", \"educ\", \"fsize\", \"marr\", \"twoearn\", \"db\", \"pira\", \"hown\"]\nD = savings[\"e401\"].to_numpy().astype(float)\nY = savings[\"net_tfa\"].to_numpy()\nX = savings[confounders].to_numpy()\n\ndef forest_reg():\n    return RandomForestRegressor(n_estimators=300, min_samples_leaf=20,\n                                 random_state=RANDOM_STATE, n_jobs=-1)\ndef forest_clf():\n    return RandomForestClassifier(n_estimators=300, min_samples_leaf=20,\n                                  random_state=RANDOM_STATE, n_jobs=-1)\n\ntheta, se = dml_effect(X, D, Y, forest_reg, forest_clf)\nprint(f\"DML estimate of the effect of eligibility: {theta:.2f}  (se {se:.2f})\")\nprint(f\"t-statistic: {theta / se:.1f}\")\nprint(f\"95% interval: {theta - 1.96 * se:.2f} to {theta + 1.96 * se:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDML estimate of the effect of eligibility: 8.80  (se 1.35)\nt-statistic: 6.5\n95% interval: 6.15 to 11.45\n```\n:::\n:::\n\n\nThe effect is 8.80 thousand dollars, with a standard error of 1.35 and a t-statistic of 6.5. The 95% interval runs from 6.15 to 11.45, well clear of zero. Eligibility for a 401(k) raised net financial assets by 8,800 dollars. This is the number Notebook 6 could not reach: its interval reached up toward nine but could not rule out zero, and DML, with flexible models and cross-fitting, finds the positive effect. Most of the raw 19.6 gap from Notebook 4 was selection, but a real and substantial effect of 8,800 dollars remains underneath.\n\nThe picture behind the number is the residual-on-residual scatter, the same one from Notebook 4, now with the forest doing the residualizing. We compute the two leftovers out-of-fold and plot one against the other; the slope of the line is the effect.\n\n::: {#eca4ad4e .cell execution_count=7}\n``` {.python .cell-code}\nfolds = KFold(5, shuffle=True, random_state=RANDOM_STATE)\ny_left = np.zeros(len(Y))\nd_left = np.zeros(len(D))\nfor train_idx, test_idx in folds.split(X):\n    y_left[test_idx] = Y[test_idx] - forest_reg().fit(X[train_idx], Y[train_idx]).predict(X[test_idx])\n    treat = forest_clf().fit(X[train_idx], D[train_idx])\n    d_left[test_idx] = D[test_idx] - treat.predict_proba(X[test_idx])[:, 1]\n\nplt.figure(figsize=(8, 5))\nplt.scatter(d_left, np.clip(y_left, -100, 200), s=6, alpha=0.2, color=\"grey\")\ngrid = np.array([d_left.min(), d_left.max()])\nplt.plot(grid, theta * grid, color=\"tab:green\", linewidth=2, label=f\"slope = {theta:.2f}\")\nplt.xlabel(\"leftover eligibility (after removing the covariates)\")\nplt.ylabel(\"leftover savings (after removing the covariates)\")\nplt.title(\"The effect is the slope through the residual-on-residual cloud\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_07_double_machine_learning_files/figure-html/cell-8-output-1.png){width=679 height=449}\n:::\n:::\n\n\nEach grey dot is one household, placed by how much of its eligibility and its savings is left once the covariates are stripped out. The cloud tilts upward: households with more leftover eligibility tend to have more leftover savings. The slope of that tilt, drawn in green, is the estimated effect of 8.80. It is the same residual-on-residual picture as Notebook 4, with a random forest doing the stripping in place of a lasso.\n\n### 3.1 Any learner in DML\n\nThe causal machinery, residualize, cross-fit and regress, never mentioned which learner we used. So we can drop in any learner and the estimate holds. We run the same DML with three very different learners, a lasso, a random forest, and gradient boosting (the sequential tree method from Notebook 3, which builds many small models that each correct the errors left by the ones before).\n\n::: {#8a6873de .cell execution_count=8}\n``` {.python .cell-code}\nlearners = {\n    \"lasso\": (lambda: LassoCV(cv=5, random_state=RANDOM_STATE, max_iter=50000),\n              lambda: LogisticRegression(max_iter=2000)),\n    \"random forest\": (forest_reg, forest_clf),\n    \"boosting\": (lambda: GradientBoostingRegressor(random_state=RANDOM_STATE),\n                 lambda: GradientBoostingClassifier(random_state=RANDOM_STATE)),\n}\n\nresults = {name: dml_effect(X, D, Y, mo, mt) for name, (mo, mt) in learners.items()}\nfor name, (th, s) in results.items():\n    print(f\"{name:14s}: {th:.2f}  (se {s:.2f}, t {th / s:.1f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nlasso         : 6.12  (se 1.47, t 4.2)\nrandom forest : 8.80  (se 1.35, t 6.5)\nboosting      : 9.62  (se 1.34, t 7.2)\n```\n:::\n:::\n\n\n::: {#e832021f .cell execution_count=9}\n``` {.python .cell-code}\nnames = list(results)\nthetas = [results[n][0] for n in names]\nerrs = [1.96 * results[n][1] for n in names]\n\nplt.figure(figsize=(8, 5))\nplt.bar(names, thetas, yerr=errs, capsize=6, color=[\"tab:blue\", \"tab:green\", \"tab:orange\"])\nplt.axhline(0, color=\"black\", linewidth=1)\nplt.ylabel(\"estimated effect of eligibility ($1,000s)\")\nplt.title(\"Any learner gives a positive, significant effect\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_07_double_machine_learning_files/figure-html/cell-10-output-1.png){width=659 height=431}\n:::\n:::\n\n\nAll three learners agree: the effect is positive and significant. The lasso, a linear model, finds 6.12; the random forest gives 8.80 and gradient boosting 9.62, both higher because they capture more of the tangled savings function. The exact number shifts with how flexibly we model the nuisances, but the end result does not. It is positive and significant!\n\n::: {.callout-tip}\n## Self-test\n\nCross-fitting splits the data into folds, much like the cross-validation of Notebook 1. Are they doing the same job?\n\n<details><summary>Show / hide answer</summary>\nNo, they share the mechanism but not the purpose. Cross-validation in Notebook 1 splits the data to *choose a hyperparameter*, by scoring predictions on held-out folds. Cross-fitting splits the data to *keep the nuisance models from contaminating the effect*, by computing each household's leftover from a model that never saw it.\n</details>\n:::\n\n### 3.2 Review of the DML recipe\n\nWe built double machine learning a piece at a time. Here is the whole workflow gathered together:\n\n::: {.callout-note}\n## The double machine learning recipe\n\n1. **Pick the target.** Write the partially linear model and identify the number you want, the treatment effect $\\theta$.\n2. **Choose two learners.** One to predict the outcome from the covariates, one to predict the treatment from the covariates. Any learner works, so pick whatever fits the data best.\n3. **Cross-fit the leftovers.** Split the data into folds. For each fold, fit both learners on the other folds and take each unit's leftover, its value minus the prediction, out-of-fold, so no unit helps fit the model that later judges it.\n4. **Regress leftover on leftover.** Regress the outcome leftovers on the treatment leftovers. The slope is the estimated effect.\n5. **Report the uncertainty.** Take the standard error from the spread of the per-unit terms, and form the confidence interval.\n:::\n\n## 4. Connections\n\nThis notebook is where we see the stream's biggest conceptual payoffs. The prediction tools from Notebooks 1 to 3 became the learners which power DML and the orthogonalization of Notebook 4 became the framework, and then cross-fitting made the technique trustworthy. The result is a recipe that estimates a causal effect with any learner and reports a valid standard error. In practice the `doubleml` python package implements all of this and more, but the moving parts are the ones we built by hand here.\n\n- **Back to Notebook 6:** there the doubly-robust estimate of the 401(k) effect was too imprecise to sign; double machine learning sharpens it to about 9,000 dollars by using flexible learners and cross-fitting.\n- **Forward to Notebook 8:** from the average effect to who benefits, estimating effects that vary across households with causal forests.\n\n### References\n\n- Ahrens, A., Chernozhukov, V., Hansen, C., Kozbur, D., Schaffer, M., & Wiemann, T. (2025). *An introduction to double/debiased machine learning.* arXiv:2504.08324.\n- Bach, P., Chernozhukov, V., Kurz, M. S., & Spindler, M. (2022). *DoubleML: An object-oriented implementation of double machine learning in Python.* Journal of Machine Learning Research, 23(53), 1-6.\n- Chernozhukov, V., Chetverikov, D., Demirer, M., Duflo, E., Hansen, C., Newey, W., & Robins, J. (2018). *Double/debiased machine learning for treatment and structural parameters.* Econometrics Journal, 21(1), C1-C68. The orthogonal moment and cross-fitting.\n- Frisch, R., & Waugh, F. V. (1933). *Partial time regressions as compared with individual trends.* Econometrica, 1(4), 387-401. The residual-on-residual result.\n- Poterba, J. M., Venti, S. F., & Wise, D. A. (1995). *Do 401(k) contributions crowd out other personal saving?* Journal of Public Economics, 58(1), 1-32. The eligibility question.\n\n---\n\n",
    "supporting": [
      "notebook_07_double_machine_learning_files"
    ],
    "filters": [],
    "includes": {}
  }
}