{
  "hash": "78a11a2be56a397ee8131489dea79e6c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"1.1 - Beginner - Introduction to Central Tendency\"\nauthor: COMET Team <br> _Sarthak Kwatra and Jonathan Graves_ \nversion: 1.0\ndate: 2023-10-13\ndescription: This notebook is an hands-on introduction to the concepts of Central Tendency at the beginner level using R. It is meant for undergraduates with no or very little prior exposure to university-level statistics. \ncategories: [introduction, beginner, econ 226, econ 227, central tendency, mean, median, mode, skewness, dispersion, R, histogram]\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html: default\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: R\n        language: r\n        name: ir\nimage: /media/comet_placeholder.png\n---\n\n## Prerequisites\n\n-   Introduction to Jupyter\n-   Introduction to R\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importing the packages we'll be using in this module!\n\n# If any of these packages isn't installed run the line - install.packages(\"ggplot2\") -  with the name of the package within the quotation marks\nlibrary(ggplot2)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'ggplot2' was built under R version 4.4.3\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyverse' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tibble' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'tidyr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'readr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'purrr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'dplyr' was built under R version 4.4.3\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'stringr' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'forcats' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: package 'lubridate' was built under R version 4.4.2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.2.0     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ lubridate 1.9.4     ✔ tibble    3.2.1\n✔ purrr     1.0.4     ✔ tidyr     1.3.1\n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n:::\n\n\n\n:::{.callout-warning}\n## Work in Progress\n\nWe haven't written self-tests for this unit yet!  You'll have to check with your friends if you've got them right or not!\n\n* Want to submit some?  [Contact us!](mailto:comet.project@ubc.ca)\n:::\n\n## Introduction to Central Tendency\n\nFor a moment, let's think of data as alphabets. This data, or these alphabets, are available to us, but they are disarrayed and scattered, and they may mean nothing by themselves. However, if we look at data as alphabets, statistics is the language that we use to put alphabets into words to understand and communicate. Statistics is how we make sense of data. \n\nTherefore, understanding different statistical tools is almost like knowing different languages. All these statistical tools use the same alphabets (the data), and yet communicate a variety of things. \n\nStatistics is an economist's arsenal of techniques and tools that allows them to extract meaningful insights from data. Many of these tools calculate a single representative value that summarizes the data in one way or another.  We call these **numerical statistics**.\n\n> Here's a helpful way of thinking about it: Have you ever tried summarizing a movie to a friend? You'd probably pick the most significant events or themes, presenting a concise yet comprehensive overview. Similarly, statistical concepts aims to \"summarize\" a data set into a single **typical** value. \n\nIf you don't have any experience with statistics, don't fret! This course starts with all of the concepts from the ground up. If you have experience with statistics, this course will allow you to associate each statistical concept with R Code to make you even more efficient. The first among these statistical tools is the idea **central tendency**. \n\nCentral tendency is meant to talk about what is \"typical\" for a dataset.  Specifically, as evident from the term, tools of _central_ tendency are concerned with the _centrality_ of the data, or the middle values of the data. However, the center or the middle can mean multiple different things as far as data is concerned. \n\nImagine standing in a room full of people and trying to find an average height. Or imagine being in a city and trying to find the most common temperature during the summer. Or imagine trying to understand what is the most commonly purchased car in your city. Both these tasks involve finding a 'central' or 'typical' value, which is the essence of central tendency.\n\nIn order to understand the concepts of central tendency and use them, we'll need a data set to work with. For this purpose, we will be using the `swiss` dataset that comes in-built as a part of R. We don't need to import it, we just need to call the dataset. Additionally, for convenience, we'll try to have a glimpse of the data set to see if anything important jumps out to us immediately. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(swiss)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 47\nColumns: 6\n$ Fertility        <dbl> 80.2, 83.1, 92.5, 85.8, 76.9, 76.1, 83.8, 92.4, 82.4,…\n$ Agriculture      <dbl> 17.0, 45.1, 39.7, 36.5, 43.5, 35.3, 70.2, 67.8, 53.3,…\n$ Examination      <int> 15, 6, 5, 12, 17, 9, 16, 14, 12, 16, 14, 21, 14, 19, …\n$ Education        <int> 12, 9, 5, 7, 15, 7, 7, 8, 7, 13, 6, 12, 7, 12, 5, 2, …\n$ Catholic         <dbl> 9.96, 84.84, 93.40, 33.77, 5.16, 90.57, 92.85, 97.16,…\n$ Infant.Mortality <dbl> 22.2, 22.2, 20.2, 20.3, 20.6, 26.6, 23.6, 24.9, 21.0,…\n```\n\n\n:::\n:::\n\n\n`swiss` is a data set with records for socio-economic indicators for each of 47 French-speaking provinces of Switzerland at about 1888. Each of these uniquely recognized administrative divisions are called _cantons_. This dataset is like a guidebook, giving us insights into each canton's characteristics. As a budding economist building your statistical arsenal, the `swiss` data set is the perfect place to start!\n\nAside from just looking at your data set, one of the more helpful ways to understand your data set is to visualize it. Across the 47 cantons, let's try to observe the `Agriculture` variable in our data set, which stands for \"% of males involved in agriculture as occupation\", and see how it varies. \n\nFor this, we'll rely on a plot that is known as a **histogram**. A histogram is a plot that groups data into ranges or \"bins\" and showcases the frequency of our data points within these ranges. Let's go ahead and visualize it!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nagriculture_plot <- ggplot(swiss, aes(y = Agriculture)) + \n  geom_histogram( \n                 bins = 30, \n                 fill=\"lightgray\", \n                 color=\"black\", \n                 alpha = 0.7) +\n  labs(title = \"Histogram of Agriculture Rates\", \n       x = \"Frequency\", \n       y = \"% of Men Involved in Agriculture as an Occupation\") +\n  scale_x_continuous(breaks = seq(min(swiss$Agriculture), max(swiss$Agriculture))) +\n  scale_y_continuous(n.breaks = 10) +\n  theme_minimal()\n\nagriculture_plot\n```\n\n::: {.cell-output-display}\n![](beginner_intro_to_central_tendency_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nIn a very similar manner, let's also look at another variable, `Education`, which stands for the percentage of draftees educated beyond primary school for each of the cantons. \n\n\n::: {.cell}\n\n```{.r .cell-code}\neducation_plot <- ggplot(swiss) + \n  geom_histogram(aes(y = Education), \n                 bins = 10, \n                 fill=\"lightgray\", \n                 color=\"black\", \n                 alpha = 0.7) +\n  labs(title = \"Histogram of Education in Draftees\", \n       x = \"Frequency\", \n       y = \"% Education beyond Primary School for Draftees.\") +\n  scale_x_continuous(breaks = seq(min(swiss$Education), max(swiss$Education))) +\n  scale_y_continuous(n.breaks = 10) +\n  theme_minimal()\n\neducation_plot\n```\n\n::: {.cell-output-display}\n![](beginner_intro_to_central_tendency_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\nThese graphs allow us to observe the distribution of the observations across the different levels in our variables. For instance, we can observe that for `Agriculture`, observations between 60 - 70 tend to have the highest frequency. Or on the other hand, most of the observations in the `Education` variable are in the 0 - 10 area. \n\nWhat does this all mean? How do we interpret all of these? To do this, we'll take assistance of a few statistical concepts, namely: **Mean, Median, and Mode**, all of which are different interpretations of the word middle. Mean, Median, and Mode are the three primary concepts in the idea of central tendency.\n\n> **Test Your Knowledge**:  Before you move on, where does the \"middle\" of the data look like for `Education`?  `Agriculture`?  Write down your answers, and see how the relate to the numerical statistics we will compute below.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# My answers are:\n\nMiddle_of_education <- ?\nMiddle_of_agriculture <- ?\n```\n:::\n\n\n## The Key Ideas of Central Tendency\n\n### Mean \n\nAt its core, the mean^[Specifically, the _arithmetic mean_.] is a simple concept – it is what you get when you distribute the total equally among every entry in the data set. Or alternatively, when you sum all of the observations in a data set, then divide by the number of observations in that data set. Formulaically, \n\n$$\n\\overline{X} = \\frac{1}{n}\\sum_{i=1}^{n} X_i =  \\frac{\\text{Sum of Value of All Data Points}}{\\text{Total Number of Data Points}}\n$$\n\nHere, $\\sum$ stands for summation, and $\\overline{X}$ is what is used to represent the mean. While this may be enough for you to understand the concept, we can nuance this explanation a slight bit and make it more intuitive to interpret!\n\n> **Check Your Understanding**: can you see why the two explanations for the mean given above are the same?\n\nLet's imagine a scenario within the context of our `swiss` dataset.  If we considered all the cantons in Switzerland, what education level would a \"typical\" canton have?  This is the **Mean Education Rate**. In R, the Mean is calculated quite simply through the `mean` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean_education <- mean(swiss$Education)\nmean_education\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.97872\n```\n\n\n:::\n:::\n\n\nWe could also check our comparison by computing it manually as well:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntotal_education <- sum(swiss$Education)\ntotal_cantons <- nrow(swiss) #number of observations in `swiss`\n\nmean_education_manual <- total_education/total_cantons\nmean_education_manual\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.97872\n```\n\n\n:::\n:::\n\n\nThis allows us to notice that the **Mean Education Rate** across all of the Swiss cantons is **10.98%**. You can practice this yourself as well! Try to calculate fraction of Catholics within a typical Swiss canton in the code block below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Note: The first blank is supposed to be the function, and the second blank is supposed to be the variable\navg_mean_catholic <- ...(swiss$...)\n```\n:::\n\n\nHaving observed the mean numerically, we can make our understanding of the concept even more robust by observing it visually. We can do this by slightly adjusting one of the histograms we've come up with earlier.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neducation_plot + \n  geom_hline(aes(yintercept=mean_education), color=\"red\", linetype=\"dashed\", linewidth=1)\n```\n\n::: {.cell-output-display}\n![](beginner_intro_to_central_tendency_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\nSee the red line?  This is the mean we calculated before!  How does it compare to the guess you made based on the histogram?\n\nHowever, as with any tool, it is important to understand the appropriate use of the mean as well as its limitations. One of the primary limitations of the mean is that it is severely affected by extreme values. \n\nLet's say there was an error in recording, and a canton accidentally reported an extremely high fertility rate, much beyond the actual range. We'll simulate this and see its effect on the mean.\n\nFirst, let's store your fertility measure from before as the original mean fertility rate:\n\n\n::: {.cell}\n\n```{.r .cell-code}\noriginal_mean <- mean(swiss$Fertility)\noriginal_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70.14255\n```\n\n\n:::\n:::\n\n\nThen, let's introduce an extreme value. For the sake of illustration, we'll assign an unrealistically high fertility rate (e.g., 1000) to the first canton:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nswiss_with_extreme <- swiss\nswiss_with_extreme$Fertility[1] <- 1000\n```\n:::\n\n\nNow, let's compute the original mean with this extreme value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextreme_mean <- mean(swiss_with_extreme$Fertility)\nextreme_mean\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 89.71277\n```\n\n\n:::\n:::\n\n\nThis allows us to observe how significant a change a single observation can bring around in the Mean, making it jump from 70 to 89.7. For good measure, let's also observe this visually: \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_histogram(data = swiss, aes(x=log(Fertility)), color=\"blue\", alpha=0.1, boundary = 0) +\n  geom_vline(aes(xintercept=log(original_mean)), color=\"blue\", linetype=\"dashed\", size=1) +\n  geom_histogram(data = swiss_with_extreme, aes(x=log(Fertility)), fill=\"red\", alpha=0.3, boundary = 0) +\n  geom_vline(data = swiss, aes(xintercept=log(extreme_mean)), color=\"red\", linetype=\"dashed\", size=1) +\n  labs(title=\"Effect of Extreme Value on Mean Fertility Rate\",\n       x=\"Fertility Rate (in logs)\",\n       fill=\"Dataset\") +\n  scale_fill_manual(values = c(\"blue\", \"red\"), labels = c(\"Original Data\")) +\n  theme_minimal()\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\nIgnoring unknown labels:\n• fill : \"Dataset\"\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](beginner_intro_to_central_tendency_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\nIn this plot, the blue histogram represents the original `swiss` data set, while the red histogram represents the data set with the extreme value. See how they're pretty similar?\n\nThe dashed lines indicate the mean of each data set. It becomes evident how the mean shifts due to just one extreme value, showcasing the sensitivity of the mean to outliers.\n\nIn conclusion, the mean is particularly susceptible to extremes in a data set. This sensitivity is a primary reason why, in skewed distributions or when outliers are suspected, one might also consider other metrics of central tendency, like the median, which remains robust in the presence of extreme values. To deal with this potential issue, we naturally move onto other measures of central tendency. \n\n## The Median\n\nThe **median** is, quite literally, the **middle** of an ordered sequence. The idea of centrality with the Median is to essentially order the data set, be it in an ascending or a descending order, and then dividing the data set in half. However, one of the characteristics that makes the Median important is that it allows us to deal with the very problem that we just elaborated on about the Mean. It is resilient to outliers or the extreme values in the data. \n\nIt provides a central location of your dataset. For a symmetrical dataset, the mean and median will be the same. However, for a skewed dataset, the median will lie closer to the bulk of the data, making it a more representative metric.\n\nTo calculate the Median, you arrange data in ascending (or descending) order. Let $n$ be the number of data points. If $n$ is odd, then:\n\n$$\n\\text{Median} = \\frac{n+1}{2}\\text{th data point}\n$$ \n\nOtherwise,\n\n$$\n\\text{Median}  = \\frac{1}{2} \\cdot [\\frac{n}{2}\\text{th data point} + (\\frac{n}{2} + 1)\\text{th data point}]\n$$\n\nNot nice!  On the other hand, in R, computing the median is straightforward using the built-in `median()` function.\n\nUsing the Fertility column of the swiss dataset as an example:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating the median\nmedian_fertility <- median(swiss$Fertility)\nmedian_fertility\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 70.4\n```\n\n\n:::\n:::\n\n\nTo further visualize where the median lies in relation to the data:\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plotting the data and highlighting the median\n\nfertility_plot <- ggplot(swiss, aes(x=Fertility)) + \n  geom_histogram(binwidth=2, fill=\"lightgray\", color=\"black\", alpha=0.7) + \n  geom_vline(aes(xintercept=median_fertility), color=\"red\", linetype=\"dashed\", size=1) +\n  labs(title=\"Median Fertility Rate Across Swiss Cantons\", x=\"Fertility Rate\") +\n  annotate(\"text\", x = median_fertility + 10, y=8, label = paste(\"Median:\", round(median_fertility, 2)), color=\"red\")\n\nfertility_plot\n```\n\n::: {.cell-output-display}\n![](beginner_intro_to_central_tendency_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\nFinally, to bring this concept home, let's repeat this exercise with the `Education` variable:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculating the median\nmedian_education <- median(swiss$Education)\nmedian_education\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 8\n```\n\n\n:::\n:::\n\n\nTo further visualize where the median lies in relation to the data:\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plotting the data and highlighting the median\n\neducation_plot + \n  geom_hline(aes(yintercept = median_education), color=\"red\", linetype=\"dashed\", size=1) +\n  labs(title=\"Median Education Rate Across Swiss Cantons\", x=\"Education Rate\") +\n  annotate(\"text\", y = median_education + 2, x=8, label = paste(\"Median:\", round(median_education, 2)), color=\"red\")\n```\n\n::: {.cell-output-display}\n![](beginner_intro_to_central_tendency_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n### Outlier Robustness\n\nOne important property of the median is that it is **robust to outliers**, unlike the mean.  This makes sense, since it only has to do with the _rank_ of observations: it doesn't matter how high the highest value is, or how low the lowest value is.\n\nWe can see this with our `swiss` education situation before.  Try it!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# compute the median for education in the original data\n\noriginal_median <- ...(swiss$Education)\noriginal_median\n\nmedian_with_extreme <- ...(...)\nmedian_with_extreme\n```\n:::\n\n\nWhat do you see?  If you want, try changing that extreme value (`1000`) to other values.  Does it make a difference?\n\n## Mode\n\nThe **mode** refers to the value(s) that **appears most frequently** in a data set. This stands in contrast to other measures like the mean, which gives an average, or the median, which provides a midpoint. \n\nThe beauty of the mode is its _versatility_. It's relevant for both numeric data sets and qualitative data. This means that the mode can be used to gauge whether a value, such as `5`, appears with the greatest frequency in a data set, as well as if a category like `\"Female\"` or `\"University Graduate\"` appears with the greatest frequency.\n\nHowever, this is also the problem with mode.  A data set's relationship with mode can be quite complicated. \n\n* It might not have a mode if no value repeats...\n* be **uni-modal** if one value dominates in frequency... \n* **bi-modal** if two values tie in their recurrence...\n* or even **multimodal** if multiple values share the highest frequency.\n\nIn R, we can calculate the mode without relying on external packages, since unlike the `mean` or the `median` function, there is no `mode` function.  But mode is so simple, we can create one ourselves.\n\nConsider a function that first creates a frequency table of the data set in question. It then identifies the maximum frequency from this table. Using this frequency, it's possible to extract the modes, which are the values that appear with this maximum frequency. Here's how it might look:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncalculate_mode <- function(x) {\n  # Tabulating frequencies of each value in the dataset\n  freq_table <- table(x)\n  \n  # Determining the maximum frequency\n  max_freq <- max(freq_table)\n  \n  # Pinpointing the values (modes) that correspond to the maximum frequency\n  modes <- as.numeric(names(freq_table[freq_table == max_freq]))\n  \n  return(modes)\n}\n\n# Applying the function on the 'Education' column from the 'swiss' dataset\nmodes_education <- calculate_mode(swiss$Education)\n\nmodes_education\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7\n```\n\n\n:::\n:::\n\n\nTherefore, as our function correctly interprets, the Mode for the Education variable is 7. This means that among the cantons, a lot of them have 7% draftees who are educated above the primary school level. \n\n## Getting All of Central Tendency Together\n\nTo truly appreciate the nature of a data set, it's beneficial to look at the mode in tandem with other measures like the mean and median. Together, these metrics provide a fuller, more nuanced picture of the data's central tendency. By superimposing our histogram with lines symbolizing the mean (blue), median (red), and mode (green), we create a tapestry that visually harmonizes the data's spread with its central measures.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(swiss, aes(x = Education)) + \n  geom_histogram(binwidth = 2, fill=\"lightgray\", color=\"black\", alpha=0.7) + \n  geom_vline(aes(xintercept = mean_education), color=\"blue\", linetype=\"dashed\", size=1) +\n  geom_vline(aes(xintercept = median_education), color=\"red\", linetype=\"dashed\", size=1) +\n  geom_vline(aes(xintercept = modes_education), color=\"green\", linetype=\"dashed\", size=1) +\n  labs(title=\"Median Education Rate Across Swiss Cantons\", x=\"Education Rate\")\n```\n\n::: {.cell-output-display}\n![](beginner_intro_to_central_tendency_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nSee the relationship?  We can also do this in a table using the `summarize` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nswiss %>%\n  summarize(\n    mean = mean(Education),\n    median = median(Education),\n    mode = calculate_mode(Education)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      mean median mode\n1 10.97872      8    7\n```\n\n\n:::\n:::\n\n\nThis is called a **table of descriptive statistics** and is an important tool for any economist.\n\n### Try it Yourself!\n\nAs a final check, why don't you make a nice table of the same results for Fertility, as well?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nswiss %>%\n  summarize(\n    ...\n  )\n```\n:::\n\n\nWhat do you see?",
    "supporting": [
      "beginner_intro_to_central_tendency_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}