{
  "hash": "326a8bdfdcfda5d0b490a2def108fa2b",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"From Prediction to Treatment Effects\"\nauthor: Alex Ronczewski\ndate: 2026-06-18\ndescription: \"The fourth notebook in the Causal ML stream. We move away from prediction to causality. We meet potential outcomes, the average treatment effect, selection bias, and the unconfoundedness assumption, we see how the prediction tools from Notebooks 1 to 3 are used for causal estimation, and we see why using them naively gives a biased effect, which sets up the orthogonalization and cross-fitting.\"\ncategories:\n  - Python\n  - machine learning\n  - causal inference\n  - potential outcomes\n  - treatment effects\n  - unconfoundedness\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html:\n    embed-resources: true\n    self-contained-math: true\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: Python\n        language: python3\n        name: python3\n---\n\n\n\n\n\n\n## Outline\n\n### Prerequisites\n\n- Notebook 3 of this stream: trees and forests, the train/test/cross-validate recipe, prediction is not causality. \n- The COMET Intermediate notebooks on regression, and some exposure to instrumental variables and difference-in-differences (ECON 326)\n- Comfort with `pandas` and basic Python at the COMET-intermediate level\n\n### Learning Outcomes\n\nBy the end of this notebook you will be able to:\n\n1. Explain the difference between a **prediction** problem and an **identification** problem.\n2. Write down the **potential outcomes** $Y(0)$ and $Y(1)$ and state the fundamental problem of causal inference.\n3. Define the **average treatment effect (ATE)** and the naive difference in means.\n4. Explain **selection bias**: why the naive comparison is not the ATE.\n5. State the **unconfoundedness** and **overlap** assumptions and explain how they identify the ATE by adjusting for $X$.\n6. Describe how the prediction tools from Notebooks 1 to 3 connect to causal estimation as **nuisance** estimators.\n7. Explain why using machine learning naively gives a **biased** treatment effect, and describe **orthogonalization** and **cross-fitting** as the fix.\n8. Say what to do when unconfoundedness fails, and connect it to **IV** and **DiD** from COMET.\n\n::: {#b366aefc .cell execution_count=1}\n``` {.python .cell-code}\nimport numpy as np\nimport pandas as pd\nimport matplotlib.pyplot as plt\n\nfrom sklearn.linear_model import LinearRegression, LassoCV\n\nRANDOM_STATE = 42  # fix randomness so the simulations are reproducible\nTRUE_EFFECT = 1.0  # in our simulated worlds we get to set the real effect ourselves\n```\n:::\n\n\n## 1. Prediction to Causality\n\nFor two of our three notebooks we asked how well we can predict savings from a household's characteristics, with having a 401(k) as the main variable. KNN, ridge, lasso, trees, and forests are all answers to that, and each notebook closed with the same warning, that a model that predicts savings well doesn't tell us the **effect** of 401(k) eligibility on savings.\n\nFrom now on we'll be shifting away from prediction. Prediction asks for a good guess of $Y$, while causal analysis asks for the effect of a **treatment** $D$ on $Y$: how much would a household's savings change if we made it eligible for a 401(k) and changed nothing else? Call $D$ the treatment (here `e401`, eligibility), $Y$ the outcome (here `net_tfa`), and $X$ the household's other characteristics. We want the effect of $D$ on $Y$. This is causal analysis. \n\nThis notebook is more conceptual and dense than the other notebooks, but it is also the most important.  \n\n### 1.1 Why a naive comparison fails\n\nThe obvious thing to do is compare the savings of households that are eligible for a 401(k) with those that are not. We just subtract mean net financial assets of ineligible households from eligible ones.\n\n::: {#96eda291 .cell execution_count=2}\n``` {.python .cell-code}\nsavings = pd.read_csv(\"datasets/Pension401k.csv\")\nconfounders = [\"age\", \"inc\", \"educ\", \"fsize\", \"marr\", \"twoearn\", \"db\", \"pira\", \"hown\"]\nD = savings[\"e401\"].to_numpy()\nY = savings[\"net_tfa\"].to_numpy()\n\nnaive_gap = Y[D == 1].mean() - Y[D == 0].mean()\nprint(f\"Eligible households, mean net financial assets  : {Y[D == 1].mean():.1f}\")\nprint(f\"Ineligible households, mean net financial assets: {Y[D == 0].mean():.1f}\")\nprint(f\"Naive difference (eligible minus ineligible)    : {naive_gap:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nEligible households, mean net financial assets  : 30.3\nIneligible households, mean net financial assets: 10.8\nNaive difference (eligible minus ineligible)    : 19.6\n```\n:::\n:::\n\n\nEligible households have about $19,600 more in net financial assets. It is tempting to call that the effect of eligibility for the 401(k). The problem is that eligible and ineligible households differ in ways that have nothing to do with 401(k) eligibility. Eligibility comes bundled with certain jobs, and those jobs often pay more, so eligible households already earn more, and higher earners already save more. The plot below shows the income gap directly.\n\n::: {#5855b78d .cell execution_count=3}\n``` {.python .cell-code}\nplt.figure(figsize=(9, 5))\nplt.hist(savings.loc[savings.e401 == 0, \"inc\"].clip(0, 150), bins=40,\n         alpha=0.6, density=True, label=\"ineligible\")\nplt.hist(savings.loc[savings.e401 == 1, \"inc\"].clip(0, 150), bins=40,\n         alpha=0.6, density=True, label=\"eligible\")\nplt.xlabel(\"household income ($1,000s)\")\nplt.ylabel(\"density\")\nplt.title(\"Eligible households already earn more, so the groups are not comparable\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_04_prediction_to_treatment_effects_files/figure-ipynb/cell-4-output-1.png){}\n:::\n:::\n\n\nThe eligible group sits to the right of the ineligible group, its income distribution is shifted rightwards. Some of the $19,600 gap is the effect of eligibility, and some of it comes from comparing richer households with poorer ones. The naive difference mixes the two together and can't separate them. This leads to bias. \n\nThe household's characteristics $X$, its income, age, and the rest, influence both whether it is eligible and how much it saves. A variable that causes both the treatment and the outcome is a **confounder**, and it is what makes the naive comparison untrustworthy.\n\n::: {#02d39d98 .cell execution_count=4}\n``` {.python .cell-code}\nfig, ax = plt.subplots(figsize=(7, 4.5))\nnodes = {\"X\": (0.5, 0.8), \"D\": (0.2, 0.2), \"Y\": (0.8, 0.2)}\nbox = dict(boxstyle=\"circle,pad=0.45\", fc=\"lightgrey\", ec=\"black\", lw=1.5)\nfor name, (x, y) in nodes.items():\n    ax.text(x, y, name, ha=\"center\", va=\"center\", fontsize=15, fontweight=\"bold\", bbox=box, zorder=3)\n\ndef draw_arrow(start, end, color):\n    ax.annotate(\"\", xy=nodes[end], xytext=nodes[start],\n                arrowprops=dict(arrowstyle=\"-|>\", color=color, lw=2.2, shrinkA=22, shrinkB=22))\n\ndraw_arrow(\"X\", \"D\", \"tab:red\")\ndraw_arrow(\"X\", \"Y\", \"tab:red\")\ndraw_arrow(\"D\", \"Y\", \"tab:green\")\nax.text(0.27, 0.52, \"confounding\", color=\"tab:red\", ha=\"center\", fontsize=11)\nax.text(0.73, 0.52, \"confounding\", color=\"tab:red\", ha=\"center\", fontsize=11)\nax.text(0.5, 0.13, \"the effect we want\", color=\"tab:green\", ha=\"center\", fontsize=11)\nax.set_xlim(0, 1)\nax.set_ylim(0, 1)\nax.axis(\"off\")\nax.set_title(\"X is a common cause of eligibility (D) and savings (Y): a confounder\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_04_prediction_to_treatment_effects_files/figure-ipynb/cell-5-output-1.png){}\n:::\n:::\n\n\nThe arrow from $D$ to $Y$ is the effect we are after (401(k) eligibility on savings). The two red arrows out of $X$ are the problem: they open a second route by which eligible and ineligible households come to differ in savings, one that is unrelated nothing to the $D \\to Y$ arrow. To recover the effect we have to deal with $X$ somehow, and to say precisely what we mean by \"the effect\" we first need a small piece of vocabulary.\n\n## 2. Potential outcomes\n\nThink about a single household and two versions of the world. In one it is eligible for a 401(k); in the other it is not. Note that apart from the 401(k) eligibility nothing else has changed, we hold everything else fixed, the households are otherwise identical. Write $Y(1)$ for the savings it would end up with if eligible, and $Y(0)$ for the savings it would end up with if not. These are its two **potential outcomes**. The effect of eligibility on that household is the difference between them:\n\n$$\n\\text{effect for household } i = Y_i(1) - Y_i(0).\n$$\n\nIf we could see both numbers for every household, causal inference would just be subtraction. To demonstrate this we will make a made up world where we can see $Y(1)$ and $Y(0)$ for 5 households. \n\n::: {#9a2fa2af .cell execution_count=5}\n``` {.python .cell-code}\nworld = pd.DataFrame({\n    \"household\": [1, 2, 3, 4, 5],\n    \"Y0_if_ineligible\": [12, 3, 30, 1, 45],\n    \"Y1_if_eligible\":   [16, 9, 33, 8, 47],\n})\nworld[\"effect\"] = world[\"Y1_if_eligible\"] - world[\"Y0_if_ineligible\"]\nworld[\"eligible_D\"] = [1, 0, 1, 0, 1]\nworld\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>household</th>\n      <th>Y0_if_ineligible</th>\n      <th>Y1_if_eligible</th>\n      <th>effect</th>\n      <th>eligible_D</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>12</td>\n      <td>16</td>\n      <td>4</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>3</td>\n      <td>9</td>\n      <td>6</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>30</td>\n      <td>33</td>\n      <td>3</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4</td>\n      <td>1</td>\n      <td>8</td>\n      <td>7</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5</td>\n      <td>45</td>\n      <td>47</td>\n      <td>2</td>\n      <td>1</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe `effect` column is what we are after. But now look at what we actually get to observe in the real world. Each household lives in only one version of the world: if it is eligible we see $Y(1)$ and never $Y(0)$, and if it is not we see $Y(0)$ and never $Y(1)$. Another possible example is a medical trial for a new drug, the patient either takes the drug or the placebo, we cannot have two identical people take one of each, it's either one or the other. The other potential outcome is a counterfactual we can never measure.\n\nHere is a table from our real world. \n\n::: {#aa73bc6a .cell execution_count=6}\n``` {.python .cell-code}\nobserved = world.copy()\nobserved[\"Y0_if_ineligible\"] = np.where(world.eligible_D == 0, world.Y0_if_ineligible, np.nan)\nobserved[\"Y1_if_eligible\"] = np.where(world.eligible_D == 1, world.Y1_if_eligible, np.nan)\nobserved = observed.drop(columns=[\"effect\"])  # unknowable, one outcome per row is missing\nobserved\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>household</th>\n      <th>Y0_if_ineligible</th>\n      <th>Y1_if_eligible</th>\n      <th>eligible_D</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>NaN</td>\n      <td>16.0</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>2</td>\n      <td>3.0</td>\n      <td>NaN</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>3</td>\n      <td>NaN</td>\n      <td>33.0</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>4</td>\n      <td>1.0</td>\n      <td>NaN</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5</td>\n      <td>NaN</td>\n      <td>47.0</td>\n      <td>1</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nHalf of each row is gone, and with it the `effect` column. This is the **fundamental problem of causal inference**: for any one household we see at most one of its two potential outcomes, so its individual effect is never observed and we can't directly measure it for any single household.\n\nWhat we can still hope for, though, is an average.\n\nThe **average treatment effect (ATE)** is the average of the individual effects across all households:\n\n$$\n\\text{ATE} = \\mathbb{E}\\big[\\, Y(1) - Y(0) \\,\\big].\n$$\n\nATE calculates how much eligibility would change savings on average if it were applied to everyone. The rest of the notebook is about calculating it from our real world table (which is missing half its entries).\n\n### 2.1 Selection bias\n\nThe naive difference from section 1.1 compares the savings we observe for the eligible with the savings we observe for the ineligible:\n\n$$\n\\mathbb{E}[Y \\mid D = 1] - \\mathbb{E}[Y \\mid D = 0].\n$$\n\nWrite this in potential-outcome terms. Among the eligible we observe $Y(1)$, and among the ineligible we observe $Y(0)$, so the naive difference is $\\mathbb{E}[Y(1) \\mid D = 1] - \\mathbb{E}[Y(0) \\mid D = 0]$. Add and subtract the savings the eligible group would have had without eligibility, $\\mathbb{E}[Y(0) \\mid D = 1]$, and it splits into two pieces:\n\n$$\n\\underbrace{\\mathbb{E}[Y(1) \\mid D=1] - \\mathbb{E}[Y(0) \\mid D=1]}_{\\text{effect on the eligible}} \\;+\\; \\underbrace{\\mathbb{E}[Y(0) \\mid D=1] - \\mathbb{E}[Y(0) \\mid D=0]}_{\\text{selection bias}}.\n$$\n\nThe first piece is a real treatment effect. The second is **selection bias**: the gap in $Y(0)$, the savings the two groups would have had even with no 401(k) anywhere. If eligible households are richer and save more to begin with, that gap is positive and the naive difference overstates the effect.\n\nWe cannot see the size of the bias in the real 401(k) data, because $Y(0)$ for the eligible is one of our missing counterfactuals. So we build a world where we set the true effect ourselves and can watch the bias appear. Each household has covariates $X$; both its eligibility and its savings depend on $X$, which is what ties them together and creates the bias (remember our causal diagram with $D$, $X$, $Y$). \n\nBecause we built this world, we can do something the 401(k) data never allows: look at $Y(0)$, the savings under no 401(k), for every household, including the eligible ones whose $Y(0)$ is a counterfactual in real life. The function below returns both potential outcomes next to what we would actually observe.\n\n::: {#c0b71f87 .cell execution_count=7}\n``` {.python .cell-code}\ndef simulate(n, p, confounding, seed):\n    rng = np.random.default_rng(seed)\n    X = rng.normal(0, 1, (n, p))\n    j = np.arange(1, p + 1)\n    beta = 4.0 / j**2                      # a few covariates drive savings, the rest are noise\n    gamma = confounding / j**2             # the same covariates push eligibility: the confounding\n    propensity = 1 / (1 + np.exp(-(X @ gamma)))\n    D = (rng.uniform(size=n) < propensity).astype(float)\n    noise = rng.normal(0, 1, n)\n    Y0 = X @ beta + noise                  # savings with no 401(k)\n    Y1 = TRUE_EFFECT + X @ beta + noise    # savings with a 401(k)\n    Y = np.where(D == 1, Y1, Y0)           # in real life we would see only one of these per row\n    return X, D, Y, Y0, Y1, propensity\n\nX_low, D_low, Y_low, Y0_low, Y1_low, propensity_low = simulate(\n    n=4000, p=20, confounding=2.0, seed=RANDOM_STATE)\nnaive_low = Y_low[D_low == 1].mean() - Y_low[D_low == 0].mean()\n```\n:::\n\n\nThe decomposition above asked for two quantities we normally cannot compute. The effect on the eligible is the average of $Y(1) - Y(0)$ among them, and the selection bias is the gap in $Y(0)$ between the two groups.\n\n::: {#c1f37ae2 .cell execution_count=8}\n``` {.python .cell-code}\neffect_on_eligible = (Y1_low - Y0_low)[D_low == 1].mean()\nselection_bias = Y0_low[D_low == 1].mean() - Y0_low[D_low == 0].mean()\nprint(f\"Naive difference        : {naive_low:.2f}\")\nprint(f\"  effect on the eligible: {effect_on_eligible:.2f}\")\nprint(f\"  selection bias        : {selection_bias:.2f}\")\nprint(f\"True effect we built in : {TRUE_EFFECT:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNaive difference        : 6.14\n  effect on the eligible: 1.00\n  selection bias        : 5.14\nTrue effect we built in : 1.00\n```\n:::\n:::\n\n\nThe naive difference of 6.14 is the true effect of 1 plus a selection bias of 5.14. The bias is five times the size of the quantity we are trying to measure. We can see exactly where it comes from by plotting $Y(0)$, the savings each household would have had with no 401(k), for the two groups side by side.\n\n::: {#df417c10 .cell execution_count=9}\n``` {.python .cell-code}\nplt.figure(figsize=(9, 5))\nplt.hist(Y0_low[D_low == 0], bins=40, alpha=0.6, density=True, label=\"ineligible\")\nplt.hist(Y0_low[D_low == 1], bins=40, alpha=0.6, density=True, label=\"eligible\")\nplt.axvline(Y0_low[D_low == 0].mean(), color=\"tab:blue\", linestyle=\"--\")\nplt.axvline(Y0_low[D_low == 1].mean(), color=\"tab:orange\", linestyle=\"--\")\nplt.xlabel(\"savings with no 401(k), Y(0)\")\nplt.ylabel(\"density\")\nplt.title(\"With no 401(k) for anyone, the eligible group would still save more\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_04_prediction_to_treatment_effects_files/figure-ipynb/cell-10-output-1.png){}\n:::\n:::\n\n\nBoth curves are drawn in a world where no household has a 401(k), so neither is affected by the treatment. They still do not line up: the eligible households, the orange histogram, sit to the right and would have saved more regardless, because the same covariates that make them likely to be eligible also make them savers (better job, higher propensity to save, age, etc). That gap, with the treatment removed entirely, is the selection bias. The naive comparison cannot separate it from the effect so it includes it.\n\n### 2.2 Unconfoundedness\n\nThis is the most key assumption in this whole stream, so we will explore it in detail. The reason the naive comparison fails is that eligibility was decided in a way that depends on $X$, and $X$ also drives savings. Suppose instead we could find, for every eligible household, an ineligible household identical on $X$: same income, age, education, family size, everything we measured. Within such a pair, the only systematic difference left is eligibility, so comparing them recovers an effect. This is **unconfoundedness** (also called selection on observables or conditional independence):\n\n$$\n\\big(Y(0), Y(1)\\big) \\;\\perp\\; D \\;\\mid\\; X.\n$$\n\nThe $\\;\\perp\\;$ symbol means independent. \n\nIn words: once we hold $X$ fixed, which household is eligible is as good as random. For our data it says that among households that match on everything we measured, whether one of them has a job that offers a 401(k) tells us nothing more about how much it would have saved on its own. It would fail if households differ in some way the survey never recorded, for example a propensity for saving, that both steers them into eligible jobs and pushes up their savings. Then eligible and ineligible households still differ after we condition on $X$, and no adjustment on $X$ can repair it. \n\nThere is a companion requirement called **overlap** or **positivity**: at every value of $X$ there must be both eligible and ineligible households, or there is no comparison to make. Together they let us write the ATE as an average of within-$X$ comparisons:\n\n$$\n\\text{ATE} = \\mathbb{E}_X\\Big[\\, \\mathbb{E}[Y \\mid D=1, X] - \\mathbb{E}[Y \\mid D=0, X] \\,\\Big].\n$$\n\n::: {.callout-important}\n## Unconfoundedness is an assumption, not a result\n\nNothing in the data can confirm $(Y(0), Y(1)) \\perp D \\mid X$, because it involves the potential outcomes we never observe. We assume that the covariates we collected capture every systematic reason a household ends up eligible, we adjust for $X$ on that basis, and we know that the whole estimate rests on the assumption.\n:::\n\nIn our simulated world unconfoundedness holds by construction, because we built $D$ to depend only on the $X$ we recorded, so we can watch the assumption do its work. We sort the households into ten groups by how likely they were to be eligible, a single number that summarises $X$, and inside each group we compare the savings of the eligible with the ineligible. Within a narrow group the two sides are alike, so the comparison should be close to the true effect.\n\n::: {#a894338d .cell execution_count=10}\n``` {.python .cell-code}\nstrata = pd.qcut(propensity_low, 10, labels=False, duplicates=\"drop\")\nwithin_stratum = [Y_low[(strata == s) & (D_low == 1)].mean()\n                  - Y_low[(strata == s) & (D_low == 0)].mean()\n                  for s in sorted(set(strata))]\n\nplt.figure(figsize=(9, 5))\nplt.scatter(range(len(within_stratum)), within_stratum, s=70, color=\"tab:green\",\n            zorder=3, label=\"within-group comparison\")\nplt.axhline(TRUE_EFFECT, color=\"black\", linestyle=\"--\", label=f\"true effect = {TRUE_EFFECT:.0f}\")\nplt.axhline(naive_low, color=\"tab:red\", linestyle=\":\", label=f\"pooled naive difference = {naive_low:.2f}\")\nplt.xlabel(\"households grouped from least to most likely to be eligible\")\nplt.ylabel(\"eligible minus ineligible savings, within group\")\nplt.title(\"Compare like with like and the effect is about 1; pool everyone and it balloons to 6.14\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_04_prediction_to_treatment_effects_files/figure-ipynb/cell-11-output-1.png){}\n:::\n:::\n\n\nIn the middle groups the within-group comparison sits close to the true effect of 1, far below the pooled naive difference of 6.14. This is the unconfoundedness assumption working: once we compare households that look alike, the selection bias is gone and what is left is the true effect. The end groups wander upwards, and that is the **overlap** problem showing up. In the lowest group almost no one is eligible and in the highest almost everyone is, so there are too few of the other side to compare against, and the estimate gets noisy. Comparing within groups like this is one way to adjust for $X$. The compact version of this is to put $D$ and $X$ into one linear regression and read the coefficient on $D$.\n\n::: {#79a55c38 .cell execution_count=11}\n``` {.python .cell-code}\nols_adjust = LinearRegression().fit(np.column_stack([D_low, X_low]), Y_low).coef_[0]\nprint(f\"True effect      : {TRUE_EFFECT:.2f}\")\nprint(f\"Naive difference : {naive_low:.2f}\")\nprint(f\"Adjusted for X   : {ols_adjust:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTrue effect      : 1.00\nNaive difference : 6.14\nAdjusted for X   : 1.04\n```\n:::\n:::\n\n\nAdjusting for $X$ brings the estimate from 6.14 back to 1.04, recovering the effect of 1 we built in. The same adjustment changes the 401(k) number too.\n\n::: {#b940a4e7 .cell execution_count=12}\n``` {.python .cell-code}\nadjusted_401k = LinearRegression().fit(\n    np.column_stack([D, savings[confounders].to_numpy()]), Y).coef_[0]\nprint(f\"401(k) naive gap      : {naive_gap:.1f}\")\nprint(f\"401(k) adjusted for X : {adjusted_401k:.1f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n401(k) naive gap      : 19.6\n401(k) adjusted for X : 5.9\n```\n:::\n:::\n\n\nAdjusting cuts the 401(k) gap from about 19,600 to about 5,900 dollars. We cannot check that number against a known truth the way we can in the simulation, and it still rests on unconfoundedness, but it is the comparison we want: eligible against ineligible households that look alike on what we measured.\n\n## 3 The role of machine learning\n\nLook again at the identification formula. To estimate the ATE under unconfoundedness we need $\\mathbb{E}[Y \\mid D, X]$, the expected savings given treatment and covariates. That is a function of $X$, and learning a function of $X$ from data is the prediction problems from Notebooks 1 to 3. A closely related quantity, the **propensity score** $\\mathbb{E}[D \\mid X]$, the probability of being eligible given the covariates, is another prediction problem based around classification. We have learned tools to solve both of these!\n\nThis is how machine learning is used in causal inference. The treatment effect is the target, and the regressions of $Y$ on $X$ and of $D$ on $X$ are **nuisance** functions: functions we have to estimate correctly so the effect comes out right, but that are not themselves the answer. In section 2 the nuisance was simple enough for OLS. When there are many covariates or the relationships are nonlinear, OLS is the wrong tool, for the reasons Notebook 2 laid out, and instead we utilize lasso, a forest, or boosting. \n\nIt would seem we're done: estimate $\\mathbb{E}[Y \\mid D, X]$ with the best predictor we have and read off the effect. But that doesn't work, so let's find out why.\n\n### 3.1 The catch: machine learning used naively gives a biased effect\n\nWe move to a world with many covariates and stronger confounding, the setting where a flexible learner is the only option and where issues start to arise. Here there are 150 covariates and 300 households, the high-dimensional situation from Notebook 2, so OLS breaks and we use lasso for the adjustment.\n\nThe naive way to use it mirrors section 2.2: put $D$ and all of $X$ into one lasso and read the coefficient on $D$.\n\n::: {#36ed2a9d .cell execution_count=13}\n``` {.python .cell-code}\nX_high, D_high, Y_high, *_ = simulate(n=300, p=150, confounding=4.0, seed=RANDOM_STATE)\n\nnaive_high = Y_high[D_high == 1].mean() - Y_high[D_high == 0].mean()\n\ndesign = np.column_stack([D_high, X_high])\nnaive_lasso = LassoCV(cv=5, random_state=RANDOM_STATE, max_iter=50000).fit(design, Y_high).coef_[0]\n\nprint(f\"True effect        : {TRUE_EFFECT:.2f}\")\nprint(f\"Naive difference   : {naive_high:.2f}\")\nprint(f\"Naive single lasso : {naive_lasso:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTrue effect        : 1.00\nNaive difference   : 6.88\nNaive single lasso : 0.75\n```\n:::\n:::\n\n\nThe naive difference is a terrible estimator at 6.88. The single lasso is closer, but 0.75 is well below our true effect of 1. The lasso penalty shrinks every coefficient toward zero to control variance, and it shrinks the coefficient on $D$ along with the rest, even though that is the one coefficient we don't want shrunk (it is the target). This is **regularization bias**, the warning Notebook 2 ended on: a lasso-selected coefficient is not a clean effect.\n\nThe fix is to stop asking a single penalized regression to find the effect. Instead we use machine learning only for the nuisance functions ($Y$ on $X$ and $D$ on $X$) and keep the effect itself out of the penalty. This is **orthogonalization**, the same idea as adjusting for $X$ in section 2.2, now done on each side individually. We partial $X$ out of the outcome and out of the treatment, each with its own lasso, and then relate what is left over:\n\n1. Predict $Y$ from $X$ and take the residual $\\tilde{Y} = Y - \\hat{\\mathbb{E}}[Y \\mid X]$: the part of savings the covariates do not explain.\n2. Predict $D$ from $X$ and take the residual $\\tilde{D} = D - \\hat{\\mathbb{E}}[D \\mid X]$: the part of eligibility the covariates do not explain.\n3. Regress $\\tilde{Y}$ on $\\tilde{D}$. That slope is the effect.\n\nThe final step is an ordinary unpenalized regression of one residual on the other, so the penalty never touches the effect.\n\n::: {#5b83d9fe .cell execution_count=14}\n``` {.python .cell-code}\ny_resid = Y_high - LassoCV(cv=5, random_state=RANDOM_STATE, max_iter=50000).fit(X_high, Y_high).predict(X_high)\nd_resid = D_high - LassoCV(cv=5, random_state=RANDOM_STATE, max_iter=50000).fit(X_high, D_high).predict(X_high)\northogonal = (d_resid @ y_resid) / (d_resid @ d_resid)\n\nprint(f\"True effect        : {TRUE_EFFECT:.2f}\")\nprint(f\"Naive single lasso : {naive_lasso:.2f}\")\nprint(f\"Orthogonalized     : {orthogonal:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTrue effect        : 1.00\nNaive single lasso : 0.75\nOrthogonalized     : 1.07\n```\n:::\n:::\n\n\nWe can look at that final regression directly. Each point below is one household, placed by how much of its eligibility and its savings are left unexplained by $X$. The slope of the line through them is the effect.\n\n::: {#faf8842c .cell execution_count=15}\n``` {.python .cell-code}\nplt.figure(figsize=(8, 5))\nplt.scatter(d_resid, y_resid, s=12, alpha=0.4, color=\"grey\")\ngrid = np.array([d_resid.min(), d_resid.max()])\nplt.plot(grid, orthogonal * grid, color=\"tab:green\", linewidth=2,\n         label=f\"slope = {orthogonal:.2f}\")\nplt.xlabel(\"treatment residual (eligibility with X partialled out)\")\nplt.ylabel(\"outcome residual (savings with X partialled out)\")\nplt.title(\"With X partialled out of both, the leftover slope is the effect\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_04_prediction_to_treatment_effects_files/figure-ipynb/cell-16-output-1.png){}\n:::\n:::\n\n\nOnce $X$ is removed from both eligibility and savings, the part left over lines up along a slope of 1.07, which is very close to the effect of 1 we constructed. Let's compare all three estimates we used.\n\n::: {#eae3f167 .cell execution_count=16}\n``` {.python .cell-code}\nplt.figure(figsize=(8, 5))\nplt.bar([\"naive\\ndifference\", \"naive\\nsingle lasso\", \"orthogonalized\"],\n        [naive_high, naive_lasso, orthogonal],\n        color=[\"tab:red\", \"tab:orange\", \"tab:green\"])\nplt.axhline(TRUE_EFFECT, color=\"black\", linestyle=\"--\", label=f\"true effect = {TRUE_EFFECT:.0f}\")\nplt.ylabel(\"estimated effect of eligibility\")\nplt.title(\"Only orthogonalization recovers the effect we built in\")\nplt.legend()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](notebook_04_prediction_to_treatment_effects_files/figure-ipynb/cell-17-output-1.png){}\n:::\n:::\n\n\nWe can still improve upon this! There is a second, subtler bias we have not removed: we fit the nuisance lassos and computed the effect on the same households, so the residuals carry a little of the lassos' own overfitting. The way we fix this is using **cross-fitting**: split the data, fit the nuisances on one part, take residuals on the other, and rotate, this is similar to cross-validation in Notebook 1. Orthogonalization plus cross-fitting is **double machine learning**, the subject of Notebook 7, where we build the estimator in full and attach standard errors to it.\n\n::: {.callout-tip}\n## Self-test\n\nWe adjusted for $X$ with OLS in section 2.2 and it worked. Why not just always use OLS and avoid the regularization bias entirely?\n\n<details><summary>Show / hide answer</summary>\nBecause OLS only works when the covariates are few relative to the sample, like section 2.2. With many covariates, our setting in section 3.1 and in Notebook 2, OLS overfits and falls apart, so we have to use a regularized or flexible learner for the nuisance. Regularization is necessary, and orthogonalization is what removes the bias.\n</details>\n:::\n\n### 3.2 When unconfoundedness fails\n\nEverything above rests on unconfoundedness: the covariates we adjusted for capture every systematic reason a household is eligible. But let's suppose they do not. Suppose the most important confounder is something we never measured. We can see what that does by taking our low-dimensional world and adjusting for every covariate except the most important one, as if it had been left out of the survey.\n\n::: {#b87aaa3e .cell execution_count=17}\n``` {.python .cell-code}\nols_hidden = LinearRegression().fit(np.column_stack([D_low, X_low[:, 1:]]), Y_low).coef_[0]\nprint(f\"True effect             : {TRUE_EFFECT:.2f}\")\nprint(f\"Adjusted for all X      : {ols_adjust:.2f}\")\nprint(f\"Adjusted, top X hidden  : {ols_hidden:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTrue effect             : 1.00\nAdjusted for all X      : 1.04\nAdjusted, top X hidden  : 5.87\n```\n:::\n:::\n\n\nWith the strongest confounder hidden, the adjusted estimate jumps from 1 to 5.87, almost as biased as the naive difference. No amount of technique with the covariates we do have can fix a confounder we don't have. Orthogonalization, cross-fitting, a stronger learner, none of them helps here, because what we are missing is information rather than a better method.\n\nThis is where the tools you met in COMET come back. When unconfoundedness is too much to assume, we look for a different source of variation. **Instrumental variables** uses a variable that shifts the treatment but affects the outcome only through it. **Difference-in-differences** uses the timing of a treatment together with a parallel-trends assumption. These are different identification strategies, each resting on its own assumption rather than on adjusting for $X$, and machine learning extends them too. Picking between adjusting for $X$, an instrument, or a difference-in-differences design really comes down to which assumption you are willing to defend.\n\n::: {.callout-note}\n## Its causal future\n\nFrom here the stream builds out the toolkit this notebook set up. Notebook 5 fixes the regularization bias for lasso specifically, with post-double-selection. Notebook 6 estimates the propensity score $\\mathbb{E}[D \\mid X]$ and uses it to reweight. Notebook 7 builds double machine learning, the orthogonalization and cross-fitting of section 3.1, in full. Notebook 8 moves from the average effect to who benefits most, with causal forests. Each one is a prediction tool from Notebooks 1 to 3, but now in its proper causal clothing. \n:::\n\n## Connections\n\n- **Back to Notebook 3:** Notebook 3 finished the prediction toolkit with trees, forests and boosting. \n- **Forward to Notebook 5:** post-double-selection lasso, the proper fix for the regularization bias of section 3.1, on the growth and convergence question from Notebook 2.\n\n### References\n\n- Belloni, A., Chernozhukov, V., & Hansen, C. (2014). *High-dimensional methods and inference on structural and treatment effects.* Journal of Economic Perspectives, 28(2), 29-50. Regularization bias and the double-selection fix.\n- CausalWizard. (n.d.). *Average treatment effect (ATE).* CausalWizard. https://causalwizard.app/inference/article/ate\n- Chernozhukov, V., Chetverikov, D., Demirer, M., Duflo, E., Hansen, C., Newey, W., & Robins, J. (2018). *Double/debiased machine learning for treatment and structural parameters.* Econometrics Journal, 21(1), C1-C68. Orthogonalization and cross-fitting.\n- Didelez, V., & Evans, R. J. (2025). *Causal assumptions.* In *Causal Inference* (APTS lecture notes), University of Oxford. https://www.stats.ox.ac.uk/~evans/APTS/causassmp.html\n- GeeksforGeeks. (2026). *Causal machine learning.* GeeksforGeeks. https://www.geeksforgeeks.org/machine-learning/causal-machine-learning/\n- Imbens, G. W., & Rubin, D. B. (2015). *Causal Inference for Statistics, Social, and Biomedical Sciences.* Cambridge University Press. The potential-outcomes framework.\n- Poterba, J. M., Venti, S. F., & Wise, D. A. (1995). *Do 401(k) contributions crowd out other personal saving?* Journal of Public Economics, 58(1), 1-32. The eligibility question.\n- Wikipedia contributors. (2026). *Ignorability.* Wikipedia. https://en.wikipedia.org/wiki/Ignorability\n\n---\n\n---\njupyter:\n  kernelspec:\n    display_name: Python 3 (ipykernel)\n    language: python\n    name: python3\n    path: 'D:\\Users\\alexr\\anaconda3\\share\\jupyter\\kernels\\python3'\n  language_info:\n    codemirror_mode:\n      name: ipython\n      version: 3\n    file_extension: .py\n    mimetype: text/x-python\n    name: python\n    nbconvert_exporter: python\n    pygments_lexer: ipython3\n    version: 3.13.5\n---\n",
    "supporting": [
      "notebook_04_prediction_to_treatment_effects_files\\figure-ipynb"
    ],
    "filters": []
  }
}