{
  "hash": "09358d2b12db8a2e4b73efd665efd2f9",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Network Analysis: CBDB Dataset\"\nauthor: prAxIs UBC Team <br> _Alex Ronczewski_\ndate: '2025-10-13'\nimage: media/degree_centrality.png\ndescription: Using Network Analysis to Analyze The China Biographical Dataset\ncategories:\n  - Python\n  - network analysis\n  - SOCI 415\nexecute:\n  eval: true\n  echo: true\n  output: true\nformat:\n  html:\n    code-fold: true\n    code-summary: \"Show the code\"\n    embed-resources: true\n    self-contained-math: true\n  ipynb:\n    jupyter:\n      kernelspec:\n        display_name: Python\n        language: python3\n        name: python3\n---\n\n\n# 0.0 Prerequisites \n\n* SOCI 415 Network Analysis Intro Notebook\n* Kinmatrix Dataset Notebook\n\nThe China Biographical Database is a freely accessible relational database with biographical information about approximately **641,568 individuals** as of August 2024, currently mainly from the 7th through 19th centuries. It was developed as a collaborative project between scholars at Harvard University, Academia Sinica, and Peking University. The data is useful for statistical, social network, and spatial analysis as well as serving as a biographical reference for Chinese History. It enables quantitative exploration of real Chinese history. \n\nThe CBDB dataset is considerably more extensive and complex than the KINMATRIX dataset from the previous notebook. The KINMATRIX dataset we used previously contained ego-centric networks: networks centered around specific individuals showing their personal connections. CBDB represents a sociocentric network: a complete network showing connections among all members of a social system. \n\nThis change allows for more complex and realistic studies of network structure like community detection, and macro-social patterns. If you wish to read more about the structure of the dataset you can follow the link [Structure of CBDB](https://projects.iq.harvard.edu/cbdb/structure-cbdb). This dataset will be ideal for more realistic family network exploration.  \n\n**Learning Objectives:** In this notebook students will learn about:\n\n* Gain an increased understanding of general network analysis in Python and how to manipulate data\n* Apply community detection algorithms to identify subgroups in historical networks\n* Calculate and interpret multiple centrality measures to identify influential historical figures\n* Analyze gender differences in network positions using statistical methods\n* Examine temporal changes in network structure across Chinese dynasties\n* Connect network analysis findings to broader sociological theories about social structure and power\n\n# 1.0 Data Loading and Intro\n\nAs with all of our notebooks so far we will begin with loading all of our libraries. This library list is similar to the one used in the KINMATRIX data analysis. \n\n::: {#e829e445 .cell execution_count=1}\n``` {.python .cell-code}\n#Libraries listed below\nimport sqlite3\nimport pandas as pd\nimport networkx as nx #Our Python network analysis library\nimport matplotlib.pyplot as plt\nimport matplotlib.patches as mpatches\nimport matplotlib.cm as cm\nimport random\nfrom community import community_louvain\nimport numpy as np\nfrom collections import Counter\nfrom pyvis.network import Network\nfrom scipy import stats\nimport seaborn as sns\nfrom collections import OrderedDict\nfrom tabulate import tabulate\n```\n:::\n\n\nNow that we have all of the libraries loaded in for our analysis we can load our data. The dataset is a .db file; it is a database. The CBDB data is extensive and has lots of variables within it, in order to access them we have to choose a table from our .db file. A table is a structured collection of data organized in rows and columns, similar to a spreadsheet. Each table contains records (rows), and every record has fields (columns). This is different from the KINMATRIX dataset which used a .dta file. The main difference students should be aware of is that we will have to select the table before selecting the variables. In the KINMATRIX data we could just list all variables from the start. For .db files there is one more step. \n\nDisplay all of the tables in the dataset .db file. \n\n::: {#c4d4b76a .cell execution_count=2}\n``` {.python .cell-code}\ndb_path = r'datasets\\latest.db' #path\nconn = sqlite3.connect(db_path)\ncursor = conn.cursor()\n\n# List all tables\ncursor.execute(\"SELECT name FROM sqlite_master WHERE type='table';\")\ntables = cursor.fetchall()\n\nprint(\"Tables in database:\", tables)\n\nconn.close()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nTables in database: [('ADDR_BELONGS_DATA',), ('ADDR_CODES',), ('ADDR_PLACE_DATA',), ('ADDR_XY',), ('ADDRESSES',), ('ALTNAME_CODES',), ('ALTNAME_DATA',), ('APPOINTMENT_CODE_TYPE_REL',), ('APPOINTMENT_CODES',), ('APPOINTMENT_TYPES',), ('ASSOC_CODE_TYPE_REL',), ('ASSOC_CODES',), ('ASSOC_DATA',), ('ASSOC_TYPES',), ('ASSUME_OFFICE_CODES',), ('BIOG_ADDR_CODES',), ('BIOG_ADDR_DATA',), ('BIOG_INST_CODES',), ('BIOG_INST_DATA',), ('BIOG_MAIN',), ('BIOG_SOURCE_DATA',), ('BIOG_TEXT_DATA',), ('CHORONYM_CODES',), ('Copy Of CopyTables',), ('CopyMissingTables',), ('CopyTables',), ('CopyTablesDefault',), ('COUNTRY_CODES',), ('DATABASE_LINK_CODES',), ('DATABASE_LINK_DATA',), ('DYNASTIES',), ('ENTRY_CODE_TYPE_REL',), ('ENTRY_CODES',), ('ENTRY_DATA',), ('ENTRY_TYPES',), ('ETHNICITY_TRIBE_CODES',), ('EVENT_CODES',), ('EVENTS_ADDR',), ('EVENTS_DATA',), ('EXTANT_CODES',), ('ForeignKeys',), ('FormLabels',), ('GANZHI_CODES',), ('HOUSEHOLD_STATUS_CODES',), ('INDEXYEAR_TYPE_CODES',), ('KIN_DATA',), ('KIN_Mourning',), ('KIN_MOURNING_STEPS',), ('KINSHIP_CODES',), ('LITERARYGENRE_CODES',), ('MEASURE_CODES',), ('NIAN_HAO',), ('OCCASION_CODES',), ('OFFICE_CATEGORIES',), ('OFFICE_CODE_TYPE_REL',), ('OFFICE_CODES',), ('OFFICE_CODES_CONVERSION',), ('OFFICE_TYPE_TREE',), ('OFFICE_TYPE_TREE_backup',), ('PARENTAL_STATUS_CODES',), ('PLACE_CODES',), ('POSSESSION_ACT_CODES',), ('POSSESSION_ADDR',), ('POSSESSION_DATA',), ('POSTED_TO_ADDR_DATA',), ('POSTED_TO_OFFICE_DATA',), ('POSTING_DATA',), ('SCHOLARLYTOPIC_CODES',), ('SOCIAL_INSTITUTION_ADDR',), ('SOCIAL_INSTITUTION_ADDR_TYPES',), ('SOCIAL_INSTITUTION_ALTNAME_CODES',), ('SOCIAL_INSTITUTION_ALTNAME_DATA',), ('SOCIAL_INSTITUTION_CODES',), ('SOCIAL_INSTITUTION_CODES_CONVERSION',), ('SOCIAL_INSTITUTION_NAME_CODES',), ('SOCIAL_INSTITUTION_TYPES',), ('STATUS_CODE_TYPE_REL',), ('STATUS_CODES',), ('STATUS_DATA',), ('STATUS_TYPES',), ('TablesFields',), ('TablesFieldsChanges',), ('TEXT_BIBLCAT_CODE_TYPE_REL',), ('TEXT_BIBLCAT_CODES',), ('TEXT_BIBLCAT_TYPES',), ('TEXT_CODES',), ('TEXT_INSTANCE_DATA',), ('TEXT_ROLE_CODES',), ('TEXT_TYPE',), ('TMP_INDEX_YEAR',), ('YEAR_RANGE_CODES',)]\n```\n:::\n:::\n\n\nThe output of the cell above is a list of all of the tables in the dataset and we can see that the list is extensive. The one we are most interested in is called KIN_DATA. Inside of this table we have information on node (Person ID), and edges (Kin Code). These variables will serve as the foundation for our analysis. We will now load the table. The output of this cell will be all of the variables within the table 'KIN_DATA.'\n\n::: {#3208cdfc .cell execution_count=3}\n``` {.python .cell-code}\n# Connect to the database\nconn = sqlite3.connect(db_path)\n\ndf = pd.read_sql_query(\"SELECT * FROM KIN_DATA\", conn)\n\n# Show the first few rows\nprint(df.head())\n\nconn.close()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   c_personid  c_kin_id  c_kin_code  c_source        c_pages  \\\n0           0    689344         337   64847.0  088  周真夫人黃氏墓誌   \n1           1         2         180       0.0           None   \n2           1     13310         210    7596.0           3047   \n3           1     13311         180       0.0           None   \n4           1    119997         182    2229.0           None   \n\n                  c_notes c_autogen_notes c_created_by c_created_date  \\\n0                    None            None   Qi Xinghai       20250329   \n1  [待考。《宋史·安惇傳》云，惇二子郊、邦。]            None          TTS       20070312   \n2                    None            None          TTS       20070312   \n3                    None            None          TTS       20070312   \n4      據宋史列傳CBDB宋史分傳#2159            None         load       20121116   \n\n  c_modified_by c_modified_date  \n0    Qi Xinghai        20250329  \n1          None            None  \n2          None            None  \n3          None            None  \n4          None            None  \n```\n:::\n:::\n\n\nWe can see from the output that the table contains both English and Chinese variables so we will have to be careful to select the English language variables. We have now loaded the correct data and just like with the KINMATRIX Dataset we will build a NetworkX Graph and print the number of nodes and edges. Using the Person ID and Kin ID variables we will create a graph with nodes and edges. \n\n::: {#bdeedbb1 .cell execution_count=4}\n``` {.python .cell-code}\n# Create an empty graph\nG = nx.Graph()\n\n# Add edges with kinship type as edge attribute\nfor _, row in df.iterrows():\n    person = row['c_personid']\n    kin = row['c_kin_id']\n    kin_type = row['c_kin_code']\n    G.add_edge(person, kin, kinship=kin_type)\n\nprint(f\"Number of nodes: {G.number_of_nodes()}\")\nprint(f\"Number of edges: {G.number_of_edges()}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nNumber of nodes: 278262\nNumber of edges: 272717\n```\n:::\n:::\n\n\nWe have over 278,000 nodes and a similar amount of edges. This is a far bigger dataset than we have previously used. This is a very extensive dataset where one of these networks is larger than all of the networks for the KINMATRIX Dataset. \n\n::: {.callout-note}\nThe size of the network presents us with both amazing opportunities and challenges. We can study macro-level patterns impossible to see in smaller networks, but we must be very careful when choosing analytical methods to not run into computational problems. Because of this we will not be able to visualize this full network, later in the notebook we will find a way to visualize smaller subsets analogous to countries and regions in the KINMATRIX Dataset. \n:::\n\n# 2.0 Louvain and Community Clusters\n\nThe first thing we will do for our analysis is look for are smaller sub-groups. This is analysis we could not do for the KINMATRIX Dataset as it was an ego-centric network. This is very popular technique in network analysis as it helps uncover hidden group structure in very expansive and complex networks. Sociologists have long recognized that large social systems organize into meaningful subgroups and being familiar with this analysis is a major benefit. The reasons for this clustering is often less apparent and knowledge of the data or in this case Chinese History is necessary. Reasons for clustering can range from geographical (remote communities behind natural barriers), temporal (individuals from the same time period or dynasty), status/social rank or in the case of UBC students similar interests (clubs) or majors. \n\nIn our case large networks (like the CBDB) can be overwhelming and computationally intensive to study. Unlike the KINMATRIX dataset where the data was naturally divided into countries and provinces there are far less clear subgroups in this dataset. By identifying clusters, sociologists can summarize, visualize, and understand the major subgroups and their relationships, making the network more interpretable. To perform this community analysis we will need to introduce some more terminology.    \n\n**Cohesive subgroups** in network analysis refer to clusters of nodes within a network that are more *densely connected to each other than to the rest of the network*. These subgroups indicate areas of high interaction or strong relationships within the larger network. Identifying cohesive subgroups helps in understanding the structure and dynamics of the network, such as how information or influence flows within and between these groups. The process of finding cohesive subgroups within networks is called **cohesive group analysis**.\n\nA **clique** is a subset of nodes within a graph where every node is directly connected to every other node in the subset. This means that in a clique, all possible edges between the nodes are present, making it a maximally connected subgraph. All nodes are that are by themselves are inherently a clique (a 1-clique). While cliques represent perfect connection (everyone connected to everyone), real social groups rarely achieve this ideal.\n\nLet's see what this looks like on an example network before moving towards our real data. \n\n::: {#7c1b4cf6 .cell execution_count=5}\n``` {.python .cell-code}\n#Create our network\nG_cliques_example = nx.Graph()\nedges_list = [(0,1),(0,2),(0,3),(0,4),(1,2),(2,3),(3,4),(1,4),(2,4),(1,3),(4,5),(5,6)]\nG_cliques_example.add_edges_from(edges_list)\npos = nx.spring_layout(G_cliques_example, seed=1000)\n\n#Find our cliques and print where they are\ncliques = [x for x in nx.find_cliques(G_cliques_example)]\nprint(cliques)\n\n#Draw our graph      \nnx.draw(G_cliques_example,pos=pos, with_labels=True, edgecolors=\"black\", node_color = \"bisque\", node_size=800)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[4, 0, 1, 2, 3], [4, 5], [6, 5]]\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](cbdb_dataset_files/figure-html/cell-6-output-2.png){width=691 height=499}\n:::\n:::\n\n\nWe can see that there are three cliques in this network: $(4, 0, 1, 2, 3)$, $(4, 5)$, and $(6, 5)$:\n\nWe can colour them green to be more easily identifiable. \n\n::: {#d05c0507 .cell execution_count=6}\n``` {.python .cell-code}\n#Set the figure size\nfig, axes = plt.subplots(3, 1, figsize=(8, 18))\nfig.set_facecolor('lightblue')\n\n#Create our network\nG_cliques_example = nx.Graph()\nedges_list = [(0,1),(0,2),(0,3),(0,4),(1,2),(2,3),(3,4),(1,4),(2,4),(1,3),(4,5),(5,6)]\nG_cliques_example.add_edges_from(edges_list)\npos = nx.spring_layout(G_cliques_example, seed=1000)\n\n#Find our cliques and print them\ncliques = [x for x in nx.find_cliques(G_cliques_example)]\nprint(cliques)\n\n#Colour our cliques\nclique_1 = [\"mediumseagreen\", \"mediumseagreen\", \"mediumseagreen\", \"mediumseagreen\", \"mediumseagreen\", \"bisque\", \"bisque\"]\nclique_2 = [\"bisque\", \"bisque\", \"bisque\",  \"bisque\", \"mediumseagreen\", \"mediumseagreen\", \"bisque\"]\nclique_3 = [\"bisque\", \"bisque\", \"bisque\", \"bisque\",  \"bisque\", \"mediumseagreen\", \"mediumseagreen\"]\n\n#Draw our cliques       \nnx.draw(G_cliques_example, ax=axes[0], pos=pos, with_labels=True, edgecolors=\"black\", node_color = clique_1, node_size=800)\nnx.draw(G_cliques_example, ax=axes[1], pos=pos, with_labels=True, edgecolors=\"black\", node_color = clique_2, node_size=800)\nnx.draw(G_cliques_example, ax=axes[2], pos=pos, with_labels=True, edgecolors=\"black\", node_color = clique_3, node_size=800)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[4, 0, 1, 2, 3], [4, 5], [6, 5]]\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](cbdb_dataset_files/figure-html/cell-7-output-2.png){width=614 height=1350}\n:::\n:::\n\n\nIt is also important to note that nodes can also be in multiple cliques. Just like in real life you can be in multiple social groups or clubs. It might be of interest to see which nodes are in the most cliques and we will do this by coloring our node with different shades of green. \n\n::: {#b2fb3da0 .cell execution_count=7}\n``` {.python .cell-code}\n#Create our example graph\nG_cliques_example = nx.Graph()\nedges_list = [(0,1),(0,2),(0,3),(0,4),(1,2),(2,3),(3,4),(1,4),(2,4),(1,3),(4,5),(5,6)]\nG_cliques_example.add_edges_from(edges_list)\npos = nx.spring_layout(G_cliques_example, seed=1000)\n\n#Find the cliques\ncliques = [x for x in nx.find_cliques(G_cliques_example)]\nprint(cliques)\n\n#For loop\nnode_counts = {}\nfor clique in cliques: #for each clique in the list of cliques...\n    for node in clique: # for each node in each clique...\n        if node in node_counts: #checks whether the current node already exists as a key in the node_counts dictionary\n            node_counts[node] += 1 #if it is in the dictionary, increase its value by 1\n        else:\n            node_counts[node] = 1 #if it isn't, dont change\n\n#Colour our nodes\ncolors = []\nfor node in G_cliques_example.nodes():\n    if node_counts[node] == 1:\n        colors.append(\"lightgreen\")\n    elif node_counts[node] == 2:\n        colors.append(\"forestgreen\")\n    elif node_counts[node] == 3:\n        colors.append(\"orange\")\n    else:\n        colors.append(\"red\")\n\n#Draw our network           \nnx.draw(G_cliques_example,pos=pos, with_labels=True, edgecolors=\"black\", node_color = colors, node_size=800)\npatch_green = mpatches.Patch(color='lightgreen', label='node in one clique') \npatch_forest = mpatches.Patch(color='forestgreen', label='node in two cliques') \nplt.legend(handles=[patch_green, patch_forest])\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[[4, 0, 1, 2, 3], [4, 5], [6, 5]]\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](cbdb_dataset_files/figure-html/cell-8-output-2.png){width=691 height=499}\n:::\n:::\n\n\n## 2.1 Network-level analysis: Clusters and clustering coefficients\n\nA **cluster** (also known as a community) is a set of nodes in a graph that are densely connected to each other but sparsely connected to nodes in other clusters. For example, in a social network, a cluster might represent a group of people who frequently interact with each other but have fewer interactions with people outside the group. **Community detection** is the process of finding such communities within nodes. \n\nBefore diving into community detection, we first need to understand modularity. **Modularity** is a numerical measure for the community structure of a graph: it compares the density of edges within the communities of a network to the density of edges between communities. A positive modularity value suggests a strong community structure, while values closer to zero or negative indicate that the divisions are no better than random.\n\nThe Louvain algorithm is a community detection method in networks that aims to optimize modularity. By optimizing modularity, the Louvain algorithm effectively uncovers natural divisions in the network where connections are dense within clusters and sparse between them, thus identifying meaningful community structures. This algorithm mimics how social groups might naturally form and dissolve over time.\n\nA less technical description of this algorithm's logic:\n\n1. Each node initially forms their own 'community'\n2. People 'join' neighboring communities if it improves overall modularity\n3. Sub-groups that emerged are treated as single nodes\n4. Process repeats until no further improvements possible\n\nThe result is a final set of communities that maximize modularity in the network. \n\n::: {.callout-note}\nIt is worth knowing that because of the nature of the Louvain Algorithm every time it is run it might lead to slightly different outcomes especially in expansive networks like the CBDB we are using. Variations in the processing order of nodes can lead to different results with each run, it's modularity-optimizing approach can fail to detect small communities or create poorly connected groups.\n:::\n\nLet's first try running the Louvain Algorithm on a random graph to demonstrate how it works before running it on our real data. \n\n::: {#b02f7dbc .cell execution_count=8}\n``` {.python .cell-code}\n#Set the seed so it is reproducible\nrandom.seed(1)\n\nn = 20  # number of nodes\nd = 3   # degree of each node\n\n# Generate the random regular graph\nrr_graph = nx.random_regular_graph(d, n)\n\npartition = community_louvain.best_partition(rr_graph)\npos = nx.spring_layout(rr_graph, seed=42)\nnum_communities = max(partition.values()) + 1\ncmap = cm.get_cmap('viridis', num_communities)\nnx.draw_networkx_nodes(\n    rr_graph, pos, node_size=40, cmap=cmap, node_color=list(partition.values())\n)\nnx.draw_networkx_edges(rr_graph, pos, alpha=0.5)\nplt.show()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nC:\\Users\\alexr\\AppData\\Local\\Temp\\ipykernel_2036\\1466713553.py:13: MatplotlibDeprecationWarning:\n\nThe get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.\n\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](cbdb_dataset_files/figure-html/cell-9-output-2.png){width=540 height=389}\n:::\n:::\n\n\nWe can see by the node coloring that by optimizing modularity the Louvain Algorithm has found smaller subgroups within our random network. Now we can try it on our real data. \n\n##  2.2 Louvain Run on our Real Data\n\nAs with before we will set a random seed so that the analysis is reproducible. We will also print out average community size along with the size of the largest and smallest communities. We will also print the top 10 largest communities and their sizes. \n\nWe will also be working with the largest connected component for this analysis as using the whole network will be too computationally intensive.  \n\n::: {#81d995d1 .cell execution_count=9}\n``` {.python .cell-code}\n#Set a seed for reproducability of our results\nnp.random.seed(1)\n\n# Load kinship data into DataFrame\nconn = sqlite3.connect(db_path)\ndf = pd.read_sql_query(\"SELECT c_personid, c_kin_id, c_kin_code FROM KIN_DATA\", conn)\nconn.close()\n\n# Build the Graph\nG = nx.Graph()\nfor _, row in df.iterrows():\n    person = row['c_personid']\n    kin = row['c_kin_id']\n    kin_type = row['c_kin_code']\n    G.add_edge(person, kin, kinship=kin_type)\n\n# Work with the largest connected component\nlargest_cc = max(nx.connected_components(G), key=len)\nG_sub = G.subgraph(largest_cc).copy()\nprint(f\"Largest connected component nodes: {G_sub.number_of_nodes()}\")\n\n# Run Louvain Community Detection\npartition = community_louvain.best_partition(G_sub)\n\n# Community Analysis Output\nnum_communities = len(set(partition.values()))\nprint(f\"In our data Louvain has detected {num_communities} communities.\")\n\n# Count community sizes\ncommunity_sizes = Counter(partition.values())\nprint(f\"\\nMetrics about Community size:\")\nprint(f\"Average community size: {np.mean(list(community_sizes.values())):.1f}\")\nprint(f\"Largest community: {max(community_sizes.values())} people\")\nprint(f\"Smallest community: {min(community_sizes.values())} people\")\n\n#Show top 10 largest communities\nprint(f\"\\nLargest Communities:\")\nfor i, (comm_id, size) in enumerate(community_sizes.most_common(10)):\n    print(f\"Community {comm_id}: {size:,} people\")\n\n# Calculate modularity\nmodularity = community_louvain.modularity(partition, G_sub)\nprint(f\"\\nModularity Score: {modularity:.4f}\")\nprint(\"(Higher modularity indicates stronger community structure)\")\n\n#Distribution Histogram of Community Size\nfig, ax = plt.subplots(figsize=(8, 6))\nfig.suptitle('CBDB Kinship Network Community Analysis', fontsize=16, fontweight='bold')\n\n# Community size histogram\nax.hist(list(community_sizes.values()), bins=30, alpha=0.7, color='skyblue', edgecolor='black')\nax.set_xlabel('Community Size (number of people)')\nax.set_ylabel('Number of Communities')\nax.set_title('Distribution of Community Sizes')\nax.grid(True, alpha=0.3)\n\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLargest connected component nodes: 52992\nIn our data Louvain has detected 188 communities.\n\nMetrics about Community size:\nAverage community size: 281.9\nLargest community: 1256 people\nSmallest community: 19 people\n\nLargest Communities:\nCommunity 46: 1,256 people\nCommunity 124: 995 people\nCommunity 48: 873 people\nCommunity 126: 801 people\nCommunity 4: 682 people\nCommunity 34: 621 people\nCommunity 18: 617 people\nCommunity 145: 606 people\nCommunity 90: 563 people\nCommunity 109: 528 people\n\nModularity Score: 0.9604\n(Higher modularity indicates stronger community structure)\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](cbdb_dataset_files/figure-html/cell-10-output-2.png){width=758 height=569}\n:::\n:::\n\n\nFrom the visualization we can see most communities are around 200 - 400 nodes in size. \n\nLet's look at two of these communities in more detail, we will look at one average sized one and one large one. We can compare these communities to the ones in the KINMATRIX Dataset. Pay attention and look for differences. \n\nThe two we will use are: \n\n* Community 20: 703 nodes with 940 edges\n* Community 125: 308 nodes with 392 edges\n\n::: {#a5684a2d .cell execution_count=10}\n``` {.python .cell-code}\nnp.random.seed(1)\n\ndef visualize_cbdb_community(G_sub, partition, community_id, max_nodes=1000):\n    community_nodes = [str(node) for node, comm_id in partition.items() if comm_id == community_id]\n    \n    print(f\"Community {community_id}: {len(community_nodes)} people\")\n    \n    # Create subgraph with string node IDs\n    subgraph = G_sub.subgraph([int(node) for node in community_nodes])\n    print(f\"Showing {len(community_nodes)} people, {subgraph.number_of_edges()} relationships\")\n    \n    net = Network(height=\"700px\", width=\"100%\", bgcolor=\"#ffffff\", notebook=True)\n    \n    for node in community_nodes:\n        degree = subgraph.degree[int(node)] \n        size = max(15, min(35, 15 + degree))\n        net.add_node(str(node), \n                     label=str(node), \n                     size=size, \n                     color=\"#3498db\",\n                     title=f\"Person {node}\\nConnections: {degree}\")\n    \n    for u, v, data in subgraph.edges(data=True):\n        net.add_edge(str(u), str(v), color=\"#cccccc\", title=f\"Kinship: {data.get('kinship','family')}\")\n    \n    filename = f\"community_{community_id}.html\"\n    net.show(filename)\n    print(f\"Interactive network: {filename}\")\n\n#Run the function\nvisualize_cbdb_community(G_sub, partition, 20)\nvisualize_cbdb_community(G_sub, partition, 125)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCommunity 20: 267 people\nShowing 267 people, 325 relationships\nWarning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.\ncommunity_20.html\nInteractive network: community_20.html\nCommunity 125: 305 people\nShowing 305 people, 328 relationships\nWarning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.\ncommunity_125.html\nInteractive network: community_125.html\n```\n:::\n:::\n\n\nWe will again use a PyVis visualization, just like with the KINMATRIX Visualizations we can zoom and pan around and hover on the nodes. This time you can also drag the nodes and the surrounding nodes will move like bacteria under a microscope.  \n\n## 2.3 Macro Stats and Dynasties\n\nTo get a better understanding of our communities we will look at some summary statistics. Let's briefly define what these summary statistics will be: \n\n* Diameter: The longest shortest path between any two nodes in the network or component. This is a way to measure how \"wide\" our network is. \n* Average Path Length: The average number of steps along the shortest paths for all possible pairs of nodes in the graph\n* Average Clustering: The likelihood that any two neighbors of a node are also connected to each other. Higher values mean people in the community tend to form \"groups\".\n\nWe will also look at degree centrality, density and number of nodes. These will allow us to quantitatively describe our communities.\n\n::: {#c37a9567 .cell execution_count=11}\n``` {.python .cell-code}\nnp.random.seed(1)\n\ndef macro_stats(G_sub, partition, community_id):\n    nodes = [n for n, c in partition.items() if c == community_id]\n    subg = G_sub.subgraph(nodes)\n    stats = {}\n\n    if nx.is_connected(subg):\n        stats['diameter'] = nx.diameter(subg)\n        stats['avg_path_length'] = nx.average_shortest_path_length(subg)\n    else:\n        # statistics of largest connected component only\n        lcc = subg.subgraph(max(nx.connected_components(subg), key=len))\n        stats['diameter'] = nx.diameter(lcc)\n        stats['avg_path_length'] = nx.average_shortest_path_length(lcc)\n\n    degrees = dict(subg.degree())\n    max_degree = max(degrees.values())\n    n = len(degrees)\n    if n > 1:\n        degree_centralization = sum(max_degree - d for d in degrees.values()) / ((n-1)*(n-2))\n    else:\n        degree_centralization = 0\n    stats['degree_centralization'] = degree_centralization\n    stats['avg_clustering'] = nx.average_clustering(subg)\n    stats['density'] = nx.density(subg)\n    stats['n_nodes'] = n\n    return stats\n\n#Print:\nstats_20 = macro_stats(G_sub, partition, 20)\nstats_125 = macro_stats(G_sub, partition, 125)\n\ncommunity_stats = [\n    ['20'] + [stats_20[k] for k in stats_20],\n    ['125'] + [stats_125[k] for k in stats_125]\n]\n\nheaders = ['Community'] + list(stats_20.keys())\nprint(tabulate(community_stats, headers=headers, tablefmt='fancy_grid', floatfmt=\".6f\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n╒═════════════╤════════════╤═══════════════════╤═════════════════════════╤══════════════════╤═══════════╤═══════════╕\n│   Community │   diameter │   avg_path_length │   degree_centralization │   avg_clustering │   density │   n_nodes │\n╞═════════════╪════════════╪═══════════════════╪═════════════════════════╪══════════════════╪═══════════╪═══════════╡\n│          20 │         30 │         12.191743 │                0.066534 │         0.157428 │  0.009152 │       267 │\n├─────────────┼────────────┼───────────────────┼─────────────────────────┼──────────────────┼───────────┼───────────┤\n│         125 │         40 │         15.132787 │                0.025990 │         0.045946 │  0.007075 │       305 │\n╘═════════════╧════════════╧═══════════════════╧═════════════════════════╧══════════════════╧═══════════╧═══════════╛\n```\n:::\n:::\n\n\nWe now have more quantifiable metrics for our visualizations. Let's continue our analysis with finding which dynasties these communities are primarily from. Every node in this dataset is a real person in Chinese history so it will be very interesting to see who these people are. \n\n::: {#7e836c90 .cell execution_count=12}\n``` {.python .cell-code}\nnp.random.seed(1)\n\n# Community 125\npersonids_125 = [n for n, c in partition.items() if c == 125]\nconn = sqlite3.connect(db_path)\n\nif personids_125:\n    query_125 = f'''\n        SELECT c_personid, c_dy FROM BIOG_MAIN\n        WHERE c_personid IN ({','.join(['?']*len(personids_125))})\n    '''\n    df_dyn_125 = pd.read_sql_query(query_125, conn, params=personids_125)\nelse:\n    df_dyn_125 = pd.DataFrame(columns=['c_personid', 'c_dy'])\n\n# Community 20\npersonids_20 = [n for n, c in partition.items() if c == 20]\n\nif personids_20:\n    query_20 = f'''\n        SELECT c_personid, c_dy FROM BIOG_MAIN\n        WHERE c_personid IN ({','.join(['?']*len(personids_20))})\n    '''\n    df_dyn_20 = pd.read_sql_query(query_20, conn, params=personids_20)\nelse:\n    df_dyn_20 = pd.DataFrame(columns=['c_personid', 'c_dy'])\n\nconn.close()\n\n# Show the most common dynasty codes\nprint(\"Community 125 dominant dynasties:\")\nprint(df_dyn_125['c_dy'].value_counts().head(3))\n\nprint(\"Community 20 dominant dynasties:\")\nprint(df_dyn_20['c_dy'].value_counts().head(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCommunity 125 dominant dynasties:\nSeries([], Name: count, dtype: int64)\nCommunity 20 dominant dynasties:\nSeries([], Name: count, dtype: int64)\n```\n:::\n:::\n\n\nWe can see that Community 125 is primarily from Dynasty 6, and Community 20 is primarily from Dynasty 15, but this does not tell us much we need to translate 6 and 15 into real dynasty names. These values represent names of real dynasties, but without the key this output does not mean anything.  \n\nLet's now map these values to real dynasty names. We will do this by looking at the c_dynasty and c_dy variables which represents real dynasty names. \n\n::: {#63890790 .cell execution_count=13}\n``` {.python .cell-code}\nnp.random.seed(1)\n\nconn = sqlite3.connect(db_path)\ndynasty_mapping = pd.read_sql_query('SELECT c_dy, c_dynasty FROM DYNASTIES', conn)\nconn.close()\n\ndef get_dynasty_breakdown(df_dyn, dynasty_mapping):\n    df_merged = df_dyn.merge(dynasty_mapping, on='c_dy', how='left')\n    return df_merged['c_dynasty'].value_counts()  \n\nprint(\"Community 125 top 3 dynasties:\")\nprint(get_dynasty_breakdown(df_dyn_125, dynasty_mapping).head(3))\n\nprint(\"Community 20 top 3 dynasties:\")\nprint(get_dynasty_breakdown(df_dyn_20, dynasty_mapping).head(3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCommunity 125 top 3 dynasties:\nSeries([], Name: count, dtype: int64)\nCommunity 20 top 3 dynasties:\nSeries([], Name: count, dtype: int64)\n```\n:::\n:::\n\n\nNow we know that Community 125 is primarily made up of individuals from the Tang Dynasty and Community 20 is primarily made up of individuals from the Song Dynasty. \n\n## 2.4 Coloring Nodes\n\nLike with the KINMATRIX Dataset we will color our Pyvis visualizations by a variable of interest. In this case we will color Community 125 by gender where male is purple and women are yellow. There are no unknown gender variables in either of these communities so we can just have two colors in our color map.  \n\n::: {#6877ee98 .cell execution_count=14}\n``` {.python .cell-code}\nnp.random.seed(1)\n\n# Get all node and person id's\nall_personids = list(set([n for n in partition.keys()]))\n\nconn = sqlite3.connect(db_path)\nquery = f'''\n    SELECT c_personid, c_female FROM BIOG_MAIN\n    WHERE c_personid IN ({','.join(str(pid) for pid in all_personids)})\n'''\ndf_gender = pd.read_sql_query(query, conn)\nconn.close()\n\n# Function to map female/male from number 1/0\ndef sex_label(val):\n    return 'female' if val == 1 else ('male' if val == 0 else 'unknown')\n\ngender_dict = {row['c_personid']: sex_label(row['c_female']) for _, row in df_gender.iterrows()}\n\ndef visualize_cbdb_community_gender(G_sub, partition, community_id, gender_dict, max_nodes=1000):\n    community_nodes = [str(node) for node, comm_id in partition.items() if comm_id == community_id]\n    print(f\"Community {community_id}: {len(community_nodes)} people\")\n    if len(community_nodes) > max_nodes:\n        print(f\"Sampling {max_nodes} nodes for performance...\")\n        subgraph_full = G_sub.subgraph([int(node) for node in community_nodes])\n        degrees = dict(subgraph_full.degree())\n        sorted_nodes = sorted(community_nodes, key=lambda x: degrees.get(int(x), 0), reverse=True)\n        community_nodes = sorted_nodes[:max_nodes//2] + random.sample(sorted_nodes[max_nodes//2:], max_nodes//2)\n\n    subgraph = G_sub.subgraph([int(node) for node in community_nodes])\n    print(f\"Showing {len(community_nodes)} people, {subgraph.number_of_edges()} relationships\")\n    net = Network(height=\"700px\", width=\"100%\", bgcolor=\"#ffffff\", notebook=True)\n\n    color_map = {'male': '#800080',   # purple\n             'female': '#FFFF00'}  # yellow \n    for node in community_nodes:\n        gender = gender_dict.get(int(node), 'unknown')\n        degree = subgraph.degree[int(node)]\n        size = max(15, min(35, 15 + degree))\n        net.add_node(str(node), \n                     label=str(node),\n                     size=size,\n                     color=color_map.get(gender, '#bdbdbd'),\n                     title=f\"Person {node}\\nConnections: {degree}\\nGender: {gender}\")\n\n    for u, v, data in subgraph.edges(data=True):\n        net.add_edge(str(u), str(v), color=\"#cccccc\", title=f\"Kinship: {data.get('kinship','family')}\")\n    filename = f\"community_{community_id}_gender.html\"\n    net.show(filename)\n    print(f\"Interactive network: {filename}\")\n\nvisualize_cbdb_community_gender(G_sub, partition, 125, gender_dict)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCommunity 125: 305 people\nShowing 305 people, 328 relationships\nWarning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.\ncommunity_125_gender.html\nInteractive network: community_125_gender.html\n```\n:::\n:::\n\n\nWe can see that most of the nodes are male, especially the most central nodes, we will come back to this later, but think about why that is? Continuing on with the notion of centrality lets color the nodes in Community 20 with a color gradient where the nodes with the lowest degree centrality will be blue and the node with the highest will be red. This will serve as an intuitive method to visualize degree centrality.  \n\n::: {#4dd7b3d8 .cell execution_count=15}\n``` {.python .cell-code}\nnp.random.seed(1)\n\ndef visualize_cbdb_community_degree(G_sub, partition, community_id, max_nodes=1000):\n    community_nodes = [str(node) for node, comm_id in partition.items() if comm_id == community_id]\n    print(f\"Community {community_id}: {len(community_nodes)} people\")\n\n    subgraph = G_sub.subgraph([int(node) for node in community_nodes])\n    print(f\"Showing {len(community_nodes)} people, {subgraph.number_of_edges()} relationships\")\n    net = Network(height=\"700px\", width=\"100%\", bgcolor=\"#ffffff\", notebook=True)\n\n    degrees = dict(subgraph.degree())\n    deg_values = [degrees[int(node)] for node in community_nodes]\n    min_deg, max_deg = min(deg_values), max(deg_values)\n    norm = plt.Normalize(min_deg, max_deg)\n    cmap = plt.get_cmap('coolwarm') \n\n    for node in community_nodes:\n        degree = degrees[int(node)]\n        size = max(15, min(35, 15 + degree))\n        rgb_vals = cmap(norm(degree))[:3]\n        hex_color = '#%02x%02x%02x' % tuple(int(x*255) for x in rgb_vals)\n        net.add_node(str(node),\n                     label=str(node),\n                     size=size,\n                     color=hex_color,\n                     title=f\"Person {node}\\nConnections: {degree}\")\n\n    for u, v, data in subgraph.edges(data=True):\n        net.add_edge(str(u), str(v), color=\"#cccccc\", title=f\"Kinship: {data.get('kinship','family')}\")\n    filename = f\"community_{community_id}_degree.html\"\n    net.show(filename)\n    print(f\"Interactive network: {filename}\")\n    print(f\"Color gradient: low degree (blue) to high degree (red).\")\n\nvisualize_cbdb_community_degree(G_sub, partition, 20)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCommunity 20: 267 people\nShowing 267 people, 325 relationships\nWarning: When  cdn_resources is 'local' jupyter notebook has issues displaying graphics on chrome/safari. Use cdn_resources='in_line' or cdn_resources='remote' if you have issues viewing graphics in a notebook.\ncommunity_20_degree.html\nInteractive network: community_20_degree.html\nColor gradient: low degree (blue) to high degree (red).\n```\n:::\n:::\n\n\nThis is a very intuitive way to look at centrality, the most important nodes are yellow, orange and red. They are physically at the center of our network. In the next section we will try to define this centrality more formally.   \n\n## 2.5 Visualization Discussion\n\nIn small groups of 3-4 look at the visualizations from this dataset and compare them to our pyVis visualizations from the KINMATRIX Dataset. Try to be specific and use the terminology introduced in the introductory notebook. How are they similar and how are they different? \n\n# 3.0 Degree Centrality for Important Family Members\n\nWe can see from our community visualization that some members are more central and connect different parts of the family network. In family analysis these would be considered important connectors. In order to examine them further we will use the measures of centrality we introduced in the first notebook. Centrality measures are quantitative metrics that identify the most important or influential nodes within a network, we will do this to try and identify key historical figures and try to reveal hidden connections.  \n\n::: {.callout-warning}\nThe cells below take a very long time to run, so we will leave it all commented and just have the output pasted below. They have to calculate the centrality for over 280,000 nodes individually. \n:::\n\n::: {#2cc9c883 .cell execution_count=16}\n``` {.python .cell-code}\n#print(f\"Analyzing network with {G_sub.number_of_nodes():,} nodes and {G_sub.number_of_edges():,} edges\")\n#degree_centrality = nx.degree_centrality(G_sub)\n#betweenness_centrality = nx.betweenness_centrality(G_sub, k=1000)  \n#closeness_centrality = nx.closeness_centrality(G_sub)\n#eigenvector_centrality = nx.eigenvector_centrality(G_sub, max_iter=1000)\n```\n:::\n\n\nCreate Centrality DataFrame and Display Statistics\n\n::: {#92a9a1da .cell execution_count=17}\n``` {.python .cell-code}\n#Create a comprehensive centrality dataframe\n#centrality_df = pd.DataFrame({\n#    'person_id': list(G_sub.nodes()),\n#    'degree': [G_sub.degree(node) for node in G_sub.nodes()],\n#    'degree_centrality': [degree_centrality[node] for node in G_sub.nodes()],\n#    'betweenness_centrality': [betweenness_centrality[node] for node in G_sub.nodes()],\n#    'closeness_centrality': [closeness_centrality[node] for node in G_sub.nodes#    'eigenvector_centrality': [eigenvector_centrality[node] for node in G_sub.nodes()]\n#})\n#print(\"Centrality Statistics:\")\n#print(centrality_df.describe())\n#print(f\"\\nDataFrame shape: {centrality_df.shape}\")\n#print(f\"Columns: {list(centrality_df.columns)}\")\n```\n:::\n\n\n**Output from above cell:**\n\nCentrality Statistics:\n           person_id        degree  degree_centrality  betweenness_centrality  \ncount   52992.000000  52992.000000       52992.000000            52992.000000   \nmean   115894.558952      2.463353           0.000046                0.000341   \nstd    117167.480510      2.806804           0.000053                0.002023   \nmin         4.000000      1.000000           0.000019                0.000000   \n25%     21419.750000      1.000000           0.000019                0.000000   \n50%    119799.500000      2.000000           0.000038                0.000000   \n75%    178417.250000      3.000000           0.000057                0.000075   \nmax    691363.000000    147.000000           0.002774                0.161482   \n\n       closeness_centrality  eigenvector_centrality  \ncount          52992.000000            5.299200e+04  \nmean               0.054518            2.787520e-04  \nstd                0.010117            4.335138e-03  \nmin                0.024212            1.972009e-17  \n25%                0.047437            3.783786e-12  \n50%                0.054617            3.964649e-10  \n75%                0.061708            4.877353e-08  \nmax                0.085383            5.227996e-01  \n\n\nNow we can look at the most central nodes in the dataset to try and find important individuals in the data. \n\nIn order to find these key individuals we will use our three centrality measures. \n\n* Degree Centrality: Measures how many direct connections a node (person) has. It's the family member with the most immediate kinship ties. \n* Betweenness Centrality: Captures how often a node lies on the shortest path between other nodes. It identifies family members who act as bridges, connecting separate branches or generations.\n* Eigenvector Centrality:  Reflects not just the number of connections, but also the quality-being connected to other well-connected family members. High eigenvector centrality means the person is part of the core, influential family group for instance an emperor or very high ranking official. \n\n::: {#bc0d3403 .cell execution_count=18}\n``` {.python .cell-code}\n#print(\"Degree Centrality (Most Connected Family Members):\")\n#top_degree = centrality_df.nlargest(10, 'degree')\n#for idx, row in top_degree.iterrows():\n#    print(f\"Person {row['person_id']:>8}: {row['degree']:>3} connections (centrality: {row['degree_centrality']:.4f})\")\n\n#print(\"Betweenness Centrality (Best Family Bridges):\")\n#top_betweenness = centrality_df.nlargest(10, 'betweenness_centrality')\n#for idx, row in top_betweenness.iterrows():\n#    print(f\"Person {row['person_id']:>8}: {row['betweenness_centrality']:.4f} (degree: {row['degree']:>3})\")\n\n#print(\"Eigenvector Centrality (Most Influential Family Connections):\")\n#top_eigenvector = centrality_df.nlargest(10, 'eigenvector_centrality')\n#for idx, row in top_eigenvector.iterrows():\n#    print(f\"Person {row['person_id']:>8}: {row['eigenvector_centrality']:.4f} (degree: {row['degree']:>3})\")\n```\n:::\n\n\nOutput:\n**Degree Centrality (Most Connected Family Members):**\nPerson   3211.0: 147.0 connections (centrality: 0.0028)\nPerson  19244.0: 95.0 connections (centrality: 0.0018)\nPerson   9008.0: 80.0 connections (centrality: 0.0015)\nPerson   9002.0: 69.0 connections (centrality: 0.0013)\nPerson  10502.0: 63.0 connections (centrality: 0.0012)\nPerson  13060.0: 61.0 connections (centrality: 0.0012)\nPerson   3214.0: 56.0 connections (centrality: 0.0011)\nPerson  19246.0: 56.0 connections (centrality: 0.0011)\nPerson   9001.0: 53.0 connections (centrality: 0.0010)\nPerson    705.0: 52.0 connections (centrality: 0.0010)\n\n**Betweenness Centrality (Best Family Bridges):**\nPerson  13059.0: 0.1588 (degree: 49.0)\nPerson  13626.0: 0.1217 (degree: 14.0)\nPerson  13060.0: 0.1147 (degree: 61.0)\nPerson   8075.0: 0.1137 (degree: 29.0)\nPerson  17267.0: 0.1092 (degree: 4.0)\nPerson    705.0: 0.0717 (degree: 52.0)\nPerson  95047.0: 0.0713 (degree: 10.0)\nPerson    810.0: 0.0685 (degree: 7.0)\nPerson  19244.0: 0.0609 (degree: 95.0)\nPerson   3211.0: 0.0604 (degree: 147.0)\n\n**Eigenvector Centrality (Most Influential Family Connections):**\nPerson   3211.0: 0.5228 (degree: 147.0)\nPerson   9002.0: 0.2929 (degree: 69.0)\nPerson   9001.0: 0.2602 (degree: 53.0)\nPerson   3198.0: 0.2168 (degree: 28.0)\nPerson  10495.0: 0.1676 (degree: 23.0)\nPerson   9003.0: 0.1582 (degree: 35.0)\nPerson  10530.0: 0.1571 (degree: 15.0)\nPerson  10509.0: 0.1546 (degree: 11.0)\nPerson  15975.0: 0.1437 (degree: 11.0)\nPerson  16805.0: 0.1421 (degree: 19.0)\n\n**Analysis**\n\nLet's look at our three types of centrality from before and use them to order our most important individuals. \n\n* Degree Centrality: These are the family members with the most direct kinship ties.\n* Betweenness Centrality: These family members connect different branches/generations\n* Eigenvector Centrality: These are connected to other highly connected family members\n\nBelow are three graphs plotting our output for most central individuals. \n\n![Degree Centrality](media/degree_centrality.png){ width=80% }\n\n![Betweenness Centrality](media/betweenness_centrality.png){ width=80% }\n\n![Eigenvector Centrality](media/eigenvector_centrality.png){ width=80% }\n\nPerson 3211 emerges as the most connected individual with 147 kinship ties, nearly 50% more than the second-most connected person (Person 19244 with 95 connections). This level of connectivity suggests Person 3211 likely represents either a major family patriarch who lived an exceptionally long life, accumulated multiple marriages and offspring, or potentially a family line that was consolidated under a single record. He will most likely be a very important figure in Chinese History. Person 3211 dominates this measure with a score of 0.5228, more than double the second-highest individual (Person 9002 with 0.2929). This indicates that Person 3211 is not only highly connected but also connected to other highly connected families, representing the apex of elite Chinese society.\n\nEven more striking is Person 17267, who achieves a betweenness centrality of 0.1092 with only 4 direct connections. This individual represents what network analysts call a \"critical bridge\" - someone whose position in the network gives them disproportionate influence over information flow and family interactions. In historical Chinese context, such individuals likely played crucial roles connecting large families like an emperor or emperor's wife.\n\n# 3.1 Discussion on Centrality \n\nUsing our definitions of the three centrality measures we are using:\n\n* Degree Centrality: Measures how many direct connections a node (person) has. It represents the family member with the most immediate kinship ties. \n* Betweenness Centrality: Captures how often a node lies on the shortest path between other nodes. It identifies family members who act as bridges, connecting separate branches or generations.\n* Eigenvector Centrality: Reflects not just the number of connections, but also the quality-being connected to other well-connected family members. High eigenvector centrality means the person is part of the core, influential family group for instance an emperor or very high ranking official. \n\nDiscuss in small groups of 3-4 people how these centrality measures exist in your own family and friendship networks. Think about how all three of these are present in your daily lives. For example do you have a friend who is really popular (high degree centrality), do you have a family member who acts as a link between two large families (high betweenness centrality). Try to link these definitions to real people, this will make the next sections more intuitive.   \n\n# 3.2 Looking at these key individuals\n\nLooking at our top ten list of key individuals we will examine further the most standout ones are: \n\n* Person 3211\n* Person 17267\n\nAnd our most prominent bridges are below, these nodes have high betweenness despite having a lower degree, meaning they’re crucial “gatekeepers” between groups.\n\n* Person 13059\n* Person 13626 \n* Person 8075\n\nLet's find who these people are.\n\n::: {#44fd2ed6 .cell execution_count=19}\n``` {.python .cell-code}\nconn = sqlite3.connect(db_path)\n\n# Key people from the previous network analysis\nkey_people = [3211, 17267, 13059, 13626, 8075]\n\n# Combined query for biography info + native place\nquery = f\"\"\"\nSELECT \n    bm.c_personid,\n    bm.c_name_chn,\n    bm.c_surname_chn,\n    bm.c_name,\n    bm.c_surname,\n    bm.c_birthyear,\n    bm.c_deathyear,\n    bm.c_dy,         -- dynasty code\n    bm.c_female,\n    a.c_name AS NativePlace_CHN\nFROM BIOG_MAIN bm\nLEFT JOIN BIOG_ADDR_DATA bad\n    ON bm.c_personid = bad.c_personid\n    AND bad.c_addr_type = 1\nLEFT JOIN ADDRESSES a\n    ON bad.c_addr_id = a.c_addr_id\nWHERE bm.c_personid IN ({\",\".join(map(str, key_people))})\n\"\"\"\n\ndf = pd.read_sql_query(query, conn)\n\n# Combine name fields into one df\ndf[\"FullName_CHN\"] = df[\"c_surname_chn\"].fillna('') + df[\"c_name_chn\"].fillna('')\ndf[\"FullName_ENG\"] = (df[\"c_surname\"].fillna('') + \" \" + df[\"c_name\"].fillna('')).str.strip()\ndf[\"Gender\"] = df[\"c_female\"].map({0: \"Male\", 1: \"Female\"})\n\n# Keep relevant columns and remove duplicates\nfinal_df = df[[\n    \"c_personid\", \"FullName_CHN\", \"FullName_ENG\",\n    \"c_birthyear\", \"c_deathyear\", \"c_dy\", \"Gender\", \"NativePlace_CHN\"\n]].drop_duplicates()\n\n# Display nicely using the display command instead of print\ndisplay(final_df)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>c_personid</th>\n      <th>FullName_CHN</th>\n      <th>FullName_ENG</th>\n      <th>c_birthyear</th>\n      <th>c_deathyear</th>\n      <th>c_dy</th>\n      <th>Gender</th>\n      <th>NativePlace_CHN</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>3211</td>\n      <td>趙趙廷美</td>\n      <td>Zhao Zhao Tingmei</td>\n      <td>947.0</td>\n      <td>984.0</td>\n      <td>15</td>\n      <td>Male</td>\n      <td>Kaifeng</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>8075</td>\n      <td>李李昉</td>\n      <td>Li Li Fang</td>\n      <td>925.0</td>\n      <td>996.0</td>\n      <td>15</td>\n      <td>Male</td>\n      <td>Kaifeng</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>13059</td>\n      <td>李李淵（唐高祖）</td>\n      <td>Li Li Yuan(Emperor Gaozu of Tang)</td>\n      <td>566.0</td>\n      <td>635.0</td>\n      <td>6</td>\n      <td>Male</td>\n      <td>Chang'an</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>13626</td>\n      <td>李李元懿</td>\n      <td>Li Li Yuanyi</td>\n      <td>0.0</td>\n      <td>0.0</td>\n      <td>6</td>\n      <td>Male</td>\n      <td>Chang'an</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>17267</td>\n      <td>李李沼</td>\n      <td>Li Li Zhao</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>7</td>\n      <td>Male</td>\n      <td>Raoyang</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nNow we have the information on our most key people. The people with the highest degree and eigenvector centrality were Zhao Tingmei and Li Zhao. \n\n[Zhao Tingmei](https://en.wikipedia.org/wiki/Zhao_Tingmei) formally known as Prince Fudao, was an imperial prince of the Song dynasty. He had 15 offspring so it makes sense that he is so integrated into the network. \n\nThe identity of Li Zhao is less clear, but he is most likely [King Li of Zhou](https://en.wikipedia.org/wiki/King_Li_of_Zhou).\n\nAs for our most prominent bridges they are:\n\n* [Li Fang](https://en.wikipedia.org/wiki/Li_Fang_(Song_dynasty))\n* [Li Yuan(Emperor Gaozu of Tang)](https://en.wikipedia.org/wiki/Emperor_Gaozu_of_Tang)\n* Li Yuanyi - We can not find information on them\n\nThis is extremely interesting as we can link all of these nodes to real people from Chinese history. If we are interested in where they are from we can also find that using the dataset. \n\nFor instance Zhao Tingmei and Li Fang are from Kaifeng. Kaifeng is a city in central China’s Henan province, just south of the Yellow River. The city was the Northern Song Dynasty capital from the 10th to 12th centuries.\n\nLi Yuan (Emperor Gaozu of Tang) and Li Yuanyi are from Chang'an. Chang'an was a city in China, located near the modern city of Xi'an, which served as the capital of several Chinese dynasties from 202 BCE to 907 CE. \n\nFinally Li Zhao is from Raoyang, compared to the other two Raoyang is less historically significant region. Raoyang County is a county in the southeast of the Hebei province.\n\n# 4.0 Women more as Bridges\n\nIntuitively from the KINMATRIX dataset we would imagine that women could act as bridges in these large family networks. An example of this would be a strategic marriage, but is this the case? We will look at the data and try to understand if that is the case. \n\nThis cell explores the BIOG_MAIN table structure to find the gender field and loads a sample to understand the data structure. In order to identify if women act as bridges we need the gender information. The variable we are going to use is **c_female,** it is an indicator variable which takes the values of 0 or 1; where 1 means the node is female. \n\nWe will now load the data from before, but with the gender variable and rebuild the network. \n\n::: {#a76e59c2 .cell execution_count=20}\n``` {.python .cell-code}\ndef load_network_data():\n    conn = sqlite3.connect(db_path)\n    \n    # Load kinship relationships\n    kin_df = pd.read_sql_query(\"SELECT c_personid, c_kin_id, c_kin_code FROM KIN_DATA\", conn)\n    print(f\"Loaded {len(kin_df):,} kinship relationships\")\n    \n    # Build network graph\n    G = nx.Graph()\n    for _, row in kin_df.iterrows():\n        person = row['c_personid']\n        kin = row['c_kin_id']\n        kin_type = row['c_kin_code']\n        G.add_edge(person, kin, kinship=kin_type)\n    \n    print(f\"Full network: {G.number_of_nodes():,} nodes, {G.number_of_edges():,} edges\")\n    \n    # Work with largest connected component\n    largest_cc = max(nx.connected_components(G), key=len)\n    G_sub = G.subgraph(largest_cc).copy()\n    print(f\"Largest component: {G_sub.number_of_nodes():,} nodes, {G_sub.number_of_edges():,} edges\")\n    \n    conn.close()\n    return G_sub, kin_df\n\n# Load the network\nG_sub, kin_df = load_network_data()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nLoaded 543,846 kinship relationships\nFull network: 278,262 nodes, 272,717 edges\nLargest component: 52,992 nodes, 65,269 edges\n```\n:::\n:::\n\n\nBecause finding centrality is too computationally intensive the cells will be commented out just like before with their output pasted below. Just like with the men we will find the Betweenness, Closeness and Eigenvector centrality. \n\nInstead of using the whole data we will also be using the largest component of the data which is made up of 52,992 nodes, and 65,269 edges (still very large). \n\n::: {#be617ed6 .cell execution_count=21}\n``` {.python .cell-code}\n#def create_centrality_dataframe(G_sub, degree_centrality, betweenness_centrality, \n#                               closeness_centrality, eigenvector_centrality):\n\n    # Create comprehensive centrality dataframe using your existing variables\n#    analysis_df = pd.DataFrame({\n#        'person_id': list(G_sub.nodes()),\n#        'degree': [G_sub.degree(node) for node in G_sub.nodes()],\n#        'degree_centrality': [degree_centrality[node] for node in G_sub.nodes()],\n#        'betweenness_centrality': [betweenness_centrality[node] for node in G_sub.nodes()],\n#        'closeness_centrality': [closeness_centrality[node] for node in G_sub.nodes()],\n#       'eigenvector_centrality': [eigenvector_centrality[node] for node in G_sub.nodes()]\n#    })\n    \n#    print(f\"Centrality analysis complete for {len(analysis_df):,} individuals\")\n#    print(f\"Average degree: {analysis_df['degree'].mean():.2f}\")\n#    print(f\"Average betweenness centrality: {analysis_df['betweenness_centrality'].mean():.6f}\")\n#    print(f\"Average closeness centrality: {analysis_df['closeness_centrality'].mean():.6f}\")\n#    print(f\"Average eigenvector centrality: {analysis_df['eigenvector_centrality'].mean():.6f}\")\n    \n#    return analysis_df\n\n# Use your existing centrality calculations (no recalculation needed!)\n#centrality_df = create_centrality_dataframe(G_sub, degree_centrality, betweenness_centrality, closeness_centrality, eigenvector_centrality)\n```\n:::\n\n\nCentrality analysis complete for 52,992 individuals:\n\n* Average degree: 2.46\n* Average betweenness centrality: 0.000342\n* Average closeness centrality: 0.054518\n* Average eigenvector centrality: 0.000279\n\nThe next step is to load gender data from the database and add our gender variable:\n\n* Gender field = c_female\n* Birth year field = c_birthyear\n* Death year field = c_deathyear\n* Index year field = c_index_year\n\nWe still need centrality so this cell will also be commented out: \n\n::: {#88669ed0 .cell execution_count=22}\n``` {.python .cell-code}\n#}#def load_and_merge_gender_data(centrality_df, gender_field='c_female'):\n#    \"\"\"Load gender & year data from BIOG_MAIN and merge with centrality_df\"\"\"\n#    conn = sqlite3.connect(db_path)\n\n#    biog_query = f\"\"\"\n#        SELECT \n#            c_personid, \n#            c_name_chn, \n#            c_name,\n#            {gender_field} AS gender,\n#            c_birthyear,\n#            c_deathyear,\n#            c_index_year\n#        FROM BIOG_MAIN\n#        WHERE {gender_field} IS NOT NULL\n#    \"\"\"\n#    biog_df = pd.read_sql_query(biog_query, conn)\n#    conn.close()\n#    print(f\"Loaded {len(biog_df):,} individuals with gender info\")\n#    merged_df = centrality_df.merge(\n#        biog_df[['c_personid', 'gender', 'c_birthyear', 'c_deathyear', 'c_index_year']],\n#        left_on='person_id',\n#        right_on='c_personid',\n#        how='left'\n#    )\n    # Gender distribution\n#    print(\"\\nGender distribution (0=male, 1=female):\")\n#    print(merged_df['gender'].value_counts(dropna=False))\n\n#    coverage = merged_df['gender'].notna().sum() / len(merged_df) * 100\n#    print(f\"Gender data coverage: {coverage:.1f}% of network nodes\")\n\n#    return merged_df\n\n#final_df = load_and_merge_gender_data(centrality_df, gender_field='c_female')\n```\n:::\n\n\n**Output:**\nGender distribution (0=male, 1=female):\n\n* 0    48869\n* 1     4123\n\nGender data coverage: 100.0% of network nodes\n\nWe can see from the output that the majority of nodes are male which is something we saw with the Pyvis visualization. This gender inconsistency makes sense as for historical records they are more likely to record men especially for ones going back to the 7th century. In the largest component we are using only 7.8% of the nodes are female. This might not end up being an issue as it is possible for women to still be stronger bridges except for a few outlier men. We will now look at what percentage of men and women have a betweeneness centrality score over 0.001. \n\n::: {#814dcef6 .cell execution_count=23}\n``` {.python .cell-code}\n#final_df['gender_label'] = final_df['gender'].map({0: 'Male', 1: 'Female'})\n#bridge_thresh = 0.001 #Define a 'bridge' threshold\n\n#female_bridges = final_df[(final_df['gender_label'] == 'Female') & \n#                          (final_df['betweenness_centrality'] > bridge_thresh)]\n#male_bridges = final_df[(final_df['gender_label'] == 'Male') & \n#                        (final_df['betweenness_centrality'] > bridge_thresh)]\n\n#n_female = (final_df['gender_label'] == 'Female').sum()\n#n_male = (final_df['gender_label'] == 'Male').sum()\n\n#prop_female_bridges = len(female_bridges) / n_female * 100 if n_female else 0\n#prop_male_bridges = len(male_bridges) / n_male * 100 if n_male else 0\n\n#print(f\"Females with betweenness > {bridge_thresh}: {len(female_bridges)} / {n_female} ({prop_female_bridges:.2f}%)\")\n#print(f\"Males with betweenness > {bridge_thresh}: {len(male_bridges)} / {n_male} ({prop_male_bridges:.2f}%)\")\n```\n:::\n\n\nOutput:\n\n* Females with betweenness centrality > 0.001: 101 / 4123 (2.45%)\n* Males with betweenness centrality> 0.001: 4452 / 48869 (9.11%)\n\nWe can see that 9.11% percent of men pass our threshold of 0.001 while only 2.45% of women, so most of the main 'bridges' in our dataset are men. We can repeat the analysis with a different betweenness centrality value. \n\n::: {#81ad1966 .cell execution_count=24}\n``` {.python .cell-code}\n#final_df['gender_label'] = final_df['gender'].map({0: 'Male', 1: 'Female'})\n\n#bridge_thresh = 0.01 # Define a 'bridge' threshold \n\n#female_bridges = final_df[(final_df['gender_label'] == 'Female') & \n#                          (final_df['betweenness_centrality'] > bridge_thresh)]\n#male_bridges = final_df[(final_df['gender_label'] == 'Male') & \n#                        (final_df['betweenness_centrality'] > bridge_thresh)]\n\n#n_female = (final_df['gender_label'] == 'Female').sum()\n#n_male = (final_df['gender_label'] == 'Male').sum()\n\n#prop_female_bridges = len(female_bridges) / n_female * 100 if n_female else 0\n#prop_male_bridges = len(male_bridges) / n_male * 100 if n_male else 0\n\n#print(f\"Females with betweenness > {bridge_thresh}: {len(female_bridges)} / {n_female} ({prop_female_bridges:.2f}%)\")\n#print(f\"Males with betweenness > {bridge_thresh}: {len(male_bridges)} / {n_male} ({prop_male_bridges:.2f}%)\")\n```\n:::\n\n\nOutput:\n\n* Females with betweenness centrality > 0.01: 5 / 4123 (0.12%)\n* Males with betweenness centrality > 0.01: 205 / 48869 (0.42%)\n\nIf we up our threshold we can see that this does not change with 0.42% men compared to 0.12% women passing our threshold of 0.01. This means that women in our dataset do not act as bridges more than men. Still let's look at the most prominent female bridges and like with the men link them to real historical figures. \n\n::: {#5ca7c3e8 .cell execution_count=25}\n``` {.python .cell-code}\n#top_female_bridges = final_df[final_df['gender_label'] == 'Female'].nlargest(10, 'betweenness_centrality')\n#print(\"Top 10 Female Bridges in the Network:\")\n#for i, row in top_female_bridges.iterrows():\n#    print(f\"Person {row['person_id']}: Betweenness={row['betweenness_centrality']:.3f}, Degree={row['degree']}\")\n```\n:::\n\n\nTop 10 Female Bridges in the Network:\n\n* Person 141303: Betweenness=0.037, Degree=12\n* Person 93663: Betweenness=0.029, Degree=28\n* Person 17702: Betweenness=0.015, Degree=11\n* Person 142641: Betweenness=0.011, Degree=6\n* Person 140204: Betweenness=0.010, Degree=5\n* Person 4217: Betweenness=0.009, Degree=12\n* Person 141789: Betweenness=0.009, Degree=12\n* Person 194260: Betweenness=0.009, Degree=8\n* Person 134070: Betweenness=0.009, Degree=3\n* Person 141996: Betweenness=0.008, Degree=15\n\nAs with the best male connectors we will continue with the first three and find their real identities. \n\n::: {#4695bda0 .cell execution_count=26}\n``` {.python .cell-code}\nconn = sqlite3.connect(db_path)\n\n# Key people\nkey_women = [141303, 93663, 17702]\n\n# Combined query for biography + native place\nquery = f\"\"\"\nSELECT \n    bm.c_personid,\n    bm.c_name_chn,\n    bm.c_surname_chn,\n    bm.c_name,\n    bm.c_surname,\n    bm.c_birthyear,\n    bm.c_deathyear,\n    bm.c_dy,         -- dynasty code\n    bm.c_female,\n    a.c_name AS NativePlace_CHN\nFROM BIOG_MAIN bm\nLEFT JOIN BIOG_ADDR_DATA bad\n    ON bm.c_personid = bad.c_personid\n    AND bad.c_addr_type = 1\nLEFT JOIN ADDRESSES a\n    ON bad.c_addr_id = a.c_addr_id\nWHERE bm.c_personid IN ({\",\".join(map(str, key_women))})\n\"\"\"\n\n# Read into dataframe\ndf = pd.read_sql_query(query, conn)\n\n# Combine name fields\ndf[\"FullName_CHN\"] = df[\"c_surname_chn\"].fillna('') + df[\"c_name_chn\"].fillna('')\ndf[\"FullName_ENG\"] = (df[\"c_surname\"].fillna('') + \" \" + df[\"c_name\"].fillna('')).str.strip()\ndf[\"Gender\"] = df[\"c_female\"].map({0: \"Male\", 1: \"Female\"})\n\n# Keep relevant columns and remove duplicates\nfinal_df = df[[\n    \"c_personid\", \"FullName_CHN\", \"FullName_ENG\",\n    \"c_birthyear\", \"c_deathyear\", \"c_dy\", \"Gender\", \"NativePlace_CHN\"\n]].drop_duplicates()\n\n# Display nicely\ndisplay(final_df)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>c_personid</th>\n      <th>FullName_CHN</th>\n      <th>FullName_ENG</th>\n      <th>c_birthyear</th>\n      <th>c_deathyear</th>\n      <th>c_dy</th>\n      <th>Gender</th>\n      <th>NativePlace_CHN</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>17702</td>\n      <td>吳吳氏（趙構妻）</td>\n      <td>Wu Wu Shi(Wife of Zhao Gou)</td>\n      <td>1115</td>\n      <td>1199</td>\n      <td>15</td>\n      <td>Female</td>\n      <td>Qiantang</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>93663</td>\n      <td>武武曌（武則天）</td>\n      <td>Wu Wu Zhao(Wu Zetian)</td>\n      <td>624</td>\n      <td>705</td>\n      <td>6</td>\n      <td>Female</td>\n      <td>Wenshui</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>141303</td>\n      <td>崔崔氏(崔庭實女)</td>\n      <td>Cui Cui Shi(Daughter of Cui Ting Shi)</td>\n      <td>725</td>\n      <td>793</td>\n      <td>6</td>\n      <td>Female</td>\n      <td>Qinghe</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nThe top women 'bridges' in our dataset are:\n\n* Wu Shi: who is the wife of [Emperor Gaozong of Song](https://en.wikipedia.org/wiki/Emperor_Gaozong_of_Song). It says that she is from Qiantang which is a river near Shanghai. \n* [Wu Zhao(Wu Zetian)](https://en.wikipedia.org/wiki/Wu_Zetian) who was empress of China from 660 to 705, ruling first through others and later in her own right. She ruled as empress through her husband Emperor Gaozong and later as empress dowager through her sons Emperors Zhongzong and Ruizong, from 660 to 690. She is from Wenshui which is  \"a county in the west-central part of Shanxi Province, China.\" \n* Cui Sui is most likely daughter of [Cui Ting Shi](https://en.wikipedia.org/wiki/Cui_Shi). She is from Qinghe which is \"located in the south of Hebei province, China, bordering Shandong province to the east.\"\n\n# 5.0 Networks over time and Across Dynasties\n\nNext we will look at the dynasties over time and try to determine if there are quantifiable differences between the networks for each of these dynasties. Static network analysis treats all relationships as simultaneous, but historical networks evolve continuously. Temporal analysis helps us understand how social structures change and why. This will be very interesting as this data covers over a thousand years of Chinese history so trying to quantify these changes is a formidable challenge. \n\nTo determine the dynasty we will use the `c_index_year` variable and if that does not exist as a substitute we will use `c_birthyear`. We have repeated this analysis with the `c_dynasty` variable the findings were nearly identical, but the code was more complicated and this solution allowed for more detailed analysis so we have settled on this version.\n\nAgain we will load more data and define our dynasties. The way we will define our dynasties are:\n\n* 618 CE (Tang founding): \n* 907 CE (Tang collapse): \n* 960 CE (Song founding): \n* 1279 CE (Yuan conquest): \n* 1368 CE (Ming founding): \n* 1644 CE (Qing conquest): \n* 1912 CE (Start of modern China): \n\nThese transition years are generally well agreed upon and each transition represents not just a change in rulers, but fundamental shifts in how elite networks formed, maintained themselves, and exercised power. It will be very interesting to see if these changes are noticable in the data. \n\n::: {#9bd21898 .cell execution_count=27}\n``` {.python .cell-code}\nconn = sqlite3.connect(db_path)\nbiog_df = pd.read_sql_query(\"\"\"\n    SELECT c_personid, c_birthyear, c_deathyear, c_index_year\n    FROM BIOG_MAIN\"\"\", conn)\n\ndef assign_dynasty(row):\n    year = row['c_index_year']\n    if year is None:\n        year = row['c_birthyear'] \n    if year is None:\n        return 'Unknown'\n    if 0 <= year <= 618: return 'Pre-Tang'\n    if 618 <= year <= 907: return 'Tang'\n    if 907 < year < 960: return 'Five Dynasties/10 Kingdoms'\n    if 960 <= year <= 1279: return 'Song'\n    if 1279 <= year <= 1368: return 'Yuan'\n    if 1368 <= year <= 1644: return 'Ming'\n    if 1644 <= year <= 1912: return 'Qing'\n    if 1912 <= year <= 2025: return 'Modern'\n    return 'Other'\n\nbiog_df['dynasty'] = biog_df.apply(assign_dynasty, axis=1)\nconn.close()\n\n#uncomment if we want to see sorted by amount\n#print(biog_df['dynasty'].value_counts())\n```\n:::\n\n\n::: {#2c298e45 .cell execution_count=28}\n``` {.python .cell-code}\n#order from before just cleanly defined\ndynasty_order = [\n    'Pre-Tang',\n    'Tang',\n    'Five Dynasties/10 Kingdoms',\n    'Song',\n    'Yuan',\n    'Ming',\n    'Qing',\n    'Modern',\n    'Other'   \n    ]\n\nbiog_df['dynasty'] = pd.Categorical(\n    biog_df['dynasty'],\n    categories=dynasty_order,\n    ordered=True\n)\n\n#Print in order\n#print(biog_df['dynasty'].value_counts(sort=False))\n```\n:::\n\n\nBefore we dive into the preliminary findings it is worth considering why different dynasties might have different network formation and structure. There are many different factors, and an understanding of Chinese history is necessary, but some examples are: \n\n* Family based networks based around royal families like in the Tang Dynasty\n* Networks made around educational achievements like in the Song and Ming Dynasty. \n* Networks made around military structures\n* Lastly fragmented periods like the Five Dynasties and the Warring States Period will be much less cohesive and have lower modularity. \n\nOpen mobility periods produced more diverse networks with varied connection patterns as opposed to closed elite periods where networks were much more exclusive, dense and isolated. \n\nNow we will filter by dynasties and create NetworkX objects for each dynasty using the node and edge variables from before. We will be able to see how many nodes and edges each dynasty has. \n\n::: {#ffa1c942 .cell execution_count=29}\n``` {.python .cell-code}\n# Define custom dynasty order\ndynasty_order = [\n    'Pre-Tang',\n    'Tang',\n    'Five Dynasties/10 Kingdoms',\n    'Song',\n    'Yuan',\n    'Ming',\n    'Qing',\n    'Modern',\n    'Other'\n]\n\n# Load kinship relationships\nconn = sqlite3.connect(db_path)\nkin_df = pd.read_sql_query(\"SELECT c_personid, c_kin_id FROM KIN_DATA\", conn)\nconn.close()\n\n# Merge dynasty info for person and kin\nkin_df = kin_df.merge(\n    biog_df[['c_personid', 'dynasty']],\n    left_on='c_personid', right_on='c_personid',\n    how='left'\n)\nkin_df = kin_df.merge(\n    biog_df[['c_personid', 'dynasty']],\n    left_on='c_kin_id', right_on='c_personid',\n    how='left',\n    suffixes=('_person', '_kin')\n)\n\n# Ensure dynasty columns are ordered categorical\nkin_df['dynasty_person'] = pd.Categorical(\n    kin_df['dynasty_person'],\n    categories=dynasty_order,\n    ordered=True\n)\nkin_df['dynasty_kin'] = pd.Categorical(\n    kin_df['dynasty_kin'],\n    categories=dynasty_order,\n    ordered=True\n)\n\ndef build_dynasty_networks(kin_df):\n    dynasty_graphs = {}\n    for dyn in dynasty_order:\n        if dyn in kin_df['dynasty_person'].values:\n            sub_edges = kin_df[kin_df['dynasty_person'] == dyn]\n            G = nx.Graph()\n            G.add_edges_from(zip(sub_edges['c_personid_person'], sub_edges['c_kin_id']))\n            dynasty_graphs[dyn] = G\n            print(f\"Dynasty {dyn}: {G.number_of_nodes()} nodes, {G.number_of_edges()} edges\")\n    return dynasty_graphs\n\ndynasty_graphs = build_dynasty_networks(kin_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nDynasty Pre-Tang: 13662 nodes, 12375 edges\nDynasty Tang: 45875 nodes, 45684 edges\nDynasty Five Dynasties/10 Kingdoms: 5668 nodes, 5454 edges\nDynasty Song: 36880 nodes, 43952 edges\nDynasty Yuan: 5733 nodes, 5264 edges\nDynasty Ming: 150844 nodes, 139453 edges\nDynasty Qing: 21093 nodes, 18648 edges\nDynasty Modern: 81 nodes, 60 edges\nDynasty Other: 95971 nodes, 71525 edges\n```\n:::\n:::\n\n\nThe output is great, we can see that most of the data has a corresponding dynasty. There is very little modern as the scope of the dataset is from the 7th through the 19th century so this makes sense. We can ignore other, and modern for this analysis.   \n\nNow we will calculate Degree Centrality, Density, Clustering Coefficient, and Modularity for our dynasties. This will serve as the first step towards trying to find differences or similarities between these dynasties. \n\n::: {#90fb2825 .cell execution_count=30}\n``` {.python .cell-code}\n# List of included dynasties in order\nordered_dynasties = [\"Pre-Tang\", \"Tang\", \"Five Dynasties/10 Kingdoms\", \"Song\", \"Yuan\", \"Ming\", \"Qing\"]\n\ndef analyze_dynasty_metrics_selected(dynasty_graphs, ordered_dynasties):\n    results = {}\n    table_data = []\n    for dyn_name in ordered_dynasties:\n        G = dynasty_graphs.get(dyn_name)\n        if G is None:\n            continue\n        # Degree centrality\n        deg_cent = nx.degree_centrality(G)\n        avg_deg_cent = sum(deg_cent.values()) / len(deg_cent)\n\n        # Average degree per node\n        avg_degree = (2 * G.number_of_edges()) / G.number_of_nodes()\n\n        # Graph density\n        density = nx.density(G)\n\n        # Clustering coefficient \n        avg_clust = nx.average_clustering(G)\n\n        # Community detection: modularity\n        communities = list(nx.community.greedy_modularity_communities(G))\n        modularity = nx.community.modularity(G, communities)\n\n        table_data.append([\n            dyn_name,\n            f\"{avg_deg_cent:.6f}\",      \n            f\"{avg_degree:.2f}\",\n            f\"{density:.8f}\",           \n            f\"{avg_clust:.4f}\",\n            f\"{modularity:.4f}\"\n        ])\n\n        results[dyn_name] = {\n            \"avg_degree_centrality\": avg_deg_cent,\n            \"avg_degree\": avg_degree,\n            \"density\": density,\n            \"avg_clustering_coefficient\": avg_clust,\n            \"modularity\": modularity\n        }\n    # Print the table\n    headers = [\"Dynasty\", \"Avg Degree Centrality\", \"Avg Degree\", \"Density\", \"Avg Clust Coeff\", \"Modularity\"]\n    print(tabulate(table_data, headers=headers, tablefmt=\"github\"))\n    return results\n\n# Run the function\ndynasty_metrics_selected = analyze_dynasty_metrics_selected(dynasty_graphs, ordered_dynasties)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n| Dynasty                    |   Avg Degree Centrality |   Avg Degree |    Density |   Avg Clust Coeff |   Modularity |\n|----------------------------|-------------------------|--------------|------------|-------------------|--------------|\n| Pre-Tang                   |                0.000133 |         1.81 | 0.00013261 |            0.0291 |       0.9889 |\n| Tang                       |                4.3e-05  |         1.99 | 4.342e-05  |            0.0708 |       0.9905 |\n| Five Dynasties/10 Kingdoms |                0.00034  |         1.92 | 0.0003396  |            0.0768 |       0.9749 |\n| Song                       |                6.5e-05  |         2.38 | 6.463e-05  |            0.1852 |       0.9634 |\n| Yuan                       |                0.00032  |         1.84 | 0.00032037 |            0.0936 |       0.9929 |\n| Ming                       |                1.2e-05  |         1.85 | 1.226e-05  |            0.0207 |       0.9999 |\n| Qing                       |                8.4e-05  |         1.77 | 8.383e-05  |            0.0753 |       0.9983 |\n```\n:::\n:::\n\n\nFrom findings we see that Degree Centrality and Density are very small these are expected because of the huge size of the network. We also have very high modularity near 1, as expected in a family network there are strong community structures. Song has the highest Average Degree for each node at 2.38 which is far more than the other dynasties.\n\nLet's look deeper as to why the Song Dynasty has such a different Average Degree. There are many factors, but some that stand out are the beginning of civil service examinations which allowed for dense networks of scholar-officials who worked and lived together. The Song dynasty was also a period of economic prosperity which allowed for larger elite populations than previous dynasties. The Song Dynasty also had very well preserved records. \n\nAnother dynasty of note in this analysis is the Yuan Dynasty which was a Mongolian-led imperial dynasty. The moderate connectivity can be indicative of the difficulty of integrating Mongol and Chinese elite networks. \n\nLet's continue with our analysis by looking at the shape of degree distribution throughout our dynasties of interest. \n\n::: {#ca8e8daa .cell execution_count=31}\n``` {.python .cell-code}\ndef analyze_degree_distributions(dynasty_graphs, ordered_dynasties):\n    plt.figure(figsize=(8, 16)) # Adjusted plot size \n    \n    for i, dyn_name in enumerate(ordered_dynasties):\n        G = dynasty_graphs.get(dyn_name)\n        if G is None:\n            continue\n            \n        degrees = [d for n, d in G.degree()]\n        \n        # Plot distribution: Calculate rows needed for max 2 columns\n        num_dynasties = len(ordered_dynasties)\n        rows = (num_dynasties + 1) // 2\n        \n        plt.subplot(rows, 2, i+1) # Set to max 2 images in a row\n        plt.hist(degrees, bins=50, alpha=0.7, color=f'C{i}')\n        plt.title(f'{dyn_name} Degree Distribution')\n        plt.xlabel('Degree')\n        plt.ylabel('Frequency')\n        plt.yscale('log')  # Log scale to see heavy tails\n        \n        # Calculate distribution statistics\n        mean_deg = np.mean(degrees)\n        median_deg = np.median(degrees)\n        max_deg = max(degrees)\n        std_deg = np.std(degrees)\n        skewness = stats.skew(degrees)\n        \n        print(f\"{dyn_name}: Mean={mean_deg:.2f} \"\n              f\"Std={std_deg:.2f}, Skewness={skewness:.2f}\")\n    \n    plt.tight_layout()\n    plt.show()\n\n# Run analysis\nanalyze_degree_distributions(dynasty_graphs, ordered_dynasties)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPre-Tang: Mean=1.81 Std=1.61, Skewness=8.27\nTang: Mean=1.99 Std=2.14, Skewness=6.28\nFive Dynasties/10 Kingdoms: Mean=1.92 Std=3.33, Skewness=19.84\nSong: Mean=2.38 Std=2.70, Skewness=7.35\nYuan: Mean=1.84 Std=2.49, Skewness=8.62\nMing: Mean=1.85 Std=2.72, Skewness=3.91\nQing: Mean=1.77 Std=2.26, Skewness=9.24\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](cbdb_dataset_files/figure-html/cell-32-output-2.png){width=757 height=1526}\n:::\n:::\n\n\nOur visualization is a histogram of the frequency of high degree nodes. The log-scale histograms show the highly skewed nature of our networks - a few individuals with many connections, and many individuals with few connections. All of them are relatively similar except for the Ming Dynasty.\n\nThere are many potential reasons for this, but one that stands out is the Ming Dynasties unique approach to scholar network formation and bureaucratic recruitment, which created a more centralized and hierarchical system compared to other Chinese dynasties. This very selective system created a different social network structure than previous dynasties. The Ming examination system produced a small core of connected scholars and officials who formed the administrative portion of the government. Unlike earlier dynasties where multiple pathways to office existed, the Ming system funneled nearly all political advancement through this single, narrow channel. This single channel was a series of exams which 2-3 million applicants would attempt per year with only about a thousand passing. This process lead to a social network which was more evenly connected than previous or future dynasties.  \n\nWe will continue our analysis with looking at how many components each dynasty has and their fragmentation and average size. \n\n::: {#d55f0372 .cell execution_count=32}\n``` {.python .cell-code}\ndef analyze_connected_components(dynasty_graphs, ordered_dynasties):\n    results = {}\n    \n    for dyn_name in ordered_dynasties:\n        G = dynasty_graphs.get(dyn_name)\n        if G is None:\n            continue\n            \n        # Get connected components\n        components = list(nx.connected_components(G))\n        num_components = len(components)\n        component_sizes = [len(c) for c in components]\n        \n        # Calculate metrics\n        largest_component_size = max(component_sizes) if component_sizes else 0\n        fragmentation_index = 1 - (largest_component_size / G.number_of_nodes())\n        avg_component_size = np.mean(component_sizes) if component_sizes else 0\n        \n        results[dyn_name] = {\n            \"num_components\": num_components,\n            \"largest_component_size\": largest_component_size,\n            \"fragmentation_index\": fragmentation_index,\n            \"avg_component_size\": avg_component_size,\n            \"component_sizes\": component_sizes\n        }\n        \n        print(f\"{dyn_name}: Components={num_components}, \"\n              f\"Largest={largest_component_size}, \"\n              f\"Fragmentation={fragmentation_index:.4f}, \"\n              f\"Avg Size={avg_component_size:.2f}\")\n    \n    return results\n\n# Run analysis\ncomponent_results = analyze_connected_components(dynasty_graphs, ordered_dynasties)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nPre-Tang: Components=1862, Largest=3643, Fragmentation=0.7333, Avg Size=7.34\nTang: Components=4523, Largest=14589, Fragmentation=0.6820, Avg Size=10.14\nFive Dynasties/10 Kingdoms: Components=763, Largest=1337, Fragmentation=0.7641, Avg Size=7.43\nSong: Components=2606, Largest=22388, Fragmentation=0.3930, Avg Size=14.15\nYuan: Components=1191, Largest=277, Fragmentation=0.9517, Avg Size=4.81\nMing: Components=15051, Largest=273, Fragmentation=0.9982, Avg Size=10.02\nQing: Components=4340, Largest=343, Fragmentation=0.9837, Avg Size=4.86\n```\n:::\n:::\n\n\nAs expected the Pre-Tang dynasty is quite disconnected with many smaller clusters. Here the high fragmentation reflects genuine political fragmentation. Multiple competing kingdoms produced separate elite networks with limited inter-kingdom marriages or alliances. The Song dynasty has the lowest fragmentation and the largest component meaning most of the network for this dynasty is one large component. This is inline with history as the dynasty was a period of political unity and economic prosperity. \n\nThe Yuan dynasty is also very fragmented which is surprising as it covered a large political period. As mentioned above this might show that the Mongol and Chinese elites did not merge well and maintained relatively separate networks. Chinese families might have avoided marriages with Mongol elites and vice versa.  \n\nThe Ming dynasty has the most components by far but a minuscule largest connected cluster. This might suggest that the examination system created many small, tight-knit groups rather than one massive interconnected network. This resembles modern professional networks where people have strong connections within their company/specialty but weaker connections across them. In general dynasties before Yuan have quite low fragmentation compared to ones after Yuan. \n\nWe will continue with temporal patterning analysis to see if within these dynasties there were large changes throughout the years. \n\nWe will use the *'c_index_year'* variable to see if density, clustering, or average degree changes over time change inside a dynasty.\n\n::: {#96eb2a98 .cell execution_count=33}\n``` {.python .cell-code}\ndef analyze_temporal_patterns(kin_df, biog_df, ordered_dynasties):\n    # Merge to get information for each edge\n    kin_temporal = kin_df.merge(biog_df[['c_personid', 'c_index_year', 'dynasty']], \n                               left_on='c_personid_person', right_on='c_personid', how='left')\n    \n    results = {}\n    \n    for dyn_name in ordered_dynasties:\n        dyn_data = kin_temporal[kin_temporal['dynasty_person'] == dyn_name].copy()\n        \n        # Group by time periods (for us 50-year bins)\n        if dyn_data['c_index_year'].notna().sum() > 0:\n            min_year = int(dyn_data['c_index_year'].min())\n            max_year = int(dyn_data['c_index_year'].max())\n            bins = range(min_year, max_year + 50, 50)\n            dyn_data['time_bin'] = pd.cut(dyn_data['c_index_year'], bins=bins)\n            \n            # Calculate metrics per time period\n            temporal_metrics = []\n            for time_bin in dyn_data['time_bin'].cat.categories:\n                bin_data = dyn_data[dyn_data['time_bin'] == time_bin]\n                if len(bin_data) > 10:  # Only analyze bins with sufficient data\n                    # Create subgraph for this time period\n                    edges = zip(bin_data['c_personid_person'], bin_data['c_kin_id'])\n                    temp_G = nx.Graph()\n                    temp_G.add_edges_from(edges)\n                    \n                    if temp_G.number_of_nodes() > 0:\n                        avg_deg = (2 * temp_G.number_of_edges()) / temp_G.number_of_nodes()\n                        density = nx.density(temp_G)\n                        clustering = nx.average_clustering(temp_G)\n                        \n                        temporal_metrics.append({\n                            'time_period': str(time_bin),\n                            'avg_degree': avg_deg,\n                            'density': density,\n                            'clustering': clustering,\n                            'nodes': temp_G.number_of_nodes(),\n                            'edges': temp_G.number_of_edges()\n                        })\n            \n            results[dyn_name] = temporal_metrics\n            \n            # Print summary\n            print(f\"\\n{dyn_name} Temporal Analysis ({min_year}-{max_year}):\")\n            for metric in temporal_metrics[:20]:  # Show first 20 time periods\n                print(f\"  {metric['time_period']}: Avg Degree={metric['avg_degree']:.2f}, \"\n                      f\"Density={metric['density']:.6f}, Clustering={metric['clustering']:.4f}\")\n    \n    return results\n\n# Run temporal analysis\ntemporal_results = analyze_temporal_patterns(kin_df, biog_df, ordered_dynasties)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nPre-Tang Temporal Analysis (0-618):\n  (0, 50]: Avg Degree=1.60, Density=0.012476, Clustering=0.0362\n  (50, 100]: Avg Degree=1.69, Density=0.013769, Clustering=0.0447\n  (100, 150]: Avg Degree=1.46, Density=0.036585, Clustering=0.0569\n  (150, 200]: Avg Degree=1.73, Density=0.013841, Clustering=0.0570\n  (200, 250]: Avg Degree=1.73, Density=0.013748, Clustering=0.1200\n  (250, 300]: Avg Degree=1.66, Density=0.010456, Clustering=0.0725\n  (300, 350]: Avg Degree=1.56, Density=0.008824, Clustering=0.0169\n  (350, 400]: Avg Degree=1.56, Density=0.005524, Clustering=0.0161\n  (400, 450]: Avg Degree=1.59, Density=0.002651, Clustering=0.0050\n  (450, 500]: Avg Degree=1.65, Density=0.001212, Clustering=0.0064\n  (500, 550]: Avg Degree=1.67, Density=0.000523, Clustering=0.0131\n  (550, 600]: Avg Degree=1.60, Density=0.000184, Clustering=0.0146\n  (600, 650]: Avg Degree=1.50, Density=0.000325, Clustering=0.0022\n\nTang Temporal Analysis (619-907):\n  (619, 669]: Avg Degree=1.66, Density=0.000108, Clustering=0.0210\n  (669, 719]: Avg Degree=1.68, Density=0.000096, Clustering=0.0282\n  (719, 769]: Avg Degree=1.79, Density=0.000100, Clustering=0.0572\n  (769, 819]: Avg Degree=1.84, Density=0.000116, Clustering=0.0667\n  (819, 869]: Avg Degree=1.67, Density=0.000244, Clustering=0.0362\n  (869, 919]: Avg Degree=1.60, Density=0.000630, Clustering=0.0381\n\nFive Dynasties/10 Kingdoms Temporal Analysis (908-959):\n  (908, 958]: Avg Degree=1.92, Density=0.000350, Clustering=0.0755\n  (958, 1008]: Avg Degree=1.56, Density=0.005524, Clustering=0.0106\n\nSong Temporal Analysis (960-1279):\n  (960, 1010]: Avg Degree=2.08, Density=0.000247, Clustering=0.0856\n  (1010, 1060]: Avg Degree=2.04, Density=0.000175, Clustering=0.1023\n  (1060, 1110]: Avg Degree=1.93, Density=0.000154, Clustering=0.0986\n  (1110, 1160]: Avg Degree=1.98, Density=0.000160, Clustering=0.1434\n  (1160, 1210]: Avg Degree=1.97, Density=0.000206, Clustering=0.2235\n  (1210, 1260]: Avg Degree=1.72, Density=0.000228, Clustering=0.0579\n  (1260, 1310]: Avg Degree=1.76, Density=0.000782, Clustering=0.0985\n\nYuan Temporal Analysis (1280-1368):\n  (1280, 1330]: Avg Degree=1.94, Density=0.000519, Clustering=0.1219\n  (1330, 1380]: Avg Degree=1.59, Density=0.000570, Clustering=0.0221\n\nMing Temporal Analysis (1369-1644):\n  (1369, 1419]: Avg Degree=1.58, Density=0.000085, Clustering=0.0072\n  (1419, 1469]: Avg Degree=1.78, Density=0.000036, Clustering=0.0178\n  (1469, 1519]: Avg Degree=1.76, Density=0.000033, Clustering=0.0154\n  (1519, 1569]: Avg Degree=1.81, Density=0.000037, Clustering=0.0122\n  (1569, 1619]: Avg Degree=1.74, Density=0.000175, Clustering=0.0475\n  (1619, 1669]: Avg Degree=1.66, Density=0.000448, Clustering=0.0685\n\nQing Temporal Analysis (1645-1912):\n  (1645, 1695]: Avg Degree=1.68, Density=0.000312, Clustering=0.0603\n  (1695, 1745]: Avg Degree=1.68, Density=0.000264, Clustering=0.0773\n  (1745, 1795]: Avg Degree=1.63, Density=0.000203, Clustering=0.0589\n  (1795, 1845]: Avg Degree=1.59, Density=0.000203, Clustering=0.0328\n  (1845, 1895]: Avg Degree=1.60, Density=0.000492, Clustering=0.0339\n  (1895, 1945]: Avg Degree=1.43, Density=0.005737, Clustering=0.0133\n```\n:::\n:::\n\n\nThe findings here are quite interesting there seems to be quite a bit of variation inside of the dynasties. By examining 50-year time bins within each dynasty, we can identify common patterns in how elite networks evolve over dynastic lifecycles: \n\n* Pre-Tang: The clustering increases through the years which makes sense as this was a very politically divided period. Increasing clustering over time suggests gradual consolidation of initially fragmented regional elites. As political stability increased, families had more opportunities to form alliances.\n* Tang: The average degree is quite stable with a slight spike in the middle. Clustering gradually increases from very low (0.0210) to peak at mid-period (0.0667), then drops similar to average degree. The mid-dynasty clustering peak followed by decline mirrors the Tang's historical trajectory. An early expansion and consolidation, followed by the An Lushan Rebellion (755 CE) and subsequent fragmentation. Our network metrics capture this political crisis.\n* Five Dynasties/10 Kingdoms Temporal Analysis: Large drop in Average Degree, with a very large decrease in clustering from (0.0755 to 0.0106). This is a period marked by political instability, elite networks could not be maintained like in times of unity. \n* Song: Late Song becomes more clustered and somewhat denser compared to early Song. Late Song's increased clustering and density reflects the dynasty's successful institutional consolidation; the networks strengthening might reflect the examination system maturing and functioning better and better. \n* Yuan: Large drop in average degree (1.94 to 1.59) and large decrease in clustering (0.1219 to 0.0221). The sharp decline from early to late Yuan suggests that initial Mongol-Chinese elite integration failed to sustain itself.\n* Ming: Very stable compared to other dynasties.  Remarkably stable metrics across time reflect the dynasty's successful institutional design. The examination system created consistent network formation patterns that persisted across centuries. This is extremely impressive. \n* Qing: Early Qing is more cohesive than late Qing except for a late density spike that is not accompanied by clustering. The final density spike without clustering increase might reflect desperate attempts to maintain connections during political crisis, but this might be more speculation. \n\nThese patterns demonstrate that political institutions profoundly shape social network evolution. Stable, examination-based systems (Song and Ming) produced networks that strengthened over time. Conquest dynasties faced ongoing integration challenges. Fragmented periods prevented stable network formation entirely. We can accurately look at the course of Chinese history through these network metrics. Not only is each node a specific individual, but the bigger picture is also present. \n\n# 6.0 Conclusion\n\nWe have successfully been able to characterize Chinese history and some very influential figures using the CBDB Dataset. We have looked at more both individuals and broader patterns across dynasties and centuries and most importantly been able to link these findings to real Chinese History. The techniques and elements used in this notebook demonstrate how large-scale network analysis methods can be used to uncover meaningful patterns in complex historical and social data through approaches such as community detection, centrality metrics, and temporal segmentation, we gained deeper insight into how elite families, political dynasties, and social roles shaped the connectivity and structure of networks over centuries.   \n\nOverall, network analysis provides powerful quantitative tools for looking at small scale relationships and general social structures. Whether applied to history, sociology (family networks), or other disciplines, the combination of network modeling and real life context allows researchers to ask better questions about how social systems function and evolve. The process is iterative; findings prompt new questions, methodologies improve, and insights deepen as data and theory interact. We hope that using a realistic dataset and asking difficult questions without clear answers can inspire some students to pursue and utilize network analysis in research to tackle these kinds of problems. \n\n# 7.0 Citations\n\n::: {style=\"padding-left: 2em; text-indent: -2em;\"}\nAl-Taie, M. Z., & Kadry, S. (2017). *Python for graph and network analysis*. Springer. https://doi.org/10.1007/978-3-319-53004-8\n\nCartwright, Mark. \"The Civil Service Examinations of Imperial China.\" World History Encyclopedia, https://www.worldhistory.org#organization, 15 Aug. 2025, www.worldhistory.org/article/1335/the-civil-service-examinations-of-imperial-china/.\n\n\"Chang’an.\" Wikipedia, Wikimedia Foundation, 10 Aug. 2025, en.wikipedia.org/wiki/Chang%27an.\n\n\"China Biographical Database Project (CBDB)\". Home, Harvard, 2024, projects.iq.harvard.edu/cbdb/home.\n\n\"The China Biographical Database User’s Guide\". The China Biographical Database, Harvard, 26 July 2024, projects.iq.harvard.edu/sites/projects.iq.harvard.edu/files/cbdb/files/cbdb_users_guide.pdf.\n\n\"Cui Shi.\" Wikipedia, Wikimedia Foundation, 18 July 2025, en.wikipedia.org/wiki/Cui_Shi.\n\n\"Dynasties of China.\" Wikipedia, Wikimedia Foundation, 27 July 2025, en.wikipedia.org/wiki/Dynasties_of_China.\n\n\"Emperor Gaozong of Song\". Wikipedia, Wikimedia Foundation, 18 July 2025, en.wikipedia.org/wiki/Emperor_Gaozong_of_Song.\n\n\"Emperor Gaozu of Tang\". Wikipedia, Wikimedia Foundation, 2 Aug. 2025, en.wikipedia.org/wiki/Emperor_Gaozu_of_Tang.\n\n\"Kaifeng\". Wikipedia, Wikimedia Foundation, 11 Aug. 2025, en.wikipedia.org/wiki/Kaifeng.\n\n\"King Li of Zhou\". Wikipedia, Wikimedia Foundation, 20 July 2025, en.wikipedia.org/wiki/King_Li_of_Zhou.\n\n\"Li Fang (Song Dynasty).\" Wikipedia, Wikimedia Foundation, 27 May 2025, en.wikipedia.org/wiki/Li_Fang_(Song_dynasty).\n\n\"Ming Dynasty\". Encyclopedia Britannica, Encyclopedia Britannica, inc., 31 July 2025, www.britannica.com/topic/Ming-dynasty-Chinese-history.\n\n\"Qiantang River.\" Wikipedia, Wikimedia Foundation, 23 July 2025, en.wikipedia.org/wiki/Qiantang_River.\n\n\"Qinghe County, Hebei.\" Wikipedia, Wikimedia Foundation, 2 Aug. 2025, en.wikipedia.org/wiki/Qinghe_County,_Hebei.\n\n\"Raoyang County.\" Wikipedia, Wikimedia Foundation, 28 Feb. 2025, en.wikipedia.org/wiki/Raoyang_County.\n\n\"Song Dynasty.\" Encyclopedia Britannica, Encyclopædia Britannica, inc., 17 July 2025, www.britannica.com/topic/Song-dynasty.\n\n\"Tang Dynasty.\" Encyclopedia Britannica, Encyclopædia Britannica, inc., 19 July 2025, www.britannica.com/topic/Tang-dynasty.\n\n\"Wenshui County.\" Wikipedia, Wikimedia Foundation, 12 Aug. 2024, en.wikipedia.org/wiki/Wenshui_County.\n\n\"Wu Zetian.\" Wikipedia, Wikimedia Foundation, 10 Aug. 2025, en.wikipedia.org/wiki/Wu_Zetian.\n\n\"Zhao Tingmei.\" Wikipedia, Wikimedia Foundation, 10 Feb. 2025, en.wikipedia.org/wiki/Zhao_Tingmei.\n:::\n\n",
    "supporting": [
      "cbdb_dataset_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}